export * from './consents.controller';
export * from './hipaa-authorizations.controller';
export * from './patient-objections.controller';
export * from './privacy-restrictions.controller';
export * from './processing-legal-bases.controller';
export * from './treatment-informed-consents.controller';
export * from './consent-evidence.controller';
export * from './consent-sweep.controller';
export * from './practitioner-access-requests.controller';
