export {
  CreateAccountDto,
  AccountResponseDto,
  AddTeamMemberDto,
  TeamMemberResponseDto,
  CreateLeadDto,
  QualifyLeadDto,
  LeadResponseDto,
  ConvertLeadDto,
  ConvertLeadResponseDto,
  CreateActivityDto,
  ActivityResponseDto,
  AdvanceStageDto,
  LoseOpportunityDto,
  OpportunityResponseDto,
  CreatePartnershipDto,
  PartnershipResponseDto,
  CreateCaseDto,
  CaseResponseDto,
  AddCaseCommentDto,
  ChangeCaseStatusDto,
  CaseStatusResponseDto,
  ChannelOptInDto,
  ChannelOptInResponseDto,
  Account360ResponseDto,
  ACCOUNT_TYPES,
  ACTIVITY_TYPES,
} from './crm.dto';
export type {
  AccountType,
  LeadSource,
  ActivityType,
  ActivitySubject,
} from './crm.dto';
