/**
 * Sub-códigos de negocio estables del módulo `procedures_perioperative`.
 *
 * Van en el 3er argumento (`reason`) de `DomainException` y sus subclases,
 * nunca reemplazan al `details` (2º argumento). Un cliente puede ramificar
 * sobre `reason` sin parsear `message`.
 */
export enum ProceduresPerioperativeErrorReason {
  // --- Caso quirúrgico: existencia y estado ---
  CASE_NOT_FOUND = 'CASE_NOT_FOUND',
  CASE_CANCELLED = 'CASE_CANCELLED',
  CASE_ALREADY_CANCELLED = 'CASE_ALREADY_CANCELLED',
  CASE_NOT_IN_PROGRESS = 'CASE_NOT_IN_PROGRESS',
  CASE_NOT_CONFIRMABLE_IN_CURRENT_STATE = 'CASE_NOT_CONFIRMABLE_IN_CURRENT_STATE',
  CASE_NOT_CANCELLABLE_IN_CURRENT_STATE = 'CASE_NOT_CANCELLABLE_IN_CURRENT_STATE',
  CASE_NUMBER_ALLOCATION_FAILED = 'CASE_NUMBER_ALLOCATION_FAILED',

  // --- Programación y quirófano ---
  SCHEDULE_END_BEFORE_START = 'SCHEDULE_END_BEFORE_START',
  URGENCY_REASON_REQUIRED = 'URGENCY_REASON_REQUIRED',
  OPERATING_ROOM_SLOT_CONFLICT = 'OPERATING_ROOM_SLOT_CONFLICT',

  // --- Modificación del caso (CAN-INT-001) ---
  PATIENT_CHANGE_NOT_ALLOWED_AFTER_CONFIRMATION = 'PATIENT_CHANGE_NOT_ALLOWED_AFTER_CONFIRMATION',
  PATIENT_CHANGE_BLOCKED_BY_DEPENDENCIES = 'PATIENT_CHANGE_BLOCKED_BY_DEPENDENCIES',

  // --- Diagnósticos ---
  MULTIPLE_PRIMARY_DIAGNOSES_NOT_ALLOWED = 'MULTIPLE_PRIMARY_DIAGNOSES_NOT_ALLOWED',
  CONDITION_REFERENCE_REQUIRED = 'CONDITION_REFERENCE_REQUIRED',

  // --- Equipo quirúrgico (CAN-INT-002) ---
  TEAM_MEMBER_WITHOUT_CURRENT_CREDENTIAL = 'TEAM_MEMBER_WITHOUT_CURRENT_CREDENTIAL',
  TEAM_MEMBER_ROLE_ALREADY_ASSIGNED = 'TEAM_MEMBER_ROLE_ALREADY_ASSIGNED',
  TEAM_MEMBER_NOT_IN_CASE = 'TEAM_MEMBER_NOT_IN_CASE',
  TEAM_MEMBER_SELF_ACTION_REQUIRED = 'TEAM_MEMBER_SELF_ACTION_REQUIRED',

  // --- Cargos y facturación del caso ---
  CHARGES_REQUIRE_COMPLETED_CASE = 'CHARGES_REQUIRE_COMPLETED_CASE',
  CHARGES_ALREADY_POSTED = 'CHARGES_ALREADY_POSTED',

  // --- Pasos operatorios y reporte intraoperatorio ---
  OPERATIVE_STEP_NOT_FOUND = 'OPERATIVE_STEP_NOT_FOUND',
  STEP_NOT_IN_CASE = 'STEP_NOT_IN_CASE',
  PROCEDURE_REFERENCE_REQUIRED = 'PROCEDURE_REFERENCE_REQUIRED',
  REPORT_NOT_FOUND = 'REPORT_NOT_FOUND',
  REPORT_BELONGS_TO_ANOTHER_CASE = 'REPORT_BELONGS_TO_ANOTHER_CASE',
  REPORT_ALREADY_SIGNED = 'REPORT_ALREADY_SIGNED',

  // --- Recuperación (PACU) ---
  PACU_STAY_ALREADY_EXISTS = 'PACU_STAY_ALREADY_EXISTS',
  PACU_STAY_NOT_FOUND = 'PACU_STAY_NOT_FOUND',
  PACU_ALREADY_DISCHARGED = 'PACU_ALREADY_DISCHARGED',
  PACU_DISCHARGE_REQUIRES_ASSESSMENT = 'PACU_DISCHARGE_REQUIRES_ASSESSMENT',
  PACU_DISCHARGE_CRITERIA_NOT_MET = 'PACU_DISCHARGE_CRITERIA_NOT_MET',

  // --- Órdenes y valoración preoperatoria ---
  SERVICE_REQUEST_REFERENCE_REQUIRED = 'SERVICE_REQUEST_REFERENCE_REQUIRED',
  ASSESSMENT_REQUIRES_ALLERGY_AND_MEDICATION_REVIEW = 'ASSESSMENT_REQUIRES_ALLERGY_AND_MEDICATION_REVIEW',
  ASSESSMENT_ALREADY_EXISTS = 'ASSESSMENT_ALREADY_EXISTS',
  ORDERS_VERIFICATION_REQUIRES_SCHEDULED_CASE = 'ORDERS_VERIFICATION_REQUIRES_SCHEDULED_CASE',
  PREOP_ORDER_NOT_IN_CASE = 'PREOP_ORDER_NOT_IN_CASE',

  // --- Checklist de seguridad quirúrgica ---
  CHECKLIST_EXCEPTION_REQUIRES_REASON = 'CHECKLIST_EXCEPTION_REQUIRES_REASON',
  CHECKLIST_NOT_FOUND = 'CHECKLIST_NOT_FOUND',
  CHECKLIST_BELONGS_TO_ANOTHER_CASE = 'CHECKLIST_BELONGS_TO_ANOTHER_CASE',
  CHECKLIST_ALREADY_COMPLETED = 'CHECKLIST_ALREADY_COMPLETED',
  CHECKLIST_PHASE_ALREADY_COMPLETED = 'CHECKLIST_PHASE_ALREADY_COMPLETED',
  CHECKLIST_PHASE_HAS_NO_ITEMS = 'CHECKLIST_PHASE_HAS_NO_ITEMS',
  CHECKLIST_ITEM_NOT_IN_PHASE = 'CHECKLIST_ITEM_NOT_IN_PHASE',

  // --- Anestesia ---
  DIFFICULT_AIRWAY_REQUIRES_RESCUE_PLAN = 'DIFFICULT_AIRWAY_REQUIRES_RESCUE_PLAN',
  ANESTHESIA_PLAN_ALREADY_EXISTS = 'ANESTHESIA_PLAN_ALREADY_EXISTS',
  ANESTHESIA_PLAN_NOT_FOUND = 'ANESTHESIA_PLAN_NOT_FOUND',
  ANESTHESIA_PLAN_BELONGS_TO_ANOTHER_CASE = 'ANESTHESIA_PLAN_BELONGS_TO_ANOTHER_CASE',
  ANESTHESIA_PLAN_ALREADY_APPROVED = 'ANESTHESIA_PLAN_ALREADY_APPROVED',
  INDUCTION_REQUIRES_APPROVED_ANESTHESIA_PLAN = 'INDUCTION_REQUIRES_APPROVED_ANESTHESIA_PLAN',

  // --- Histórico odontológico ---
  INVALID_DENTAL_SITE = 'INVALID_DENTAL_SITE',
  SITE_DETAIL_REQUIRES_TOOTH_SITE = 'SITE_DETAIL_REQUIRES_TOOTH_SITE',
}
