import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `accounting` (parte 2/2).
 * 167 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const accountingIndexes2: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['fiscal_periods', 'ix_fiscal_periods_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['fiscal_periods', 'ix_fiscal_periods_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['fiscal_periods', 'ix_fiscal_periods_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['fiscal_years', 'ix_fiscal_years_practice_id', ['practice_id'], false, 'btree'],
  ['fiscal_years', 'ix_fiscal_years_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['fiscal_years', 'ix_fiscal_years_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['fiscal_years', 'ix_fiscal_years_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['functional_areas', 'uq_functional_areas_tenant_id_code', ['tenant_id', 'code'], true, 'btree'],
  ['functional_areas', 'ix_functional_areas_tenant_id', ['tenant_id'], false, 'btree'],
  ['functional_areas', 'ix_functional_areas_parent_functional_area_id', ['parent_functional_area_id'], false, 'btree'],
  ['functional_areas', 'ix_functional_areas_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['functional_areas', 'ix_functional_areas_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['functional_areas', 'ix_functional_areas_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['infrastructure_items', 'ix_infrastructure_items_practice_id', ['practice_id'], false, 'btree'],
  ['infrastructure_items', 'ix_infrastructure_items_category_concept_id', ['category_concept_id'], false, 'btree'],
  ['infrastructure_items', 'ix_infrastructure_items_asset_id', ['asset_id'], false, 'btree'],
  ['infrastructure_items', 'ix_infrastructure_items_branch_id', ['branch_id'], false, 'btree'],
  ['infrastructure_items', 'ix_infrastructure_items_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['infrastructure_items', 'ix_infrastructure_items_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['infrastructure_items', 'ix_infrastructure_items_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['internal_orders', 'uq_internal_orders_tenant_id_order_number', ['tenant_id', 'order_number'], true, 'btree'],
  ['internal_orders', 'ix_internal_orders_controlling_area_id', ['controlling_area_id'], false, 'btree'],
  ['internal_orders', 'ix_internal_orders_tenant_id', ['tenant_id'], false, 'btree'],
  ['internal_orders', 'ix_internal_orders_order_type_concept_id', ['order_type_concept_id'], false, 'btree'],
  ['internal_orders', 'ix_internal_orders_responsible_cost_center_id', ['responsible_cost_center_id'], false, 'btree'],
  ['internal_orders', 'ix_internal_orders_responsible_profit_center_id', ['responsible_profit_center_id'], false, 'btree'],
  ['internal_orders', 'ix_internal_orders_project_id', ['project_id'], false, 'btree'],
  ['internal_orders', 'ix_internal_orders_wbs_element_id', ['wbs_element_id'], false, 'btree'],
  ['internal_orders', 'ix_internal_orders_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['internal_orders', 'ix_internal_orders_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['internal_orders', 'ix_internal_orders_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['internal_orders', 'ix_internal_orders_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['internal_orders', 'ix_internal_orders_tenant_status_updated', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['journal_entry_assignments', 'uq_journal_entry_assignments_ledger_entry_id', ['ledger_entry_id'], true, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_ledger_entry_id', ['ledger_entry_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_branch_id', ['branch_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_department_id', ['department_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_cost_center_id', ['cost_center_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_profit_center_id', ['profit_center_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_functional_area_id', ['functional_area_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_segment_id', ['segment_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_internal_order_id', ['internal_order_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_project_id', ['project_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_wbs_element_id', ['wbs_element_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_business_partner_id', ['business_partner_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_subledger_account_id', ['subledger_account_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_asset_id', ['asset_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_asset_component_id', ['asset_component_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_liability_id', ['liability_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_contract_id', ['contract_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_invoice_id', ['invoice_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_bill_id', ['bill_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_purchase_order_item_id', ['purchase_order_item_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_goods_receipt_item_id', ['goods_receipt_item_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_sales_order_item_id', ['sales_order_item_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_payment_transaction_id', ['payment_transaction_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_company_bank_account_id', ['company_bank_account_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_employee_id', ['employee_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_assignment_source_concept_id', ['assignment_source_concept_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_derived_by_rule_id', ['derived_by_rule_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_business_partner_line', ['business_partner_id', 'ledger_entry_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_asset_line', ['asset_id', 'ledger_entry_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_liability_line', ['liability_id', 'ledger_entry_id'], false, 'btree'],
  ['journal_entry_assignments', 'ix_journal_entry_assignments_contract_line', ['contract_id', 'ledger_entry_id'], false, 'btree'],
  ['journal_transactions', 'uq_journal_transactions_transaction_number', ['transaction_number'], true, 'btree'],
  ['journal_transactions', 'ix_journal_transactions_practice_id', ['practice_id'], false, 'btree'],
  ['journal_transactions', 'ix_journal_transactions_transaction_type_concept_id', ['transaction_type_concept_id'], false, 'btree'],
  ['journal_transactions', 'ix_journal_transactions_fiscal_period_id', ['fiscal_period_id'], false, 'btree'],
  ['journal_transactions', 'ix_journal_transactions_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['journal_transactions', 'ix_journal_transactions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['journal_transactions', 'ix_journal_transactions_posted_by_user_id', ['posted_by_user_id'], false, 'btree'],
  ['journal_transactions', 'ix_journal_transactions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['journal_transactions', 'ix_journal_transactions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['ledger_entries', 'ix_ledger_entries_transaction_id', ['transaction_id'], false, 'btree'],
  ['ledger_entries', 'ix_ledger_entries_account_id', ['account_id'], false, 'btree'],
  ['ledger_entries', 'ix_ledger_entries_cost_center_id', ['cost_center_id'], false, 'btree'],
  ['ledger_entries', 'ix_ledger_entries_direction_concept_id', ['direction_concept_id'], false, 'btree'],
  ['ledger_entries', 'ix_ledger_entries_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['ledger_entries', 'ix_ledger_entries_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['ledger_entries', 'ix_ledger_entries_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['liabilities', 'ix_liabilities_practice_id', ['practice_id'], false, 'btree'],
  ['liabilities', 'ix_liabilities_liability_type_concept_id', ['liability_type_concept_id'], false, 'btree'],
  ['liabilities', 'ix_liabilities_account_id', ['account_id'], false, 'btree'],
  ['liabilities', 'ix_liabilities_practice_id_account_id', ['practice_id', 'account_id', 'status_concept_id'], false, 'btree'],
  ['liabilities', 'ix_liabilities_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['liabilities', 'ix_liabilities_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['liabilities', 'ix_liabilities_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['liability_payments', 'ix_liability_payments_liability_id', ['liability_id'], false, 'btree'],
  ['liability_payments', 'ix_liability_payments_transaction_id', ['transaction_id'], false, 'btree'],
  ['liability_payments', 'ix_liability_payments_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['liability_payments', 'ix_liability_payments_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['liability_postings', 'ix_liability_postings_liability_id', ['liability_id'], false, 'btree'],
  ['liability_postings', 'ix_liability_postings_liability_schedule_id', ['liability_schedule_id'], false, 'btree'],
  ['liability_postings', 'ix_liability_postings_ledger_entry_id', ['ledger_entry_id'], false, 'btree'],
  ['liability_postings', 'ix_liability_postings_component_concept_id', ['component_concept_id'], false, 'btree'],
  ['liability_postings', 'ix_liability_postings_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['liability_postings', 'ix_liability_postings_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['liability_postings', 'ix_liability_postings_liability_effective', ['liability_id', 'effective_date'], false, 'btree'],
  ['liability_postings', 'ix_liability_postings_ledger_liability', ['ledger_entry_id', 'liability_id'], false, 'btree'],
  ['liability_postings', 'brin_liability_postings_created_at', ['created_at'], false, 'brin'],
  ['liability_schedules', 'uq_liability_schedules_liability_id_installment_number', ['liability_id', 'installment_number'], true, 'btree'],
  ['liability_schedules', 'ix_liability_schedules_liability_id', ['liability_id'], false, 'btree'],
  ['liability_schedules', 'ix_liability_schedules_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['liability_schedules', 'ix_liability_schedules_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['liability_schedules', 'ix_liability_schedules_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['liability_schedules', 'ix_liability_schedules_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['liability_schedules', 'ix_liability_schedules_liability_status_due', ['liability_id', 'status_concept_id', 'due_date'], false, 'btree'],
  ['open_items', 'ix_open_items_tenant_id', ['tenant_id'], false, 'btree'],
  ['open_items', 'ix_open_items_subledger_account_id', ['subledger_account_id'], false, 'btree'],
  ['open_items', 'ix_open_items_ledger_entry_id', ['ledger_entry_id'], false, 'btree'],
  ['open_items', 'ix_open_items_document_type_concept_id', ['document_type_concept_id'], false, 'btree'],
  ['open_items', 'ix_open_items_invoice_id', ['invoice_id'], false, 'btree'],
  ['open_items', 'ix_open_items_bill_id', ['bill_id'], false, 'btree'],
  ['open_items', 'ix_open_items_contract_id', ['contract_id'], false, 'btree'],
  ['open_items', 'ix_open_items_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['open_items', 'ix_open_items_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['open_items', 'ix_open_items_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['open_items', 'ix_open_items_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['open_items', 'ix_open_items_tenant_status_due', ['tenant_id', 'status_concept_id', 'due_date'], false, 'btree'],
  ['open_items', 'ix_open_items_subledger_status_due', ['subledger_account_id', 'status_concept_id', 'due_date'], false, 'btree'],
  ['profit_centers', 'uq_profit_centers_tenant_id_code', ['tenant_id', 'code'], true, 'btree'],
  ['profit_centers', 'ix_profit_centers_controlling_area_id', ['controlling_area_id'], false, 'btree'],
  ['profit_centers', 'ix_profit_centers_tenant_id', ['tenant_id'], false, 'btree'],
  ['profit_centers', 'ix_profit_centers_parent_profit_center_id', ['parent_profit_center_id'], false, 'btree'],
  ['profit_centers', 'ix_profit_centers_segment_id', ['segment_id'], false, 'btree'],
  ['profit_centers', 'ix_profit_centers_responsible_employee_id', ['responsible_employee_id'], false, 'btree'],
  ['profit_centers', 'ix_profit_centers_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['profit_centers', 'ix_profit_centers_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['profit_centers', 'ix_profit_centers_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['purchases', 'ix_purchases_practice_id', ['practice_id'], false, 'btree'],
  ['purchases', 'ix_purchases_transaction_id', ['transaction_id'], false, 'btree'],
  ['purchases', 'ix_purchases_vendor_id', ['vendor_id'], false, 'btree'],
  ['purchases', 'ix_purchases_bill_id', ['bill_id'], false, 'btree'],
  ['purchases', 'ix_purchases_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['purchases', 'ix_purchases_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['purchases', 'ix_purchases_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['sales', 'ix_sales_practice_id', ['practice_id'], false, 'btree'],
  ['sales', 'ix_sales_transaction_id', ['transaction_id'], false, 'btree'],
  ['sales', 'ix_sales_customer_type_concept_id', ['customer_type_concept_id'], false, 'btree'],
  ['sales', 'ix_sales_invoice_id', ['invoice_id'], false, 'btree'],
  ['sales', 'ix_sales_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['sales', 'ix_sales_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['sales', 'ix_sales_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['segments', 'uq_segments_tenant_id_code', ['tenant_id', 'code'], true, 'btree'],
  ['segments', 'ix_segments_tenant_id', ['tenant_id'], false, 'btree'],
  ['segments', 'ix_segments_parent_segment_id', ['parent_segment_id'], false, 'btree'],
  ['segments', 'ix_segments_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['segments', 'ix_segments_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['segments', 'ix_segments_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['subledger_accounts', 'uq_subledger_accounts_tenant_id_business_partner_id_su_8a871de6', ['tenant_id', 'business_partner_id', 'subledger_role_concept_id'], true, 'btree'],
  ['subledger_accounts', 'ix_subledger_accounts_tenant_id', ['tenant_id'], false, 'btree'],
  ['subledger_accounts', 'ix_subledger_accounts_business_partner_id', ['business_partner_id'], false, 'btree'],
  ['subledger_accounts', 'ix_subledger_accounts_subledger_role_concept_id', ['subledger_role_concept_id'], false, 'btree'],
  ['subledger_accounts', 'ix_subledger_accounts_reconciliation_account_id', ['reconciliation_account_id'], false, 'btree'],
  ['subledger_accounts', 'ix_subledger_accounts_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['subledger_accounts', 'ix_subledger_accounts_payment_terms_concept_id', ['payment_terms_concept_id'], false, 'btree'],
  ['subledger_accounts', 'ix_subledger_accounts_dunning_procedure_concept_id', ['dunning_procedure_concept_id'], false, 'btree'],
  ['subledger_accounts', 'ix_subledger_accounts_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['subledger_accounts', 'ix_subledger_accounts_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['subledger_accounts', 'ix_subledger_accounts_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['subledger_accounts', 'ix_subledger_accounts_tenant_status', ['tenant_id', 'status_concept_id'], false, 'btree'],
  ['transaction_files', 'ix_transaction_files_transaction_id', ['transaction_id'], false, 'btree'],
  ['transaction_files', 'ix_transaction_files_file_id', ['file_id'], false, 'btree'],
  ['transaction_files', 'ix_transaction_files_category_concept_id', ['category_concept_id'], false, 'btree'],
  ['transaction_files', 'ix_transaction_files_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['transaction_files', 'ix_transaction_files_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
];
