import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `accounting` (parte 1/2).
 * 180 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const accountingIndexes1: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['accounting_document_links', 'uq_accounting_document_links_source_transaction_id_tar_c5560530', ['source_transaction_id', 'target_transaction_id', 'relation_type_concept_id'], true, 'btree'],
  ['accounting_document_links', 'ix_accounting_document_links_source_transaction_id', ['source_transaction_id'], false, 'btree'],
  ['accounting_document_links', 'ix_accounting_document_links_target_transaction_id', ['target_transaction_id'], false, 'btree'],
  ['accounting_document_links', 'ix_accounting_document_links_relation_type_concept_id', ['relation_type_concept_id'], false, 'btree'],
  ['accounting_document_links', 'ix_accounting_document_links_source_line_id', ['source_line_id'], false, 'btree'],
  ['accounting_document_links', 'ix_accounting_document_links_target_line_id', ['target_line_id'], false, 'btree'],
  ['accounting_document_links', 'ix_accounting_document_links_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['accounting_document_links', 'ix_accounting_document_links_target_relation', ['target_transaction_id', 'relation_type_concept_id'], false, 'btree'],
  ['accounts', 'ix_accounts_practice_id', ['practice_id'], false, 'btree'],
  ['accounts', 'ix_accounts_account_group_id', ['account_group_id'], false, 'btree'],
  ['accounts', 'ix_accounts_account_type_concept_id', ['account_type_concept_id'], false, 'btree'],
  ['accounts', 'ix_accounts_normal_balance_concept_id', ['normal_balance_concept_id'], false, 'btree'],
  ['accounts', 'ix_accounts_parent_account_id', ['parent_account_id'], false, 'btree'],
  ['accounts', 'ix_accounts_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['accounts', 'ix_accounts_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['accounts', 'ix_accounts_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['accounts', 'ix_accounts_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['account_determination_rules', 'ix_account_determination_rules_tenant_id', ['tenant_id'], false, 'btree'],
  ['account_determination_rules', 'ix_account_determination_rules_posting_scenario_concept_id', ['posting_scenario_concept_id'], false, 'btree'],
  ['account_determination_rules', 'ix_account_determination_rules_account_role_concept_id', ['account_role_concept_id'], false, 'btree'],
  ['account_determination_rules', 'ix_account_determination_rules_source_type_concept_id', ['source_type_concept_id'], false, 'btree'],
  ['account_determination_rules', 'ix_account_determination_rules_asset_class_id', ['asset_class_id'], false, 'btree'],
  ['account_determination_rules', 'ix_account_determination_rules_liability_type_concept_id', ['liability_type_concept_id'], false, 'btree'],
  ['account_determination_rules', 'ix_account_determination_rules_contract_type_concept_id', ['contract_type_concept_id'], false, 'btree'],
  ['account_determination_rules', 'ix_account_determination_rules_tax_code_id', ['tax_code_id'], false, 'btree'],
  ['account_determination_rules', 'ix_account_determination_rules_service_concept_id', ['service_concept_id'], false, 'btree'],
  ['account_determination_rules', 'ix_account_determination_rules_target_account_id', ['target_account_id'], false, 'btree'],
  ['account_determination_rules', 'ix_account_determination_rules_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['account_determination_rules', 'ix_account_determination_rules_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['account_determination_rules', 'ix_account_determination_rules_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['account_determination_rules', 'ix_account_determination_rules_tenant_scenario_priority', ['tenant_id', 'posting_scenario_concept_id', 'priority'], false, 'btree'],
  ['account_groups', 'ix_account_groups_practice_id', ['practice_id'], false, 'btree'],
  ['account_groups', 'ix_account_groups_parent_group_id', ['parent_group_id'], false, 'btree'],
  ['account_groups', 'ix_account_groups_account_type_concept_id', ['account_type_concept_id'], false, 'btree'],
  ['account_groups', 'ix_account_groups_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['account_groups', 'ix_account_groups_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['accrual_objects', 'uq_accrual_objects_tenant_id_object_number', ['tenant_id', 'object_number'], true, 'btree'],
  ['accrual_objects', 'ix_accrual_objects_tenant_id', ['tenant_id'], false, 'btree'],
  ['accrual_objects', 'ix_accrual_objects_accrual_type_concept_id', ['accrual_type_concept_id'], false, 'btree'],
  ['accrual_objects', 'ix_accrual_objects_contract_id', ['contract_id'], false, 'btree'],
  ['accrual_objects', 'ix_accrual_objects_business_partner_id', ['business_partner_id'], false, 'btree'],
  ['accrual_objects', 'ix_accrual_objects_expense_account_id', ['expense_account_id'], false, 'btree'],
  ['accrual_objects', 'ix_accrual_objects_accrual_account_id', ['accrual_account_id'], false, 'btree'],
  ['accrual_objects', 'ix_accrual_objects_cost_center_id', ['cost_center_id'], false, 'btree'],
  ['accrual_objects', 'ix_accrual_objects_profit_center_id', ['profit_center_id'], false, 'btree'],
  ['accrual_objects', 'ix_accrual_objects_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['accrual_objects', 'ix_accrual_objects_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['accrual_objects', 'ix_accrual_objects_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['accrual_objects', 'ix_accrual_objects_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['accrual_objects', 'ix_accrual_objects_tenant_status', ['tenant_id', 'status_concept_id'], false, 'btree'],
  ['accrual_postings', 'uq_accrual_postings_accrual_schedule_line_id_ledger_entry_id', ['accrual_schedule_line_id', 'ledger_entry_id'], true, 'btree'],
  ['accrual_postings', 'ix_accrual_postings_accrual_schedule_line_id', ['accrual_schedule_line_id'], false, 'btree'],
  ['accrual_postings', 'ix_accrual_postings_ledger_entry_id', ['ledger_entry_id'], false, 'btree'],
  ['accrual_postings', 'ix_accrual_postings_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['accrual_postings', 'ix_accrual_postings_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['accrual_postings', 'brin_accrual_postings_created_at', ['created_at'], false, 'brin'],
  ['accrual_schedule_lines', 'uq_accrual_schedule_lines_accrual_object_id_fiscal_period_id', ['accrual_object_id', 'fiscal_period_id'], true, 'btree'],
  ['accrual_schedule_lines', 'ix_accrual_schedule_lines_accrual_object_id', ['accrual_object_id'], false, 'btree'],
  ['accrual_schedule_lines', 'ix_accrual_schedule_lines_fiscal_period_id', ['fiscal_period_id'], false, 'btree'],
  ['accrual_schedule_lines', 'ix_accrual_schedule_lines_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['accrual_schedule_lines', 'ix_accrual_schedule_lines_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['accrual_schedule_lines', 'ix_accrual_schedule_lines_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['accrual_schedule_lines', 'ix_accrual_schedule_lines_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['assets', 'ix_assets_practice_id', ['practice_id'], false, 'btree'],
  ['assets', 'ix_assets_asset_type_concept_id', ['asset_type_concept_id'], false, 'btree'],
  ['assets', 'ix_assets_account_id', ['account_id'], false, 'btree'],
  ['assets', 'ix_assets_practice_id_account_id', ['practice_id', 'account_id', 'status_concept_id'], false, 'btree'],
  ['assets', 'ix_assets_depreciation_method_concept_id', ['depreciation_method_concept_id'], false, 'btree'],
  ['assets', 'ix_assets_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['assets', 'ix_assets_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['assets', 'ix_assets_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['asset_assignments', 'ix_asset_assignments_asset_id', ['asset_id'], false, 'btree'],
  ['asset_assignments', 'ix_asset_assignments_asset_component_id', ['asset_component_id'], false, 'btree'],
  ['asset_assignments', 'ix_asset_assignments_branch_id', ['branch_id'], false, 'btree'],
  ['asset_assignments', 'ix_asset_assignments_department_id', ['department_id'], false, 'btree'],
  ['asset_assignments', 'ix_asset_assignments_cost_center_id', ['cost_center_id'], false, 'btree'],
  ['asset_assignments', 'ix_asset_assignments_profit_center_id', ['profit_center_id'], false, 'btree'],
  ['asset_assignments', 'ix_asset_assignments_project_id', ['project_id'], false, 'btree'],
  ['asset_assignments', 'ix_asset_assignments_wbs_element_id', ['wbs_element_id'], false, 'btree'],
  ['asset_assignments', 'ix_asset_assignments_responsible_employee_id', ['responsible_employee_id'], false, 'btree'],
  ['asset_assignments', 'ix_asset_assignments_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['asset_assignments', 'ix_asset_assignments_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['asset_assignments', 'ix_asset_assignments_asset_valid_from', ['asset_id', 'valid_from desc'], false, 'btree'],
  ['asset_classes', 'uq_asset_classes_tenant_id_code', ['tenant_id', 'code'], true, 'btree'],
  ['asset_classes', 'ix_asset_classes_tenant_id', ['tenant_id'], false, 'btree'],
  ['asset_classes', 'ix_asset_classes_asset_type_concept_id', ['asset_type_concept_id'], false, 'btree'],
  ['asset_classes', 'ix_asset_classes_acquisition_account_id', ['acquisition_account_id'], false, 'btree'],
  ['asset_classes', 'ix_asset_classes_accumulated_depreciation_account_id', ['accumulated_depreciation_account_id'], false, 'btree'],
  ['asset_classes', 'ix_asset_classes_depreciation_expense_account_id', ['depreciation_expense_account_id'], false, 'btree'],
  ['asset_classes', 'ix_asset_classes_gain_account_id', ['gain_account_id'], false, 'btree'],
  ['asset_classes', 'ix_asset_classes_loss_account_id', ['loss_account_id'], false, 'btree'],
  ['asset_classes', 'ix_asset_classes_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['asset_classes', 'ix_asset_classes_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['asset_classes', 'ix_asset_classes_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['asset_components', 'uq_asset_components_asset_id_component_number', ['asset_id', 'component_number'], true, 'btree'],
  ['asset_components', 'ix_asset_components_asset_id', ['asset_id'], false, 'btree'],
  ['asset_components', 'ix_asset_components_asset_class_id', ['asset_class_id'], false, 'btree'],
  ['asset_components', 'ix_asset_components_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['asset_components', 'ix_asset_components_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['asset_components', 'ix_asset_components_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['asset_depreciations', 'ix_asset_depreciations_asset_id', ['asset_id'], false, 'btree'],
  ['asset_depreciations', 'ix_asset_depreciations_fiscal_period_id', ['fiscal_period_id'], false, 'btree'],
  ['asset_depreciations', 'ix_asset_depreciations_transaction_id', ['transaction_id'], false, 'btree'],
  ['asset_depreciations', 'ix_asset_depreciations_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['asset_depreciations', 'ix_asset_depreciations_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['asset_postings', 'ix_asset_postings_asset_id', ['asset_id'], false, 'btree'],
  ['asset_postings', 'ix_asset_postings_asset_component_id', ['asset_component_id'], false, 'btree'],
  ['asset_postings', 'ix_asset_postings_ledger_entry_id', ['ledger_entry_id'], false, 'btree'],
  ['asset_postings', 'ix_asset_postings_transaction_type_concept_id', ['transaction_type_concept_id'], false, 'btree'],
  ['asset_postings', 'ix_asset_postings_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['asset_postings', 'ix_asset_postings_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['asset_postings', 'ix_asset_postings_asset_value_date', ['asset_id', 'asset_value_date'], false, 'btree'],
  ['asset_postings', 'ix_asset_postings_ledger_asset', ['ledger_entry_id', 'asset_id'], false, 'btree'],
  ['asset_postings', 'brin_asset_postings_created_at', ['created_at'], false, 'brin'],
  ['asset_valuations', 'uq_asset_valuations_asset_id_asset_component_id_depreciation_a', ['asset_id', 'asset_component_id', 'depreciation_area_id', 'valid_from'], true, 'btree'],
  ['asset_valuations', 'ix_asset_valuations_asset_id', ['asset_id'], false, 'btree'],
  ['asset_valuations', 'ix_asset_valuations_asset_component_id', ['asset_component_id'], false, 'btree'],
  ['asset_valuations', 'ix_asset_valuations_depreciation_area_id', ['depreciation_area_id'], false, 'btree'],
  ['asset_valuations', 'ix_asset_valuations_depreciation_method_concept_id', ['depreciation_method_concept_id'], false, 'btree'],
  ['asset_valuations', 'ix_asset_valuations_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['asset_valuations', 'ix_asset_valuations_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['clearing_documents', 'uq_clearing_documents_tenant_id_clearing_number', ['tenant_id', 'clearing_number'], true, 'btree'],
  ['clearing_documents', 'ix_clearing_documents_tenant_id', ['tenant_id'], false, 'btree'],
  ['clearing_documents', 'ix_clearing_documents_transaction_id', ['transaction_id'], false, 'btree'],
  ['clearing_documents', 'ix_clearing_documents_company_bank_account_id', ['company_bank_account_id'], false, 'btree'],
  ['clearing_documents', 'ix_clearing_documents_payment_transaction_id', ['payment_transaction_id'], false, 'btree'],
  ['clearing_documents', 'ix_clearing_documents_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['clearing_documents', 'ix_clearing_documents_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['clearing_documents', 'ix_clearing_documents_tenant_date', ['tenant_id', 'clearing_date'], false, 'btree'],
  ['clearing_items', 'uq_clearing_items_clearing_document_id_open_item_id', ['clearing_document_id', 'open_item_id'], true, 'btree'],
  ['clearing_items', 'ix_clearing_items_clearing_document_id', ['clearing_document_id'], false, 'btree'],
  ['clearing_items', 'ix_clearing_items_open_item_id', ['open_item_id'], false, 'btree'],
  ['clearing_items', 'ix_clearing_items_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['clearing_items', 'ix_clearing_items_residual_open_item_id', ['residual_open_item_id'], false, 'btree'],
  ['clearing_items', 'ix_clearing_items_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['company_bank_accounts', 'uq_company_bank_accounts_tenant_id_account_number_hash', ['tenant_id', 'account_number_hash'], true, 'btree'],
  ['company_bank_accounts', 'ix_company_bank_accounts_tenant_id', ['tenant_id'], false, 'btree'],
  ['company_bank_accounts', 'ix_company_bank_accounts_account_id', ['account_id'], false, 'btree'],
  ['company_bank_accounts', 'ix_company_bank_accounts_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['company_bank_accounts', 'ix_company_bank_accounts_branch_id', ['branch_id'], false, 'btree'],
  ['company_bank_accounts', 'ix_company_bank_accounts_clearing_account_id', ['clearing_account_id'], false, 'btree'],
  ['company_bank_accounts', 'ix_company_bank_accounts_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['company_bank_accounts', 'ix_company_bank_accounts_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['company_bank_accounts', 'ix_company_bank_accounts_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['company_bank_accounts', 'ix_company_bank_accounts_tenant_status', ['tenant_id', 'status_concept_id'], false, 'btree'],
  ['controlling_areas', 'uq_controlling_areas_tenant_id_code', ['tenant_id', 'code'], true, 'btree'],
  ['controlling_areas', 'ix_controlling_areas_tenant_id', ['tenant_id'], false, 'btree'],
  ['controlling_areas', 'ix_controlling_areas_operating_currency_concept_id', ['operating_currency_concept_id'], false, 'btree'],
  ['controlling_areas', 'ix_controlling_areas_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['controlling_areas', 'ix_controlling_areas_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['controlling_areas', 'ix_controlling_areas_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['cost_centers', 'ix_cost_centers_practice_id', ['practice_id'], false, 'btree'],
  ['cost_centers', 'ix_cost_centers_parent_cost_center_id', ['parent_cost_center_id'], false, 'btree'],
  ['cost_centers', 'ix_cost_centers_practitioner_profile_id', ['practitioner_profile_id'], false, 'btree'],
  ['cost_centers', 'ix_cost_centers_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['cost_centers', 'ix_cost_centers_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['cost_centers', 'ix_cost_centers_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['cost_center_maps', 'ix_cost_center_maps_practice_id', ['practice_id'], false, 'btree'],
  ['cost_center_maps', 'ix_cost_center_maps_source_type_concept_id', ['source_type_concept_id'], false, 'btree'],
  ['cost_center_maps', 'ix_cost_center_maps_cost_center_id', ['cost_center_id'], false, 'btree'],
  ['cost_center_maps', 'ix_cost_center_maps_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['cost_center_maps', 'ix_cost_center_maps_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['depreciation_areas', 'uq_depreciation_areas_tenant_id_code', ['tenant_id', 'code'], true, 'btree'],
  ['depreciation_areas', 'ix_depreciation_areas_tenant_id', ['tenant_id'], false, 'btree'],
  ['depreciation_areas', 'ix_depreciation_areas_accounting_principle_concept_id', ['accounting_principle_concept_id'], false, 'btree'],
  ['depreciation_areas', 'ix_depreciation_areas_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['depreciation_areas', 'ix_depreciation_areas_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['depreciation_areas', 'ix_depreciation_areas_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['depreciation_areas', 'ix_depreciation_areas_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['employee_payments', 'ix_employee_payments_employee_id', ['employee_id'], false, 'btree'],
  ['employee_payments', 'ix_employee_payments_fiscal_period_id', ['fiscal_period_id'], false, 'btree'],
  ['employee_payments', 'ix_employee_payments_transaction_id', ['transaction_id'], false, 'btree'],
  ['employee_payments', 'ix_employee_payments_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['employee_payments', 'ix_employee_payments_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['employee_payments', 'ix_employee_payments_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['exchange_rates', 'ix_exchange_rates_from_currency_concept_id', ['from_currency_concept_id'], false, 'btree'],
  ['exchange_rates', 'ix_exchange_rates_to_currency_concept_id', ['to_currency_concept_id'], false, 'btree'],
  ['exchange_rates', 'ix_exchange_rates_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['exchange_rates', 'ix_exchange_rates_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['fiscal_periods', 'ix_fiscal_periods_fiscal_year_id', ['fiscal_year_id'], false, 'btree'],
];
