import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `ads` (parte 2/3).
 * 180 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const adsIndexes2: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['business_managers', 'ix_business_managers_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['business_managers', 'ix_business_managers_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['campaigns', 'ix_campaigns_ad_account_id', ['ad_account_id'], false, 'btree'],
  ['campaigns', 'ix_campaigns_objective_concept_id', ['objective_concept_id'], false, 'btree'],
  ['campaigns', 'ix_campaigns_buying_type_concept_id', ['buying_type_concept_id'], false, 'btree'],
  ['campaigns', 'ix_campaigns_bid_strategy_concept_id', ['bid_strategy_concept_id'], false, 'btree'],
  ['campaigns', 'ix_campaigns_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['campaigns', 'ix_campaigns_effective_status_concept_id', ['effective_status_concept_id'], false, 'btree'],
  ['campaigns', 'ix_campaigns_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['campaigns', 'ix_campaigns_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['catalog_feeds', 'ix_catalog_feeds_product_catalog_id', ['product_catalog_id'], false, 'btree'],
  ['catalog_feeds', 'ix_catalog_feeds_feed_source_concept_id', ['feed_source_concept_id'], false, 'btree'],
  ['catalog_feeds', 'ix_catalog_feeds_file_id', ['file_id'], false, 'btree'],
  ['catalog_feeds', 'ix_catalog_feeds_last_status_concept_id', ['last_status_concept_id'], false, 'btree'],
  ['catalog_feeds', 'ix_catalog_feeds_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['catalog_feeds', 'ix_catalog_feeds_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['catalog_feeds', 'ix_catalog_feeds_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['catalog_products', 'ix_catalog_products_product_catalog_id', ['product_catalog_id'], false, 'btree'],
  ['catalog_products', 'ix_catalog_products_availability_concept_id', ['availability_concept_id'], false, 'btree'],
  ['catalog_products', 'ix_catalog_products_condition_concept_id', ['condition_concept_id'], false, 'btree'],
  ['catalog_products', 'ix_catalog_products_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['catalog_products', 'ix_catalog_products_category_concept_id', ['category_concept_id'], false, 'btree'],
  ['catalog_products', 'ix_catalog_products_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['catalog_products', 'ix_catalog_products_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['catalog_products', 'ix_catalog_products_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['collection_ads', 'ix_collection_ads_ad_account_id', ['ad_account_id'], false, 'btree'],
  ['collection_ads', 'ix_collection_ads_layout_concept_id', ['layout_concept_id'], false, 'btree'],
  ['collection_ads', 'ix_collection_ads_hero_creative_id', ['hero_creative_id'], false, 'btree'],
  ['collection_ads', 'ix_collection_ads_product_set_id', ['product_set_id'], false, 'btree'],
  ['collection_ads', 'ix_collection_ads_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['collection_ads', 'ix_collection_ads_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['collection_ads', 'ix_collection_ads_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['conversion_attributions', 'ix_conversion_attributions_pixel_event_id', ['pixel_event_id'], false, 'btree'],
  ['conversion_attributions', 'ix_conversion_attributions_attribution_type_concept_id', ['attribution_type_concept_id'], false, 'btree'],
  ['conversion_attributions', 'ix_conversion_attributions_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['conversion_attributions', 'ix_conversion_attributions_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['conversion_datasets', 'ix_conversion_datasets_tenant_id', ['tenant_id'], false, 'btree'],
  ['conversion_datasets', 'ix_conversion_datasets_ad_account_id', ['ad_account_id'], false, 'btree'],
  ['conversion_datasets', 'ix_conversion_datasets_dataset_type_concept_id', ['dataset_type_concept_id'], false, 'btree'],
  ['conversion_datasets', 'ix_conversion_datasets_external_dataset_id', ['external_dataset_id'], false, 'btree'],
  ['conversion_datasets', 'ix_conversion_datasets_data_use_case_concept_id', ['data_use_case_concept_id'], false, 'btree'],
  ['conversion_datasets', 'ix_conversion_datasets_default_attribution_setting_id', ['default_attribution_setting_id'], false, 'btree'],
  ['conversion_datasets', 'ix_conversion_datasets_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['conversion_datasets', 'ix_conversion_datasets_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['conversion_datasets', 'ix_conversion_datasets_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['conversion_datasets', 'ix_conversion_datasets_tenant_status', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['conversion_datasets', 'uk_conversion_datasets_account_code', ['ad_account_id', 'code'], true, 'btree'],
  ['conversion_datasets', 'uk_conversion_datasets_external', ['ad_account_id', 'external_dataset_id'], true, 'btree'],
  ['conversion_event_custom_data', 'ix_conversion_event_custom_data_server_conversion_event_id', ['server_conversion_event_id'], false, 'btree'],
  ['conversion_event_custom_data', 'ix_conversion_event_custom_data_order_id', ['order_id'], false, 'btree'],
  ['conversion_event_custom_data', 'uk_conversion_event_custom_data_event', ['server_conversion_event_id'], true, 'btree'],
  ['conversion_event_deduplication', 'ix_conversion_event_deduplication_conversion_dataset_id', ['conversion_dataset_id'], false, 'btree'],
  ['conversion_event_deduplication', 'ix_conversion_event_deduplication_event_id', ['event_id'], false, 'btree'],
  ['conversion_event_deduplication', 'ix_conversion_event_deduplication_server_conversion_event_id', ['server_conversion_event_id'], false, 'btree'],
  ['conversion_event_deduplication', 'ix_conversion_event_deduplication_resolution_concept_id', ['resolution_concept_id'], false, 'btree'],
  ['conversion_event_deduplication', 'uk_conversion_event_dedup_key', ['conversion_dataset_id', 'event_name', 'event_id'], true, 'btree'],
  ['conversion_event_delivery_attempts', 'ix_conversion_event_delivery_attempts_server_conversio_755102a2', ['server_conversion_event_id'], false, 'btree'],
  ['conversion_event_delivery_attempts', 'ix_conversion_event_delivery_attempts_platform_connection_id', ['platform_connection_id'], false, 'btree'],
  ['conversion_event_delivery_attempts', 'ix_conversion_event_delivery_attempts_result_concept_id', ['result_concept_id'], false, 'btree'],
  ['conversion_event_delivery_attempts', 'ix_conversion_event_delivery_attempts_external_trace_id', ['external_trace_id'], false, 'btree'],
  ['conversion_event_delivery_attempts', 'uk_conversion_delivery_attempt_event_attempt', ['server_conversion_event_id', 'platform_connection_id', 'attempt_number'], true, 'btree'],
  ['conversion_event_user_data', 'ix_conversion_event_user_data_server_conversion_event_id', ['server_conversion_event_id'], false, 'btree'],
  ['conversion_event_user_data', 'ix_conversion_event_user_data_click_id', ['click_id'], false, 'btree'],
  ['conversion_event_user_data', 'ix_conversion_event_user_data_browser_id', ['browser_id'], false, 'btree'],
  ['conversion_event_user_data', 'uk_conversion_event_user_data_event', ['server_conversion_event_id'], true, 'btree'],
  ['creative_assets', 'ix_creative_assets_ad_creative_id', ['ad_creative_id'], false, 'btree'],
  ['creative_assets', 'ix_creative_assets_asset_type_concept_id', ['asset_type_concept_id'], false, 'btree'],
  ['creative_assets', 'ix_creative_assets_file_id', ['file_id'], false, 'btree'],
  ['creative_assets', 'ix_creative_assets_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['creative_assets', 'ix_creative_assets_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['custom_audiences', 'ix_custom_audiences_ad_account_id', ['ad_account_id'], false, 'btree'],
  ['custom_audiences', 'ix_custom_audiences_audience_type_concept_id', ['audience_type_concept_id'], false, 'btree'],
  ['custom_audiences', 'ix_custom_audiences_subtype_concept_id', ['subtype_concept_id'], false, 'btree'],
  ['custom_audiences', 'ix_custom_audiences_source_concept_id', ['source_concept_id'], false, 'btree'],
  ['custom_audiences', 'ix_custom_audiences_lookalike_source_audience_id', ['lookalike_source_audience_id'], false, 'btree'],
  ['custom_audiences', 'ix_custom_audiences_data_source_pixel_id', ['data_source_pixel_id'], false, 'btree'],
  ['custom_audiences', 'ix_custom_audiences_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['custom_audiences', 'ix_custom_audiences_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['custom_audiences', 'ix_custom_audiences_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['custom_conversions', 'ix_custom_conversions_ad_account_id', ['ad_account_id'], false, 'btree'],
  ['custom_conversions', 'ix_custom_conversions_pixel_id', ['pixel_id'], false, 'btree'],
  ['custom_conversions', 'ix_custom_conversions_conversion_category_concept_id', ['conversion_category_concept_id'], false, 'btree'],
  ['custom_conversions', 'ix_custom_conversions_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['custom_conversions', 'ix_custom_conversions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['custom_conversions', 'ix_custom_conversions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['custom_conversions', 'ix_custom_conversions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['dataset_connections', 'ix_dataset_connections_conversion_dataset_id', ['conversion_dataset_id'], false, 'btree'],
  ['dataset_connections', 'ix_dataset_connections_platform_connection_id', ['platform_connection_id'], false, 'btree'],
  ['dataset_connections', 'ix_dataset_connections_tracking_pixel_id', ['tracking_pixel_id'], false, 'btree'],
  ['dataset_connections', 'ix_dataset_connections_connection_type_concept_id', ['connection_type_concept_id'], false, 'btree'],
  ['dataset_connections', 'ix_dataset_connections_external_connection_id', ['external_connection_id'], false, 'btree'],
  ['dataset_connections', 'ix_dataset_connections_test_event_code_secret_id', ['test_event_code_secret_id'], false, 'btree'],
  ['dataset_connections', 'ix_dataset_connections_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['dataset_connections', 'ix_dataset_connections_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['dataset_connections', 'ix_dataset_connections_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['dataset_connections', 'uk_dataset_connections_dataset_type', ['conversion_dataset_id', 'connection_type_concept_id', 'platform_connection_id'], true, 'btree'],
  ['dataset_quality_snapshots', 'ix_dataset_quality_snapshots_conversion_dataset_id', ['conversion_dataset_id'], false, 'btree'],
  ['dataset_quality_snapshots', 'ix_dataset_quality_snapshots_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['delivery_status_snapshots', 'ix_delivery_status_snapshots_ad_account_id', ['ad_account_id'], false, 'btree'],
  ['delivery_status_snapshots', 'ix_delivery_status_snapshots_entity_type_concept_id', ['entity_type_concept_id'], false, 'btree'],
  ['delivery_status_snapshots', 'ix_delivery_status_snapshots_effective_status_concept_id', ['effective_status_concept_id'], false, 'btree'],
  ['delivery_status_snapshots', 'ix_delivery_status_snapshots_review_status_concept_id', ['review_status_concept_id'], false, 'btree'],
  ['delivery_status_snapshots', 'ix_delivery_status_snapshots_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['dynamic_ad_templates', 'ix_dynamic_ad_templates_ad_account_id', ['ad_account_id'], false, 'btree'],
  ['dynamic_ad_templates', 'ix_dynamic_ad_templates_product_set_id', ['product_set_id'], false, 'btree'],
  ['dynamic_ad_templates', 'ix_dynamic_ad_templates_format_concept_id', ['format_concept_id'], false, 'btree'],
  ['dynamic_ad_templates', 'ix_dynamic_ad_templates_call_to_action_concept_id', ['call_to_action_concept_id'], false, 'btree'],
  ['dynamic_ad_templates', 'ix_dynamic_ad_templates_creative_id', ['creative_id'], false, 'btree'],
  ['dynamic_ad_templates', 'ix_dynamic_ad_templates_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['dynamic_ad_templates', 'ix_dynamic_ad_templates_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['dynamic_ad_templates', 'ix_dynamic_ad_templates_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['experiment_variants', 'ix_experiment_variants_ad_experiment_id', ['ad_experiment_id'], false, 'btree'],
  ['experiment_variants', 'ix_experiment_variants_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['experiment_variants', 'ix_experiment_variants_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['external_ad_object_snapshots', 'ix_external_ad_object_snapshots_platform_connection_id', ['platform_connection_id'], false, 'btree'],
  ['external_ad_object_snapshots', 'ix_external_ad_object_snapshots_object_type_concept_id', ['object_type_concept_id'], false, 'btree'],
  ['external_ad_object_snapshots', 'ix_external_ad_object_snapshots_external_object_id', ['external_object_id'], false, 'btree'],
  ['external_ad_object_snapshots', 'uk_external_ad_snapshots_version', ['platform_connection_id', 'object_type_concept_id', 'external_object_id', 'external_updated_at'], true, 'btree'],
  ['feed_run_logs', 'ix_feed_run_logs_catalog_feed_id', ['catalog_feed_id'], false, 'btree'],
  ['feed_run_logs', 'ix_feed_run_logs_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['feed_run_logs', 'ix_feed_run_logs_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['frequency_caps', 'ix_frequency_caps_scope_concept_id', ['scope_concept_id'], false, 'btree'],
  ['frequency_caps', 'ix_frequency_caps_time_window_concept_id', ['time_window_concept_id'], false, 'btree'],
  ['frequency_caps', 'ix_frequency_caps_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['frequency_caps', 'ix_frequency_caps_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['insight_breakdown_definitions', 'ix_insight_breakdown_definitions_platform_concept_id', ['platform_concept_id'], false, 'btree'],
  ['insight_breakdown_definitions', 'ix_insight_breakdown_definitions_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['insight_breakdown_definitions', 'ix_insight_breakdown_definitions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['insight_breakdown_definitions', 'ix_insight_breakdown_definitions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['insight_breakdown_definitions', 'uk_insight_breakdown_platform_code', ['platform_concept_id', 'breakdown_code'], true, 'btree'],
  ['insight_fact_rows', 'ix_insight_fact_rows_insight_query_run_id', ['insight_query_run_id'], false, 'btree'],
  ['insight_fact_rows', 'ix_insight_fact_rows_object_type_concept_id', ['object_type_concept_id'], false, 'btree'],
  ['insight_fact_rows', 'ix_insight_fact_rows_external_object_id', ['external_object_id'], false, 'btree'],
  ['insight_fact_rows', 'ix_insight_fact_rows_campaign_id', ['campaign_id'], false, 'btree'],
  ['insight_fact_rows', 'ix_insight_fact_rows_ad_set_id', ['ad_set_id'], false, 'btree'],
  ['insight_fact_rows', 'ix_insight_fact_rows_ad_id', ['ad_id'], false, 'btree'],
  ['insight_fact_rows', 'ix_insight_fact_rows_query_date', ['insight_query_run_id', 'fact_date', 'external_object_id'], false, 'btree'],
  ['insight_metric_definitions', 'ix_insight_metric_definitions_platform_concept_id', ['platform_concept_id'], false, 'btree'],
  ['insight_metric_definitions', 'ix_insight_metric_definitions_data_type_concept_id', ['data_type_concept_id'], false, 'btree'],
  ['insight_metric_definitions', 'ix_insight_metric_definitions_aggregation_concept_id', ['aggregation_concept_id'], false, 'btree'],
  ['insight_metric_definitions', 'ix_insight_metric_definitions_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['insight_metric_definitions', 'ix_insight_metric_definitions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['insight_metric_definitions', 'ix_insight_metric_definitions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['insight_metric_definitions', 'uk_insight_metric_definitions_platform_code', ['platform_concept_id', 'metric_code'], true, 'btree'],
  ['insight_query_runs', 'ix_insight_query_runs_tenant_id', ['tenant_id'], false, 'btree'],
  ['insight_query_runs', 'ix_insight_query_runs_ad_account_id', ['ad_account_id'], false, 'btree'],
  ['insight_query_runs', 'ix_insight_query_runs_platform_connection_id', ['platform_connection_id'], false, 'btree'],
  ['insight_query_runs', 'ix_insight_query_runs_object_level_concept_id', ['object_level_concept_id'], false, 'btree'],
  ['insight_query_runs', 'ix_insight_query_runs_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['insight_query_runs', 'ix_insight_query_runs_external_report_id', ['external_report_id'], false, 'btree'],
  ['insight_query_runs', 'ix_insight_query_runs_tenant_status', ['tenant_id', 'status_concept_id', 'created_at desc'], false, 'btree'],
  ['insights_daily', 'ix_insights_daily_ad_account_id', ['ad_account_id'], false, 'btree'],
  ['insights_daily', 'ix_insights_daily_entity_type_concept_id', ['entity_type_concept_id'], false, 'btree'],
  ['insights_daily', 'ix_insights_daily_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['insights_daily', 'ix_insights_daily_source_concept_id', ['source_concept_id'], false, 'btree'],
  ['insights_daily', 'ix_insights_daily_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['lead_answers', 'ix_lead_answers_lead_submission_id', ['lead_submission_id'], false, 'btree'],
  ['lead_answers', 'ix_lead_answers_lead_form_question_id', ['lead_form_question_id'], false, 'btree'],
  ['lead_answers', 'uk_lead_answers_submission_question', ['lead_submission_id', 'lead_form_question_id'], true, 'btree'],
  ['lead_delivery_events', 'ix_lead_delivery_events_lead_submission_id', ['lead_submission_id'], false, 'btree'],
  ['lead_delivery_events', 'ix_lead_delivery_events_destination_type_concept_id', ['destination_type_concept_id'], false, 'btree'],
  ['lead_delivery_events', 'ix_lead_delivery_events_result_concept_id', ['result_concept_id'], false, 'btree'],
  ['lead_delivery_events', 'uk_lead_delivery_submission_attempt', ['lead_submission_id', 'destination_type_concept_id', 'attempt_number'], true, 'btree'],
  ['lead_form_questions', 'ix_lead_form_questions_lead_form_id', ['lead_form_id'], false, 'btree'],
  ['lead_form_questions', 'ix_lead_form_questions_question_type_concept_id', ['question_type_concept_id'], false, 'btree'],
  ['lead_form_questions', 'ix_lead_form_questions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['lead_form_questions', 'ix_lead_form_questions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['lead_form_questions', 'ix_lead_form_questions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['lead_form_questions', 'uk_lead_form_questions_form_key', ['lead_form_id', 'question_key'], true, 'btree'],
  ['lead_forms', 'ix_lead_forms_tenant_id', ['tenant_id'], false, 'btree'],
  ['lead_forms', 'ix_lead_forms_ad_account_id', ['ad_account_id'], false, 'btree'],
  ['lead_forms', 'ix_lead_forms_ad_identity_asset_id', ['ad_identity_asset_id'], false, 'btree'],
  ['lead_forms', 'ix_lead_forms_external_form_id', ['external_form_id'], false, 'btree'],
  ['lead_forms', 'ix_lead_forms_form_type_concept_id', ['form_type_concept_id'], false, 'btree'],
  ['lead_forms', 'ix_lead_forms_destination_crm_pipeline_id', ['destination_crm_pipeline_id'], false, 'btree'],
  ['lead_forms', 'ix_lead_forms_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['lead_forms', 'ix_lead_forms_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['lead_forms', 'ix_lead_forms_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['lead_forms', 'ix_lead_forms_tenant_status', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['lead_forms', 'uk_lead_forms_account_code', ['ad_account_id', 'code'], true, 'btree'],
];
