import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `ads` (parte 3/3).
 * 111 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const adsIndexes3: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['lead_forms', 'ix_lead_forms_ad_identity_asset_id', ['ad_identity_asset_id'], false, 'btree'],
  ['lead_forms', 'ix_lead_forms_external_form_id', ['external_form_id'], false, 'btree'],
  ['lead_forms', 'ix_lead_forms_form_type_concept_id', ['form_type_concept_id'], false, 'btree'],
  ['lead_forms', 'ix_lead_forms_destination_crm_pipeline_id', ['destination_crm_pipeline_id'], false, 'btree'],
  ['lead_forms', 'ix_lead_forms_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['lead_forms', 'ix_lead_forms_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['lead_forms', 'ix_lead_forms_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['lead_forms', 'ix_lead_forms_tenant_status', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['lead_forms', 'uk_lead_forms_account_code', ['ad_account_id', 'code'], true, 'btree'],
  ['lead_forms', 'uk_lead_forms_external', ['ad_account_id', 'external_form_id'], true, 'btree'],
  ['lead_form_questions', 'ix_lead_form_questions_lead_form_id', ['lead_form_id'], false, 'btree'],
  ['lead_form_questions', 'ix_lead_form_questions_question_type_concept_id', ['question_type_concept_id'], false, 'btree'],
  ['lead_form_questions', 'ix_lead_form_questions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['lead_form_questions', 'ix_lead_form_questions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['lead_form_questions', 'ix_lead_form_questions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['lead_form_questions', 'uk_lead_form_questions_form_key', ['lead_form_id', 'question_key'], true, 'btree'],
  ['lead_submissions', 'ix_lead_submissions_tenant_id', ['tenant_id'], false, 'btree'],
  ['lead_submissions', 'ix_lead_submissions_lead_form_id', ['lead_form_id'], false, 'btree'],
  ['lead_submissions', 'ix_lead_submissions_ad_id', ['ad_id'], false, 'btree'],
  ['lead_submissions', 'ix_lead_submissions_ad_set_id', ['ad_set_id'], false, 'btree'],
  ['lead_submissions', 'ix_lead_submissions_campaign_id', ['campaign_id'], false, 'btree'],
  ['lead_submissions', 'ix_lead_submissions_external_lead_id', ['external_lead_id'], false, 'btree'],
  ['lead_submissions', 'ix_lead_submissions_crm_lead_id', ['crm_lead_id'], false, 'btree'],
  ['lead_submissions', 'ix_lead_submissions_consent_directive_id', ['consent_directive_id'], false, 'btree'],
  ['lead_submissions', 'ix_lead_submissions_processing_status_concept_id', ['processing_status_concept_id'], false, 'btree'],
  ['lead_submissions', 'ix_lead_submissions_tenant_created', ['tenant_id', 'created_at desc'], false, 'btree'],
  ['lead_submissions', 'brin_lead_submissions_created_at', ['created_at'], false, 'brin'],
  ['lead_submissions', 'uk_lead_submissions_form_external', ['lead_form_id', 'external_lead_id'], true, 'btree'],
  ['lead_submissions', 'ix_lead_submissions_tenant_submitted', ['tenant_id', 'submitted_at desc'], false, 'btree'],
  ['lookalike_specs', 'ix_lookalike_specs_ad_account_id', ['ad_account_id'], false, 'btree'],
  ['lookalike_specs', 'ix_lookalike_specs_source_audience_id', ['source_audience_id'], false, 'btree'],
  ['lookalike_specs', 'ix_lookalike_specs_country_concept_id', ['country_concept_id'], false, 'btree'],
  ['lookalike_specs', 'ix_lookalike_specs_similarity_concept_id', ['similarity_concept_id'], false, 'btree'],
  ['lookalike_specs', 'ix_lookalike_specs_generated_audience_id', ['generated_audience_id'], false, 'btree'],
  ['lookalike_specs', 'ix_lookalike_specs_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['lookalike_specs', 'ix_lookalike_specs_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['lookalike_specs', 'ix_lookalike_specs_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['offline_conversion_events', 'ix_offline_conversion_events_offline_conversion_set_id', ['offline_conversion_set_id'], false, 'btree'],
  ['offline_conversion_events', 'ix_offline_conversion_events_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['offline_conversion_events', 'ix_offline_conversion_events_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['offline_conversion_events', 'brin_offline_conversion_events_recorded_at', ['recorded_at'], false, 'brin'],
  ['offline_conversion_sets', 'ix_offline_conversion_sets_ad_account_id', ['ad_account_id'], false, 'btree'],
  ['offline_conversion_sets', 'ix_offline_conversion_sets_upload_source_concept_id', ['upload_source_concept_id'], false, 'btree'],
  ['offline_conversion_sets', 'ix_offline_conversion_sets_file_id', ['file_id'], false, 'btree'],
  ['offline_conversion_sets', 'ix_offline_conversion_sets_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['offline_conversion_sets', 'ix_offline_conversion_sets_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['offline_conversion_sets', 'ix_offline_conversion_sets_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['partner_relationships', 'ix_partner_relationships_business_manager_id', ['business_manager_id'], false, 'btree'],
  ['partner_relationships', 'ix_partner_relationships_partner_id', ['partner_id'], false, 'btree'],
  ['partner_relationships', 'ix_partner_relationships_relationship_type_concept_id', ['relationship_type_concept_id'], false, 'btree'],
  ['partner_relationships', 'ix_partner_relationships_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['partner_relationships', 'ix_partner_relationships_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['partner_relationships', 'ix_partner_relationships_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['pixel_events', 'ix_pixel_events_pixel_id', ['pixel_id'], false, 'btree'],
  ['pixel_events', 'ix_pixel_events_event_source_concept_id', ['event_source_concept_id'], false, 'btree'],
  ['pixel_events', 'ix_pixel_events_action_source_concept_id', ['action_source_concept_id'], false, 'btree'],
  ['pixel_events', 'ix_pixel_events_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['pixel_events', 'ix_pixel_events_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['pixel_events', 'brin_pixel_events_recorded_at', ['recorded_at'], false, 'brin'],
  ['product_catalogs', 'ix_product_catalogs_business_manager_id', ['business_manager_id'], false, 'btree'],
  ['product_catalogs', 'ix_product_catalogs_vertical_concept_id', ['vertical_concept_id'], false, 'btree'],
  ['product_catalogs', 'ix_product_catalogs_default_currency_concept_id', ['default_currency_concept_id'], false, 'btree'],
  ['product_catalogs', 'ix_product_catalogs_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['product_catalogs', 'ix_product_catalogs_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['product_catalogs', 'ix_product_catalogs_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['product_localizations', 'ix_product_localizations_catalog_product_id', ['catalog_product_id'], false, 'btree'],
  ['product_localizations', 'ix_product_localizations_language_concept_id', ['language_concept_id'], false, 'btree'],
  ['product_localizations', 'ix_product_localizations_country_concept_id', ['country_concept_id'], false, 'btree'],
  ['product_localizations', 'ix_product_localizations_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['product_localizations', 'ix_product_localizations_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['product_localizations', 'ix_product_localizations_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['product_sets', 'ix_product_sets_product_catalog_id', ['product_catalog_id'], false, 'btree'],
  ['product_sets', 'ix_product_sets_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['product_sets', 'ix_product_sets_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['product_sets', 'ix_product_sets_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['product_set_members', 'ix_product_set_members_product_set_id', ['product_set_id'], false, 'btree'],
  ['product_set_members', 'ix_product_set_members_catalog_product_id', ['catalog_product_id'], false, 'btree'],
  ['product_set_members', 'ix_product_set_members_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['product_set_members', 'ix_product_set_members_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['rule_executions', 'ix_rule_executions_automated_rule_id', ['automated_rule_id'], false, 'btree'],
  ['rule_executions', 'ix_rule_executions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['rule_executions', 'ix_rule_executions_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['rule_executions', 'brin_rule_executions_recorded_at', ['recorded_at'], false, 'brin'],
  ['saved_audiences', 'ix_saved_audiences_ad_account_id', ['ad_account_id'], false, 'btree'],
  ['saved_audiences', 'ix_saved_audiences_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['saved_audiences', 'ix_saved_audiences_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['saved_audiences', 'ix_saved_audiences_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['server_conversion_events', 'ix_server_conversion_events_tenant_id', ['tenant_id'], false, 'btree'],
  ['server_conversion_events', 'ix_server_conversion_events_conversion_dataset_id', ['conversion_dataset_id'], false, 'btree'],
  ['server_conversion_events', 'ix_server_conversion_events_event_id', ['event_id'], false, 'btree'],
  ['server_conversion_events', 'ix_server_conversion_events_action_source_concept_id', ['action_source_concept_id'], false, 'btree'],
  ['server_conversion_events', 'ix_server_conversion_events_external_order_id', ['external_order_id'], false, 'btree'],
  ['server_conversion_events', 'ix_server_conversion_events_payment_transaction_id', ['payment_transaction_id'], false, 'btree'],
  ['server_conversion_events', 'ix_server_conversion_events_crm_lead_id', ['crm_lead_id'], false, 'btree'],
  ['server_conversion_events', 'ix_server_conversion_events_crm_opportunity_id', ['crm_opportunity_id'], false, 'btree'],
  ['server_conversion_events', 'ix_server_conversion_events_consent_directive_id', ['consent_directive_id'], false, 'btree'],
  ['server_conversion_events', 'ix_server_conversion_events_processing_status_concept_id', ['processing_status_concept_id'], false, 'btree'],
  ['server_conversion_events', 'ix_server_conversion_events_blocked_reason_concept_id', ['blocked_reason_concept_id'], false, 'btree'],
  ['server_conversion_events', 'ix_server_conversion_events_tenant_created', ['tenant_id', 'created_at desc'], false, 'btree'],
  ['server_conversion_events', 'brin_server_conversion_events_created_at', ['created_at'], false, 'brin'],
  ['server_conversion_events', 'uk_server_conversion_events_dataset_event', ['conversion_dataset_id', 'event_name', 'event_id'], true, 'btree'],
  ['server_conversion_events', 'ix_server_conversion_events_order', ['tenant_id', 'external_order_id'], false, 'btree'],
  ['targeting_specs', 'ix_targeting_specs_ad_account_id', ['ad_account_id'], false, 'btree'],
  ['targeting_specs', 'ix_targeting_specs_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['targeting_specs', 'ix_targeting_specs_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['tracking_pixels', 'uq_tracking_pixels_pixel_code', ['pixel_code'], true, 'btree'],
  ['tracking_pixels', 'ix_tracking_pixels_business_manager_id', ['business_manager_id'], false, 'btree'],
  ['tracking_pixels', 'ix_tracking_pixels_ad_account_id', ['ad_account_id'], false, 'btree'],
  ['tracking_pixels', 'ix_tracking_pixels_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['tracking_pixels', 'ix_tracking_pixels_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['tracking_pixels', 'ix_tracking_pixels_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
];
