import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `ads` (parte 1/3).
 * 180 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const adsIndexes1: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['ad_account_users', 'ix_ad_account_users_ad_account_id', ['ad_account_id'], false, 'btree'],
  ['ad_account_users', 'ix_ad_account_users_user_id', ['user_id'], false, 'btree'],
  ['ad_account_users', 'ix_ad_account_users_partner_id', ['partner_id'], false, 'btree'],
  ['ad_account_users', 'ix_ad_account_users_role_concept_id', ['role_concept_id'], false, 'btree'],
  ['ad_account_users', 'ix_ad_account_users_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['ad_account_users', 'ix_ad_account_users_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['ad_account_users', 'ix_ad_account_users_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['ad_accounts', 'uq_ad_accounts_external_account_ref', ['external_account_ref'], true, 'btree'],
  ['ad_accounts', 'ix_ad_accounts_business_manager_id', ['business_manager_id'], false, 'btree'],
  ['ad_accounts', 'ix_ad_accounts_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['ad_accounts', 'ix_ad_accounts_account_status_concept_id', ['account_status_concept_id'], false, 'btree'],
  ['ad_accounts', 'ix_ad_accounts_funding_payment_method_id', ['funding_payment_method_id'], false, 'btree'],
  ['ad_accounts', 'ix_ad_accounts_disable_reason_concept_id', ['disable_reason_concept_id'], false, 'btree'],
  ['ad_accounts', 'ix_ad_accounts_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['ad_accounts', 'ix_ad_accounts_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['ad_billing_events', 'ix_ad_billing_events_ad_account_id', ['ad_account_id'], false, 'btree'],
  ['ad_billing_events', 'ix_ad_billing_events_billing_event_type_concept_id', ['billing_event_type_concept_id'], false, 'btree'],
  ['ad_billing_events', 'ix_ad_billing_events_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['ad_billing_events', 'ix_ad_billing_events_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['ad_creatives', 'ix_ad_creatives_ad_account_id', ['ad_account_id'], false, 'btree'],
  ['ad_creatives', 'ix_ad_creatives_format_concept_id', ['format_concept_id'], false, 'btree'],
  ['ad_creatives', 'ix_ad_creatives_call_to_action_concept_id', ['call_to_action_concept_id'], false, 'btree'],
  ['ad_creatives', 'ix_ad_creatives_primary_media_file_id', ['primary_media_file_id'], false, 'btree'],
  ['ad_creatives', 'ix_ad_creatives_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['ad_creatives', 'ix_ad_creatives_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['ad_creatives', 'ix_ad_creatives_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['ad_event_data_policies', 'ix_ad_event_data_policies_tenant_id', ['tenant_id'], false, 'btree'],
  ['ad_event_data_policies', 'ix_ad_event_data_policies_jurisdiction_concept_id', ['jurisdiction_concept_id'], false, 'btree'],
  ['ad_event_data_policies', 'ix_ad_event_data_policies_purpose_of_use_concept_id', ['purpose_of_use_concept_id'], false, 'btree'],
  ['ad_event_data_policies', 'ix_ad_event_data_policies_consent_scope_concept_id', ['consent_scope_concept_id'], false, 'btree'],
  ['ad_event_data_policies', 'ix_ad_event_data_policies_default_action_concept_id', ['default_action_concept_id'], false, 'btree'],
  ['ad_event_data_policies', 'ix_ad_event_data_policies_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['ad_event_data_policies', 'ix_ad_event_data_policies_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['ad_event_data_policies', 'ix_ad_event_data_policies_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['ad_event_data_policies', 'ix_ad_event_data_policies_tenant_created', ['tenant_id', 'created_at desc'], false, 'btree'],
  ['ad_event_data_policies', 'uk_ad_event_data_policies_tenant_code', ['tenant_id', 'code'], true, 'btree'],
  ['ad_event_field_rules', 'ix_ad_event_field_rules_ad_event_data_policy_id', ['ad_event_data_policy_id'], false, 'btree'],
  ['ad_event_field_rules', 'ix_ad_event_field_rules_action_concept_id', ['action_concept_id'], false, 'btree'],
  ['ad_event_field_rules', 'ix_ad_event_field_rules_transformation_concept_id', ['transformation_concept_id'], false, 'btree'],
  ['ad_event_field_rules', 'ix_ad_event_field_rules_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['ad_event_field_rules', 'ix_ad_event_field_rules_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['ad_event_field_rules', 'ix_ad_event_field_rules_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['ad_event_field_rules', 'uk_ad_event_field_rules_policy_event_field', ['ad_event_data_policy_id', 'event_name_pattern', 'field_path'], true, 'btree'],
  ['ad_experiments', 'ix_ad_experiments_ad_account_id', ['ad_account_id'], false, 'btree'],
  ['ad_experiments', 'ix_ad_experiments_experiment_type_concept_id', ['experiment_type_concept_id'], false, 'btree'],
  ['ad_experiments', 'ix_ad_experiments_objective_metric_concept_id', ['objective_metric_concept_id'], false, 'btree'],
  ['ad_experiments', 'ix_ad_experiments_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['ad_experiments', 'ix_ad_experiments_winner_variant_id', ['winner_variant_id'], false, 'btree'],
  ['ad_experiments', 'ix_ad_experiments_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['ad_experiments', 'ix_ad_experiments_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['ad_identity_asset_assignments', 'ix_ad_identity_asset_assignments_ad_identity_asset_id', ['ad_identity_asset_id'], false, 'btree'],
  ['ad_identity_asset_assignments', 'ix_ad_identity_asset_assignments_assignable_type_concept_id', ['assignable_type_concept_id'], false, 'btree'],
  ['ad_identity_asset_assignments', 'ix_ad_identity_asset_assignments_assignable_id', ['assignable_id'], false, 'btree'],
  ['ad_identity_asset_assignments', 'ix_ad_identity_asset_assignments_assignment_role_concept_id', ['assignment_role_concept_id'], false, 'btree'],
  ['ad_identity_asset_assignments', 'ix_ad_identity_asset_assignments_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['ad_identity_asset_assignments', 'ix_ad_identity_asset_assignments_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['ad_identity_asset_assignments', 'ix_ad_identity_assignments_target', ['assignable_type_concept_id', 'assignable_id', 'effective_to'], false, 'btree'],
  ['ad_identity_assets', 'ix_ad_identity_assets_tenant_id', ['tenant_id'], false, 'btree'],
  ['ad_identity_assets', 'ix_ad_identity_assets_platform_connection_id', ['platform_connection_id'], false, 'btree'],
  ['ad_identity_assets', 'ix_ad_identity_assets_identity_type_concept_id', ['identity_type_concept_id'], false, 'btree'],
  ['ad_identity_assets', 'ix_ad_identity_assets_external_identity_id', ['external_identity_id'], false, 'btree'],
  ['ad_identity_assets', 'ix_ad_identity_assets_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['ad_identity_assets', 'ix_ad_identity_assets_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['ad_identity_assets', 'ix_ad_identity_assets_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['ad_identity_assets', 'ix_ad_identity_assets_tenant_status', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['ad_identity_assets', 'uk_ad_identity_assets_connection_external', ['platform_connection_id', 'identity_type_concept_id', 'external_identity_id'], true, 'btree'],
  ['ad_invoice_lines', 'ix_ad_invoice_lines_ad_invoice_id', ['ad_invoice_id'], false, 'btree'],
  ['ad_invoice_lines', 'ix_ad_invoice_lines_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['ad_invoice_lines', 'ix_ad_invoice_lines_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['ad_invoices', 'uq_ad_invoices_invoice_number', ['invoice_number'], true, 'btree'],
  ['ad_invoices', 'ix_ad_invoices_ad_account_id', ['ad_account_id'], false, 'btree'],
  ['ad_invoices', 'ix_ad_invoices_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['ad_invoices', 'ix_ad_invoices_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['ad_invoices', 'ix_ad_invoices_payment_intent_id', ['payment_intent_id'], false, 'btree'],
  ['ad_invoices', 'ix_ad_invoices_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['ad_invoices', 'ix_ad_invoices_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['ad_partners', 'ix_ad_partners_partner_type_concept_id', ['partner_type_concept_id'], false, 'btree'],
  ['ad_partners', 'ix_ad_partners_tenant_id', ['tenant_id'], false, 'btree'],
  ['ad_partners', 'ix_ad_partners_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['ad_partners', 'ix_ad_partners_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['ad_partners', 'ix_ad_partners_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['ad_partners', 'ix_ad_partners_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['ad_placements', 'ix_ad_placements_ad_set_id', ['ad_set_id'], false, 'btree'],
  ['ad_placements', 'ix_ad_placements_platform_concept_id', ['platform_concept_id'], false, 'btree'],
  ['ad_placements', 'ix_ad_placements_position_concept_id', ['position_concept_id'], false, 'btree'],
  ['ad_placements', 'ix_ad_placements_device_concept_id', ['device_concept_id'], false, 'btree'],
  ['ad_placements', 'ix_ad_placements_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['ad_placements', 'ix_ad_placements_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['ad_platform_connections', 'ix_ad_platform_connections_tenant_id', ['tenant_id'], false, 'btree'],
  ['ad_platform_connections', 'ix_ad_platform_connections_business_manager_id', ['business_manager_id'], false, 'btree'],
  ['ad_platform_connections', 'ix_ad_platform_connections_ad_account_id', ['ad_account_id'], false, 'btree'],
  ['ad_platform_connections', 'ix_ad_platform_connections_platform_concept_id', ['platform_concept_id'], false, 'btree'],
  ['ad_platform_connections', 'ix_ad_platform_connections_credential_id', ['credential_id'], false, 'btree'],
  ['ad_platform_connections', 'ix_ad_platform_connections_external_business_id', ['external_business_id'], false, 'btree'],
  ['ad_platform_connections', 'ix_ad_platform_connections_external_ad_account_id', ['external_ad_account_id'], false, 'btree'],
  ['ad_platform_connections', 'ix_ad_platform_connections_webhook_verification_secret_id', ['webhook_verification_secret_id'], false, 'btree'],
  ['ad_platform_connections', 'ix_ad_platform_connections_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['ad_platform_connections', 'ix_ad_platform_connections_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['ad_platform_connections', 'ix_ad_platform_connections_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['ad_platform_connections', 'ix_ad_platform_connections_tenant_status', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['ad_platform_connections', 'uk_ad_platform_connections_tenant_platform_external', ['tenant_id', 'platform_concept_id', 'external_ad_account_id'], true, 'btree'],
  ['ad_policy_appeals', 'ix_ad_policy_appeals_ad_policy_violation_id', ['ad_policy_violation_id'], false, 'btree'],
  ['ad_policy_appeals', 'ix_ad_policy_appeals_submitted_by_user_id', ['submitted_by_user_id'], false, 'btree'],
  ['ad_policy_appeals', 'ix_ad_policy_appeals_evidence_file_id', ['evidence_file_id'], false, 'btree'],
  ['ad_policy_appeals', 'ix_ad_policy_appeals_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['ad_policy_appeals', 'ix_ad_policy_appeals_external_appeal_id', ['external_appeal_id'], false, 'btree'],
  ['ad_policy_appeals', 'ix_ad_policy_appeals_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['ad_policy_appeals', 'ix_ad_policy_appeals_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['ad_policy_violations', 'ix_ad_policy_violations_ad_id', ['ad_id'], false, 'btree'],
  ['ad_policy_violations', 'ix_ad_policy_violations_ad_review_event_id', ['ad_review_event_id'], false, 'btree'],
  ['ad_policy_violations', 'ix_ad_policy_violations_policy_category_concept_id', ['policy_category_concept_id'], false, 'btree'],
  ['ad_policy_violations', 'ix_ad_policy_violations_severity_concept_id', ['severity_concept_id'], false, 'btree'],
  ['ad_policy_violations', 'ix_ad_policy_violations_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['ad_policy_violations', 'ix_ad_policy_violations_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['ad_policy_violations', 'ix_ad_policy_violations_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['ad_review_events', 'ix_ad_review_events_ad_id', ['ad_id'], false, 'btree'],
  ['ad_review_events', 'ix_ad_review_events_review_event_type_concept_id', ['review_event_type_concept_id'], false, 'btree'],
  ['ad_review_events', 'ix_ad_review_events_review_status_concept_id', ['review_status_concept_id'], false, 'btree'],
  ['ad_review_events', 'ix_ad_review_events_external_review_id', ['external_review_id'], false, 'btree'],
  ['ad_sets', 'ix_ad_sets_campaign_id', ['campaign_id'], false, 'btree'],
  ['ad_sets', 'ix_ad_sets_optimization_goal_concept_id', ['optimization_goal_concept_id'], false, 'btree'],
  ['ad_sets', 'ix_ad_sets_billing_event_concept_id', ['billing_event_concept_id'], false, 'btree'],
  ['ad_sets', 'ix_ad_sets_bid_strategy_concept_id', ['bid_strategy_concept_id'], false, 'btree'],
  ['ad_sets', 'ix_ad_sets_targeting_spec_id', ['targeting_spec_id'], false, 'btree'],
  ['ad_sets', 'ix_ad_sets_pacing_type_concept_id', ['pacing_type_concept_id'], false, 'btree'],
  ['ad_sets', 'ix_ad_sets_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['ad_sets', 'ix_ad_sets_effective_status_concept_id', ['effective_status_concept_id'], false, 'btree'],
  ['ad_sets', 'ix_ad_sets_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['ad_sets', 'ix_ad_sets_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['ad_sync_checkpoints', 'ix_ad_sync_checkpoints_platform_connection_id', ['platform_connection_id'], false, 'btree'],
  ['ad_sync_checkpoints', 'ix_ad_sync_checkpoints_object_type_concept_id', ['object_type_concept_id'], false, 'btree'],
  ['ad_sync_checkpoints', 'uk_ad_sync_checkpoints_connection_object_key', ['platform_connection_id', 'object_type_concept_id', 'checkpoint_key'], true, 'btree'],
  ['ad_sync_runs', 'ix_ad_sync_runs_platform_connection_id', ['platform_connection_id'], false, 'btree'],
  ['ad_sync_runs', 'ix_ad_sync_runs_sync_direction_concept_id', ['sync_direction_concept_id'], false, 'btree'],
  ['ad_sync_runs', 'ix_ad_sync_runs_object_type_concept_id', ['object_type_concept_id'], false, 'btree'],
  ['ad_sync_runs', 'ix_ad_sync_runs_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['ads', 'ix_ads_ad_set_id', ['ad_set_id'], false, 'btree'],
  ['ads', 'ix_ads_creative_id', ['creative_id'], false, 'btree'],
  ['ads', 'ix_ads_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['ads', 'ix_ads_effective_status_concept_id', ['effective_status_concept_id'], false, 'btree'],
  ['ads', 'ix_ads_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['ads', 'ix_ads_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['adset_learning_snapshots', 'ix_adset_learning_snapshots_ad_set_id', ['ad_set_id'], false, 'btree'],
  ['adset_learning_snapshots', 'ix_adset_learning_snapshots_learning_status_concept_id', ['learning_status_concept_id'], false, 'btree'],
  ['adset_learning_snapshots', 'ix_adset_learning_snapshots_limited_reason_concept_id', ['limited_reason_concept_id'], false, 'btree'],
  ['attribution_settings', 'ix_attribution_settings_ad_account_id', ['ad_account_id'], false, 'btree'],
  ['attribution_settings', 'ix_attribution_settings_attribution_model_concept_id', ['attribution_model_concept_id'], false, 'btree'],
  ['attribution_settings', 'ix_attribution_settings_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['attribution_settings', 'ix_attribution_settings_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['automated_rules', 'ix_automated_rules_ad_account_id', ['ad_account_id'], false, 'btree'],
  ['automated_rules', 'ix_automated_rules_scope_concept_id', ['scope_concept_id'], false, 'btree'],
  ['automated_rules', 'ix_automated_rules_action_concept_id', ['action_concept_id'], false, 'btree'],
  ['automated_rules', 'ix_automated_rules_evaluation_schedule_concept_id', ['evaluation_schedule_concept_id'], false, 'btree'],
  ['automated_rules', 'ix_automated_rules_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['automated_rules', 'ix_automated_rules_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['automated_rules', 'ix_automated_rules_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['blocked_ad_events', 'ix_blocked_ad_events_tenant_id', ['tenant_id'], false, 'btree'],
  ['blocked_ad_events', 'ix_blocked_ad_events_ad_event_data_policy_id', ['ad_event_data_policy_id'], false, 'btree'],
  ['blocked_ad_events', 'ix_blocked_ad_events_reason_concept_id', ['reason_concept_id'], false, 'btree'],
  ['blocked_ad_events', 'ix_blocked_ad_events_review_status_concept_id', ['review_status_concept_id'], false, 'btree'],
  ['blocked_ad_events', 'ix_blocked_ad_events_tenant_created', ['tenant_id', 'created_at desc'], false, 'btree'],
  ['brand_lift_studies', 'ix_brand_lift_studies_ad_account_id', ['ad_account_id'], false, 'btree'],
  ['brand_lift_studies', 'ix_brand_lift_studies_campaign_id', ['campaign_id'], false, 'btree'],
  ['brand_lift_studies', 'ix_brand_lift_studies_metric_concept_id', ['metric_concept_id'], false, 'btree'],
  ['brand_lift_studies', 'ix_brand_lift_studies_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['brand_lift_studies', 'ix_brand_lift_studies_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['brand_lift_studies', 'ix_brand_lift_studies_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['budget_schedules', 'ix_budget_schedules_entity_type_concept_id', ['entity_type_concept_id'], false, 'btree'],
  ['budget_schedules', 'ix_budget_schedules_budget_type_concept_id', ['budget_type_concept_id'], false, 'btree'],
  ['budget_schedules', 'ix_budget_schedules_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['budget_schedules', 'ix_budget_schedules_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['budget_schedules', 'ix_budget_schedules_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['budget_schedules', 'ix_budget_schedules_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['business_managers', 'uq_business_managers_external_business_ref', ['external_business_ref'], true, 'btree'],
  ['business_managers', 'ix_business_managers_tenant_id', ['tenant_id'], false, 'btree'],
  ['business_managers', 'ix_business_managers_owner_user_id', ['owner_user_id'], false, 'btree'],
  ['business_managers', 'ix_business_managers_vertical_concept_id', ['vertical_concept_id'], false, 'btree'],
  ['business_managers', 'ix_business_managers_primary_country_concept_id', ['primary_country_concept_id'], false, 'btree'],
  ['business_managers', 'ix_business_managers_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['business_managers', 'ix_business_managers_created_by_user_id', ['created_by_user_id'], false, 'btree'],
];
