import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `audit` (parte 4/4).
 * 103 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const auditIndexes4: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['record_automations_history', 'ix_record_automations_history_change_reason_concept_id', ['change_reason_concept_id'], false, 'btree'],
  ['record_automations_history', 'brin_record_automations_history_recorded_at', ['recorded_at'], false, 'brin'],
  ['referrals_history', 'ix_referrals_history_referral_id', ['referral_id'], false, 'btree'],
  ['referrals_history', 'ix_referrals_history_operation_concept_id', ['operation_concept_id'], false, 'btree'],
  ['referrals_history', 'ix_referrals_history_changed_by_user_id', ['changed_by_user_id'], false, 'btree'],
  ['referrals_history', 'ix_referrals_history_change_reason_concept_id', ['change_reason_concept_id'], false, 'btree'],
  ['referrals_history', 'brin_referrals_history_recorded_at', ['recorded_at'], false, 'brin'],
  ['referral_programs_history', 'ix_referral_programs_history_referral_programs_id', ['referral_programs_id'], false, 'btree'],
  ['referral_programs_history', 'ix_referral_programs_history_operation_concept_id', ['operation_concept_id'], false, 'btree'],
  ['referral_programs_history', 'ix_referral_programs_history_changed_by_user_id', ['changed_by_user_id'], false, 'btree'],
  ['referral_programs_history', 'ix_referral_programs_history_change_reason_concept_id', ['change_reason_concept_id'], false, 'btree'],
  ['referral_programs_history', 'brin_referral_programs_history_recorded_at', ['recorded_at'], false, 'brin'],
  ['report_definitions_history', 'ix_report_definitions_history_report_definition_id', ['report_definition_id'], false, 'btree'],
  ['report_definitions_history', 'ix_report_definitions_history_operation_concept_id', ['operation_concept_id'], false, 'btree'],
  ['report_definitions_history', 'ix_report_definitions_history_changed_by_user_id', ['changed_by_user_id'], false, 'btree'],
  ['report_definitions_history', 'ix_report_definitions_history_change_reason_concept_id', ['change_reason_concept_id'], false, 'btree'],
  ['report_definitions_history', 'brin_report_definitions_history_recorded_at', ['recorded_at'], false, 'brin'],
  ['report_schedules_history', 'ix_report_schedules_history_report_schedule_id', ['report_schedule_id'], false, 'btree'],
  ['report_schedules_history', 'ix_report_schedules_history_operation_concept_id', ['operation_concept_id'], false, 'btree'],
  ['report_schedules_history', 'ix_report_schedules_history_changed_by_user_id', ['changed_by_user_id'], false, 'btree'],
  ['report_schedules_history', 'ix_report_schedules_history_change_reason_concept_id', ['change_reason_concept_id'], false, 'btree'],
  ['report_schedules_history', 'brin_report_schedules_history_recorded_at', ['recorded_at'], false, 'brin'],
  ['schedule_templates_history', 'ix_schedule_templates_history_schedule_template_id', ['schedule_template_id'], false, 'btree'],
  ['schedule_templates_history', 'ix_schedule_templates_history_operation_concept_id', ['operation_concept_id'], false, 'btree'],
  ['schedule_templates_history', 'ix_schedule_templates_history_changed_by_user_id', ['changed_by_user_id'], false, 'btree'],
  ['schedule_templates_history', 'ix_schedule_templates_history_change_reason_concept_id', ['change_reason_concept_id'], false, 'btree'],
  ['schedule_templates_history', 'brin_schedule_templates_history_recorded_at', ['recorded_at'], false, 'brin'],
  ['segments_history', 'ix_segments_history_segments_id', ['segments_id'], false, 'btree'],
  ['segments_history', 'ix_segments_history_operation_concept_id', ['operation_concept_id'], false, 'btree'],
  ['segments_history', 'ix_segments_history_changed_by_user_id', ['changed_by_user_id'], false, 'btree'],
  ['segments_history', 'ix_segments_history_change_reason_concept_id', ['change_reason_concept_id'], false, 'btree'],
  ['segments_history', 'brin_segments_history_recorded_at', ['recorded_at'], false, 'brin'],
  ['service_reviews_history', 'ix_service_reviews_history_service_review_id', ['service_review_id'], false, 'btree'],
  ['service_reviews_history', 'ix_service_reviews_history_operation_concept_id', ['operation_concept_id'], false, 'btree'],
  ['service_reviews_history', 'ix_service_reviews_history_changed_by_user_id', ['changed_by_user_id'], false, 'btree'],
  ['service_reviews_history', 'ix_service_reviews_history_change_reason_concept_id', ['change_reason_concept_id'], false, 'btree'],
  ['service_reviews_history', 'brin_service_reviews_history_recorded_at', ['recorded_at'], false, 'brin'],
  ['shipments_history', 'ix_shipments_history_shipment_id', ['shipment_id'], false, 'btree'],
  ['shipments_history', 'ix_shipments_history_operation_concept_id', ['operation_concept_id'], false, 'btree'],
  ['shipments_history', 'ix_shipments_history_changed_by_user_id', ['changed_by_user_id'], false, 'btree'],
  ['shipments_history', 'ix_shipments_history_change_reason_concept_id', ['change_reason_concept_id'], false, 'btree'],
  ['shipments_history', 'brin_shipments_history_recorded_at', ['recorded_at'], false, 'brin'],
  ['social_posts_history', 'ix_social_posts_history_social_post_id', ['social_post_id'], false, 'btree'],
  ['social_posts_history', 'ix_social_posts_history_operation_concept_id', ['operation_concept_id'], false, 'btree'],
  ['social_posts_history', 'ix_social_posts_history_changed_by_user_id', ['changed_by_user_id'], false, 'btree'],
  ['social_posts_history', 'ix_social_posts_history_change_reason_concept_id', ['change_reason_concept_id'], false, 'btree'],
  ['social_posts_history', 'brin_social_posts_history_recorded_at', ['recorded_at'], false, 'brin'],
  ['subscriptions_history', 'ix_subscriptions_history_subscriptions_id', ['subscriptions_id'], false, 'btree'],
  ['subscriptions_history', 'ix_subscriptions_history_operation_concept_id', ['operation_concept_id'], false, 'btree'],
  ['subscriptions_history', 'ix_subscriptions_history_changed_by_user_id', ['changed_by_user_id'], false, 'btree'],
  ['subscriptions_history', 'ix_subscriptions_history_change_reason_concept_id', ['change_reason_concept_id'], false, 'btree'],
  ['subscriptions_history', 'brin_subscriptions_history_recorded_at', ['recorded_at'], false, 'brin'],
  ['subscription_plans_history', 'ix_subscription_plans_history_subscription_plans_id', ['subscription_plans_id'], false, 'btree'],
  ['subscription_plans_history', 'ix_subscription_plans_history_operation_concept_id', ['operation_concept_id'], false, 'btree'],
  ['subscription_plans_history', 'ix_subscription_plans_history_changed_by_user_id', ['changed_by_user_id'], false, 'btree'],
  ['subscription_plans_history', 'ix_subscription_plans_history_change_reason_concept_id', ['change_reason_concept_id'], false, 'btree'],
  ['subscription_plans_history', 'brin_subscription_plans_history_recorded_at', ['recorded_at'], false, 'brin'],
  ['tenants_history', 'ix_tenants_history_tenant_id', ['tenant_id'], false, 'btree'],
  ['tenants_history', 'ix_tenants_history_operation_concept_id', ['operation_concept_id'], false, 'btree'],
  ['tenants_history', 'ix_tenants_history_changed_by_user_id', ['changed_by_user_id'], false, 'btree'],
  ['tenants_history', 'ix_tenants_history_change_reason_concept_id', ['change_reason_concept_id'], false, 'btree'],
  ['tenants_history', 'ix_tenants_history_tenant_id_recorded_at', ['tenant_id', 'recorded_at desc'], false, 'btree'],
  ['tenants_history', 'brin_tenants_history_recorded_at', ['recorded_at'], false, 'brin'],
  ['test_cases_history', 'ix_test_cases_history_test_case_id', ['test_case_id'], false, 'btree'],
  ['test_cases_history', 'ix_test_cases_history_operation_concept_id', ['operation_concept_id'], false, 'btree'],
  ['test_cases_history', 'ix_test_cases_history_changed_by_user_id', ['changed_by_user_id'], false, 'btree'],
  ['test_cases_history', 'ix_test_cases_history_change_reason_concept_id', ['change_reason_concept_id'], false, 'btree'],
  ['test_cases_history', 'brin_test_cases_history_recorded_at', ['recorded_at'], false, 'brin'],
  ['test_suites_history', 'ix_test_suites_history_test_suite_id', ['test_suite_id'], false, 'btree'],
  ['test_suites_history', 'ix_test_suites_history_operation_concept_id', ['operation_concept_id'], false, 'btree'],
  ['test_suites_history', 'ix_test_suites_history_changed_by_user_id', ['changed_by_user_id'], false, 'btree'],
  ['test_suites_history', 'ix_test_suites_history_change_reason_concept_id', ['change_reason_concept_id'], false, 'btree'],
  ['test_suites_history', 'brin_test_suites_history_recorded_at', ['recorded_at'], false, 'brin'],
  ['topics_history', 'ix_topics_history_topics_id', ['topics_id'], false, 'btree'],
  ['topics_history', 'ix_topics_history_operation_concept_id', ['operation_concept_id'], false, 'btree'],
  ['topics_history', 'ix_topics_history_changed_by_user_id', ['changed_by_user_id'], false, 'btree'],
  ['topics_history', 'ix_topics_history_change_reason_concept_id', ['change_reason_concept_id'], false, 'btree'],
  ['topics_history', 'brin_topics_history_recorded_at', ['recorded_at'], false, 'brin'],
  ['trackable_subjects_history', 'ix_trackable_subjects_history_trackable_subject_id', ['trackable_subject_id'], false, 'btree'],
  ['trackable_subjects_history', 'ix_trackable_subjects_history_operation_concept_id', ['operation_concept_id'], false, 'btree'],
  ['trackable_subjects_history', 'ix_trackable_subjects_history_changed_by_user_id', ['changed_by_user_id'], false, 'btree'],
  ['trackable_subjects_history', 'ix_trackable_subjects_history_change_reason_concept_id', ['change_reason_concept_id'], false, 'btree'],
  ['trackable_subjects_history', 'brin_trackable_subjects_history_recorded_at', ['recorded_at'], false, 'brin'],
  ['users_history', 'ix_users_history_user_id', ['user_id'], false, 'btree'],
  ['users_history', 'ix_users_history_operation_concept_id', ['operation_concept_id'], false, 'btree'],
  ['users_history', 'ix_users_history_changed_by_user_id', ['changed_by_user_id'], false, 'btree'],
  ['users_history', 'ix_users_history_change_reason_concept_id', ['change_reason_concept_id'], false, 'btree'],
  ['users_history', 'brin_users_history_recorded_at', ['recorded_at'], false, 'brin'],
  ['verified_badges_history', 'ix_verified_badges_history_verified_badges_id', ['verified_badges_id'], false, 'btree'],
  ['verified_badges_history', 'ix_verified_badges_history_operation_concept_id', ['operation_concept_id'], false, 'btree'],
  ['verified_badges_history', 'ix_verified_badges_history_changed_by_user_id', ['changed_by_user_id'], false, 'btree'],
  ['verified_badges_history', 'ix_verified_badges_history_change_reason_concept_id', ['change_reason_concept_id'], false, 'btree'],
  ['verified_badges_history', 'brin_verified_badges_history_recorded_at', ['recorded_at'], false, 'brin'],
  ['wallets_history', 'ix_wallets_history_wallets_id', ['wallets_id'], false, 'btree'],
  ['wallets_history', 'ix_wallets_history_operation_concept_id', ['operation_concept_id'], false, 'btree'],
  ['wallets_history', 'ix_wallets_history_changed_by_user_id', ['changed_by_user_id'], false, 'btree'],
  ['wallets_history', 'ix_wallets_history_change_reason_concept_id', ['change_reason_concept_id'], false, 'btree'],
  ['wallets_history', 'brin_wallets_history_recorded_at', ['recorded_at'], false, 'brin'],
  ['workflows_history', 'ix_workflows_history_workflows_id', ['workflows_id'], false, 'btree'],
  ['workflows_history', 'ix_workflows_history_operation_concept_id', ['operation_concept_id'], false, 'btree'],
  ['workflows_history', 'ix_workflows_history_changed_by_user_id', ['changed_by_user_id'], false, 'btree'],
  ['workflows_history', 'ix_workflows_history_change_reason_concept_id', ['change_reason_concept_id'], false, 'btree'],
  ['workflows_history', 'brin_workflows_history_recorded_at', ['recorded_at'], false, 'brin'],
];
