import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `auth_providers`.
 * 57 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const authProvidersIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['account_link_requests', 'uq_account_link_requests_link_token_hash', ['link_token_hash'], true, 'btree'],
  ['account_link_requests', 'ix_account_link_requests_provider_id', ['provider_id'], false, 'btree'],
  ['account_link_requests', 'ix_account_link_requests_user_id', ['user_id'], false, 'btree'],
  ['account_link_requests', 'ix_account_link_requests_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['account_link_requests', 'ix_account_link_requests_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['account_link_requests', 'ix_account_link_requests_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['federated_identities', 'uq_federated_identities_external_subject', ['external_subject'], true, 'btree'],
  ['federated_identities', 'ix_federated_identities_provider_id', ['provider_id'], false, 'btree'],
  ['federated_identities', 'ix_federated_identities_user_id', ['user_id'], false, 'btree'],
  ['federated_identities', 'ix_federated_identities_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['federated_identities', 'ix_federated_identities_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['federated_identities', 'ix_federated_identities_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['federated_login_attempts', 'ix_federated_login_attempts_provider_id', ['provider_id'], false, 'btree'],
  ['federated_login_attempts', 'ix_federated_login_attempts_tenant_id', ['tenant_id'], false, 'btree'],
  ['federated_login_attempts', 'ix_federated_login_attempts_user_id', ['user_id'], false, 'btree'],
  ['federated_login_attempts', 'ix_federated_login_attempts_outcome_concept_id', ['outcome_concept_id'], false, 'btree'],
  ['federated_login_attempts', 'ix_federated_login_attempts_failure_reason_concept_id', ['failure_reason_concept_id'], false, 'btree'],
  ['federated_login_attempts', 'ix_federated_login_attempts_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['federated_login_attempts', 'ix_federated_login_attempts_tenant_id_recorded_at', ['tenant_id', 'recorded_at desc'], false, 'btree'],
  ['identity_providers', 'uq_identity_providers_code', ['code'], true, 'btree'],
  ['identity_providers', 'ix_identity_providers_tenant_id', ['tenant_id'], false, 'btree'],
  ['identity_providers', 'ix_identity_providers_protocol_concept_id', ['protocol_concept_id'], false, 'btree'],
  ['identity_providers', 'ix_identity_providers_provider_category_concept_id', ['provider_category_concept_id'], false, 'btree'],
  ['identity_providers', 'ix_identity_providers_logo_file_id', ['logo_file_id'], false, 'btree'],
  ['identity_providers', 'ix_identity_providers_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['identity_providers', 'ix_identity_providers_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['identity_providers', 'ix_identity_providers_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['identity_providers', 'ix_identity_providers_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['provider_attribute_mappings', 'ix_provider_attribute_mappings_provider_id', ['provider_id'], false, 'btree'],
  ['provider_attribute_mappings', 'ix_provider_attribute_mappings_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['provider_attribute_mappings', 'ix_provider_attribute_mappings_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['provider_protocol_configs', 'ix_provider_protocol_configs_provider_id', ['provider_id'], false, 'btree'],
  ['provider_protocol_configs', 'ix_provider_protocol_configs_environment_concept_id', ['environment_concept_id'], false, 'btree'],
  ['provider_protocol_configs', 'ix_provider_protocol_configs_token_endpoint_auth_concept_id', ['token_endpoint_auth_concept_id'], false, 'btree'],
  ['provider_protocol_configs', 'ix_provider_protocol_configs_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['provider_protocol_configs', 'ix_provider_protocol_configs_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['provider_protocol_configs', 'ix_provider_protocol_configs_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['provider_signing_keys', 'ix_provider_signing_keys_provider_id', ['provider_id'], false, 'btree'],
  ['provider_signing_keys', 'ix_provider_signing_keys_key_use_concept_id', ['key_use_concept_id'], false, 'btree'],
  ['provider_signing_keys', 'ix_provider_signing_keys_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['provider_signing_keys', 'ix_provider_signing_keys_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['provider_signing_keys', 'ix_provider_signing_keys_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['provider_tenant_bindings', 'ix_provider_tenant_bindings_provider_id', ['provider_id'], false, 'btree'],
  ['provider_tenant_bindings', 'ix_provider_tenant_bindings_tenant_id', ['tenant_id'], false, 'btree'],
  ['provider_tenant_bindings', 'ix_provider_tenant_bindings_default_role_concept_id', ['default_role_concept_id'], false, 'btree'],
  ['provider_tenant_bindings', 'ix_provider_tenant_bindings_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['provider_tenant_bindings', 'ix_provider_tenant_bindings_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['provider_tenant_bindings', 'ix_provider_tenant_bindings_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['provider_tenant_bindings', 'ix_provider_tenant_bindings_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['provisioning_rules', 'ix_provisioning_rules_provider_id', ['provider_id'], false, 'btree'],
  ['provisioning_rules', 'ix_provisioning_rules_tenant_id', ['tenant_id'], false, 'btree'],
  ['provisioning_rules', 'ix_provisioning_rules_assign_role_concept_id', ['assign_role_concept_id'], false, 'btree'],
  ['provisioning_rules', 'ix_provisioning_rules_assign_tenant_id', ['assign_tenant_id'], false, 'btree'],
  ['provisioning_rules', 'ix_provisioning_rules_effect_concept_id', ['effect_concept_id'], false, 'btree'],
  ['provisioning_rules', 'ix_provisioning_rules_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['provisioning_rules', 'ix_provisioning_rules_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['provisioning_rules', 'ix_provisioning_rules_tenant_id_updated_at', ['tenant_id', 'updated_at desc'], false, 'btree'],
];
