import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `authz`.
 * 76 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const authzIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['access_policies', 'ix_access_policies_tenant_id', ['tenant_id'], false, 'btree'],
  ['access_policies', 'ix_access_policies_effect_concept_id', ['effect_concept_id'], false, 'btree'],
  ['access_policies', 'ix_access_policies_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['access_policies', 'ix_access_policies_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['access_policies', 'ix_access_policies_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['access_policies', 'ix_access_policies_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['clinical_access_grants', 'ix_clinical_access_grants_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['clinical_access_grants', 'ix_clinical_access_grants_granted_user_id', ['granted_user_id'], false, 'btree'],
  ['clinical_access_grants', 'ix_clinical_access_grants_tenant_id', ['tenant_id'], false, 'btree'],
  ['clinical_access_grants', 'ix_clinical_access_grants_branch_id', ['branch_id'], false, 'btree'],
  ['clinical_access_grants', 'ix_clinical_access_grants_encounter_id', ['encounter_id'], false, 'btree'],
  ['clinical_access_grants', 'ix_clinical_access_grants_consent_id', ['consent_id'], false, 'btree'],
  ['clinical_access_grants', 'ix_clinical_access_grants_reason_concept_id', ['reason_concept_id'], false, 'btree'],
  ['clinical_access_grants', 'ix_clinical_access_grants_access_level_concept_id', ['access_level_concept_id'], false, 'btree'],
  ['clinical_access_grants', 'ix_clinical_access_grants_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['clinical_access_grants', 'ix_clinical_access_grants_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['clinical_access_grants', 'ix_clinical_access_grants_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['clinical_access_grants', 'ix_clinical_access_grants_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['clinical_access_grants', 'ix_clinical_access_grants_patient_profile_id_updated_at', ['tenant_id', 'patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['field_permissions', 'ix_field_permissions_role_id', ['role_id'], false, 'btree'],
  ['field_permissions', 'ix_field_permissions_mask_strategy_concept_id', ['mask_strategy_concept_id'], false, 'btree'],
  ['field_permissions', 'ix_field_permissions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['field_permissions', 'ix_field_permissions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['permission_categories', 'uq_permission_categories_code', ['code'], true, 'btree'],
  ['permission_categories', 'ix_permission_categories_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['permission_categories', 'ix_permission_categories_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['permissions', 'uq_permissions_code', ['code'], true, 'btree'],
  ['permissions', 'ix_permissions_category_id', ['category_id'], false, 'btree'],
  ['permissions', 'ix_permissions_action_concept_id', ['action_concept_id'], false, 'btree'],
  ['permissions', 'ix_permissions_default_scope_concept_id', ['default_scope_concept_id'], false, 'btree'],
  ['permissions', 'ix_permissions_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['permissions', 'ix_permissions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['permissions', 'ix_permissions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['resource_scope_grants', 'ix_resource_scope_grants_subject_type_concept_id', ['subject_type_concept_id'], false, 'btree'],
  ['resource_scope_grants', 'ix_resource_scope_grants_permission_id', ['permission_id'], false, 'btree'],
  ['resource_scope_grants', 'ix_resource_scope_grants_resource_type_concept_id', ['resource_type_concept_id'], false, 'btree'],
  ['resource_scope_grants', 'ix_resource_scope_grants_effect_concept_id', ['effect_concept_id'], false, 'btree'],
  ['resource_scope_grants', 'ix_resource_scope_grants_tenant_id', ['tenant_id'], false, 'btree'],
  ['resource_scope_grants', 'ix_resource_scope_grants_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['resource_scope_grants', 'ix_resource_scope_grants_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['resource_scope_grants', 'ix_resource_scope_grants_tenant_id_updated_at', ['tenant_id', 'updated_at desc'], false, 'btree'],
  ['role_permissions', 'ix_role_permissions_role_id', ['role_id'], false, 'btree'],
  ['role_permissions', 'ix_role_permissions_permission_id', ['permission_id'], false, 'btree'],
  ['role_permissions', 'ix_role_permissions_effect_concept_id', ['effect_concept_id'], false, 'btree'],
  ['role_permissions', 'ix_role_permissions_scope_concept_id', ['scope_concept_id'], false, 'btree'],
  ['role_permissions', 'ix_role_permissions_field_value_set_id', ['field_value_set_id'], false, 'btree'],
  ['role_permissions', 'ix_role_permissions_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['role_permissions', 'ix_role_permissions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['role_permissions', 'ix_role_permissions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['roles', 'ix_roles_tenant_id', ['tenant_id'], false, 'btree'],
  ['roles', 'ix_roles_parent_role_id', ['parent_role_id'], false, 'btree'],
  ['roles', 'ix_roles_base_role_concept_id', ['base_role_concept_id'], false, 'btree'],
  ['roles', 'ix_roles_scope_concept_id', ['scope_concept_id'], false, 'btree'],
  ['roles', 'ix_roles_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['roles', 'ix_roles_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['roles', 'ix_roles_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['roles', 'ix_roles_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['user_permission_grants', 'ix_user_permission_grants_user_id', ['user_id'], false, 'btree'],
  ['user_permission_grants', 'ix_user_permission_grants_permission_id', ['permission_id'], false, 'btree'],
  ['user_permission_grants', 'ix_user_permission_grants_effect_concept_id', ['effect_concept_id'], false, 'btree'],
  ['user_permission_grants', 'ix_user_permission_grants_scope_concept_id', ['scope_concept_id'], false, 'btree'],
  ['user_permission_grants', 'ix_user_permission_grants_tenant_id', ['tenant_id'], false, 'btree'],
  ['user_permission_grants', 'ix_user_permission_grants_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['user_permission_grants', 'ix_user_permission_grants_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['user_permission_grants', 'ix_user_permission_grants_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['user_permission_grants', 'ix_user_permission_grants_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['user_role_assignments', 'ix_user_role_assignments_user_id', ['user_id'], false, 'btree'],
  ['user_role_assignments', 'ix_user_role_assignments_role_id', ['role_id'], false, 'btree'],
  ['user_role_assignments', 'ix_user_role_assignments_tenant_id', ['tenant_id'], false, 'btree'],
  ['user_role_assignments', 'ix_user_role_assignments_branch_id', ['branch_id'], false, 'btree'],
  ['user_role_assignments', 'ix_user_role_assignments_practice_id', ['practice_id'], false, 'btree'],
  ['user_role_assignments', 'ix_user_role_assignments_assigned_by_user_id', ['assigned_by_user_id'], false, 'btree'],
  ['user_role_assignments', 'ix_user_role_assignments_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['user_role_assignments', 'ix_user_role_assignments_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['user_role_assignments', 'ix_user_role_assignments_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['user_role_assignments', 'ix_user_role_assignments_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
];
