import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `automation`.
 * 112 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const automationIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['agent_guardrails', 'ix_agent_guardrails_agent_id', ['agent_id'], false, 'btree'],
  ['agent_guardrails', 'ix_agent_guardrails_guardrail_policy_id', ['guardrail_policy_id'], false, 'btree'],
  ['agent_guardrails', 'ix_agent_guardrails_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['agent_guardrails', 'ix_agent_guardrails_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['agent_memory', 'ix_agent_memory_agent_id', ['agent_id'], false, 'btree'],
  ['agent_memory', 'ix_agent_memory_scope_concept_id', ['scope_concept_id'], false, 'btree'],
  ['agent_memory', 'ix_agent_memory_memory_type_concept_id', ['memory_type_concept_id'], false, 'btree'],
  ['agent_memory', 'ix_agent_memory_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['agent_memory', 'ix_agent_memory_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['agent_memory', 'ix_agent_memory_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['agent_run_steps', 'ix_agent_run_steps_agent_run_id', ['agent_run_id'], false, 'btree'],
  ['agent_run_steps', 'ix_agent_run_steps_step_kind_concept_id', ['step_kind_concept_id'], false, 'btree'],
  ['agent_run_steps', 'ix_agent_run_steps_agent_tool_id', ['agent_tool_id'], false, 'btree'],
  ['agent_run_steps', 'ix_agent_run_steps_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['agent_run_steps', 'ix_agent_run_steps_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['agent_runs', 'ix_agent_runs_workflow_run_id', ['workflow_run_id'], false, 'btree'],
  ['agent_runs', 'ix_agent_runs_agent_id', ['agent_id'], false, 'btree'],
  ['agent_runs', 'ix_agent_runs_agent_version_id', ['agent_version_id'], false, 'btree'],
  ['agent_runs', 'ix_agent_runs_task_type_concept_id', ['task_type_concept_id'], false, 'btree'],
  ['agent_runs', 'ix_agent_runs_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['agent_runs', 'ix_agent_runs_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['agent_runs', 'ix_agent_runs_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['agent_tool_bindings', 'ix_agent_tool_bindings_agent_version_id', ['agent_version_id'], false, 'btree'],
  ['agent_tool_bindings', 'ix_agent_tool_bindings_agent_tool_id', ['agent_tool_id'], false, 'btree'],
  ['agent_tool_bindings', 'ix_agent_tool_bindings_permission_effect_concept_id', ['permission_effect_concept_id'], false, 'btree'],
  ['agent_tool_bindings', 'ix_agent_tool_bindings_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['agent_tool_bindings', 'ix_agent_tool_bindings_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['agent_tools', 'uq_agent_tools_code', ['code'], true, 'btree'],
  ['agent_tools', 'ix_agent_tools_tool_type_concept_id', ['tool_type_concept_id'], false, 'btree'],
  ['agent_tools', 'ix_agent_tools_integration_endpoint_id', ['integration_endpoint_id'], false, 'btree'],
  ['agent_tools', 'ix_agent_tools_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['agent_tools', 'ix_agent_tools_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['agent_tools', 'ix_agent_tools_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['agent_versions', 'ix_agent_versions_agent_id', ['agent_id'], false, 'btree'],
  ['agent_versions', 'ix_agent_versions_model_concept_id', ['model_concept_id'], false, 'btree'],
  ['agent_versions', 'ix_agent_versions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['agent_versions', 'ix_agent_versions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['agent_versions', 'ix_agent_versions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['agent_versions', 'uq_agent_versions_agent_id_version', ['agent_id', 'version'], true, 'btree'],
  ['agents', 'uq_agents_code', ['code'], true, 'btree'],
  ['agents', 'ix_agents_tenant_id', ['tenant_id'], false, 'btree'],
  ['agents', 'ix_agents_agent_type_concept_id', ['agent_type_concept_id'], false, 'btree'],
  ['agents', 'ix_agents_default_model_concept_id', ['default_model_concept_id'], false, 'btree'],
  ['agents', 'ix_agents_system_service_component_id', ['system_service_component_id'], false, 'btree'],
  ['agents', 'ix_agents_autonomy_level_concept_id', ['autonomy_level_concept_id'], false, 'btree'],
  ['agents', 'ix_agents_acts_as_user_id', ['acts_as_user_id'], false, 'btree'],
  ['agents', 'ix_agents_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['agents', 'ix_agents_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['agents', 'ix_agents_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['agents', 'ix_agents_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['automation_approvals', 'ix_automation_approvals_agent_run_id', ['agent_run_id'], false, 'btree'],
  ['automation_approvals', 'ix_automation_approvals_agent_run_step_id', ['agent_run_step_id'], false, 'btree'],
  ['automation_approvals', 'ix_automation_approvals_approval_type_concept_id', ['approval_type_concept_id'], false, 'btree'],
  ['automation_approvals', 'ix_automation_approvals_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['automation_approvals', 'ix_automation_approvals_decided_by_user_id', ['decided_by_user_id'], false, 'btree'],
  ['automation_approvals', 'ix_automation_approvals_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['automation_approvals', 'ix_automation_approvals_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['automation_triggers', 'uq_automation_triggers_code', ['code'], true, 'btree'],
  ['automation_triggers', 'ix_automation_triggers_tenant_id', ['tenant_id'], false, 'btree'],
  ['automation_triggers', 'ix_automation_triggers_trigger_type_concept_id', ['trigger_type_concept_id'], false, 'btree'],
  ['automation_triggers', 'ix_automation_triggers_workflow_id', ['workflow_id'], false, 'btree'],
  ['automation_triggers', 'ix_automation_triggers_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['automation_triggers', 'ix_automation_triggers_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['automation_triggers', 'ix_automation_triggers_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['automation_triggers', 'ix_automation_triggers_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['guardrail_policies', 'uq_guardrail_policies_code', ['code'], true, 'btree'],
  ['guardrail_policies', 'ix_guardrail_policies_tenant_id', ['tenant_id'], false, 'btree'],
  ['guardrail_policies', 'ix_guardrail_policies_policy_type_concept_id', ['policy_type_concept_id'], false, 'btree'],
  ['guardrail_policies', 'ix_guardrail_policies_pii_phi_handling_concept_id', ['pii_phi_handling_concept_id'], false, 'btree'],
  ['guardrail_policies', 'ix_guardrail_policies_enforcement_concept_id', ['enforcement_concept_id'], false, 'btree'],
  ['guardrail_policies', 'ix_guardrail_policies_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['guardrail_policies', 'ix_guardrail_policies_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['guardrail_policies', 'ix_guardrail_policies_tenant_id_updated_at', ['tenant_id', 'updated_at desc'], false, 'btree'],
  ['knowledge_sources', 'ix_knowledge_sources_tenant_id', ['tenant_id'], false, 'btree'],
  ['knowledge_sources', 'ix_knowledge_sources_source_type_concept_id', ['source_type_concept_id'], false, 'btree'],
  ['knowledge_sources', 'ix_knowledge_sources_file_id', ['file_id'], false, 'btree'],
  ['knowledge_sources', 'ix_knowledge_sources_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['knowledge_sources', 'ix_knowledge_sources_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['knowledge_sources', 'ix_knowledge_sources_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['knowledge_sources', 'ix_knowledge_sources_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['record_automations', 'ix_record_automations_tenant_id', ['tenant_id'], false, 'btree'],
  ['record_automations', 'ix_record_automations_automation_action_concept_id', ['automation_action_concept_id'], false, 'btree'],
  ['record_automations', 'ix_record_automations_agent_id', ['agent_id'], false, 'btree'],
  ['record_automations', 'ix_record_automations_workflow_id', ['workflow_id'], false, 'btree'],
  ['record_automations', 'ix_record_automations_write_mode_concept_id', ['write_mode_concept_id'], false, 'btree'],
  ['record_automations', 'ix_record_automations_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['record_automations', 'ix_record_automations_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['record_automations', 'ix_record_automations_tenant_id_updated_at', ['tenant_id', 'updated_at desc'], false, 'btree'],
  ['workflow_runs', 'uq_workflow_runs_run_number', ['run_number'], true, 'btree'],
  ['workflow_runs', 'ix_workflow_runs_workflow_id', ['workflow_id'], false, 'btree'],
  ['workflow_runs', 'ix_workflow_runs_trigger_id', ['trigger_id'], false, 'btree'],
  ['workflow_runs', 'ix_workflow_runs_tenant_id', ['tenant_id'], false, 'btree'],
  ['workflow_runs', 'ix_workflow_runs_trigger_source_concept_id', ['trigger_source_concept_id'], false, 'btree'],
  ['workflow_runs', 'ix_workflow_runs_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['workflow_runs', 'ix_workflow_runs_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['workflow_runs', 'ix_workflow_runs_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['workflow_runs', 'ix_workflow_runs_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['workflow_steps', 'ix_workflow_steps_workflow_id', ['workflow_id'], false, 'btree'],
  ['workflow_steps', 'ix_workflow_steps_step_type_concept_id', ['step_type_concept_id'], false, 'btree'],
  ['workflow_steps', 'ix_workflow_steps_agent_id', ['agent_id'], false, 'btree'],
  ['workflow_steps', 'ix_workflow_steps_agent_tool_id', ['agent_tool_id'], false, 'btree'],
  ['workflow_steps', 'ix_workflow_steps_on_success_step_id', ['on_success_step_id'], false, 'btree'],
  ['workflow_steps', 'ix_workflow_steps_on_failure_step_id', ['on_failure_step_id'], false, 'btree'],
  ['workflow_steps', 'ix_workflow_steps_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['workflow_steps', 'ix_workflow_steps_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['workflows', 'uq_workflows_code', ['code'], true, 'btree'],
  ['workflows', 'ix_workflows_tenant_id', ['tenant_id'], false, 'btree'],
  ['workflows', 'ix_workflows_orchestration_type_concept_id', ['orchestration_type_concept_id'], false, 'btree'],
  ['workflows', 'ix_workflows_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['workflows', 'ix_workflows_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['workflows', 'ix_workflows_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['workflows', 'ix_workflows_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
];
