import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `billing`.
 * 154 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const billingIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['bill_lines', 'ix_bill_lines_bill_id', ['bill_id'], false, 'btree'],
  ['bill_lines', 'ix_bill_lines_expense_account_id', ['expense_account_id'], false, 'btree'],
  ['bill_lines', 'ix_bill_lines_cost_center_id', ['cost_center_id'], false, 'btree'],
  ['bill_lines', 'ix_bill_lines_contract_line_item_id', ['contract_line_item_id'], false, 'btree'],
  ['bill_lines', 'ix_bill_lines_purchase_order_item_id', ['purchase_order_item_id'], false, 'btree'],
  ['bill_lines', 'ix_bill_lines_goods_receipt_item_id', ['goods_receipt_item_id'], false, 'btree'],
  ['bill_lines', 'ix_bill_lines_service_entry_item_id', ['service_entry_item_id'], false, 'btree'],
  ['bill_lines', 'ix_bill_lines_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['bill_lines', 'ix_bill_lines_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['billing_document_links', 'ix_billing_document_links_tenant_id', ['tenant_id'], false, 'btree'],
  ['billing_document_links', 'ix_billing_document_links_invoice_id', ['invoice_id'], false, 'btree'],
  ['billing_document_links', 'ix_billing_document_links_bill_id', ['bill_id'], false, 'btree'],
  ['billing_document_links', 'ix_billing_document_links_contract_id', ['contract_id'], false, 'btree'],
  ['billing_document_links', 'ix_billing_document_links_sales_order_id', ['sales_order_id'], false, 'btree'],
  ['billing_document_links', 'ix_billing_document_links_purchase_order_id', ['purchase_order_id'], false, 'btree'],
  ['billing_document_links', 'ix_billing_document_links_claim_id', ['claim_id'], false, 'btree'],
  ['billing_document_links', 'ix_billing_document_links_encounter_id', ['encounter_id'], false, 'btree'],
  ['billing_document_links', 'ix_billing_document_links_relation_type_concept_id', ['relation_type_concept_id'], false, 'btree'],
  ['billing_document_links', 'ix_billing_document_links_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['billing_document_links', 'ix_billing_document_links_tenant_relation_created', ['tenant_id', 'relation_type_concept_id', 'created_at desc'], false, 'btree'],
  ['bills', 'ix_bills_practice_id', ['practice_id'], false, 'btree'],
  ['bills', 'ix_bills_vendor_id', ['vendor_id'], false, 'btree'],
  ['bills', 'ix_bills_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['bills', 'ix_bills_transaction_id', ['transaction_id'], false, 'btree'],
  ['bills', 'ix_bills_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['bills', 'ix_bills_supplier_business_partner_id', ['supplier_business_partner_id'], false, 'btree'],
  ['bills', 'ix_bills_supplier_subledger_account_id', ['supplier_subledger_account_id'], false, 'btree'],
  ['bills', 'ix_bills_contract_id', ['contract_id'], false, 'btree'],
  ['bills', 'ix_bills_purchase_order_id', ['purchase_order_id'], false, 'btree'],
  ['bills', 'ix_bills_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['bills', 'ix_bills_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['budget_lines', 'ix_budget_lines_budget_id', ['budget_id'], false, 'btree'],
  ['budget_lines', 'ix_budget_lines_account_id', ['account_id'], false, 'btree'],
  ['budget_lines', 'ix_budget_lines_cost_center_id', ['cost_center_id'], false, 'btree'],
  ['budget_lines', 'ix_budget_lines_fiscal_period_id', ['fiscal_period_id'], false, 'btree'],
  ['budget_lines', 'ix_budget_lines_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['budget_lines', 'ix_budget_lines_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['budgets', 'ix_budgets_practice_id', ['practice_id'], false, 'btree'],
  ['budgets', 'ix_budgets_fiscal_year_id', ['fiscal_year_id'], false, 'btree'],
  ['budgets', 'ix_budgets_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['budgets', 'ix_budgets_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['budgets', 'ix_budgets_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['dunning_items', 'uq_dunning_items_dunning_run_id_invoice_id', ['dunning_run_id', 'invoice_id'], true, 'btree'],
  ['dunning_items', 'ix_dunning_items_dunning_run_id', ['dunning_run_id'], false, 'btree'],
  ['dunning_items', 'ix_dunning_items_invoice_id', ['invoice_id'], false, 'btree'],
  ['dunning_items', 'ix_dunning_items_open_item_id', ['open_item_id'], false, 'btree'],
  ['dunning_items', 'ix_dunning_items_business_partner_id', ['business_partner_id'], false, 'btree'],
  ['dunning_items', 'ix_dunning_items_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['dunning_items', 'ix_dunning_items_notice_file_id', ['notice_file_id'], false, 'btree'],
  ['dunning_items', 'ix_dunning_items_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['dunning_items', 'ix_dunning_items_status_overdue', ['status_concept_id', 'days_overdue desc'], false, 'btree'],
  ['dunning_runs', 'uq_dunning_runs_tenant_id_run_number', ['tenant_id', 'run_number'], true, 'btree'],
  ['dunning_runs', 'ix_dunning_runs_tenant_id', ['tenant_id'], false, 'btree'],
  ['dunning_runs', 'ix_dunning_runs_dunning_level_concept_id', ['dunning_level_concept_id'], false, 'btree'],
  ['dunning_runs', 'ix_dunning_runs_company_bank_account_id', ['company_bank_account_id'], false, 'btree'],
  ['dunning_runs', 'ix_dunning_runs_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['dunning_runs', 'ix_dunning_runs_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['dunning_runs', 'ix_dunning_runs_tenant_status_date', ['tenant_id', 'status_concept_id', 'run_date desc'], false, 'btree'],
  ['financial_kpi_snapshots', 'ix_financial_kpi_snapshots_practice_id', ['practice_id'], false, 'btree'],
  ['financial_kpi_snapshots', 'ix_financial_kpi_snapshots_fiscal_period_id', ['fiscal_period_id'], false, 'btree'],
  ['financial_kpi_snapshots', 'ix_financial_kpi_snapshots_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['invoice_lines', 'ix_invoice_lines_invoice_id', ['invoice_id'], false, 'btree'],
  ['invoice_lines', 'ix_invoice_lines_service_id', ['service_id'], false, 'btree'],
  ['invoice_lines', 'ix_invoice_lines_tax_code_id', ['tax_code_id'], false, 'btree'],
  ['invoice_lines', 'ix_invoice_lines_income_account_id', ['income_account_id'], false, 'btree'],
  ['invoice_lines', 'ix_invoice_lines_cost_center_id', ['cost_center_id'], false, 'btree'],
  ['invoice_lines', 'ix_invoice_lines_contract_line_item_id', ['contract_line_item_id'], false, 'btree'],
  ['invoice_lines', 'ix_invoice_lines_sales_order_item_id', ['sales_order_item_id'], false, 'btree'],
  ['invoice_lines', 'ix_invoice_lines_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['invoice_lines', 'ix_invoice_lines_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['invoices', 'uq_invoices_invoice_number', ['invoice_number'], true, 'btree'],
  ['invoices', 'ix_invoices_practice_id', ['practice_id'], false, 'btree'],
  ['invoices', 'ix_invoices_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['invoices', 'ix_invoices_encounter_id', ['encounter_id'], false, 'btree'],
  ['invoices', 'ix_invoices_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['invoices', 'ix_invoices_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['invoices', 'ix_invoices_customer_business_partner_id', ['customer_business_partner_id'], false, 'btree'],
  ['invoices', 'ix_invoices_customer_subledger_account_id', ['customer_subledger_account_id'], false, 'btree'],
  ['invoices', 'ix_invoices_contract_id', ['contract_id'], false, 'btree'],
  ['invoices', 'ix_invoices_sales_order_id', ['sales_order_id'], false, 'btree'],
  ['invoices', 'ix_invoices_transaction_id', ['transaction_id'], false, 'btree'],
  ['invoices', 'ix_invoices_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['invoices', 'ix_invoices_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['invoices', 'ix_invoices_patient_profile_id_updated_at', ['patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['patient_statements', 'ix_patient_statements_practice_id', ['practice_id'], false, 'btree'],
  ['patient_statements', 'ix_patient_statements_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['patient_statements', 'ix_patient_statements_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['patient_statements', 'ix_patient_statements_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['patient_statements', 'ix_patient_statements_patient_profile_id_updated_at', ['patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['payable_payment_allocations', 'uq_payable_payment_allocations_payment_made_id_bill_id_3897742e', ['payment_made_id', 'bill_id', 'open_item_id'], true, 'btree'],
  ['payable_payment_allocations', 'ix_payable_payment_allocations_payment_made_id', ['payment_made_id'], false, 'btree'],
  ['payable_payment_allocations', 'ix_payable_payment_allocations_bill_id', ['bill_id'], false, 'btree'],
  ['payable_payment_allocations', 'ix_payable_payment_allocations_open_item_id', ['open_item_id'], false, 'btree'],
  ['payable_payment_allocations', 'ix_payable_payment_allocations_clearing_item_id', ['clearing_item_id'], false, 'btree'],
  ['payable_payment_allocations', 'ix_payable_payment_allocations_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['payable_payment_allocations', 'ix_payable_payment_allocations_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['payments_made', 'ix_payments_made_practice_id', ['practice_id'], false, 'btree'],
  ['payments_made', 'ix_payments_made_bill_id', ['bill_id'], false, 'btree'],
  ['payments_made', 'ix_payments_made_vendor_id', ['vendor_id'], false, 'btree'],
  ['payments_made', 'ix_payments_made_method_concept_id', ['method_concept_id'], false, 'btree'],
  ['payments_made', 'ix_payments_made_transaction_id', ['transaction_id'], false, 'btree'],
  ['payments_made', 'ix_payments_made_payment_transaction_id', ['payment_transaction_id'], false, 'btree'],
  ['payments_made', 'ix_payments_made_clearing_document_id', ['clearing_document_id'], false, 'btree'],
  ['payments_made', 'ix_payments_made_company_bank_account_id', ['company_bank_account_id'], false, 'btree'],
  ['payments_made', 'ix_payments_made_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['payments_made', 'ix_payments_made_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['payments_made', 'ix_payments_made_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['payments_received', 'ix_payments_received_practice_id', ['practice_id'], false, 'btree'],
  ['payments_received', 'ix_payments_received_invoice_id', ['invoice_id'], false, 'btree'],
  ['payments_received', 'ix_payments_received_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['payments_received', 'ix_payments_received_method_concept_id', ['method_concept_id'], false, 'btree'],
  ['payments_received', 'ix_payments_received_transaction_id', ['transaction_id'], false, 'btree'],
  ['payments_received', 'ix_payments_received_payment_transaction_id', ['payment_transaction_id'], false, 'btree'],
  ['payments_received', 'ix_payments_received_clearing_document_id', ['clearing_document_id'], false, 'btree'],
  ['payments_received', 'ix_payments_received_company_bank_account_id', ['company_bank_account_id'], false, 'btree'],
  ['payments_received', 'ix_payments_received_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['payments_received', 'ix_payments_received_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['payments_received', 'ix_payments_received_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['payments_received', 'ix_payments_received_patient_profile_id_updated_at', ['patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['receivable_payment_allocations', 'uq_receivable_payment_allocations_payment_received_id__c1caeee3', ['payment_received_id', 'invoice_id', 'open_item_id'], true, 'btree'],
  ['receivable_payment_allocations', 'ix_receivable_payment_allocations_payment_received_id', ['payment_received_id'], false, 'btree'],
  ['receivable_payment_allocations', 'ix_receivable_payment_allocations_invoice_id', ['invoice_id'], false, 'btree'],
  ['receivable_payment_allocations', 'ix_receivable_payment_allocations_open_item_id', ['open_item_id'], false, 'btree'],
  ['receivable_payment_allocations', 'ix_receivable_payment_allocations_clearing_item_id', ['clearing_item_id'], false, 'btree'],
  ['receivable_payment_allocations', 'ix_receivable_payment_allocations_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['receivable_payment_allocations', 'ix_receivable_payment_allocations_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['reimbursements', 'ix_reimbursements_claim_id', ['claim_id'], false, 'btree'],
  ['reimbursements', 'ix_reimbursements_transaction_id', ['transaction_id'], false, 'btree'],
  ['reimbursements', 'ix_reimbursements_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['reimbursements', 'ix_reimbursements_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['reimbursements', 'ix_reimbursements_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['service_catalog', 'ix_service_catalog_practice_id', ['practice_id'], false, 'btree'],
  ['service_catalog', 'ix_service_catalog_service_concept_id', ['service_concept_id'], false, 'btree'],
  ['service_catalog', 'ix_service_catalog_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['service_catalog', 'ix_service_catalog_tax_code_id', ['tax_code_id'], false, 'btree'],
  ['service_catalog', 'ix_service_catalog_income_account_id', ['income_account_id'], false, 'btree'],
  ['service_catalog', 'ix_service_catalog_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['service_catalog', 'ix_service_catalog_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['tax_codes', 'ix_tax_codes_practice_id', ['practice_id'], false, 'btree'],
  ['tax_codes', 'ix_tax_codes_tax_type_concept_id', ['tax_type_concept_id'], false, 'btree'],
  ['tax_codes', 'ix_tax_codes_jurisdiction_concept_id', ['jurisdiction_concept_id'], false, 'btree'],
  ['tax_codes', 'ix_tax_codes_account_id', ['account_id'], false, 'btree'],
  ['tax_codes', 'ix_tax_codes_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['tax_codes', 'ix_tax_codes_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['tax_periods', 'ix_tax_periods_practice_id', ['practice_id'], false, 'btree'],
  ['tax_periods', 'ix_tax_periods_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['tax_periods', 'ix_tax_periods_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['tax_periods', 'ix_tax_periods_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['vendors', 'ix_vendors_practice_id', ['practice_id'], false, 'btree'],
  ['vendors', 'ix_vendors_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['vendors', 'ix_vendors_business_partner_id', ['business_partner_id'], false, 'btree'],
  ['vendors', 'ix_vendors_supplier_subledger_account_id', ['supplier_subledger_account_id'], false, 'btree'],
  ['vendors', 'ix_vendors_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['vendors', 'ix_vendors_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
];
