import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `chart`.
 * 80 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const chartIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['care_plans', 'ix_care_plans_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['care_plans', 'ix_care_plans_condition_id', ['condition_id'], false, 'btree'],
  ['care_plans', 'ix_care_plans_encounter_id', ['encounter_id'], false, 'btree'],
  ['care_plans', 'ix_care_plans_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['care_plans', 'ix_care_plans_intent_concept_id', ['intent_concept_id'], false, 'btree'],
  ['care_plans', 'ix_care_plans_author_profile_id', ['author_profile_id'], false, 'btree'],
  ['care_plans', 'ix_care_plans_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['care_plans', 'ix_care_plans_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['care_plans', 'ix_care_plans_patient_profile_id_updated_at', ['patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['care_plan_activities', 'ix_care_plan_activities_care_plan_id', ['care_plan_id'], false, 'btree'],
  ['care_plan_activities', 'ix_care_plan_activities_activity_concept_id', ['activity_concept_id'], false, 'btree'],
  ['care_plan_activities', 'ix_care_plan_activities_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['care_plan_activities', 'ix_care_plan_activities_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['care_plan_activities', 'ix_care_plan_activities_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['chart_template_assignments', 'ix_chart_template_assignments_template_id', ['template_id'], false, 'btree'],
  ['chart_template_assignments', 'ix_chart_template_assignments_practice_id', ['practice_id'], false, 'btree'],
  ['chart_template_assignments', 'ix_chart_template_assignments_practitioner_profile_id', ['practitioner_profile_id'], false, 'btree'],
  ['chart_template_assignments', 'ix_chart_template_assignments_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['chart_template_assignments', 'ix_chart_template_assignments_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['chart_template_assignments', 'ix_chart_template_assignments_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['clinical_note_headers', 'ix_clinical_note_headers_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['clinical_note_headers', 'ix_clinical_note_headers_encounter_id', ['encounter_id'], false, 'btree'],
  ['clinical_note_headers', 'ix_clinical_note_headers_note_type_concept_id', ['note_type_concept_id'], false, 'btree'],
  ['clinical_note_headers', 'ix_clinical_note_headers_lifecycle_status_concept_id', ['lifecycle_status_concept_id'], false, 'btree'],
  ['clinical_note_headers', 'ix_clinical_note_headers_current_version_id', ['current_version_id'], false, 'btree'],
  ['clinical_note_headers', 'ix_clinical_note_headers_current_released_version_id', ['current_released_version_id'], false, 'btree'],
  ['clinical_note_headers', 'ix_clinical_note_headers_patient_release_status_concept_id', ['patient_release_status_concept_id'], false, 'btree'],
  ['clinical_note_headers', 'ix_clinical_note_headers_confidentiality_concept_id', ['confidentiality_concept_id'], false, 'btree'],
  ['clinical_note_headers', 'ix_clinical_note_headers_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['clinical_note_headers', 'ix_clinical_note_headers_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['clinical_note_headers', 'ix_clinical_note_headers_patient_profile_id_updated_at', ['patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['clinical_note_signatures', 'ix_clinical_note_signatures_clinical_note_version_id', ['clinical_note_version_id'], false, 'btree'],
  ['clinical_note_signatures', 'ix_clinical_note_signatures_signer_profile_id', ['signer_profile_id'], false, 'btree'],
  ['clinical_note_signatures', 'ix_clinical_note_signatures_signature_type_concept_id', ['signature_type_concept_id'], false, 'btree'],
  ['clinical_note_versions', 'ix_clinical_note_versions_clinical_note_id', ['clinical_note_id'], false, 'btree'],
  ['clinical_note_versions', 'ix_clinical_note_versions_author_profile_id', ['author_profile_id'], false, 'btree'],
  ['clinical_note_versions', 'ix_clinical_note_versions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['clinical_note_versions', 'ix_clinical_note_versions_supersedes_version_id', ['supersedes_version_id'], false, 'btree'],
  ['clinical_note_versions', 'ix_clinical_note_versions_amendment_reason_concept_id', ['amendment_reason_concept_id'], false, 'btree'],
  ['clinical_note_versions', 'ix_clinical_note_versions_signed_by_profile_id', ['signed_by_profile_id'], false, 'btree'],
  ['clinical_note_versions', 'ix_clinical_note_versions_release_eligibility_concept_id', ['release_eligibility_concept_id'], false, 'btree'],
  ['clinical_note_versions', 'ix_clinical_note_versions_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['clinical_note_versions', 'uq_clinical_note_versions_clinical_note_id_version_number', ['clinical_note_id', 'version_number'], true, 'btree'],
  ['clinical_note_versions', 'brin_clinical_note_versions_recorded_at', ['recorded_at'], false, 'brin'],
  ['document_records', 'ix_document_records_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['document_records', 'ix_document_records_tenant_id', ['tenant_id'], false, 'btree'],
  ['document_records', 'ix_document_records_encounter_id', ['encounter_id'], false, 'btree'],
  ['document_records', 'ix_document_records_category_concept_id', ['category_concept_id'], false, 'btree'],
  ['document_records', 'ix_document_records_source_concept_id', ['source_concept_id'], false, 'btree'],
  ['document_records', 'ix_document_records_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['document_records', 'ix_document_records_confidentiality_concept_id', ['confidentiality_concept_id'], false, 'btree'],
  ['document_records', 'ix_document_records_patient_visibility_concept_id', ['patient_visibility_concept_id'], false, 'btree'],
  ['document_records', 'ix_document_records_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['document_records', 'ix_document_records_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['document_records', 'ix_document_records_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['document_records', 'ix_document_records_patient_profile_id_updated_at', ['tenant_id', 'patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['document_record_files', 'ix_document_record_files_document_record_id', ['document_record_id'], false, 'btree'],
  ['document_record_files', 'ix_document_record_files_file_id', ['file_id'], false, 'btree'],
  ['document_record_files', 'ix_document_record_files_content_role_concept_id', ['content_role_concept_id'], false, 'btree'],
  ['document_record_files', 'ix_document_record_files_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['note_release_events', 'ix_note_release_events_clinical_note_version_id', ['clinical_note_version_id'], false, 'btree'],
  ['note_release_events', 'ix_note_release_events_action_concept_id', ['action_concept_id'], false, 'btree'],
  ['note_release_events', 'ix_note_release_events_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['note_release_events', 'ix_note_release_events_resulting_visibility_concept_id', ['resulting_visibility_concept_id'], false, 'btree'],
  ['note_release_events', 'ix_note_release_events_reason_concept_id', ['reason_concept_id'], false, 'btree'],
  ['note_release_events', 'ix_note_release_events_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['note_release_events', 'ix_note_release_events_patient_profile_id_recorded_at', ['patient_profile_id', 'recorded_at desc'], false, 'btree'],
  ['note_release_events', 'brin_note_release_events_recorded_at', ['recorded_at'], false, 'brin'],
  ['physical_exam_findings', 'ix_physical_exam_findings_clinical_note_version_id', ['clinical_note_version_id'], false, 'btree'],
  ['physical_exam_findings', 'ix_physical_exam_findings_body_system_concept_id', ['body_system_concept_id'], false, 'btree'],
  ['physical_exam_findings', 'ix_physical_exam_findings_finding_concept_id', ['finding_concept_id'], false, 'btree'],
  ['physical_exam_findings', 'ix_physical_exam_findings_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['specialty_chart_templates', 'ix_specialty_chart_templates_specialty_concept_id', ['specialty_concept_id'], false, 'btree'],
  ['specialty_chart_templates', 'ix_specialty_chart_templates_tenant_id', ['tenant_id'], false, 'btree'],
  ['specialty_chart_templates', 'ix_specialty_chart_templates_section_id', ['section_id'], false, 'btree'],
  ['specialty_chart_templates', 'ix_specialty_chart_templates_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['specialty_chart_templates', 'ix_specialty_chart_templates_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['specialty_chart_templates', 'ix_specialty_chart_templates_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['specialty_chart_templates', 'ix_specialty_chart_templates_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['specialty_chart_templates', 'uq_specialty_chart_templates_section_id_version', ['section_id', 'version'], true, 'btree'],
];
