import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `clinical` (parte 2/2).
 * 51 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const clinicalIndexes2: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['observations', 'ix_observations_method_concept_id', ['method_concept_id'], false, 'btree'],
  ['observations', 'ix_observations_body_site_concept_id', ['body_site_concept_id'], false, 'btree'],
  ['observations', 'ix_observations_specimen_id', ['specimen_id'], false, 'btree'],
  ['observations', 'ix_observations_source_device_id', ['source_device_id'], false, 'btree'],
  ['observations', 'ix_observations_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['observations', 'ix_observations_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['observations', 'ix_observations_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['observations', 'ix_observations_custodian_tenant_id_status_concept_id', ['custodian_tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['observations', 'ix_observations_patient_profile_id_updated_at', ['custodian_tenant_id', 'patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['observations', 'ix_observations_patient_code_effective', ['custodian_tenant_id', 'patient_profile_id', 'code_concept_id', 'effective_start_at desc'], false, 'btree'],
  ['observations', 'ix_observations_encounter_code', ['encounter_id', 'code_concept_id'], false, 'btree'],
  ['procedures', 'ix_procedures_custodian_tenant_id', ['custodian_tenant_id'], false, 'btree'],
  ['procedures', 'ix_procedures_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['procedures', 'ix_procedures_encounter_id', ['encounter_id'], false, 'btree'],
  ['procedures', 'ix_procedures_code_concept_id', ['code_concept_id'], false, 'btree'],
  ['procedures', 'ix_procedures_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['procedures', 'ix_procedures_performer_profile_id', ['performer_profile_id'], false, 'btree'],
  ['procedures', 'ix_procedures_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['procedures', 'ix_procedures_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['procedures', 'ix_procedures_custodian_tenant_id_status_concept_id', ['custodian_tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['procedures', 'ix_procedures_patient_profile_id_updated_at', ['custodian_tenant_id', 'patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['procedures', 'ix_procedures_service_request_id', ['service_request_id'], false, 'btree'],
  ['procedures', 'ix_procedures_parent_procedure_id', ['parent_procedure_id'], false, 'btree'],
  ['procedures', 'ix_procedures_practice_site_id', ['practice_site_id'], false, 'btree'],
  ['procedures', 'ix_procedures_patient_occurrence', ['custodian_tenant_id', 'patient_profile_id', 'occurrence_start_at desc'], false, 'btree'],
  ['procedures', 'ix_procedures_code_status_time', ['custodian_tenant_id', 'code_concept_id', 'status_concept_id', 'occurrence_start_at desc'], false, 'btree'],
  ['service_requests', 'ix_service_requests_custodian_tenant_id', ['custodian_tenant_id'], false, 'btree'],
  ['service_requests', 'ix_service_requests_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['service_requests', 'ix_service_requests_encounter_id', ['encounter_id'], false, 'btree'],
  ['service_requests', 'ix_service_requests_code_concept_id', ['code_concept_id'], false, 'btree'],
  ['service_requests', 'ix_service_requests_category_concept_id', ['category_concept_id'], false, 'btree'],
  ['service_requests', 'ix_service_requests_intent_concept_id', ['intent_concept_id'], false, 'btree'],
  ['service_requests', 'ix_service_requests_priority_concept_id', ['priority_concept_id'], false, 'btree'],
  ['service_requests', 'ix_service_requests_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['service_requests', 'ix_service_requests_requester_profile_id', ['requester_profile_id'], false, 'btree'],
  ['service_requests', 'ix_service_requests_performer_tenant_id', ['performer_tenant_id'], false, 'btree'],
  ['service_requests', 'ix_service_requests_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['service_requests', 'ix_service_requests_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['service_requests', 'ix_service_requests_custodian_tenant_id_status_concept_id', ['custodian_tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['service_requests', 'ix_service_requests_patient_profile_id_updated_at', ['custodian_tenant_id', 'patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['social_history', 'ix_social_history_custodian_tenant_id', ['custodian_tenant_id'], false, 'btree'],
  ['social_history', 'ix_social_history_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['social_history', 'ix_social_history_category_concept_id', ['category_concept_id'], false, 'btree'],
  ['social_history', 'ix_social_history_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['social_history', 'ix_social_history_value_concept_id', ['value_concept_id'], false, 'btree'],
  ['social_history', 'ix_social_history_unit_concept_id', ['unit_concept_id'], false, 'btree'],
  ['social_history', 'ix_social_history_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['social_history', 'ix_social_history_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['social_history', 'ix_social_history_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['social_history', 'ix_social_history_custodian_tenant_id_status_concept_id', ['custodian_tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['social_history', 'ix_social_history_patient_profile_id_updated_at', ['custodian_tenant_id', 'patient_profile_id', 'updated_at desc'], false, 'btree'],
];
