import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `clinical_ext`.
 * 93 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const clinicalExtIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['care_gaps', 'ix_care_gaps_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['care_gaps', 'ix_care_gaps_gap_type_concept_id', ['gap_type_concept_id'], false, 'btree'],
  ['care_gaps', 'ix_care_gaps_measure_concept_id', ['measure_concept_id'], false, 'btree'],
  ['care_gaps', 'ix_care_gaps_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['care_gaps', 'ix_care_gaps_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['care_gaps', 'ix_care_gaps_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['care_gaps', 'ix_care_gaps_patient_profile_id_updated_at', ['patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['care_teams', 'ix_care_teams_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['care_teams', 'ix_care_teams_episode_id', ['episode_id'], false, 'btree'],
  ['care_teams', 'ix_care_teams_tenant_id', ['tenant_id'], false, 'btree'],
  ['care_teams', 'ix_care_teams_category_concept_id', ['category_concept_id'], false, 'btree'],
  ['care_teams', 'ix_care_teams_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['care_teams', 'ix_care_teams_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['care_teams', 'ix_care_teams_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['care_teams', 'ix_care_teams_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['care_teams', 'ix_care_teams_patient_profile_id_updated_at', ['tenant_id', 'patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['care_team_members', 'ix_care_team_members_care_team_id', ['care_team_id'], false, 'btree'],
  ['care_team_members', 'ix_care_team_members_practitioner_profile_id', ['practitioner_profile_id'], false, 'btree'],
  ['care_team_members', 'ix_care_team_members_related_person_id', ['related_person_id'], false, 'btree'],
  ['care_team_members', 'ix_care_team_members_member_role_concept_id', ['member_role_concept_id'], false, 'btree'],
  ['care_team_members', 'ix_care_team_members_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['care_team_members', 'ix_care_team_members_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['care_team_members', 'ix_care_team_members_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['cds_rules', 'uq_cds_rules_code', ['code'], true, 'btree'],
  ['cds_rules', 'ix_cds_rules_tenant_id', ['tenant_id'], false, 'btree'],
  ['cds_rules', 'ix_cds_rules_rule_type_concept_id', ['rule_type_concept_id'], false, 'btree'],
  ['cds_rules', 'ix_cds_rules_severity_concept_id', ['severity_concept_id'], false, 'btree'],
  ['cds_rules', 'ix_cds_rules_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['cds_rules', 'ix_cds_rules_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['cds_rules', 'ix_cds_rules_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['cds_rules', 'ix_cds_rules_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['clinical_alerts', 'ix_clinical_alerts_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['clinical_alerts', 'ix_clinical_alerts_encounter_id', ['encounter_id'], false, 'btree'],
  ['clinical_alerts', 'ix_clinical_alerts_alert_type_concept_id', ['alert_type_concept_id'], false, 'btree'],
  ['clinical_alerts', 'ix_clinical_alerts_severity_concept_id', ['severity_concept_id'], false, 'btree'],
  ['clinical_alerts', 'ix_clinical_alerts_trigger_concept_id', ['trigger_concept_id'], false, 'btree'],
  ['clinical_alerts', 'ix_clinical_alerts_rule_id', ['rule_id'], false, 'btree'],
  ['clinical_alerts', 'ix_clinical_alerts_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['clinical_alerts', 'ix_clinical_alerts_overridden_by_user_id', ['overridden_by_user_id'], false, 'btree'],
  ['clinical_alerts', 'ix_clinical_alerts_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['clinical_alerts', 'ix_clinical_alerts_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['clinical_alerts', 'ix_clinical_alerts_patient_profile_id_updated_at', ['patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['drug_interactions', 'ix_drug_interactions_substance_a_concept_id', ['substance_a_concept_id'], false, 'btree'],
  ['drug_interactions', 'ix_drug_interactions_substance_b_concept_id', ['substance_b_concept_id'], false, 'btree'],
  ['drug_interactions', 'ix_drug_interactions_severity_concept_id', ['severity_concept_id'], false, 'btree'],
  ['drug_interactions', 'ix_drug_interactions_evidence_level_concept_id', ['evidence_level_concept_id'], false, 'btree'],
  ['drug_interactions', 'ix_drug_interactions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['drug_interactions', 'ix_drug_interactions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['immunization_schedules', 'ix_immunization_schedules_tenant_id', ['tenant_id'], false, 'btree'],
  ['immunization_schedules', 'ix_immunization_schedules_vaccine_concept_id', ['vaccine_concept_id'], false, 'btree'],
  ['immunization_schedules', 'ix_immunization_schedules_jurisdiction_concept_id', ['jurisdiction_concept_id'], false, 'btree'],
  ['immunization_schedules', 'ix_immunization_schedules_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['immunization_schedules', 'ix_immunization_schedules_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['immunization_schedules', 'ix_immunization_schedules_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['immunization_schedules', 'ix_immunization_schedules_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['order_sets', 'ix_order_sets_tenant_id', ['tenant_id'], false, 'btree'],
  ['order_sets', 'ix_order_sets_specialty_concept_id', ['specialty_concept_id'], false, 'btree'],
  ['order_sets', 'ix_order_sets_condition_concept_id', ['condition_concept_id'], false, 'btree'],
  ['order_sets', 'ix_order_sets_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['order_sets', 'ix_order_sets_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['order_sets', 'ix_order_sets_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['order_sets', 'ix_order_sets_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['order_set_items', 'ix_order_set_items_order_set_id', ['order_set_id'], false, 'btree'],
  ['order_set_items', 'ix_order_set_items_item_type_concept_id', ['item_type_concept_id'], false, 'btree'],
  ['order_set_items', 'ix_order_set_items_code_concept_id', ['code_concept_id'], false, 'btree'],
  ['order_set_items', 'ix_order_set_items_default_route_concept_id', ['default_route_concept_id'], false, 'btree'],
  ['order_set_items', 'ix_order_set_items_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['order_set_items', 'ix_order_set_items_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['reference_ranges', 'ix_reference_ranges_code_concept_id', ['code_concept_id'], false, 'btree'],
  ['reference_ranges', 'ix_reference_ranges_unit_concept_id', ['unit_concept_id'], false, 'btree'],
  ['reference_ranges', 'ix_reference_ranges_sex_concept_id', ['sex_concept_id'], false, 'btree'],
  ['reference_ranges', 'ix_reference_ranges_condition_concept_id', ['condition_concept_id'], false, 'btree'],
  ['reference_ranges', 'ix_reference_ranges_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['reference_ranges', 'ix_reference_ranges_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['referrals', 'ix_referrals_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['referrals', 'ix_referrals_source_encounter_id', ['source_encounter_id'], false, 'btree'],
  ['referrals', 'ix_referrals_referring_profile_id', ['referring_profile_id'], false, 'btree'],
  ['referrals', 'ix_referrals_target_profile_id', ['target_profile_id'], false, 'btree'],
  ['referrals', 'ix_referrals_target_tenant_id', ['target_tenant_id'], false, 'btree'],
  ['referrals', 'ix_referrals_specialty_concept_id', ['specialty_concept_id'], false, 'btree'],
  ['referrals', 'ix_referrals_service_request_id', ['service_request_id'], false, 'btree'],
  ['referrals', 'ix_referrals_reason_concept_id', ['reason_concept_id'], false, 'btree'],
  ['referrals', 'ix_referrals_priority_concept_id', ['priority_concept_id'], false, 'btree'],
  ['referrals', 'ix_referrals_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['referrals', 'ix_referrals_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['referrals', 'ix_referrals_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['referrals', 'ix_referrals_patient_profile_id_updated_at', ['patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['virtual_encounters', 'ix_virtual_encounters_encounter_id', ['encounter_id'], false, 'btree'],
  ['virtual_encounters', 'ix_virtual_encounters_platform_concept_id', ['platform_concept_id'], false, 'btree'],
  ['virtual_encounters', 'ix_virtual_encounters_recording_file_id', ['recording_file_id'], false, 'btree'],
  ['virtual_encounters', 'ix_virtual_encounters_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['virtual_encounters', 'ix_virtual_encounters_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['virtual_encounters', 'ix_virtual_encounters_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
];
