import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `clinical` (parte 1/2).
 * 180 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const clinicalIndexes1: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['allergy_intolerances', 'ix_allergy_intolerances_custodian_tenant_id', ['custodian_tenant_id'], false, 'btree'],
  ['allergy_intolerances', 'ix_allergy_intolerances_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['allergy_intolerances', 'ix_allergy_intolerances_substance_concept_id', ['substance_concept_id'], false, 'btree'],
  ['allergy_intolerances', 'ix_allergy_intolerances_type_concept_id', ['type_concept_id'], false, 'btree'],
  ['allergy_intolerances', 'ix_allergy_intolerances_category_concept_id', ['category_concept_id'], false, 'btree'],
  ['allergy_intolerances', 'ix_allergy_intolerances_criticality_concept_id', ['criticality_concept_id'], false, 'btree'],
  ['allergy_intolerances', 'ix_allergy_intolerances_clinical_status_concept_id', ['clinical_status_concept_id'], false, 'btree'],
  ['allergy_intolerances', 'ix_allergy_intolerances_verification_status_concept_id', ['verification_status_concept_id'], false, 'btree'],
  ['allergy_intolerances', 'ix_allergy_intolerances_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['allergy_intolerances', 'ix_allergy_intolerances_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['allergy_intolerances', 'ix_allergy_intolerances_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['allergy_intolerances', 'ix_allergy_intolerances_custodian_tenant_id_updated_at', ['custodian_tenant_id', 'updated_at desc'], false, 'btree'],
  ['allergy_intolerances', 'ix_allergy_intolerances_patient_profile_id_updated_at', ['custodian_tenant_id', 'patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['allergy_intolerances', 'ix_allergies_patient_status', ['custodian_tenant_id', 'patient_profile_id', 'clinical_status_concept_id'], false, 'btree'],
  ['allergy_reactions', 'ix_allergy_reactions_allergy_id', ['allergy_id'], false, 'btree'],
  ['allergy_reactions', 'ix_allergy_reactions_manifestation_concept_id', ['manifestation_concept_id'], false, 'btree'],
  ['allergy_reactions', 'ix_allergy_reactions_severity_concept_id', ['severity_concept_id'], false, 'btree'],
  ['allergy_reactions', 'ix_allergy_reactions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['allergy_reactions', 'ix_allergy_reactions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['appointments', 'ix_appointments_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['appointments', 'ix_appointments_practitioner_profile_id', ['practitioner_profile_id'], false, 'btree'],
  ['appointments', 'ix_appointments_tenant_id', ['tenant_id'], false, 'btree'],
  ['appointments', 'ix_appointments_branch_id', ['branch_id'], false, 'btree'],
  ['appointments', 'ix_appointments_type_concept_id', ['type_concept_id'], false, 'btree'],
  ['appointments', 'ix_appointments_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['appointments', 'ix_appointments_channel_concept_id', ['channel_concept_id'], false, 'btree'],
  ['appointments', 'ix_appointments_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['appointments', 'ix_appointments_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['appointments', 'ix_appointments_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['appointments', 'ix_appointments_patient_profile_id_updated_at', ['tenant_id', 'patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['appointments', 'ix_appointments_patient_start', ['patient_profile_id', 'start_at desc'], false, 'btree'],
  ['care_episodes', 'ix_care_episodes_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['care_episodes', 'ix_care_episodes_tenant_id', ['tenant_id'], false, 'btree'],
  ['care_episodes', 'ix_care_episodes_responsible_practitioner_id', ['responsible_practitioner_id'], false, 'btree'],
  ['care_episodes', 'ix_care_episodes_type_concept_id', ['type_concept_id'], false, 'btree'],
  ['care_episodes', 'ix_care_episodes_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['care_episodes', 'ix_care_episodes_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['care_episodes', 'ix_care_episodes_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['care_episodes', 'ix_care_episodes_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['care_episodes', 'ix_care_episodes_patient_profile_id_updated_at', ['tenant_id', 'patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['conditions', 'ix_conditions_custodian_tenant_id', ['custodian_tenant_id'], false, 'btree'],
  ['conditions', 'ix_conditions_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['conditions', 'ix_conditions_encounter_id', ['encounter_id'], false, 'btree'],
  ['conditions', 'ix_conditions_code_concept_id', ['code_concept_id'], false, 'btree'],
  ['conditions', 'ix_conditions_category_concept_id', ['category_concept_id'], false, 'btree'],
  ['conditions', 'ix_conditions_clinical_status_concept_id', ['clinical_status_concept_id'], false, 'btree'],
  ['conditions', 'ix_conditions_verification_status_concept_id', ['verification_status_concept_id'], false, 'btree'],
  ['conditions', 'ix_conditions_severity_concept_id', ['severity_concept_id'], false, 'btree'],
  ['conditions', 'ix_conditions_laterality_concept_id', ['laterality_concept_id'], false, 'btree'],
  ['conditions', 'ix_conditions_clinical_course_concept_id', ['clinical_course_concept_id'], false, 'btree'],
  ['conditions', 'ix_conditions_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['conditions', 'ix_conditions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['conditions', 'ix_conditions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['conditions', 'ix_conditions_custodian_tenant_id_updated_at', ['custodian_tenant_id', 'updated_at desc'], false, 'btree'],
  ['conditions', 'ix_conditions_patient_profile_id_updated_at', ['custodian_tenant_id', 'patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['conditions', 'ix_conditions_patient_clinical_status', ['custodian_tenant_id', 'patient_profile_id', 'clinical_status_concept_id', 'onset_at desc'], false, 'btree'],
  ['diagnostic_reports', 'ix_diagnostic_reports_custodian_tenant_id', ['custodian_tenant_id'], false, 'btree'],
  ['diagnostic_reports', 'ix_diagnostic_reports_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['diagnostic_reports', 'ix_diagnostic_reports_service_request_id', ['service_request_id'], false, 'btree'],
  ['diagnostic_reports', 'ix_diagnostic_reports_encounter_id', ['encounter_id'], false, 'btree'],
  ['diagnostic_reports', 'ix_diagnostic_reports_code_concept_id', ['code_concept_id'], false, 'btree'],
  ['diagnostic_reports', 'ix_diagnostic_reports_category_concept_id', ['category_concept_id'], false, 'btree'],
  ['diagnostic_reports', 'ix_diagnostic_reports_lifecycle_status_concept_id', ['lifecycle_status_concept_id'], false, 'btree'],
  ['diagnostic_reports', 'ix_diagnostic_reports_current_version_id', ['current_version_id'], false, 'btree'],
  ['diagnostic_reports', 'ix_diagnostic_reports_current_released_version_id', ['current_released_version_id'], false, 'btree'],
  ['diagnostic_reports', 'ix_diagnostic_reports_result_release_status_concept_id', ['result_release_status_concept_id'], false, 'btree'],
  ['diagnostic_reports', 'ix_diagnostic_reports_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['diagnostic_reports', 'ix_diagnostic_reports_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['diagnostic_reports', 'ix_diagnostic_reports_custodian_tenant_id_lifecycle_st_43c65044', ['custodian_tenant_id', 'lifecycle_status_concept_id', 'updated_at desc'], false, 'btree'],
  ['diagnostic_reports', 'ix_diagnostic_reports_patient_profile_id_updated_at', ['custodian_tenant_id', 'patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['encounters', 'ix_encounters_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['encounters', 'ix_encounters_episode_id', ['episode_id'], false, 'btree'],
  ['encounters', 'ix_encounters_tenant_id', ['tenant_id'], false, 'btree'],
  ['encounters', 'ix_encounters_branch_id', ['branch_id'], false, 'btree'],
  ['encounters', 'ix_encounters_primary_practitioner_id', ['primary_practitioner_id'], false, 'btree'],
  ['encounters', 'ix_encounters_class_concept_id', ['class_concept_id'], false, 'btree'],
  ['encounters', 'ix_encounters_type_concept_id', ['type_concept_id'], false, 'btree'],
  ['encounters', 'ix_encounters_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['encounters', 'ix_encounters_appointment_id', ['appointment_id'], false, 'btree'],
  ['encounters', 'ix_encounters_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['encounters', 'ix_encounters_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['encounters', 'ix_encounters_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['encounters', 'ix_encounters_patient_profile_id_updated_at', ['tenant_id', 'patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['encounter_locations', 'ix_encounter_locations_encounter_id', ['encounter_id'], false, 'btree'],
  ['encounter_locations', 'ix_encounter_locations_practice_site_id', ['practice_site_id'], false, 'btree'],
  ['encounter_locations', 'ix_encounter_locations_clinical_unit_id', ['clinical_unit_id'], false, 'btree'],
  ['encounter_locations', 'ix_encounter_locations_care_space_id', ['care_space_id'], false, 'btree'],
  ['encounter_locations', 'ix_encounter_locations_location_status_concept_id', ['location_status_concept_id'], false, 'btree'],
  ['encounter_locations', 'ix_encounter_locations_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['encounter_locations', 'ix_encounter_locations_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['encounter_participants', 'ix_encounter_participants_encounter_id', ['encounter_id'], false, 'btree'],
  ['encounter_participants', 'ix_encounter_participants_practitioner_profile_id', ['practitioner_profile_id'], false, 'btree'],
  ['encounter_participants', 'ix_encounter_participants_participant_role_concept_id', ['participant_role_concept_id'], false, 'btree'],
  ['encounter_participants', 'ix_encounter_participants_practitioner_role_assignment_id', ['practitioner_role_assignment_id'], false, 'btree'],
  ['encounter_participants', 'ix_encounter_participants_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['encounter_participants', 'ix_encounter_participants_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['encounter_participants', 'ix_encounter_participants_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['family_member_history', 'ix_family_member_history_custodian_tenant_id', ['custodian_tenant_id'], false, 'btree'],
  ['family_member_history', 'ix_family_member_history_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['family_member_history', 'ix_family_member_history_relationship_concept_id', ['relationship_concept_id'], false, 'btree'],
  ['family_member_history', 'ix_family_member_history_condition_concept_id', ['condition_concept_id'], false, 'btree'],
  ['family_member_history', 'ix_family_member_history_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['family_member_history', 'ix_family_member_history_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['family_member_history', 'ix_family_member_history_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['family_member_history', 'ix_family_member_history_custodian_tenant_id_updated_at', ['custodian_tenant_id', 'updated_at desc'], false, 'btree'],
  ['family_member_history', 'ix_family_member_history_patient_profile_id_updated_at', ['custodian_tenant_id', 'patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['immunizations', 'ix_immunizations_custodian_tenant_id', ['custodian_tenant_id'], false, 'btree'],
  ['immunizations', 'ix_immunizations_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['immunizations', 'ix_immunizations_vaccine_concept_id', ['vaccine_concept_id'], false, 'btree'],
  ['immunizations', 'ix_immunizations_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['immunizations', 'ix_immunizations_route_concept_id', ['route_concept_id'], false, 'btree'],
  ['immunizations', 'ix_immunizations_administered_by_profile_id', ['administered_by_profile_id'], false, 'btree'],
  ['immunizations', 'ix_immunizations_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['immunizations', 'ix_immunizations_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['immunizations', 'ix_immunizations_custodian_tenant_id_status_concept_id', ['custodian_tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['immunizations', 'ix_immunizations_patient_profile_id_updated_at', ['custodian_tenant_id', 'patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['medication_records', 'ix_medication_records_custodian_tenant_id', ['custodian_tenant_id'], false, 'btree'],
  ['medication_records', 'ix_medication_records_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['medication_records', 'ix_medication_records_request_id', ['request_id'], false, 'btree'],
  ['medication_records', 'ix_medication_records_medication_concept_id', ['medication_concept_id'], false, 'btree'],
  ['medication_records', 'ix_medication_records_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['medication_records', 'ix_medication_records_record_type_concept_id', ['record_type_concept_id'], false, 'btree'],
  ['medication_records', 'ix_medication_records_unit_concept_id', ['unit_concept_id'], false, 'btree'],
  ['medication_records', 'ix_medication_records_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['medication_records', 'ix_medication_records_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['medication_records', 'ix_medication_records_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['medication_records', 'ix_medication_records_custodian_tenant_id_status_concept_id', ['custodian_tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['medication_records', 'ix_medication_records_patient_profile_id_updated_at', ['custodian_tenant_id', 'patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['medication_requests', 'ix_medication_requests_custodian_tenant_id', ['custodian_tenant_id'], false, 'btree'],
  ['medication_requests', 'ix_medication_requests_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['medication_requests', 'ix_medication_requests_encounter_id', ['encounter_id'], false, 'btree'],
  ['medication_requests', 'ix_medication_requests_medication_concept_id', ['medication_concept_id'], false, 'btree'],
  ['medication_requests', 'ix_medication_requests_substance_atc_concept_id', ['substance_atc_concept_id'], false, 'btree'],
  ['medication_requests', 'ix_medication_requests_intent_concept_id', ['intent_concept_id'], false, 'btree'],
  ['medication_requests', 'ix_medication_requests_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['medication_requests', 'ix_medication_requests_prescriber_profile_id', ['prescriber_profile_id'], false, 'btree'],
  ['medication_requests', 'ix_medication_requests_route_concept_id', ['route_concept_id'], false, 'btree'],
  ['medication_requests', 'ix_medication_requests_unit_concept_id', ['unit_concept_id'], false, 'btree'],
  ['medication_requests', 'ix_medication_requests_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['medication_requests', 'ix_medication_requests_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['medication_requests', 'ix_medication_requests_custodian_tenant_id_status_concept_id', ['custodian_tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['medication_requests', 'ix_medication_requests_patient_profile_id_updated_at', ['custodian_tenant_id', 'patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['medication_requests', 'uq_medication_requests_issue_idempotency_key', ['issue_idempotency_key'], true, 'btree', 'issue_idempotency_key IS NOT NULL'],
  ['observations', 'ix_observations_custodian_tenant_id', ['custodian_tenant_id'], false, 'btree'],
  ['observations', 'ix_observations_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['observations', 'ix_observations_encounter_id', ['encounter_id'], false, 'btree'],
  ['observations', 'ix_observations_based_on_service_request_id', ['based_on_service_request_id'], false, 'btree'],
  ['observations', 'ix_observations_category_concept_id', ['category_concept_id'], false, 'btree'],
  ['observations', 'ix_observations_code_concept_id', ['code_concept_id'], false, 'btree'],
  ['observations', 'ix_observations_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['observations', 'ix_observations_value_type_concept_id', ['value_type_concept_id'], false, 'btree'],
  ['observations', 'ix_observations_value_concept_id', ['value_concept_id'], false, 'btree'],
  ['observations', 'ix_observations_quantity_unit_concept_id', ['quantity_unit_concept_id'], false, 'btree'],
  ['observations', 'ix_observations_range_unit_concept_id', ['range_unit_concept_id'], false, 'btree'],
  ['observations', 'ix_observations_ratio_numerator_unit_concept_id', ['ratio_numerator_unit_concept_id'], false, 'btree'],
  ['observations', 'ix_observations_ratio_denominator_unit_concept_id', ['ratio_denominator_unit_concept_id'], false, 'btree'],
  ['observations', 'ix_observations_value_file_id', ['value_file_id'], false, 'btree'],
  ['observations', 'ix_observations_value_reference_type_concept_id', ['value_reference_type_concept_id'], false, 'btree'],
  ['observations', 'ix_observations_data_absent_reason_concept_id', ['data_absent_reason_concept_id'], false, 'btree'],
  ['observations', 'ix_observations_interpretation_concept_id', ['interpretation_concept_id'], false, 'btree'],
  ['observations', 'ix_observations_method_concept_id', ['method_concept_id'], false, 'btree'],
  ['observations', 'ix_observations_body_site_concept_id', ['body_site_concept_id'], false, 'btree'],
  ['observations', 'ix_observations_specimen_id', ['specimen_id'], false, 'btree'],
  ['observations', 'ix_observations_source_device_id', ['source_device_id'], false, 'btree'],
  ['observations', 'ix_observations_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['observations', 'ix_observations_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['observations', 'ix_observations_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['observations', 'ix_observations_custodian_tenant_id_status_concept_id', ['custodian_tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['observations', 'ix_observations_patient_profile_id_updated_at', ['custodian_tenant_id', 'patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['observations', 'ix_observations_patient_code_effective', ['custodian_tenant_id', 'patient_profile_id', 'code_concept_id', 'effective_start_at desc'], false, 'btree'],
  ['observations', 'ix_observations_encounter_code', ['encounter_id', 'code_concept_id'], false, 'btree', 'encounter_id IS NOT NULL'],
  ['observation_components', 'ix_observation_components_observation_id', ['observation_id'], false, 'btree'],
  ['observation_components', 'ix_observation_components_code_concept_id', ['code_concept_id'], false, 'btree'],
  ['observation_components', 'ix_observation_components_value_type_concept_id', ['value_type_concept_id'], false, 'btree'],
  ['observation_components', 'ix_observation_components_value_concept_id', ['value_concept_id'], false, 'btree'],
  ['observation_components', 'ix_observation_components_quantity_unit_concept_id', ['quantity_unit_concept_id'], false, 'btree'],
  ['observation_components', 'ix_observation_components_range_unit_concept_id', ['range_unit_concept_id'], false, 'btree'],
  ['observation_components', 'ix_observation_components_data_absent_reason_concept_id', ['data_absent_reason_concept_id'], false, 'btree'],
  ['observation_components', 'ix_observation_components_interpretation_concept_id', ['interpretation_concept_id'], false, 'btree'],
  ['observation_components', 'ix_observation_components_created_by_user_id', ['created_by_user_id'], false, 'btree'],
];
