import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `community` (parte 2/2).
 * 63 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const communityIndexes2: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['reactions', 'ix_reactions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['reactions', 'ix_reactions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['reactions', 'uq_reactions_actor_target_type', ['actor_profile_id', 'reactable_type_concept_id', 'reactable_ref_id', 'reaction_type_concept_id'], true, 'btree'],
  ['review_dimension_scores', 'ix_review_dimension_scores_review_id', ['review_id'], false, 'btree'],
  ['review_dimension_scores', 'ix_review_dimension_scores_dimension_concept_id', ['dimension_concept_id'], false, 'btree'],
  ['review_responses', 'ix_review_responses_review_id', ['review_id'], false, 'btree'],
  ['review_responses', 'ix_review_responses_responder_public_profile_id', ['responder_public_profile_id'], false, 'btree'],
  ['review_responses', 'ix_review_responses_moderation_status_concept_id', ['moderation_status_concept_id'], false, 'btree'],
  ['review_responses', 'ix_review_responses_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['review_responses', 'ix_review_responses_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['service_reviews', 'ix_service_reviews_target_public_profile_id', ['target_public_profile_id'], false, 'btree'],
  ['service_reviews', 'ix_service_reviews_reviewer_patient_profile_id', ['reviewer_patient_profile_id'], false, 'btree'],
  ['service_reviews', 'ix_service_reviews_verified_encounter_id', ['verified_encounter_id'], false, 'btree'],
  ['service_reviews', 'ix_service_reviews_reviewer_display_mode_concept_id', ['reviewer_display_mode_concept_id'], false, 'btree'],
  ['service_reviews', 'ix_service_reviews_verification_status_concept_id', ['verification_status_concept_id'], false, 'btree'],
  ['service_reviews', 'ix_service_reviews_moderation_status_concept_id', ['moderation_status_concept_id'], false, 'btree'],
  ['service_reviews', 'ix_service_reviews_publication_status_concept_id', ['publication_status_concept_id'], false, 'btree'],
  ['service_reviews', 'ix_service_reviews_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['service_reviews', 'ix_service_reviews_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['service_reviews', 'uq_service_reviews_verified_encounter', ['reviewer_patient_profile_id', 'target_public_profile_id', 'verified_encounter_id'], true, 'btree', 'verified_encounter_id IS NOT NULL'],
  ['social_follows', 'ix_social_follows_follower_profile_id', ['follower_profile_id'], false, 'btree'],
  ['social_follows', 'ix_social_follows_followable_type_concept_id', ['followable_type_concept_id'], false, 'btree'],
  ['social_follows', 'ix_social_follows_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['social_follows', 'ix_social_follows_notification_level_concept_id', ['notification_level_concept_id'], false, 'btree'],
  ['social_follows', 'ix_social_follows_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['social_follows', 'ix_social_follows_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['social_follows', 'uq_social_follows_actor_target', ['follower_profile_id', 'followable_type_concept_id', 'followable_ref_id'], true, 'btree'],
  ['social_notifications', 'ix_social_notifications_recipient_profile_id', ['recipient_profile_id'], false, 'btree'],
  ['social_notifications', 'ix_social_notifications_notification_type_concept_id', ['notification_type_concept_id'], false, 'btree'],
  ['social_notifications', 'ix_social_notifications_actor_profile_id', ['actor_profile_id'], false, 'btree'],
  ['social_notifications', 'ix_social_notifications_source_type_concept_id', ['source_type_concept_id'], false, 'btree'],
  ['social_notifications', 'ix_social_notifications_notification_request_id', ['notification_request_id'], false, 'btree'],
  ['social_notifications', 'ix_social_notifications_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['social_notifications', 'ix_social_notifications_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['social_notifications', 'ix_social_notifications_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['social_posts', 'ix_social_posts_author_public_profile_id', ['author_public_profile_id'], false, 'btree'],
  ['social_posts', 'ix_social_posts_post_type_concept_id', ['post_type_concept_id'], false, 'btree'],
  ['social_posts', 'ix_social_posts_visibility_concept_id', ['visibility_concept_id'], false, 'btree'],
  ['social_posts', 'ix_social_posts_health_data_screening_status_concept_id', ['health_data_screening_status_concept_id'], false, 'btree'],
  ['social_posts', 'ix_social_posts_moderation_status_concept_id', ['moderation_status_concept_id'], false, 'btree'],
  ['social_posts', 'ix_social_posts_publication_status_concept_id', ['publication_status_concept_id'], false, 'btree'],
  ['social_posts', 'ix_social_posts_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['social_posts', 'ix_social_posts_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['social_posts', 'ix_social_posts_profile_publication', ['author_public_profile_id', 'publication_status_concept_id', 'published_at desc'], false, 'btree'],
  ['topics', 'uq_topics_code', ['code'], true, 'btree'],
  ['topics', 'ix_topics_parent_topic_id', ['parent_topic_id'], false, 'btree'],
  ['topics', 'ix_topics_specialty_concept_id', ['specialty_concept_id'], false, 'btree'],
  ['topics', 'ix_topics_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['topics', 'ix_topics_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['topics', 'ix_topics_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['user_blocks', 'ix_user_blocks_blocker_profile_id', ['blocker_profile_id'], false, 'btree'],
  ['user_blocks', 'ix_user_blocks_blocked_profile_id', ['blocked_profile_id'], false, 'btree'],
  ['user_blocks', 'ix_user_blocks_reason_concept_id', ['reason_concept_id'], false, 'btree'],
  ['user_blocks', 'ix_user_blocks_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['user_blocks', 'ix_user_blocks_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['user_blocks', 'ix_user_blocks_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['verified_badges', 'ix_verified_badges_subject_type_concept_id', ['subject_type_concept_id'], false, 'btree'],
  ['verified_badges', 'ix_verified_badges_badge_type_concept_id', ['badge_type_concept_id'], false, 'btree'],
  ['verified_badges', 'ix_verified_badges_verification_method_concept_id', ['verification_method_concept_id'], false, 'btree'],
  ['verified_badges', 'ix_verified_badges_verified_by_user_id', ['verified_by_user_id'], false, 'btree'],
  ['verified_badges', 'ix_verified_badges_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['verified_badges', 'ix_verified_badges_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['verified_badges', 'ix_verified_badges_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
];
