import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `community` (parte 1/2).
 * 180 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const communityIndexes1: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['bookmarks', 'ix_bookmarks_profile_id', ['profile_id'], false, 'btree'],
  ['bookmarks', 'ix_bookmarks_bookmarkable_type_concept_id', ['bookmarkable_type_concept_id'], false, 'btree'],
  ['bookmarks', 'ix_bookmarks_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['bookmarks', 'ix_bookmarks_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['comments', 'ix_comments_tenant_id', ['tenant_id'], false, 'btree'],
  ['comments', 'ix_comments_author_profile_id', ['author_profile_id'], false, 'btree'],
  ['comments', 'ix_comments_commentable_type_concept_id', ['commentable_type_concept_id'], false, 'btree'],
  ['comments', 'ix_comments_parent_comment_id', ['parent_comment_id'], false, 'btree'],
  ['comments', 'ix_comments_root_comment_id', ['root_comment_id'], false, 'btree'],
  ['comments', 'ix_comments_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['comments', 'ix_comments_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['comments', 'ix_comments_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['comments', 'ix_comments_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['comments', 'ix_comments_thread', ['commentable_type_concept_id', 'commentable_ref_id', 'root_comment_id', 'created_at'], false, 'btree'],
  ['comment_media', 'ix_comment_media_comment_id', ['comment_id'], false, 'btree'],
  ['comment_media', 'ix_comment_media_file_id', ['file_id'], false, 'btree'],
  ['comment_media', 'ix_comment_media_media_role_concept_id', ['media_role_concept_id'], false, 'btree'],
  ['comment_media', 'ix_comment_media_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['content_hashtags', 'ix_content_hashtags_hashtag_id', ['hashtag_id'], false, 'btree'],
  ['content_hashtags', 'ix_content_hashtags_content_type_concept_id', ['content_type_concept_id'], false, 'btree'],
  ['content_hashtags', 'ix_content_hashtags_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['content_hashtags', 'ix_content_hashtags_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['content_reports', 'ix_content_reports_reporter_user_id', ['reporter_user_id'], false, 'btree'],
  ['content_reports', 'ix_content_reports_target_type_concept_id', ['target_type_concept_id'], false, 'btree'],
  ['content_reports', 'ix_content_reports_reason_concept_id', ['reason_concept_id'], false, 'btree'],
  ['content_reports', 'ix_content_reports_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['content_reports', 'ix_content_reports_assigned_moderator_user_id', ['assigned_moderator_user_id'], false, 'btree'],
  ['conversations', 'ix_conversations_pinned_message_id', ['pinned_message_id'], false, 'btree'],
  ['conversations', 'ix_conversations_tenant_id', ['tenant_id'], false, 'btree'],
  ['conversations', 'ix_conversations_conversation_type_concept_id', ['conversation_type_concept_id'], false, 'btree'],
  ['conversations', 'ix_conversations_group_id', ['group_id'], false, 'btree'],
  ['conversations', 'ix_conversations_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['conversations', 'ix_conversations_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['conversations', 'ix_conversations_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['conversations', 'ix_conversations_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['conversation_participants', 'ix_conversation_participants_profile_pinned', ['participant_profile_id', 'is_pinned'], false, 'btree', 'is_pinned'],
  ['conversation_participants', 'ix_conversation_participants_conversation_id', ['conversation_id'], false, 'btree'],
  ['conversation_participants', 'ix_conversation_participants_participant_profile_id', ['participant_profile_id'], false, 'btree'],
  ['conversation_participants', 'ix_conversation_participants_role_concept_id', ['role_concept_id'], false, 'btree'],
  ['conversation_participants', 'ix_conversation_participants_last_read_message_id', ['last_read_message_id'], false, 'btree'],
  ['conversation_participants', 'ix_conversation_participants_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['conversation_participants', 'ix_conversation_participants_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['conversation_participants', 'ix_conversation_participants_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['direct_messages', 'ix_direct_messages_conversation_id', ['conversation_id'], false, 'btree'],
  ['direct_messages', 'ix_direct_messages_sender_profile_id', ['sender_profile_id'], false, 'btree'],
  ['direct_messages', 'ix_direct_messages_reply_to_message_id', ['reply_to_message_id'], false, 'btree'],
  ['direct_messages', 'ix_direct_messages_content_type_concept_id', ['content_type_concept_id'], false, 'btree'],
  ['direct_messages', 'ix_direct_messages_attachment_file_id', ['attachment_file_id'], false, 'btree'],
  ['direct_messages', 'ix_direct_messages_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['direct_messages', 'ix_direct_messages_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['direct_messages', 'ix_direct_messages_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['feedback_tickets', 'uk_feedback_tickets_ticket_number', ['tenant_id', 'ticket_number'], true, 'btree'],
  ['feedback_tickets', 'ix_feedback_tickets_reporter_user_id', ['reporter_user_id'], false, 'btree'],
  ['feedback_tickets', 'ix_feedback_tickets_category_concept_id', ['category_concept_id'], false, 'btree'],
  ['feedback_tickets', 'ix_feedback_tickets_status_concept_id', ['tenant_id', 'status_concept_id'], false, 'btree'],
  ['feedback_tickets', 'ix_feedback_tickets_severity_concept_id', ['severity_concept_id'], false, 'btree'],
  ['feedback_tickets', 'ix_feedback_tickets_assigned_to_user_id', ['assigned_to_user_id'], false, 'btree'],
  ['feedback_tickets', 'ix_feedback_tickets_opened_at', ['opened_at'], false, 'btree'],
  ['feedback_ticket_comments', 'ix_feedback_ticket_comments_feedback_ticket_id', ['feedback_ticket_id'], false, 'btree'],
  ['feedback_ticket_comments', 'ix_feedback_ticket_comments_author_user_id', ['author_user_id'], false, 'btree'],
  ['feedback_ticket_comments', 'ix_feedback_ticket_comments_created_at', ['created_at'], false, 'btree'],
  ['feedback_ticket_events', 'ix_feedback_ticket_events_feedback_ticket_id', ['feedback_ticket_id'], false, 'btree'],
  ['feedback_ticket_events', 'uk_feedback_ticket_events_revision', ['feedback_ticket_id', 'revision_no'], true, 'btree'],
  ['feedback_ticket_events', 'ix_feedback_ticket_events_to_status_concept_id', ['to_status_concept_id'], false, 'btree'],
  ['feedback_ticket_events', 'ix_feedback_ticket_events_recorded_at', ['recorded_at'], false, 'btree'],
  ['feed_items', 'ix_feed_items_owner_profile_id', ['owner_profile_id'], false, 'btree'],
  ['feed_items', 'ix_feed_items_item_type_concept_id', ['item_type_concept_id'], false, 'btree'],
  ['feed_items', 'ix_feed_items_source_type_concept_id', ['source_type_concept_id'], false, 'btree'],
  ['feed_items', 'ix_feed_items_origin_concept_id', ['origin_concept_id'], false, 'btree'],
  ['feed_items', 'ix_feed_items_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['feed_items', 'ix_feed_items_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['groups', 'uq_groups_slug', ['slug'], true, 'btree'],
  ['groups', 'ix_groups_tenant_id', ['tenant_id'], false, 'btree'],
  ['groups', 'ix_groups_visibility_concept_id', ['visibility_concept_id'], false, 'btree'],
  ['groups', 'ix_groups_group_type_concept_id', ['group_type_concept_id'], false, 'btree'],
  ['groups', 'ix_groups_topic_id', ['topic_id'], false, 'btree'],
  ['groups', 'ix_groups_owner_profile_id', ['owner_profile_id'], false, 'btree'],
  ['groups', 'ix_groups_cover_file_id', ['cover_file_id'], false, 'btree'],
  ['groups', 'ix_groups_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['groups', 'ix_groups_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['groups', 'ix_groups_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['groups', 'ix_groups_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['group_members', 'ix_group_members_group_id', ['group_id'], false, 'btree'],
  ['group_members', 'ix_group_members_member_profile_id', ['member_profile_id'], false, 'btree'],
  ['group_members', 'ix_group_members_member_role_concept_id', ['member_role_concept_id'], false, 'btree'],
  ['group_members', 'ix_group_members_join_status_concept_id', ['join_status_concept_id'], false, 'btree'],
  ['group_members', 'ix_group_members_invited_by_profile_id', ['invited_by_profile_id'], false, 'btree'],
  ['group_members', 'ix_group_members_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['group_members', 'ix_group_members_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['hashtags', 'uq_hashtags_tag', ['tag'], true, 'btree'],
  ['hashtags', 'ix_hashtags_topic_id', ['topic_id'], false, 'btree'],
  ['hashtags', 'ix_hashtags_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['hashtags', 'ix_hashtags_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['hashtags', 'ix_hashtags_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['mentions', 'ix_mentions_source_type_concept_id', ['source_type_concept_id'], false, 'btree'],
  ['mentions', 'ix_mentions_mentioned_profile_id', ['mentioned_profile_id'], false, 'btree'],
  ['mentions', 'ix_mentions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['mentions', 'ix_mentions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['mentions', 'ix_mentions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['message_receipts', 'ix_message_receipts_direct_message_id', ['direct_message_id'], false, 'btree'],
  ['message_receipts', 'ix_message_receipts_recipient_profile_id', ['recipient_profile_id'], false, 'btree'],
  ['message_receipts', 'ix_message_receipts_receipt_type_concept_id', ['receipt_type_concept_id'], false, 'btree'],
  ['message_receipts', 'ix_message_receipts_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['message_receipts', 'brin_message_receipts_recorded_at', ['recorded_at'], false, 'brin'],
  ['moderation_appeals', 'ix_moderation_appeals_moderation_decision_id', ['moderation_decision_id'], false, 'btree'],
  ['moderation_appeals', 'ix_moderation_appeals_appellant_profile_id', ['appellant_profile_id'], false, 'btree'],
  ['moderation_appeals', 'ix_moderation_appeals_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['moderation_appeals', 'ix_moderation_appeals_reviewed_by_user_id', ['reviewed_by_user_id'], false, 'btree'],
  ['moderation_appeals', 'ix_moderation_appeals_resolution_concept_id', ['resolution_concept_id'], false, 'btree'],
  ['moderation_appeals', 'ix_moderation_appeals_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['moderation_appeals', 'ix_moderation_appeals_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['moderation_decisions', 'ix_moderation_decisions_moderation_queue_id', ['moderation_queue_id'], false, 'btree'],
  ['moderation_decisions', 'ix_moderation_decisions_decision_concept_id', ['decision_concept_id'], false, 'btree'],
  ['moderation_decisions', 'ix_moderation_decisions_policy_concept_id', ['policy_concept_id'], false, 'btree'],
  ['moderation_decisions', 'ix_moderation_decisions_action_taken_concept_id', ['action_taken_concept_id'], false, 'btree'],
  ['moderation_decisions', 'ix_moderation_decisions_decided_by_user_id', ['decided_by_user_id'], false, 'btree'],
  ['moderation_decisions', 'ix_moderation_decisions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['moderation_decisions', 'ix_moderation_decisions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['moderation_queue', 'ix_moderation_queue_tenant_id', ['tenant_id'], false, 'btree'],
  ['moderation_queue', 'ix_moderation_queue_content_type_concept_id', ['content_type_concept_id'], false, 'btree'],
  ['moderation_queue', 'ix_moderation_queue_source_concept_id', ['source_concept_id'], false, 'btree'],
  ['moderation_queue', 'ix_moderation_queue_content_report_id', ['content_report_id'], false, 'btree'],
  ['moderation_queue', 'ix_moderation_queue_priority_concept_id', ['priority_concept_id'], false, 'btree'],
  ['moderation_queue', 'ix_moderation_queue_assigned_to_user_id', ['assigned_to_user_id'], false, 'btree'],
  ['moderation_queue', 'ix_moderation_queue_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['moderation_queue', 'ix_moderation_queue_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['moderation_queue', 'ix_moderation_queue_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['moderation_queue', 'ix_moderation_queue_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['moderation_strikes', 'ix_moderation_strikes_subject_profile_id', ['subject_profile_id'], false, 'btree'],
  ['moderation_strikes', 'ix_moderation_strikes_moderation_decision_id', ['moderation_decision_id'], false, 'btree'],
  ['moderation_strikes', 'ix_moderation_strikes_severity_concept_id', ['severity_concept_id'], false, 'btree'],
  ['moderation_strikes', 'ix_moderation_strikes_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['moderation_strikes', 'ix_moderation_strikes_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['moderation_strikes', 'ix_moderation_strikes_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['polls', 'ix_polls_post_id', ['post_id'], false, 'btree'],
  ['polls', 'ix_polls_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['polls', 'ix_polls_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['polls', 'ix_polls_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['poll_options', 'ix_poll_options_poll_id', ['poll_id'], false, 'btree'],
  ['poll_options', 'ix_poll_options_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['poll_options', 'ix_poll_options_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['poll_votes', 'ix_poll_votes_poll_id', ['poll_id'], false, 'btree'],
  ['poll_votes', 'ix_poll_votes_poll_option_id', ['poll_option_id'], false, 'btree'],
  ['poll_votes', 'ix_poll_votes_voter_profile_id', ['voter_profile_id'], false, 'btree'],
  ['poll_votes', 'ix_poll_votes_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['poll_votes', 'ix_poll_votes_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['post_media', 'ix_post_media_post_id', ['post_id'], false, 'btree'],
  ['post_media', 'ix_post_media_file_id', ['file_id'], false, 'btree'],
  ['post_media', 'ix_post_media_media_role_concept_id', ['media_role_concept_id'], false, 'btree'],
  ['post_media', 'ix_post_media_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['post_shares', 'ix_post_shares_post_id', ['post_id'], false, 'btree'],
  ['post_shares', 'ix_post_shares_sharer_profile_id', ['sharer_profile_id'], false, 'btree'],
  ['post_shares', 'ix_post_shares_share_type_concept_id', ['share_type_concept_id'], false, 'btree'],
  ['post_shares', 'ix_post_shares_target_group_id', ['target_group_id'], false, 'btree'],
  ['post_shares', 'ix_post_shares_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['post_shares', 'ix_post_shares_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['prestige_awards', 'uk_prestige_awards_idempotency_key', ['idempotency_key'], true, 'btree'],
  ['prestige_awards', 'ix_prestige_awards_subject', ['tenant_id', 'subject_type_concept_id', 'subject_ref_id'], false, 'btree'],
  ['prestige_awards', 'ix_prestige_awards_public_profile_id', ['public_profile_id'], false, 'btree'],
  ['prestige_awards', 'ix_prestige_awards_awarded_by_user_id', ['awarded_by_user_id'], false, 'btree'],
  ['prestige_awards', 'ix_prestige_awards_reason_concept_id', ['reason_concept_id'], false, 'btree'],
  ['prestige_awards', 'ix_prestige_awards_recorded_at', ['recorded_at'], false, 'btree'],
  ['prestige_scores', 'uk_prestige_scores_subject', ['tenant_id', 'subject_type_concept_id', 'subject_ref_id'], true, 'btree'],
  ['prestige_scores', 'ix_prestige_scores_public_profile_id', ['public_profile_id'], false, 'btree'],
  ['prestige_scores', 'ix_prestige_scores_level_concept_id', ['level_concept_id'], false, 'btree'],
  ['prestige_scores', 'ix_prestige_scores_total_points', ['tenant_id', 'total_points'], false, 'btree'],
  ['public_profiles', 'uq_public_profiles_slug', ['slug'], true, 'btree'],
  ['public_profiles', 'ix_public_profiles_tenant_id', ['tenant_id'], false, 'btree'],
  ['public_profiles', 'ix_public_profiles_target_type_concept_id', ['target_type_concept_id'], false, 'btree'],
  ['public_profiles', 'ix_public_profiles_avatar_file_id', ['avatar_file_id'], false, 'btree'],
  ['public_profiles', 'ix_public_profiles_cover_file_id', ['cover_file_id'], false, 'btree'],
  ['public_profiles', 'ix_public_profiles_verification_status_concept_id', ['verification_status_concept_id'], false, 'btree'],
  ['public_profiles', 'ix_public_profiles_visibility_concept_id', ['visibility_concept_id'], false, 'btree'],
  ['public_profiles', 'ix_public_profiles_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['public_profiles', 'ix_public_profiles_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['public_profiles', 'ix_public_profiles_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['public_profiles', 'ix_public_profiles_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['reactions', 'ix_reactions_actor_profile_id', ['actor_profile_id'], false, 'btree'],
  ['reactions', 'ix_reactions_reactable_type_concept_id', ['reactable_type_concept_id'], false, 'btree'],
  ['reactions', 'ix_reactions_reaction_type_concept_id', ['reaction_type_concept_id'], false, 'btree'],
];
