import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `consent`.
 * 97 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const consentIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['consents', 'ix_consents_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['consents', 'ix_consents_granted_by_user_id', ['granted_by_user_id'], false, 'btree'],
  ['consents', 'ix_consents_granted_by_related_person_id', ['granted_by_related_person_id'], false, 'btree'],
  ['consents', 'ix_consents_category_concept_id', ['category_concept_id'], false, 'btree'],
  ['consents', 'ix_consents_processing_purpose_id', ['processing_purpose_id'], false, 'btree'],
  ['consents', 'ix_consents_processing_legal_basis_id', ['processing_legal_basis_id'], false, 'btree'],
  ['consents', 'ix_consents_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['consents', 'ix_consents_tenant_id', ['tenant_id'], false, 'btree'],
  ['consents', 'ix_consents_withdrawal_reason_concept_id', ['withdrawal_reason_concept_id'], false, 'btree'],
  ['consents', 'ix_consents_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['consents', 'ix_consents_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['consents', 'ix_consents_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['consents', 'ix_consents_patient_profile_id_updated_at', ['tenant_id', 'patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['consents', 'ix_consents_patient_purpose_status', ['patient_profile_id', 'processing_purpose_id', 'status_concept_id', 'valid_from desc'], false, 'btree'],
  ['consent_events', 'ix_consent_events_subject_type_concept_id', ['subject_type_concept_id'], false, 'btree'],
  ['consent_events', 'ix_consent_events_event_type_concept_id', ['event_type_concept_id'], false, 'btree'],
  ['consent_events', 'ix_consent_events_previous_status_concept_id', ['previous_status_concept_id'], false, 'btree'],
  ['consent_events', 'ix_consent_events_new_status_concept_id', ['new_status_concept_id'], false, 'btree'],
  ['consent_events', 'ix_consent_events_reason_concept_id', ['reason_concept_id'], false, 'btree'],
  ['consent_events', 'ix_consent_events_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['consent_events', 'brin_consent_events_recorded_at', ['recorded_at'], false, 'brin'],
  ['consent_evidence', 'ix_consent_evidence_subject_type_concept_id', ['subject_type_concept_id'], false, 'btree'],
  ['consent_evidence', 'ix_consent_evidence_evidence_type_concept_id', ['evidence_type_concept_id'], false, 'btree'],
  ['consent_evidence', 'ix_consent_evidence_document_file_id', ['document_file_id'], false, 'btree'],
  ['consent_evidence', 'ix_consent_evidence_signature_id', ['signature_id'], false, 'btree'],
  ['consent_evidence', 'ix_consent_evidence_captured_channel_concept_id', ['captured_channel_concept_id'], false, 'btree'],
  ['consent_evidence', 'ix_consent_evidence_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['consent_evidence', 'brin_consent_evidence_recorded_at', ['recorded_at'], false, 'brin'],
  ['consent_provisions', 'ix_consent_provisions_consent_id', ['consent_id'], false, 'btree'],
  ['consent_provisions', 'ix_consent_provisions_provision_type_concept_id', ['provision_type_concept_id'], false, 'btree'],
  ['consent_provisions', 'ix_consent_provisions_action_concept_id', ['action_concept_id'], false, 'btree'],
  ['consent_provisions', 'ix_consent_provisions_data_class_concept_id', ['data_class_concept_id'], false, 'btree'],
  ['consent_provisions', 'ix_consent_provisions_actor_tenant_id', ['actor_tenant_id'], false, 'btree'],
  ['consent_provisions', 'ix_consent_provisions_actor_user_id', ['actor_user_id'], false, 'btree'],
  ['consent_provisions', 'ix_consent_provisions_actor_role_concept_id', ['actor_role_concept_id'], false, 'btree'],
  ['consent_provisions', 'ix_consent_provisions_purpose_of_use_concept_id', ['purpose_of_use_concept_id'], false, 'btree'],
  ['consent_provisions', 'ix_consent_provisions_security_label_concept_id', ['security_label_concept_id'], false, 'btree'],
  ['consent_provisions', 'ix_consent_provisions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['consent_provisions', 'ix_consent_provisions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['hipaa_authorizations', 'ix_hipaa_authorizations_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['hipaa_authorizations', 'ix_hipaa_authorizations_tenant_id', ['tenant_id'], false, 'btree'],
  ['hipaa_authorizations', 'ix_hipaa_authorizations_processing_purpose_id', ['processing_purpose_id'], false, 'btree'],
  ['hipaa_authorizations', 'ix_hipaa_authorizations_expiration_type_concept_id', ['expiration_type_concept_id'], false, 'btree'],
  ['hipaa_authorizations', 'ix_hipaa_authorizations_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['hipaa_authorizations', 'ix_hipaa_authorizations_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['hipaa_authorizations', 'ix_hipaa_authorizations_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['hipaa_authorizations', 'ix_hipaa_authorizations_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['hipaa_authorizations', 'ix_hipaa_authorizations_patient_profile_id_updated_at', ['tenant_id', 'patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['patient_objections', 'ix_patient_objections_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['patient_objections', 'ix_patient_objections_tenant_id', ['tenant_id'], false, 'btree'],
  ['patient_objections', 'ix_patient_objections_processing_purpose_id', ['processing_purpose_id'], false, 'btree'],
  ['patient_objections', 'ix_patient_objections_objection_type_concept_id', ['objection_type_concept_id'], false, 'btree'],
  ['patient_objections', 'ix_patient_objections_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['patient_objections', 'ix_patient_objections_resolution_concept_id', ['resolution_concept_id'], false, 'btree'],
  ['patient_objections', 'ix_patient_objections_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['patient_objections', 'ix_patient_objections_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['patient_objections', 'ix_patient_objections_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['patient_objections', 'ix_patient_objections_patient_profile_id_updated_at', ['tenant_id', 'patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['privacy_restrictions', 'ix_privacy_restrictions_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['privacy_restrictions', 'ix_privacy_restrictions_tenant_id', ['tenant_id'], false, 'btree'],
  ['privacy_restrictions', 'ix_privacy_restrictions_restriction_type_concept_id', ['restriction_type_concept_id'], false, 'btree'],
  ['privacy_restrictions', 'ix_privacy_restrictions_data_class_concept_id', ['data_class_concept_id'], false, 'btree'],
  ['privacy_restrictions', 'ix_privacy_restrictions_target_actor_type_concept_id', ['target_actor_type_concept_id'], false, 'btree'],
  ['privacy_restrictions', 'ix_privacy_restrictions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['privacy_restrictions', 'ix_privacy_restrictions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['privacy_restrictions', 'ix_privacy_restrictions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['privacy_restrictions', 'ix_privacy_restrictions_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['privacy_restrictions', 'ix_privacy_restrictions_patient_profile_id_updated_at', ['tenant_id', 'patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['processing_legal_bases', 'ix_processing_legal_bases_tenant_id', ['tenant_id'], false, 'btree'],
  ['processing_legal_bases', 'ix_processing_legal_bases_processing_purpose_id', ['processing_purpose_id'], false, 'btree'],
  ['processing_legal_bases', 'ix_processing_legal_bases_jurisdiction_concept_id', ['jurisdiction_concept_id'], false, 'btree'],
  ['processing_legal_bases', 'ix_processing_legal_bases_general_legal_basis_concept_id', ['general_legal_basis_concept_id'], false, 'btree'],
  ['processing_legal_bases', 'ix_processing_legal_bases_special_category_condition_concept_id', ['special_category_condition_concept_id'], false, 'btree'],
  ['processing_legal_bases', 'ix_processing_legal_bases_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['processing_legal_bases', 'ix_processing_legal_bases_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['processing_legal_bases', 'ix_processing_legal_bases_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['processing_legal_bases', 'ix_processing_legal_bases_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['processing_legal_bases', 'uq_processing_legal_basis_version', ['tenant_id', 'processing_purpose_id', 'jurisdiction_concept_id', 'valid_from'], true, 'btree'],
  ['processing_purposes', 'uq_processing_purposes_code', ['code'], true, 'btree'],
  ['processing_purposes', 'ix_processing_purposes_purpose_category_concept_id', ['purpose_category_concept_id'], false, 'btree'],
  ['processing_purposes', 'ix_processing_purposes_purpose_of_use_concept_id', ['purpose_of_use_concept_id'], false, 'btree'],
  ['processing_purposes', 'ix_processing_purposes_default_retention_class_concept_id', ['default_retention_class_concept_id'], false, 'btree'],
  ['processing_purposes', 'ix_processing_purposes_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['processing_purposes', 'ix_processing_purposes_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['processing_purposes', 'ix_processing_purposes_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['treatment_informed_consents', 'ix_treatment_informed_consents_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['treatment_informed_consents', 'ix_treatment_informed_consents_tenant_id', ['tenant_id'], false, 'btree'],
  ['treatment_informed_consents', 'ix_treatment_informed_consents_encounter_id', ['encounter_id'], false, 'btree'],
  ['treatment_informed_consents', 'ix_treatment_informed_consents_procedure_code_concept_id', ['procedure_code_concept_id'], false, 'btree'],
  ['treatment_informed_consents', 'ix_treatment_informed_consents_interpreter_user_id', ['interpreter_user_id'], false, 'btree'],
  ['treatment_informed_consents', 'ix_treatment_informed_consents_witness_user_id', ['witness_user_id'], false, 'btree'],
  ['treatment_informed_consents', 'ix_treatment_informed_consents_decision_concept_id', ['decision_concept_id'], false, 'btree'],
  ['treatment_informed_consents', 'ix_treatment_informed_consents_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['treatment_informed_consents', 'ix_treatment_informed_consents_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['treatment_informed_consents', 'ix_treatment_informed_consents_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['treatment_informed_consents', 'ix_treatment_informed_consents_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['treatment_informed_consents', 'ix_treatment_informed_consents_patient_profile_id_updated_at', ['tenant_id', 'patient_profile_id', 'updated_at desc'], false, 'btree'],
];
