import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `crm` (parte 1/2).
 * 180 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const crmIndexes1: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['account_contact_relations', 'uq_account_contact_relations_crm_account_id_contact_id_6579264d', ['crm_account_id', 'contact_id', 'relation_role_concept_id', 'valid_from'], true, 'btree'],
  ['account_contact_relations', 'ix_account_contact_relations_crm_account_id', ['crm_account_id'], false, 'btree'],
  ['account_contact_relations', 'ix_account_contact_relations_contact_id', ['contact_id'], false, 'btree'],
  ['account_contact_relations', 'ix_account_contact_relations_relation_role_concept_id', ['relation_role_concept_id'], false, 'btree'],
  ['account_contact_relations', 'ix_account_contact_relations_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['account_contact_relations', 'ix_account_contact_relations_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['account_contact_relations', 'ix_account_contact_relations_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['account_team_members', 'uq_account_team_members_crm_account_id_user_id_team_ro_099044e1', ['crm_account_id', 'user_id', 'team_role_concept_id', 'valid_from'], true, 'btree'],
  ['account_team_members', 'ix_account_team_members_crm_account_id', ['crm_account_id'], false, 'btree'],
  ['account_team_members', 'ix_account_team_members_user_id', ['user_id'], false, 'btree'],
  ['account_team_members', 'ix_account_team_members_team_role_concept_id', ['team_role_concept_id'], false, 'btree'],
  ['account_team_members', 'ix_account_team_members_access_level_concept_id', ['access_level_concept_id'], false, 'btree'],
  ['account_team_members', 'ix_account_team_members_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['account_team_members', 'ix_account_team_members_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['contacts', 'ix_contacts_tenant_id', ['tenant_id'], false, 'btree'],
  ['contacts', 'ix_contacts_crm_account_id', ['crm_account_id'], false, 'btree'],
  ['contacts', 'ix_contacts_contact_type_concept_id', ['contact_type_concept_id'], false, 'btree'],
  ['contacts', 'ix_contacts_linked_user_id', ['linked_user_id'], false, 'btree'],
  ['contacts', 'ix_contacts_owner_user_id', ['owner_user_id'], false, 'btree'],
  ['contacts', 'ix_contacts_lifecycle_stage_concept_id', ['lifecycle_stage_concept_id'], false, 'btree'],
  ['contacts', 'ix_contacts_source_concept_id', ['source_concept_id'], false, 'btree'],
  ['contacts', 'ix_contacts_marketing_consent_id', ['marketing_consent_id'], false, 'btree'],
  ['contacts', 'ix_contacts_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['contacts', 'ix_contacts_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['contacts', 'ix_contacts_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['contacts', 'ix_contacts_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['contact_channels', 'ix_contact_channels_contact_id', ['contact_id'], false, 'btree'],
  ['contact_channels', 'ix_contact_channels_channel_type_concept_id', ['channel_type_concept_id'], false, 'btree'],
  ['contact_channels', 'ix_contact_channels_opt_in_status_concept_id', ['opt_in_status_concept_id'], false, 'btree'],
  ['contact_channels', 'ix_contact_channels_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['contact_channels', 'ix_contact_channels_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['crm_accounts', 'ix_crm_accounts_tenant_id', ['tenant_id'], false, 'btree'],
  ['crm_accounts', 'ix_crm_accounts_account_type_concept_id', ['account_type_concept_id'], false, 'btree'],
  ['crm_accounts', 'ix_crm_accounts_industry_concept_id', ['industry_concept_id'], false, 'btree'],
  ['crm_accounts', 'ix_crm_accounts_parent_account_id', ['parent_account_id'], false, 'btree'],
  ['crm_accounts', 'ix_crm_accounts_linked_tenant_id', ['linked_tenant_id'], false, 'btree'],
  ['crm_accounts', 'ix_crm_accounts_business_partner_id', ['business_partner_id'], false, 'btree'],
  ['crm_accounts', 'ix_crm_accounts_owner_user_id', ['owner_user_id'], false, 'btree'],
  ['crm_accounts', 'ix_crm_accounts_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['crm_accounts', 'ix_crm_accounts_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['crm_accounts', 'ix_crm_accounts_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['crm_accounts', 'ix_crm_accounts_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['crm_accounts', 'ix_crm_accounts_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['crm_activities', 'ix_crm_activities_tenant_id', ['tenant_id'], false, 'btree'],
  ['crm_activities', 'ix_crm_activities_activity_type_concept_id', ['activity_type_concept_id'], false, 'btree'],
  ['crm_activities', 'ix_crm_activities_subject_type_concept_id', ['subject_type_concept_id'], false, 'btree'],
  ['crm_activities', 'ix_crm_activities_contact_id', ['contact_id'], false, 'btree'],
  ['crm_activities', 'ix_crm_activities_crm_account_id', ['crm_account_id'], false, 'btree'],
  ['crm_activities', 'ix_crm_activities_direction_concept_id', ['direction_concept_id'], false, 'btree'],
  ['crm_activities', 'ix_crm_activities_outcome_concept_id', ['outcome_concept_id'], false, 'btree'],
  ['crm_activities', 'ix_crm_activities_owner_user_id', ['owner_user_id'], false, 'btree'],
  ['crm_activities', 'ix_crm_activities_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['crm_activities', 'ix_crm_activities_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['crm_activities', 'ix_crm_activities_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['crm_activities', 'ix_crm_activities_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['crm_activity_assignments', 'uq_crm_activity_assignments_crm_activity_id_assignee_u_669bd146', ['crm_activity_id', 'assignee_user_id', 'assignment_role_concept_id'], true, 'btree'],
  ['crm_activity_assignments', 'ix_crm_activity_assignments_crm_activity_id', ['crm_activity_id'], false, 'btree'],
  ['crm_activity_assignments', 'ix_crm_activity_assignments_assignee_user_id', ['assignee_user_id'], false, 'btree'],
  ['crm_activity_assignments', 'ix_crm_activity_assignments_assignment_role_concept_id', ['assignment_role_concept_id'], false, 'btree'],
  ['crm_activity_assignments', 'ix_crm_activity_assignments_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['crm_activity_assignments', 'ix_crm_activity_assignments_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['crm_activity_assignments', 'ix_crm_activity_assignments_assignee_status_assigned', ['assignee_user_id', 'status_concept_id', 'assigned_at desc'], false, 'btree'],
  ['crm_activity_relations', 'ix_crm_activity_relations_crm_activity_id', ['crm_activity_id'], false, 'btree'],
  ['crm_activity_relations', 'ix_crm_activity_relations_relation_kind_concept_id', ['relation_kind_concept_id'], false, 'btree'],
  ['crm_activity_relations', 'ix_crm_activity_relations_related_entity_type_concept_id', ['related_entity_type_concept_id'], false, 'btree'],
  ['crm_activity_relations', 'ix_crm_activity_relations_crm_account_id', ['crm_account_id'], false, 'btree'],
  ['crm_activity_relations', 'ix_crm_activity_relations_contact_id', ['contact_id'], false, 'btree'],
  ['crm_activity_relations', 'ix_crm_activity_relations_lead_id', ['lead_id'], false, 'btree'],
  ['crm_activity_relations', 'ix_crm_activity_relations_opportunity_id', ['opportunity_id'], false, 'btree'],
  ['crm_activity_relations', 'ix_crm_activity_relations_partnership_id', ['partnership_id'], false, 'btree'],
  ['crm_activity_relations', 'ix_crm_activity_relations_contract_id', ['contract_id'], false, 'btree'],
  ['crm_activity_relations', 'ix_crm_activity_relations_case_id', ['case_id'], false, 'btree'],
  ['crm_activity_relations', 'ix_crm_activity_relations_related_user_id', ['related_user_id'], false, 'btree'],
  ['crm_activity_relations', 'ix_crm_activity_relations_participant_role_concept_id', ['participant_role_concept_id'], false, 'btree'],
  ['crm_activity_relations', 'ix_crm_activity_relations_response_status_concept_id', ['response_status_concept_id'], false, 'btree'],
  ['crm_activity_relations', 'ix_crm_activity_relations_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['crm_activity_relations', 'ix_crm_activity_relations_activity_kind', ['crm_activity_id', 'relation_kind_concept_id'], false, 'btree'],
  ['crm_activity_relations', 'ix_crm_activity_relations_account_activity', ['crm_account_id', 'crm_activity_id'], false, 'btree'],
  ['crm_activity_relations', 'ix_crm_activity_relations_contact_activity', ['contact_id', 'crm_activity_id'], false, 'btree'],
  ['crm_activity_relations', 'ix_crm_activity_relations_opportunity_activity', ['opportunity_id', 'crm_activity_id'], false, 'btree'],
  ['crm_activity_relations', 'ix_crm_activity_relations_case_activity', ['case_id', 'crm_activity_id'], false, 'btree'],
  ['crm_activity_reminders', 'uq_crm_activity_reminders_crm_activity_id_recipient_us_595aad96', ['crm_activity_id', 'recipient_user_id', 'remind_at'], true, 'btree'],
  ['crm_activity_reminders', 'ix_crm_activity_reminders_crm_activity_id', ['crm_activity_id'], false, 'btree'],
  ['crm_activity_reminders', 'ix_crm_activity_reminders_recipient_user_id', ['recipient_user_id'], false, 'btree'],
  ['crm_activity_reminders', 'ix_crm_activity_reminders_channel_concept_id', ['channel_concept_id'], false, 'btree'],
  ['crm_activity_reminders', 'ix_crm_activity_reminders_delivery_status_concept_id', ['delivery_status_concept_id'], false, 'btree'],
  ['crm_activity_reminders', 'ix_crm_activity_reminders_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['crm_activity_reminders', 'ix_crm_activity_reminders_delivery_remind', ['delivery_status_concept_id', 'remind_at'], false, 'btree'],
  ['crm_call_logs', 'uq_crm_call_logs_crm_activity_id', ['crm_activity_id'], true, 'btree'],
  ['crm_call_logs', 'ix_crm_call_logs_crm_activity_id', ['crm_activity_id'], false, 'btree'],
  ['crm_call_logs', 'ix_crm_call_logs_call_direction_concept_id', ['call_direction_concept_id'], false, 'btree'],
  ['crm_call_logs', 'ix_crm_call_logs_outcome_concept_id', ['outcome_concept_id'], false, 'btree'],
  ['crm_call_logs', 'ix_crm_call_logs_recording_file_id', ['recording_file_id'], false, 'btree'],
  ['crm_call_logs', 'ix_crm_call_logs_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['crm_cases', 'uq_crm_cases_tenant_id_case_number', ['tenant_id', 'case_number'], true, 'btree'],
  ['crm_cases', 'ix_crm_cases_tenant_id', ['tenant_id'], false, 'btree'],
  ['crm_cases', 'ix_crm_cases_crm_account_id', ['crm_account_id'], false, 'btree'],
  ['crm_cases', 'ix_crm_cases_primary_contact_id', ['primary_contact_id'], false, 'btree'],
  ['crm_cases', 'ix_crm_cases_business_partner_id', ['business_partner_id'], false, 'btree'],
  ['crm_cases', 'ix_crm_cases_contract_id', ['contract_id'], false, 'btree'],
  ['crm_cases', 'ix_crm_cases_invoice_id', ['invoice_id'], false, 'btree'],
  ['crm_cases', 'ix_crm_cases_case_type_concept_id', ['case_type_concept_id'], false, 'btree'],
  ['crm_cases', 'ix_crm_cases_origin_concept_id', ['origin_concept_id'], false, 'btree'],
  ['crm_cases', 'ix_crm_cases_priority_concept_id', ['priority_concept_id'], false, 'btree'],
  ['crm_cases', 'ix_crm_cases_owner_user_id', ['owner_user_id'], false, 'btree'],
  ['crm_cases', 'ix_crm_cases_parent_case_id', ['parent_case_id'], false, 'btree'],
  ['crm_cases', 'ix_crm_cases_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['crm_cases', 'ix_crm_cases_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['crm_cases', 'ix_crm_cases_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['crm_cases', 'ix_crm_cases_tenant_status_priority_updated', ['tenant_id', 'status_concept_id', 'priority_concept_id', 'updated_at desc'], false, 'btree'],
  ['crm_cases', 'ix_crm_cases_owner_status_updated', ['owner_user_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['crm_case_comments', 'ix_crm_case_comments_crm_case_id', ['crm_case_id'], false, 'btree'],
  ['crm_case_comments', 'ix_crm_case_comments_author_user_id', ['author_user_id'], false, 'btree'],
  ['crm_case_comments', 'ix_crm_case_comments_attachment_file_id', ['attachment_file_id'], false, 'btree'],
  ['crm_case_comments', 'ix_crm_case_comments_case_created', ['crm_case_id', 'created_at desc'], false, 'btree'],
  ['crm_case_comments', 'brin_crm_case_comments_created_at', ['created_at'], false, 'brin'],
  ['crm_case_contacts', 'uq_crm_case_contacts_crm_case_id_contact_id_role_concept_id', ['crm_case_id', 'contact_id', 'role_concept_id'], true, 'btree'],
  ['crm_case_contacts', 'ix_crm_case_contacts_crm_case_id', ['crm_case_id'], false, 'btree'],
  ['crm_case_contacts', 'ix_crm_case_contacts_contact_id', ['contact_id'], false, 'btree'],
  ['crm_case_contacts', 'ix_crm_case_contacts_role_concept_id', ['role_concept_id'], false, 'btree'],
  ['crm_case_contacts', 'ix_crm_case_contacts_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['crm_case_milestones', 'ix_crm_case_milestones_crm_case_id', ['crm_case_id'], false, 'btree'],
  ['crm_case_milestones', 'ix_crm_case_milestones_crm_entitlement_id', ['crm_entitlement_id'], false, 'btree'],
  ['crm_case_milestones', 'ix_crm_case_milestones_milestone_type_concept_id', ['milestone_type_concept_id'], false, 'btree'],
  ['crm_case_milestones', 'ix_crm_case_milestones_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['crm_case_milestones', 'ix_crm_case_milestones_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['crm_case_milestones', 'ix_crm_case_milestones_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['crm_case_milestones', 'ix_crm_case_milestones_status_target', ['status_concept_id', 'target_at'], false, 'btree'],
  ['crm_case_status_history', 'ix_crm_case_status_history_crm_case_id', ['crm_case_id'], false, 'btree'],
  ['crm_case_status_history', 'ix_crm_case_status_history_from_status_concept_id', ['from_status_concept_id'], false, 'btree'],
  ['crm_case_status_history', 'ix_crm_case_status_history_to_status_concept_id', ['to_status_concept_id'], false, 'btree'],
  ['crm_case_status_history', 'ix_crm_case_status_history_changed_by_user_id', ['changed_by_user_id'], false, 'btree'],
  ['crm_case_status_history', 'ix_crm_case_status_history_case_changed', ['crm_case_id', 'changed_at desc'], false, 'btree'],
  ['crm_case_status_history', 'brin_crm_case_status_history_created_at', ['created_at'], false, 'brin'],
  ['crm_email_messages', 'uq_crm_email_messages_crm_activity_id', ['crm_activity_id'], true, 'btree'],
  ['crm_email_messages', 'ix_crm_email_messages_crm_activity_id', ['crm_activity_id'], false, 'btree'],
  ['crm_email_messages', 'ix_crm_email_messages_body_html_file_id', ['body_html_file_id'], false, 'btree'],
  ['crm_email_messages', 'ix_crm_email_messages_delivery_status_concept_id', ['delivery_status_concept_id'], false, 'btree'],
  ['crm_email_messages', 'ix_crm_email_messages_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['crm_email_recipients', 'ix_crm_email_recipients_crm_email_message_id', ['crm_email_message_id'], false, 'btree'],
  ['crm_email_recipients', 'ix_crm_email_recipients_recipient_type_concept_id', ['recipient_type_concept_id'], false, 'btree'],
  ['crm_email_recipients', 'ix_crm_email_recipients_contact_id', ['contact_id'], false, 'btree'],
  ['crm_email_recipients', 'ix_crm_email_recipients_lead_id', ['lead_id'], false, 'btree'],
  ['crm_email_recipients', 'ix_crm_email_recipients_user_id', ['user_id'], false, 'btree'],
  ['crm_email_recipients', 'ix_crm_email_recipients_delivery_status_concept_id', ['delivery_status_concept_id'], false, 'btree'],
  ['crm_email_recipients', 'ix_crm_email_recipients_message_type', ['crm_email_message_id', 'recipient_type_concept_id'], false, 'btree'],
  ['crm_entitlements', 'ix_crm_entitlements_tenant_id', ['tenant_id'], false, 'btree'],
  ['crm_entitlements', 'ix_crm_entitlements_crm_account_id', ['crm_account_id'], false, 'btree'],
  ['crm_entitlements', 'ix_crm_entitlements_business_partner_id', ['business_partner_id'], false, 'btree'],
  ['crm_entitlements', 'ix_crm_entitlements_contract_id', ['contract_id'], false, 'btree'],
  ['crm_entitlements', 'ix_crm_entitlements_entitlement_type_concept_id', ['entitlement_type_concept_id'], false, 'btree'],
  ['crm_entitlements', 'ix_crm_entitlements_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['crm_entitlements', 'ix_crm_entitlements_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['crm_entitlements', 'ix_crm_entitlements_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['crm_entitlements', 'ix_crm_entitlements_account_status_end', ['crm_account_id', 'status_concept_id', 'end_date'], false, 'btree'],
  ['crm_events', 'uq_crm_events_crm_activity_id', ['crm_activity_id'], true, 'btree'],
  ['crm_events', 'ix_crm_events_crm_activity_id', ['crm_activity_id'], false, 'btree'],
  ['crm_events', 'ix_crm_events_event_subtype_concept_id', ['event_subtype_concept_id'], false, 'btree'],
  ['crm_events', 'ix_crm_events_organizer_user_id', ['organizer_user_id'], false, 'btree'],
  ['crm_events', 'ix_crm_events_recurrence_rule_id', ['recurrence_rule_id'], false, 'btree'],
  ['crm_events', 'ix_crm_events_parent_event_id', ['parent_event_id'], false, 'btree'],
  ['crm_events', 'ix_crm_events_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['crm_events', 'ix_crm_events_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['crm_events', 'ix_crm_events_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['crm_events', 'ix_crm_events_start_end', ['start_at', 'end_at'], false, 'btree'],
  ['crm_notes', 'uq_crm_notes_crm_activity_id', ['crm_activity_id'], true, 'btree'],
  ['crm_notes', 'ix_crm_notes_crm_activity_id', ['crm_activity_id'], false, 'btree'],
  ['crm_notes', 'ix_crm_notes_document_file_id', ['document_file_id'], false, 'btree'],
  ['crm_notes', 'ix_crm_notes_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['crm_notes', 'ix_crm_notes_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['crm_recurrence_rules', 'ix_crm_recurrence_rules_tenant_id', ['tenant_id'], false, 'btree'],
  ['crm_recurrence_rules', 'ix_crm_recurrence_rules_recurrence_frequency_concept_id', ['recurrence_frequency_concept_id'], false, 'btree'],
  ['crm_recurrence_rules', 'ix_crm_recurrence_rules_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['crm_recurrence_rules', 'ix_crm_recurrence_rules_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['crm_recurrence_rules', 'ix_crm_recurrence_rules_tenant_until', ['tenant_id', 'until_at'], false, 'btree'],
  ['crm_tasks', 'uq_crm_tasks_crm_activity_id', ['crm_activity_id'], true, 'btree'],
  ['crm_tasks', 'ix_crm_tasks_crm_activity_id', ['crm_activity_id'], false, 'btree'],
  ['crm_tasks', 'ix_crm_tasks_task_subtype_concept_id', ['task_subtype_concept_id'], false, 'btree'],
  ['crm_tasks', 'ix_crm_tasks_priority_concept_id', ['priority_concept_id'], false, 'btree'],
  ['crm_tasks', 'ix_crm_tasks_recurrence_rule_id', ['recurrence_rule_id'], false, 'btree'],
];
