import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `crm` (parte 2/2).
 * 76 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const crmIndexes2: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['crm_tasks', 'ix_crm_tasks_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['crm_tasks', 'ix_crm_tasks_status_due', ['status_concept_id', 'due_date'], false, 'btree'],
  ['leads', 'ix_leads_tenant_id', ['tenant_id'], false, 'btree'],
  ['leads', 'ix_leads_lead_source_concept_id', ['lead_source_concept_id'], false, 'btree'],
  ['leads', 'ix_leads_contact_id', ['contact_id'], false, 'btree'],
  ['leads', 'ix_leads_crm_account_id', ['crm_account_id'], false, 'btree'],
  ['leads', 'ix_leads_lead_status_concept_id', ['lead_status_concept_id'], false, 'btree'],
  ['leads', 'ix_leads_owner_user_id', ['owner_user_id'], false, 'btree'],
  ['leads', 'ix_leads_converted_opportunity_id', ['converted_opportunity_id'], false, 'btree'],
  ['leads', 'ix_leads_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['leads', 'ix_leads_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['leads', 'ix_leads_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['leads', 'ix_leads_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['opportunities', 'ix_opportunities_tenant_id', ['tenant_id'], false, 'btree'],
  ['opportunities', 'ix_opportunities_pipeline_id', ['pipeline_id'], false, 'btree'],
  ['opportunities', 'ix_opportunities_stage_id', ['stage_id'], false, 'btree'],
  ['opportunities', 'ix_opportunities_crm_account_id', ['crm_account_id'], false, 'btree'],
  ['opportunities', 'ix_opportunities_primary_contact_id', ['primary_contact_id'], false, 'btree'],
  ['opportunities', 'ix_opportunities_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['opportunities', 'ix_opportunities_owner_user_id', ['owner_user_id'], false, 'btree'],
  ['opportunities', 'ix_opportunities_contract_id', ['contract_id'], false, 'btree'],
  ['opportunities', 'ix_opportunities_sales_order_id', ['sales_order_id'], false, 'btree'],
  ['opportunities', 'ix_opportunities_lost_reason_concept_id', ['lost_reason_concept_id'], false, 'btree'],
  ['opportunities', 'ix_opportunities_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['opportunities', 'ix_opportunities_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['opportunities', 'ix_opportunities_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['opportunities', 'ix_opportunities_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['opportunity_contact_roles', 'uq_opportunity_contact_roles_opportunity_id_contact_id_06ce3ee3', ['opportunity_id', 'contact_id', 'role_concept_id'], true, 'btree'],
  ['opportunity_contact_roles', 'ix_opportunity_contact_roles_opportunity_id', ['opportunity_id'], false, 'btree'],
  ['opportunity_contact_roles', 'ix_opportunity_contact_roles_contact_id', ['contact_id'], false, 'btree'],
  ['opportunity_contact_roles', 'ix_opportunity_contact_roles_role_concept_id', ['role_concept_id'], false, 'btree'],
  ['opportunity_contact_roles', 'ix_opportunity_contact_roles_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['opportunity_contact_roles', 'ix_opportunity_contact_roles_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['opportunity_line_items', 'uq_opportunity_line_items_opportunity_id_line_number', ['opportunity_id', 'line_number'], true, 'btree'],
  ['opportunity_line_items', 'ix_opportunity_line_items_opportunity_id', ['opportunity_id'], false, 'btree'],
  ['opportunity_line_items', 'ix_opportunity_line_items_product_or_service_type_concept_id', ['product_or_service_type_concept_id'], false, 'btree'],
  ['opportunity_line_items', 'ix_opportunity_line_items_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['opportunity_line_items', 'ix_opportunity_line_items_contract_line_item_id', ['contract_line_item_id'], false, 'btree'],
  ['opportunity_line_items', 'ix_opportunity_line_items_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['opportunity_line_items', 'ix_opportunity_line_items_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['opportunity_line_items', 'ix_opportunity_line_items_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['opportunity_stage_history', 'ix_opportunity_stage_history_opportunity_id', ['opportunity_id'], false, 'btree'],
  ['opportunity_stage_history', 'ix_opportunity_stage_history_from_stage_id', ['from_stage_id'], false, 'btree'],
  ['opportunity_stage_history', 'ix_opportunity_stage_history_to_stage_id', ['to_stage_id'], false, 'btree'],
  ['opportunity_stage_history', 'ix_opportunity_stage_history_changed_by_user_id', ['changed_by_user_id'], false, 'btree'],
  ['opportunity_stage_history', 'ix_opportunity_stage_history_reason_concept_id', ['reason_concept_id'], false, 'btree'],
  ['opportunity_stage_history', 'ix_opportunity_stage_history_opportunity_changed', ['opportunity_id', 'changed_at desc'], false, 'btree'],
  ['partnership_agreements', 'ix_partnership_agreements_partnership_id', ['partnership_id'], false, 'btree'],
  ['partnership_agreements', 'ix_partnership_agreements_agreement_type_concept_id', ['agreement_type_concept_id'], false, 'btree'],
  ['partnership_agreements', 'ix_partnership_agreements_contract_id', ['contract_id'], false, 'btree'],
  ['partnership_agreements', 'ix_partnership_agreements_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['partnership_agreements', 'ix_partnership_agreements_document_file_id', ['document_file_id'], false, 'btree'],
  ['partnership_agreements', 'ix_partnership_agreements_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['partnership_agreements', 'ix_partnership_agreements_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['partnership_agreements', 'ix_partnership_agreements_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['partnerships', 'ix_partnerships_tenant_id', ['tenant_id'], false, 'btree'],
  ['partnerships', 'ix_partnerships_partnership_type_concept_id', ['partnership_type_concept_id'], false, 'btree'],
  ['partnerships', 'ix_partnerships_crm_account_id', ['crm_account_id'], false, 'btree'],
  ['partnerships', 'ix_partnerships_ad_partner_id', ['ad_partner_id'], false, 'btree'],
  ['partnerships', 'ix_partnerships_contract_id', ['contract_id'], false, 'btree'],
  ['partnerships', 'ix_partnerships_tier_concept_id', ['tier_concept_id'], false, 'btree'],
  ['partnerships', 'ix_partnerships_owner_user_id', ['owner_user_id'], false, 'btree'],
  ['partnerships', 'ix_partnerships_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['partnerships', 'ix_partnerships_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['partnerships', 'ix_partnerships_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['partnerships', 'ix_partnerships_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['pipeline_stages', 'ix_pipeline_stages_pipeline_id', ['pipeline_id'], false, 'btree'],
  ['pipeline_stages', 'ix_pipeline_stages_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['pipeline_stages', 'ix_pipeline_stages_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['pipelines', 'uq_pipelines_code', ['code'], true, 'btree'],
  ['pipelines', 'ix_pipelines_tenant_id', ['tenant_id'], false, 'btree'],
  ['pipelines', 'ix_pipelines_pipeline_type_concept_id', ['pipeline_type_concept_id'], false, 'btree'],
  ['pipelines', 'ix_pipelines_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['pipelines', 'ix_pipelines_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['pipelines', 'ix_pipelines_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['pipelines', 'ix_pipelines_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
];
