import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `delegated_access`.
 * 54 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const delegatedAccessIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['delegated_access_approval_requests', 'ix_delegated_access_approval_requests_practitioner_del_01d90a86', ['practitioner_delegate_assignment_id'], false, 'btree'],
  ['delegated_access_approval_requests', 'ix_delegated_access_approval_requests_requested_permission_id', ['requested_permission_id'], false, 'btree'],
  ['delegated_access_approval_requests', 'ix_delegated_access_approval_requests_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['delegated_access_approval_requests', 'ix_delegated_access_approval_requests_encounter_id', ['encounter_id'], false, 'btree'],
  ['delegated_access_approval_requests', 'ix_delegated_access_approval_requests_decided_by_user_id', ['decided_by_user_id'], false, 'btree'],
  ['delegated_access_approval_requests', 'ix_delegated_access_approval_requests_decision_concept_id', ['decision_concept_id'], false, 'btree'],
  ['delegated_access_approval_requests', 'ix_delegated_access_approval_requests_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['delegated_access_approval_requests', 'ix_delegated_access_approval_requests_patient_profile__beb5e078', ['patient_profile_id', 'created_at desc'], false, 'btree'],
  ['delegated_access_grants', 'ix_delegated_access_grants_practitioner_delegate_assignment_id', ['practitioner_delegate_assignment_id'], false, 'btree'],
  ['delegated_access_grants', 'ix_delegated_access_grants_grant_type_concept_id', ['grant_type_concept_id'], false, 'btree'],
  ['delegated_access_grants', 'ix_delegated_access_grants_purpose_of_use_concept_id', ['purpose_of_use_concept_id'], false, 'btree'],
  ['delegated_access_grants', 'ix_delegated_access_grants_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['delegated_access_grants', 'ix_delegated_access_grants_encounter_id', ['encounter_id'], false, 'btree'],
  ['delegated_access_grants', 'ix_delegated_access_grants_resource_type_concept_id', ['resource_type_concept_id'], false, 'btree'],
  ['delegated_access_grants', 'ix_delegated_access_grants_approved_by_user_id', ['approved_by_user_id'], false, 'btree'],
  ['delegated_access_grants', 'ix_delegated_access_grants_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['delegated_access_grants', 'ix_delegated_access_grants_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['delegated_access_grants', 'ix_delegated_access_grants_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['delegated_access_grants', 'ix_delegated_access_grants_patient_profile_id_updated_at', ['patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['delegated_permission_set_items', 'ix_delegated_permission_set_items_delegated_permission_set_id', ['delegated_permission_set_id'], false, 'btree'],
  ['delegated_permission_set_items', 'ix_delegated_permission_set_items_permission_id', ['permission_id'], false, 'btree'],
  ['delegated_permission_sets', 'ix_delegated_permission_sets_tenant_id', ['tenant_id'], false, 'btree'],
  ['delegated_permission_sets', 'ix_delegated_permission_sets_delegate_type_concept_id', ['delegate_type_concept_id'], false, 'btree'],
  ['delegated_permission_sets', 'ix_delegated_permission_sets_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['delegated_permission_sets', 'ix_delegated_permission_sets_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['delegated_permission_sets', 'ix_delegated_permission_sets_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['delegated_permission_sets', 'ix_delegated_permission_sets_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['delegation_events', 'ix_delegation_events_practitioner_delegate_assignment_id', ['practitioner_delegate_assignment_id'], false, 'btree'],
  ['delegation_events', 'ix_delegation_events_event_type_concept_id', ['event_type_concept_id'], false, 'btree'],
  ['delegation_events', 'ix_delegation_events_actor_user_id', ['actor_user_id'], false, 'btree'],
  ['delegation_events', 'ix_delegation_events_target_user_id', ['target_user_id'], false, 'btree'],
  ['delegation_events', 'ix_delegation_events_reason_concept_id', ['reason_concept_id'], false, 'btree'],
  ['organization_user_assignments', 'ix_organization_user_assignments_tenant_membership_id', ['tenant_membership_id'], false, 'btree'],
  ['organization_user_assignments', 'ix_organization_user_assignments_practice_id', ['practice_id'], false, 'btree'],
  ['organization_user_assignments', 'ix_organization_user_assignments_practice_site_id', ['practice_site_id'], false, 'btree'],
  ['organization_user_assignments', 'ix_organization_user_assignments_clinical_unit_id', ['clinical_unit_id'], false, 'btree'],
  ['organization_user_assignments', 'ix_organization_user_assignments_care_space_id', ['care_space_id'], false, 'btree'],
  ['organization_user_assignments', 'ix_organization_user_assignments_diagnostic_unit_id', ['diagnostic_unit_id'], false, 'btree'],
  ['organization_user_assignments', 'ix_organization_user_assignments_pharmacy_id', ['pharmacy_id'], false, 'btree'],
  ['organization_user_assignments', 'ix_organization_user_assignments_assignment_role_concept_id', ['assignment_role_concept_id'], false, 'btree'],
  ['organization_user_assignments', 'ix_organization_user_assignments_access_scope_concept_id', ['access_scope_concept_id'], false, 'btree'],
  ['organization_user_assignments', 'ix_organization_user_assignments_supervisor_user_id', ['supervisor_user_id'], false, 'btree'],
  ['organization_user_assignments', 'ix_organization_user_assignments_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['organization_user_assignments', 'ix_organization_user_assignments_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['organization_user_assignments', 'ix_organization_user_assignments_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['practitioner_delegate_assignments', 'ix_practitioner_delegate_assignments_practitioner_role_5ab23b12', ['practitioner_role_assignment_id'], false, 'btree'],
  ['practitioner_delegate_assignments', 'ix_practitioner_delegate_assignments_delegate_user_ass_52dcb36c', ['delegate_user_assignment_id'], false, 'btree'],
  ['practitioner_delegate_assignments', 'ix_practitioner_delegate_assignments_delegated_permiss_e45e3818', ['delegated_permission_set_id'], false, 'btree'],
  ['practitioner_delegate_assignments', 'ix_practitioner_delegate_assignments_delegate_role_concept_id', ['delegate_role_concept_id'], false, 'btree'],
  ['practitioner_delegate_assignments', 'ix_practitioner_delegate_assignments_patient_scope_concept_id', ['patient_scope_concept_id'], false, 'btree'],
  ['practitioner_delegate_assignments', 'ix_practitioner_delegate_assignments_appointment_scope_692488ef', ['appointment_scope_concept_id'], false, 'btree'],
  ['practitioner_delegate_assignments', 'ix_practitioner_delegate_assignments_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['practitioner_delegate_assignments', 'ix_practitioner_delegate_assignments_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['practitioner_delegate_assignments', 'ix_practitioner_delegate_assignments_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
];
