import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `diagnostics` (parte 2/2).
 * 108 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const diagnosticsIndexes2: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['laboratory_work_order_tests', 'ix_laboratory_work_order_tests_analyzer_device_id', ['analyzer_device_id'], false, 'btree'],
  ['laboratory_work_order_tests', 'ix_laboratory_work_order_tests_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['laboratory_work_order_tests', 'ix_laboratory_work_order_tests_observation_id', ['observation_id'], false, 'btree'],
  ['laboratory_work_order_tests', 'ix_laboratory_work_order_tests_diagnostic_report_id', ['diagnostic_report_id'], false, 'btree'],
  ['laboratory_work_order_tests', 'ix_laboratory_work_order_tests_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['laboratory_work_order_tests', 'ix_laboratory_work_order_tests_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['laboratory_work_order_tests', 'uk_lab_work_order_tests_order_request_code', ['laboratory_work_order_id', 'service_request_id', 'test_code_concept_id'], true, 'btree'],
  ['laboratory_work_orders', 'ix_laboratory_work_orders_custodian_tenant_id', ['custodian_tenant_id'], false, 'btree'],
  ['laboratory_work_orders', 'ix_laboratory_work_orders_laboratory_accession_id', ['laboratory_accession_id'], false, 'btree'],
  ['laboratory_work_orders', 'ix_laboratory_work_orders_assigned_laboratory_unit_id', ['assigned_laboratory_unit_id'], false, 'btree'],
  ['laboratory_work_orders', 'ix_laboratory_work_orders_assigned_profile_id', ['assigned_profile_id'], false, 'btree'],
  ['laboratory_work_orders', 'ix_laboratory_work_orders_priority_concept_id', ['priority_concept_id'], false, 'btree'],
  ['laboratory_work_orders', 'ix_laboratory_work_orders_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['laboratory_work_orders', 'ix_laboratory_work_orders_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['laboratory_work_orders', 'ix_laboratory_work_orders_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['laboratory_work_orders', 'uk_lab_work_orders_tenant_number', ['custodian_tenant_id', 'work_order_number'], true, 'btree'],
  ['media_annotations', 'ix_media_annotations_clinical_media_id', ['clinical_media_id'], false, 'btree'],
  ['media_annotations', 'ix_media_annotations_imaging_instance_id', ['imaging_instance_id'], false, 'btree'],
  ['media_annotations', 'ix_media_annotations_annotation_type_concept_id', ['annotation_type_concept_id'], false, 'btree'],
  ['media_annotations', 'ix_media_annotations_label_concept_id', ['label_concept_id'], false, 'btree'],
  ['media_annotations', 'ix_media_annotations_author_profile_id', ['author_profile_id'], false, 'btree'],
  ['media_annotations', 'ix_media_annotations_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['media_annotations', 'ix_media_annotations_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['media_annotations', 'ix_media_annotations_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['observation_specimens', 'ix_observation_specimens_observation_id', ['observation_id'], false, 'btree'],
  ['observation_specimens', 'ix_observation_specimens_specimen_id', ['specimen_id'], false, 'btree'],
  ['observation_specimens', 'ix_observation_specimens_relationship_concept_id', ['relationship_concept_id'], false, 'btree'],
  ['radiation_dose_events', 'ix_radiation_dose_events_custodian_tenant_id', ['custodian_tenant_id'], false, 'btree'],
  ['radiation_dose_events', 'ix_radiation_dose_events_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['radiation_dose_events', 'ix_radiation_dose_events_imaging_study_id', ['imaging_study_id'], false, 'btree'],
  ['radiation_dose_events', 'ix_radiation_dose_events_imaging_series_id', ['imaging_series_id'], false, 'btree'],
  ['radiation_dose_events', 'ix_radiation_dose_events_unit_concept_id', ['unit_concept_id'], false, 'btree'],
  ['radiation_dose_events', 'ix_radiation_dose_events_device_id', ['device_id'], false, 'btree'],
  ['radiation_dose_events', 'ix_radiation_dose_patient_time', ['custodian_tenant_id', 'patient_profile_id', 'recorded_at desc'], false, 'btree'],
  ['result_verifications', 'ix_result_verifications_custodian_tenant_id', ['custodian_tenant_id'], false, 'btree'],
  ['result_verifications', 'ix_result_verifications_verifiable_type_concept_id', ['verifiable_type_concept_id'], false, 'btree'],
  ['result_verifications', 'ix_result_verifications_verifiable_id', ['verifiable_id'], false, 'btree'],
  ['result_verifications', 'ix_result_verifications_verification_level_concept_id', ['verification_level_concept_id'], false, 'btree'],
  ['result_verifications', 'ix_result_verifications_result_concept_id', ['result_concept_id'], false, 'btree'],
  ['result_verifications', 'ix_result_verifications_verified_by_profile_id', ['verified_by_profile_id'], false, 'btree'],
  ['result_verifications', 'ix_result_verifications_previous_verification_id', ['previous_verification_id'], false, 'btree'],
  ['result_verifications', 'ix_result_verifications_signature_id', ['signature_id'], false, 'btree'],
  ['result_verifications', 'ix_result_verifications_target', ['verifiable_type_concept_id', 'verifiable_id', 'verified_at desc'], false, 'btree'],
  ['specimen_chain_of_custody_events', 'ix_specimen_chain_of_custody_events_specimen_id', ['specimen_id'], false, 'btree'],
  ['specimen_chain_of_custody_events', 'ix_specimen_chain_of_custody_events_specimen_container_id', ['specimen_container_id'], false, 'btree'],
  ['specimen_chain_of_custody_events', 'ix_specimen_chain_of_custody_events_custody_event_type_cbadcc6c', ['custody_event_type_concept_id'], false, 'btree'],
  ['specimen_chain_of_custody_events', 'ix_specimen_chain_of_custody_events_from_party_type_concept_id', ['from_party_type_concept_id'], false, 'btree'],
  ['specimen_chain_of_custody_events', 'ix_specimen_chain_of_custody_events_from_party_id', ['from_party_id'], false, 'btree'],
  ['specimen_chain_of_custody_events', 'ix_specimen_chain_of_custody_events_to_party_type_concept_id', ['to_party_type_concept_id'], false, 'btree'],
  ['specimen_chain_of_custody_events', 'ix_specimen_chain_of_custody_events_to_party_id', ['to_party_id'], false, 'btree'],
  ['specimen_chain_of_custody_events', 'ix_specimen_chain_of_custody_events_location_id', ['location_id'], false, 'btree'],
  ['specimen_chain_of_custody_events', 'ix_specimen_chain_of_custody_events_signed_by_user_id', ['signed_by_user_id'], false, 'btree'],
  ['specimen_collection_events', 'ix_specimen_collection_events_specimen_id', ['specimen_id'], false, 'btree'],
  ['specimen_collection_events', 'ix_specimen_collection_events_event_type_concept_id', ['event_type_concept_id'], false, 'btree'],
  ['specimen_collection_events', 'ix_specimen_collection_events_collector_profile_id', ['collector_profile_id'], false, 'btree'],
  ['specimen_collection_events', 'ix_specimen_collection_events_collection_site_id', ['collection_site_id'], false, 'btree'],
  ['specimen_collection_events', 'ix_specimen_collection_events_body_site_concept_id', ['body_site_concept_id'], false, 'btree'],
  ['specimen_collection_events', 'ix_specimen_collection_events_method_concept_id', ['method_concept_id'], false, 'btree'],
  ['specimen_collection_events', 'ix_specimen_collection_events_fasting_status_concept_id', ['fasting_status_concept_id'], false, 'btree'],
  ['specimen_container_events', 'ix_specimen_container_events_specimen_container_id', ['specimen_container_id'], false, 'btree'],
  ['specimen_container_events', 'ix_specimen_container_events_event_type_concept_id', ['event_type_concept_id'], false, 'btree'],
  ['specimen_container_events', 'ix_specimen_container_events_source_location_id', ['source_location_id'], false, 'btree'],
  ['specimen_container_events', 'ix_specimen_container_events_destination_location_id', ['destination_location_id'], false, 'btree'],
  ['specimen_container_events', 'ix_specimen_container_events_actor_profile_id', ['actor_profile_id'], false, 'btree'],
  ['specimen_containers', 'ix_specimen_containers_specimen_id', ['specimen_id'], false, 'btree'],
  ['specimen_containers', 'ix_specimen_containers_container_type_concept_id', ['container_type_concept_id'], false, 'btree'],
  ['specimen_containers', 'ix_specimen_containers_additive_concept_id', ['additive_concept_id'], false, 'btree'],
  ['specimen_containers', 'ix_specimen_containers_capacity_unit_concept_id', ['capacity_unit_concept_id'], false, 'btree'],
  ['specimen_containers', 'ix_specimen_containers_specimen_quantity_unit_concept_id', ['specimen_quantity_unit_concept_id'], false, 'btree'],
  ['specimen_containers', 'ix_specimen_containers_parent_container_id', ['parent_container_id'], false, 'btree'],
  ['specimen_containers', 'ix_specimen_containers_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['specimen_containers', 'ix_specimen_containers_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['specimen_containers', 'ix_specimen_containers_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['specimen_containers', 'uk_specimen_containers_specimen_identifier', ['specimen_id', 'container_identifier'], true, 'btree'],
  ['specimen_identifiers', 'ix_specimen_identifiers_specimen_id', ['specimen_id'], false, 'btree'],
  ['specimen_identifiers', 'ix_specimen_identifiers_identifier_type_concept_id', ['identifier_type_concept_id'], false, 'btree'],
  ['specimen_identifiers', 'ix_specimen_identifiers_assigning_organization_id', ['assigning_organization_id'], false, 'btree'],
  ['specimen_identifiers', 'ix_specimen_identifiers_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['specimen_identifiers', 'ix_specimen_identifiers_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['specimen_identifiers', 'uk_specimen_identifiers_system_value', ['identifier_system', 'identifier_value'], true, 'btree'],
  ['specimen_parent_links', 'ix_specimen_parent_links_child_specimen_id', ['child_specimen_id'], false, 'btree'],
  ['specimen_parent_links', 'ix_specimen_parent_links_parent_specimen_id', ['parent_specimen_id'], false, 'btree'],
  ['specimen_parent_links', 'ix_specimen_parent_links_relationship_type_concept_id', ['relationship_type_concept_id'], false, 'btree'],
  ['specimen_parent_links', 'ix_specimen_parent_links_quantity_unit_concept_id', ['quantity_unit_concept_id'], false, 'btree'],
  ['specimen_parent_links', 'uk_specimen_parent_links_pair_type', ['child_specimen_id', 'parent_specimen_id', 'relationship_type_concept_id'], true, 'btree'],
  ['specimen_processing_steps', 'ix_specimen_processing_steps_specimen_id', ['specimen_id'], false, 'btree'],
  ['specimen_processing_steps', 'ix_specimen_processing_steps_procedure_concept_id', ['procedure_concept_id'], false, 'btree'],
  ['specimen_processing_steps', 'ix_specimen_processing_steps_additive_concept_id', ['additive_concept_id'], false, 'btree'],
  ['specimen_processing_steps', 'ix_specimen_processing_steps_performer_profile_id', ['performer_profile_id'], false, 'btree'],
  ['specimen_processing_steps', 'ix_specimen_processing_steps_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['specimen_rejection_events', 'ix_specimen_rejection_events_specimen_id', ['specimen_id'], false, 'btree'],
  ['specimen_rejection_events', 'ix_specimen_rejection_events_rejection_reason_concept_id', ['rejection_reason_concept_id'], false, 'btree'],
  ['specimen_rejection_events', 'ix_specimen_rejection_events_rejected_by_profile_id', ['rejected_by_profile_id'], false, 'btree'],
  ['specimen_rejection_events', 'ix_specimen_rejection_events_recollection_service_request_id', ['recollection_service_request_id'], false, 'btree'],
  ['specimens', 'ix_specimens_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['specimens', 'ix_specimens_service_request_id', ['service_request_id'], false, 'btree'],
  ['specimens', 'ix_specimens_encounter_id', ['encounter_id'], false, 'btree'],
  ['specimens', 'ix_specimens_specimen_type_concept_id', ['specimen_type_concept_id'], false, 'btree'],
  ['specimens', 'ix_specimens_body_site_concept_id', ['body_site_concept_id'], false, 'btree'],
  ['specimens', 'ix_specimens_collection_method_concept_id', ['collection_method_concept_id'], false, 'btree'],
  ['specimens', 'ix_specimens_collector_profile_id', ['collector_profile_id'], false, 'btree'],
  ['specimens', 'ix_specimens_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['specimens', 'ix_specimens_container_type_concept_id', ['container_type_concept_id'], false, 'btree'],
  ['specimens', 'ix_specimens_quantity_unit_concept_id', ['quantity_unit_concept_id'], false, 'btree'],
  ['specimens', 'ix_specimens_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['specimens', 'ix_specimens_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['specimens', 'ix_specimens_patient_profile_id_updated_at', ['patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['specimens', 'ix_specimens_custodian_tenant_id', ['custodian_tenant_id'], false, 'btree'],
];
