import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `directory`.
 * 49 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const directoryIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['branch_memberships', 'ix_branch_memberships_tenant_membership_id', ['tenant_membership_id'], false, 'btree'],
  ['branch_memberships', 'ix_branch_memberships_branch_id', ['branch_id'], false, 'btree'],
  ['branch_memberships', 'ix_branch_memberships_local_role_concept_id', ['local_role_concept_id'], false, 'btree'],
  ['branch_memberships', 'ix_branch_memberships_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['branch_memberships', 'ix_branch_memberships_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['branch_memberships', 'ix_branch_memberships_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['branches', 'ix_branches_tenant_id', ['tenant_id'], false, 'btree'],
  ['branches', 'ix_branches_branch_type_concept_id', ['branch_type_concept_id'], false, 'btree'],
  ['branches', 'ix_branches_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['branches', 'ix_branches_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['branches', 'ix_branches_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['branches', 'ix_branches_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['tenant_affiliation_documents', 'ix_tenant_affiliation_documents_tenant_id', ['tenant_id'], false, 'btree'],
  ['tenant_affiliation_documents', 'ix_tenant_affiliation_documents_document_type_concept_id', ['document_type_concept_id'], false, 'btree'],
  ['tenant_affiliation_documents', 'ix_tenant_affiliation_documents_issuing_authority_concept_id', ['issuing_authority_concept_id'], false, 'btree'],
  ['tenant_affiliation_documents', 'ix_tenant_affiliation_documents_verification_status_concept_id', ['verification_status_concept_id'], false, 'btree'],
  ['tenant_affiliation_documents', 'ix_tenant_affiliation_documents_file_id', ['file_id'], false, 'btree'],
  ['tenant_affiliation_documents', 'ix_tenant_affiliation_documents_identifier_id', ['identifier_id'], false, 'btree'],
  ['tenant_affiliation_documents', 'ix_tenant_affiliation_documents_valid_to', ['valid_to'], false, 'btree'],
  ['tenant_affiliation_documents', 'uk_tenant_affiliation_documents_tenant_type_file', ['tenant_id', 'document_type_concept_id', 'file_id'], true, 'btree'],
  ['tenant_legal_representatives', 'ix_tenant_legal_representatives_tenant_id', ['tenant_id'], false, 'btree'],
  ['tenant_legal_representatives', 'ix_tenant_legal_representatives_person_id', ['person_id'], false, 'btree'],
  ['tenant_legal_representatives', 'ix_tenant_legal_representatives_role_concept_id', ['representative_role_concept_id'], false, 'btree'],
  ['tenant_legal_representatives', 'uk_tenant_legal_representatives_primary', ['tenant_id', 'is_primary'], true, 'btree'],
  ['tenant_memberships', 'ix_tenant_memberships_user_id', ['user_id'], false, 'btree'],
  ['tenant_memberships', 'ix_tenant_memberships_tenant_id', ['tenant_id'], false, 'btree'],
  ['tenant_memberships', 'ix_tenant_memberships_primary_branch_id', ['primary_branch_id'], false, 'btree'],
  ['tenant_memberships', 'ix_tenant_memberships_tenant_role_concept_id', ['tenant_role_concept_id'], false, 'btree'],
  ['tenant_memberships', 'ix_tenant_memberships_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['tenant_memberships', 'ix_tenant_memberships_access_scope_concept_id', ['access_scope_concept_id'], false, 'btree'],
  ['tenant_memberships', 'ix_tenant_memberships_invited_by_user_id', ['invited_by_user_id'], false, 'btree'],
  ['tenant_memberships', 'ix_tenant_memberships_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['tenant_memberships', 'ix_tenant_memberships_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['tenant_memberships', 'ix_tenant_memberships_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['tenant_web_configs', 'uk_tenant_web_configs_domain', ['domain'], true, 'btree'],
  ['tenant_web_configs', 'ix_tenant_web_configs_tenant_id', ['tenant_id'], false, 'btree'],
  ['tenant_web_configs', 'ix_tenant_web_configs_primary_language_concept_id', ['primary_language_concept_id'], false, 'btree'],
  ['tenants', 'uq_tenants_code', ['code'], true, 'btree'],
  ['tenants', 'ix_tenants_tenant_type_concept_id', ['tenant_type_concept_id'], false, 'btree'],
  ['tenants', 'ix_tenants_legal_entity_type_concept_id', ['legal_entity_type_concept_id'], false, 'btree'],
  ['tenants', 'ix_tenants_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['tenants', 'ix_tenants_verification_status_concept_id', ['verification_status_concept_id'], false, 'btree'],
  ['tenants', 'ix_tenants_country_concept_id', ['country_concept_id'], false, 'btree'],
  ['tenants', 'ix_tenants_jurisdiction_concept_id', ['jurisdiction_concept_id'], false, 'btree'],
  ['tenants', 'ix_tenants_data_residency_region_concept_id', ['data_residency_region_concept_id'], false, 'btree'],
  ['tenants', 'ix_tenants_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['tenants', 'ix_tenants_parent_tenant_id', ['parent_tenant_id'], false, 'btree'],
  ['tenants', 'ix_tenants_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['tenants', 'ix_tenants_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
];
