import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `education`.
 * 96 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const educationIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['assessments', 'ix_assessments_course_id', ['course_id'], false, 'btree'],
  ['assessments', 'ix_assessments_course_module_id', ['course_module_id'], false, 'btree'],
  ['assessments', 'ix_assessments_assessment_type_concept_id', ['assessment_type_concept_id'], false, 'btree'],
  ['assessments', 'ix_assessments_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['assessments', 'ix_assessments_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['assessments', 'ix_assessments_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['assessment_attempts', 'ix_assessment_attempts_assessment_id', ['assessment_id'], false, 'btree'],
  ['assessment_attempts', 'ix_assessment_attempts_enrollment_id', ['enrollment_id'], false, 'btree'],
  ['assessment_attempts', 'ix_assessment_attempts_graded_by_user_id', ['graded_by_user_id'], false, 'btree'],
  ['assessment_attempts', 'ix_assessment_attempts_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['assessment_attempts', 'ix_assessment_attempts_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['assessment_attempts', 'ix_assessment_attempts_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['assessment_attempts', 'uq_assessment_attempts_assessment_id_attempt_number', ['assessment_id', 'attempt_number'], true, 'btree'],
  ['assessment_questions', 'ix_assessment_questions_assessment_id', ['assessment_id'], false, 'btree'],
  ['assessment_questions', 'ix_assessment_questions_question_type_concept_id', ['question_type_concept_id'], false, 'btree'],
  ['assessment_questions', 'ix_assessment_questions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['assessment_questions', 'ix_assessment_questions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['certificates', 'uq_certificates_certificate_number', ['certificate_number'], true, 'btree'],
  ['certificates', 'uq_certificates_verification_code', ['verification_code'], true, 'btree'],
  ['certificates', 'ix_certificates_enrollment_id', ['enrollment_id'], false, 'btree'],
  ['certificates', 'ix_certificates_course_id', ['course_id'], false, 'btree'],
  ['certificates', 'ix_certificates_file_id', ['file_id'], false, 'btree'],
  ['certificates', 'ix_certificates_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['certificates', 'ix_certificates_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['certificates', 'ix_certificates_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['cme_credit_records', 'ix_cme_credit_records_practitioner_profile_id', ['practitioner_profile_id'], false, 'btree'],
  ['cme_credit_records', 'ix_cme_credit_records_certificate_id', ['certificate_id'], false, 'btree'],
  ['cme_credit_records', 'ix_cme_credit_records_accrediting_body_concept_id', ['accrediting_body_concept_id'], false, 'btree'],
  ['cme_credit_records', 'ix_cme_credit_records_specialty_concept_id', ['specialty_concept_id'], false, 'btree'],
  ['cme_credit_records', 'ix_cme_credit_records_jurisdiction_concept_id', ['jurisdiction_concept_id'], false, 'btree'],
  ['cme_credit_records', 'ix_cme_credit_records_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['cme_credit_records', 'ix_cme_credit_records_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['cme_credit_records', 'ix_cme_credit_records_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['courses', 'uq_courses_code', ['code'], true, 'btree'],
  ['courses', 'ix_courses_tenant_id', ['tenant_id'], false, 'btree'],
  ['courses', 'ix_courses_course_type_concept_id', ['course_type_concept_id'], false, 'btree'],
  ['courses', 'ix_courses_specialty_concept_id', ['specialty_concept_id'], false, 'btree'],
  ['courses', 'ix_courses_level_concept_id', ['level_concept_id'], false, 'btree'],
  ['courses', 'ix_courses_language_concept_id', ['language_concept_id'], false, 'btree'],
  ['courses', 'ix_courses_cover_file_id', ['cover_file_id'], false, 'btree'],
  ['courses', 'ix_courses_accrediting_body_concept_id', ['accrediting_body_concept_id'], false, 'btree'],
  ['courses', 'ix_courses_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['courses', 'ix_courses_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['courses', 'ix_courses_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['courses', 'ix_courses_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['courses', 'ix_courses_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['course_cohorts', 'ix_course_cohorts_course_id', ['course_id'], false, 'btree'],
  ['course_cohorts', 'ix_course_cohorts_delivery_mode_concept_id', ['delivery_mode_concept_id'], false, 'btree'],
  ['course_cohorts', 'ix_course_cohorts_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['course_cohorts', 'ix_course_cohorts_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['course_cohorts', 'ix_course_cohorts_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['course_instructors', 'ix_course_instructors_course_id', ['course_id'], false, 'btree'],
  ['course_instructors', 'ix_course_instructors_instructor_id', ['instructor_id'], false, 'btree'],
  ['course_instructors', 'ix_course_instructors_role_concept_id', ['role_concept_id'], false, 'btree'],
  ['course_instructors', 'ix_course_instructors_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['course_instructors', 'ix_course_instructors_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['course_modules', 'ix_course_modules_course_id', ['course_id'], false, 'btree'],
  ['course_modules', 'ix_course_modules_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['course_modules', 'ix_course_modules_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['course_modules', 'ix_course_modules_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['course_reviews', 'ix_course_reviews_course_id', ['course_id'], false, 'btree'],
  ['course_reviews', 'ix_course_reviews_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['course_reviews', 'ix_course_reviews_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['course_reviews', 'ix_course_reviews_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['course_versions', 'ix_course_versions_course_id', ['course_id'], false, 'btree'],
  ['course_versions', 'ix_course_versions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['course_versions', 'ix_course_versions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['course_versions', 'ix_course_versions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['course_versions', 'uq_course_versions_course_id_version', ['course_id', 'version'], true, 'btree'],
  ['enrollments', 'ix_enrollments_course_id', ['course_id'], false, 'btree'],
  ['enrollments', 'ix_enrollments_cohort_id', ['cohort_id'], false, 'btree'],
  ['enrollments', 'ix_enrollments_learner_type_concept_id', ['learner_type_concept_id'], false, 'btree'],
  ['enrollments', 'ix_enrollments_enrollment_source_concept_id', ['enrollment_source_concept_id'], false, 'btree'],
  ['enrollments', 'ix_enrollments_payment_intent_id', ['payment_intent_id'], false, 'btree'],
  ['enrollments', 'ix_enrollments_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['enrollments', 'ix_enrollments_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['enrollments', 'ix_enrollments_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['instructors', 'ix_instructors_tenant_id', ['tenant_id'], false, 'btree'],
  ['instructors', 'ix_instructors_practitioner_profile_id', ['practitioner_profile_id'], false, 'btree'],
  ['instructors', 'ix_instructors_user_id', ['user_id'], false, 'btree'],
  ['instructors', 'ix_instructors_photo_file_id', ['photo_file_id'], false, 'btree'],
  ['instructors', 'ix_instructors_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['instructors', 'ix_instructors_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['instructors', 'ix_instructors_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['instructors', 'ix_instructors_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['lessons', 'ix_lessons_course_module_id', ['course_module_id'], false, 'btree'],
  ['lessons', 'ix_lessons_content_type_concept_id', ['content_type_concept_id'], false, 'btree'],
  ['lessons', 'ix_lessons_media_file_id', ['media_file_id'], false, 'btree'],
  ['lessons', 'ix_lessons_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['lessons', 'ix_lessons_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['lessons', 'ix_lessons_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['lesson_progress', 'ix_lesson_progress_enrollment_id', ['enrollment_id'], false, 'btree'],
  ['lesson_progress', 'ix_lesson_progress_lesson_id', ['lesson_id'], false, 'btree'],
  ['lesson_progress', 'ix_lesson_progress_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['lesson_progress', 'ix_lesson_progress_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['lesson_progress', 'brin_lesson_progress_recorded_at', ['recorded_at'], false, 'brin'],
];
