import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `erp` (parte 2/3).
 * 180 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const erpIndexes2: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['contract_team_members', 'ix_contract_team_members_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['contract_terminations', 'ix_contract_terminations_contract_id', ['contract_id'], false, 'btree'],
  ['contract_terminations', 'ix_contract_terminations_termination_type_concept_id', ['termination_type_concept_id'], false, 'btree'],
  ['contract_terminations', 'ix_contract_terminations_initiated_by_user_id', ['initiated_by_user_id'], false, 'btree'],
  ['contract_terminations', 'ix_contract_terminations_approved_by_user_id', ['approved_by_user_id'], false, 'btree'],
  ['contract_terminations', 'ix_contract_terminations_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['contract_terminations', 'ix_contract_terminations_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['contract_terminations', 'ix_contract_terminations_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['contract_terminations', 'ix_contract_terminations_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['contract_terminations', 'ix_contract_terminations_contract_status', ['contract_id', 'status_concept_id'], false, 'btree'],
  ['contract_versions', 'uq_contract_versions_contract_id_version_number', ['contract_id', 'version_number'], true, 'btree'],
  ['contract_versions', 'ix_contract_versions_contract_id', ['contract_id'], false, 'btree'],
  ['contract_versions', 'ix_contract_versions_version_type_concept_id', ['version_type_concept_id'], false, 'btree'],
  ['contract_versions', 'ix_contract_versions_main_document_file_id', ['main_document_file_id'], false, 'btree'],
  ['contract_versions', 'ix_contract_versions_approved_by_user_id', ['approved_by_user_id'], false, 'btree'],
  ['contract_versions', 'ix_contract_versions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['contract_versions', 'ix_contract_versions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['contracts', 'uq_contracts_contract_number', ['contract_number'], true, 'btree'],
  ['contracts', 'ix_contracts_tenant_id', ['tenant_id'], false, 'btree'],
  ['contracts', 'ix_contracts_contract_type_concept_id', ['contract_type_concept_id'], false, 'btree'],
  ['contracts', 'ix_contracts_counterparty_type_concept_id', ['counterparty_type_concept_id'], false, 'btree'],
  ['contracts', 'ix_contracts_renewal_type_concept_id', ['renewal_type_concept_id'], false, 'btree'],
  ['contracts', 'ix_contracts_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['contracts', 'ix_contracts_governing_jurisdiction_concept_id', ['governing_jurisdiction_concept_id'], false, 'btree'],
  ['contracts', 'ix_contracts_owner_user_id', ['owner_user_id'], false, 'btree'],
  ['contracts', 'ix_contracts_primary_business_partner_id', ['primary_business_partner_id'], false, 'btree'],
  ['contracts', 'ix_contracts_current_version_id', ['current_version_id'], false, 'btree'],
  ['contracts', 'ix_contracts_parent_contract_id', ['parent_contract_id'], false, 'btree'],
  ['contracts', 'ix_contracts_master_agreement_id', ['master_agreement_id'], false, 'btree'],
  ['contracts', 'ix_contracts_owning_department_id', ['owning_department_id'], false, 'btree'],
  ['contracts', 'ix_contracts_owning_cost_center_id', ['owning_cost_center_id'], false, 'btree'],
  ['contracts', 'ix_contracts_owning_profit_center_id', ['owning_profit_center_id'], false, 'btree'],
  ['contracts', 'ix_contracts_approval_status_concept_id', ['approval_status_concept_id'], false, 'btree'],
  ['contracts', 'ix_contracts_signature_status_concept_id', ['signature_status_concept_id'], false, 'btree'],
  ['contracts', 'ix_contracts_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['contracts', 'ix_contracts_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['contracts', 'ix_contracts_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['contracts', 'ix_contracts_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['departments', 'ix_departments_tenant_id', ['tenant_id'], false, 'btree'],
  ['departments', 'ix_departments_parent_department_id', ['parent_department_id'], false, 'btree'],
  ['departments', 'ix_departments_manager_employee_id', ['manager_employee_id'], false, 'btree'],
  ['departments', 'ix_departments_cost_center_id', ['cost_center_id'], false, 'btree'],
  ['departments', 'ix_departments_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['departments', 'ix_departments_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['departments', 'ix_departments_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['departments', 'ix_departments_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['employee_assignments', 'ix_employee_assignments_employment_record_id', ['employment_record_id'], false, 'btree'],
  ['employee_assignments', 'ix_employee_assignments_assignment_type_concept_id', ['assignment_type_concept_id'], false, 'btree'],
  ['employee_assignments', 'ix_employee_assignments_practice_id', ['practice_id'], false, 'btree'],
  ['employee_assignments', 'ix_employee_assignments_branch_id', ['branch_id'], false, 'btree'],
  ['employee_assignments', 'ix_employee_assignments_department_id', ['department_id'], false, 'btree'],
  ['employee_assignments', 'ix_employee_assignments_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['employee_assignments', 'ix_employee_assignments_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['employee_assignments', 'ix_employee_assignments_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['employees', 'ix_employees_practice_id', ['practice_id'], false, 'btree'],
  ['employees', 'ix_employees_person_user_id', ['person_user_id'], false, 'btree'],
  ['employees', 'ix_employees_role_concept_id', ['role_concept_id'], false, 'btree'],
  ['employees', 'ix_employees_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['employees', 'ix_employees_payment_method_concept_id', ['payment_method_concept_id'], false, 'btree'],
  ['employees', 'ix_employees_business_partner_id', ['business_partner_id'], false, 'btree'],
  ['employees', 'ix_employees_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['employees', 'ix_employees_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['employees', 'ix_employees_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['employment_records', 'ix_employment_records_employee_id', ['employee_id'], false, 'btree'],
  ['employment_records', 'ix_employment_records_tenant_id', ['tenant_id'], false, 'btree'],
  ['employment_records', 'ix_employment_records_position_id', ['position_id'], false, 'btree'],
  ['employment_records', 'ix_employment_records_department_id', ['department_id'], false, 'btree'],
  ['employment_records', 'ix_employment_records_employment_type_concept_id', ['employment_type_concept_id'], false, 'btree'],
  ['employment_records', 'ix_employment_records_manager_employee_id', ['manager_employee_id'], false, 'btree'],
  ['employment_records', 'ix_employment_records_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['employment_records', 'ix_employment_records_contract_id', ['contract_id'], false, 'btree'],
  ['employment_records', 'ix_employment_records_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['employment_records', 'ix_employment_records_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['employment_records', 'ix_employment_records_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['employment_records', 'ix_employment_records_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['enterprise_document_flow', 'uq_enterprise_document_flow_predecessor_type_concept_i_24f1d8d4', ['predecessor_type_concept_id', 'predecessor_id', 'successor_type_concept_id', 'successor_id', 'relation_type_concept_id'], true, 'btree'],
  ['enterprise_document_flow', 'ix_enterprise_document_flow_tenant_id', ['tenant_id'], false, 'btree'],
  ['enterprise_document_flow', 'ix_enterprise_document_flow_predecessor_type_concept_id', ['predecessor_type_concept_id'], false, 'btree'],
  ['enterprise_document_flow', 'ix_enterprise_document_flow_successor_type_concept_id', ['successor_type_concept_id'], false, 'btree'],
  ['enterprise_document_flow', 'ix_enterprise_document_flow_relation_type_concept_id', ['relation_type_concept_id'], false, 'btree'],
  ['enterprise_document_flow', 'ix_enterprise_document_flow_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['enterprise_document_flow', 'ix_enterprise_document_flow_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['goods_receipt_items', 'uq_goods_receipt_items_goods_receipt_id_line_number', ['goods_receipt_id', 'line_number'], true, 'btree'],
  ['goods_receipt_items', 'ix_goods_receipt_items_goods_receipt_id', ['goods_receipt_id'], false, 'btree'],
  ['goods_receipt_items', 'ix_goods_receipt_items_purchase_order_item_id', ['purchase_order_item_id'], false, 'btree'],
  ['goods_receipt_items', 'ix_goods_receipt_items_inventory_ledger_entry_id', ['inventory_ledger_entry_id'], false, 'btree'],
  ['goods_receipt_items', 'ix_goods_receipt_items_asset_id', ['asset_id'], false, 'btree'],
  ['goods_receipt_items', 'ix_goods_receipt_items_quality_status_concept_id', ['quality_status_concept_id'], false, 'btree'],
  ['goods_receipt_items', 'ix_goods_receipt_items_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['goods_receipt_items', 'ix_goods_receipt_items_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['goods_receipts', 'uq_goods_receipts_tenant_id_receipt_number', ['tenant_id', 'receipt_number'], true, 'btree'],
  ['goods_receipts', 'ix_goods_receipts_tenant_id', ['tenant_id'], false, 'btree'],
  ['goods_receipts', 'ix_goods_receipts_purchase_order_id', ['purchase_order_id'], false, 'btree'],
  ['goods_receipts', 'ix_goods_receipts_receiving_branch_id', ['receiving_branch_id'], false, 'btree'],
  ['goods_receipts', 'ix_goods_receipts_received_by_employee_id', ['received_by_employee_id'], false, 'btree'],
  ['goods_receipts', 'ix_goods_receipts_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['goods_receipts', 'ix_goods_receipts_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['goods_receipts', 'ix_goods_receipts_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['goods_receipts', 'ix_goods_receipts_tenant_status_updated', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['invoice_match_items', 'uq_invoice_match_items_invoice_match_run_id_bill_line_id', ['invoice_match_run_id', 'bill_line_id'], true, 'btree'],
  ['invoice_match_items', 'ix_invoice_match_items_invoice_match_run_id', ['invoice_match_run_id'], false, 'btree'],
  ['invoice_match_items', 'ix_invoice_match_items_bill_line_id', ['bill_line_id'], false, 'btree'],
  ['invoice_match_items', 'ix_invoice_match_items_purchase_order_item_id', ['purchase_order_item_id'], false, 'btree'],
  ['invoice_match_items', 'ix_invoice_match_items_goods_receipt_item_id', ['goods_receipt_item_id'], false, 'btree'],
  ['invoice_match_items', 'ix_invoice_match_items_service_entry_item_id', ['service_entry_item_id'], false, 'btree'],
  ['invoice_match_items', 'ix_invoice_match_items_tolerance_rule_concept_id', ['tolerance_rule_concept_id'], false, 'btree'],
  ['invoice_match_items', 'ix_invoice_match_items_result_concept_id', ['result_concept_id'], false, 'btree'],
  ['invoice_match_items', 'ix_invoice_match_items_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['invoice_match_runs', 'ix_invoice_match_runs_tenant_id', ['tenant_id'], false, 'btree'],
  ['invoice_match_runs', 'ix_invoice_match_runs_bill_id', ['bill_id'], false, 'btree'],
  ['invoice_match_runs', 'ix_invoice_match_runs_match_type_concept_id', ['match_type_concept_id'], false, 'btree'],
  ['invoice_match_runs', 'ix_invoice_match_runs_purchase_order_id', ['purchase_order_id'], false, 'btree'],
  ['invoice_match_runs', 'ix_invoice_match_runs_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['invoice_match_runs', 'ix_invoice_match_runs_result_concept_id', ['result_concept_id'], false, 'btree'],
  ['invoice_match_runs', 'ix_invoice_match_runs_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['invoice_match_runs', 'ix_invoice_match_runs_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['invoice_match_runs', 'ix_invoice_match_runs_tenant_status_run', ['tenant_id', 'status_concept_id', 'run_at desc'], false, 'btree'],
  ['lease_accounting_links', 'ix_lease_accounting_links_lease_contract_id', ['lease_contract_id'], false, 'btree'],
  ['lease_accounting_links', 'ix_lease_accounting_links_lease_object_id', ['lease_object_id'], false, 'btree'],
  ['lease_accounting_links', 'ix_lease_accounting_links_right_of_use_asset_id', ['right_of_use_asset_id'], false, 'btree'],
  ['lease_accounting_links', 'ix_lease_accounting_links_lease_liability_id', ['lease_liability_id'], false, 'btree'],
  ['lease_accounting_links', 'ix_lease_accounting_links_right_of_use_asset_account_id', ['right_of_use_asset_account_id'], false, 'btree'],
  ['lease_accounting_links', 'ix_lease_accounting_links_lease_liability_account_id', ['lease_liability_account_id'], false, 'btree'],
  ['lease_accounting_links', 'ix_lease_accounting_links_interest_expense_account_id', ['interest_expense_account_id'], false, 'btree'],
  ['lease_accounting_links', 'ix_lease_accounting_links_depreciation_expense_account_id', ['depreciation_expense_account_id'], false, 'btree'],
  ['lease_accounting_links', 'ix_lease_accounting_links_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['lease_accounting_links', 'ix_lease_accounting_links_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['lease_accounting_links', 'ix_lease_accounting_links_lease_valid_from', ['lease_contract_id', 'valid_from desc'], false, 'btree'],
  ['lease_cash_flows', 'ix_lease_cash_flows_lease_contract_id', ['lease_contract_id'], false, 'btree'],
  ['lease_cash_flows', 'ix_lease_cash_flows_lease_object_id', ['lease_object_id'], false, 'btree'],
  ['lease_cash_flows', 'ix_lease_cash_flows_flow_type_concept_id', ['flow_type_concept_id'], false, 'btree'],
  ['lease_cash_flows', 'ix_lease_cash_flows_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['lease_cash_flows', 'ix_lease_cash_flows_index_reference_concept_id', ['index_reference_concept_id'], false, 'btree'],
  ['lease_cash_flows', 'ix_lease_cash_flows_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['lease_cash_flows', 'ix_lease_cash_flows_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['lease_cash_flows', 'ix_lease_cash_flows_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['lease_cash_flows', 'ix_lease_cash_flows_lease_status_due', ['lease_contract_id', 'status_concept_id', 'due_date'], false, 'btree'],
  ['lease_contracts', 'uq_lease_contracts_contract_id', ['contract_id'], true, 'btree'],
  ['lease_contracts', 'ix_lease_contracts_contract_id', ['contract_id'], false, 'btree'],
  ['lease_contracts', 'ix_lease_contracts_lease_role_concept_id', ['lease_role_concept_id'], false, 'btree'],
  ['lease_contracts', 'ix_lease_contracts_accounting_principle_concept_id', ['accounting_principle_concept_id'], false, 'btree'],
  ['lease_contracts', 'ix_lease_contracts_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['lease_contracts', 'ix_lease_contracts_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['lease_contracts', 'ix_lease_contracts_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['lease_contracts', 'ix_lease_contracts_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['lease_objects', 'ix_lease_objects_lease_contract_id', ['lease_contract_id'], false, 'btree'],
  ['lease_objects', 'ix_lease_objects_object_type_concept_id', ['object_type_concept_id'], false, 'btree'],
  ['lease_objects', 'ix_lease_objects_source_asset_id', ['source_asset_id'], false, 'btree'],
  ['lease_objects', 'ix_lease_objects_branch_id', ['branch_id'], false, 'btree'],
  ['lease_objects', 'ix_lease_objects_unit_concept_id', ['unit_concept_id'], false, 'btree'],
  ['lease_objects', 'ix_lease_objects_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['lease_objects', 'ix_lease_objects_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['lease_objects', 'ix_lease_objects_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['lease_valuations', 'uq_lease_valuations_lease_contract_id_valuation_date_accountin', ['lease_contract_id', 'valuation_date', 'accounting_principle_concept_id'], true, 'btree'],
  ['lease_valuations', 'ix_lease_valuations_lease_contract_id', ['lease_contract_id'], false, 'btree'],
  ['lease_valuations', 'ix_lease_valuations_accounting_principle_concept_id', ['accounting_principle_concept_id'], false, 'btree'],
  ['lease_valuations', 'ix_lease_valuations_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['lease_valuations', 'ix_lease_valuations_journal_transaction_id', ['journal_transaction_id'], false, 'btree'],
  ['lease_valuations', 'ix_lease_valuations_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['lease_valuations', 'ix_lease_valuations_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['performance_reviews', 'ix_performance_reviews_employee_id', ['employee_id'], false, 'btree'],
  ['performance_reviews', 'ix_performance_reviews_reviewer_employee_id', ['reviewer_employee_id'], false, 'btree'],
  ['performance_reviews', 'ix_performance_reviews_rating_concept_id', ['rating_concept_id'], false, 'btree'],
  ['performance_reviews', 'ix_performance_reviews_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['performance_reviews', 'ix_performance_reviews_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['performance_reviews', 'ix_performance_reviews_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['positions', 'ix_positions_tenant_id', ['tenant_id'], false, 'btree'],
  ['positions', 'ix_positions_department_id', ['department_id'], false, 'btree'],
  ['positions', 'ix_positions_job_family_concept_id', ['job_family_concept_id'], false, 'btree'],
  ['positions', 'ix_positions_grade_concept_id', ['grade_concept_id'], false, 'btree'],
  ['positions', 'ix_positions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['positions', 'ix_positions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['positions', 'ix_positions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['positions', 'ix_positions_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['projects', 'uq_projects_tenant_id_project_number', ['tenant_id', 'project_number'], true, 'btree'],
  ['projects', 'ix_projects_tenant_id', ['tenant_id'], false, 'btree'],
  ['projects', 'ix_projects_project_type_concept_id', ['project_type_concept_id'], false, 'btree'],
  ['projects', 'ix_projects_responsible_employee_id', ['responsible_employee_id'], false, 'btree'],
  ['projects', 'ix_projects_department_id', ['department_id'], false, 'btree'],
  ['projects', 'ix_projects_cost_center_id', ['cost_center_id'], false, 'btree'],
];
