import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `erp` (parte 1/3).
 * 180 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const erpIndexes1: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['business_partners', 'uq_business_partners_tenant_id_partner_number', ['tenant_id', 'partner_number'], true, 'btree'],
  ['business_partners', 'ix_business_partners_tenant_id', ['tenant_id'], false, 'btree'],
  ['business_partners', 'ix_business_partners_partner_category_concept_id', ['partner_category_concept_id'], false, 'btree'],
  ['business_partners', 'ix_business_partners_country_concept_id', ['country_concept_id'], false, 'btree'],
  ['business_partners', 'ix_business_partners_linked_tenant_id', ['linked_tenant_id'], false, 'btree'],
  ['business_partners', 'ix_business_partners_linked_person_id', ['linked_person_id'], false, 'btree'],
  ['business_partners', 'ix_business_partners_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['business_partners', 'ix_business_partners_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['business_partners', 'ix_business_partners_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['business_partners', 'ix_business_partners_tenant_status_updated', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['business_partner_bank_accounts', 'uq_business_partner_bank_accounts_business_partner_id__0b2a44a3', ['business_partner_id', 'account_number_hash'], true, 'btree'],
  ['business_partner_bank_accounts', 'ix_business_partner_bank_accounts_business_partner_id', ['business_partner_id'], false, 'btree'],
  ['business_partner_bank_accounts', 'ix_business_partner_bank_accounts_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['business_partner_bank_accounts', 'ix_business_partner_bank_accounts_verification_status__14f1d2aa', ['verification_status_concept_id'], false, 'btree'],
  ['business_partner_bank_accounts', 'ix_business_partner_bank_accounts_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['business_partner_bank_accounts', 'ix_business_partner_bank_accounts_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['business_partner_bank_accounts', 'ix_business_partner_bank_accounts_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['business_partner_relationships', 'ix_business_partner_relationships_source_business_partner_id', ['source_business_partner_id'], false, 'btree'],
  ['business_partner_relationships', 'ix_business_partner_relationships_target_business_partner_id', ['target_business_partner_id'], false, 'btree'],
  ['business_partner_relationships', 'ix_business_partner_relationships_relationship_type_concept_id', ['relationship_type_concept_id'], false, 'btree'],
  ['business_partner_relationships', 'ix_business_partner_relationships_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['business_partner_relationships', 'ix_business_partner_relationships_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['business_partner_relationships', 'ix_business_partner_relationships_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['business_partner_relationships', 'ix_business_partner_relationships_source_type_valid', ['source_business_partner_id', 'relationship_type_concept_id', 'valid_from'], false, 'btree'],
  ['business_partner_roles', 'uq_business_partner_roles_business_partner_id_role_con_4a8deccf', ['business_partner_id', 'role_concept_id', 'company_code_tenant_id', 'valid_from'], true, 'btree'],
  ['business_partner_roles', 'ix_business_partner_roles_business_partner_id', ['business_partner_id'], false, 'btree'],
  ['business_partner_roles', 'ix_business_partner_roles_role_concept_id', ['role_concept_id'], false, 'btree'],
  ['business_partner_roles', 'ix_business_partner_roles_company_code_tenant_id', ['company_code_tenant_id'], false, 'btree'],
  ['business_partner_roles', 'ix_business_partner_roles_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['business_partner_roles', 'ix_business_partner_roles_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['business_partner_roles', 'ix_business_partner_roles_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['business_partner_tax_registrations', 'uq_business_partner_tax_registrations_business_partner_91eeddc3', ['business_partner_id', 'tax_type_concept_id', 'tax_number'], true, 'btree'],
  ['business_partner_tax_registrations', 'ix_business_partner_tax_registrations_business_partner_id', ['business_partner_id'], false, 'btree'],
  ['business_partner_tax_registrations', 'ix_business_partner_tax_registrations_tax_type_concept_id', ['tax_type_concept_id'], false, 'btree'],
  ['business_partner_tax_registrations', 'ix_business_partner_tax_registrations_country_concept_id', ['country_concept_id'], false, 'btree'],
  ['business_partner_tax_registrations', 'ix_business_partner_tax_registrations_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['business_partner_tax_registrations', 'ix_business_partner_tax_registrations_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['contracts', 'uq_contracts_contract_number', ['contract_number'], true, 'btree'],
  ['contracts', 'ix_contracts_tenant_id', ['tenant_id'], false, 'btree'],
  ['contracts', 'ix_contracts_contract_type_concept_id', ['contract_type_concept_id'], false, 'btree'],
  ['contracts', 'ix_contracts_counterparty_type_concept_id', ['counterparty_type_concept_id'], false, 'btree'],
  ['contracts', 'ix_contracts_renewal_type_concept_id', ['renewal_type_concept_id'], false, 'btree'],
  ['contracts', 'ix_contracts_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['contracts', 'ix_contracts_governing_jurisdiction_concept_id', ['governing_jurisdiction_concept_id'], false, 'btree'],
  ['contracts', 'ix_contracts_owner_user_id', ['owner_user_id'], false, 'btree'],
  ['contracts', 'ix_contracts_primary_business_partner_id', ['primary_business_partner_id'], false, 'btree'],
  ['contracts', 'ix_contracts_current_version_id', ['current_version_id'], false, 'btree'],
  ['contracts', 'ix_contracts_parent_contract_id', ['parent_contract_id'], false, 'btree'],
  ['contracts', 'ix_contracts_master_agreement_id', ['master_agreement_id'], false, 'btree'],
  ['contracts', 'ix_contracts_owning_department_id', ['owning_department_id'], false, 'btree'],
  ['contracts', 'ix_contracts_owning_cost_center_id', ['owning_cost_center_id'], false, 'btree'],
  ['contracts', 'ix_contracts_owning_profit_center_id', ['owning_profit_center_id'], false, 'btree'],
  ['contracts', 'ix_contracts_approval_status_concept_id', ['approval_status_concept_id'], false, 'btree'],
  ['contracts', 'ix_contracts_signature_status_concept_id', ['signature_status_concept_id'], false, 'btree'],
  ['contracts', 'ix_contracts_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['contracts', 'ix_contracts_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['contracts', 'ix_contracts_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['contracts', 'ix_contracts_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['contract_accounting_terms', 'ix_contract_accounting_terms_contract_id', ['contract_id'], false, 'btree'],
  ['contract_accounting_terms', 'ix_contract_accounting_terms_contract_line_item_id', ['contract_line_item_id'], false, 'btree'],
  ['contract_accounting_terms', 'ix_contract_accounting_terms_accounting_treatment_concept_id', ['accounting_treatment_concept_id'], false, 'btree'],
  ['contract_accounting_terms', 'ix_contract_accounting_terms_expense_account_id', ['expense_account_id'], false, 'btree'],
  ['contract_accounting_terms', 'ix_contract_accounting_terms_revenue_account_id', ['revenue_account_id'], false, 'btree'],
  ['contract_accounting_terms', 'ix_contract_accounting_terms_accrual_account_id', ['accrual_account_id'], false, 'btree'],
  ['contract_accounting_terms', 'ix_contract_accounting_terms_asset_account_id', ['asset_account_id'], false, 'btree'],
  ['contract_accounting_terms', 'ix_contract_accounting_terms_liability_account_id', ['liability_account_id'], false, 'btree'],
  ['contract_accounting_terms', 'ix_contract_accounting_terms_cost_center_id', ['cost_center_id'], false, 'btree'],
  ['contract_accounting_terms', 'ix_contract_accounting_terms_profit_center_id', ['profit_center_id'], false, 'btree'],
  ['contract_accounting_terms', 'ix_contract_accounting_terms_tax_code_id', ['tax_code_id'], false, 'btree'],
  ['contract_accounting_terms', 'ix_contract_accounting_terms_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['contract_accounting_terms', 'ix_contract_accounting_terms_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['contract_accounting_terms', 'ix_contract_accounting_terms_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['contract_accounting_terms', 'ix_contract_accounting_terms_contract_effective', ['contract_id', 'effective_from desc'], false, 'btree'],
  ['contract_amendments', 'ix_contract_amendments_contract_id', ['contract_id'], false, 'btree'],
  ['contract_amendments', 'ix_contract_amendments_base_version_id', ['base_version_id'], false, 'btree'],
  ['contract_amendments', 'ix_contract_amendments_resulting_version_id', ['resulting_version_id'], false, 'btree'],
  ['contract_amendments', 'ix_contract_amendments_amendment_type_concept_id', ['amendment_type_concept_id'], false, 'btree'],
  ['contract_amendments', 'ix_contract_amendments_requested_by_user_id', ['requested_by_user_id'], false, 'btree'],
  ['contract_amendments', 'ix_contract_amendments_approved_by_user_id', ['approved_by_user_id'], false, 'btree'],
  ['contract_amendments', 'ix_contract_amendments_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['contract_amendments', 'ix_contract_amendments_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['contract_amendments', 'ix_contract_amendments_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['contract_amendments', 'ix_contract_amendments_contract_status_effective', ['contract_id', 'status_concept_id', 'effective_date'], false, 'btree'],
  ['contract_approval_requests', 'ix_contract_approval_requests_contract_id', ['contract_id'], false, 'btree'],
  ['contract_approval_requests', 'ix_contract_approval_requests_contract_version_id', ['contract_version_id'], false, 'btree'],
  ['contract_approval_requests', 'ix_contract_approval_requests_contract_amendment_id', ['contract_amendment_id'], false, 'btree'],
  ['contract_approval_requests', 'ix_contract_approval_requests_approval_type_concept_id', ['approval_type_concept_id'], false, 'btree'],
  ['contract_approval_requests', 'ix_contract_approval_requests_requested_by_user_id', ['requested_by_user_id'], false, 'btree'],
  ['contract_approval_requests', 'ix_contract_approval_requests_workflow_instance_id', ['workflow_instance_id'], false, 'btree'],
  ['contract_approval_requests', 'ix_contract_approval_requests_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['contract_approval_requests', 'ix_contract_approval_requests_contract_status_due', ['contract_id', 'status_concept_id', 'due_at'], false, 'btree'],
  ['contract_approval_steps', 'uq_contract_approval_steps_contract_approval_request_i_754e6454', ['contract_approval_request_id', 'step_number'], true, 'btree'],
  ['contract_approval_steps', 'ix_contract_approval_steps_contract_approval_request_id', ['contract_approval_request_id'], false, 'btree'],
  ['contract_approval_steps', 'ix_contract_approval_steps_approver_user_id', ['approver_user_id'], false, 'btree'],
  ['contract_approval_steps', 'ix_contract_approval_steps_approver_team_role_concept_id', ['approver_team_role_concept_id'], false, 'btree'],
  ['contract_approval_steps', 'ix_contract_approval_steps_decision_concept_id', ['decision_concept_id'], false, 'btree'],
  ['contract_approval_steps', 'ix_contract_approval_steps_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['contract_clauses', 'uq_contract_clauses_tenant_id_clause_code', ['tenant_id', 'clause_code'], true, 'btree'],
  ['contract_clauses', 'ix_contract_clauses_tenant_id', ['tenant_id'], false, 'btree'],
  ['contract_clauses', 'ix_contract_clauses_clause_type_concept_id', ['clause_type_concept_id'], false, 'btree'],
  ['contract_clauses', 'ix_contract_clauses_risk_level_concept_id', ['risk_level_concept_id'], false, 'btree'],
  ['contract_clauses', 'ix_contract_clauses_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['contract_clauses', 'ix_contract_clauses_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['contract_clauses', 'ix_contract_clauses_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['contract_clause_instances', 'uq_contract_clause_instances_contract_version_id_contr_91a0f87f', ['contract_version_id', 'contract_clause_id', 'ordinal'], true, 'btree'],
  ['contract_clause_instances', 'ix_contract_clause_instances_contract_version_id', ['contract_version_id'], false, 'btree'],
  ['contract_clause_instances', 'ix_contract_clause_instances_contract_clause_id', ['contract_clause_id'], false, 'btree'],
  ['contract_clause_instances', 'ix_contract_clause_instances_deviation_type_concept_id', ['deviation_type_concept_id'], false, 'btree'],
  ['contract_clause_instances', 'ix_contract_clause_instances_approved_by_user_id', ['approved_by_user_id'], false, 'btree'],
  ['contract_clause_instances', 'ix_contract_clause_instances_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['contract_clause_instances', 'ix_contract_clause_instances_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['contract_clause_instances', 'ix_contract_clause_instances_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['contract_documents', 'ix_contract_documents_contract_id', ['contract_id'], false, 'btree'],
  ['contract_documents', 'ix_contract_documents_document_type_concept_id', ['document_type_concept_id'], false, 'btree'],
  ['contract_documents', 'ix_contract_documents_file_id', ['file_id'], false, 'btree'],
  ['contract_documents', 'ix_contract_documents_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['contract_documents', 'ix_contract_documents_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['contract_documents', 'uq_contract_documents_contract_id_version', ['contract_id', 'version'], true, 'btree'],
  ['contract_line_items', 'ix_contract_line_items_contract_id', ['contract_id'], false, 'btree'],
  ['contract_line_items', 'ix_contract_line_items_service_concept_id', ['service_concept_id'], false, 'btree'],
  ['contract_line_items', 'ix_contract_line_items_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['contract_line_items', 'ix_contract_line_items_recurrence_concept_id', ['recurrence_concept_id'], false, 'btree'],
  ['contract_line_items', 'ix_contract_line_items_account_id', ['account_id'], false, 'btree'],
  ['contract_line_items', 'ix_contract_line_items_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['contract_line_items', 'ix_contract_line_items_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['contract_milestones', 'ix_contract_milestones_contract_id', ['contract_id'], false, 'btree'],
  ['contract_milestones', 'ix_contract_milestones_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['contract_milestones', 'ix_contract_milestones_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['contract_milestones', 'ix_contract_milestones_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['contract_milestones', 'ix_contract_milestones_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['contract_object_assignments', 'ix_contract_object_assignments_contract_id', ['contract_id'], false, 'btree'],
  ['contract_object_assignments', 'ix_contract_object_assignments_contract_line_item_id', ['contract_line_item_id'], false, 'btree'],
  ['contract_object_assignments', 'ix_contract_object_assignments_assignment_role_concept_id', ['assignment_role_concept_id'], false, 'btree'],
  ['contract_object_assignments', 'ix_contract_object_assignments_business_partner_id', ['business_partner_id'], false, 'btree'],
  ['contract_object_assignments', 'ix_contract_object_assignments_asset_id', ['asset_id'], false, 'btree'],
  ['contract_object_assignments', 'ix_contract_object_assignments_liability_id', ['liability_id'], false, 'btree'],
  ['contract_object_assignments', 'ix_contract_object_assignments_project_id', ['project_id'], false, 'btree'],
  ['contract_object_assignments', 'ix_contract_object_assignments_wbs_element_id', ['wbs_element_id'], false, 'btree'],
  ['contract_object_assignments', 'ix_contract_object_assignments_cost_center_id', ['cost_center_id'], false, 'btree'],
  ['contract_object_assignments', 'ix_contract_object_assignments_profit_center_id', ['profit_center_id'], false, 'btree'],
  ['contract_object_assignments', 'ix_contract_object_assignments_purchase_order_id', ['purchase_order_id'], false, 'btree'],
  ['contract_object_assignments', 'ix_contract_object_assignments_sales_order_id', ['sales_order_id'], false, 'btree'],
  ['contract_object_assignments', 'ix_contract_object_assignments_employee_id', ['employee_id'], false, 'btree'],
  ['contract_object_assignments', 'ix_contract_object_assignments_practice_id', ['practice_id'], false, 'btree'],
  ['contract_object_assignments', 'ix_contract_object_assignments_branch_id', ['branch_id'], false, 'btree'],
  ['contract_object_assignments', 'ix_contract_object_assignments_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['contract_object_assignments', 'ix_contract_object_assignments_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['contract_object_assignments', 'ix_contract_object_assignments_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['contract_object_assignments', 'ix_contract_object_assignments_contract_role_status', ['contract_id', 'assignment_role_concept_id', 'status_concept_id'], false, 'btree'],
  ['contract_obligations', 'ix_contract_obligations_contract_id', ['contract_id'], false, 'btree'],
  ['contract_obligations', 'ix_contract_obligations_contract_version_id', ['contract_version_id'], false, 'btree'],
  ['contract_obligations', 'ix_contract_obligations_contract_clause_instance_id', ['contract_clause_instance_id'], false, 'btree'],
  ['contract_obligations', 'ix_contract_obligations_obligation_type_concept_id', ['obligation_type_concept_id'], false, 'btree'],
  ['contract_obligations', 'ix_contract_obligations_responsible_business_partner_id', ['responsible_business_partner_id'], false, 'btree'],
  ['contract_obligations', 'ix_contract_obligations_responsible_user_id', ['responsible_user_id'], false, 'btree'],
  ['contract_obligations', 'ix_contract_obligations_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['contract_obligations', 'ix_contract_obligations_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['contract_obligations', 'ix_contract_obligations_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['contract_obligations', 'ix_contract_obligations_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['contract_obligations', 'ix_contract_obligations_contract_status_due', ['contract_id', 'status_concept_id', 'due_date'], false, 'btree'],
  ['contract_obligations', 'ix_contract_obligations_responsible_status_due', ['responsible_user_id', 'status_concept_id', 'due_date'], false, 'btree'],
  ['contract_obligation_events', 'ix_contract_obligation_events_contract_obligation_id', ['contract_obligation_id'], false, 'btree'],
  ['contract_obligation_events', 'ix_contract_obligation_events_event_type_concept_id', ['event_type_concept_id'], false, 'btree'],
  ['contract_obligation_events', 'ix_contract_obligation_events_evidence_file_id', ['evidence_file_id'], false, 'btree'],
  ['contract_obligation_events', 'ix_contract_obligation_events_outcome_concept_id', ['outcome_concept_id'], false, 'btree'],
  ['contract_obligation_events', 'ix_contract_obligation_events_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['contract_obligation_events', 'ix_contract_obligation_events_obligation_event', ['contract_obligation_id', 'event_at desc'], false, 'btree'],
  ['contract_obligation_events', 'brin_contract_obligation_events_created_at', ['created_at'], false, 'brin'],
  ['contract_parties', 'ix_contract_parties_contract_id', ['contract_id'], false, 'btree'],
  ['contract_parties', 'ix_contract_parties_party_role_concept_id', ['party_role_concept_id'], false, 'btree'],
  ['contract_parties', 'ix_contract_parties_party_type_concept_id', ['party_type_concept_id'], false, 'btree'],
  ['contract_parties', 'ix_contract_parties_signatory_user_id', ['signatory_user_id'], false, 'btree'],
  ['contract_parties', 'ix_contract_parties_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['contract_parties', 'ix_contract_parties_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['contract_payment_schedules', 'uq_contract_payment_schedules_contract_id_installment_number', ['contract_id', 'installment_number'], true, 'btree'],
  ['contract_payment_schedules', 'ix_contract_payment_schedules_contract_id', ['contract_id'], false, 'btree'],
  ['contract_payment_schedules', 'ix_contract_payment_schedules_contract_line_item_id', ['contract_line_item_id'], false, 'btree'],
  ['contract_payment_schedules', 'ix_contract_payment_schedules_contract_obligation_id', ['contract_obligation_id'], false, 'btree'],
  ['contract_payment_schedules', 'ix_contract_payment_schedules_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['contract_payment_schedules', 'ix_contract_payment_schedules_payment_direction_concept_id', ['payment_direction_concept_id'], false, 'btree'],
];
