import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `erp` (parte 3/3).
 * 121 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const erpIndexes3: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['projects', 'ix_projects_profit_center_id', ['profit_center_id'], false, 'btree'],
  ['projects', 'ix_projects_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['projects', 'ix_projects_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['projects', 'ix_projects_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['projects', 'ix_projects_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['purchase_order_items', 'uq_purchase_order_items_purchase_order_id_line_number', ['purchase_order_id', 'line_number'], true, 'btree'],
  ['purchase_order_items', 'ix_purchase_order_items_purchase_order_id', ['purchase_order_id'], false, 'btree'],
  ['purchase_order_items', 'ix_purchase_order_items_purchase_requisition_item_id', ['purchase_requisition_item_id'], false, 'btree'],
  ['purchase_order_items', 'ix_purchase_order_items_contract_line_item_id', ['contract_line_item_id'], false, 'btree'],
  ['purchase_order_items', 'ix_purchase_order_items_item_type_concept_id', ['item_type_concept_id'], false, 'btree'],
  ['purchase_order_items', 'ix_purchase_order_items_unit_concept_id', ['unit_concept_id'], false, 'btree'],
  ['purchase_order_items', 'ix_purchase_order_items_tax_code_id', ['tax_code_id'], false, 'btree'],
  ['purchase_order_items', 'ix_purchase_order_items_expense_account_id', ['expense_account_id'], false, 'btree'],
  ['purchase_order_items', 'ix_purchase_order_items_inventory_account_id', ['inventory_account_id'], false, 'btree'],
  ['purchase_order_items', 'ix_purchase_order_items_asset_id', ['asset_id'], false, 'btree'],
  ['purchase_order_items', 'ix_purchase_order_items_cost_center_id', ['cost_center_id'], false, 'btree'],
  ['purchase_order_items', 'ix_purchase_order_items_profit_center_id', ['profit_center_id'], false, 'btree'],
  ['purchase_order_items', 'ix_purchase_order_items_project_id', ['project_id'], false, 'btree'],
  ['purchase_order_items', 'ix_purchase_order_items_wbs_element_id', ['wbs_element_id'], false, 'btree'],
  ['purchase_order_items', 'ix_purchase_order_items_branch_id', ['branch_id'], false, 'btree'],
  ['purchase_order_items', 'ix_purchase_order_items_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['purchase_order_items', 'ix_purchase_order_items_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['purchase_order_items', 'ix_purchase_order_items_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['purchase_orders', 'uq_purchase_orders_tenant_id_purchase_order_number', ['tenant_id', 'purchase_order_number'], true, 'btree'],
  ['purchase_orders', 'ix_purchase_orders_tenant_id', ['tenant_id'], false, 'btree'],
  ['purchase_orders', 'ix_purchase_orders_supplier_business_partner_id', ['supplier_business_partner_id'], false, 'btree'],
  ['purchase_orders', 'ix_purchase_orders_contract_id', ['contract_id'], false, 'btree'],
  ['purchase_orders', 'ix_purchase_orders_purchase_requisition_id', ['purchase_requisition_id'], false, 'btree'],
  ['purchase_orders', 'ix_purchase_orders_ordering_department_id', ['ordering_department_id'], false, 'btree'],
  ['purchase_orders', 'ix_purchase_orders_buyer_employee_id', ['buyer_employee_id'], false, 'btree'],
  ['purchase_orders', 'ix_purchase_orders_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['purchase_orders', 'ix_purchase_orders_payment_terms_concept_id', ['payment_terms_concept_id'], false, 'btree'],
  ['purchase_orders', 'ix_purchase_orders_incoterm_concept_id', ['incoterm_concept_id'], false, 'btree'],
  ['purchase_orders', 'ix_purchase_orders_approval_status_concept_id', ['approval_status_concept_id'], false, 'btree'],
  ['purchase_orders', 'ix_purchase_orders_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['purchase_orders', 'ix_purchase_orders_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['purchase_orders', 'ix_purchase_orders_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['purchase_orders', 'ix_purchase_orders_tenant_status_updated', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['purchase_requisition_items', 'uq_purchase_requisition_items_purchase_requisition_id__283ecf3d', ['purchase_requisition_id', 'line_number'], true, 'btree'],
  ['purchase_requisition_items', 'ix_purchase_requisition_items_purchase_requisition_id', ['purchase_requisition_id'], false, 'btree'],
  ['purchase_requisition_items', 'ix_purchase_requisition_items_item_type_concept_id', ['item_type_concept_id'], false, 'btree'],
  ['purchase_requisition_items', 'ix_purchase_requisition_items_unit_concept_id', ['unit_concept_id'], false, 'btree'],
  ['purchase_requisition_items', 'ix_purchase_requisition_items_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['purchase_requisition_items', 'ix_purchase_requisition_items_cost_center_id', ['cost_center_id'], false, 'btree'],
  ['purchase_requisition_items', 'ix_purchase_requisition_items_profit_center_id', ['profit_center_id'], false, 'btree'],
  ['purchase_requisition_items', 'ix_purchase_requisition_items_project_id', ['project_id'], false, 'btree'],
  ['purchase_requisition_items', 'ix_purchase_requisition_items_wbs_element_id', ['wbs_element_id'], false, 'btree'],
  ['purchase_requisition_items', 'ix_purchase_requisition_items_asset_id', ['asset_id'], false, 'btree'],
  ['purchase_requisition_items', 'ix_purchase_requisition_items_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['purchase_requisition_items', 'ix_purchase_requisition_items_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['purchase_requisition_items', 'ix_purchase_requisition_items_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['purchase_requisitions', 'uq_purchase_requisitions_tenant_id_requisition_number', ['tenant_id', 'requisition_number'], true, 'btree'],
  ['purchase_requisitions', 'ix_purchase_requisitions_tenant_id', ['tenant_id'], false, 'btree'],
  ['purchase_requisitions', 'ix_purchase_requisitions_requester_employee_id', ['requester_employee_id'], false, 'btree'],
  ['purchase_requisitions', 'ix_purchase_requisitions_requesting_department_id', ['requesting_department_id'], false, 'btree'],
  ['purchase_requisitions', 'ix_purchase_requisitions_project_id', ['project_id'], false, 'btree'],
  ['purchase_requisitions', 'ix_purchase_requisitions_wbs_element_id', ['wbs_element_id'], false, 'btree'],
  ['purchase_requisitions', 'ix_purchase_requisitions_approval_status_concept_id', ['approval_status_concept_id'], false, 'btree'],
  ['purchase_requisitions', 'ix_purchase_requisitions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['purchase_requisitions', 'ix_purchase_requisitions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['purchase_requisitions', 'ix_purchase_requisitions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['purchase_requisitions', 'ix_purchase_requisitions_tenant_status_updated', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['sales_order_items', 'uq_sales_order_items_sales_order_id_line_number', ['sales_order_id', 'line_number'], true, 'btree'],
  ['sales_order_items', 'ix_sales_order_items_sales_order_id', ['sales_order_id'], false, 'btree'],
  ['sales_order_items', 'ix_sales_order_items_contract_line_item_id', ['contract_line_item_id'], false, 'btree'],
  ['sales_order_items', 'ix_sales_order_items_tax_code_id', ['tax_code_id'], false, 'btree'],
  ['sales_order_items', 'ix_sales_order_items_income_account_id', ['income_account_id'], false, 'btree'],
  ['sales_order_items', 'ix_sales_order_items_cost_center_id', ['cost_center_id'], false, 'btree'],
  ['sales_order_items', 'ix_sales_order_items_profit_center_id', ['profit_center_id'], false, 'btree'],
  ['sales_order_items', 'ix_sales_order_items_project_id', ['project_id'], false, 'btree'],
  ['sales_order_items', 'ix_sales_order_items_wbs_element_id', ['wbs_element_id'], false, 'btree'],
  ['sales_order_items', 'ix_sales_order_items_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['sales_order_items', 'ix_sales_order_items_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['sales_order_items', 'ix_sales_order_items_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['sales_orders', 'uq_sales_orders_tenant_id_sales_order_number', ['tenant_id', 'sales_order_number'], true, 'btree'],
  ['sales_orders', 'ix_sales_orders_tenant_id', ['tenant_id'], false, 'btree'],
  ['sales_orders', 'ix_sales_orders_customer_business_partner_id', ['customer_business_partner_id'], false, 'btree'],
  ['sales_orders', 'ix_sales_orders_contract_id', ['contract_id'], false, 'btree'],
  ['sales_orders', 'ix_sales_orders_opportunity_id', ['opportunity_id'], false, 'btree'],
  ['sales_orders', 'ix_sales_orders_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['sales_orders', 'ix_sales_orders_payment_terms_concept_id', ['payment_terms_concept_id'], false, 'btree'],
  ['sales_orders', 'ix_sales_orders_owner_employee_id', ['owner_employee_id'], false, 'btree'],
  ['sales_orders', 'ix_sales_orders_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['sales_orders', 'ix_sales_orders_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['sales_orders', 'ix_sales_orders_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['sales_orders', 'ix_sales_orders_tenant_status_updated', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['service_entry_items', 'uq_service_entry_items_service_entry_sheet_id_line_number', ['service_entry_sheet_id', 'line_number'], true, 'btree'],
  ['service_entry_items', 'ix_service_entry_items_service_entry_sheet_id', ['service_entry_sheet_id'], false, 'btree'],
  ['service_entry_items', 'ix_service_entry_items_purchase_order_item_id', ['purchase_order_item_id'], false, 'btree'],
  ['service_entry_items', 'ix_service_entry_items_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['service_entry_items', 'ix_service_entry_items_cost_center_id', ['cost_center_id'], false, 'btree'],
  ['service_entry_items', 'ix_service_entry_items_profit_center_id', ['profit_center_id'], false, 'btree'],
  ['service_entry_items', 'ix_service_entry_items_project_id', ['project_id'], false, 'btree'],
  ['service_entry_items', 'ix_service_entry_items_wbs_element_id', ['wbs_element_id'], false, 'btree'],
  ['service_entry_items', 'ix_service_entry_items_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['service_entry_items', 'ix_service_entry_items_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['service_entry_sheets', 'uq_service_entry_sheets_tenant_id_sheet_number', ['tenant_id', 'sheet_number'], true, 'btree'],
  ['service_entry_sheets', 'ix_service_entry_sheets_tenant_id', ['tenant_id'], false, 'btree'],
  ['service_entry_sheets', 'ix_service_entry_sheets_purchase_order_id', ['purchase_order_id'], false, 'btree'],
  ['service_entry_sheets', 'ix_service_entry_sheets_supplier_business_partner_id', ['supplier_business_partner_id'], false, 'btree'],
  ['service_entry_sheets', 'ix_service_entry_sheets_accepted_by_employee_id', ['accepted_by_employee_id'], false, 'btree'],
  ['service_entry_sheets', 'ix_service_entry_sheets_approval_status_concept_id', ['approval_status_concept_id'], false, 'btree'],
  ['service_entry_sheets', 'ix_service_entry_sheets_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['service_entry_sheets', 'ix_service_entry_sheets_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['service_entry_sheets', 'ix_service_entry_sheets_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['service_entry_sheets', 'ix_service_entry_sheets_tenant_status_updated', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['time_off_requests', 'ix_time_off_requests_employee_id', ['employee_id'], false, 'btree'],
  ['time_off_requests', 'ix_time_off_requests_leave_type_concept_id', ['leave_type_concept_id'], false, 'btree'],
  ['time_off_requests', 'ix_time_off_requests_approver_user_id', ['approver_user_id'], false, 'btree'],
  ['time_off_requests', 'ix_time_off_requests_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['time_off_requests', 'ix_time_off_requests_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['time_off_requests', 'ix_time_off_requests_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['wbs_elements', 'uq_wbs_elements_project_id_wbs_code', ['project_id', 'wbs_code'], true, 'btree'],
  ['wbs_elements', 'ix_wbs_elements_project_id', ['project_id'], false, 'btree'],
  ['wbs_elements', 'ix_wbs_elements_parent_wbs_element_id', ['parent_wbs_element_id'], false, 'btree'],
  ['wbs_elements', 'ix_wbs_elements_cost_center_id', ['cost_center_id'], false, 'btree'],
  ['wbs_elements', 'ix_wbs_elements_profit_center_id', ['profit_center_id'], false, 'btree'],
  ['wbs_elements', 'ix_wbs_elements_responsible_employee_id', ['responsible_employee_id'], false, 'btree'],
  ['wbs_elements', 'ix_wbs_elements_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['wbs_elements', 'ix_wbs_elements_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['wbs_elements', 'ix_wbs_elements_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
];
