import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `forms`.
 * 109 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const formsIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['dynamic_field_definitions', 'uq_dynamic_field_definitions_code', ['code'], true, 'btree'],
  ['dynamic_field_definitions', 'ix_dynamic_field_definitions_data_use_concept_id', ['data_use_concept_id'], false, 'btree'],
  ['dynamic_field_definitions', 'ix_dynamic_field_definitions_sensitivity_concept_id', ['sensitivity_concept_id'], false, 'btree'],
  ['dynamic_field_definitions', 'ix_dynamic_field_definitions_semantic_concept_id', ['semantic_concept_id'], false, 'btree'],
  ['dynamic_field_definitions', 'ix_dynamic_field_definitions_value_set_id', ['value_set_id'], false, 'btree'],
  ['dynamic_field_definitions', 'ix_dynamic_field_definitions_unit_value_set_id', ['unit_value_set_id'], false, 'btree'],
  ['dynamic_field_definitions', 'ix_dynamic_field_definitions_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['dynamic_field_definitions', 'ix_dynamic_field_definitions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['dynamic_field_definitions', 'ix_dynamic_field_definitions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['dynamic_field_sections', 'uq_dynamic_field_sections_code', ['code'], true, 'btree'],
  ['dynamic_field_sections', 'ix_dynamic_field_sections_parent_section_id', ['parent_section_id'], false, 'btree'],
  ['dynamic_field_sections', 'ix_dynamic_field_sections_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['dynamic_field_sections', 'ix_dynamic_field_sections_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['dynamic_field_sections', 'ix_dynamic_field_sections_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['extension_target_policies', 'ix_extension_target_policies_target_resource_concept_id', ['target_resource_concept_id'], false, 'btree'],
  ['extension_target_policies', 'ix_extension_target_policies_definition_set_id', ['definition_set_id'], false, 'btree'],
  ['extension_target_policies', 'ix_extension_target_policies_tenant_id', ['tenant_id'], false, 'btree'],
  ['extension_target_policies', 'ix_extension_target_policies_jurisdiction_concept_id', ['jurisdiction_concept_id'], false, 'btree'],
  ['extension_target_policies', 'ix_extension_target_policies_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['extension_target_policies', 'ix_extension_target_policies_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['extension_target_policies', 'ix_extension_target_policies_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['extension_target_policies', 'ix_extension_target_policies_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['field_assignments', 'ix_field_assignments_field_id', ['field_id'], false, 'btree'],
  ['field_assignments', 'ix_field_assignments_target_resource_concept_id', ['target_resource_concept_id'], false, 'btree'],
  ['field_assignments', 'ix_field_assignments_profile_type_concept_id', ['profile_type_concept_id'], false, 'btree'],
  ['field_assignments', 'ix_field_assignments_tenant_id', ['tenant_id'], false, 'btree'],
  ['field_assignments', 'ix_field_assignments_branch_id', ['branch_id'], false, 'btree'],
  ['field_assignments', 'ix_field_assignments_section_id', ['section_id'], false, 'btree'],
  ['field_assignments', 'ix_field_assignments_read_role_value_set_id', ['read_role_value_set_id'], false, 'btree'],
  ['field_assignments', 'ix_field_assignments_write_role_value_set_id', ['write_role_value_set_id'], false, 'btree'],
  ['field_assignments', 'ix_field_assignments_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['field_assignments', 'ix_field_assignments_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['field_assignments', 'ix_field_assignments_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['field_assignments', 'ix_field_assignments_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['field_definition_localizations', 'ix_field_definition_localizations_field_id', ['field_id'], false, 'btree'],
  ['field_definition_localizations', 'ix_field_definition_localizations_language_concept_id', ['language_concept_id'], false, 'btree'],
  ['field_definition_localizations', 'ix_field_definition_localizations_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['field_definition_localizations', 'ix_field_definition_localizations_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['field_definition_set_versions', 'ix_field_definition_set_versions_definition_set_id', ['definition_set_id'], false, 'btree'],
  ['field_definition_set_versions', 'ix_field_definition_set_versions_publication_status_concept_id', ['publication_status_concept_id'], false, 'btree'],
  ['field_definition_set_versions', 'ix_field_definition_set_versions_compatibility_concept_id', ['compatibility_concept_id'], false, 'btree'],
  ['field_definition_set_versions', 'ix_field_definition_set_versions_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['field_definition_sets', 'uq_field_definition_sets_namespace_uri', ['namespace_uri'], true, 'btree'],
  ['field_definition_sets', 'ix_field_definition_sets_owner_tenant_id', ['owner_tenant_id'], false, 'btree'],
  ['field_definition_sets', 'ix_field_definition_sets_target_domain_concept_id', ['target_domain_concept_id'], false, 'btree'],
  ['field_definition_sets', 'ix_field_definition_sets_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['field_definition_sets', 'ix_field_definition_sets_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['field_definition_sets', 'ix_field_definition_sets_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['field_dependencies', 'ix_field_dependencies_target_field_id', ['target_field_id'], false, 'btree'],
  ['field_dependencies', 'ix_field_dependencies_source_field_id', ['source_field_id'], false, 'btree'],
  ['field_dependencies', 'ix_field_dependencies_operator_concept_id', ['operator_concept_id'], false, 'btree'],
  ['field_dependencies', 'ix_field_dependencies_behavior_concept_id', ['behavior_concept_id'], false, 'btree'],
  ['field_dependencies', 'ix_field_dependencies_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['field_dependencies', 'ix_field_dependencies_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['field_schema_migrations', 'ix_field_schema_migrations_definition_set_id', ['definition_set_id'], false, 'btree'],
  ['field_schema_migrations', 'ix_field_schema_migrations_from_version_id', ['from_version_id'], false, 'btree'],
  ['field_schema_migrations', 'ix_field_schema_migrations_to_version_id', ['to_version_id'], false, 'btree'],
  ['field_schema_migrations', 'ix_field_schema_migrations_migration_type_concept_id', ['migration_type_concept_id'], false, 'btree'],
  ['field_schema_migrations', 'ix_field_schema_migrations_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['field_schema_migrations', 'ix_field_schema_migrations_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['field_schema_migrations', 'ix_field_schema_migrations_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['field_set_members', 'ix_field_set_members_definition_set_version_id', ['definition_set_version_id'], false, 'btree'],
  ['field_set_members', 'ix_field_set_members_field_id', ['field_id'], false, 'btree'],
  ['field_set_members', 'ix_field_set_members_section_id', ['section_id'], false, 'btree'],
  ['field_set_members', 'ix_field_set_members_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['field_validation_rules', 'ix_field_validation_rules_field_id', ['field_id'], false, 'btree'],
  ['field_validation_rules', 'ix_field_validation_rules_rule_type_concept_id', ['rule_type_concept_id'], false, 'btree'],
  ['field_validation_rules', 'ix_field_validation_rules_operator_concept_id', ['operator_concept_id'], false, 'btree'],
  ['field_validation_rules', 'ix_field_validation_rules_severity_concept_id', ['severity_concept_id'], false, 'btree'],
  ['field_validation_rules', 'ix_field_validation_rules_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['field_validation_rules', 'ix_field_validation_rules_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['field_value_access_rules', 'ix_field_value_access_rules_field_id', ['field_id'], false, 'btree'],
  ['field_value_access_rules', 'ix_field_value_access_rules_assignment_id', ['assignment_id'], false, 'btree'],
  ['field_value_access_rules', 'ix_field_value_access_rules_purpose_of_use_value_set_id', ['purpose_of_use_value_set_id'], false, 'btree'],
  ['field_value_access_rules', 'ix_field_value_access_rules_read_role_value_set_id', ['read_role_value_set_id'], false, 'btree'],
  ['field_value_access_rules', 'ix_field_value_access_rules_write_role_value_set_id', ['write_role_value_set_id'], false, 'btree'],
  ['field_value_access_rules', 'ix_field_value_access_rules_consent_category_concept_id', ['consent_category_concept_id'], false, 'btree'],
  ['field_value_access_rules', 'ix_field_value_access_rules_mask_strategy_concept_id', ['mask_strategy_concept_id'], false, 'btree'],
  ['field_value_access_rules', 'ix_field_value_access_rules_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['field_value_access_rules', 'ix_field_value_access_rules_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['field_value_access_rules', 'ix_field_value_access_rules_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['field_value_audit', 'ix_field_value_audit_field_value_id', ['field_value_id'], false, 'btree'],
  ['field_value_audit', 'ix_field_value_audit_action_concept_id', ['action_concept_id'], false, 'btree'],
  ['field_value_audit', 'ix_field_value_audit_user_id', ['user_id'], false, 'btree'],
  ['field_value_audit', 'ix_field_value_audit_reason_concept_id', ['reason_concept_id'], false, 'btree'],
  ['field_value_audit', 'ix_field_value_audit_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['field_value_provenance', 'ix_field_value_provenance_field_value_id', ['field_value_id'], false, 'btree'],
  ['field_value_provenance', 'ix_field_value_provenance_import_batch_id', ['import_batch_id'], false, 'btree'],
  ['field_value_provenance', 'ix_field_value_provenance_author_profile_id', ['author_profile_id'], false, 'btree'],
  ['field_value_provenance', 'ix_field_value_provenance_entered_by_user_id', ['entered_by_user_id'], false, 'btree'],
  ['field_value_provenance', 'ix_field_value_provenance_verification_status_concept_id', ['verification_status_concept_id'], false, 'btree'],
  ['field_value_provenance', 'ix_field_value_provenance_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['field_values', 'ix_field_values_form_instance_id', ['form_instance_id'], false, 'btree'],
  ['field_values', 'ix_field_values_resource_type_concept_id', ['resource_type_concept_id'], false, 'btree'],
  ['field_values', 'ix_field_values_field_id', ['field_id'], false, 'btree'],
  ['field_values', 'ix_field_values_assignment_id', ['assignment_id'], false, 'btree'],
  ['field_values', 'ix_field_values_value_concept_id', ['value_concept_id'], false, 'btree'],
  ['field_values', 'ix_field_values_file_id', ['file_id'], false, 'btree'],
  ['field_values', 'ix_field_values_unit_concept_id', ['unit_concept_id'], false, 'btree'],
  ['field_values', 'ix_field_values_data_source_concept_id', ['data_source_concept_id'], false, 'btree'],
  ['field_values', 'ix_field_values_value_status_concept_id', ['value_status_concept_id'], false, 'btree'],
  ['field_values', 'ix_field_values_supersedes_value_id', ['supersedes_value_id'], false, 'btree'],
  ['field_values', 'ix_field_values_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['field_values', 'ix_field_values_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['form_instances', 'ix_form_instances_resource_type_concept_id', ['resource_type_concept_id'], false, 'btree'],
  ['form_instances', 'ix_form_instances_tenant_context_id', ['tenant_context_id'], false, 'btree'],
  ['form_instances', 'ix_form_instances_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['form_instances', 'ix_form_instances_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['form_instances', 'ix_form_instances_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
];
