import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `health_context`.
 * 62 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const healthContextIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['context_agents', 'uq_context_agents_code', ['code'], true, 'btree'],
  ['context_agents', 'ix_context_agents_agent_type_concept_id', ['agent_type_concept_id'], false, 'btree'],
  ['context_agents', 'ix_context_agents_provider_id', ['provider_id'], false, 'btree'],
  ['context_agents', 'ix_context_agents_owner_tenant_id', ['owner_tenant_id'], false, 'btree'],
  ['context_agents', 'ix_context_agents_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['context_agents', 'ix_context_agents_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['context_agents', 'ix_context_agents_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['context_collection_runs', 'uq_context_collection_runs_idempotency_key', ['idempotency_key'], true, 'btree'],
  ['context_collection_runs', 'ix_context_collection_runs_schedule_id', ['schedule_id'], false, 'btree'],
  ['context_collection_runs', 'ix_context_collection_runs_agent_id', ['agent_id'], false, 'btree'],
  ['context_collection_runs', 'ix_context_collection_runs_country_concept_id', ['country_concept_id'], false, 'btree'],
  ['context_collection_runs', 'ix_context_collection_runs_trigger_concept_id', ['trigger_concept_id'], false, 'btree'],
  ['context_collection_runs', 'ix_context_collection_runs_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['context_collection_runs', 'ix_context_collection_runs_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['context_collection_runs', 'brin_context_collection_runs_recorded_at', ['recorded_at'], false, 'brin'],
  ['context_fact_evidence', 'ix_context_fact_evidence_health_context_fact_id', ['health_context_fact_id'], false, 'btree'],
  ['context_fact_evidence', 'ix_context_fact_evidence_source_observation_id', ['source_observation_id'], false, 'btree'],
  ['context_fact_evidence', 'ix_context_fact_evidence_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['context_fact_evidence', 'brin_context_fact_evidence_recorded_at', ['recorded_at'], false, 'brin'],
  ['context_quality_reviews', 'ix_context_quality_reviews_context_version_id', ['context_version_id'], false, 'btree'],
  ['context_quality_reviews', 'ix_context_quality_reviews_reviewer_agent_id', ['reviewer_agent_id'], false, 'btree'],
  ['context_quality_reviews', 'ix_context_quality_reviews_reviewed_by_user_id', ['reviewed_by_user_id'], false, 'btree'],
  ['context_quality_reviews', 'ix_context_quality_reviews_review_type_concept_id', ['review_type_concept_id'], false, 'btree'],
  ['context_quality_reviews', 'ix_context_quality_reviews_outcome_concept_id', ['outcome_concept_id'], false, 'btree'],
  ['context_quality_reviews', 'brin_context_quality_reviews_recorded_at', ['recorded_at'], false, 'brin'],
  ['context_source_observations', 'ix_context_source_observations_collection_run_id', ['collection_run_id'], false, 'btree'],
  ['context_source_observations', 'ix_context_source_observations_source_id', ['source_id'], false, 'btree'],
  ['context_source_observations', 'ix_context_source_observations_country_concept_id', ['country_concept_id'], false, 'btree'],
  ['context_source_observations', 'ix_context_source_observations_raw_payload_file_id', ['raw_payload_file_id'], false, 'btree'],
  ['context_source_observations', 'ix_context_source_observations_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['context_source_observations', 'ix_context_source_observations_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['context_source_observations', 'brin_context_source_observations_recorded_at', ['recorded_at'], false, 'brin'],
  ['country_context_schedules', 'ix_country_context_schedules_country_concept_id', ['country_concept_id'], false, 'btree'],
  ['country_context_schedules', 'ix_country_context_schedules_agent_id', ['agent_id'], false, 'btree'],
  ['country_context_schedules', 'ix_country_context_schedules_timezone_concept_id', ['timezone_concept_id'], false, 'btree'],
  ['country_context_schedules', 'ix_country_context_schedules_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['country_context_schedules', 'ix_country_context_schedules_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['country_context_schedules', 'ix_country_context_schedules_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['country_health_contexts', 'ix_country_health_contexts_country_concept_id', ['country_concept_id'], false, 'btree'],
  ['country_health_contexts', 'ix_country_health_contexts_context_domain_concept_id', ['context_domain_concept_id'], false, 'btree'],
  ['country_health_contexts', 'ix_country_health_contexts_current_version_id', ['current_version_id'], false, 'btree'],
  ['country_health_contexts', 'ix_country_health_contexts_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['country_health_contexts', 'ix_country_health_contexts_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['country_health_contexts', 'ix_country_health_contexts_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['country_health_context_versions', 'ix_country_health_context_versions_country_health_context_id', ['country_health_context_id'], false, 'btree'],
  ['country_health_context_versions', 'ix_country_health_context_versions_collection_run_id', ['collection_run_id'], false, 'btree'],
  ['country_health_context_versions', 'ix_country_health_context_versions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['country_health_context_versions', 'ix_country_health_context_versions_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['country_health_context_versions', 'uq_country_health_context_versions_country_health_cont_2ef6a520', ['country_health_context_id', 'version_number'], true, 'btree'],
  ['health_context_facts', 'ix_health_context_facts_context_version_id', ['context_version_id'], false, 'btree'],
  ['health_context_facts', 'ix_health_context_facts_metric_concept_id', ['metric_concept_id'], false, 'btree'],
  ['health_context_facts', 'ix_health_context_facts_unit_concept_id', ['unit_concept_id'], false, 'btree'],
  ['health_context_facts', 'ix_health_context_facts_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['health_context_facts', 'ix_health_context_facts_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['health_context_facts', 'brin_health_context_facts_recorded_at', ['recorded_at'], false, 'brin'],
  ['health_context_sources', 'uq_health_context_sources_code', ['code'], true, 'btree'],
  ['health_context_sources', 'ix_health_context_sources_source_type_concept_id', ['source_type_concept_id'], false, 'btree'],
  ['health_context_sources', 'ix_health_context_sources_country_concept_id', ['country_concept_id'], false, 'btree'],
  ['health_context_sources', 'ix_health_context_sources_trust_tier_concept_id', ['trust_tier_concept_id'], false, 'btree'],
  ['health_context_sources', 'ix_health_context_sources_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['health_context_sources', 'ix_health_context_sources_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['health_context_sources', 'ix_health_context_sources_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
];
