import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `health_data` (parte 2/2).
 * 58 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const healthDataIndexes2: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['health_terminology_mapping_sets', 'ix_health_terminology_mapping_sets_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['health_terminology_mapping_sets', 'ix_health_terminology_mapping_sets_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['health_terminology_mapping_sets', 'ix_health_terminology_mapping_sets_tenant_created', ['tenant_id', 'created_at desc'], false, 'btree'],
  ['health_terminology_mapping_sets', 'uk_health_terminology_mapping_sets_tenant_code_version', ['tenant_id', 'code', 'version'], true, 'btree'],
  ['omop_mapping_rules', 'ix_omop_mapping_rules_omop_mapping_set_id', ['omop_mapping_set_id'], false, 'btree'],
  ['omop_mapping_rules', 'ix_omop_mapping_rules_source_resource_type_concept_id', ['source_resource_type_concept_id'], false, 'btree'],
  ['omop_mapping_rules', 'ix_omop_mapping_rules_vocabulary_mapping_set_id', ['vocabulary_mapping_set_id'], false, 'btree'],
  ['omop_mapping_rules', 'ix_omop_mapping_rules_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['omop_mapping_rules', 'ix_omop_mapping_rules_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['omop_mapping_rules', 'ix_omop_mapping_rules_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['omop_mapping_rules', 'uk_omop_mapping_rules_set_target', ['omop_mapping_set_id', 'source_resource_type_concept_id', 'target_table', 'target_column'], true, 'btree'],
  ['omop_mapping_sets', 'ix_omop_mapping_sets_tenant_id', ['tenant_id'], false, 'btree'],
  ['omop_mapping_sets', 'ix_omop_mapping_sets_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['omop_mapping_sets', 'ix_omop_mapping_sets_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['omop_mapping_sets', 'ix_omop_mapping_sets_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['omop_mapping_sets', 'ix_omop_mapping_sets_tenant_created', ['tenant_id', 'created_at desc'], false, 'btree'],
  ['omop_mapping_sets', 'uk_omop_mapping_sets_tenant_code_versions', ['tenant_id', 'code', 'omop_cdm_version', 'source_model_version'], true, 'btree'],
  ['omop_transformation_runs', 'ix_omop_transformation_runs_tenant_id', ['tenant_id'], false, 'btree'],
  ['omop_transformation_runs', 'ix_omop_transformation_runs_omop_mapping_set_id', ['omop_mapping_set_id'], false, 'btree'],
  ['omop_transformation_runs', 'ix_omop_transformation_runs_health_ingestion_batch_id', ['health_ingestion_batch_id'], false, 'btree'],
  ['omop_transformation_runs', 'ix_omop_transformation_runs_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['omop_transformation_runs', 'ix_omop_transformation_runs_lineage_job_run_id', ['lineage_job_run_id'], false, 'btree'],
  ['omop_transformation_runs', 'ix_omop_transformation_runs_tenant_status', ['tenant_id', 'status_concept_id', 'created_at desc'], false, 'btree'],
  ['patient_identity_clusters', 'ix_patient_identity_clusters_tenant_id', ['tenant_id'], false, 'btree'],
  ['patient_identity_clusters', 'ix_patient_identity_clusters_master_patient_profile_id', ['master_patient_profile_id'], false, 'btree'],
  ['patient_identity_clusters', 'ix_patient_identity_clusters_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['patient_identity_clusters', 'ix_patient_identity_clusters_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['patient_identity_clusters', 'ix_patient_identity_clusters_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['patient_identity_clusters', 'ix_patient_identity_clusters_tenant_status', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['patient_identity_clusters', 'uk_patient_identity_clusters_tenant_identifier', ['tenant_id', 'cluster_identifier'], true, 'btree'],
  ['patient_identity_members', 'ix_patient_identity_members_patient_identity_cluster_id', ['patient_identity_cluster_id'], false, 'btree'],
  ['patient_identity_members', 'ix_patient_identity_members_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['patient_identity_members', 'ix_patient_identity_members_source_system_id', ['source_system_id'], false, 'btree'],
  ['patient_identity_members', 'ix_patient_identity_members_member_role_concept_id', ['member_role_concept_id'], false, 'btree'],
  ['patient_identity_members', 'ix_patient_identity_members_match_status_concept_id', ['match_status_concept_id'], false, 'btree'],
  ['patient_identity_members', 'uk_patient_identity_members_cluster_patient', ['patient_identity_cluster_id', 'patient_profile_id', 'effective_from'], true, 'btree'],
  ['patient_match_candidates', 'ix_patient_match_candidates_tenant_id', ['tenant_id'], false, 'btree'],
  ['patient_match_candidates', 'ix_patient_match_candidates_left_patient_profile_id', ['left_patient_profile_id'], false, 'btree'],
  ['patient_match_candidates', 'ix_patient_match_candidates_right_patient_profile_id', ['right_patient_profile_id'], false, 'btree'],
  ['patient_match_candidates', 'ix_patient_match_candidates_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['patient_match_candidates', 'ix_patient_match_candidates_tenant_status', ['tenant_id', 'status_concept_id', 'created_at desc'], false, 'btree'],
  ['patient_match_candidates', 'uk_patient_match_candidates_pair_algorithm', ['tenant_id', 'left_patient_profile_id', 'right_patient_profile_id', 'algorithm_version'], true, 'btree'],
  ['patient_match_decisions', 'ix_patient_match_decisions_patient_match_candidate_id', ['patient_match_candidate_id'], false, 'btree'],
  ['patient_match_decisions', 'ix_patient_match_decisions_decision_concept_id', ['decision_concept_id'], false, 'btree'],
  ['patient_match_decisions', 'ix_patient_match_decisions_decided_by_user_id', ['decided_by_user_id'], false, 'btree'],
  ['patient_match_decisions', 'ix_patient_match_decisions_resulting_cluster_id', ['resulting_cluster_id'], false, 'btree'],
  ['patient_match_decisions', 'uk_patient_match_decisions_candidate', ['patient_match_candidate_id'], true, 'btree'],
  ['patient_timeline_entries', 'ix_patient_timeline_entries_custodian_tenant_id', ['custodian_tenant_id'], false, 'btree'],
  ['patient_timeline_entries', 'ix_patient_timeline_entries_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['patient_timeline_entries', 'ix_patient_timeline_entries_event_type_concept_id', ['event_type_concept_id'], false, 'btree'],
  ['patient_timeline_entries', 'ix_patient_timeline_entries_source_entity_type_concept_id', ['source_entity_type_concept_id'], false, 'btree'],
  ['patient_timeline_entries', 'ix_patient_timeline_entries_source_entity_id', ['source_entity_id'], false, 'btree'],
  ['patient_timeline_entries', 'ix_patient_timeline_entries_encounter_id', ['encounter_id'], false, 'btree'],
  ['patient_timeline_entries', 'ix_patient_timeline_entries_organization_id', ['organization_id'], false, 'btree'],
  ['patient_timeline_entries', 'ix_patient_timeline_entries_clinical_priority_concept_id', ['clinical_priority_concept_id'], false, 'btree'],
  ['patient_timeline_entries', 'ix_patient_timeline_entries_patient_visibility_concept_id', ['patient_visibility_concept_id'], false, 'btree'],
  ['patient_timeline_entries', 'uk_patient_timeline_entries_source', ['source_entity_type_concept_id', 'source_entity_id', 'event_type_concept_id'], true, 'btree'],
  ['patient_timeline_entries', 'ix_patient_timeline_entries_patient_time', ['custodian_tenant_id', 'patient_profile_id', 'event_time desc'], false, 'btree'],
];
