import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `health_data` (parte 1/2).
 * 180 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const healthDataIndexes1: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['canonical_health_resources', 'ix_canonical_health_resources_custodian_tenant_id', ['custodian_tenant_id'], false, 'btree'],
  ['canonical_health_resources', 'ix_canonical_health_resources_resource_type_concept_id', ['resource_type_concept_id'], false, 'btree'],
  ['canonical_health_resources', 'ix_canonical_health_resources_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['canonical_health_resources', 'ix_canonical_health_resources_encounter_id', ['encounter_id'], false, 'btree'],
  ['canonical_health_resources', 'ix_canonical_health_resources_source_system_id', ['source_system_id'], false, 'btree'],
  ['canonical_health_resources', 'ix_canonical_health_resources_current_version_id', ['current_version_id'], false, 'btree'],
  ['canonical_health_resources', 'ix_canonical_health_resources_lifecycle_status_concept_id', ['lifecycle_status_concept_id'], false, 'btree'],
  ['canonical_health_resources', 'ix_canonical_health_resources_retention_policy_id', ['retention_policy_id'], false, 'btree'],
  ['canonical_health_resources', 'uk_canonical_health_resources_tenant_type_logical', ['custodian_tenant_id', 'resource_type_concept_id', 'logical_identifier'], true, 'btree'],
  ['canonical_health_resources', 'ix_canonical_health_resources_patient_type', ['custodian_tenant_id', 'patient_profile_id', 'resource_type_concept_id', 'updated_at desc'], false, 'btree'],
  ['canonical_health_resource_versions', 'ix_canonical_health_resource_versions_canonical_health_e81f83a5', ['canonical_health_resource_id'], false, 'btree'],
  ['canonical_health_resource_versions', 'ix_canonical_health_resource_versions_health_ingestion_d6d6039b', ['health_ingestion_record_id'], false, 'btree'],
  ['canonical_health_resource_versions', 'ix_canonical_health_resource_versions_change_type_concept_id', ['change_type_concept_id'], false, 'btree'],
  ['canonical_health_resource_versions', 'ix_canonical_health_resource_versions_payload_format_concept_id', ['payload_format_concept_id'], false, 'btree'],
  ['canonical_health_resource_versions', 'ix_canonical_health_resource_versions_original_payload_file_id', ['original_payload_file_id'], false, 'btree'],
  ['canonical_health_resource_versions', 'ix_canonical_health_resource_versions_provenance_record_id', ['provenance_record_id'], false, 'btree'],
  ['canonical_health_resource_versions', 'ix_canonical_health_resource_versions_supersedes_version_id', ['supersedes_version_id'], false, 'btree'],
  ['canonical_health_resource_versions', 'brin_canonical_health_resource_versions_recorded_at', ['recorded_at'], false, 'brin'],
  ['canonical_health_resource_versions', 'uk_canonical_health_resource_versions_resource_version', ['canonical_health_resource_id', 'version_number'], true, 'btree'],
  ['canonical_health_resource_versions', 'gin_canonical_health_versions_payload', ['normalized_payload_json'], false, 'gin'],
  ['canonical_resource_bindings', 'ix_canonical_resource_bindings_canonical_health_resource_id', ['canonical_health_resource_id'], false, 'btree'],
  ['canonical_resource_bindings', 'ix_canonical_resource_bindings_domain_entity_type_concept_id', ['domain_entity_type_concept_id'], false, 'btree'],
  ['canonical_resource_bindings', 'ix_canonical_resource_bindings_domain_entity_id', ['domain_entity_id'], false, 'btree'],
  ['canonical_resource_bindings', 'ix_canonical_resource_bindings_binding_role_concept_id', ['binding_role_concept_id'], false, 'btree'],
  ['canonical_resource_bindings', 'ix_canonical_resource_bindings_binding_status_concept_id', ['binding_status_concept_id'], false, 'btree'],
  ['canonical_resource_bindings', 'ix_canonical_resource_bindings_mapping_version_id', ['mapping_version_id'], false, 'btree'],
  ['canonical_resource_bindings', 'uk_canonical_resource_bindings_resource_target', ['canonical_health_resource_id', 'domain_entity_type_concept_id', 'domain_entity_id', 'binding_role_concept_id'], true, 'btree'],
  ['canonical_resource_bindings', 'ix_canonical_resource_bindings_target', ['domain_entity_type_concept_id', 'domain_entity_id'], false, 'btree'],
  ['canonical_resource_identifiers', 'ix_canonical_resource_identifiers_canonical_health_resource_id', ['canonical_health_resource_id'], false, 'btree'],
  ['canonical_resource_identifiers', 'ix_canonical_resource_identifiers_identifier_type_concept_id', ['identifier_type_concept_id'], false, 'btree'],
  ['canonical_resource_identifiers', 'uk_canonical_resource_identifiers_system_value', ['identifier_system', 'identifier_value', 'canonical_health_resource_id'], true, 'btree'],
  ['canonical_resource_relationships', 'ix_canonical_resource_relationships_source_resource_id', ['source_resource_id'], false, 'btree'],
  ['canonical_resource_relationships', 'ix_canonical_resource_relationships_target_resource_id', ['target_resource_id'], false, 'btree'],
  ['canonical_resource_relationships', 'ix_canonical_resource_relationships_relationship_type__429279b9', ['relationship_type_concept_id'], false, 'btree'],
  ['canonical_resource_relationships', 'ix_canonical_resource_relationships_relationship_role__312b7dc1', ['relationship_role_concept_id'], false, 'btree'],
  ['canonical_resource_relationships', 'uk_canonical_resource_relationships_pair_type', ['source_resource_id', 'target_resource_id', 'relationship_type_concept_id', 'effective_from'], true, 'btree'],
  ['fhir_profile_definitions', 'ix_fhir_profile_definitions_resource_type_concept_id', ['resource_type_concept_id'], false, 'btree'],
  ['fhir_profile_definitions', 'ix_fhir_profile_definitions_jurisdiction_concept_id', ['jurisdiction_concept_id'], false, 'btree'],
  ['fhir_profile_definitions', 'ix_fhir_profile_definitions_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['fhir_profile_definitions', 'ix_fhir_profile_definitions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['fhir_profile_definitions', 'ix_fhir_profile_definitions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['fhir_profile_definitions', 'uk_fhir_profile_definitions_url', ['canonical_url'], true, 'btree'],
  ['fhir_profile_versions', 'ix_fhir_profile_versions_fhir_profile_definition_id', ['fhir_profile_definition_id'], false, 'btree'],
  ['fhir_profile_versions', 'ix_fhir_profile_versions_fhir_release_concept_id', ['fhir_release_concept_id'], false, 'btree'],
  ['fhir_profile_versions', 'ix_fhir_profile_versions_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['fhir_profile_versions', 'ix_fhir_profile_versions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['fhir_profile_versions', 'ix_fhir_profile_versions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['fhir_profile_versions', 'uk_fhir_profile_versions_profile_version', ['fhir_profile_definition_id', 'version'], true, 'btree'],
  ['fhir_validation_issues', 'ix_fhir_validation_issues_fhir_validation_run_id', ['fhir_validation_run_id'], false, 'btree'],
  ['fhir_validation_issues', 'ix_fhir_validation_issues_severity_concept_id', ['severity_concept_id'], false, 'btree'],
  ['fhir_validation_issues', 'brin_fhir_validation_issues_created_at', ['created_at'], false, 'brin'],
  ['fhir_validation_runs', 'ix_fhir_validation_runs_tenant_id', ['tenant_id'], false, 'btree'],
  ['fhir_validation_runs', 'ix_fhir_validation_runs_canonical_health_resource_version_id', ['canonical_health_resource_version_id'], false, 'btree'],
  ['fhir_validation_runs', 'ix_fhir_validation_runs_fhir_profile_version_id', ['fhir_profile_version_id'], false, 'btree'],
  ['fhir_validation_runs', 'ix_fhir_validation_runs_result_concept_id', ['result_concept_id'], false, 'btree'],
  ['fhir_validation_runs', 'ix_fhir_validation_runs_tenant_created', ['tenant_id', 'created_at desc'], false, 'btree'],
  ['fhir_validation_runs', 'brin_fhir_validation_runs_created_at', ['created_at'], false, 'brin'],
  ['health_data_quality_issues', 'ix_health_data_quality_issues_health_data_quality_run_id', ['health_data_quality_run_id'], false, 'btree'],
  ['health_data_quality_issues', 'ix_health_data_quality_issues_health_data_quality_rule_id', ['health_data_quality_rule_id'], false, 'btree'],
  ['health_data_quality_issues', 'ix_health_data_quality_issues_canonical_health_resource_id', ['canonical_health_resource_id'], false, 'btree'],
  ['health_data_quality_issues', 'ix_health_data_quality_issues_canonical_resource_version_id', ['canonical_resource_version_id'], false, 'btree'],
  ['health_data_quality_issues', 'ix_health_data_quality_issues_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['health_data_quality_issues', 'ix_health_data_quality_issues_assigned_user_id', ['assigned_user_id'], false, 'btree'],
  ['health_data_quality_issues', 'brin_health_data_quality_issues_created_at', ['created_at'], false, 'brin'],
  ['health_data_quality_rules', 'ix_health_data_quality_rules_health_data_quality_rule_set_id', ['health_data_quality_rule_set_id'], false, 'btree'],
  ['health_data_quality_rules', 'ix_health_data_quality_rules_dimension_concept_id', ['dimension_concept_id'], false, 'btree'],
  ['health_data_quality_rules', 'ix_health_data_quality_rules_severity_concept_id', ['severity_concept_id'], false, 'btree'],
  ['health_data_quality_rules', 'ix_health_data_quality_rules_expression_language_concept_id', ['expression_language_concept_id'], false, 'btree'],
  ['health_data_quality_rules', 'ix_health_data_quality_rules_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['health_data_quality_rules', 'ix_health_data_quality_rules_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['health_data_quality_rules', 'ix_health_data_quality_rules_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['health_data_quality_rules', 'uk_health_data_quality_rules_set_code', ['health_data_quality_rule_set_id', 'rule_code'], true, 'btree'],
  ['health_data_quality_rule_sets', 'ix_health_data_quality_rule_sets_tenant_id', ['tenant_id'], false, 'btree'],
  ['health_data_quality_rule_sets', 'ix_health_data_quality_rule_sets_scope_concept_id', ['scope_concept_id'], false, 'btree'],
  ['health_data_quality_rule_sets', 'ix_health_data_quality_rule_sets_resource_type_concept_id', ['resource_type_concept_id'], false, 'btree'],
  ['health_data_quality_rule_sets', 'ix_health_data_quality_rule_sets_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['health_data_quality_rule_sets', 'ix_health_data_quality_rule_sets_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['health_data_quality_rule_sets', 'ix_health_data_quality_rule_sets_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['health_data_quality_rule_sets', 'ix_health_data_quality_rule_sets_tenant_created', ['tenant_id', 'created_at desc'], false, 'btree'],
  ['health_data_quality_rule_sets', 'uk_health_data_quality_rule_sets_tenant_code_version', ['tenant_id', 'code', 'version'], true, 'btree'],
  ['health_data_quality_runs', 'ix_health_data_quality_runs_tenant_id', ['tenant_id'], false, 'btree'],
  ['health_data_quality_runs', 'ix_health_data_quality_runs_health_data_quality_rule_set_id', ['health_data_quality_rule_set_id'], false, 'btree'],
  ['health_data_quality_runs', 'ix_health_data_quality_runs_health_ingestion_batch_id', ['health_ingestion_batch_id'], false, 'btree'],
  ['health_data_quality_runs', 'ix_health_data_quality_runs_canonical_resource_id', ['canonical_resource_id'], false, 'btree'],
  ['health_data_quality_runs', 'ix_health_data_quality_runs_result_concept_id', ['result_concept_id'], false, 'btree'],
  ['health_data_quality_runs', 'ix_health_data_quality_runs_tenant_created', ['tenant_id', 'created_at desc'], false, 'btree'],
  ['health_data_quality_runs', 'brin_health_data_quality_runs_created_at', ['created_at'], false, 'brin'],
  ['health_deidentification_profiles', 'ix_health_deidentification_profiles_tenant_id', ['tenant_id'], false, 'btree'],
  ['health_deidentification_profiles', 'ix_health_deidentification_profiles_methodology_concept_id', ['methodology_concept_id'], false, 'btree'],
  ['health_deidentification_profiles', 'ix_health_deidentification_profiles_reidentification_k_57e6e028', ['reidentification_key_secret_id'], false, 'btree'],
  ['health_deidentification_profiles', 'ix_health_deidentification_profiles_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['health_deidentification_profiles', 'ix_health_deidentification_profiles_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['health_deidentification_profiles', 'ix_health_deidentification_profiles_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['health_deidentification_profiles', 'ix_health_deidentification_profiles_tenant_created', ['tenant_id', 'created_at desc'], false, 'btree'],
  ['health_deidentification_profiles', 'uk_health_deidentification_profiles_tenant_code_version', ['tenant_id', 'code', 'version'], true, 'btree'],
  ['health_deidentification_runs', 'ix_health_deidentification_runs_tenant_id', ['tenant_id'], false, 'btree'],
  ['health_deidentification_runs', 'ix_health_deidentification_runs_health_deidentificatio_06745a39', ['health_deidentification_profile_id'], false, 'btree'],
  ['health_deidentification_runs', 'ix_health_deidentification_runs_purpose_concept_id', ['purpose_concept_id'], false, 'btree'],
  ['health_deidentification_runs', 'ix_health_deidentification_runs_consent_directive_id', ['consent_directive_id'], false, 'btree'],
  ['health_deidentification_runs', 'ix_health_deidentification_runs_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['health_deidentification_runs', 'ix_health_deidentification_runs_input_manifest_file_id', ['input_manifest_file_id'], false, 'btree'],
  ['health_deidentification_runs', 'ix_health_deidentification_runs_output_manifest_file_id', ['output_manifest_file_id'], false, 'btree'],
  ['health_deidentification_runs', 'ix_health_deidentification_runs_tenant_status', ['tenant_id', 'status_concept_id', 'created_at desc'], false, 'btree'],
  ['health_deidentification_runs', 'brin_health_deidentification_runs_created_at', ['created_at'], false, 'brin'],
  ['health_export_jobs', 'ix_health_export_jobs_tenant_id', ['tenant_id'], false, 'btree'],
  ['health_export_jobs', 'ix_health_export_jobs_export_type_concept_id', ['export_type_concept_id'], false, 'btree'],
  ['health_export_jobs', 'ix_health_export_jobs_requested_by_user_id', ['requested_by_user_id'], false, 'btree'],
  ['health_export_jobs', 'ix_health_export_jobs_purpose_of_use_concept_id', ['purpose_of_use_concept_id'], false, 'btree'],
  ['health_export_jobs', 'ix_health_export_jobs_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['health_export_jobs', 'ix_health_export_jobs_cohort_definition_id', ['cohort_definition_id'], false, 'btree'],
  ['health_export_jobs', 'ix_health_export_jobs_consent_directive_id', ['consent_directive_id'], false, 'btree'],
  ['health_export_jobs', 'ix_health_export_jobs_deidentification_run_id', ['deidentification_run_id'], false, 'btree'],
  ['health_export_jobs', 'ix_health_export_jobs_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['health_export_jobs', 'ix_health_export_jobs_tenant_status', ['tenant_id', 'status_concept_id', 'created_at desc'], false, 'btree'],
  ['health_export_jobs', 'brin_health_export_jobs_created_at', ['created_at'], false, 'brin'],
  ['health_export_manifests', 'ix_health_export_manifests_health_export_job_id', ['health_export_job_id'], false, 'btree'],
  ['health_export_manifests', 'ix_health_export_manifests_file_id', ['file_id'], false, 'btree'],
  ['health_export_manifests', 'ix_health_export_manifests_encryption_profile_id', ['encryption_profile_id'], false, 'btree'],
  ['health_export_manifests', 'ix_health_export_manifests_retention_policy_id', ['retention_policy_id'], false, 'btree'],
  ['health_export_manifests', 'brin_health_export_manifests_created_at', ['created_at'], false, 'brin'],
  ['health_export_manifests', 'uk_health_export_manifests_job_version', ['health_export_job_id', 'manifest_version'], true, 'btree'],
  ['health_ingestion_batches', 'ix_health_ingestion_batches_tenant_id', ['tenant_id'], false, 'btree'],
  ['health_ingestion_batches', 'ix_health_ingestion_batches_health_source_connection_id', ['health_source_connection_id'], false, 'btree'],
  ['health_ingestion_batches', 'ix_health_ingestion_batches_ingestion_mode_concept_id', ['ingestion_mode_concept_id'], false, 'btree'],
  ['health_ingestion_batches', 'ix_health_ingestion_batches_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['health_ingestion_batches', 'ix_health_ingestion_batches_payload_manifest_file_id', ['payload_manifest_file_id'], false, 'btree'],
  ['health_ingestion_batches', 'ix_health_ingestion_batches_tenant_status', ['tenant_id', 'status_concept_id', 'created_at desc'], false, 'btree'],
  ['health_ingestion_batches', 'brin_health_ingestion_batches_created_at', ['created_at'], false, 'brin'],
  ['health_ingestion_batches', 'uk_health_ingestion_batches_connection_identifier', ['health_source_connection_id', 'batch_identifier'], true, 'btree'],
  ['health_ingestion_records', 'ix_health_ingestion_records_health_ingestion_batch_id', ['health_ingestion_batch_id'], false, 'btree'],
  ['health_ingestion_records', 'ix_health_ingestion_records_resource_type_concept_id', ['resource_type_concept_id'], false, 'btree'],
  ['health_ingestion_records', 'ix_health_ingestion_records_payload_file_id', ['payload_file_id'], false, 'btree'],
  ['health_ingestion_records', 'ix_health_ingestion_records_validation_status_concept_id', ['validation_status_concept_id'], false, 'btree'],
  ['health_ingestion_records', 'ix_health_ingestion_records_processing_status_concept_id', ['processing_status_concept_id'], false, 'btree'],
  ['health_ingestion_records', 'ix_health_ingestion_records_canonical_resource_id', ['canonical_resource_id'], false, 'btree'],
  ['health_ingestion_records', 'brin_health_ingestion_records_created_at', ['created_at'], false, 'brin'],
  ['health_ingestion_records', 'uk_health_ingestion_records_batch_source', ['health_ingestion_batch_id', 'source_record_identifier', 'source_version'], true, 'btree'],
  ['health_lineage_edges', 'ix_health_lineage_edges_tenant_id', ['tenant_id'], false, 'btree'],
  ['health_lineage_edges', 'ix_health_lineage_edges_source_type_concept_id', ['source_type_concept_id'], false, 'btree'],
  ['health_lineage_edges', 'ix_health_lineage_edges_source_id', ['source_id'], false, 'btree'],
  ['health_lineage_edges', 'ix_health_lineage_edges_target_type_concept_id', ['target_type_concept_id'], false, 'btree'],
  ['health_lineage_edges', 'ix_health_lineage_edges_target_id', ['target_id'], false, 'btree'],
  ['health_lineage_edges', 'ix_health_lineage_edges_transformation_type_concept_id', ['transformation_type_concept_id'], false, 'btree'],
  ['health_lineage_edges', 'ix_health_lineage_edges_job_run_id', ['job_run_id'], false, 'btree'],
  ['health_lineage_edges', 'ix_health_lineage_edges_tenant_created', ['tenant_id', 'created_at desc'], false, 'btree'],
  ['health_lineage_edges', 'brin_health_lineage_edges_recorded_at', ['recorded_at'], false, 'brin'],
  ['health_lineage_edges', 'ix_health_lineage_edges_source', ['source_type_concept_id', 'source_id', 'recorded_at desc'], false, 'btree'],
  ['health_lineage_edges', 'ix_health_lineage_edges_target', ['target_type_concept_id', 'target_id', 'recorded_at desc'], false, 'btree'],
  ['health_provenance_records', 'ix_health_provenance_records_custodian_tenant_id', ['custodian_tenant_id'], false, 'btree'],
  ['health_provenance_records', 'ix_health_provenance_records_activity_concept_id', ['activity_concept_id'], false, 'btree'],
  ['health_provenance_records', 'ix_health_provenance_records_source_system_id', ['source_system_id'], false, 'btree'],
  ['health_provenance_records', 'ix_health_provenance_records_responsible_agent_type_concept_id', ['responsible_agent_type_concept_id'], false, 'btree'],
  ['health_provenance_records', 'ix_health_provenance_records_responsible_agent_id', ['responsible_agent_id'], false, 'btree'],
  ['health_provenance_records', 'ix_health_provenance_records_on_behalf_of_organization_id', ['on_behalf_of_organization_id'], false, 'btree'],
  ['health_provenance_records', 'ix_health_provenance_records_signature_id', ['signature_id'], false, 'btree'],
  ['health_provenance_records', 'brin_health_provenance_records_recorded_at', ['recorded_at'], false, 'brin'],
  ['health_provenance_targets', 'ix_health_provenance_targets_health_provenance_record_id', ['health_provenance_record_id'], false, 'btree'],
  ['health_provenance_targets', 'ix_health_provenance_targets_target_type_concept_id', ['target_type_concept_id'], false, 'btree'],
  ['health_provenance_targets', 'ix_health_provenance_targets_target_id', ['target_id'], false, 'btree'],
  ['health_provenance_targets', 'ix_health_provenance_targets_role_concept_id', ['role_concept_id'], false, 'btree'],
  ['health_provenance_targets', 'uk_health_provenance_targets_record_target', ['health_provenance_record_id', 'target_type_concept_id', 'target_id', 'role_concept_id'], true, 'btree'],
  ['health_provenance_targets', 'ix_health_provenance_targets_target', ['target_type_concept_id', 'target_id'], false, 'btree'],
  ['health_source_connections', 'ix_health_source_connections_health_source_system_id', ['health_source_system_id'], false, 'btree'],
  ['health_source_connections', 'ix_health_source_connections_connection_type_concept_id', ['connection_type_concept_id'], false, 'btree'],
  ['health_source_connections', 'ix_health_source_connections_credential_id', ['credential_id'], false, 'btree'],
  ['health_source_connections', 'ix_health_source_connections_network_policy_id', ['network_policy_id'], false, 'btree'],
  ['health_source_connections', 'ix_health_source_connections_format_concept_id', ['format_concept_id'], false, 'btree'],
  ['health_source_connections', 'ix_health_source_connections_cursor_strategy_concept_id', ['cursor_strategy_concept_id'], false, 'btree'],
  ['health_source_connections', 'ix_health_source_connections_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['health_source_connections', 'ix_health_source_connections_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['health_source_connections', 'ix_health_source_connections_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['health_source_connections', 'uk_health_source_connections_system_type_endpoint', ['health_source_system_id', 'connection_type_concept_id', 'endpoint_uri'], true, 'btree'],
  ['health_source_systems', 'ix_health_source_systems_tenant_id', ['tenant_id'], false, 'btree'],
  ['health_source_systems', 'ix_health_source_systems_source_type_concept_id', ['source_type_concept_id'], false, 'btree'],
  ['health_source_systems', 'ix_health_source_systems_organization_id', ['organization_id'], false, 'btree'],
  ['health_source_systems', 'ix_health_source_systems_trust_level_concept_id', ['trust_level_concept_id'], false, 'btree'],
  ['health_source_systems', 'ix_health_source_systems_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['health_source_systems', 'ix_health_source_systems_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['health_source_systems', 'ix_health_source_systems_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['health_source_systems', 'ix_health_source_systems_tenant_created', ['tenant_id', 'created_at desc'], false, 'btree'],
];
