import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `iam`.
 * 65 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const iamIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['account_activations', 'ux_account_activations_token_hash', ['token_hash'], true, 'btree'],
  ['account_activations', 'ix_account_activations_user', ['user_id', 'state_concept_id'], false, 'btree'],
  ['account_lockouts', 'ix_account_lockouts_user_id', ['user_id'], false, 'btree'],
  ['account_lockouts', 'ix_account_lockouts_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['account_lockouts', 'ix_account_lockouts_locked_until', ['locked_until'], false, 'btree'],
  ['api_keys', 'uk_api_keys_key_prefix', ['key_prefix'], true, 'btree'],
  ['api_keys', 'ix_api_keys_tenant_id', ['tenant_id'], false, 'btree'],
  ['api_keys', 'ix_api_keys_owner_user_id', ['owner_user_id'], false, 'btree'],
  ['api_keys', 'ix_api_keys_service_principal_id', ['service_principal_id'], false, 'btree'],
  ['api_keys', 'ix_api_keys_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['api_key_scopes', 'ix_api_key_scopes_api_key_id', ['api_key_id'], false, 'btree'],
  ['api_key_scopes', 'uk_api_key_scopes_key_scope', ['api_key_id', 'scope_concept_id', 'resource'], true, 'btree'],
  ['authentication_credentials', 'ix_authentication_credentials_user_id', ['user_id'], false, 'btree'],
  ['authentication_credentials', 'ix_authentication_credentials_method_concept_id', ['method_concept_id'], false, 'btree'],
  ['authentication_credentials', 'ix_authentication_credentials_hash_algorithm_concept_id', ['hash_algorithm_concept_id'], false, 'btree'],
  ['authentication_credentials', 'ix_authentication_credentials_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['authentication_credentials', 'ix_authentication_credentials_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['authentication_credentials', 'ix_authentication_credentials_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['authentication_credentials', 'ux_authentication_credentials_live_password_subject', ['external_subject'], true, 'btree', 'method_concept_id = \'37da1281-cc62-5032-b598-1eb39dc46060\' AND external_subject IS NOT NULL AND state_concept_id IN (\'38a1d301-f40d-5b17-a695-5e6d605f8b19\', \'2e38dae4-c0c2-52ff-b1c9-a954ff880a38\')'],
  ['devices', 'uq_devices_device_fingerprint', ['device_fingerprint'], true, 'btree'],
  ['devices', 'ix_devices_user_id', ['user_id'], false, 'btree'],
  ['devices', 'ix_devices_platform_concept_id', ['platform_concept_id'], false, 'btree'],
  ['devices', 'ix_devices_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['devices', 'ix_devices_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['email_verifications', 'ux_email_verifications_token_hash', ['token_hash'], true, 'btree'],
  ['email_verifications', 'ix_email_verifications_user', ['user_id', 'state_concept_id'], false, 'btree'],
  ['mfa_factors', 'ix_mfa_factors_user_id', ['user_id'], false, 'btree'],
  ['mfa_factors', 'ix_mfa_factors_factor_type_concept_id', ['factor_type_concept_id'], false, 'btree'],
  ['mfa_factors', 'ix_mfa_factors_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['mfa_factors', 'ix_mfa_factors_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['mfa_factors', 'ix_mfa_factors_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['password_resets', 'ux_password_resets_token_hash', ['token_hash'], true, 'btree'],
  ['password_resets', 'ix_password_resets_user_state', ['user_id', 'state_concept_id'], false, 'btree'],
  ['refresh_tokens', 'uq_refresh_tokens_token_hash', ['token_hash'], true, 'btree'],
  ['refresh_tokens', 'ix_refresh_tokens_session_id', ['session_id'], false, 'btree'],
  ['refresh_tokens', 'ix_refresh_tokens_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['refresh_tokens', 'ix_refresh_tokens_replaced_by_id', ['replaced_by_id'], false, 'btree'],
  ['refresh_tokens', 'ix_refresh_tokens_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['refresh_tokens', 'ix_refresh_tokens_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['refresh_tokens', 'ix_refresh_tokens_session_state', ['session_id', 'state_concept_id', 'expires_at'], false, 'btree'],
  ['security_events', 'ix_security_events_user_id', ['user_id'], false, 'btree'],
  ['security_events', 'ix_security_events_event_type_concept_id', ['event_type_concept_id'], false, 'btree'],
  ['security_events', 'ix_security_events_outcome_concept_id', ['outcome_concept_id'], false, 'btree'],
  ['security_events', 'ix_security_events_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['security_events', 'brin_security_events_recorded_at', ['recorded_at'], false, 'brin'],
  ['sessions', 'uq_sessions_token_id', ['token_id'], true, 'btree'],
  ['sessions', 'ix_sessions_user_id', ['user_id'], false, 'btree'],
  ['sessions', 'ix_sessions_device_id', ['device_id'], false, 'btree'],
  ['sessions', 'ix_sessions_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['sessions', 'ix_sessions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['sessions', 'ix_sessions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['sessions', 'ix_sessions_user_state_expiry', ['user_id', 'state_concept_id', 'expires_at'], false, 'btree'],
  ['users', 'ix_users_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['users', 'ix_users_preferred_language_concept_id', ['preferred_language_concept_id'], false, 'btree'],
  ['users', 'ix_users_residence_country_concept_id', ['residence_country_concept_id'], false, 'btree'],
  ['users', 'ix_users_data_residency_region_concept_id', ['data_residency_region_concept_id'], false, 'btree'],
  ['users', 'ix_users_mfa_status_concept_id', ['mfa_status_concept_id'], false, 'btree'],
  ['users', 'ix_users_legal_basis_concept_id', ['legal_basis_concept_id'], false, 'btree'],
  ['users', 'ix_users_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['users', 'ix_users_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['user_global_roles', 'ix_user_global_roles_user_id', ['user_id'], false, 'btree'],
  ['user_global_roles', 'ix_user_global_roles_role_concept_id', ['role_concept_id'], false, 'btree'],
  ['user_global_roles', 'ix_user_global_roles_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['user_global_roles', 'ix_user_global_roles_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['user_global_roles', 'ix_user_global_roles_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
];
