import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `identity_assurance`.
 * 76 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const identityAssuranceIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['identity_assertions', 'ix_identity_assertions_identity_verification_case_id', ['identity_verification_case_id'], false, 'btree'],
  ['identity_assertions', 'ix_identity_assertions_issuer_identity_authority_id', ['issuer_identity_authority_id'], false, 'btree'],
  ['identity_assertions', 'ix_identity_assertions_subject_type_concept_id', ['subject_type_concept_id'], false, 'btree'],
  ['identity_assertions', 'ix_identity_assertions_assertion_type_concept_id', ['assertion_type_concept_id'], false, 'btree'],
  ['identity_assertions', 'ix_identity_assertions_assurance_level_concept_id', ['assurance_level_concept_id'], false, 'btree'],
  ['identity_assertions', 'ix_identity_assertions_revocation_reason_concept_id', ['revocation_reason_concept_id'], false, 'btree'],
  ['identity_assertions', 'brin_identity_assertions_created_at', ['created_at'], false, 'brin'],
  ['identity_authorities', 'uq_identity_authorities_authority_code', ['authority_code'], true, 'btree'],
  ['identity_authorities', 'ix_identity_authorities_tenant_id', ['tenant_id'], false, 'btree'],
  ['identity_authorities', 'ix_identity_authorities_authority_type_concept_id', ['authority_type_concept_id'], false, 'btree'],
  ['identity_authorities', 'ix_identity_authorities_jurisdiction_concept_id', ['jurisdiction_concept_id'], false, 'btree'],
  ['identity_authorities', 'ix_identity_authorities_assurance_framework_concept_id', ['assurance_framework_concept_id'], false, 'btree'],
  ['identity_authorities', 'ix_identity_authorities_verification_status_concept_id', ['verification_status_concept_id'], false, 'btree'],
  ['identity_authorities', 'ix_identity_authorities_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['identity_authorities', 'ix_identity_authorities_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['identity_authorities', 'ix_identity_authorities_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['identity_authorities', 'ix_identity_authorities_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['identity_authority_endpoints', 'ix_identity_authority_endpoints_identity_authority_id', ['identity_authority_id'], false, 'btree'],
  ['identity_authority_endpoints', 'ix_identity_authority_endpoints_integration_endpoint_id', ['integration_endpoint_id'], false, 'btree'],
  ['identity_authority_endpoints', 'ix_identity_authority_endpoints_capability_concept_id', ['capability_concept_id'], false, 'btree'],
  ['identity_authority_endpoints', 'ix_identity_authority_endpoints_assurance_level_concept_id', ['assurance_level_concept_id'], false, 'btree'],
  ['identity_authority_endpoints', 'ix_identity_authority_endpoints_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['identity_authority_endpoints', 'ix_identity_authority_endpoints_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['identity_authority_endpoints', 'ix_identity_authority_endpoints_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['identity_checks', 'ix_identity_checks_identity_verification_case_id', ['identity_verification_case_id'], false, 'btree'],
  ['identity_checks', 'ix_identity_checks_check_type_concept_id', ['check_type_concept_id'], false, 'btree'],
  ['identity_checks', 'ix_identity_checks_authority_id', ['authority_id'], false, 'btree'],
  ['identity_checks', 'ix_identity_checks_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['identity_checks', 'ix_identity_checks_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['identity_checks', 'ix_identity_checks_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['identity_check_results', 'ix_identity_check_results_identity_check_id', ['identity_check_id'], false, 'btree'],
  ['identity_check_results', 'ix_identity_check_results_result_concept_id', ['result_concept_id'], false, 'btree'],
  ['identity_check_results', 'ix_identity_check_results_supersedes_result_id', ['supersedes_result_id'], false, 'btree'],
  ['identity_check_results', 'ix_identity_check_results_checked_by_actor_type_concept_id', ['checked_by_actor_type_concept_id'], false, 'btree'],
  ['identity_evidence_records', 'ix_identity_evidence_records_identity_verification_case_id', ['identity_verification_case_id'], false, 'btree'],
  ['identity_evidence_records', 'ix_identity_evidence_records_evidence_type_concept_id', ['evidence_type_concept_id'], false, 'btree'],
  ['identity_evidence_records', 'ix_identity_evidence_records_issuer_authority_id', ['issuer_authority_id'], false, 'btree'],
  ['identity_evidence_records', 'ix_identity_evidence_records_evidence_file_id', ['evidence_file_id'], false, 'btree'],
  ['identity_evidence_records', 'ix_identity_evidence_records_evidence_quality_concept_id', ['evidence_quality_concept_id'], false, 'btree'],
  ['identity_evidence_records', 'ix_identity_evidence_records_collected_under_consent_id', ['collected_under_consent_id'], false, 'btree'],
  ['identity_evidence_records', 'ix_identity_evidence_records_verification_status_concept_id', ['verification_status_concept_id'], false, 'btree'],
  ['identity_evidence_records', 'ix_identity_evidence_records_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['identity_fraud_signals', 'ix_identity_fraud_signals_identity_verification_case_id', ['identity_verification_case_id'], false, 'btree'],
  ['identity_fraud_signals', 'ix_identity_fraud_signals_signal_type_concept_id', ['signal_type_concept_id'], false, 'btree'],
  ['identity_fraud_signals', 'ix_identity_fraud_signals_severity_concept_id', ['severity_concept_id'], false, 'btree'],
  ['identity_fraud_signals', 'ix_identity_fraud_signals_source_concept_id', ['source_concept_id'], false, 'btree'],
  ['identity_fraud_signals', 'ix_identity_fraud_signals_resolution_concept_id', ['resolution_concept_id'], false, 'btree'],
  ['identity_fraud_signals', 'brin_identity_fraud_signals_created_at', ['created_at'], false, 'brin'],
  ['identity_manual_review_cases', 'ix_identity_manual_review_cases_identity_verification_case_id', ['identity_verification_case_id'], false, 'btree'],
  ['identity_manual_review_cases', 'ix_identity_manual_review_cases_review_reason_concept_id', ['review_reason_concept_id'], false, 'btree'],
  ['identity_manual_review_cases', 'ix_identity_manual_review_cases_assigned_to_user_id', ['assigned_to_user_id'], false, 'btree'],
  ['identity_manual_review_cases', 'ix_identity_manual_review_cases_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['identity_manual_review_cases', 'ix_identity_manual_review_cases_decision_concept_id', ['decision_concept_id'], false, 'btree'],
  ['identity_manual_review_cases', 'ix_identity_manual_review_cases_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['identity_manual_review_cases', 'ix_identity_manual_review_cases_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['identity_verification_attempts', 'ix_identity_verification_attempts_identity_verification_case_id', ['identity_verification_case_id'], false, 'btree'],
  ['identity_verification_attempts', 'ix_identity_verification_attempts_identity_authority_e_96e7ce47', ['identity_authority_endpoint_id'], false, 'btree'],
  ['identity_verification_attempts', 'ix_identity_verification_attempts_request_message_id', ['request_message_id'], false, 'btree'],
  ['identity_verification_attempts', 'ix_identity_verification_attempts_response_message_id', ['response_message_id'], false, 'btree'],
  ['identity_verification_attempts', 'ix_identity_verification_attempts_outcome_concept_id', ['outcome_concept_id'], false, 'btree'],
  ['identity_verification_attempts', 'uq_identity_verification_attempts_identity_verificatio_905f086b', ['identity_verification_case_id', 'attempt_number'], true, 'btree'],
  ['identity_verification_attempts', 'uq_identity_verification_attempts_idempotency', ['idempotency_key'], true, 'btree'],
  ['identity_verification_cases', 'ix_identity_verification_cases_subject_type_concept_id', ['subject_type_concept_id'], false, 'btree'],
  ['identity_verification_cases', 'ix_identity_verification_cases_identity_verification_policy_id', ['identity_verification_policy_id'], false, 'btree'],
  ['identity_verification_cases', 'ix_identity_verification_cases_requested_assurance_lev_ebd923e4', ['requested_assurance_level_concept_id'], false, 'btree'],
  ['identity_verification_cases', 'ix_identity_verification_cases_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['identity_verification_cases', 'ix_identity_verification_cases_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['identity_verification_cases', 'ix_identity_verification_cases_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['identity_verification_policies', 'uq_identity_verification_policies_policy_code', ['policy_code'], true, 'btree'],
  ['identity_verification_policies', 'ix_identity_verification_policies_subject_type_concept_id', ['subject_type_concept_id'], false, 'btree'],
  ['identity_verification_policies', 'ix_identity_verification_policies_transaction_risk_concept_id', ['transaction_risk_concept_id'], false, 'btree'],
  ['identity_verification_policies', 'ix_identity_verification_policies_required_identity_as_c2e6ce75', ['required_identity_assurance_level_concept_id'], false, 'btree'],
  ['identity_verification_policies', 'ix_identity_verification_policies_required_authenticat_2f8a398a', ['required_authenticator_assurance_level_concept_id'], false, 'btree'],
  ['identity_verification_policies', 'ix_identity_verification_policies_required_federation__a44c44f2', ['required_federation_assurance_level_concept_id'], false, 'btree'],
  ['identity_verification_policies', 'ix_identity_verification_policies_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['identity_verification_policies', 'ix_identity_verification_policies_created_by_user_id', ['created_by_user_id'], false, 'btree'],
];
