import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `integration_contracts`.
 * 52 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const integrationContractsIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['contract_webhook_subscriptions', 'ix_contract_webhook_subscriptions_integration_contract_id', ['integration_contract_id'], false, 'btree'],
  ['contract_webhook_subscriptions', 'ix_contract_webhook_subscriptions_event_type_concept_id', ['event_type_concept_id'], false, 'btree'],
  ['contract_webhook_subscriptions', 'ix_contract_webhook_subscriptions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['contract_webhook_subscriptions', 'ix_contract_webhook_subscriptions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['contract_webhook_subscriptions', 'ix_contract_webhook_subscriptions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['integration_auth_profiles', 'ix_integration_auth_profiles_integration_contract_id', ['integration_contract_id'], false, 'btree'],
  ['integration_auth_profiles', 'ix_integration_auth_profiles_auth_profile_concept_id', ['auth_profile_concept_id'], false, 'btree'],
  ['integration_auth_profiles', 'ix_integration_auth_profiles_token_binding_concept_id', ['token_binding_concept_id'], false, 'btree'],
  ['integration_auth_profiles', 'ix_integration_auth_profiles_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['integration_auth_profiles', 'ix_integration_auth_profiles_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['integration_auth_profiles', 'ix_integration_auth_profiles_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['integration_contract_versions', 'ix_integration_contract_versions_integration_contract_id', ['integration_contract_id'], false, 'btree'],
  ['integration_contract_versions', 'ix_integration_contract_versions_request_schema_file_id', ['request_schema_file_id'], false, 'btree'],
  ['integration_contract_versions', 'ix_integration_contract_versions_response_schema_file_id', ['response_schema_file_id'], false, 'btree'],
  ['integration_contract_versions', 'ix_integration_contract_versions_openapi_file_id', ['openapi_file_id'], false, 'btree'],
  ['integration_contract_versions', 'ix_integration_contract_versions_mapping_profile_id', ['mapping_profile_id'], false, 'btree'],
  ['integration_contract_versions', 'ix_integration_contract_versions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['integration_contract_versions', 'ix_integration_contract_versions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['integration_contract_versions', 'uq_integration_contract_versions_integration_contract__74f90c0c', ['integration_contract_id', 'version_number'], true, 'btree'],
  ['integration_contracts', 'ix_integration_contracts_external_provider_id', ['external_provider_id'], false, 'btree'],
  ['integration_contracts', 'ix_integration_contracts_capability_concept_id', ['capability_concept_id'], false, 'btree'],
  ['integration_contracts', 'ix_integration_contracts_data_classification_concept_id', ['data_classification_concept_id'], false, 'btree'],
  ['integration_contracts', 'ix_integration_contracts_legal_basis_concept_id', ['legal_basis_concept_id'], false, 'btree'],
  ['integration_contracts', 'ix_integration_contracts_allowed_purpose_value_set_id', ['allowed_purpose_value_set_id'], false, 'btree'],
  ['integration_contracts', 'ix_integration_contracts_data_use_agreement_id', ['data_use_agreement_id'], false, 'btree'],
  ['integration_contracts', 'ix_integration_contracts_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['integration_contracts', 'ix_integration_contracts_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['integration_contracts', 'ix_integration_contracts_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['integration_exchange_attempts', 'ix_integration_exchange_attempts_integration_exchange_record_id', ['integration_exchange_record_id'], false, 'btree'],
  ['integration_exchange_attempts', 'ix_integration_exchange_attempts_endpoint_id', ['endpoint_id'], false, 'btree'],
  ['integration_exchange_attempts', 'ix_integration_exchange_attempts_retry_decision_concept_id', ['retry_decision_concept_id'], false, 'btree'],
  ['integration_exchange_attempts', 'ix_integration_exchange_attempts_outcome_concept_id', ['outcome_concept_id'], false, 'btree'],
  ['integration_exchange_attempts', 'uq_integration_exchange_attempts_integration_exchange__2d126a36', ['integration_exchange_record_id', 'attempt_number'], true, 'btree'],
  ['integration_exchange_records', 'ix_integration_exchange_records_integration_contract_version_id', ['integration_contract_version_id'], false, 'btree'],
  ['integration_exchange_records', 'ix_integration_exchange_records_direction_concept_id', ['direction_concept_id'], false, 'btree'],
  ['integration_exchange_records', 'ix_integration_exchange_records_message_type_concept_id', ['message_type_concept_id'], false, 'btree'],
  ['integration_exchange_records', 'ix_integration_exchange_records_subject_type_concept_id', ['subject_type_concept_id'], false, 'btree'],
  ['integration_exchange_records', 'ix_integration_exchange_records_payload_file_id', ['payload_file_id'], false, 'btree'],
  ['integration_exchange_records', 'ix_integration_exchange_records_outcome_concept_id', ['outcome_concept_id'], false, 'btree'],
  ['integration_exchange_records', 'uq_integration_exchange_records_idempotency', ['idempotency_key'], true, 'btree'],
  ['integration_idempotency_records', 'ix_integration_idempotency_records_integration_contract_id', ['integration_contract_id'], false, 'btree'],
  ['integration_idempotency_records', 'ix_integration_idempotency_records_operation_concept_id', ['operation_concept_id'], false, 'btree'],
  ['integration_idempotency_records', 'ix_integration_idempotency_records_first_exchange_record_id', ['first_exchange_record_id'], false, 'btree'],
  ['integration_idempotency_records', 'ix_integration_idempotency_records_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['integration_idempotency_records', 'uq_integration_idempotency_records_idempotency', ['idempotency_key'], true, 'btree'],
  ['integration_sync_cursors', 'ix_integration_sync_cursors_integration_contract_id', ['integration_contract_id'], false, 'btree'],
  ['integration_sync_cursors', 'ix_integration_sync_cursors_last_successful_exchange_id', ['last_successful_exchange_id'], false, 'btree'],
  ['integration_sync_cursors', 'ix_integration_sync_cursors_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['webhook_delivery_evidence', 'ix_webhook_delivery_evidence_webhook_subscription_id', ['webhook_subscription_id'], false, 'btree'],
  ['webhook_delivery_evidence', 'ix_webhook_delivery_evidence_integration_exchange_record_id', ['integration_exchange_record_id'], false, 'btree'],
  ['webhook_delivery_evidence', 'ix_webhook_delivery_evidence_signature_verification_concept_id', ['signature_verification_concept_id'], false, 'btree'],
  ['webhook_delivery_evidence', 'ix_webhook_delivery_evidence_outcome_concept_id', ['outcome_concept_id'], false, 'btree'],
];
