import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `integrations`.
 * 55 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const integrationsIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['external_providers', 'uq_external_providers_code', ['code'], true, 'btree'],
  ['external_providers', 'ix_external_providers_provider_type_concept_id', ['provider_type_concept_id'], false, 'btree'],
  ['external_providers', 'ix_external_providers_auth_type_concept_id', ['auth_type_concept_id'], false, 'btree'],
  ['external_providers', 'ix_external_providers_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['external_providers', 'ix_external_providers_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['external_providers', 'ix_external_providers_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['inbound_messages', 'ix_inbound_messages_connection_id', ['connection_id'], false, 'btree'],
  ['inbound_messages', 'ix_inbound_messages_endpoint_id', ['endpoint_id'], false, 'btree'],
  ['inbound_messages', 'ix_inbound_messages_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['inbound_messages', 'ix_inbound_messages_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['inbound_messages', 'ix_inbound_messages_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['integration_endpoints', 'ix_integration_endpoints_provider_id', ['provider_id'], false, 'btree'],
  ['integration_endpoints', 'ix_integration_endpoints_http_method_concept_id', ['http_method_concept_id'], false, 'btree'],
  ['integration_endpoints', 'ix_integration_endpoints_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['integration_endpoints', 'ix_integration_endpoints_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['integration_endpoints', 'ix_integration_endpoints_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['integration_endpoints', 'uq_integration_endpoints_provider_id_version', ['provider_id', 'version'], true, 'btree'],
  ['integration_field_mappings', 'ix_integration_field_mappings_endpoint_id', ['endpoint_id'], false, 'btree'],
  ['integration_field_mappings', 'ix_integration_field_mappings_concept_map_id', ['concept_map_id'], false, 'btree'],
  ['integration_field_mappings', 'ix_integration_field_mappings_direction_concept_id', ['direction_concept_id'], false, 'btree'],
  ['integration_field_mappings', 'ix_integration_field_mappings_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['integration_field_mappings', 'ix_integration_field_mappings_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['message_responses', 'ix_message_responses_outbound_message_id', ['outbound_message_id'], false, 'btree'],
  ['message_responses', 'ix_message_responses_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['message_responses', 'ix_message_responses_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['message_retries', 'ix_message_retries_outbound_message_id', ['outbound_message_id'], false, 'btree'],
  ['message_retries', 'ix_message_retries_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['message_retries', 'ix_message_retries_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['message_retries', 'ix_message_retries_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['message_retries', 'uq_message_retries_outbound_message_id_attempt_number', ['outbound_message_id', 'attempt_number'], true, 'btree'],
  ['outbound_messages', 'uq_outbound_messages_idempotency_key', ['idempotency_key'], true, 'btree'],
  ['outbound_messages', 'ix_outbound_messages_connection_id', ['connection_id'], false, 'btree'],
  ['outbound_messages', 'ix_outbound_messages_endpoint_id', ['endpoint_id'], false, 'btree'],
  ['outbound_messages', 'ix_outbound_messages_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['outbound_messages', 'ix_outbound_messages_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['outbound_messages', 'ix_outbound_messages_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['provider_connections', 'ix_provider_connections_provider_id', ['provider_id'], false, 'btree'],
  ['provider_connections', 'ix_provider_connections_tenant_id', ['tenant_id'], false, 'btree'],
  ['provider_connections', 'ix_provider_connections_environment_concept_id', ['environment_concept_id'], false, 'btree'],
  ['provider_connections', 'ix_provider_connections_credential_id', ['credential_id'], false, 'btree'],
  ['provider_connections', 'ix_provider_connections_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['provider_connections', 'ix_provider_connections_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['provider_connections', 'ix_provider_connections_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['provider_connections', 'ix_provider_connections_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['provider_credentials', 'ix_provider_credentials_connection_id', ['connection_id'], false, 'btree'],
  ['provider_credentials', 'ix_provider_credentials_secret_type_concept_id', ['secret_type_concept_id'], false, 'btree'],
  ['provider_credentials', 'ix_provider_credentials_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['provider_credentials', 'ix_provider_credentials_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['provider_credentials', 'ix_provider_credentials_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['webhook_subscriptions', 'ix_webhook_subscriptions_provider_id', ['provider_id'], false, 'btree'],
  ['webhook_subscriptions', 'ix_webhook_subscriptions_tenant_id', ['tenant_id'], false, 'btree'],
  ['webhook_subscriptions', 'ix_webhook_subscriptions_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['webhook_subscriptions', 'ix_webhook_subscriptions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['webhook_subscriptions', 'ix_webhook_subscriptions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['webhook_subscriptions', 'ix_webhook_subscriptions_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
];
