import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `messaging`.
 * 102 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const messagingIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['dead_letter_jobs', 'ix_dead_letter_jobs_queue_id', ['queue_id'], false, 'btree'],
  ['dead_letter_jobs', 'ix_dead_letter_jobs_original_job_id', ['original_job_id'], false, 'btree'],
  ['dead_letter_jobs', 'ix_dead_letter_jobs_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['delivery_receipts', 'ix_delivery_receipts_delivery_id', ['delivery_id'], false, 'btree'],
  ['delivery_receipts', 'ix_delivery_receipts_receipt_type_concept_id', ['receipt_type_concept_id'], false, 'btree'],
  ['delivery_receipts', 'ix_delivery_receipts_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['domain_events', 'ix_domain_events_tenant_id', ['tenant_id'], false, 'btree'],
  ['domain_events', 'ix_domain_events_causation_id', ['causation_id'], false, 'btree'],
  ['domain_events', 'ix_domain_events_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['domain_events', 'ix_domain_events_tenant_id_recorded_at', ['tenant_id', 'recorded_at desc'], false, 'btree'],
  ['event_deliveries', 'ix_event_deliveries_domain_event_id', ['domain_event_id'], false, 'btree'],
  ['event_deliveries', 'ix_event_deliveries_subscription_id', ['subscription_id'], false, 'btree'],
  ['event_deliveries', 'ix_event_deliveries_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['event_deliveries', 'ix_event_deliveries_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['event_deliveries', 'uq_event_deliveries_domain_event_id_attempt_number', ['domain_event_id', 'attempt_number'], true, 'btree'],
  ['event_subscriptions', 'ix_event_subscriptions_tenant_id', ['tenant_id'], false, 'btree'],
  ['event_subscriptions', 'ix_event_subscriptions_delivery_mode_concept_id', ['delivery_mode_concept_id'], false, 'btree'],
  ['event_subscriptions', 'ix_event_subscriptions_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['event_subscriptions', 'ix_event_subscriptions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['event_subscriptions', 'ix_event_subscriptions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['event_subscriptions', 'ix_event_subscriptions_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['in_app_notifications', 'ix_in_app_notifications_recipient_user_id', ['recipient_user_id'], false, 'btree'],
  ['in_app_notifications', 'ix_in_app_notifications_tenant_id', ['tenant_id'], false, 'btree'],
  ['in_app_notifications', 'ix_in_app_notifications_channel_concept_id', ['channel_concept_id'], false, 'btree'],
  ['in_app_notifications', 'ix_in_app_notifications_category_concept_id', ['category_concept_id'], false, 'btree'],
  ['in_app_notifications', 'ix_in_app_notifications_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['in_app_notifications', 'ix_in_app_notifications_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['in_app_notifications', 'ix_in_app_notifications_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['in_app_notifications', 'ix_in_app_notifications_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['message_channels', 'uq_message_channels_code', ['code'], true, 'btree'],
  ['message_channels', 'ix_message_channels_channel_type_concept_id', ['channel_type_concept_id'], false, 'btree'],
  ['message_channels', 'ix_message_channels_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['message_channels', 'ix_message_channels_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['message_channels', 'ix_message_channels_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['message_queues', 'uq_message_queues_code', ['code'], true, 'btree'],
  ['message_queues', 'ix_message_queues_dead_letter_queue_id', ['dead_letter_queue_id'], false, 'btree'],
  ['message_queues', 'ix_message_queues_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['message_queues', 'ix_message_queues_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['message_queues', 'ix_message_queues_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['message_templates', 'ix_message_templates_tenant_id', ['tenant_id'], false, 'btree'],
  ['message_templates', 'ix_message_templates_channel_id', ['channel_id'], false, 'btree'],
  ['message_templates', 'ix_message_templates_language_concept_id', ['language_concept_id'], false, 'btree'],
  ['message_templates', 'ix_message_templates_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['message_templates', 'ix_message_templates_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['message_templates', 'ix_message_templates_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['message_templates', 'ix_message_templates_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['message_templates', 'uq_message_templates_channel_id_version', ['channel_id', 'version'], true, 'btree'],
  ['messaging_providers', 'uq_messaging_providers_code', ['code'], true, 'btree'],
  ['messaging_providers', 'ix_messaging_providers_provider_type_concept_id', ['provider_type_concept_id'], false, 'btree'],
  ['messaging_providers', 'ix_messaging_providers_external_provider_id', ['external_provider_id'], false, 'btree'],
  ['messaging_providers', 'ix_messaging_providers_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['messaging_providers', 'ix_messaging_providers_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['messaging_providers', 'ix_messaging_providers_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['notification_deliveries', 'ix_notification_deliveries_notification_request_id', ['notification_request_id'], false, 'btree'],
  ['notification_deliveries', 'ix_notification_deliveries_provider_id', ['provider_id'], false, 'btree'],
  ['notification_deliveries', 'ix_notification_deliveries_channel_id', ['channel_id'], false, 'btree'],
  ['notification_deliveries', 'ix_notification_deliveries_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['notification_deliveries', 'ix_notification_deliveries_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['notification_deliveries', 'ix_notification_deliveries_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['notification_deliveries', 'ix_notification_deliveries_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['notification_deliveries', 'uq_notification_deliveries_notification_request_id_att_f36b3e5c', ['notification_request_id', 'attempt_number'], true, 'btree'],
  ['notification_requests', 'ix_notification_requests_tenant_id', ['tenant_id'], false, 'btree'],
  ['notification_requests', 'ix_notification_requests_recipient_user_id', ['recipient_user_id'], false, 'btree'],
  ['notification_requests', 'ix_notification_requests_channel_id', ['channel_id'], false, 'btree'],
  ['notification_requests', 'ix_notification_requests_template_id', ['template_id'], false, 'btree'],
  ['notification_requests', 'ix_notification_requests_domain_event_id', ['domain_event_id'], false, 'btree'],
  ['notification_requests', 'ix_notification_requests_category_concept_id', ['category_concept_id'], false, 'btree'],
  ['notification_requests', 'ix_notification_requests_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['notification_requests', 'ix_notification_requests_consent_id', ['consent_id'], false, 'btree'],
  ['notification_requests', 'ix_notification_requests_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['notification_requests', 'ix_notification_requests_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['notification_requests', 'ix_notification_requests_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['outbox_messages', 'uq_outbox_messages_idempotency_key', ['idempotency_key'], true, 'btree'],
  ['outbox_messages', 'ix_outbox_messages_tenant_id', ['tenant_id'], false, 'btree'],
  ['outbox_messages', 'ix_outbox_messages_domain_event_id', ['domain_event_id'], false, 'btree'],
  ['outbox_messages', 'ix_outbox_messages_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['outbox_messages', 'ix_outbox_messages_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['outbox_messages', 'ix_outbox_messages_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['outbox_messages', 'ix_outbox_messages_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['provider_channel_configs', 'ix_provider_channel_configs_provider_id', ['provider_id'], false, 'btree'],
  ['provider_channel_configs', 'ix_provider_channel_configs_channel_id', ['channel_id'], false, 'btree'],
  ['provider_channel_configs', 'ix_provider_channel_configs_tenant_id', ['tenant_id'], false, 'btree'],
  ['provider_channel_configs', 'ix_provider_channel_configs_credential_id', ['credential_id'], false, 'btree'],
  ['provider_channel_configs', 'ix_provider_channel_configs_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['provider_channel_configs', 'ix_provider_channel_configs_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['provider_channel_configs', 'ix_provider_channel_configs_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['provider_channel_configs', 'ix_provider_channel_configs_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['queued_jobs', 'uq_queued_jobs_dedupe_key', ['dedupe_key'], true, 'btree'],
  ['queued_jobs', 'ix_queued_jobs_queue_id', ['queue_id'], false, 'btree'],
  ['queued_jobs', 'ix_queued_jobs_tenant_id', ['tenant_id'], false, 'btree'],
  ['queued_jobs', 'ix_queued_jobs_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['queued_jobs', 'ix_queued_jobs_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['queued_jobs', 'ix_queued_jobs_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['queued_jobs', 'ix_queued_jobs_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['recipient_preferences', 'ix_recipient_preferences_user_id', ['user_id'], false, 'btree'],
  ['recipient_preferences', 'ix_recipient_preferences_tenant_id', ['tenant_id'], false, 'btree'],
  ['recipient_preferences', 'ix_recipient_preferences_channel_id', ['channel_id'], false, 'btree'],
  ['recipient_preferences', 'ix_recipient_preferences_category_concept_id', ['category_concept_id'], false, 'btree'],
  ['recipient_preferences', 'ix_recipient_preferences_language_concept_id', ['language_concept_id'], false, 'btree'],
  ['recipient_preferences', 'ix_recipient_preferences_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['recipient_preferences', 'ix_recipient_preferences_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['recipient_preferences', 'ix_recipient_preferences_tenant_id_updated_at', ['tenant_id', 'updated_at desc'], false, 'btree'],
];
