import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `payments` (parte 1/3).
 * 180 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const paymentsIndexes1: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['callback_verification_runs', 'ix_callback_verification_runs_provider_callback_event_id', ['provider_callback_event_id'], false, 'btree'],
  ['callback_verification_runs', 'ix_callback_verification_runs_verification_method_concept_id', ['verification_method_concept_id'], false, 'btree'],
  ['callback_verification_runs', 'ix_callback_verification_runs_result_concept_id', ['result_concept_id'], false, 'btree'],
  ['callback_verification_runs', 'brin_callback_verification_runs_created_at', ['created_at'], false, 'brin'],
  ['cashier_payment_contexts', 'ix_cashier_payment_contexts_tenant_id', ['tenant_id'], false, 'btree'],
  ['cashier_payment_contexts', 'ix_cashier_payment_contexts_payment_checkout_session_id', ['payment_checkout_session_id'], false, 'btree'],
  ['cashier_payment_contexts', 'ix_cashier_payment_contexts_cashier_user_id', ['cashier_user_id'], false, 'btree'],
  ['cashier_payment_contexts', 'ix_cashier_payment_contexts_cash_register_id', ['cash_register_id'], false, 'btree'],
  ['cashier_payment_contexts', 'ix_cashier_payment_contexts_site_id', ['site_id'], false, 'btree'],
  ['cashier_payment_contexts', 'ix_cashier_payment_contexts_tenant_created', ['tenant_id', 'created_at desc'], false, 'btree'],
  ['cashier_payment_contexts', 'uk_cashier_payment_contexts_session', ['payment_checkout_session_id'], true, 'btree'],
  ['cash_registers', 'ix_cash_registers_tenant_id', ['tenant_id'], false, 'btree'],
  ['cash_registers', 'ix_cash_registers_care_space_id', ['care_space_id'], false, 'btree'],
  ['cash_registers', 'ix_cash_registers_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['cash_registers', 'brin_cash_registers_created_at', ['created_at'], false, 'brin'],
  ['connected_accounts', 'ix_connected_accounts_tenant_id', ['tenant_id'], false, 'btree'],
  ['connected_accounts', 'ix_connected_accounts_gateway_id', ['gateway_id'], false, 'btree'],
  ['connected_accounts', 'ix_connected_accounts_business_partner_id', ['business_partner_id'], false, 'btree'],
  ['connected_accounts', 'ix_connected_accounts_company_bank_account_id', ['company_bank_account_id'], false, 'btree'],
  ['connected_accounts', 'ix_connected_accounts_payee_type_concept_id', ['payee_type_concept_id'], false, 'btree'],
  ['connected_accounts', 'ix_connected_accounts_onboarding_status_concept_id', ['onboarding_status_concept_id'], false, 'btree'],
  ['connected_accounts', 'ix_connected_accounts_default_wallet_id', ['default_wallet_id'], false, 'btree'],
  ['connected_accounts', 'ix_connected_accounts_payout_schedule_concept_id', ['payout_schedule_concept_id'], false, 'btree'],
  ['connected_accounts', 'ix_connected_accounts_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['connected_accounts', 'ix_connected_accounts_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['connected_accounts', 'ix_connected_accounts_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['connected_accounts', 'ix_connected_accounts_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['fee_schedules', 'uq_fee_schedules_code', ['code'], true, 'btree'],
  ['fee_schedules', 'ix_fee_schedules_tenant_id', ['tenant_id'], false, 'btree'],
  ['fee_schedules', 'ix_fee_schedules_fee_type_concept_id', ['fee_type_concept_id'], false, 'btree'],
  ['fee_schedules', 'ix_fee_schedules_calculation_method_concept_id', ['calculation_method_concept_id'], false, 'btree'],
  ['fee_schedules', 'ix_fee_schedules_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['fee_schedules', 'ix_fee_schedules_applies_to_concept_id', ['applies_to_concept_id'], false, 'btree'],
  ['fee_schedules', 'ix_fee_schedules_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['fee_schedules', 'ix_fee_schedules_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['fee_schedules', 'ix_fee_schedules_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['fee_schedules', 'ix_fee_schedules_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['fx_rate_locks', 'ix_fx_rate_locks_payment_intent_id', ['payment_intent_id'], false, 'btree'],
  ['fx_rate_locks', 'ix_fx_rate_locks_from_currency_concept_id', ['from_currency_concept_id'], false, 'btree'],
  ['fx_rate_locks', 'ix_fx_rate_locks_to_currency_concept_id', ['to_currency_concept_id'], false, 'btree'],
  ['fx_rate_locks', 'ix_fx_rate_locks_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['fx_rate_locks', 'ix_fx_rate_locks_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['fx_rate_locks', 'ix_fx_rate_locks_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['gateway_connections', 'ix_gateway_connections_gateway_id', ['gateway_id'], false, 'btree'],
  ['gateway_connections', 'ix_gateway_connections_tenant_id', ['tenant_id'], false, 'btree'],
  ['gateway_connections', 'ix_gateway_connections_practice_id', ['practice_id'], false, 'btree'],
  ['gateway_connections', 'ix_gateway_connections_environment_concept_id', ['environment_concept_id'], false, 'btree'],
  ['gateway_connections', 'ix_gateway_connections_credential_id', ['credential_id'], false, 'btree'],
  ['gateway_connections', 'ix_gateway_connections_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['gateway_connections', 'ix_gateway_connections_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['gateway_connections', 'ix_gateway_connections_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['gateway_connections', 'ix_gateway_connections_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['gateway_payment_channel_mappings', 'ix_gateway_payment_channel_mappings_gateway_connection_id', ['gateway_connection_id'], false, 'btree'],
  ['gateway_payment_channel_mappings', 'ix_gateway_payment_channel_mappings_payment_channel_catalog_id', ['payment_channel_catalog_id'], false, 'btree'],
  ['gateway_payment_channel_mappings', 'ix_gateway_payment_channel_mappings_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['gateway_payment_channel_mappings', 'ix_gateway_payment_channel_mappings_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['gateway_payment_channel_mappings', 'ix_gateway_payment_channel_mappings_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['gateway_payment_channel_mappings', 'uk_gateway_channel_mapping', ['gateway_connection_id', 'payment_channel_catalog_id'], true, 'btree'],
  ['gateway_payment_channel_mappings', 'uk_gateway_external_channel', ['gateway_connection_id', 'external_channel_code'], true, 'btree'],
  ['gateway_settlements', 'uq_gateway_settlements_settlement_ref', ['settlement_ref'], true, 'btree'],
  ['gateway_settlements', 'ix_gateway_settlements_gateway_id', ['gateway_id'], false, 'btree'],
  ['gateway_settlements', 'ix_gateway_settlements_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['gateway_settlements', 'ix_gateway_settlements_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['gateway_settlements', 'ix_gateway_settlements_journal_transaction_id', ['journal_transaction_id'], false, 'btree'],
  ['gateway_settlements', 'ix_gateway_settlements_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['gateway_settlements', 'ix_gateway_settlements_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['installment_plans', 'ix_installment_plans_payment_intent_id', ['payment_intent_id'], false, 'btree'],
  ['installment_plans', 'ix_installment_plans_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['installment_plans', 'ix_installment_plans_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['installment_plans', 'ix_installment_plans_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['installment_plans', 'ix_installment_plans_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['installment_schedules', 'ix_installment_schedules_installment_plan_id', ['installment_plan_id'], false, 'btree'],
  ['installment_schedules', 'ix_installment_schedules_payment_transaction_id', ['payment_transaction_id'], false, 'btree'],
  ['installment_schedules', 'ix_installment_schedules_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['installment_schedules', 'ix_installment_schedules_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['installment_schedules', 'ix_installment_schedules_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['invoice_regeneration_requests', 'ix_invoice_regeneration_requests_tenant_id', ['tenant_id'], false, 'btree'],
  ['invoice_regeneration_requests', 'ix_invoice_regeneration_requests_gateway_connection_id', ['gateway_connection_id'], false, 'btree'],
  ['invoice_regeneration_requests', 'ix_invoice_regeneration_requests_payment_transaction_id', ['payment_transaction_id'], false, 'btree'],
  ['invoice_regeneration_requests', 'ix_invoice_regeneration_requests_payment_debt_id', ['payment_debt_id'], false, 'btree'],
  ['invoice_regeneration_requests', 'ix_invoice_regeneration_requests_requested_by_user_id', ['requested_by_user_id'], false, 'btree'],
  ['invoice_regeneration_requests', 'ix_invoice_regeneration_requests_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['invoice_regeneration_requests', 'ix_invoice_regeneration_requests_external_request_id', ['external_request_id'], false, 'btree'],
  ['invoice_regeneration_requests', 'ix_invoice_regeneration_requests_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['invoice_regeneration_requests', 'ix_invoice_regeneration_requests_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['invoice_regeneration_requests', 'ix_invoice_regeneration_requests_tenant_status', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['invoice_regeneration_requests', 'uk_invoice_regeneration_tenant_number', ['tenant_id', 'request_number'], true, 'btree'],
  ['kyc_verifications', 'ix_kyc_verifications_connected_account_id', ['connected_account_id'], false, 'btree'],
  ['kyc_verifications', 'ix_kyc_verifications_kyc_level_concept_id', ['kyc_level_concept_id'], false, 'btree'],
  ['kyc_verifications', 'ix_kyc_verifications_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['kyc_verifications', 'ix_kyc_verifications_risk_rating_concept_id', ['risk_rating_concept_id'], false, 'btree'],
  ['kyc_verifications', 'ix_kyc_verifications_evidence_file_id', ['evidence_file_id'], false, 'btree'],
  ['kyc_verifications', 'ix_kyc_verifications_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['kyc_verifications', 'ix_kyc_verifications_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['payment_cancellation_requests', 'ix_payment_cancellation_requests_tenant_id', ['tenant_id'], false, 'btree'],
  ['payment_cancellation_requests', 'ix_payment_cancellation_requests_gateway_connection_id', ['gateway_connection_id'], false, 'btree'],
  ['payment_cancellation_requests', 'ix_payment_cancellation_requests_payment_debt_id', ['payment_debt_id'], false, 'btree'],
  ['payment_cancellation_requests', 'ix_payment_cancellation_requests_payment_checkout_session_id', ['payment_checkout_session_id'], false, 'btree'],
  ['payment_cancellation_requests', 'ix_payment_cancellation_requests_payment_transaction_id', ['payment_transaction_id'], false, 'btree'],
  ['payment_cancellation_requests', 'ix_payment_cancellation_requests_reason_concept_id', ['reason_concept_id'], false, 'btree'],
  ['payment_cancellation_requests', 'ix_payment_cancellation_requests_requested_by_user_id', ['requested_by_user_id'], false, 'btree'],
  ['payment_cancellation_requests', 'ix_payment_cancellation_requests_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['payment_cancellation_requests', 'ix_payment_cancellation_requests_external_cancellation_id', ['external_cancellation_id'], false, 'btree'],
  ['payment_cancellation_requests', 'ix_payment_cancellation_requests_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['payment_cancellation_requests', 'ix_payment_cancellation_requests_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['payment_cancellation_requests', 'ix_payment_cancellation_requests_tenant_status', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['payment_cancellation_requests', 'uk_payment_cancellation_requests_tenant_number', ['tenant_id', 'request_number'], true, 'btree'],
  ['payment_channel_catalog', 'ix_payment_channel_catalog_channel_type_concept_id', ['channel_type_concept_id'], false, 'btree'],
  ['payment_channel_catalog', 'ix_payment_channel_catalog_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['payment_channel_catalog', 'ix_payment_channel_catalog_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['payment_channel_catalog', 'ix_payment_channel_catalog_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['payment_checkout_sessions', 'ix_payment_checkout_sessions_tenant_id', ['tenant_id'], false, 'btree'],
  ['payment_checkout_sessions', 'ix_payment_checkout_sessions_gateway_connection_id', ['gateway_connection_id'], false, 'btree'],
  ['payment_checkout_sessions', 'ix_payment_checkout_sessions_payment_debt_id', ['payment_debt_id'], false, 'btree'],
  ['payment_checkout_sessions', 'ix_payment_checkout_sessions_payment_intent_id', ['payment_intent_id'], false, 'btree'],
  ['payment_checkout_sessions', 'ix_payment_checkout_sessions_external_transaction_id', ['external_transaction_id'], false, 'btree'],
  ['payment_checkout_sessions', 'ix_payment_checkout_sessions_callback_endpoint_id', ['callback_endpoint_id'], false, 'btree'],
  ['payment_checkout_sessions', 'ix_payment_checkout_sessions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['payment_checkout_sessions', 'ix_payment_checkout_sessions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['payment_checkout_sessions', 'ix_payment_checkout_sessions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['payment_checkout_sessions', 'ix_payment_checkout_sessions_tenant_status', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['payment_checkout_sessions', 'uk_payment_checkout_sessions_token', ['session_token_hash'], true, 'btree'],
  ['payment_checkout_sessions', 'uk_payment_checkout_external_transaction', ['gateway_connection_id', 'external_transaction_id'], true, 'btree'],
  ['payment_debts', 'ix_payment_debts_tenant_id', ['tenant_id'], false, 'btree'],
  ['payment_debts', 'ix_payment_debts_gateway_connection_id', ['gateway_connection_id'], false, 'btree'],
  ['payment_debts', 'ix_payment_debts_debtor_business_partner_id', ['debtor_business_partner_id'], false, 'btree'],
  ['payment_debts', 'ix_payment_debts_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['payment_debts', 'ix_payment_debts_contract_id', ['contract_id'], false, 'btree'],
  ['payment_debts', 'ix_payment_debts_invoice_id', ['invoice_id'], false, 'btree'],
  ['payment_debts', 'ix_payment_debts_external_debt_id', ['external_debt_id'], false, 'btree'],
  ['payment_debts', 'ix_payment_debts_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['payment_debts', 'ix_payment_debts_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['payment_debts', 'ix_payment_debts_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['payment_debts', 'ix_payment_debts_tenant_status', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['payment_debts', 'uk_payment_debts_tenant_number', ['tenant_id', 'internal_debt_number'], true, 'btree'],
  ['payment_debts', 'uk_payment_debts_gateway_external', ['gateway_connection_id', 'external_debt_id'], true, 'btree'],
  ['payment_debts', 'ix_payment_debts_partner_status_due', ['debtor_business_partner_id', 'status_concept_id', 'due_at'], false, 'btree'],
  ['payment_debt_invoice_requests', 'ix_payment_debt_invoice_requests_payment_debt_id', ['payment_debt_id'], false, 'btree'],
  ['payment_debt_invoice_requests', 'ix_payment_debt_invoice_requests_requested_by_user_id', ['requested_by_user_id'], false, 'btree'],
  ['payment_debt_invoice_requests', 'ix_payment_debt_invoice_requests_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['payment_debt_invoice_requests', 'ix_payment_debt_invoice_requests_external_invoice_request_id', ['external_invoice_request_id'], false, 'btree'],
  ['payment_debt_invoice_requests', 'brin_payment_debt_invoice_requests_created_at', ['created_at'], false, 'brin'],
  ['payment_debt_invoice_requests', 'uk_debt_invoice_requests_debt_number', ['payment_debt_id', 'request_number'], true, 'btree'],
  ['payment_debt_lines', 'ix_payment_debt_lines_payment_debt_id', ['payment_debt_id'], false, 'btree'],
  ['payment_debt_lines', 'ix_payment_debt_lines_billable_item_type_concept_id', ['billable_item_type_concept_id'], false, 'btree'],
  ['payment_debt_lines', 'ix_payment_debt_lines_billable_item_id', ['billable_item_id'], false, 'btree'],
  ['payment_debt_lines', 'ix_payment_debt_lines_accounting_account_id', ['accounting_account_id'], false, 'btree'],
  ['payment_debt_lines', 'ix_payment_debt_lines_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['payment_debt_lines', 'ix_payment_debt_lines_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['payment_debt_lines', 'uk_payment_debt_lines_debt_line', ['payment_debt_id', 'line_number'], true, 'btree'],
  ['payment_disputes', 'ix_payment_disputes_payment_transaction_id', ['payment_transaction_id'], false, 'btree'],
  ['payment_disputes', 'ix_payment_disputes_dispute_type_concept_id', ['dispute_type_concept_id'], false, 'btree'],
  ['payment_disputes', 'ix_payment_disputes_reason_concept_id', ['reason_concept_id'], false, 'btree'],
  ['payment_disputes', 'ix_payment_disputes_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['payment_disputes', 'ix_payment_disputes_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['payment_disputes', 'ix_payment_disputes_evidence_file_id', ['evidence_file_id'], false, 'btree'],
  ['payment_disputes', 'ix_payment_disputes_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['payment_disputes', 'ix_payment_disputes_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['payment_gateways', 'uq_payment_gateways_code', ['code'], true, 'btree'],
  ['payment_gateways', 'ix_payment_gateways_gateway_type_concept_id', ['gateway_type_concept_id'], false, 'btree'],
  ['payment_gateways', 'ix_payment_gateways_external_provider_id', ['external_provider_id'], false, 'btree'],
  ['payment_gateways', 'ix_payment_gateways_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['payment_gateways', 'ix_payment_gateways_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['payment_gateways', 'ix_payment_gateways_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['payment_intents', 'uq_payment_intents_idempotency_key', ['idempotency_key'], true, 'btree'],
  ['payment_intents', 'ix_payment_intents_tenant_id', ['tenant_id'], false, 'btree'],
  ['payment_intents', 'ix_payment_intents_practice_id', ['practice_id'], false, 'btree'],
  ['payment_intents', 'ix_payment_intents_gateway_id', ['gateway_id'], false, 'btree'],
  ['payment_intents', 'ix_payment_intents_gateway_connection_id', ['gateway_connection_id'], false, 'btree'],
  ['payment_intents', 'ix_payment_intents_payment_method_id', ['payment_method_id'], false, 'btree'],
  ['payment_intents', 'ix_payment_intents_purpose_concept_id', ['purpose_concept_id'], false, 'btree'],
  ['payment_intents', 'ix_payment_intents_invoice_id', ['invoice_id'], false, 'btree'],
  ['payment_intents', 'ix_payment_intents_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['payment_intents', 'ix_payment_intents_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['payment_intents', 'ix_payment_intents_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['payment_intents', 'ix_payment_intents_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['payment_intents', 'ix_payment_intents_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['payment_mandates', 'uq_payment_mandates_mandate_ref', ['mandate_ref'], true, 'btree'],
  ['payment_mandates', 'ix_payment_mandates_tenant_id', ['tenant_id'], false, 'btree'],
  ['payment_mandates', 'ix_payment_mandates_payer_type_concept_id', ['payer_type_concept_id'], false, 'btree'],
];
