import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `payments` (parte 2/3).
 * 180 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const paymentsIndexes2: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['payment_mandates', 'ix_payment_mandates_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['payment_mandates', 'ix_payment_mandates_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['payment_mandates', 'ix_payment_mandates_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['payment_mandates', 'ix_payment_mandates_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['payment_methods', 'ix_payment_methods_tenant_id', ['tenant_id'], false, 'btree'],
  ['payment_methods', 'ix_payment_methods_owner_type_concept_id', ['owner_type_concept_id'], false, 'btree'],
  ['payment_methods', 'ix_payment_methods_gateway_id', ['gateway_id'], false, 'btree'],
  ['payment_methods', 'ix_payment_methods_method_type_concept_id', ['method_type_concept_id'], false, 'btree'],
  ['payment_methods', 'ix_payment_methods_billing_address_id', ['billing_address_id'], false, 'btree'],
  ['payment_methods', 'ix_payment_methods_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['payment_methods', 'ix_payment_methods_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['payment_methods', 'ix_payment_methods_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['payment_methods', 'ix_payment_methods_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['payment_receipts', 'ix_payment_receipts_tenant_id', ['tenant_id'], false, 'btree'],
  ['payment_receipts', 'ix_payment_receipts_payment_transaction_id', ['payment_transaction_id'], false, 'btree'],
  ['payment_receipts', 'ix_payment_receipts_payment_debt_id', ['payment_debt_id'], false, 'btree'],
  ['payment_receipts', 'ix_payment_receipts_payer_business_partner_id', ['payer_business_partner_id'], false, 'btree'],
  ['payment_receipts', 'ix_payment_receipts_file_id', ['file_id'], false, 'btree'],
  ['payment_receipts', 'ix_payment_receipts_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['payment_receipts', 'ix_payment_receipts_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['payment_receipts', 'ix_payment_receipts_tenant_created', ['tenant_id', 'created_at desc'], false, 'btree'],
  ['payment_receipts', 'uk_payment_receipts_tenant_number', ['tenant_id', 'receipt_number'], true, 'btree'],
  ['payment_receipts', 'uk_payment_receipts_transaction', ['payment_transaction_id'], true, 'btree'],
  ['payment_splits', 'ix_payment_splits_payment_intent_id', ['payment_intent_id'], false, 'btree'],
  ['payment_splits', 'ix_payment_splits_payee_connected_account_id', ['payee_connected_account_id'], false, 'btree'],
  ['payment_splits', 'ix_payment_splits_split_type_concept_id', ['split_type_concept_id'], false, 'btree'],
  ['payment_splits', 'ix_payment_splits_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['payment_splits', 'ix_payment_splits_destination_wallet_id', ['destination_wallet_id'], false, 'btree'],
  ['payment_splits', 'ix_payment_splits_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['payment_splits', 'ix_payment_splits_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['payment_splits', 'ix_payment_splits_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['payment_status_inquiries', 'ix_payment_status_inquiries_gateway_connection_id', ['gateway_connection_id'], false, 'btree'],
  ['payment_status_inquiries', 'ix_payment_status_inquiries_payment_debt_id', ['payment_debt_id'], false, 'btree'],
  ['payment_status_inquiries', 'ix_payment_status_inquiries_payment_checkout_session_id', ['payment_checkout_session_id'], false, 'btree'],
  ['payment_status_inquiries', 'ix_payment_status_inquiries_payment_transaction_id', ['payment_transaction_id'], false, 'btree'],
  ['payment_status_inquiries', 'ix_payment_status_inquiries_external_transaction_id', ['external_transaction_id'], false, 'btree'],
  ['payment_status_inquiries', 'ix_payment_status_inquiries_inquiry_reason_concept_id', ['inquiry_reason_concept_id'], false, 'btree'],
  ['payment_status_inquiries', 'ix_payment_status_inquiries_result_status_concept_id', ['result_status_concept_id'], false, 'btree'],
  ['payment_transactions', 'uq_payment_transactions_gateway_transaction_ref', ['gateway_transaction_ref'], true, 'btree'],
  ['payment_transactions', 'ix_payment_transactions_payment_intent_id', ['payment_intent_id'], false, 'btree'],
  ['payment_transactions', 'ix_payment_transactions_payer_business_partner_id', ['payer_business_partner_id'], false, 'btree'],
  ['payment_transactions', 'ix_payment_transactions_payee_business_partner_id', ['payee_business_partner_id'], false, 'btree'],
  ['payment_transactions', 'ix_payment_transactions_contract_id', ['contract_id'], false, 'btree'],
  ['payment_transactions', 'ix_payment_transactions_company_bank_account_id', ['company_bank_account_id'], false, 'btree'],
  ['payment_transactions', 'ix_payment_transactions_clearing_document_id', ['clearing_document_id'], false, 'btree'],
  ['payment_transactions', 'ix_payment_transactions_gateway_id', ['gateway_id'], false, 'btree'],
  ['payment_transactions', 'ix_payment_transactions_transaction_type_concept_id', ['transaction_type_concept_id'], false, 'btree'],
  ['payment_transactions', 'ix_payment_transactions_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['payment_transactions', 'ix_payment_transactions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['payment_transactions', 'ix_payment_transactions_failure_reason_concept_id', ['failure_reason_concept_id'], false, 'btree'],
  ['payment_transactions', 'ix_payment_transactions_journal_transaction_id', ['journal_transaction_id'], false, 'btree'],
  ['payment_transactions', 'ix_payment_transactions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['payment_transactions', 'ix_payment_transactions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['payment_webhook_events', 'uq_payment_webhook_events_gateway_event_ref', ['gateway_event_ref'], true, 'btree'],
  ['payment_webhook_events', 'ix_payment_webhook_events_gateway_id', ['gateway_id'], false, 'btree'],
  ['payment_webhook_events', 'ix_payment_webhook_events_gateway_connection_id', ['gateway_connection_id'], false, 'btree'],
  ['payment_webhook_events', 'ix_payment_webhook_events_related_intent_id', ['related_intent_id'], false, 'btree'],
  ['payment_webhook_events', 'ix_payment_webhook_events_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['payout_items', 'ix_payout_items_payout_id', ['payout_id'], false, 'btree'],
  ['payout_items', 'ix_payout_items_source_type_concept_id', ['source_type_concept_id'], false, 'btree'],
  ['payout_items', 'ix_payout_items_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['payout_items', 'ix_payout_items_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['payouts', 'ix_payouts_tenant_id', ['tenant_id'], false, 'btree'],
  ['payouts', 'ix_payouts_practice_id', ['practice_id'], false, 'btree'],
  ['payouts', 'ix_payouts_payee_type_concept_id', ['payee_type_concept_id'], false, 'btree'],
  ['payouts', 'ix_payouts_gateway_id', ['gateway_id'], false, 'btree'],
  ['payouts', 'ix_payouts_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['payouts', 'ix_payouts_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['payouts', 'ix_payouts_journal_transaction_id', ['journal_transaction_id'], false, 'btree'],
  ['payouts', 'ix_payouts_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['payouts', 'ix_payouts_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['payouts', 'ix_payouts_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['plan_eligibility_rules', 'ix_plan_eligibility_rules_plan_id', ['plan_id'], false, 'btree'],
  ['plan_eligibility_rules', 'ix_plan_eligibility_rules_practice_type', ['eligible_practice_type_concept_id'], false, 'btree'],
  ['plan_eligibility_rules', 'uk_plan_eligibility_rules_plan_type', ['plan_id', 'eligible_practice_type_concept_id'], true, 'btree'],
  ['plan_features', 'ix_plan_features_plan_id', ['plan_id'], false, 'btree'],
  ['plan_features', 'ix_plan_features_feature_concept_id', ['feature_concept_id'], false, 'btree'],
  ['plan_features', 'uk_plan_features_plan_feature', ['plan_id', 'feature_concept_id'], true, 'btree'],
  ['plan_prices', 'ix_plan_prices_plan_id', ['plan_id'], false, 'btree'],
  ['plan_prices', 'ix_plan_prices_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['plan_prices', 'uk_plan_prices_plan_currency_interval', ['plan_id', 'currency_concept_id', 'billing_interval_concept_id', 'region_concept_id'], true, 'btree'],
  ['plan_quotas', 'ix_plan_quotas_plan_id', ['plan_id'], false, 'btree'],
  ['plan_quotas', 'ix_plan_quotas_metric_concept_id', ['metric_concept_id'], false, 'btree'],
  ['plan_quotas', 'uk_plan_quotas_plan_metric', ['plan_id', 'metric_concept_id'], true, 'btree'],
  ['provider_api_attempts', 'ix_provider_api_attempts_provider_api_operation_id', ['provider_api_operation_id'], false, 'btree'],
  ['provider_api_attempts', 'ix_provider_api_attempts_payment_debt_id', ['payment_debt_id'], false, 'btree'],
  ['provider_api_attempts', 'ix_provider_api_attempts_payment_checkout_session_id', ['payment_checkout_session_id'], false, 'btree'],
  ['provider_api_attempts', 'ix_provider_api_attempts_payment_transaction_id', ['payment_transaction_id'], false, 'btree'],
  ['provider_api_attempts', 'ix_provider_api_attempts_correlation_id', ['correlation_id'], false, 'btree'],
  ['provider_api_attempts', 'ix_provider_api_attempts_result_concept_id', ['result_concept_id'], false, 'btree'],
  ['provider_api_attempts', 'uk_provider_api_attempts_operation_correlation_attempt', ['provider_api_operation_id', 'correlation_id', 'attempt_number'], true, 'btree'],
  ['provider_api_operations', 'ix_provider_api_operations_gateway_connection_id', ['gateway_connection_id'], false, 'btree'],
  ['provider_api_operations', 'ix_provider_api_operations_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['provider_api_operations', 'ix_provider_api_operations_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['provider_api_operations', 'ix_provider_api_operations_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['provider_api_operations', 'uk_provider_api_operations_connection_code', ['gateway_connection_id', 'operation_code'], true, 'btree'],
  ['provider_callback_endpoints', 'ix_provider_callback_endpoints_gateway_connection_id', ['gateway_connection_id'], false, 'btree'],
  ['provider_callback_endpoints', 'ix_provider_callback_endpoints_verification_method_concept_id', ['verification_method_concept_id'], false, 'btree'],
  ['provider_callback_endpoints', 'ix_provider_callback_endpoints_verification_secret_id', ['verification_secret_id'], false, 'btree'],
  ['provider_callback_endpoints', 'ix_provider_callback_endpoints_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['provider_callback_endpoints', 'ix_provider_callback_endpoints_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['provider_callback_endpoints', 'ix_provider_callback_endpoints_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['provider_callback_endpoints', 'uk_provider_callback_endpoints_connection_code', ['gateway_connection_id', 'code'], true, 'btree'],
  ['provider_callback_endpoints', 'uk_provider_callback_endpoints_path', ['callback_path'], true, 'btree'],
  ['provider_callback_events', 'ix_provider_callback_events_provider_callback_endpoint_id', ['provider_callback_endpoint_id'], false, 'btree'],
  ['provider_callback_events', 'ix_provider_callback_events_payment_checkout_session_id', ['payment_checkout_session_id'], false, 'btree'],
  ['provider_callback_events', 'ix_provider_callback_events_payment_transaction_id', ['payment_transaction_id'], false, 'btree'],
  ['provider_callback_events', 'ix_provider_callback_events_external_event_id', ['external_event_id'], false, 'btree'],
  ['provider_callback_events', 'ix_provider_callback_events_external_transaction_id', ['external_transaction_id'], false, 'btree'],
  ['provider_callback_events', 'ix_provider_callback_events_verification_status_concept_id', ['verification_status_concept_id'], false, 'btree'],
  ['provider_callback_events', 'ix_provider_callback_events_processing_status_concept_id', ['processing_status_concept_id'], false, 'btree'],
  ['provider_callback_events', 'ix_provider_callback_events_duplicate_of_event_id', ['duplicate_of_event_id'], false, 'btree'],
  ['provider_callback_events', 'uk_provider_callback_external_event', ['provider_callback_endpoint_id', 'external_event_id'], true, 'btree'],
  ['provider_callback_events', 'ix_provider_callback_external_transaction', ['provider_callback_endpoint_id', 'external_transaction_id', 'received_at desc'], false, 'btree'],
  ['provider_invoice_artifacts', 'ix_provider_invoice_artifacts_gateway_connection_id', ['gateway_connection_id'], false, 'btree'],
  ['provider_invoice_artifacts', 'ix_provider_invoice_artifacts_payment_transaction_id', ['payment_transaction_id'], false, 'btree'],
  ['provider_invoice_artifacts', 'ix_provider_invoice_artifacts_invoice_regeneration_request_id', ['invoice_regeneration_request_id'], false, 'btree'],
  ['provider_invoice_artifacts', 'ix_provider_invoice_artifacts_artifact_type_concept_id', ['artifact_type_concept_id'], false, 'btree'],
  ['provider_invoice_artifacts', 'ix_provider_invoice_artifacts_external_invoice_id', ['external_invoice_id'], false, 'btree'],
  ['provider_invoice_artifacts', 'ix_provider_invoice_artifacts_file_id', ['file_id'], false, 'btree'],
  ['provider_invoice_artifacts', 'ix_provider_invoice_artifacts_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['provider_invoice_artifacts', 'ix_provider_invoice_artifacts_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['provider_invoice_artifacts', 'ix_provider_invoice_artifacts_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['provider_invoice_artifacts', 'uk_provider_invoice_artifacts_external', ['gateway_connection_id', 'external_invoice_id', 'artifact_type_concept_id'], true, 'btree'],
  ['provider_reconciliation_records', 'ix_provider_reconciliation_records_gateway_connection_id', ['gateway_connection_id'], false, 'btree'],
  ['provider_reconciliation_records', 'ix_provider_reconciliation_records_reconciliation_run_id', ['reconciliation_run_id'], false, 'btree'],
  ['provider_reconciliation_records', 'ix_provider_reconciliation_records_payment_debt_id', ['payment_debt_id'], false, 'btree'],
  ['provider_reconciliation_records', 'ix_provider_reconciliation_records_payment_transaction_id', ['payment_transaction_id'], false, 'btree'],
  ['provider_reconciliation_records', 'ix_provider_reconciliation_records_external_transaction_id', ['external_transaction_id'], false, 'btree'],
  ['provider_reconciliation_records', 'ix_provider_reconciliation_records_match_status_concept_id', ['match_status_concept_id'], false, 'btree'],
  ['provider_reconciliation_records', 'ix_provider_reconciliation_records_mismatch_reason_concept_id', ['mismatch_reason_concept_id'], false, 'btree'],
  ['provider_reconciliation_records', 'uk_provider_reconciliation_connection_external_run', ['gateway_connection_id', 'external_transaction_id', 'reconciliation_run_id'], true, 'btree'],
  ['reconciliation_exceptions', 'ix_reconciliation_exceptions_reconciliation_run_id', ['reconciliation_run_id'], false, 'btree'],
  ['reconciliation_exceptions', 'ix_reconciliation_exceptions_exception_type_concept_id', ['exception_type_concept_id'], false, 'btree'],
  ['reconciliation_exceptions', 'ix_reconciliation_exceptions_payment_transaction_id', ['payment_transaction_id'], false, 'btree'],
  ['reconciliation_exceptions', 'ix_reconciliation_exceptions_wallet_ledger_entry_id', ['wallet_ledger_entry_id'], false, 'btree'],
  ['reconciliation_exceptions', 'ix_reconciliation_exceptions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['reconciliation_exceptions', 'ix_reconciliation_exceptions_resolved_by_user_id', ['resolved_by_user_id'], false, 'btree'],
  ['reconciliation_exceptions', 'ix_reconciliation_exceptions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['reconciliation_exceptions', 'ix_reconciliation_exceptions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['reconciliation_runs', 'ix_reconciliation_runs_tenant_id', ['tenant_id'], false, 'btree'],
  ['reconciliation_runs', 'ix_reconciliation_runs_gateway_id', ['gateway_id'], false, 'btree'],
  ['reconciliation_runs', 'ix_reconciliation_runs_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['reconciliation_runs', 'ix_reconciliation_runs_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['reconciliation_runs', 'ix_reconciliation_runs_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['reconciliation_runs', 'ix_reconciliation_runs_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['refunds', 'ix_refunds_payment_transaction_id', ['payment_transaction_id'], false, 'btree'],
  ['refunds', 'ix_refunds_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['refunds', 'ix_refunds_reason_concept_id', ['reason_concept_id'], false, 'btree'],
  ['refunds', 'ix_refunds_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['refunds', 'ix_refunds_journal_transaction_id', ['journal_transaction_id'], false, 'btree'],
  ['refunds', 'ix_refunds_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['refunds', 'ix_refunds_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['risk_assessments', 'ix_risk_assessments_payment_intent_id', ['payment_intent_id'], false, 'btree'],
  ['risk_assessments', 'ix_risk_assessments_risk_level_concept_id', ['risk_level_concept_id'], false, 'btree'],
  ['risk_assessments', 'ix_risk_assessments_decision_concept_id', ['decision_concept_id'], false, 'btree'],
  ['risk_assessments', 'ix_risk_assessments_three_ds_status_concept_id', ['three_ds_status_concept_id'], false, 'btree'],
  ['risk_assessments', 'ix_risk_assessments_reviewed_by_user_id', ['reviewed_by_user_id'], false, 'btree'],
  ['risk_assessments', 'ix_risk_assessments_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['risk_assessments', 'ix_risk_assessments_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['settlement_lines', 'ix_settlement_lines_settlement_id', ['settlement_id'], false, 'btree'],
  ['settlement_lines', 'ix_settlement_lines_payment_transaction_id', ['payment_transaction_id'], false, 'btree'],
  ['settlement_lines', 'ix_settlement_lines_refund_id', ['refund_id'], false, 'btree'],
  ['settlement_lines', 'ix_settlement_lines_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['settlement_lines', 'ix_settlement_lines_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['subscription_plans', 'uq_subscription_plans_code', ['code'], true, 'btree'],
  ['subscription_plans', 'ix_subscription_plans_tenant_id', ['tenant_id'], false, 'btree'],
  ['subscription_plans', 'ix_subscription_plans_practice_id', ['practice_id'], false, 'btree'],
  ['subscription_plans', 'ix_subscription_plans_billing_interval_concept_id', ['billing_interval_concept_id'], false, 'btree'],
  ['subscription_plans', 'ix_subscription_plans_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['subscription_plans', 'ix_subscription_plans_usage_type_concept_id', ['usage_type_concept_id'], false, 'btree'],
  ['subscription_plans', 'ix_subscription_plans_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['subscription_plans', 'ix_subscription_plans_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['subscription_plans', 'ix_subscription_plans_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['subscription_plans', 'ix_subscription_plans_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['subscription_usage_counters', 'ix_subscription_usage_counters_subscription_id', ['subscription_id'], false, 'btree'],
  ['subscription_usage_counters', 'ix_subscription_usage_counters_metric_concept_id', ['metric_concept_id'], false, 'btree'],
  ['subscription_usage_counters', 'uk_subscription_usage_counters_period', ['subscription_id', 'metric_concept_id', 'period_start'], true, 'btree'],
  ['subscriptions', 'ix_subscriptions_tenant_id', ['tenant_id'], false, 'btree'],
  ['subscriptions', 'ix_subscriptions_plan_id', ['plan_id'], false, 'btree'],
];
