import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `pharmacy`.
 * 68 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const pharmacyIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['pharmacies', 'uq_pharmacies_tenant_id', ['tenant_id'], true, 'btree'],
  ['pharmacies', 'uq_pharmacies_code', ['code'], true, 'btree'],
  ['pharmacies', 'ix_pharmacies_tenant_id', ['tenant_id'], false, 'btree'],
  ['pharmacies', 'ix_pharmacies_pharmacy_type_concept_id', ['pharmacy_type_concept_id'], false, 'btree'],
  ['pharmacies', 'ix_pharmacies_ownership_type_concept_id', ['ownership_type_concept_id'], false, 'btree'],
  ['pharmacies', 'ix_pharmacies_public_profile_id', ['public_profile_id'], false, 'btree'],
  ['pharmacies', 'ix_pharmacies_default_currency_concept_id', ['default_currency_concept_id'], false, 'btree'],
  ['pharmacies', 'ix_pharmacies_verification_status_concept_id', ['verification_status_concept_id'], false, 'btree'],
  ['pharmacies', 'ix_pharmacies_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['pharmacies', 'ix_pharmacies_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['pharmacies', 'ix_pharmacies_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['pharmacies', 'ix_pharmacies_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['pharmacy_external_product_mappings', 'ix_pharmacy_external_product_mappings_pharmacy_integra_f6b3c236', ['pharmacy_integration_connection_id'], false, 'btree'],
  ['pharmacy_external_product_mappings', 'ix_pharmacy_external_product_mappings_pharmacy_product_id', ['pharmacy_product_id'], false, 'btree'],
  ['pharmacy_external_product_mappings', 'ix_pharmacy_external_product_mappings_verification_sta_079f1a0f', ['verification_status_concept_id'], false, 'btree'],
  ['pharmacy_external_product_mappings', 'ix_pharmacy_external_product_mappings_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['pharmacy_external_product_mappings', 'ix_pharmacy_external_product_mappings_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['pharmacy_integration_connections', 'ix_pharmacy_integration_connections_pharmacy_id', ['pharmacy_id'], false, 'btree'],
  ['pharmacy_integration_connections', 'ix_pharmacy_integration_connections_pharmacy_site_id', ['pharmacy_site_id'], false, 'btree'],
  ['pharmacy_integration_connections', 'ix_pharmacy_integration_connections_connection_id', ['connection_id'], false, 'btree'],
  ['pharmacy_integration_connections', 'ix_pharmacy_integration_connections_integration_mode_concept_id', ['integration_mode_concept_id'], false, 'btree'],
  ['pharmacy_integration_connections', 'ix_pharmacy_integration_connections_inventory_authorit_20c81904', ['inventory_authority_concept_id'], false, 'btree'],
  ['pharmacy_integration_connections', 'ix_pharmacy_integration_connections_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['pharmacy_integration_connections', 'ix_pharmacy_integration_connections_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['pharmacy_integration_connections', 'ix_pharmacy_integration_connections_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['pharmacy_licenses', 'ix_pharmacy_licenses_pharmacy_id', ['pharmacy_id'], false, 'btree'],
  ['pharmacy_licenses', 'ix_pharmacy_licenses_pharmacy_site_id', ['pharmacy_site_id'], false, 'btree'],
  ['pharmacy_licenses', 'ix_pharmacy_licenses_license_type_concept_id', ['license_type_concept_id'], false, 'btree'],
  ['pharmacy_licenses', 'ix_pharmacy_licenses_issuing_authority_tenant_id', ['issuing_authority_tenant_id'], false, 'btree'],
  ['pharmacy_licenses', 'ix_pharmacy_licenses_jurisdiction_concept_id', ['jurisdiction_concept_id'], false, 'btree'],
  ['pharmacy_licenses', 'ix_pharmacy_licenses_evidence_file_id', ['evidence_file_id'], false, 'btree'],
  ['pharmacy_licenses', 'ix_pharmacy_licenses_verification_status_concept_id', ['verification_status_concept_id'], false, 'btree'],
  ['pharmacy_licenses', 'ix_pharmacy_licenses_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['pharmacy_licenses', 'ix_pharmacy_licenses_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['pharmacy_price_lists', 'ix_pharmacy_price_lists_pharmacy_id', ['pharmacy_id'], false, 'btree'],
  ['pharmacy_price_lists', 'ix_pharmacy_price_lists_pharmacy_site_id', ['pharmacy_site_id'], false, 'btree'],
  ['pharmacy_price_lists', 'ix_pharmacy_price_lists_price_list_type_concept_id', ['price_list_type_concept_id'], false, 'btree'],
  ['pharmacy_price_lists', 'ix_pharmacy_price_lists_insurer_tenant_id', ['insurer_tenant_id'], false, 'btree'],
  ['pharmacy_price_lists', 'ix_pharmacy_price_lists_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['pharmacy_price_lists', 'ix_pharmacy_price_lists_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['pharmacy_price_lists', 'ix_pharmacy_price_lists_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['pharmacy_price_lists', 'ix_pharmacy_price_lists_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['pharmacy_products', 'ix_pharmacy_products_pharmacy_id', ['pharmacy_id'], false, 'btree'],
  ['pharmacy_products', 'ix_pharmacy_products_medication_concept_id', ['medication_concept_id'], false, 'btree'],
  ['pharmacy_products', 'ix_pharmacy_products_inventory_item_concept_id', ['inventory_item_concept_id'], false, 'btree'],
  ['pharmacy_products', 'ix_pharmacy_products_manufacturer_tenant_id', ['manufacturer_tenant_id'], false, 'btree'],
  ['pharmacy_products', 'ix_pharmacy_products_dosage_form_concept_id', ['dosage_form_concept_id'], false, 'btree'],
  ['pharmacy_products', 'ix_pharmacy_products_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['pharmacy_products', 'ix_pharmacy_products_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['pharmacy_products', 'ix_pharmacy_products_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['pharmacy_product_identifiers', 'ix_pharmacy_product_identifiers_pharmacy_product_id', ['pharmacy_product_id'], false, 'btree'],
  ['pharmacy_product_identifiers', 'ix_pharmacy_product_identifiers_identifier_type_concept_id', ['identifier_type_concept_id'], false, 'btree'],
  ['pharmacy_product_identifiers', 'ix_pharmacy_product_identifiers_assigning_authority_tenant_id', ['assigning_authority_tenant_id'], false, 'btree'],
  ['pharmacy_product_identifiers', 'ix_pharmacy_product_identifiers_jurisdiction_concept_id', ['jurisdiction_concept_id'], false, 'btree'],
  ['pharmacy_product_identifiers', 'ix_pharmacy_product_identifiers_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['pharmacy_product_prices', 'ix_pharmacy_product_prices_pharmacy_price_list_id', ['pharmacy_price_list_id'], false, 'btree'],
  ['pharmacy_product_prices', 'ix_pharmacy_product_prices_pharmacy_product_id', ['pharmacy_product_id'], false, 'btree'],
  ['pharmacy_product_prices', 'ix_pharmacy_product_prices_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['pharmacy_product_prices', 'ix_pharmacy_product_prices_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['pharmacy_product_prices', 'uq_pharmacy_product_prices_pharmacy_price_list_id_vers_7ebb36be', ['pharmacy_price_list_id', 'version_number'], true, 'btree'],
  ['pharmacy_sites', 'ix_pharmacy_sites_pharmacy_id', ['pharmacy_id'], false, 'btree'],
  ['pharmacy_sites', 'ix_pharmacy_sites_practice_site_id', ['practice_site_id'], false, 'btree'],
  ['pharmacy_sites', 'ix_pharmacy_sites_pharmacy_site_type_concept_id', ['pharmacy_site_type_concept_id'], false, 'btree'],
  ['pharmacy_sites', 'ix_pharmacy_sites_dispensing_mode_concept_id', ['dispensing_mode_concept_id'], false, 'btree'],
  ['pharmacy_sites', 'ix_pharmacy_sites_controlled_substance_capability_concept_id', ['controlled_substance_capability_concept_id'], false, 'btree'],
  ['pharmacy_sites', 'ix_pharmacy_sites_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['pharmacy_sites', 'ix_pharmacy_sites_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['pharmacy_sites', 'ix_pharmacy_sites_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
];
