import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `platform_ops` (parte 2/2).
 * 74 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const platformOpsIndexes2: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['recovery_objectives', 'ix_recovery_objectives_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['resilience_exercises', 'ix_resilience_exercises_tenant_id', ['tenant_id'], false, 'btree'],
  ['resilience_exercises', 'ix_resilience_exercises_service_component_id', ['service_component_id'], false, 'btree'],
  ['resilience_exercises', 'ix_resilience_exercises_exercise_type_concept_id', ['exercise_type_concept_id'], false, 'btree'],
  ['resilience_exercises', 'ix_resilience_exercises_result_concept_id', ['result_concept_id'], false, 'btree'],
  ['resilience_exercises', 'ix_resilience_exercises_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['resilience_exercises', 'ix_resilience_exercises_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['resilience_exercises', 'ix_resilience_exercises_tenant_created', ['tenant_id', 'created_at desc'], false, 'btree'],
  ['runbook_executions', 'ix_runbook_executions_runbook_version_id', ['runbook_version_id'], false, 'btree'],
  ['runbook_executions', 'ix_runbook_executions_health_incident_id', ['health_incident_id'], false, 'btree'],
  ['runbook_executions', 'ix_runbook_executions_change_request_id', ['change_request_id'], false, 'btree'],
  ['runbook_executions', 'ix_runbook_executions_execution_mode_concept_id', ['execution_mode_concept_id'], false, 'btree'],
  ['runbook_executions', 'ix_runbook_executions_result_concept_id', ['result_concept_id'], false, 'btree'],
  ['runbook_executions', 'ix_runbook_executions_initiated_by_user_id', ['initiated_by_user_id'], false, 'btree'],
  ['runbook_versions', 'ix_runbook_versions_runbook_id', ['runbook_id'], false, 'btree'],
  ['runbook_versions', 'ix_runbook_versions_approved_by_user_id', ['approved_by_user_id'], false, 'btree'],
  ['runbook_versions', 'uk_runbook_versions_runbook_version', ['runbook_id', 'version_number'], true, 'btree'],
  ['runbooks', 'ix_runbooks_tenant_id', ['tenant_id'], false, 'btree'],
  ['runbooks', 'ix_runbooks_service_component_id', ['service_component_id'], false, 'btree'],
  ['runbooks', 'ix_runbooks_runbook_type_concept_id', ['runbook_type_concept_id'], false, 'btree'],
  ['runbooks', 'ix_runbooks_current_version_id', ['current_version_id'], false, 'btree'],
  ['runbooks', 'ix_runbooks_owner_team_id', ['owner_team_id'], false, 'btree'],
  ['runbooks', 'ix_runbooks_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['runbooks', 'ix_runbooks_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['runbooks', 'ix_runbooks_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['runbooks', 'ix_runbooks_tenant_created', ['tenant_id', 'created_at desc'], false, 'btree'],
  ['runbooks', 'uk_runbooks_service_code', ['service_component_id', 'code'], true, 'btree'],
  ['service_components', 'uq_service_components_code', ['code'], true, 'btree'],
  ['service_components', 'ix_service_components_tenant_id', ['tenant_id'], false, 'btree'],
  ['service_components', 'ix_service_components_component_type_concept_id', ['component_type_concept_id'], false, 'btree'],
  ['service_components', 'ix_service_components_criticality_concept_id', ['criticality_concept_id'], false, 'btree'],
  ['service_components', 'ix_service_components_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['service_components', 'ix_service_components_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['service_components', 'ix_service_components_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['service_components', 'ix_service_components_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['service_dependencies', 'ix_service_dependencies_upstream_service_component_id', ['upstream_service_component_id'], false, 'btree'],
  ['service_dependencies', 'ix_service_dependencies_downstream_service_component_id', ['downstream_service_component_id'], false, 'btree'],
  ['service_dependencies', 'ix_service_dependencies_dependency_type_concept_id', ['dependency_type_concept_id'], false, 'btree'],
  ['service_dependencies', 'ix_service_dependencies_criticality_concept_id', ['criticality_concept_id'], false, 'btree'],
  ['service_dependencies', 'ix_service_dependencies_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['service_dependencies', 'ix_service_dependencies_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['service_dependencies', 'ix_service_dependencies_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['service_dependencies', 'uk_service_dependencies_pair_type', ['upstream_service_component_id', 'downstream_service_component_id', 'dependency_type_concept_id'], true, 'btree'],
  ['service_level_indicators', 'ix_service_level_indicators_service_component_id', ['service_component_id'], false, 'btree'],
  ['service_level_indicators', 'ix_service_level_indicators_indicator_type_concept_id', ['indicator_type_concept_id'], false, 'btree'],
  ['service_level_indicators', 'ix_service_level_indicators_unit_concept_id', ['unit_concept_id'], false, 'btree'],
  ['service_level_indicators', 'ix_service_level_indicators_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['service_level_indicators', 'ix_service_level_indicators_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['service_level_indicators', 'ix_service_level_indicators_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['service_level_indicators', 'uk_service_level_indicators_service_code', ['service_component_id', 'code'], true, 'btree'],
  ['service_level_objectives', 'ix_service_level_objectives_service_level_indicator_id', ['service_level_indicator_id'], false, 'btree'],
  ['service_level_objectives', 'ix_service_level_objectives_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['service_level_objectives', 'ix_service_level_objectives_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['service_level_objectives', 'ix_service_level_objectives_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['service_level_objectives', 'uk_service_level_objectives_indicator_code', ['service_level_indicator_id', 'code', 'effective_from'], true, 'btree'],
  ['service_ownerships', 'ix_service_ownerships_service_component_id', ['service_component_id'], false, 'btree'],
  ['service_ownerships', 'ix_service_ownerships_operational_team_id', ['operational_team_id'], false, 'btree'],
  ['service_ownerships', 'ix_service_ownerships_ownership_role_concept_id', ['ownership_role_concept_id'], false, 'btree'],
  ['service_ownerships', 'ix_service_ownerships_escalation_policy_id', ['escalation_policy_id'], false, 'btree'],
  ['service_ownerships', 'ix_service_ownerships_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['service_ownerships', 'ix_service_ownerships_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['service_ownerships', 'ix_service_ownerships_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['service_ownerships', 'ix_service_ownerships_active', ['service_component_id', 'ownership_role_concept_id', 'effective_to'], false, 'btree'],
  ['slo_measurements', 'ix_slo_measurements_service_level_objective_id', ['service_level_objective_id'], false, 'btree'],
  ['slo_measurements', 'ix_slo_measurements_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['slo_measurements', 'ix_slo_measurements_objective_window', ['service_level_objective_id', 'window_end desc'], false, 'btree'],
  ['tool_registry', 'uq_tool_registry_code', ['code'], true, 'btree'],
  ['tool_registry', 'ix_tool_registry_tenant_id', ['tenant_id'], false, 'btree'],
  ['tool_registry', 'ix_tool_registry_tool_type_concept_id', ['tool_type_concept_id'], false, 'btree'],
  ['tool_registry', 'ix_tool_registry_approved_by_user_id', ['approved_by_user_id'], false, 'btree'],
  ['tool_registry', 'ix_tool_registry_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['tool_registry', 'ix_tool_registry_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['tool_registry', 'ix_tool_registry_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['tool_registry', 'ix_tool_registry_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
];
