import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `platform_ops` (parte 1/2).
 * 180 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const platformOpsIndexes1: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['artifacts', 'uq_artifacts_artifact_ref', ['artifact_ref'], true, 'btree'],
  ['artifacts', 'ix_artifacts_tenant_id', ['tenant_id'], false, 'btree'],
  ['artifacts', 'ix_artifacts_service_component_id', ['service_component_id'], false, 'btree'],
  ['artifacts', 'ix_artifacts_produced_by_tool_id', ['produced_by_tool_id'], false, 'btree'],
  ['artifacts', 'ix_artifacts_artifact_type_concept_id', ['artifact_type_concept_id'], false, 'btree'],
  ['artifacts', 'ix_artifacts_file_id', ['file_id'], false, 'btree'],
  ['artifacts', 'ix_artifacts_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['artifacts', 'ix_artifacts_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['artifacts', 'ix_artifacts_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['artifacts', 'ix_artifacts_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['artifacts', 'uq_artifacts_service_component_id_version', ['service_component_id', 'version'], true, 'btree'],
  ['capacity_measurements', 'ix_capacity_measurements_capacity_plan_id', ['capacity_plan_id'], false, 'btree'],
  ['capacity_measurements', 'ix_capacity_measurements_metric_concept_id', ['metric_concept_id'], false, 'btree'],
  ['capacity_measurements', 'brin_capacity_measurements_created_at', ['created_at'], false, 'brin'],
  ['capacity_plans', 'ix_capacity_plans_service_component_id', ['service_component_id'], false, 'btree'],
  ['capacity_plans', 'ix_capacity_plans_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['capacity_plans', 'ix_capacity_plans_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['capacity_plans', 'ix_capacity_plans_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['capacity_plans', 'uk_capacity_plans_service_code_horizon', ['service_component_id', 'code', 'planning_horizon_start'], true, 'btree'],
  ['change_approvals', 'ix_change_approvals_change_request_id', ['change_request_id'], false, 'btree'],
  ['change_approvals', 'ix_change_approvals_approver_user_id', ['approver_user_id'], false, 'btree'],
  ['change_approvals', 'ix_change_approvals_decision_concept_id', ['decision_concept_id'], false, 'btree'],
  ['change_approvals', 'brin_change_approvals_created_at', ['created_at'], false, 'brin'],
  ['change_approvals', 'uk_change_approvals_change_step_approver', ['change_request_id', 'approval_step', 'approver_user_id'], true, 'btree'],
  ['change_requests', 'ix_change_requests_tenant_id', ['tenant_id'], false, 'btree'],
  ['change_requests', 'ix_change_requests_service_component_id', ['service_component_id'], false, 'btree'],
  ['change_requests', 'ix_change_requests_deployment_id', ['deployment_id'], false, 'btree'],
  ['change_requests', 'ix_change_requests_change_type_concept_id', ['change_type_concept_id'], false, 'btree'],
  ['change_requests', 'ix_change_requests_risk_level_concept_id', ['risk_level_concept_id'], false, 'btree'],
  ['change_requests', 'ix_change_requests_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['change_requests', 'ix_change_requests_requested_by_user_id', ['requested_by_user_id'], false, 'btree'],
  ['change_requests', 'ix_change_requests_maintenance_window_id', ['maintenance_window_id'], false, 'btree'],
  ['change_requests', 'ix_change_requests_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['change_requests', 'ix_change_requests_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['change_requests', 'ix_change_requests_tenant_status', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['change_requests', 'uk_change_requests_tenant_number', ['tenant_id', 'change_number'], true, 'btree'],
  ['component_tools', 'ix_component_tools_service_component_id', ['service_component_id'], false, 'btree'],
  ['component_tools', 'ix_component_tools_tool_id', ['tool_id'], false, 'btree'],
  ['component_tools', 'ix_component_tools_usage_concept_id', ['usage_concept_id'], false, 'btree'],
  ['component_tools', 'ix_component_tools_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['component_tools', 'ix_component_tools_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['deployments', 'uq_deployments_deployment_number', ['deployment_number'], true, 'btree'],
  ['deployments', 'ix_deployments_tenant_id', ['tenant_id'], false, 'btree'],
  ['deployments', 'ix_deployments_service_component_id', ['service_component_id'], false, 'btree'],
  ['deployments', 'ix_deployments_artifact_id', ['artifact_id'], false, 'btree'],
  ['deployments', 'ix_deployments_environment_concept_id', ['environment_concept_id'], false, 'btree'],
  ['deployments', 'ix_deployments_strategy_concept_id', ['strategy_concept_id'], false, 'btree'],
  ['deployments', 'ix_deployments_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['deployments', 'ix_deployments_deployed_by_user_id', ['deployed_by_user_id'], false, 'btree'],
  ['deployments', 'ix_deployments_rollback_of_deployment_id', ['rollback_of_deployment_id'], false, 'btree'],
  ['deployments', 'ix_deployments_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['deployments', 'ix_deployments_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['deployments', 'ix_deployments_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['error_budget_burn_events', 'ix_error_budget_burn_events_error_budget_policy_id', ['error_budget_policy_id'], false, 'btree'],
  ['error_budget_burn_events', 'ix_error_budget_burn_events_severity_concept_id', ['severity_concept_id'], false, 'btree'],
  ['error_budget_burn_events', 'ix_error_budget_burn_events_health_incident_id', ['health_incident_id'], false, 'btree'],
  ['error_budget_burn_events', 'brin_error_budget_burn_events_occurred_at', ['occurred_at'], false, 'brin'],
  ['error_budget_policies', 'ix_error_budget_policies_service_level_objective_id', ['service_level_objective_id'], false, 'btree'],
  ['error_budget_policies', 'ix_error_budget_policies_required_approval_role_concept_id', ['required_approval_role_concept_id'], false, 'btree'],
  ['error_budget_policies', 'ix_error_budget_policies_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['error_budget_policies', 'ix_error_budget_policies_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['error_budget_policies', 'ix_error_budget_policies_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['error_budget_policies', 'uk_error_budget_policies_slo_code', ['service_level_objective_id', 'code'], true, 'btree'],
  ['escalation_policies', 'ix_escalation_policies_tenant_id', ['tenant_id'], false, 'btree'],
  ['escalation_policies', 'ix_escalation_policies_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['escalation_policies', 'ix_escalation_policies_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['escalation_policies', 'ix_escalation_policies_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['escalation_policies', 'ix_escalation_policies_tenant_created', ['tenant_id', 'created_at desc'], false, 'btree'],
  ['escalation_policies', 'uk_escalation_policies_tenant_code', ['tenant_id', 'code'], true, 'btree'],
  ['escalation_policy_steps', 'ix_escalation_policy_steps_escalation_policy_id', ['escalation_policy_id'], false, 'btree'],
  ['escalation_policy_steps', 'ix_escalation_policy_steps_target_type_concept_id', ['target_type_concept_id'], false, 'btree'],
  ['escalation_policy_steps', 'ix_escalation_policy_steps_operational_team_id', ['operational_team_id'], false, 'btree'],
  ['escalation_policy_steps', 'ix_escalation_policy_steps_on_call_schedule_id', ['on_call_schedule_id'], false, 'btree'],
  ['escalation_policy_steps', 'ix_escalation_policy_steps_target_user_id', ['target_user_id'], false, 'btree'],
  ['escalation_policy_steps', 'ix_escalation_policy_steps_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['escalation_policy_steps', 'ix_escalation_policy_steps_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['escalation_policy_steps', 'uk_escalation_policy_steps_policy_step', ['escalation_policy_id', 'step_number'], true, 'btree'],
  ['health_checks', 'uq_health_checks_code', ['code'], true, 'btree'],
  ['health_checks', 'ix_health_checks_tenant_id', ['tenant_id'], false, 'btree'],
  ['health_checks', 'ix_health_checks_service_component_id', ['service_component_id'], false, 'btree'],
  ['health_checks', 'ix_health_checks_check_type_concept_id', ['check_type_concept_id'], false, 'btree'],
  ['health_checks', 'ix_health_checks_target_kind_concept_id', ['target_kind_concept_id'], false, 'btree'],
  ['health_checks', 'ix_health_checks_severity_concept_id', ['severity_concept_id'], false, 'btree'],
  ['health_checks', 'ix_health_checks_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['health_checks', 'ix_health_checks_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['health_checks', 'ix_health_checks_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['health_checks', 'ix_health_checks_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['health_check_runs', 'ix_health_check_runs_health_check_id', ['health_check_id'], false, 'btree'],
  ['health_check_runs', 'ix_health_check_runs_service_component_id', ['service_component_id'], false, 'btree'],
  ['health_check_runs', 'ix_health_check_runs_deployment_id', ['deployment_id'], false, 'btree'],
  ['health_check_runs', 'ix_health_check_runs_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['health_check_runs', 'ix_health_check_runs_run_source_concept_id', ['run_source_concept_id'], false, 'btree'],
  ['health_check_runs', 'ix_health_check_runs_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['health_check_runs', 'brin_health_check_runs_recorded_at', ['recorded_at'], false, 'brin'],
  ['health_incidents', 'uq_health_incidents_incident_number', ['incident_number'], true, 'btree'],
  ['health_incidents', 'ix_health_incidents_tenant_id', ['tenant_id'], false, 'btree'],
  ['health_incidents', 'ix_health_incidents_service_component_id', ['service_component_id'], false, 'btree'],
  ['health_incidents', 'ix_health_incidents_health_check_id', ['health_check_id'], false, 'btree'],
  ['health_incidents', 'ix_health_incidents_severity_concept_id', ['severity_concept_id'], false, 'btree'],
  ['health_incidents', 'ix_health_incidents_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['health_incidents', 'ix_health_incidents_detected_by_run_id', ['detected_by_run_id'], false, 'btree'],
  ['health_incidents', 'ix_health_incidents_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['health_incidents', 'ix_health_incidents_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['health_incidents', 'ix_health_incidents_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['incident_communications', 'ix_incident_communications_health_incident_id', ['health_incident_id'], false, 'btree'],
  ['incident_communications', 'ix_incident_communications_communication_type_concept_id', ['communication_type_concept_id'], false, 'btree'],
  ['incident_communications', 'ix_incident_communications_audience_concept_id', ['audience_concept_id'], false, 'btree'],
  ['incident_communications', 'ix_incident_communications_published_by_user_id', ['published_by_user_id'], false, 'btree'],
  ['incident_communications', 'brin_incident_communications_created_at', ['created_at'], false, 'brin'],
  ['incident_responders', 'ix_incident_responders_health_incident_id', ['health_incident_id'], false, 'btree'],
  ['incident_responders', 'ix_incident_responders_user_id', ['user_id'], false, 'btree'],
  ['incident_responders', 'ix_incident_responders_responder_role_concept_id', ['responder_role_concept_id'], false, 'btree'],
  ['incident_responders', 'uk_incident_responders_incident_user_role', ['health_incident_id', 'user_id', 'responder_role_concept_id'], true, 'btree'],
  ['incident_timeline_events', 'ix_incident_timeline_events_health_incident_id', ['health_incident_id'], false, 'btree'],
  ['incident_timeline_events', 'ix_incident_timeline_events_event_type_concept_id', ['event_type_concept_id'], false, 'btree'],
  ['incident_timeline_events', 'ix_incident_timeline_events_actor_user_id', ['actor_user_id'], false, 'btree'],
  ['incident_timeline_events', 'brin_incident_timeline_events_occurred_at', ['occurred_at'], false, 'brin'],
  ['incident_timeline_events', 'ix_incident_timeline_incident_occurred', ['health_incident_id', 'occurred_at'], false, 'btree'],
  ['maintenance_windows', 'ix_maintenance_windows_tenant_id', ['tenant_id'], false, 'btree'],
  ['maintenance_windows', 'ix_maintenance_windows_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['maintenance_windows', 'ix_maintenance_windows_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['maintenance_windows', 'ix_maintenance_windows_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['maintenance_windows', 'ix_maintenance_windows_tenant_status', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['on_call_schedules', 'ix_on_call_schedules_operational_team_id', ['operational_team_id'], false, 'btree'],
  ['on_call_schedules', 'ix_on_call_schedules_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['on_call_schedules', 'ix_on_call_schedules_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['on_call_schedules', 'ix_on_call_schedules_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['on_call_schedules', 'uk_on_call_schedules_team_code', ['operational_team_id', 'code'], true, 'btree'],
  ['on_call_shifts', 'ix_on_call_shifts_on_call_schedule_id', ['on_call_schedule_id'], false, 'btree'],
  ['on_call_shifts', 'ix_on_call_shifts_user_id', ['user_id'], false, 'btree'],
  ['on_call_shifts', 'ix_on_call_shifts_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['on_call_shifts', 'ix_on_call_shifts_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['on_call_shifts', 'ix_on_call_shifts_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['operational_improvement_items', 'ix_operational_improvement_items_tenant_id', ['tenant_id'], false, 'btree'],
  ['operational_improvement_items', 'ix_operational_improvement_items_service_component_id', ['service_component_id'], false, 'btree'],
  ['operational_improvement_items', 'ix_operational_improvement_items_postmortem_action_item_id', ['postmortem_action_item_id'], false, 'btree'],
  ['operational_improvement_items', 'ix_operational_improvement_items_readiness_review_finding_id', ['readiness_review_finding_id'], false, 'btree'],
  ['operational_improvement_items', 'ix_operational_improvement_items_source_type_concept_id', ['source_type_concept_id'], false, 'btree'],
  ['operational_improvement_items', 'ix_operational_improvement_items_priority_concept_id', ['priority_concept_id'], false, 'btree'],
  ['operational_improvement_items', 'ix_operational_improvement_items_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['operational_improvement_items', 'ix_operational_improvement_items_owner_user_id', ['owner_user_id'], false, 'btree'],
  ['operational_improvement_items', 'ix_operational_improvement_items_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['operational_improvement_items', 'ix_operational_improvement_items_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['operational_improvement_items', 'ix_operational_improvement_items_tenant_status', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['operational_readiness_reviews', 'ix_operational_readiness_reviews_service_component_id', ['service_component_id'], false, 'btree'],
  ['operational_readiness_reviews', 'ix_operational_readiness_reviews_deployment_id', ['deployment_id'], false, 'btree'],
  ['operational_readiness_reviews', 'ix_operational_readiness_reviews_review_type_concept_id', ['review_type_concept_id'], false, 'btree'],
  ['operational_readiness_reviews', 'ix_operational_readiness_reviews_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['operational_readiness_reviews', 'ix_operational_readiness_reviews_facilitator_user_id', ['facilitator_user_id'], false, 'btree'],
  ['operational_readiness_reviews', 'ix_operational_readiness_reviews_decision_concept_id', ['decision_concept_id'], false, 'btree'],
  ['operational_readiness_reviews', 'ix_operational_readiness_reviews_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['operational_readiness_reviews', 'ix_operational_readiness_reviews_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['operational_teams', 'ix_operational_teams_tenant_id', ['tenant_id'], false, 'btree'],
  ['operational_teams', 'ix_operational_teams_team_type_concept_id', ['team_type_concept_id'], false, 'btree'],
  ['operational_teams', 'ix_operational_teams_manager_user_id', ['manager_user_id'], false, 'btree'],
  ['operational_teams', 'ix_operational_teams_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['operational_teams', 'ix_operational_teams_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['operational_teams', 'ix_operational_teams_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['operational_teams', 'ix_operational_teams_tenant_created', ['tenant_id', 'created_at desc'], false, 'btree'],
  ['operational_teams', 'uk_operational_teams_tenant_code', ['tenant_id', 'code'], true, 'btree'],
  ['postmortems', 'ix_postmortems_health_incident_id', ['health_incident_id'], false, 'btree'],
  ['postmortems', 'ix_postmortems_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['postmortems', 'ix_postmortems_owner_user_id', ['owner_user_id'], false, 'btree'],
  ['postmortems', 'ix_postmortems_reviewed_by_user_id', ['reviewed_by_user_id'], false, 'btree'],
  ['postmortems', 'ix_postmortems_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['postmortems', 'ix_postmortems_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['postmortems', 'uk_postmortems_incident', ['health_incident_id'], true, 'btree'],
  ['postmortem_action_items', 'ix_postmortem_action_items_postmortem_id', ['postmortem_id'], false, 'btree'],
  ['postmortem_action_items', 'ix_postmortem_action_items_action_type_concept_id', ['action_type_concept_id'], false, 'btree'],
  ['postmortem_action_items', 'ix_postmortem_action_items_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['postmortem_action_items', 'ix_postmortem_action_items_owner_user_id', ['owner_user_id'], false, 'btree'],
  ['postmortem_action_items', 'ix_postmortem_action_items_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['postmortem_action_items', 'ix_postmortem_action_items_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['postmortem_action_items', 'uk_postmortem_action_items_postmortem_code', ['postmortem_id', 'action_code'], true, 'btree'],
  ['readiness_review_findings', 'ix_readiness_review_findings_operational_readiness_review_id', ['operational_readiness_review_id'], false, 'btree'],
  ['readiness_review_findings', 'ix_readiness_review_findings_severity_concept_id', ['severity_concept_id'], false, 'btree'],
  ['readiness_review_findings', 'ix_readiness_review_findings_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['readiness_review_findings', 'ix_readiness_review_findings_owner_user_id', ['owner_user_id'], false, 'btree'],
  ['readiness_review_findings', 'ix_readiness_review_findings_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['readiness_review_findings', 'ix_readiness_review_findings_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
];
