import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `practice`.
 * 82 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const practiceIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['care_spaces', 'ix_care_spaces_practice_site_id', ['practice_site_id'], false, 'btree'],
  ['care_spaces', 'ix_care_spaces_clinical_unit_id', ['clinical_unit_id'], false, 'btree'],
  ['care_spaces', 'ix_care_spaces_parent_space_id', ['parent_space_id'], false, 'btree'],
  ['care_spaces', 'ix_care_spaces_space_type_concept_id', ['space_type_concept_id'], false, 'btree'],
  ['care_spaces', 'ix_care_spaces_operational_status_concept_id', ['operational_status_concept_id'], false, 'btree'],
  ['care_spaces', 'ix_care_spaces_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['care_spaces', 'ix_care_spaces_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['care_spaces', 'ix_care_spaces_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['clinical_units', 'ix_clinical_units_practice_site_id', ['practice_site_id'], false, 'btree'],
  ['clinical_units', 'ix_clinical_units_parent_unit_id', ['parent_unit_id'], false, 'btree'],
  ['clinical_units', 'ix_clinical_units_unit_type_concept_id', ['unit_type_concept_id'], false, 'btree'],
  ['clinical_units', 'ix_clinical_units_specialty_concept_id', ['specialty_concept_id'], false, 'btree'],
  ['clinical_units', 'ix_clinical_units_service_mode_concept_id', ['service_mode_concept_id'], false, 'btree'],
  ['clinical_units', 'ix_clinical_units_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['clinical_units', 'ix_clinical_units_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['clinical_units', 'ix_clinical_units_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['healthcare_services', 'ix_healthcare_services_practice_id', ['practice_id'], false, 'btree'],
  ['healthcare_services', 'ix_healthcare_services_practice_site_id', ['practice_site_id'], false, 'btree'],
  ['healthcare_services', 'ix_healthcare_services_clinical_unit_id', ['clinical_unit_id'], false, 'btree'],
  ['healthcare_services', 'ix_healthcare_services_service_concept_id', ['service_concept_id'], false, 'btree'],
  ['healthcare_services', 'ix_healthcare_services_specialty_concept_id', ['specialty_concept_id'], false, 'btree'],
  ['healthcare_services', 'ix_healthcare_services_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['healthcare_services', 'ix_healthcare_services_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['healthcare_services', 'ix_healthcare_services_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['inventory_items', 'ix_inventory_items_practice_id', ['practice_id'], false, 'btree'],
  ['inventory_items', 'ix_inventory_items_product_concept_id', ['product_concept_id'], false, 'btree'],
  ['inventory_items', 'ix_inventory_items_unit_concept_id', ['unit_concept_id'], false, 'btree'],
  ['inventory_items', 'ix_inventory_items_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['inventory_items', 'ix_inventory_items_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['inventory_items', 'ix_inventory_items_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['inventory_movements', 'ix_inventory_movements_inventory_item_id', ['inventory_item_id'], false, 'btree'],
  ['inventory_movements', 'ix_inventory_movements_movement_type_concept_id', ['movement_type_concept_id'], false, 'btree'],
  ['inventory_movements', 'ix_inventory_movements_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['inventory_movements', 'brin_inventory_movements_recorded_at', ['recorded_at'], false, 'brin'],
  ['practices', 'ix_practices_tenant_id', ['tenant_id'], false, 'btree'],
  ['practices', 'ix_practices_type_concept_id', ['type_concept_id'], false, 'btree'],
  ['practices', 'ix_practices_admin_user_id', ['admin_user_id'], false, 'btree'],
  ['practices', 'ix_practices_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['practices', 'ix_practices_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['practices', 'ix_practices_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['practices', 'ix_practices_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['practices', 'ix_practices_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['practice_accreditations', 'ix_practice_accreditations_practice_id', ['practice_id'], false, 'btree'],
  ['practice_accreditations', 'ix_practice_accreditations_practice_site_id', ['practice_site_id'], false, 'btree'],
  ['practice_accreditations', 'ix_practice_accreditations_accreditation_type_concept_id', ['accreditation_type_concept_id'], false, 'btree'],
  ['practice_accreditations', 'ix_practice_accreditations_issuer_tenant_id', ['issuer_tenant_id'], false, 'btree'],
  ['practice_accreditations', 'ix_practice_accreditations_evidence_file_id', ['evidence_file_id'], false, 'btree'],
  ['practice_accreditations', 'ix_practice_accreditations_verification_status_concept_id', ['verification_status_concept_id'], false, 'btree'],
  ['practice_accreditations', 'ix_practice_accreditations_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['practice_accreditations', 'ix_practice_accreditations_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['practice_settings', 'ix_practice_settings_practice_id', ['practice_id'], false, 'btree'],
  ['practice_settings', 'ix_practice_settings_category_concept_id', ['category_concept_id'], false, 'btree'],
  ['practice_settings', 'ix_practice_settings_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['practice_settings', 'ix_practice_settings_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['practice_sites', 'ix_practice_sites_practice_id', ['practice_id'], false, 'btree'],
  ['practice_sites', 'ix_practice_sites_branch_id', ['branch_id'], false, 'btree'],
  ['practice_sites', 'ix_practice_sites_site_type_concept_id', ['site_type_concept_id'], false, 'btree'],
  ['practice_sites', 'ix_practice_sites_physical_type_concept_id', ['physical_type_concept_id'], false, 'btree'],
  ['practice_sites', 'ix_practice_sites_operational_status_concept_id', ['operational_status_concept_id'], false, 'btree'],
  ['practice_sites', 'ix_practice_sites_address_id', ['address_id'], false, 'btree'],
  ['practice_sites', 'ix_practice_sites_managing_tenant_id', ['managing_tenant_id'], false, 'btree'],
  ['practice_sites', 'ix_practice_sites_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['practice_sites', 'ix_practice_sites_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['practice_sites', 'ix_practice_sites_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['practitioner_role_assignments', 'ix_practitioner_role_assignments_practitioner_profile_id', ['practitioner_profile_id'], false, 'btree'],
  ['practitioner_role_assignments', 'ix_practitioner_role_assignments_practice_id', ['practice_id'], false, 'btree'],
  ['practitioner_role_assignments', 'ix_practitioner_role_assignments_practice_site_id', ['practice_site_id'], false, 'btree'],
  ['practitioner_role_assignments', 'ix_practitioner_role_assignments_clinical_unit_id', ['clinical_unit_id'], false, 'btree'],
  ['practitioner_role_assignments', 'ix_practitioner_role_assignments_healthcare_service_id', ['healthcare_service_id'], false, 'btree'],
  ['practitioner_role_assignments', 'ix_practitioner_role_assignments_role_concept_id', ['role_concept_id'], false, 'btree'],
  ['practitioner_role_assignments', 'ix_practitioner_role_assignments_specialty_concept_id', ['specialty_concept_id'], false, 'btree'],
  ['practitioner_role_assignments', 'ix_practitioner_role_assignments_supervisor_practition_4d201e89', ['supervisor_practitioner_profile_id'], false, 'btree'],
  ['practitioner_role_assignments', 'ix_practitioner_role_assignments_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['practitioner_role_assignments', 'ix_practitioner_role_assignments_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['practitioner_role_assignments', 'ix_practitioner_role_assignments_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['practitioner_support_assignments', 'ix_practitioner_support_assignments_practitioner_role__d1c4a67d', ['practitioner_role_assignment_id'], false, 'btree'],
  ['practitioner_support_assignments', 'ix_practitioner_support_assignments_support_profile_id', ['support_profile_id'], false, 'btree'],
  ['practitioner_support_assignments', 'ix_practitioner_support_assignments_support_role_concept_id', ['support_role_concept_id'], false, 'btree'],
  ['practitioner_support_assignments', 'ix_practitioner_support_assignments_scope_concept_id', ['scope_concept_id'], false, 'btree'],
  ['practitioner_support_assignments', 'ix_practitioner_support_assignments_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['practitioner_support_assignments', 'ix_practitioner_support_assignments_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['practitioner_support_assignments', 'ix_practitioner_support_assignments_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
];
