import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `procedures_perioperative` (parte 1/2).
 * 180 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const proceduresPerioperativeIndexes1: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['anesthesia_airway_assessments', 'ix_anesthesia_airway_assessments_anesthesia_plan_id', ['anesthesia_plan_id'], false, 'btree'],
  ['anesthesia_airway_assessments', 'ix_anesthesia_airway_assessments_assessed_by_profile_id', ['assessed_by_profile_id'], false, 'btree'],
  ['anesthesia_airway_assessments', 'ix_anesthesia_airway_assessments_mallampati_concept_id', ['mallampati_concept_id'], false, 'btree'],
  ['anesthesia_airway_assessments', 'ix_anesthesia_airway_assessments_neck_mobility_concept_id', ['neck_mobility_concept_id'], false, 'btree'],
  ['anesthesia_airway_assessments', 'ix_anesthesia_airway_assessments_dentition_status_concept_id', ['dentition_status_concept_id'], false, 'btree'],
  ['anesthesia_events', 'ix_anesthesia_events_procedure_case_id', ['procedure_case_id'], false, 'btree'],
  ['anesthesia_events', 'ix_anesthesia_events_anesthesia_plan_id', ['anesthesia_plan_id'], false, 'btree'],
  ['anesthesia_events', 'ix_anesthesia_events_event_type_concept_id', ['event_type_concept_id'], false, 'btree'],
  ['anesthesia_events', 'ix_anesthesia_events_medication_administration_id', ['medication_administration_id'], false, 'btree'],
  ['anesthesia_events', 'ix_anesthesia_events_observation_id', ['observation_id'], false, 'btree'],
  ['anesthesia_events', 'ix_anesthesia_events_device_id', ['device_id'], false, 'btree'],
  ['anesthesia_events', 'ix_anesthesia_events_performed_by_profile_id', ['performed_by_profile_id'], false, 'btree'],
  ['anesthesia_events', 'ix_anesthesia_events_severity_concept_id', ['severity_concept_id'], false, 'btree'],
  ['anesthesia_events', 'ix_anesthesia_events_case_time', ['procedure_case_id', 'occurred_at'], false, 'btree'],
  ['anesthesia_plans', 'ix_anesthesia_plans_procedure_case_id', ['procedure_case_id'], false, 'btree'],
  ['anesthesia_plans', 'ix_anesthesia_plans_anesthesiologist_profile_id', ['anesthesiologist_profile_id'], false, 'btree'],
  ['anesthesia_plans', 'ix_anesthesia_plans_anesthesia_type_concept_id', ['anesthesia_type_concept_id'], false, 'btree'],
  ['anesthesia_plans', 'ix_anesthesia_plans_technique_concept_id', ['technique_concept_id'], false, 'btree'],
  ['anesthesia_plans', 'ix_anesthesia_plans_airway_plan_concept_id', ['airway_plan_concept_id'], false, 'btree'],
  ['anesthesia_plans', 'ix_anesthesia_plans_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['anesthesia_plans', 'ix_anesthesia_plans_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['anesthesia_plans', 'ix_anesthesia_plans_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['implant_identifiers', 'ix_implant_identifiers_procedure_implant_id', ['procedure_implant_id'], false, 'btree'],
  ['implant_identifiers', 'ix_implant_identifiers_identifier_type_concept_id', ['identifier_type_concept_id'], false, 'btree'],
  ['implant_identifiers', 'uk_implant_identifiers_type_value', ['identifier_type_concept_id', 'identifier_value'], true, 'btree'],
  ['instrument_sets', 'ix_instrument_sets_tenant_id', ['tenant_id'], false, 'btree'],
  ['instrument_sets', 'ix_instrument_sets_set_type_concept_id', ['set_type_concept_id'], false, 'btree'],
  ['instrument_sets', 'ix_instrument_sets_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['operating_room_utilization_events', 'ix_operating_room_utilization_events_operating_room_id', ['operating_room_id'], false, 'btree'],
  ['operating_room_utilization_events', 'ix_operating_room_utilization_events_procedure_case_id', ['procedure_case_id'], false, 'btree'],
  ['operating_room_utilization_events', 'ix_operating_room_utilization_events_event_type_concept_id', ['event_type_concept_id'], false, 'btree'],
  ['operating_room_utilization_events', 'ix_operating_room_utilization_events_delay_reason_concept_id', ['delay_reason_concept_id'], false, 'btree'],
  ['operating_room_utilization_events', 'ix_operating_room_utilization_events_turnover_category_21fa0c9f', ['turnover_category_concept_id'], false, 'btree'],
  ['operating_room_utilization_events', 'ix_operating_room_utilization_events_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['operating_room_utilization_events', 'ix_or_utilization_room_time', ['operating_room_id', 'occurred_at desc'], false, 'btree'],
  ['operative_findings', 'ix_operative_findings_procedure_case_id', ['procedure_case_id'], false, 'btree'],
  ['operative_findings', 'ix_operative_findings_operative_step_id', ['operative_step_id'], false, 'btree'],
  ['operative_findings', 'ix_operative_findings_finding_code_concept_id', ['finding_code_concept_id'], false, 'btree'],
  ['operative_findings', 'ix_operative_findings_body_site_concept_id', ['body_site_concept_id'], false, 'btree'],
  ['operative_findings', 'ix_operative_findings_laterality_concept_id', ['laterality_concept_id'], false, 'btree'],
  ['operative_findings', 'ix_operative_findings_severity_concept_id', ['severity_concept_id'], false, 'btree'],
  ['operative_findings', 'ix_operative_findings_observation_id', ['observation_id'], false, 'btree'],
  ['operative_findings', 'ix_operative_findings_recorded_by_profile_id', ['recorded_by_profile_id'], false, 'btree'],
  ['operative_reports', 'ix_operative_reports_procedure_case_id', ['procedure_case_id'], false, 'btree'],
  ['operative_reports', 'ix_operative_reports_procedure_id', ['procedure_id'], false, 'btree'],
  ['operative_reports', 'ix_operative_reports_author_profile_id', ['author_profile_id'], false, 'btree'],
  ['operative_reports', 'ix_operative_reports_disposition_concept_id', ['disposition_concept_id'], false, 'btree'],
  ['operative_reports', 'ix_operative_reports_file_id', ['file_id'], false, 'btree'],
  ['operative_reports', 'ix_operative_reports_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['operative_reports', 'ix_operative_reports_signature_id', ['signature_id'], false, 'btree'],
  ['operative_reports', 'uk_operative_reports_case_version', ['procedure_case_id', 'report_version'], true, 'btree'],
  ['operative_steps', 'ix_operative_steps_procedure_case_id', ['procedure_case_id'], false, 'btree'],
  ['operative_steps', 'ix_operative_steps_procedure_id', ['procedure_id'], false, 'btree'],
  ['operative_steps', 'ix_operative_steps_step_code_concept_id', ['step_code_concept_id'], false, 'btree'],
  ['operative_steps', 'ix_operative_steps_performed_by_profile_id', ['performed_by_profile_id'], false, 'btree'],
  ['operative_steps', 'ix_operative_steps_body_site_concept_id', ['body_site_concept_id'], false, 'btree'],
  ['operative_steps', 'ix_operative_steps_laterality_concept_id', ['laterality_concept_id'], false, 'btree'],
  ['operative_steps', 'ix_operative_steps_technique_concept_id', ['technique_concept_id'], false, 'btree'],
  ['operative_steps', 'ix_operative_steps_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['operative_steps', 'ix_operative_steps_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['operative_steps', 'ix_operative_steps_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['operative_steps', 'uk_operative_steps_case_step', ['procedure_case_id', 'step_number'], true, 'btree'],
  ['pacu_assessments', 'ix_pacu_assessments_pacu_stay_id', ['pacu_stay_id'], false, 'btree'],
  ['pacu_assessments', 'ix_pacu_assessments_assessed_by_profile_id', ['assessed_by_profile_id'], false, 'btree'],
  ['pacu_assessments', 'ix_pacu_assessments_sedation_score_concept_id', ['sedation_score_concept_id'], false, 'btree'],
  ['pacu_assessments', 'ix_pacu_assessments_airway_status_concept_id', ['airway_status_concept_id'], false, 'btree'],
  ['pacu_stays', 'ix_pacu_stays_procedure_case_id', ['procedure_case_id'], false, 'btree'],
  ['pacu_stays', 'ix_pacu_stays_care_space_id', ['care_space_id'], false, 'btree'],
  ['pacu_stays', 'ix_pacu_stays_admitted_by_profile_id', ['admitted_by_profile_id'], false, 'btree'],
  ['pacu_stays', 'ix_pacu_stays_discharged_by_profile_id', ['discharged_by_profile_id'], false, 'btree'],
  ['pacu_stays', 'ix_pacu_stays_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['pacu_stays', 'ix_pacu_stays_discharge_destination_concept_id', ['discharge_destination_concept_id'], false, 'btree'],
  ['pacu_stays', 'ix_pacu_stays_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['pacu_stays', 'ix_pacu_stays_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['pacu_stays', 'uk_pacu_stays_case', ['procedure_case_id'], true, 'btree'],
  ['postoperative_followups', 'ix_postoperative_followups_procedure_case_id', ['procedure_case_id'], false, 'btree'],
  ['postoperative_followups', 'ix_postoperative_followups_followup_type_concept_id', ['followup_type_concept_id'], false, 'btree'],
  ['postoperative_followups', 'ix_postoperative_followups_appointment_id', ['appointment_id'], false, 'btree'],
  ['postoperative_followups', 'ix_postoperative_followups_completed_by_profile_id', ['completed_by_profile_id'], false, 'btree'],
  ['postoperative_followups', 'ix_postoperative_followups_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['postoperative_followups', 'ix_postoperative_followups_wound_status_concept_id', ['wound_status_concept_id'], false, 'btree'],
  ['postoperative_followups', 'ix_postoperative_followups_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['postoperative_followups', 'ix_postoperative_followups_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['postoperative_orders', 'ix_postoperative_orders_procedure_case_id', ['procedure_case_id'], false, 'btree'],
  ['postoperative_orders', 'ix_postoperative_orders_service_request_id', ['service_request_id'], false, 'btree'],
  ['postoperative_orders', 'ix_postoperative_orders_order_role_concept_id', ['order_role_concept_id'], false, 'btree'],
  ['postoperative_orders', 'ix_postoperative_orders_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['postoperative_orders', 'ix_postoperative_orders_verified_by_profile_id', ['verified_by_profile_id'], false, 'btree'],
  ['postoperative_orders', 'uk_postoperative_orders_case_request', ['procedure_case_id', 'service_request_id'], true, 'btree'],
  ['preoperative_assessments', 'ix_preoperative_assessments_procedure_case_id', ['procedure_case_id'], false, 'btree'],
  ['preoperative_assessments', 'ix_preoperative_assessments_assessment_type_concept_id', ['assessment_type_concept_id'], false, 'btree'],
  ['preoperative_assessments', 'ix_preoperative_assessments_assessed_by_profile_id', ['assessed_by_profile_id'], false, 'btree'],
  ['preoperative_assessments', 'ix_preoperative_assessments_fitness_status_concept_id', ['fitness_status_concept_id'], false, 'btree'],
  ['preoperative_assessments', 'ix_preoperative_assessments_asa_class_concept_id', ['asa_class_concept_id'], false, 'btree'],
  ['preoperative_assessments', 'ix_preoperative_assessments_airway_class_concept_id', ['airway_class_concept_id'], false, 'btree'],
  ['preoperative_assessments', 'ix_preoperative_assessments_bleeding_risk_concept_id', ['bleeding_risk_concept_id'], false, 'btree'],
  ['preoperative_assessments', 'ix_preoperative_assessments_infection_risk_concept_id', ['infection_risk_concept_id'], false, 'btree'],
  ['preoperative_assessments', 'ix_preoperative_assessments_nutrition_risk_concept_id', ['nutrition_risk_concept_id'], false, 'btree'],
  ['preoperative_assessments', 'ix_preoperative_assessments_pregnancy_status_concept_id', ['pregnancy_status_concept_id'], false, 'btree'],
  ['preoperative_assessments', 'ix_preoperative_assessments_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['preoperative_assessments', 'ix_preoperative_assessments_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['preoperative_assessments', 'ix_preoperative_assessments_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['preoperative_orders', 'ix_preoperative_orders_procedure_case_id', ['procedure_case_id'], false, 'btree'],
  ['preoperative_orders', 'ix_preoperative_orders_service_request_id', ['service_request_id'], false, 'btree'],
  ['preoperative_orders', 'ix_preoperative_orders_order_role_concept_id', ['order_role_concept_id'], false, 'btree'],
  ['preoperative_orders', 'ix_preoperative_orders_required_before_milestone_concept_id', ['required_before_milestone_concept_id'], false, 'btree'],
  ['preoperative_orders', 'ix_preoperative_orders_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['preoperative_orders', 'ix_preoperative_orders_verified_by_profile_id', ['verified_by_profile_id'], false, 'btree'],
  ['preoperative_orders', 'uk_preoperative_orders_case_request', ['procedure_case_id', 'service_request_id'], true, 'btree'],
  ['preoperative_risk_scores', 'ix_preoperative_risk_scores_preoperative_assessment_id', ['preoperative_assessment_id'], false, 'btree'],
  ['preoperative_risk_scores', 'ix_preoperative_risk_scores_risk_model_concept_id', ['risk_model_concept_id'], false, 'btree'],
  ['preoperative_risk_scores', 'ix_preoperative_risk_scores_risk_category_concept_id', ['risk_category_concept_id'], false, 'btree'],
  ['preoperative_risk_scores', 'uk_preoperative_risk_scores_assessment_model', ['preoperative_assessment_id', 'risk_model_concept_id', 'model_version'], true, 'btree'],
  ['procedure_body_sites', 'ix_procedure_body_sites_procedure_id', ['procedure_id'], false, 'btree'],
  ['procedure_body_sites', 'ix_procedure_body_sites_body_site_concept_id', ['body_site_concept_id'], false, 'btree'],
  ['procedure_body_sites', 'ix_procedure_body_sites_laterality_concept_id', ['laterality_concept_id'], false, 'btree'],
  ['procedure_body_sites', 'ix_procedure_body_sites_role_concept_id', ['role_concept_id'], false, 'btree'],
  ['procedure_body_sites', 'uk_procedure_body_sites_procedure_site_role', ['procedure_id', 'body_site_concept_id', 'laterality_concept_id', 'role_concept_id'], true, 'btree'],
  ['procedure_cancellations', 'ix_procedure_cancellations_procedure_case_id', ['procedure_case_id'], false, 'btree'],
  ['procedure_cancellations', 'ix_procedure_cancellations_cancellation_reason_concept_id', ['cancellation_reason_concept_id'], false, 'btree'],
  ['procedure_cancellations', 'ix_procedure_cancellations_cancellation_category_concept_id', ['cancellation_category_concept_id'], false, 'btree'],
  ['procedure_cancellations', 'ix_procedure_cancellations_cancelled_by_user_id', ['cancelled_by_user_id'], false, 'btree'],
  ['procedure_cancellations', 'ix_procedure_cancellations_preventable_concept_id', ['preventable_concept_id'], false, 'btree'],
  ['procedure_cancellations', 'ix_procedure_cancellations_replacement_case_id', ['replacement_case_id'], false, 'btree'],
  ['procedure_case_diagnoses', 'ix_procedure_case_diagnoses_procedure_case_id', ['procedure_case_id'], false, 'btree'],
  ['procedure_case_diagnoses', 'ix_procedure_case_diagnoses_condition_id', ['condition_id'], false, 'btree'],
  ['procedure_case_diagnoses', 'ix_procedure_case_diagnoses_diagnosis_role_concept_id', ['diagnosis_role_concept_id'], false, 'btree'],
  ['procedure_case_diagnoses', 'uk_procedure_case_diagnoses_case_sequence', ['procedure_case_id', 'sequence_number'], true, 'btree'],
  ['procedure_case_locations', 'ix_procedure_case_locations_procedure_case_id', ['procedure_case_id'], false, 'btree'],
  ['procedure_case_locations', 'ix_procedure_case_locations_care_space_id', ['care_space_id'], false, 'btree'],
  ['procedure_case_locations', 'ix_procedure_case_locations_location_role_concept_id', ['location_role_concept_id'], false, 'btree'],
  ['procedure_case_locations', 'ix_procedure_case_locations_transfer_reason_concept_id', ['transfer_reason_concept_id'], false, 'btree'],
  ['procedure_case_milestones', 'ix_procedure_case_milestones_procedure_case_id', ['procedure_case_id'], false, 'btree'],
  ['procedure_case_milestones', 'ix_procedure_case_milestones_milestone_type_concept_id', ['milestone_type_concept_id'], false, 'btree'],
  ['procedure_case_milestones', 'ix_procedure_case_milestones_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['procedure_case_milestones', 'ix_procedure_case_milestones_recorded_by_profile_id', ['recorded_by_profile_id'], false, 'btree'],
  ['procedure_case_milestones', 'uk_procedure_case_milestones_case_type', ['procedure_case_id', 'milestone_type_concept_id'], true, 'btree'],
  ['procedure_case_status_history', 'ix_procedure_case_status_history_procedure_case_id', ['procedure_case_id'], false, 'btree'],
  ['procedure_case_status_history', 'ix_procedure_case_status_history_from_status_concept_id', ['from_status_concept_id'], false, 'btree'],
  ['procedure_case_status_history', 'ix_procedure_case_status_history_to_status_concept_id', ['to_status_concept_id'], false, 'btree'],
  ['procedure_case_status_history', 'ix_procedure_case_status_history_changed_by_user_id', ['changed_by_user_id'], false, 'btree'],
  ['procedure_case_status_history', 'ix_procedure_case_status_history_reason_concept_id', ['reason_concept_id'], false, 'btree'],
  ['procedure_case_status_history', 'ix_procedure_case_status_history_workflow_transition_id', ['workflow_transition_id'], false, 'btree'],
  ['procedure_case_team_members', 'ix_procedure_case_team_members_procedure_case_id', ['procedure_case_id'], false, 'btree'],
  ['procedure_case_team_members', 'ix_procedure_case_team_members_practitioner_profile_id', ['practitioner_profile_id'], false, 'btree'],
  ['procedure_case_team_members', 'ix_procedure_case_team_members_team_role_concept_id', ['team_role_concept_id'], false, 'btree'],
  ['procedure_case_team_members', 'ix_procedure_case_team_members_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['procedure_case_team_members', 'ix_procedure_case_team_members_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['procedure_case_team_members', 'ix_procedure_case_team_members_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['procedure_case_team_members', 'uk_procedure_case_team_member_role', ['procedure_case_id', 'practitioner_profile_id', 'team_role_concept_id'], true, 'btree'],
  ['procedure_cases', 'ix_procedure_cases_custodian_tenant_id', ['custodian_tenant_id'], false, 'btree'],
  ['procedure_cases', 'ix_procedure_cases_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['procedure_cases', 'ix_procedure_cases_encounter_id', ['encounter_id'], false, 'btree'],
  ['procedure_cases', 'ix_procedure_cases_service_request_id', ['service_request_id'], false, 'btree'],
  ['procedure_cases', 'ix_procedure_cases_primary_procedure_id', ['primary_procedure_id'], false, 'btree'],
  ['procedure_cases', 'ix_procedure_cases_case_type_concept_id', ['case_type_concept_id'], false, 'btree'],
  ['procedure_cases', 'ix_procedure_cases_priority_concept_id', ['priority_concept_id'], false, 'btree'],
  ['procedure_cases', 'ix_procedure_cases_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['procedure_cases', 'ix_procedure_cases_surgical_specialty_concept_id', ['surgical_specialty_concept_id'], false, 'btree'],
  ['procedure_cases', 'ix_procedure_cases_requested_by_profile_id', ['requested_by_profile_id'], false, 'btree'],
  ['procedure_cases', 'ix_procedure_cases_primary_surgeon_profile_id', ['primary_surgeon_profile_id'], false, 'btree'],
  ['procedure_cases', 'ix_procedure_cases_anesthesiologist_profile_id', ['anesthesiologist_profile_id'], false, 'btree'],
  ['procedure_cases', 'ix_procedure_cases_practice_site_id', ['practice_site_id'], false, 'btree'],
  ['procedure_cases', 'ix_procedure_cases_operating_room_id', ['operating_room_id'], false, 'btree'],
  ['procedure_cases', 'ix_procedure_cases_cancellation_reason_concept_id', ['cancellation_reason_concept_id'], false, 'btree'],
  ['procedure_cases', 'ix_procedure_cases_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['procedure_cases', 'ix_procedure_cases_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['procedure_cases', 'uk_procedure_cases_tenant_number', ['custodian_tenant_id', 'case_number'], true, 'btree'],
  ['procedure_cases', 'ix_procedure_cases_room_schedule', ['operating_room_id', 'scheduled_start_at', 'scheduled_end_at'], false, 'btree'],
  ['procedure_cases', 'ix_procedure_cases_patient_time', ['custodian_tenant_id', 'patient_profile_id', 'scheduled_start_at desc'], false, 'btree'],
  ['procedure_charge_items', 'ix_procedure_charge_items_procedure_case_id', ['procedure_case_id'], false, 'btree'],
  ['procedure_charge_items', 'ix_procedure_charge_items_procedure_id', ['procedure_id'], false, 'btree'],
  ['procedure_charge_items', 'ix_procedure_charge_items_charge_item_type_concept_id', ['charge_item_type_concept_id'], false, 'btree'],
  ['procedure_charge_items', 'ix_procedure_charge_items_billable_item_id', ['billable_item_id'], false, 'btree'],
  ['procedure_charge_items', 'ix_procedure_charge_items_billing_claim_line_id', ['billing_claim_line_id'], false, 'btree'],
  ['procedure_charge_items', 'ix_procedure_charge_items_invoice_line_id', ['invoice_line_id'], false, 'btree'],
  ['procedure_charge_items', 'ix_procedure_charge_items_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['procedure_charge_items', 'ix_procedure_charge_items_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['procedure_charge_items', 'ix_procedure_charge_items_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['procedure_complications', 'ix_procedure_complications_procedure_case_id', ['procedure_case_id'], false, 'btree'],
];
