import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `procedures_perioperative` (parte 2/2).
 * 89 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const proceduresPerioperativeIndexes2: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['procedure_case_team_members', 'ix_procedure_case_team_members_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['procedure_case_team_members', 'uk_procedure_case_team_member_role', ['procedure_case_id', 'practitioner_profile_id', 'team_role_concept_id'], true, 'btree'],
  ['procedure_charge_items', 'ix_procedure_charge_items_procedure_case_id', ['procedure_case_id'], false, 'btree'],
  ['procedure_charge_items', 'ix_procedure_charge_items_procedure_id', ['procedure_id'], false, 'btree'],
  ['procedure_charge_items', 'ix_procedure_charge_items_charge_item_type_concept_id', ['charge_item_type_concept_id'], false, 'btree'],
  ['procedure_charge_items', 'ix_procedure_charge_items_billable_item_id', ['billable_item_id'], false, 'btree'],
  ['procedure_charge_items', 'ix_procedure_charge_items_billing_claim_line_id', ['billing_claim_line_id'], false, 'btree'],
  ['procedure_charge_items', 'ix_procedure_charge_items_invoice_line_id', ['invoice_line_id'], false, 'btree'],
  ['procedure_charge_items', 'ix_procedure_charge_items_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['procedure_charge_items', 'ix_procedure_charge_items_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['procedure_charge_items', 'ix_procedure_charge_items_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['procedure_complications', 'ix_procedure_complications_procedure_case_id', ['procedure_case_id'], false, 'btree'],
  ['procedure_complications', 'ix_procedure_complications_procedure_id', ['procedure_id'], false, 'btree'],
  ['procedure_complications', 'ix_procedure_complications_complication_code_concept_id', ['complication_code_concept_id'], false, 'btree'],
  ['procedure_complications', 'ix_procedure_complications_severity_concept_id', ['severity_concept_id'], false, 'btree'],
  ['procedure_complications', 'ix_procedure_complications_relatedness_concept_id', ['relatedness_concept_id'], false, 'btree'],
  ['procedure_complications', 'ix_procedure_complications_condition_id', ['condition_id'], false, 'btree'],
  ['procedure_complications', 'ix_procedure_complications_outcome_concept_id', ['outcome_concept_id'], false, 'btree'],
  ['procedure_complications', 'ix_procedure_complications_reported_by_profile_id', ['reported_by_profile_id'], false, 'btree'],
  ['procedure_complications', 'brin_procedure_complications_created_at', ['created_at'], false, 'brin'],
  ['procedure_devices', 'ix_procedure_devices_procedure_id', ['procedure_id'], false, 'btree'],
  ['procedure_devices', 'ix_procedure_devices_device_id', ['device_id'], false, 'btree'],
  ['procedure_devices', 'ix_procedure_devices_use_role_concept_id', ['use_role_concept_id'], false, 'btree'],
  ['procedure_devices', 'ix_procedure_devices_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['procedure_devices', 'ix_procedure_devices_device', ['device_id', 'used_at desc'], false, 'btree'],
  ['procedure_implants', 'ix_procedure_implants_procedure_case_id', ['procedure_case_id'], false, 'btree'],
  ['procedure_implants', 'ix_procedure_implants_procedure_id', ['procedure_id'], false, 'btree'],
  ['procedure_implants', 'ix_procedure_implants_implant_device_id', ['implant_device_id'], false, 'btree'],
  ['procedure_implants', 'ix_procedure_implants_implant_role_concept_id', ['implant_role_concept_id'], false, 'btree'],
  ['procedure_implants', 'ix_procedure_implants_body_site_concept_id', ['body_site_concept_id'], false, 'btree'],
  ['procedure_implants', 'ix_procedure_implants_laterality_concept_id', ['laterality_concept_id'], false, 'btree'],
  ['procedure_implants', 'ix_procedure_implants_explant_reason_concept_id', ['explant_reason_concept_id'], false, 'btree'],
  ['procedure_implants', 'ix_procedure_implants_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['procedure_implants', 'ix_procedure_implants_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['procedure_implants', 'ix_procedure_implants_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['procedure_medication_uses', 'ix_procedure_medication_uses_procedure_case_id', ['procedure_case_id'], false, 'btree'],
  ['procedure_medication_uses', 'ix_procedure_medication_uses_procedure_id', ['procedure_id'], false, 'btree'],
  ['procedure_medication_uses', 'ix_procedure_medication_uses_medication_administration_id', ['medication_administration_id'], false, 'btree'],
  ['procedure_medication_uses', 'ix_procedure_medication_uses_use_role_concept_id', ['use_role_concept_id'], false, 'btree'],
  ['procedure_medication_uses', 'ix_procedure_medication_uses_operative_step_id', ['operative_step_id'], false, 'btree'],
  ['procedure_medication_uses', 'uk_procedure_medication_uses_case_admin_role', ['procedure_case_id', 'medication_administration_id', 'use_role_concept_id'], true, 'btree'],
  ['procedure_outcomes', 'ix_procedure_outcomes_procedure_case_id', ['procedure_case_id'], false, 'btree'],
  ['procedure_outcomes', 'ix_procedure_outcomes_outcome_type_concept_id', ['outcome_type_concept_id'], false, 'btree'],
  ['procedure_outcomes', 'ix_procedure_outcomes_observation_id', ['observation_id'], false, 'btree'],
  ['procedure_outcomes', 'ix_procedure_outcomes_outcome_concept_id', ['outcome_concept_id'], false, 'btree'],
  ['procedure_outcomes', 'ix_procedure_outcomes_unit_concept_id', ['unit_concept_id'], false, 'btree'],
  ['procedure_outcomes', 'brin_procedure_outcomes_created_at', ['created_at'], false, 'brin'],
  ['procedure_performers', 'ix_procedure_performers_procedure_id', ['procedure_id'], false, 'btree'],
  ['procedure_performers', 'ix_procedure_performers_practitioner_profile_id', ['practitioner_profile_id'], false, 'btree'],
  ['procedure_performers', 'ix_procedure_performers_performer_role_concept_id', ['performer_role_concept_id'], false, 'btree'],
  ['procedure_performers', 'ix_procedure_performers_organization_id', ['organization_id'], false, 'btree'],
  ['procedure_performers', 'uk_procedure_performers_procedure_practitioner_role', ['procedure_id', 'practitioner_profile_id', 'performer_role_concept_id'], true, 'btree'],
  ['procedure_specimens', 'ix_procedure_specimens_procedure_case_id', ['procedure_case_id'], false, 'btree'],
  ['procedure_specimens', 'ix_procedure_specimens_procedure_id', ['procedure_id'], false, 'btree'],
  ['procedure_specimens', 'ix_procedure_specimens_specimen_id', ['specimen_id'], false, 'btree'],
  ['procedure_specimens', 'ix_procedure_specimens_specimen_role_concept_id', ['specimen_role_concept_id'], false, 'btree'],
  ['procedure_specimens', 'ix_procedure_specimens_operative_step_id', ['operative_step_id'], false, 'btree'],
  ['procedure_specimens', 'ix_procedure_specimens_body_site_concept_id', ['body_site_concept_id'], false, 'btree'],
  ['procedure_specimens', 'uk_procedure_specimens_case_specimen', ['procedure_case_id', 'specimen_id'], true, 'btree'],
  ['sterility_verification_checks', 'ix_sterility_verification_checks_procedure_case_id', ['procedure_case_id'], false, 'btree'],
  ['sterility_verification_checks', 'ix_sterility_verification_checks_check_type_concept_id', ['check_type_concept_id'], false, 'btree'],
  ['sterility_verification_checks', 'ix_sterility_verification_checks_checked_by_profile_id', ['checked_by_profile_id'], false, 'btree'],
  ['sterility_verification_checks', 'ix_sterility_verification_checks_result_concept_id', ['result_concept_id'], false, 'btree'],
  ['sterility_verification_checks', 'ix_sterility_verification_checks_sterilization_load_id', ['sterilization_load_id'], false, 'btree'],
  ['sterility_verification_checks', 'ix_sterility_verification_checks_instrument_set_id', ['instrument_set_id'], false, 'btree'],
  ['sterility_verification_checks', 'brin_sterility_verification_checks_created_at', ['created_at'], false, 'brin'],
  ['sterilization_loads', 'ix_sterilization_loads_tenant_id', ['tenant_id'], false, 'btree'],
  ['sterilization_loads', 'ix_sterilization_loads_method_concept_id', ['method_concept_id'], false, 'btree'],
  ['sterilization_loads', 'ix_sterilization_loads_result_concept_id', ['result_concept_id'], false, 'btree'],
  ['sterilization_loads', 'brin_sterilization_loads_created_at', ['created_at'], false, 'brin'],
  ['surgical_safety_checklists', 'ix_surgical_safety_checklists_procedure_case_id', ['procedure_case_id'], false, 'btree'],
  ['surgical_safety_checklists', 'ix_surgical_safety_checklists_checklist_type_concept_id', ['checklist_type_concept_id'], false, 'btree'],
  ['surgical_safety_checklists', 'ix_surgical_safety_checklists_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['surgical_safety_checklists', 'ix_surgical_safety_checklists_coordinator_profile_id', ['coordinator_profile_id'], false, 'btree'],
  ['surgical_safety_checklists', 'uk_surgical_safety_checklists_case_type_version', ['procedure_case_id', 'checklist_type_concept_id', 'checklist_version'], true, 'btree'],
  ['surgical_safety_items', 'ix_surgical_safety_items_checklist_type_concept_id', ['checklist_type_concept_id'], false, 'btree'],
  ['surgical_safety_items', 'ix_surgical_safety_items_phase_concept_id', ['phase_concept_id'], false, 'btree'],
  ['surgical_safety_items', 'ix_surgical_safety_items_response_type_concept_id', ['response_type_concept_id'], false, 'btree'],
  ['surgical_safety_items', 'ix_surgical_safety_items_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['surgical_safety_items', 'ix_surgical_safety_items_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['surgical_safety_items', 'ix_surgical_safety_items_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['surgical_safety_items', 'uk_surgical_safety_items_version_code', ['checklist_type_concept_id', 'checklist_version', 'item_code'], true, 'btree'],
  ['surgical_safety_responses', 'ix_surgical_safety_responses_surgical_safety_checklist_id', ['surgical_safety_checklist_id'], false, 'btree'],
  ['surgical_safety_responses', 'ix_surgical_safety_responses_surgical_safety_item_id', ['surgical_safety_item_id'], false, 'btree'],
  ['surgical_safety_responses', 'ix_surgical_safety_responses_response_status_concept_id', ['response_status_concept_id'], false, 'btree'],
  ['surgical_safety_responses', 'ix_surgical_safety_responses_response_concept_id', ['response_concept_id'], false, 'btree'],
  ['surgical_safety_responses', 'ix_surgical_safety_responses_responded_by_profile_id', ['responded_by_profile_id'], false, 'btree'],
  ['surgical_safety_responses', 'brin_surgical_safety_responses_created_at', ['created_at'], false, 'brin'],
  ['surgical_safety_responses', 'uk_surgical_safety_responses_checklist_item', ['surgical_safety_checklist_id', 'surgical_safety_item_id'], true, 'btree'],
];
