import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `profiles`.
 * 121 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const profilesIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['administrator_profiles', 'ix_administrator_profiles_administrator_type_concept_id', ['administrator_type_concept_id'], false, 'btree'],
  ['administrator_profiles', 'ix_administrator_profiles_administrative_level_concept_id', ['administrative_level_concept_id'], false, 'btree'],
  ['administrator_profiles', 'ix_administrator_profiles_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['administrator_profiles', 'ix_administrator_profiles_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['emergency_staff_profiles', 'ix_emergency_staff_profiles_staff_type_concept_id', ['staff_type_concept_id'], false, 'btree'],
  ['emergency_staff_profiles', 'ix_emergency_staff_profiles_availability_status_concept_id', ['availability_status_concept_id'], false, 'btree'],
  ['emergency_staff_profiles', 'ix_emergency_staff_profiles_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['emergency_staff_profiles', 'ix_emergency_staff_profiles_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['health_practitioner_profiles', 'uq_health_practitioner_profiles_practitioner_code', ['practitioner_code'], true, 'btree'],
  ['health_practitioner_profiles', 'ix_health_practitioner_profiles_practitioner_category__a69797c8', ['practitioner_category_concept_id'], false, 'btree'],
  ['health_practitioner_profiles', 'ix_health_practitioner_profiles_verification_status_concept_id', ['verification_status_concept_id'], false, 'btree'],
  ['health_practitioner_profiles', 'ix_health_practitioner_profiles_practice_status_concept_id', ['practice_status_concept_id'], false, 'btree'],
  ['health_practitioner_profiles', 'ix_health_practitioner_profiles_photo_file_id', ['photo_file_id'], false, 'btree'],
  ['health_practitioner_profiles', 'ix_health_practitioner_profiles_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['health_practitioner_profiles', 'ix_health_practitioner_profiles_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['insurance_representative_profiles', 'ix_insurance_representative_profiles_representative_ty_e1930540', ['representative_type_concept_id'], false, 'btree'],
  ['insurance_representative_profiles', 'ix_insurance_representative_profiles_role_concept_id', ['role_concept_id'], false, 'btree'],
  ['insurance_representative_profiles', 'ix_insurance_representative_profiles_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['insurance_representative_profiles', 'ix_insurance_representative_profiles_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['jurisdiction_authorizations', 'ix_jurisdiction_authorizations_practitioner_profile_id', ['practitioner_profile_id'], false, 'btree'],
  ['jurisdiction_authorizations', 'ix_jurisdiction_authorizations_jurisdiction_concept_id', ['jurisdiction_concept_id'], false, 'btree'],
  ['jurisdiction_authorizations', 'ix_jurisdiction_authorizations_practice_scope_concept_id', ['practice_scope_concept_id'], false, 'btree'],
  ['jurisdiction_authorizations', 'ix_jurisdiction_authorizations_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['jurisdiction_authorizations', 'ix_jurisdiction_authorizations_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['jurisdiction_authorizations', 'ix_jurisdiction_authorizations_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['patient_identity_links', 'ix_patient_identity_links_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['patient_identity_links', 'ix_patient_identity_links_source_tenant_id', ['source_tenant_id'], false, 'btree'],
  ['patient_identity_links', 'ix_patient_identity_links_link_type_concept_id', ['link_type_concept_id'], false, 'btree'],
  ['patient_identity_links', 'ix_patient_identity_links_verification_status_concept_id', ['verification_status_concept_id'], false, 'btree'],
  ['patient_identity_links', 'ix_patient_identity_links_verified_by_user_id', ['verified_by_user_id'], false, 'btree'],
  ['patient_identity_links', 'ix_patient_identity_links_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['patient_identity_links', 'ix_patient_identity_links_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['patient_identity_links', 'ix_patient_identity_links_source_tenant_id_updated_at', ['source_tenant_id', 'updated_at desc'], false, 'btree'],
  ['patient_identity_links', 'ix_patient_identity_links_patient_profile_id_updated_at', ['source_tenant_id', 'patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['patient_identity_links', 'uq_patient_identity_source', ['source_tenant_id', 'source_system_uri', 'source_patient_identifier'], true, 'btree'],
  ['patient_merge_events', 'ix_patient_merge_events_surviving_patient_profile_id', ['surviving_patient_profile_id'], false, 'btree'],
  ['patient_merge_events', 'ix_patient_merge_events_merged_patient_profile_id', ['merged_patient_profile_id'], false, 'btree'],
  ['patient_merge_events', 'ix_patient_merge_events_reason_concept_id', ['reason_concept_id'], false, 'btree'],
  ['patient_merge_events', 'ix_patient_merge_events_decision_status_concept_id', ['decision_status_concept_id'], false, 'btree'],
  ['patient_merge_events', 'ix_patient_merge_events_approved_by_user_id', ['approved_by_user_id'], false, 'btree'],
  ['patient_merge_events', 'ix_patient_merge_events_reversal_of_event_id', ['reversal_of_event_id'], false, 'btree'],
  ['patient_merge_events', 'ix_patient_merge_events_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['patient_merge_events', 'brin_patient_merge_events_recorded_at', ['recorded_at'], false, 'brin'],
  ['patient_portal_proxies', 'ix_patient_portal_proxies_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['patient_portal_proxies', 'ix_patient_portal_proxies_proxy_user_id', ['proxy_user_id'], false, 'btree'],
  ['patient_portal_proxies', 'ix_patient_portal_proxies_related_person_id', ['related_person_id'], false, 'btree'],
  ['patient_portal_proxies', 'ix_patient_portal_proxies_scope_value_set_id', ['scope_value_set_id'], false, 'btree'],
  ['patient_portal_proxies', 'ix_patient_portal_proxies_legal_basis_record_id', ['legal_basis_record_id'], false, 'btree'],
  ['patient_portal_proxies', 'ix_patient_portal_proxies_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['patient_portal_proxies', 'ix_patient_portal_proxies_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['patient_portal_proxies', 'ix_patient_portal_proxies_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['patient_portal_proxies', 'ix_patient_portal_proxies_patient_profile_id_updated_at', ['patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['patient_profiles', 'uq_patient_profiles_patient_code', ['patient_code'], true, 'btree'],
  ['patient_profiles', 'uq_patient_profiles_master_patient_index_code', ['master_patient_index_code'], true, 'btree'],
  ['patient_profiles', 'ix_patient_profiles_abo_group_concept_id', ['abo_group_concept_id'], false, 'btree'],
  ['patient_profiles', 'ix_patient_profiles_rh_factor_concept_id', ['rh_factor_concept_id'], false, 'btree'],
  ['patient_profiles', 'ix_patient_profiles_insurance_status_concept_id', ['insurance_status_concept_id'], false, 'btree'],
  ['patient_profiles', 'ix_patient_profiles_clinical_language_concept_id', ['clinical_language_concept_id'], false, 'btree'],
  ['patient_profiles', 'ix_patient_profiles_record_linkage_status_concept_id', ['record_linkage_status_concept_id'], false, 'btree'],
  ['patient_profiles', 'ix_patient_profiles_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['patient_profiles', 'ix_patient_profiles_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['persons', 'ix_persons_person_status_concept_id', ['person_status_concept_id'], false, 'btree'],
  ['persons', 'ix_persons_administrative_gender_concept_id', ['administrative_gender_concept_id'], false, 'btree'],
  ['persons', 'ix_persons_sex_at_birth_concept_id', ['sex_at_birth_concept_id'], false, 'btree'],
  ['persons', 'ix_persons_gender_identity_concept_id', ['gender_identity_concept_id'], false, 'btree'],
  ['persons', 'ix_persons_vital_status_concept_id', ['vital_status_concept_id'], false, 'btree'],
  ['persons', 'ix_persons_nationality_concept_id', ['nationality_concept_id'], false, 'btree'],
  ['persons', 'ix_persons_preferred_language_concept_id', ['preferred_language_concept_id'], false, 'btree'],
  ['persons', 'ix_persons_merge_survivor_person_id', ['merge_survivor_person_id'], false, 'btree'],
  ['persons', 'ix_persons_photo_file_id', ['photo_file_id'], false, 'btree'],
  ['persons', 'ix_persons_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['persons', 'ix_persons_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['person_account_links', 'ix_person_account_links_person_id', ['person_id'], false, 'btree'],
  ['person_account_links', 'ix_person_account_links_user_id', ['user_id'], false, 'btree'],
  ['person_account_links', 'ix_person_account_links_link_type_concept_id', ['link_type_concept_id'], false, 'btree'],
  ['person_account_links', 'ix_person_account_links_verification_status_concept_id', ['verification_status_concept_id'], false, 'btree'],
  ['person_account_links', 'ix_person_account_links_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['person_account_links', 'ix_person_account_links_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['person_account_links', 'ix_person_account_links_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['person_profiles', 'ix_person_profiles_person_id', ['person_id'], false, 'btree'],
  ['person_profiles', 'ix_person_profiles_profile_type_concept_id', ['profile_type_concept_id'], false, 'btree'],
  ['person_profiles', 'ix_person_profiles_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['person_profiles', 'ix_person_profiles_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['person_profiles', 'ix_person_profiles_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['person_profiles', 'uq_person_profiles_person_type', ['person_id', 'profile_type_concept_id'], true, 'btree'],
  ['practitioner_languages', 'ix_practitioner_languages_practitioner_profile_id', ['practitioner_profile_id'], false, 'btree'],
  ['practitioner_languages', 'ix_practitioner_languages_language_concept_id', ['language_concept_id'], false, 'btree'],
  ['practitioner_languages', 'ix_practitioner_languages_proficiency_concept_id', ['proficiency_concept_id'], false, 'btree'],
  ['practitioner_languages', 'ix_practitioner_languages_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['practitioner_languages', 'ix_practitioner_languages_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['practitioner_specialties', 'ix_practitioner_specialties_practitioner_profile_id', ['practitioner_profile_id'], false, 'btree'],
  ['practitioner_specialties', 'ix_practitioner_specialties_specialty_concept_id', ['specialty_concept_id'], false, 'btree'],
  ['practitioner_specialties', 'ix_practitioner_specialties_supporting_credential_id', ['supporting_credential_id'], false, 'btree'],
  ['practitioner_specialties', 'ix_practitioner_specialties_specialty_role_concept_id', ['specialty_role_concept_id'], false, 'btree'],
  ['practitioner_specialties', 'ix_practitioner_specialties_verification_status_concept_id', ['verification_status_concept_id'], false, 'btree'],
  ['practitioner_specialties', 'ix_practitioner_specialties_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['practitioner_specialties', 'ix_practitioner_specialties_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['practitioner_specialties', 'uq_practitioner_specialty_active', ['practitioner_profile_id', 'specialty_concept_id'], true, 'btree', 'valid_to IS NULL'],
  ['professional_credentials', 'ix_professional_credentials_practitioner_profile_id', ['practitioner_profile_id'], false, 'btree'],
  ['professional_credentials', 'ix_professional_credentials_credential_type_concept_id', ['credential_type_concept_id'], false, 'btree'],
  ['professional_credentials', 'ix_professional_credentials_issuing_authority_tenant_id', ['issuing_authority_tenant_id'], false, 'btree'],
  ['professional_credentials', 'ix_professional_credentials_issuing_country_concept_id', ['issuing_country_concept_id'], false, 'btree'],
  ['professional_credentials', 'ix_professional_credentials_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['professional_credentials', 'ix_professional_credentials_file_id', ['file_id'], false, 'btree'],
  ['professional_credentials', 'ix_professional_credentials_verified_by_user_id', ['verified_by_user_id'], false, 'btree'],
  ['professional_credentials', 'ix_professional_credentials_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['professional_credentials', 'ix_professional_credentials_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['provider_operator_profiles', 'ix_provider_operator_profiles_operator_type_concept_id', ['operator_type_concept_id'], false, 'btree'],
  ['provider_operator_profiles', 'ix_provider_operator_profiles_role_concept_id', ['role_concept_id'], false, 'btree'],
  ['provider_operator_profiles', 'ix_provider_operator_profiles_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['provider_operator_profiles', 'ix_provider_operator_profiles_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['related_persons', 'ix_related_persons_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['related_persons', 'ix_related_persons_person_id', ['person_id'], false, 'btree'],
  ['related_persons', 'ix_related_persons_relationship_concept_id', ['relationship_concept_id'], false, 'btree'],
  ['related_persons', 'ix_related_persons_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['related_persons', 'ix_related_persons_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['related_persons', 'ix_related_persons_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['related_persons', 'ix_related_persons_patient_profile_id_updated_at', ['patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['secretary_profiles', 'ix_secretary_profiles_role_concept_id', ['role_concept_id'], false, 'btree'],
  ['secretary_profiles', 'ix_secretary_profiles_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['secretary_profiles', 'ix_secretary_profiles_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
];
