import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `promotions`.
 * 80 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const promotionsIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['coupons', 'uq_coupons_code', ['code'], true, 'btree'],
  ['coupons', 'ix_coupons_promotion_id', ['promotion_id'], false, 'btree'],
  ['coupons', 'ix_coupons_coupon_type_concept_id', ['coupon_type_concept_id'], false, 'btree'],
  ['coupons', 'ix_coupons_assigned_member_type_concept_id', ['assigned_member_type_concept_id'], false, 'btree'],
  ['coupons', 'ix_coupons_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['coupons', 'ix_coupons_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['coupons', 'ix_coupons_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['discount_rules', 'ix_discount_rules_promotion_id', ['promotion_id'], false, 'btree'],
  ['discount_rules', 'ix_discount_rules_discount_type_concept_id', ['discount_type_concept_id'], false, 'btree'],
  ['discount_rules', 'ix_discount_rules_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['discount_rules', 'ix_discount_rules_applies_to_concept_id', ['applies_to_concept_id'], false, 'btree'],
  ['discount_rules', 'ix_discount_rules_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['discount_rules', 'ix_discount_rules_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['earning_rules', 'ix_earning_rules_loyalty_program_id', ['loyalty_program_id'], false, 'btree'],
  ['earning_rules', 'ix_earning_rules_event_type_concept_id', ['event_type_concept_id'], false, 'btree'],
  ['earning_rules', 'ix_earning_rules_award_type_concept_id', ['award_type_concept_id'], false, 'btree'],
  ['earning_rules', 'ix_earning_rules_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['earning_rules', 'ix_earning_rules_period_concept_id', ['period_concept_id'], false, 'btree'],
  ['earning_rules', 'ix_earning_rules_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['earning_rules', 'ix_earning_rules_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['loyalty_memberships', 'ix_loyalty_memberships_loyalty_program_id', ['loyalty_program_id'], false, 'btree'],
  ['loyalty_memberships', 'ix_loyalty_memberships_member_type_concept_id', ['member_type_concept_id'], false, 'btree'],
  ['loyalty_memberships', 'ix_loyalty_memberships_current_tier_id', ['current_tier_id'], false, 'btree'],
  ['loyalty_memberships', 'ix_loyalty_memberships_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['loyalty_memberships', 'ix_loyalty_memberships_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['loyalty_memberships', 'ix_loyalty_memberships_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['loyalty_programs', 'uq_loyalty_programs_code', ['code'], true, 'btree'],
  ['loyalty_programs', 'ix_loyalty_programs_tenant_id', ['tenant_id'], false, 'btree'],
  ['loyalty_programs', 'ix_loyalty_programs_program_type_concept_id', ['program_type_concept_id'], false, 'btree'],
  ['loyalty_programs', 'ix_loyalty_programs_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['loyalty_programs', 'ix_loyalty_programs_expiry_policy_concept_id', ['expiry_policy_concept_id'], false, 'btree'],
  ['loyalty_programs', 'ix_loyalty_programs_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['loyalty_programs', 'ix_loyalty_programs_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['loyalty_programs', 'ix_loyalty_programs_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['loyalty_programs', 'ix_loyalty_programs_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['loyalty_tiers', 'ix_loyalty_tiers_loyalty_program_id', ['loyalty_program_id'], false, 'btree'],
  ['loyalty_tiers', 'ix_loyalty_tiers_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['loyalty_tiers', 'ix_loyalty_tiers_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['member_referrals', 'uq_member_referrals_referral_code', ['referral_code'], true, 'btree'],
  ['member_referrals', 'ix_member_referrals_referral_program_id', ['referral_program_id'], false, 'btree'],
  ['member_referrals', 'ix_member_referrals_referrer_user_id', ['referrer_user_id'], false, 'btree'],
  ['member_referrals', 'ix_member_referrals_referee_user_id', ['referee_user_id'], false, 'btree'],
  ['member_referrals', 'ix_member_referrals_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['member_referrals', 'ix_member_referrals_referrer_reward_ledger_id', ['referrer_reward_ledger_id'], false, 'btree'],
  ['member_referrals', 'ix_member_referrals_referee_reward_ledger_id', ['referee_reward_ledger_id'], false, 'btree'],
  ['member_referrals', 'ix_member_referrals_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['member_referrals', 'ix_member_referrals_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['points_ledger_entries', 'uq_points_ledger_entries_idempotency_key', ['idempotency_key'], true, 'btree'],
  ['points_ledger_entries', 'ix_points_ledger_entries_loyalty_membership_id', ['loyalty_membership_id'], false, 'btree'],
  ['points_ledger_entries', 'ix_points_ledger_entries_direction_concept_id', ['direction_concept_id'], false, 'btree'],
  ['points_ledger_entries', 'ix_points_ledger_entries_reason_concept_id', ['reason_concept_id'], false, 'btree'],
  ['points_ledger_entries', 'ix_points_ledger_entries_earning_rule_id', ['earning_rule_id'], false, 'btree'],
  ['points_ledger_entries', 'ix_points_ledger_entries_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['promotions', 'uq_promotions_code', ['code'], true, 'btree'],
  ['promotions', 'ix_promotions_tenant_id', ['tenant_id'], false, 'btree'],
  ['promotions', 'ix_promotions_promotion_type_concept_id', ['promotion_type_concept_id'], false, 'btree'],
  ['promotions', 'ix_promotions_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['promotions', 'ix_promotions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['promotions', 'ix_promotions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['promotions', 'ix_promotions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['promotions', 'ix_promotions_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['redemptions', 'ix_redemptions_promotion_id', ['promotion_id'], false, 'btree'],
  ['redemptions', 'ix_redemptions_coupon_id', ['coupon_id'], false, 'btree'],
  ['redemptions', 'ix_redemptions_discount_rule_id', ['discount_rule_id'], false, 'btree'],
  ['redemptions', 'ix_redemptions_redeemer_type_concept_id', ['redeemer_type_concept_id'], false, 'btree'],
  ['redemptions', 'ix_redemptions_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['redemptions', 'ix_redemptions_payment_intent_id', ['payment_intent_id'], false, 'btree'],
  ['redemptions', 'ix_redemptions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['redemptions', 'ix_redemptions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['redemptions', 'ix_redemptions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['referral_programs', 'uq_referral_programs_code', ['code'], true, 'btree'],
  ['referral_programs', 'ix_referral_programs_tenant_id', ['tenant_id'], false, 'btree'],
  ['referral_programs', 'ix_referral_programs_referrer_award_type_concept_id', ['referrer_award_type_concept_id'], false, 'btree'],
  ['referral_programs', 'ix_referral_programs_referee_award_type_concept_id', ['referee_award_type_concept_id'], false, 'btree'],
  ['referral_programs', 'ix_referral_programs_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['referral_programs', 'ix_referral_programs_qualifying_event_concept_id', ['qualifying_event_concept_id'], false, 'btree'],
  ['referral_programs', 'ix_referral_programs_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['referral_programs', 'ix_referral_programs_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['referral_programs', 'ix_referral_programs_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['referral_programs', 'ix_referral_programs_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
];
