import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `qa_lab`.
 * 92 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const qaLabIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['assertion_results', 'ix_assertion_results_test_case_result_id', ['test_case_result_id'], false, 'btree'],
  ['assertion_results', 'ix_assertion_results_test_assertion_id', ['test_assertion_id'], false, 'btree'],
  ['assertion_results', 'ix_assertion_results_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['assertion_results', 'brin_assertion_results_recorded_at', ['recorded_at'], false, 'brin'],
  ['request_payloads', 'ix_request_payloads_test_case_result_id', ['test_case_result_id'], false, 'btree'],
  ['request_payloads', 'ix_request_payloads_direction_concept_id', ['direction_concept_id'], false, 'btree'],
  ['request_payloads', 'ix_request_payloads_http_method_concept_id', ['http_method_concept_id'], false, 'btree'],
  ['request_payloads', 'ix_request_payloads_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['request_payloads', 'brin_request_payloads_recorded_at', ['recorded_at'], false, 'brin'],
  ['response_payloads', 'ix_response_payloads_test_case_result_id', ['test_case_result_id'], false, 'btree'],
  ['response_payloads', 'ix_response_payloads_request_payload_id', ['request_payload_id'], false, 'btree'],
  ['response_payloads', 'ix_response_payloads_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['response_payloads', 'brin_response_payloads_recorded_at', ['recorded_at'], false, 'brin'],
  ['run_artifacts', 'ix_run_artifacts_test_run_id', ['test_run_id'], false, 'btree'],
  ['run_artifacts', 'ix_run_artifacts_test_case_result_id', ['test_case_result_id'], false, 'btree'],
  ['run_artifacts', 'ix_run_artifacts_artifact_type_concept_id', ['artifact_type_concept_id'], false, 'btree'],
  ['run_artifacts', 'ix_run_artifacts_file_id', ['file_id'], false, 'btree'],
  ['run_artifacts', 'ix_run_artifacts_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['run_artifacts', 'ix_run_artifacts_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['test_assertions', 'ix_test_assertions_test_case_id', ['test_case_id'], false, 'btree'],
  ['test_assertions', 'ix_test_assertions_assertion_type_concept_id', ['assertion_type_concept_id'], false, 'btree'],
  ['test_assertions', 'ix_test_assertions_operator_concept_id', ['operator_concept_id'], false, 'btree'],
  ['test_assertions', 'ix_test_assertions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['test_assertions', 'ix_test_assertions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['test_cases', 'ix_test_cases_suite_id', ['suite_id'], false, 'btree'],
  ['test_cases', 'ix_test_cases_case_type_concept_id', ['case_type_concept_id'], false, 'btree'],
  ['test_cases', 'ix_test_cases_endpoint_id', ['endpoint_id'], false, 'btree'],
  ['test_cases', 'ix_test_cases_http_method_concept_id', ['http_method_concept_id'], false, 'btree'],
  ['test_cases', 'ix_test_cases_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['test_cases', 'ix_test_cases_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['test_cases', 'ix_test_cases_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['test_case_results', 'ix_test_case_results_test_run_id', ['test_run_id'], false, 'btree'],
  ['test_case_results', 'ix_test_case_results_test_case_id', ['test_case_id'], false, 'btree'],
  ['test_case_results', 'ix_test_case_results_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['test_case_results', 'ix_test_case_results_error_type_concept_id', ['error_type_concept_id'], false, 'btree'],
  ['test_case_results', 'ix_test_case_results_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['test_case_results', 'ix_test_case_results_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['test_defects', 'uq_test_defects_defect_number', ['defect_number'], true, 'btree'],
  ['test_defects', 'ix_test_defects_tenant_id', ['tenant_id'], false, 'btree'],
  ['test_defects', 'ix_test_defects_test_case_id', ['test_case_id'], false, 'btree'],
  ['test_defects', 'ix_test_defects_test_case_result_id', ['test_case_result_id'], false, 'btree'],
  ['test_defects', 'ix_test_defects_defect_type_concept_id', ['defect_type_concept_id'], false, 'btree'],
  ['test_defects', 'ix_test_defects_severity_concept_id', ['severity_concept_id'], false, 'btree'],
  ['test_defects', 'ix_test_defects_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['test_defects', 'ix_test_defects_assigned_to_user_id', ['assigned_to_user_id'], false, 'btree'],
  ['test_defects', 'ix_test_defects_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['test_defects', 'ix_test_defects_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['test_defects', 'ix_test_defects_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['test_defects', 'ix_test_defects_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['test_environments', 'uq_test_environments_code', ['code'], true, 'btree'],
  ['test_environments', 'ix_test_environments_environment_concept_id', ['environment_concept_id'], false, 'btree'],
  ['test_environments', 'ix_test_environments_tenant_id', ['tenant_id'], false, 'btree'],
  ['test_environments', 'ix_test_environments_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['test_environments', 'ix_test_environments_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['test_environments', 'ix_test_environments_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['test_environments', 'ix_test_environments_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['test_fixtures', 'ix_test_fixtures_suite_id', ['suite_id'], false, 'btree'],
  ['test_fixtures', 'ix_test_fixtures_test_case_id', ['test_case_id'], false, 'btree'],
  ['test_fixtures', 'ix_test_fixtures_file_id', ['file_id'], false, 'btree'],
  ['test_fixtures', 'ix_test_fixtures_fixture_type_concept_id', ['fixture_type_concept_id'], false, 'btree'],
  ['test_fixtures', 'ix_test_fixtures_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['test_fixtures', 'ix_test_fixtures_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['test_runs', 'uq_test_runs_run_number', ['run_number'], true, 'btree'],
  ['test_runs', 'ix_test_runs_suite_id', ['suite_id'], false, 'btree'],
  ['test_runs', 'ix_test_runs_environment_id', ['environment_id'], false, 'btree'],
  ['test_runs', 'ix_test_runs_tenant_id', ['tenant_id'], false, 'btree'],
  ['test_runs', 'ix_test_runs_trigger_concept_id', ['trigger_concept_id'], false, 'btree'],
  ['test_runs', 'ix_test_runs_triggered_by_user_id', ['triggered_by_user_id'], false, 'btree'],
  ['test_runs', 'ix_test_runs_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['test_runs', 'ix_test_runs_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['test_runs', 'ix_test_runs_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['test_runs', 'ix_test_runs_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['test_schedules', 'uq_test_schedules_code', ['code'], true, 'btree'],
  ['test_schedules', 'ix_test_schedules_suite_id', ['suite_id'], false, 'btree'],
  ['test_schedules', 'ix_test_schedules_environment_id', ['environment_id'], false, 'btree'],
  ['test_schedules', 'ix_test_schedules_tenant_id', ['tenant_id'], false, 'btree'],
  ['test_schedules', 'ix_test_schedules_trigger_concept_id', ['trigger_concept_id'], false, 'btree'],
  ['test_schedules', 'ix_test_schedules_concurrency_policy_concept_id', ['concurrency_policy_concept_id'], false, 'btree'],
  ['test_schedules', 'ix_test_schedules_last_run_id', ['last_run_id'], false, 'btree'],
  ['test_schedules', 'ix_test_schedules_notify_channel_concept_id', ['notify_channel_concept_id'], false, 'btree'],
  ['test_schedules', 'ix_test_schedules_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['test_schedules', 'ix_test_schedules_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['test_schedules', 'ix_test_schedules_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['test_schedules', 'ix_test_schedules_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['test_suites', 'uq_test_suites_code', ['code'], true, 'btree'],
  ['test_suites', 'ix_test_suites_tenant_id', ['tenant_id'], false, 'btree'],
  ['test_suites', 'ix_test_suites_target_system_concept_id', ['target_system_concept_id'], false, 'btree'],
  ['test_suites', 'ix_test_suites_suite_type_concept_id', ['suite_type_concept_id'], false, 'btree'],
  ['test_suites', 'ix_test_suites_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['test_suites', 'ix_test_suites_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['test_suites', 'ix_test_suites_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['test_suites', 'ix_test_suites_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
];
