import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `read_models`.
 * 86 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const readModelsIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['frontend_page_views', 'ix_frontend_page_views_frontend_route_id', ['frontend_route_id'], false, 'btree'],
  ['frontend_page_views', 'ix_frontend_page_views_read_model_definition_id', ['read_model_definition_id'], false, 'btree'],
  ['frontend_page_views', 'ix_frontend_page_views_view_type_concept_id', ['view_type_concept_id'], false, 'btree'],
  ['frontend_page_views', 'ix_frontend_page_views_field_mask_policy_id', ['field_mask_policy_id'], false, 'btree'],
  ['frontend_page_views', 'ix_frontend_page_views_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['frontend_page_views', 'ix_frontend_page_views_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['frontend_page_views', 'ix_frontend_page_views_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['frontend_page_views', 'uq_frontend_page_views_route_code', ['frontend_route_id', 'view_code'], true, 'btree'],
  ['frontend_routes', 'ix_frontend_routes_portal_surface_id', ['portal_surface_id'], false, 'btree'],
  ['frontend_routes', 'ix_frontend_routes_required_permission_id', ['required_permission_id'], false, 'btree'],
  ['frontend_routes', 'ix_frontend_routes_purpose_of_use_concept_id', ['purpose_of_use_concept_id'], false, 'btree'],
  ['frontend_routes', 'ix_frontend_routes_cache_policy_concept_id', ['cache_policy_concept_id'], false, 'btree'],
  ['frontend_routes', 'ix_frontend_routes_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['frontend_routes', 'ix_frontend_routes_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['frontend_routes', 'ix_frontend_routes_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['frontend_routes', 'uq_frontend_routes_portal_code', ['portal_surface_id', 'route_code'], true, 'btree'],
  ['frontend_routes', 'uq_frontend_routes_pattern', ['portal_surface_id', 'route_pattern'], true, 'btree'],
  ['frontend_view_actions', 'ix_frontend_view_actions_frontend_page_view_id', ['frontend_page_view_id'], false, 'btree'],
  ['frontend_view_actions', 'ix_frontend_view_actions_action_type_concept_id', ['action_type_concept_id'], false, 'btree'],
  ['frontend_view_actions', 'ix_frontend_view_actions_required_permission_id', ['required_permission_id'], false, 'btree'],
  ['frontend_view_actions', 'ix_frontend_view_actions_allowed_state_value_set_id', ['allowed_state_value_set_id'], false, 'btree'],
  ['frontend_view_actions', 'ix_frontend_view_actions_confirmation_policy_concept_id', ['confirmation_policy_concept_id'], false, 'btree'],
  ['frontend_view_actions', 'ix_frontend_view_actions_prominence_concept_id', ['prominence_concept_id'], false, 'btree'],
  ['frontend_view_actions', 'ix_frontend_view_actions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['frontend_view_actions', 'ix_frontend_view_actions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['frontend_view_actions', 'ix_frontend_view_actions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['frontend_view_actions', 'uq_frontend_view_actions_code', ['frontend_page_view_id', 'action_code'], true, 'btree'],
  ['frontend_view_fields', 'ix_frontend_view_fields_frontend_page_view_id', ['frontend_page_view_id'], false, 'btree'],
  ['frontend_view_fields', 'ix_frontend_view_fields_display_component_concept_id', ['display_component_concept_id'], false, 'btree'],
  ['frontend_view_fields', 'ix_frontend_view_fields_permission_id', ['permission_id'], false, 'btree'],
  ['frontend_view_fields', 'ix_frontend_view_fields_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['frontend_view_fields', 'ix_frontend_view_fields_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['frontend_view_fields', 'ix_frontend_view_fields_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['frontend_view_fields', 'uq_frontend_view_fields_code', ['frontend_page_view_id', 'field_code'], true, 'btree'],
  ['frontend_view_filters', 'ix_frontend_view_filters_frontend_page_view_id', ['frontend_page_view_id'], false, 'btree'],
  ['frontend_view_filters', 'ix_frontend_view_filters_operator_value_set_id', ['operator_value_set_id'], false, 'btree'],
  ['frontend_view_filters', 'ix_frontend_view_filters_input_type_concept_id', ['input_type_concept_id'], false, 'btree'],
  ['frontend_view_filters', 'ix_frontend_view_filters_value_set_id', ['value_set_id'], false, 'btree'],
  ['frontend_view_filters', 'ix_frontend_view_filters_dynamic_enum_definition_id', ['dynamic_enum_definition_id'], false, 'btree'],
  ['frontend_view_filters', 'ix_frontend_view_filters_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['frontend_view_filters', 'ix_frontend_view_filters_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['frontend_view_filters', 'ix_frontend_view_filters_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['frontend_view_filters', 'uq_frontend_view_filters_code', ['frontend_page_view_id', 'filter_code'], true, 'btree'],
  ['frontend_view_kpis', 'ix_frontend_view_kpis_frontend_page_view_id', ['frontend_page_view_id'], false, 'btree'],
  ['frontend_view_kpis', 'ix_frontend_view_kpis_unit_concept_id', ['unit_concept_id'], false, 'btree'],
  ['frontend_view_kpis', 'ix_frontend_view_kpis_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['frontend_view_kpis', 'ix_frontend_view_kpis_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['frontend_view_kpis', 'ix_frontend_view_kpis_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['frontend_view_sort_options', 'ix_frontend_view_sort_options_frontend_page_view_id', ['frontend_page_view_id'], false, 'btree'],
  ['frontend_view_sort_options', 'ix_frontend_view_sort_options_direction_concept_id', ['direction_concept_id'], false, 'btree'],
  ['frontend_view_sort_options', 'ix_frontend_view_sort_options_nulls_position_concept_id', ['nulls_position_concept_id'], false, 'btree'],
  ['frontend_view_sort_options', 'ix_frontend_view_sort_options_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['frontend_view_sort_options', 'ix_frontend_view_sort_options_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['frontend_view_sort_options', 'ix_frontend_view_sort_options_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['frontend_view_sort_options', 'uq_frontend_view_sort_code', ['frontend_page_view_id', 'sort_code'], true, 'btree'],
  ['frontend_view_states', 'ix_frontend_view_states_frontend_page_view_id', ['frontend_page_view_id'], false, 'btree'],
  ['frontend_view_states', 'ix_frontend_view_states_state_type_concept_id', ['state_type_concept_id'], false, 'btree'],
  ['frontend_view_states', 'ix_frontend_view_states_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['frontend_view_states', 'ix_frontend_view_states_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['frontend_view_states', 'ix_frontend_view_states_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['portal_surfaces', 'uq_portal_surfaces_portal_code', ['portal_code'], true, 'btree'],
  ['portal_surfaces', 'ix_portal_surfaces_portal_type_concept_id', ['portal_type_concept_id'], false, 'btree'],
  ['portal_surfaces', 'ix_portal_surfaces_audience_role_value_set_id', ['audience_role_value_set_id'], false, 'btree'],
  ['portal_surfaces', 'ix_portal_surfaces_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['portal_surfaces', 'ix_portal_surfaces_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['portal_surfaces', 'ix_portal_surfaces_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['read_model_definitions', 'ix_read_model_definitions_object_type_concept_id', ['object_type_concept_id'], false, 'btree'],
  ['read_model_definitions', 'ix_read_model_definitions_refresh_mode_concept_id', ['refresh_mode_concept_id'], false, 'btree'],
  ['read_model_definitions', 'ix_read_model_definitions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['read_model_definitions', 'ix_read_model_definitions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['read_model_definitions', 'ix_read_model_definitions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['read_model_definitions', 'uq_read_model_definition_version', ['schema_name', 'object_name', 'version_number'], true, 'btree'],
  ['read_model_dependencies', 'ix_read_model_dependencies_read_model_definition_id', ['read_model_definition_id'], false, 'btree'],
  ['read_model_dependencies', 'ix_read_model_dependencies_dependency_type_concept_id', ['dependency_type_concept_id'], false, 'btree'],
  ['read_model_refresh_runs', 'ix_read_model_refresh_runs_read_model_definition_id', ['read_model_definition_id'], false, 'btree'],
  ['read_model_refresh_runs', 'ix_read_model_refresh_runs_refresh_type_concept_id', ['refresh_type_concept_id'], false, 'btree'],
  ['read_model_refresh_runs', 'ix_read_model_refresh_runs_result_concept_id', ['result_concept_id'], false, 'btree'],
  ['read_model_refresh_runs', 'brin_read_model_refresh_runs_created_at', ['created_at'], false, 'brin'],
  ['user_view_preferences', 'ix_user_view_preferences_user_id', ['user_id'], false, 'btree'],
  ['user_view_preferences', 'ix_user_view_preferences_frontend_page_view_id', ['frontend_page_view_id'], false, 'btree'],
  ['user_view_preferences', 'ix_user_view_preferences_tenant_id', ['tenant_id'], false, 'btree'],
  ['user_view_preferences', 'ix_user_view_preferences_density_concept_id', ['density_concept_id'], false, 'btree'],
  ['user_view_preferences', 'ix_user_view_preferences_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['user_view_preferences', 'ix_user_view_preferences_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['user_view_preferences', 'ix_user_view_preferences_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['user_view_preferences', 'ix_user_view_preferences_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
];
