import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `reporting`.
 * 79 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const reportingIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['dashboard_widgets', 'ix_dashboard_widgets_dashboard_id', ['dashboard_id'], false, 'btree'],
  ['dashboard_widgets', 'ix_dashboard_widgets_report_definition_id', ['report_definition_id'], false, 'btree'],
  ['dashboard_widgets', 'ix_dashboard_widgets_widget_type_concept_id', ['widget_type_concept_id'], false, 'btree'],
  ['dashboard_widgets', 'ix_dashboard_widgets_visualization_concept_id', ['visualization_concept_id'], false, 'btree'],
  ['dashboard_widgets', 'ix_dashboard_widgets_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['dashboard_widgets', 'ix_dashboard_widgets_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['dashboards', 'uq_dashboards_code', ['code'], true, 'btree'],
  ['dashboards', 'ix_dashboards_tenant_id', ['tenant_id'], false, 'btree'],
  ['dashboards', 'ix_dashboards_required_permission_id', ['required_permission_id'], false, 'btree'],
  ['dashboards', 'ix_dashboards_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['dashboards', 'ix_dashboards_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['dashboards', 'ix_dashboards_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['dashboards', 'ix_dashboards_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['report_columns', 'ix_report_columns_report_definition_id', ['report_definition_id'], false, 'btree'],
  ['report_columns', 'ix_report_columns_aggregation_concept_id', ['aggregation_concept_id'], false, 'btree'],
  ['report_columns', 'ix_report_columns_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['report_columns', 'ix_report_columns_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['report_data_sources', 'uq_report_data_sources_code', ['code'], true, 'btree'],
  ['report_data_sources', 'ix_report_data_sources_tenant_id', ['tenant_id'], false, 'btree'],
  ['report_data_sources', 'ix_report_data_sources_source_type_concept_id', ['source_type_concept_id'], false, 'btree'],
  ['report_data_sources', 'ix_report_data_sources_read_model_definition_id', ['read_model_definition_id'], false, 'btree'],
  ['report_data_sources', 'ix_report_data_sources_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['report_data_sources', 'ix_report_data_sources_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['report_data_sources', 'ix_report_data_sources_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['report_data_sources', 'ix_report_data_sources_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['report_definitions', 'uq_report_definitions_code', ['code'], true, 'btree'],
  ['report_definitions', 'ix_report_definitions_tenant_id', ['tenant_id'], false, 'btree'],
  ['report_definitions', 'ix_report_definitions_category_concept_id', ['category_concept_id'], false, 'btree'],
  ['report_definitions', 'ix_report_definitions_data_source_id', ['data_source_id'], false, 'btree'],
  ['report_definitions', 'ix_report_definitions_default_output_format_concept_id', ['default_output_format_concept_id'], false, 'btree'],
  ['report_definitions', 'ix_report_definitions_required_permission_id', ['required_permission_id'], false, 'btree'],
  ['report_definitions', 'ix_report_definitions_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['report_definitions', 'ix_report_definitions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['report_definitions', 'ix_report_definitions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['report_definitions', 'ix_report_definitions_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['report_distributions', 'ix_report_distributions_schedule_id', ['schedule_id'], false, 'btree'],
  ['report_distributions', 'ix_report_distributions_report_execution_id', ['report_execution_id'], false, 'btree'],
  ['report_distributions', 'ix_report_distributions_recipient_type_concept_id', ['recipient_type_concept_id'], false, 'btree'],
  ['report_distributions', 'ix_report_distributions_recipient_user_id', ['recipient_user_id'], false, 'btree'],
  ['report_distributions', 'ix_report_distributions_channel_id', ['channel_id'], false, 'btree'],
  ['report_distributions', 'ix_report_distributions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['report_distributions', 'ix_report_distributions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['report_distributions', 'ix_report_distributions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['report_executions', 'ix_report_executions_report_definition_id', ['report_definition_id'], false, 'btree'],
  ['report_executions', 'ix_report_executions_report_version_id', ['report_version_id'], false, 'btree'],
  ['report_executions', 'ix_report_executions_schedule_id', ['schedule_id'], false, 'btree'],
  ['report_executions', 'ix_report_executions_tenant_id', ['tenant_id'], false, 'btree'],
  ['report_executions', 'ix_report_executions_trigger_concept_id', ['trigger_concept_id'], false, 'btree'],
  ['report_executions', 'ix_report_executions_requested_by_user_id', ['requested_by_user_id'], false, 'btree'],
  ['report_executions', 'ix_report_executions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['report_executions', 'ix_report_executions_output_format_concept_id', ['output_format_concept_id'], false, 'btree'],
  ['report_executions', 'ix_report_executions_output_file_id', ['output_file_id'], false, 'btree'],
  ['report_executions', 'ix_report_executions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['report_executions', 'ix_report_executions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['report_executions', 'ix_report_executions_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['report_parameters', 'ix_report_parameters_report_definition_id', ['report_definition_id'], false, 'btree'],
  ['report_parameters', 'ix_report_parameters_value_set_id', ['value_set_id'], false, 'btree'],
  ['report_parameters', 'ix_report_parameters_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['report_parameters', 'ix_report_parameters_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['report_schedules', 'ix_report_schedules_report_definition_id', ['report_definition_id'], false, 'btree'],
  ['report_schedules', 'ix_report_schedules_tenant_id', ['tenant_id'], false, 'btree'],
  ['report_schedules', 'ix_report_schedules_output_format_concept_id', ['output_format_concept_id'], false, 'btree'],
  ['report_schedules', 'ix_report_schedules_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['report_schedules', 'ix_report_schedules_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['report_schedules', 'ix_report_schedules_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['report_schedules', 'ix_report_schedules_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['report_snapshots', 'ix_report_snapshots_report_execution_id', ['report_execution_id'], false, 'btree'],
  ['report_snapshots', 'ix_report_snapshots_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['report_snapshots', 'ix_report_snapshots_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['report_subscriptions', 'ix_report_subscriptions_report_schedule_id', ['report_schedule_id'], false, 'btree'],
  ['report_subscriptions', 'ix_report_subscriptions_subscriber_user_id', ['subscriber_user_id'], false, 'btree'],
  ['report_subscriptions', 'ix_report_subscriptions_channel_id', ['channel_id'], false, 'btree'],
  ['report_subscriptions', 'ix_report_subscriptions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['report_subscriptions', 'ix_report_subscriptions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['report_versions', 'ix_report_versions_report_definition_id', ['report_definition_id'], false, 'btree'],
  ['report_versions', 'ix_report_versions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['report_versions', 'ix_report_versions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['report_versions', 'ix_report_versions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['report_versions', 'uq_report_versions_report_definition_id_version', ['report_definition_id', 'version'], true, 'btree'],
];
