import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `scheduling`.
 * 109 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const schedulingIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['appointment_bookings', 'ix_appointment_bookings_tenant_id', ['tenant_id'], false, 'btree'],
  ['appointment_bookings', 'ix_appointment_bookings_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['appointment_bookings', 'ix_appointment_bookings_bookable_slot_id', ['bookable_slot_id'], false, 'btree'],
  ['appointment_bookings', 'ix_appointment_bookings_resource_id', ['resource_id'], false, 'btree'],
  ['appointment_bookings', 'ix_appointment_bookings_appointment_id', ['appointment_id'], false, 'btree'],
  ['appointment_bookings', 'ix_appointment_bookings_service_concept_id', ['service_concept_id'], false, 'btree'],
  ['appointment_bookings', 'ix_appointment_bookings_booking_channel_concept_id', ['booking_channel_concept_id'], false, 'btree'],
  ['appointment_bookings', 'ix_appointment_bookings_booked_by_user_id', ['booked_by_user_id'], false, 'btree'],
  ['appointment_bookings', 'ix_appointment_bookings_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['appointment_bookings', 'ix_appointment_bookings_booking_policy_id', ['booking_policy_id'], false, 'btree'],
  ['appointment_bookings', 'ix_appointment_bookings_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['appointment_bookings', 'ix_appointment_bookings_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['appointment_bookings', 'ix_appointment_bookings_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['appointment_bookings', 'ix_appointment_bookings_patient_profile_id_updated_at', ['tenant_id', 'patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['appointment_reminders', 'ix_appointment_reminders_booking_id', ['booking_id'], false, 'btree'],
  ['appointment_reminders', 'ix_appointment_reminders_channel_concept_id', ['channel_concept_id'], false, 'btree'],
  ['appointment_reminders', 'ix_appointment_reminders_notification_request_id', ['notification_request_id'], false, 'btree'],
  ['appointment_reminders', 'ix_appointment_reminders_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['appointment_reminders', 'ix_appointment_reminders_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['appointment_reminders', 'ix_appointment_reminders_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['availability_exceptions', 'ix_availability_exceptions_resource_id', ['resource_id'], false, 'btree'],
  ['availability_exceptions', 'ix_availability_exceptions_exception_type_concept_id', ['exception_type_concept_id'], false, 'btree'],
  ['availability_exceptions', 'ix_availability_exceptions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['availability_exceptions', 'ix_availability_exceptions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['availability_slots', 'ix_availability_slots_schedule_id', ['schedule_id'], false, 'btree'],
  ['availability_slots', 'ix_availability_slots_practitioner_profile_id', ['practitioner_profile_id'], false, 'btree'],
  ['availability_slots', 'ix_availability_slots_care_space_id', ['care_space_id'], false, 'btree'],
  ['availability_slots', 'ix_availability_slots_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['availability_slots', 'ix_availability_slots_appointment_id', ['appointment_id'], false, 'btree'],
  ['availability_slots', 'ix_availability_slots_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['availability_slots', 'ix_availability_slots_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['bookable_slots', 'ix_bookable_slots_resource_id', ['resource_id'], false, 'btree'],
  ['bookable_slots', 'ix_bookable_slots_schedule_template_id', ['schedule_template_id'], false, 'btree'],
  ['bookable_slots', 'ix_bookable_slots_service_concept_id', ['service_concept_id'], false, 'btree'],
  ['bookable_slots', 'ix_bookable_slots_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['bookable_slots', 'ix_bookable_slots_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['bookable_slots', 'ix_bookable_slots_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['booking_cancellations', 'ix_booking_cancellations_booking_id', ['booking_id'], false, 'btree'],
  ['booking_cancellations', 'ix_booking_cancellations_reason_concept_id', ['reason_concept_id'], false, 'btree'],
  ['booking_cancellations', 'ix_booking_cancellations_cancelled_by_user_id', ['cancelled_by_user_id'], false, 'btree'],
  ['booking_cancellations', 'ix_booking_cancellations_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['booking_cancellations', 'ix_booking_cancellations_fee_payment_intent_id', ['fee_payment_intent_id'], false, 'btree'],
  ['booking_cancellations', 'ix_booking_cancellations_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['booking_cancellations', 'ix_booking_cancellations_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['booking_cancellations', 'ix_booking_cancellations_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['booking_confirmation_rules', 'ix_booking_confirmation_rules_tenant_id', ['tenant_id'], false, 'btree'],
  ['booking_confirmation_rules', 'ix_booking_confirmation_rules_scope', ['scope_type_concept_id', 'scope_id'], false, 'btree'],
  ['booking_policies', 'ix_booking_policies_tenant_id', ['tenant_id'], false, 'btree'],
  ['booking_policies', 'ix_booking_policies_practice_id', ['practice_id'], false, 'btree'],
  ['booking_policies', 'ix_booking_policies_currency_concept_id', ['currency_concept_id'], false, 'btree'],
  ['booking_policies', 'ix_booking_policies_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['booking_policies', 'ix_booking_policies_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['booking_policies', 'ix_booking_policies_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['booking_policies', 'ix_booking_policies_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['booking_reschedules', 'ix_booking_reschedules_booking_id', ['booking_id'], false, 'btree'],
  ['booking_reschedules', 'ix_booking_reschedules_from_slot_id', ['from_slot_id'], false, 'btree'],
  ['booking_reschedules', 'ix_booking_reschedules_to_slot_id', ['to_slot_id'], false, 'btree'],
  ['booking_reschedules', 'ix_booking_reschedules_reason_concept_id', ['reason_concept_id'], false, 'btree'],
  ['booking_reschedules', 'ix_booking_reschedules_rescheduled_by_user_id', ['rescheduled_by_user_id'], false, 'btree'],
  ['booking_reschedules', 'ix_booking_reschedules_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['booking_reschedules', 'brin_booking_reschedules_recorded_at', ['recorded_at'], false, 'brin'],
  ['calendar_absences', 'ix_calendar_absences_subject', ['tenant_id', 'subject_type_concept_id', 'subject_ref_id'], false, 'btree'],
  ['calendar_absences', 'ix_calendar_absences_resource_id', ['resource_id'], false, 'btree'],
  ['calendar_absences', 'ix_calendar_absences_person_id', ['person_id'], false, 'btree'],
  ['calendar_absences', 'ix_calendar_absences_user_id', ['user_id'], false, 'btree'],
  ['calendar_absences', 'ix_calendar_absences_range', ['tenant_id', 'start_at', 'end_at'], false, 'btree'],
  ['calendar_absences', 'ix_calendar_absences_approval_status_concept_id', ['approval_status_concept_id'], false, 'btree'],
  ['calendar_absences', 'ix_calendar_absences_time_off_request_id', ['time_off_request_id'], false, 'btree'],
  ['practitioner_schedules', 'ix_practitioner_schedules_practitioner_profile_id', ['practitioner_profile_id'], false, 'btree'],
  ['practitioner_schedules', 'ix_practitioner_schedules_practice_id', ['practice_id'], false, 'btree'],
  ['practitioner_schedules', 'ix_practitioner_schedules_care_space_id', ['care_space_id'], false, 'btree'],
  ['practitioner_schedules', 'ix_practitioner_schedules_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['practitioner_schedules', 'ix_practitioner_schedules_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['practitioner_schedules', 'ix_practitioner_schedules_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['schedulable_resources', 'ix_schedulable_resources_tenant_id', ['tenant_id'], false, 'btree'],
  ['schedulable_resources', 'ix_schedulable_resources_practice_id', ['practice_id'], false, 'btree'],
  ['schedulable_resources', 'ix_schedulable_resources_resource_type_concept_id', ['resource_type_concept_id'], false, 'btree'],
  ['schedulable_resources', 'ix_schedulable_resources_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['schedulable_resources', 'ix_schedulable_resources_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['schedulable_resources', 'ix_schedulable_resources_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['schedulable_resources', 'ix_schedulable_resources_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['schedule_rules', 'ix_schedule_rules_schedule_template_id', ['schedule_template_id'], false, 'btree'],
  ['schedule_rules', 'ix_schedule_rules_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['schedule_rules', 'ix_schedule_rules_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['schedule_templates', 'ix_schedule_templates_resource_id', ['resource_id'], false, 'btree'],
  ['schedule_templates', 'ix_schedule_templates_practitioner_schedule_id', ['practitioner_schedule_id'], false, 'btree'],
  ['schedule_templates', 'ix_schedule_templates_service_concept_id', ['service_concept_id'], false, 'btree'],
  ['schedule_templates', 'ix_schedule_templates_booking_policy_id', ['booking_policy_id'], false, 'btree'],
  ['schedule_templates', 'ix_schedule_templates_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['schedule_templates', 'ix_schedule_templates_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['schedule_templates', 'ix_schedule_templates_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['slot_holds', 'uq_slot_holds_hold_token', ['hold_token'], true, 'btree'],
  ['slot_holds', 'ix_slot_holds_bookable_slot_id', ['bookable_slot_id'], false, 'btree'],
  ['slot_holds', 'ix_slot_holds_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['slot_holds', 'ix_slot_holds_held_by_user_id', ['held_by_user_id'], false, 'btree'],
  ['slot_holds', 'ix_slot_holds_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['slot_holds', 'ix_slot_holds_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['slot_holds', 'ix_slot_holds_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['slot_holds', 'ix_slot_holds_patient_profile_id_updated_at', ['patient_profile_id', 'updated_at desc'], false, 'btree'],
  ['waitlist_entries', 'ix_waitlist_entries_tenant_id', ['tenant_id'], false, 'btree'],
  ['waitlist_entries', 'ix_waitlist_entries_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['waitlist_entries', 'ix_waitlist_entries_resource_id', ['resource_id'], false, 'btree'],
  ['waitlist_entries', 'ix_waitlist_entries_service_concept_id', ['service_concept_id'], false, 'btree'],
  ['waitlist_entries', 'ix_waitlist_entries_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['waitlist_entries', 'ix_waitlist_entries_fulfilled_booking_id', ['fulfilled_booking_id'], false, 'btree'],
  ['waitlist_entries', 'ix_waitlist_entries_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['waitlist_entries', 'ix_waitlist_entries_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['waitlist_entries', 'ix_waitlist_entries_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['waitlist_entries', 'ix_waitlist_entries_patient_profile_id_updated_at', ['tenant_id', 'patient_profile_id', 'updated_at desc'], false, 'btree'],
];
