import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `system_ops`.
 * 177 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const systemOpsIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['accepted_risks', 'ix_accepted_risks_tenant_id', ['tenant_id'], false, 'btree'],
  ['accepted_risks', 'ix_accepted_risks_severity_concept_id', ['severity_concept_id'], false, 'btree'],
  ['accepted_risks', 'ix_accepted_risks_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['accepted_risks', 'ix_accepted_risks_accepted_by_user_id', ['accepted_by_user_id'], false, 'btree'],
  ['anonymization_rules', 'uq_anonymization_rules_code', ['code'], true, 'btree'],
  ['anonymization_rules', 'ix_anonymization_rules_technique_concept_id', ['technique_concept_id'], false, 'btree'],
  ['anonymization_rules', 'ix_anonymization_rules_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['anonymization_rules', 'ix_anonymization_rules_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['assessment_control_results', 'ix_assessment_control_results_workload_assessment_id', ['workload_assessment_id'], false, 'btree'],
  ['assessment_control_results', 'ix_assessment_control_results_operational_framework_control_id', ['operational_framework_control_id'], false, 'btree'],
  ['assessment_control_results', 'ix_assessment_control_results_result_concept_id', ['result_concept_id'], false, 'btree'],
  ['assessment_control_results', 'ix_assessment_control_results_maturity_level_concept_id', ['maturity_level_concept_id'], false, 'btree'],
  ['assessment_control_results', 'ix_assessment_control_results_assessor_user_id', ['assessor_user_id'], false, 'btree'],
  ['assessment_control_results', 'ix_assessment_control_results_accepted_risk_id', ['accepted_risk_id'], false, 'btree'],
  ['assessment_control_results', 'ix_assessment_control_results_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['assessment_control_results', 'ix_assessment_control_results_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['assessment_control_results', 'uk_assessment_control_results_assessment_control', ['workload_assessment_id', 'operational_framework_control_id'], true, 'btree'],
  ['assessment_findings', 'ix_assessment_findings_workload_assessment_id', ['workload_assessment_id'], false, 'btree'],
  ['assessment_findings', 'ix_assessment_findings_assessment_control_result_id', ['assessment_control_result_id'], false, 'btree'],
  ['assessment_findings', 'ix_assessment_findings_severity_concept_id', ['severity_concept_id'], false, 'btree'],
  ['assessment_findings', 'ix_assessment_findings_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['assessment_findings', 'ix_assessment_findings_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['assessment_findings', 'ix_assessment_findings_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['assessment_findings', 'uk_assessment_findings_assessment_code', ['workload_assessment_id', 'finding_code'], true, 'btree'],
  ['backup_policies', 'ix_backup_policies_tenant_id', ['tenant_id'], false, 'btree'],
  ['backup_policies', 'ix_backup_policies_resource_scope_concept_id', ['resource_scope_concept_id'], false, 'btree'],
  ['backup_policies', 'ix_backup_policies_backup_type_concept_id', ['backup_type_concept_id'], false, 'btree'],
  ['backup_policies', 'ix_backup_policies_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['backup_policies', 'ix_backup_policies_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['backup_policies', 'ix_backup_policies_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['backup_policies', 'ix_backup_policies_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['breach_notifications', 'ix_breach_notifications_security_incident_id', ['security_incident_id'], false, 'btree'],
  ['breach_notifications', 'ix_breach_notifications_authority_concept_id', ['authority_concept_id'], false, 'btree'],
  ['breach_notifications', 'ix_breach_notifications_deadline_at', ['deadline_at'], false, 'btree'],
  ['breach_notifications', 'ix_breach_notifications_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['cross_border_transfer_events', 'ix_cross_border_transfer_events_tenant_id', ['tenant_id'], false, 'btree'],
  ['cross_border_transfer_events', 'ix_cross_border_transfer_events_data_category_concept_id', ['data_category_concept_id'], false, 'btree'],
  ['cross_border_transfer_events', 'ix_cross_border_transfer_events_source_region_concept_id', ['source_region_concept_id'], false, 'btree'],
  ['cross_border_transfer_events', 'ix_cross_border_transfer_events_destination_region_concept_id', ['destination_region_concept_id'], false, 'btree'],
  ['cross_border_transfer_events', 'ix_cross_border_transfer_events_transfer_basis_concept_id', ['transfer_basis_concept_id'], false, 'btree'],
  ['cross_border_transfer_events', 'ix_cross_border_transfer_events_recipient_tenant_id', ['recipient_tenant_id'], false, 'btree'],
  ['cross_border_transfer_events', 'ix_cross_border_transfer_events_approved_by_user_id', ['approved_by_user_id'], false, 'btree'],
  ['cross_border_transfer_events', 'ix_cross_border_transfer_events_tenant_id_recorded_at', ['tenant_id', 'recorded_at desc'], false, 'btree'],
  ['data_classifications', 'uq_data_classifications_code', ['code'], true, 'btree'],
  ['data_classifications', 'ix_data_classifications_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['data_classifications', 'ix_data_classifications_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['data_classifications', 'ix_data_classifications_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['data_domains', 'uq_data_domains_code', ['code'], true, 'btree'],
  ['data_domains', 'ix_data_domains_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['data_domains', 'ix_data_domains_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['data_residency_policies', 'uq_data_residency_policies_code', ['code'], true, 'btree'],
  ['data_residency_policies', 'ix_data_residency_policies_jurisdiction_concept_id', ['jurisdiction_concept_id'], false, 'btree'],
  ['data_residency_policies', 'ix_data_residency_policies_data_classification_id', ['data_classification_id'], false, 'btree'],
  ['data_residency_policies', 'ix_data_residency_policies_allowed_storage_region_value_set_id', ['allowed_storage_region_value_set_id'], false, 'btree'],
  ['data_residency_policies', 'ix_data_residency_policies_allowed_processing_region_v_e59a2240', ['allowed_processing_region_value_set_id'], false, 'btree'],
  ['data_residency_policies', 'ix_data_residency_policies_cross_border_transfer_basis_1b4c4437', ['cross_border_transfer_basis_concept_id'], false, 'btree'],
  ['data_residency_policies', 'ix_data_residency_policies_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['data_residency_policies', 'ix_data_residency_policies_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['data_residency_policies', 'ix_data_residency_policies_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['draft_records', 'ix_draft_records_owner_user_id', ['owner_user_id'], false, 'btree'],
  ['draft_records', 'ix_draft_records_tenant_id', ['tenant_id'], false, 'btree'],
  ['draft_records', 'ix_draft_records_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['draft_records', 'ix_draft_records_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['draft_records', 'ix_draft_records_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['draft_records', 'ix_draft_records_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['encryption_keys', 'uk_encryption_keys_key_alias', ['key_alias'], true, 'btree'],
  ['encryption_keys', 'ix_encryption_keys_purpose_concept_id', ['key_purpose_concept_id'], false, 'btree'],
  ['encryption_keys', 'ix_encryption_keys_next_rotation_at', ['next_rotation_at'], false, 'btree'],
  ['encryption_keys', 'ix_encryption_keys_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['entity_registry', 'ix_entity_registry_domain_id', ['domain_id'], false, 'btree'],
  ['entity_registry', 'ix_entity_registry_classification_id', ['classification_id'], false, 'btree'],
  ['entity_registry', 'ix_entity_registry_retention_policy_id', ['retention_policy_id'], false, 'btree'],
  ['entity_registry', 'ix_entity_registry_write_policy_id', ['write_policy_id'], false, 'btree'],
  ['entity_registry', 'ix_entity_registry_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['entity_registry', 'ix_entity_registry_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['entity_registry', 'ix_entity_registry_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['field_registry', 'ix_field_registry_entity_registry_id', ['entity_registry_id'], false, 'btree'],
  ['field_registry', 'ix_field_registry_classification_id', ['classification_id'], false, 'btree'],
  ['field_registry', 'ix_field_registry_masking_strategy_concept_id', ['masking_strategy_concept_id'], false, 'btree'],
  ['field_registry', 'ix_field_registry_anonymization_rule_id', ['anonymization_rule_id'], false, 'btree'],
  ['field_registry', 'ix_field_registry_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['field_registry', 'ix_field_registry_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['governance_change_log', 'ix_governance_change_log_action_concept_id', ['action_concept_id'], false, 'btree'],
  ['governance_change_log', 'ix_governance_change_log_changed_by_user_id', ['changed_by_user_id'], false, 'btree'],
  ['governance_change_log', 'ix_governance_change_log_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['key_rotation_events', 'ix_key_rotation_events_encryption_key_id', ['encryption_key_id'], false, 'btree'],
  ['key_rotation_events', 'ix_key_rotation_events_occurred_at', ['occurred_at'], false, 'btree'],
  ['legal_holds', 'ix_legal_holds_tenant_id', ['tenant_id'], false, 'btree'],
  ['legal_holds', 'ix_legal_holds_target_type_concept_id', ['target_type_concept_id'], false, 'btree'],
  ['legal_holds', 'ix_legal_holds_reason_concept_id', ['reason_concept_id'], false, 'btree'],
  ['legal_holds', 'ix_legal_holds_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['legal_holds', 'ix_legal_holds_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['legal_holds', 'ix_legal_holds_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['legal_holds', 'ix_legal_holds_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['operational_framework_controls', 'ix_operational_framework_controls_operational_framework_id', ['operational_framework_id'], false, 'btree'],
  ['operational_framework_controls', 'ix_operational_framework_controls_parent_control_id', ['parent_control_id'], false, 'btree'],
  ['operational_framework_controls', 'ix_operational_framework_controls_pillar_concept_id', ['pillar_concept_id'], false, 'btree'],
  ['operational_framework_controls', 'ix_operational_framework_controls_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['operational_framework_controls', 'ix_operational_framework_controls_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['operational_framework_controls', 'ix_operational_framework_controls_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['operational_framework_controls', 'uk_operational_framework_controls_framework_code', ['operational_framework_id', 'control_code'], true, 'btree'],
  ['operational_frameworks', 'ix_operational_frameworks_provider_concept_id', ['provider_concept_id'], false, 'btree'],
  ['operational_frameworks', 'ix_operational_frameworks_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['operational_frameworks', 'ix_operational_frameworks_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['operational_frameworks', 'ix_operational_frameworks_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['operational_frameworks', 'uk_operational_frameworks_code_version', ['code', 'version'], true, 'btree'],
  ['partition_specs', 'uk_partition_specs_code', ['code'], true, 'btree'],
  ['partition_specs', 'uk_partition_specs_table', ['schema_name', 'table_name'], true, 'btree'],
  ['partition_specs', 'ix_partition_specs_entity_registry_id', ['entity_registry_id'], false, 'btree'],
  ['partition_specs', 'ix_partition_specs_strategy_concept_id', ['partition_strategy_concept_id'], false, 'btree'],
  ['partition_specs', 'ix_partition_specs_retention_policy_id', ['retention_policy_id'], false, 'btree'],
  ['record_revisions', 'ix_record_revisions_operation_concept_id', ['operation_concept_id'], false, 'btree'],
  ['record_revisions', 'ix_record_revisions_changed_by_user_id', ['changed_by_user_id'], false, 'btree'],
  ['record_revisions', 'ix_record_revisions_change_reason_concept_id', ['change_reason_concept_id'], false, 'btree'],
  ['record_revisions', 'ix_record_revisions_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['remediation_actions', 'ix_remediation_actions_remediation_plan_id', ['remediation_plan_id'], false, 'btree'],
  ['remediation_actions', 'ix_remediation_actions_assessment_finding_id', ['assessment_finding_id'], false, 'btree'],
  ['remediation_actions', 'ix_remediation_actions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['remediation_actions', 'ix_remediation_actions_assigned_user_id', ['assigned_user_id'], false, 'btree'],
  ['remediation_actions', 'ix_remediation_actions_verification_user_id', ['verification_user_id'], false, 'btree'],
  ['remediation_actions', 'ix_remediation_actions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['remediation_actions', 'ix_remediation_actions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['remediation_actions', 'uk_remediation_actions_plan_code', ['remediation_plan_id', 'action_code'], true, 'btree'],
  ['remediation_plans', 'ix_remediation_plans_tenant_id', ['tenant_id'], false, 'btree'],
  ['remediation_plans', 'ix_remediation_plans_workload_assessment_id', ['workload_assessment_id'], false, 'btree'],
  ['remediation_plans', 'ix_remediation_plans_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['remediation_plans', 'ix_remediation_plans_owner_user_id', ['owner_user_id'], false, 'btree'],
  ['remediation_plans', 'ix_remediation_plans_approved_by_user_id', ['approved_by_user_id'], false, 'btree'],
  ['remediation_plans', 'ix_remediation_plans_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['remediation_plans', 'ix_remediation_plans_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['remediation_plans', 'ix_remediation_plans_tenant_status', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['remediation_plans', 'uk_remediation_plans_tenant_code', ['tenant_id', 'code'], true, 'btree'],
  ['restore_test_runs', 'ix_restore_test_runs_backup_policy_id', ['backup_policy_id'], false, 'btree'],
  ['restore_test_runs', 'ix_restore_test_runs_outcome_concept_id', ['outcome_concept_id'], false, 'btree'],
  ['restore_test_runs', 'ix_restore_test_runs_evidence_file_id', ['evidence_file_id'], false, 'btree'],
  ['restore_test_runs', 'ix_restore_test_runs_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['retention_executions', 'ix_retention_executions_retention_policy_id', ['retention_policy_id'], false, 'btree'],
  ['retention_executions', 'ix_retention_executions_entity_registry_id', ['entity_registry_id'], false, 'btree'],
  ['retention_executions', 'ix_retention_executions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['retention_executions', 'ix_retention_executions_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['retention_policies', 'uq_retention_policies_code', ['code'], true, 'btree'],
  ['retention_policies', 'ix_retention_policies_legal_basis_concept_id', ['legal_basis_concept_id'], false, 'btree'],
  ['retention_policies', 'ix_retention_policies_disposition_concept_id', ['disposition_concept_id'], false, 'btree'],
  ['retention_policies', 'ix_retention_policies_jurisdiction_concept_id', ['jurisdiction_concept_id'], false, 'btree'],
  ['retention_policies', 'ix_retention_policies_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['retention_policies', 'ix_retention_policies_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['retention_policies', 'ix_retention_policies_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['security_incidents', 'uk_security_incidents_code', ['code'], true, 'btree'],
  ['security_incidents', 'ix_security_incidents_severity_concept_id', ['severity_concept_id'], false, 'btree'],
  ['security_incidents', 'ix_security_incidents_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['security_incidents', 'ix_security_incidents_detected_at', ['detected_at'], false, 'btree'],
  ['tenant_residency_bindings', 'ix_tenant_residency_bindings_tenant_id', ['tenant_id'], false, 'btree'],
  ['tenant_residency_bindings', 'ix_tenant_residency_bindings_residency_policy_id', ['residency_policy_id'], false, 'btree'],
  ['tenant_residency_bindings', 'ix_tenant_residency_bindings_primary_region_concept_id', ['primary_region_concept_id'], false, 'btree'],
  ['tenant_residency_bindings', 'ix_tenant_residency_bindings_disaster_recovery_region__5ff5dc29', ['disaster_recovery_region_concept_id'], false, 'btree'],
  ['tenant_residency_bindings', 'ix_tenant_residency_bindings_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['tenant_residency_bindings', 'ix_tenant_residency_bindings_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['tenant_residency_bindings', 'ix_tenant_residency_bindings_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['tenant_residency_bindings', 'ix_tenant_residency_bindings_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['workload_assessments', 'ix_workload_assessments_tenant_id', ['tenant_id'], false, 'btree'],
  ['workload_assessments', 'ix_workload_assessments_operational_framework_id', ['operational_framework_id'], false, 'btree'],
  ['workload_assessments', 'ix_workload_assessments_service_component_id', ['service_component_id'], false, 'btree'],
  ['workload_assessments', 'ix_workload_assessments_assessment_type_concept_id', ['assessment_type_concept_id'], false, 'btree'],
  ['workload_assessments', 'ix_workload_assessments_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['workload_assessments', 'ix_workload_assessments_facilitator_user_id', ['facilitator_user_id'], false, 'btree'],
  ['workload_assessments', 'ix_workload_assessments_approved_by_user_id', ['approved_by_user_id'], false, 'btree'],
  ['workload_assessments', 'ix_workload_assessments_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['workload_assessments', 'ix_workload_assessments_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['workload_assessments', 'ix_workload_assessments_tenant_status', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['workload_assessments', 'ix_workload_assessments_tenant_workload', ['tenant_id', 'workload_code', 'created_at desc'], false, 'btree'],
  ['write_policies', 'uq_write_policies_code', ['code'], true, 'btree'],
  ['write_policies', 'ix_write_policies_insert_mode_concept_id', ['insert_mode_concept_id'], false, 'btree'],
  ['write_policies', 'ix_write_policies_update_mode_concept_id', ['update_mode_concept_id'], false, 'btree'],
  ['write_policies', 'ix_write_policies_delete_mode_concept_id', ['delete_mode_concept_id'], false, 'btree'],
  ['write_policies', 'ix_write_policies_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['write_policies', 'ix_write_policies_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['write_policies', 'ix_write_policies_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
];
