import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `system_context`.
 * 59 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const systemContextIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['dynamic_enum_bindings', 'ix_dynamic_enum_bindings_dynamic_enum_definition_id', ['dynamic_enum_definition_id'], false, 'btree'],
  ['dynamic_enum_bindings', 'ix_dynamic_enum_bindings_system_context_id', ['system_context_id'], false, 'btree'],
  ['dynamic_enum_bindings', 'ix_dynamic_enum_bindings_fallback_concept_id', ['fallback_concept_id'], false, 'btree'],
  ['dynamic_enum_bindings', 'ix_dynamic_enum_bindings_validation_mode_concept_id', ['validation_mode_concept_id'], false, 'btree'],
  ['dynamic_enum_bindings', 'ix_dynamic_enum_bindings_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['dynamic_enum_bindings', 'ix_dynamic_enum_bindings_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['dynamic_enum_bindings', 'ix_dynamic_enum_bindings_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['dynamic_enum_definitions', 'uq_dynamic_enum_definitions_code', ['code'], true, 'btree'],
  ['dynamic_enum_definitions', 'ix_dynamic_enum_definitions_value_set_id', ['value_set_id'], false, 'btree'],
  ['dynamic_enum_definitions', 'ix_dynamic_enum_definitions_scope_type_concept_id', ['scope_type_concept_id'], false, 'btree'],
  ['dynamic_enum_definitions', 'ix_dynamic_enum_definitions_tenant_id', ['tenant_id'], false, 'btree'],
  ['dynamic_enum_definitions', 'ix_dynamic_enum_definitions_country_concept_id', ['country_concept_id'], false, 'btree'],
  ['dynamic_enum_definitions', 'ix_dynamic_enum_definitions_selection_mode_concept_id', ['selection_mode_concept_id'], false, 'btree'],
  ['dynamic_enum_definitions', 'ix_dynamic_enum_definitions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['dynamic_enum_definitions', 'ix_dynamic_enum_definitions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['dynamic_enum_definitions', 'ix_dynamic_enum_definitions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['dynamic_enum_definitions', 'ix_dynamic_enum_definitions_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['dynamic_enum_options', 'ix_dynamic_enum_options_dynamic_enum_version_id', ['dynamic_enum_version_id'], false, 'btree'],
  ['dynamic_enum_options', 'ix_dynamic_enum_options_concept_id', ['concept_id'], false, 'btree'],
  ['dynamic_enum_options', 'ix_dynamic_enum_options_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['dynamic_enum_versions', 'ix_dynamic_enum_versions_dynamic_enum_definition_id', ['dynamic_enum_definition_id'], false, 'btree'],
  ['dynamic_enum_versions', 'ix_dynamic_enum_versions_value_set_version_id', ['value_set_version_id'], false, 'btree'],
  ['dynamic_enum_versions', 'ix_dynamic_enum_versions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['dynamic_enum_versions', 'ix_dynamic_enum_versions_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['dynamic_enum_versions', 'uq_dynamic_enum_versions_dynamic_enum_definition_id_ve_fe5c676f', ['dynamic_enum_definition_id', 'version_number'], true, 'btree'],
  ['system_context_bindings', 'ix_system_context_bindings_system_context_id', ['system_context_id'], false, 'btree'],
  ['system_context_bindings', 'ix_system_context_bindings_consumer_type_concept_id', ['consumer_type_concept_id'], false, 'btree'],
  ['system_context_bindings', 'ix_system_context_bindings_tenant_id', ['tenant_id'], false, 'btree'],
  ['system_context_bindings', 'ix_system_context_bindings_country_concept_id', ['country_concept_id'], false, 'btree'],
  ['system_context_bindings', 'ix_system_context_bindings_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['system_context_bindings', 'ix_system_context_bindings_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['system_context_bindings', 'ix_system_context_bindings_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['system_context_bindings', 'ix_system_context_bindings_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['system_context_inputs', 'ix_system_context_inputs_system_context_version_id', ['system_context_version_id'], false, 'btree'],
  ['system_context_inputs', 'ix_system_context_inputs_source_type_concept_id', ['source_type_concept_id'], false, 'btree'],
  ['system_context_inputs', 'ix_system_context_inputs_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['system_context_refresh_runs', 'uq_system_context_refresh_runs_idempotency_key', ['idempotency_key'], true, 'btree'],
  ['system_context_refresh_runs', 'ix_system_context_refresh_runs_system_context_id', ['system_context_id'], false, 'btree'],
  ['system_context_refresh_runs', 'ix_system_context_refresh_runs_trigger_concept_id', ['trigger_concept_id'], false, 'btree'],
  ['system_context_refresh_runs', 'ix_system_context_refresh_runs_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['system_context_refresh_runs', 'ix_system_context_refresh_runs_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['system_context_versions', 'ix_system_context_versions_system_context_id', ['system_context_id'], false, 'btree'],
  ['system_context_versions', 'ix_system_context_versions_refresh_run_id', ['refresh_run_id'], false, 'btree'],
  ['system_context_versions', 'ix_system_context_versions_generated_by_agent_id', ['generated_by_agent_id'], false, 'btree'],
  ['system_context_versions', 'ix_system_context_versions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['system_context_versions', 'ix_system_context_versions_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['system_context_versions', 'uq_system_context_versions_system_context_id_version_number', ['system_context_id', 'version_number'], true, 'btree'],
  ['system_contexts', 'uq_system_contexts_code', ['code'], true, 'btree'],
  ['system_contexts', 'ix_system_contexts_context_type_concept_id', ['context_type_concept_id'], false, 'btree'],
  ['system_contexts', 'ix_system_contexts_scope_type_concept_id', ['scope_type_concept_id'], false, 'btree'],
  ['system_contexts', 'ix_system_contexts_tenant_id', ['tenant_id'], false, 'btree'],
  ['system_contexts', 'ix_system_contexts_country_concept_id', ['country_concept_id'], false, 'btree'],
  ['system_contexts', 'ix_system_contexts_locale_concept_id', ['locale_concept_id'], false, 'btree'],
  ['system_contexts', 'ix_system_contexts_current_version_id', ['current_version_id'], false, 'btree'],
  ['system_contexts', 'ix_system_contexts_refresh_policy_concept_id', ['refresh_policy_concept_id'], false, 'btree'],
  ['system_contexts', 'ix_system_contexts_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['system_contexts', 'ix_system_contexts_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['system_contexts', 'ix_system_contexts_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['system_contexts', 'ix_system_contexts_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
];
