import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `telemetry`.
 * 83 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const telemetryIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['activity_event_schema_definitions', 'ix_activity_event_schema_definitions_purpose_definition_id', ['purpose_definition_id'], false, 'btree'],
  ['activity_event_schema_definitions', 'ix_activity_event_schema_definitions_portal_type_concept_id', ['portal_type_concept_id'], false, 'btree'],
  ['activity_event_schema_definitions', 'ix_activity_event_schema_definitions_pii_classificatio_2357b2ab', ['pii_classification_concept_id'], false, 'btree'],
  ['activity_event_schema_definitions', 'ix_activity_event_schema_definitions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['activity_event_schema_definitions', 'ix_activity_event_schema_definitions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['analytics_subjects', 'uq_analytics_subjects_pseudonymous_subject_key', ['pseudonymous_subject_key'], true, 'btree'],
  ['analytics_subjects', 'ix_analytics_subjects_user_id', ['user_id'], false, 'btree'],
  ['analytics_subjects', 'ix_analytics_subjects_patient_profile_id', ['patient_profile_id'], false, 'btree'],
  ['analytics_subjects', 'ix_analytics_subjects_rotated_from_subject_id', ['rotated_from_subject_id'], false, 'btree'],
  ['analytics_subjects', 'ix_analytics_subjects_created_from_consent_id', ['created_from_consent_id'], false, 'btree'],
  ['analytics_subjects', 'ix_analytics_subjects_patient_profile_id_created_at', ['patient_profile_id', 'created_at desc'], false, 'btree'],
  ['client_contexts', 'ix_client_contexts_session_journey_id', ['session_journey_id'], false, 'btree'],
  ['client_contexts', 'ix_client_contexts_analytics_subject_id', ['analytics_subject_id'], false, 'btree'],
  ['client_contexts', 'ix_client_contexts_session_id', ['session_id'], false, 'btree'],
  ['client_contexts', 'ix_client_contexts_portal_type_concept_id', ['portal_type_concept_id'], false, 'btree'],
  ['client_contexts', 'ix_client_contexts_device_type_concept_id', ['device_type_concept_id'], false, 'btree'],
  ['client_contexts', 'ix_client_contexts_os_family_concept_id', ['os_family_concept_id'], false, 'btree'],
  ['client_contexts', 'ix_client_contexts_browser_family_concept_id', ['browser_family_concept_id'], false, 'btree'],
  ['client_contexts', 'ix_client_contexts_country_concept_id', ['country_concept_id'], false, 'btree'],
  ['client_contexts', 'ix_client_contexts_data_classification_concept_id', ['data_classification_concept_id'], false, 'btree'],
  ['conversion_events', 'ix_conversion_events_funnel_definition_id', ['funnel_definition_id'], false, 'btree'],
  ['conversion_events', 'ix_conversion_events_analytics_subject_id', ['analytics_subject_id'], false, 'btree'],
  ['conversion_events', 'ix_conversion_events_session_journey_id', ['session_journey_id'], false, 'btree'],
  ['conversion_events', 'ix_conversion_events_completion_event_id', ['completion_event_id'], false, 'btree'],
  ['funnel_definitions', 'uq_funnel_definitions_funnel_code', ['funnel_code'], true, 'btree'],
  ['funnel_definitions', 'ix_funnel_definitions_portal_type_concept_id', ['portal_type_concept_id'], false, 'btree'],
  ['funnel_definitions', 'ix_funnel_definitions_purpose_definition_id', ['purpose_definition_id'], false, 'btree'],
  ['funnel_definitions', 'ix_funnel_definitions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['funnel_definitions', 'ix_funnel_definitions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['funnel_definitions', 'ix_funnel_definitions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['funnel_definitions', 'uq_funnel_definitions_purpose_definition_id_version_number', ['purpose_definition_id', 'version_number'], true, 'btree'],
  ['funnel_steps', 'ix_funnel_steps_funnel_definition_id', ['funnel_definition_id'], false, 'btree'],
  ['funnel_steps', 'ix_funnel_steps_event_schema_definition_id', ['event_schema_definition_id'], false, 'btree'],
  ['session_journeys', 'ix_session_journeys_session_id', ['session_id'], false, 'btree'],
  ['session_journeys', 'ix_session_journeys_analytics_subject_id', ['analytics_subject_id'], false, 'btree'],
  ['session_journeys', 'ix_session_journeys_portal_type_concept_id', ['portal_type_concept_id'], false, 'btree'],
  ['session_journeys', 'ix_session_journeys_entry_event_id', ['entry_event_id'], false, 'btree'],
  ['session_journeys', 'ix_session_journeys_exit_event_id', ['exit_event_id'], false, 'btree'],
  ['session_journeys', 'ix_session_journeys_journey_status_concept_id', ['journey_status_concept_id'], false, 'btree'],
  ['tracking_consents', 'ix_tracking_consents_user_id', ['user_id'], false, 'btree'],
  ['tracking_consents', 'ix_tracking_consents_purpose_definition_id', ['purpose_definition_id'], false, 'btree'],
  ['tracking_consents', 'ix_tracking_consents_decision_concept_id', ['decision_concept_id'], false, 'btree'],
  ['tracking_consents', 'ix_tracking_consents_jurisdiction_concept_id', ['jurisdiction_concept_id'], false, 'btree'],
  ['tracking_consents', 'ix_tracking_consents_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['tracking_disclosure_acceptances', 'ix_tracking_disclosure_acceptances_tracking_disclosure_ca448e76', ['tracking_disclosure_version_id'], false, 'btree'],
  ['tracking_disclosure_acceptances', 'ix_tracking_disclosure_acceptances_user_id', ['user_id'], false, 'btree'],
  ['tracking_disclosure_acceptances', 'ix_tracking_disclosure_acceptances_session_id', ['session_id'], false, 'btree'],
  ['tracking_disclosure_acceptances', 'ix_tracking_disclosure_acceptances_acceptance_status_concept_id', ['acceptance_status_concept_id'], false, 'btree'],
  ['tracking_disclosure_versions', 'ix_tracking_disclosure_versions_jurisdiction_concept_id', ['jurisdiction_concept_id'], false, 'btree'],
  ['tracking_disclosure_versions', 'ix_tracking_disclosure_versions_file_id', ['file_id'], false, 'btree'],
  ['tracking_disclosure_versions', 'ix_tracking_disclosure_versions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['tracking_disclosure_versions', 'ix_tracking_disclosure_versions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['tracking_disclosure_versions', 'uq_tracking_disclosure_versions_file_id_version_number', ['file_id', 'version_number'], true, 'btree'],
  ['tracking_purpose_definitions', 'uq_tracking_purpose_definitions_purpose_code', ['purpose_code'], true, 'btree'],
  ['tracking_purpose_definitions', 'ix_tracking_purpose_definitions_purpose_category_concept_id', ['purpose_category_concept_id'], false, 'btree'],
  ['tracking_purpose_definitions', 'ix_tracking_purpose_definitions_legal_basis_concept_id', ['legal_basis_concept_id'], false, 'btree'],
  ['tracking_purpose_definitions', 'ix_tracking_purpose_definitions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['tracking_purpose_definitions', 'ix_tracking_purpose_definitions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['user_activity_events', 'ix_user_activity_events_event_schema_definition_id', ['event_schema_definition_id'], false, 'btree'],
  ['user_activity_events', 'ix_user_activity_events_analytics_subject_id', ['analytics_subject_id'], false, 'btree'],
  ['user_activity_events', 'ix_user_activity_events_user_id', ['user_id'], false, 'btree'],
  ['user_activity_events', 'ix_user_activity_events_session_id', ['session_id'], false, 'btree'],
  ['user_activity_events', 'ix_user_activity_events_device_id', ['device_id'], false, 'btree'],
  ['user_activity_events', 'ix_user_activity_events_tenant_id', ['tenant_id'], false, 'btree'],
  ['user_activity_events', 'ix_user_activity_events_portal_type_concept_id', ['portal_type_concept_id'], false, 'btree'],
  ['user_activity_events', 'ix_user_activity_events_target_type_concept_id', ['target_type_concept_id'], false, 'btree'],
  ['user_activity_events', 'ix_user_activity_events_consent_snapshot_id', ['consent_snapshot_id'], false, 'btree'],
  ['user_activity_events', 'ix_user_activity_events_security_audit_event_id', ['security_audit_event_id'], false, 'btree'],
  ['user_activity_events', 'ix_user_activity_events_tenant_id_created_at', ['tenant_id', 'created_at desc'], false, 'btree'],
  ['user_activity_events', 'brin_user_activity_events_created_at', ['created_at'], false, 'brin'],
  ['user_activity_event_properties', 'ix_user_activity_event_properties_user_activity_event_id', ['user_activity_event_id'], false, 'btree'],
  ['user_activity_event_properties', 'ix_user_activity_event_properties_value_type_concept_id', ['value_type_concept_id'], false, 'btree'],
  ['user_activity_event_properties', 'ix_user_activity_event_properties_value_concept_id', ['value_concept_id'], false, 'btree'],
  ['user_activity_event_properties', 'ix_user_activity_event_properties_data_classification__18c7c7cf', ['data_classification_concept_id'], false, 'btree'],
  ['web_vitals', 'ix_web_vitals_user_activity_event_id', ['user_activity_event_id'], false, 'btree'],
  ['web_vitals', 'ix_web_vitals_session_journey_id', ['session_journey_id'], false, 'btree'],
  ['web_vitals', 'ix_web_vitals_analytics_subject_id', ['analytics_subject_id'], false, 'btree'],
  ['web_vitals', 'ix_web_vitals_client_context_id', ['client_context_id'], false, 'btree'],
  ['web_vitals', 'ix_web_vitals_portal_type_concept_id', ['portal_type_concept_id'], false, 'btree'],
  ['web_vitals', 'ix_web_vitals_metric_concept_id', ['metric_concept_id'], false, 'btree'],
  ['web_vitals', 'ix_web_vitals_rating_concept_id', ['rating_concept_id'], false, 'btree'],
  ['web_vitals', 'ix_web_vitals_navigation_type_concept_id', ['navigation_type_concept_id'], false, 'btree'],
  ['web_vitals', 'brin_web_vitals_created_at', ['created_at'], false, 'brin'],
];
