import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `terminology`.
 * 83 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const terminologyIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['catalog_concepts', 'ix_catalog_concepts_code_system_version_id', ['code_system_version_id'], false, 'btree'],
  ['catalog_concepts', 'ix_catalog_concepts_replaced_by_concept_id', ['replaced_by_concept_id'], false, 'btree'],
  ['catalog_concepts', 'ix_catalog_concepts_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['catalog_concepts', 'ix_catalog_concepts_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['catalog_concepts', 'ix_catalog_concepts_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['catalog_concepts', 'uq_catalog_concepts_version_code', ['code_system_version_id', 'code'], true, 'btree'],
  ['catalog_concepts', 'ix_catalog_concepts_display', ['display'], false, 'btree'],
  ['catalog_import_batches', 'ix_catalog_import_batches_source_id', ['source_id'], false, 'btree'],
  ['catalog_import_batches', 'ix_catalog_import_batches_code_system_version_id', ['code_system_version_id'], false, 'btree'],
  ['catalog_import_batches', 'ix_catalog_import_batches_file_id', ['file_id'], false, 'btree'],
  ['catalog_import_batches', 'ix_catalog_import_batches_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['catalog_import_batches', 'ix_catalog_import_batches_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['code_system_versions', 'ix_code_system_versions_code_system_id', ['code_system_id'], false, 'btree'],
  ['code_system_versions', 'ix_code_system_versions_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['code_system_versions', 'ix_code_system_versions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['code_system_versions', 'ix_code_system_versions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['code_system_versions', 'uq_code_system_versions_code_system_id_version', ['code_system_id', 'version'], true, 'btree'],
  ['code_system_versions', 'uq_code_system_versions_system_version', ['code_system_id', 'version'], true, 'btree'],
  ['code_systems', 'uq_code_systems_internal_code', ['internal_code'], true, 'btree'],
  ['code_systems', 'uq_code_systems_canonical_url', ['canonical_url'], true, 'btree'],
  ['code_systems', 'ix_code_systems_source_id', ['source_id'], false, 'btree'],
  ['code_systems', 'ix_code_systems_content_type_concept_id', ['content_type_concept_id'], false, 'btree'],
  ['code_systems', 'ix_code_systems_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['code_systems', 'ix_code_systems_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['code_systems', 'ix_code_systems_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['concept_designations', 'ix_concept_designations_concept_id', ['concept_id'], false, 'btree'],
  ['concept_designations', 'ix_concept_designations_language_concept_id', ['language_concept_id'], false, 'btree'],
  ['concept_designations', 'ix_concept_designations_designation_type_concept_id', ['designation_type_concept_id'], false, 'btree'],
  ['concept_designations', 'ix_concept_designations_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['concept_designations', 'ix_concept_designations_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['concept_maps', 'ix_concept_maps_source_concept_id', ['source_concept_id'], false, 'btree'],
  ['concept_maps', 'ix_concept_maps_target_concept_id', ['target_concept_id'], false, 'btree'],
  ['concept_maps', 'ix_concept_maps_equivalence_concept_id', ['equivalence_concept_id'], false, 'btree'],
  ['concept_maps', 'ix_concept_maps_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['concept_maps', 'ix_concept_maps_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['concept_maps', 'ix_concept_maps_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['concept_properties', 'ix_concept_properties_concept_id', ['concept_id'], false, 'btree'],
  ['concept_properties', 'ix_concept_properties_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['concept_properties', 'ix_concept_properties_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['concept_relationships', 'ix_concept_relationships_source_concept_id', ['source_concept_id'], false, 'btree'],
  ['concept_relationships', 'ix_concept_relationships_target_concept_id', ['target_concept_id'], false, 'btree'],
  ['concept_relationships', 'ix_concept_relationships_relationship_type_concept_id', ['relationship_type_concept_id'], false, 'btree'],
  ['concept_relationships', 'ix_concept_relationships_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['concept_relationships', 'ix_concept_relationships_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['tenant_catalog_policies', 'ix_tenant_catalog_policies_tenant_id', ['tenant_id'], false, 'btree'],
  ['tenant_catalog_policies', 'ix_tenant_catalog_policies_value_set_id', ['value_set_id'], false, 'btree'],
  ['tenant_catalog_policies', 'ix_tenant_catalog_policies_mode_concept_id', ['mode_concept_id'], false, 'btree'],
  ['tenant_catalog_policies', 'ix_tenant_catalog_policies_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['tenant_catalog_policies', 'ix_tenant_catalog_policies_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['tenant_catalog_policies', 'ix_tenant_catalog_policies_tenant_id_updated_at', ['tenant_id', 'updated_at desc'], false, 'btree'],
  ['tenant_concept_config', 'ix_tenant_concept_config_tenant_id', ['tenant_id'], false, 'btree'],
  ['tenant_concept_config', 'ix_tenant_concept_config_concept_id', ['concept_id'], false, 'btree'],
  ['tenant_concept_config', 'ix_tenant_concept_config_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['tenant_concept_config', 'ix_tenant_concept_config_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['tenant_concept_config', 'ix_tenant_concept_config_tenant_id_updated_at', ['tenant_id', 'updated_at desc'], false, 'btree'],
  ['terminology_sources', 'uq_terminology_sources_code', ['code'], true, 'btree'],
  ['terminology_sources', 'ix_terminology_sources_source_type_concept_id', ['source_type_concept_id'], false, 'btree'],
  ['terminology_sources', 'ix_terminology_sources_jurisdiction_concept_id', ['jurisdiction_concept_id'], false, 'btree'],
  ['terminology_sources', 'ix_terminology_sources_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['terminology_sources', 'ix_terminology_sources_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['terminology_sources', 'ix_terminology_sources_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['value_set_members', 'ix_value_set_members_value_set_version_id', ['value_set_version_id'], false, 'btree'],
  ['value_set_members', 'ix_value_set_members_concept_id', ['concept_id'], false, 'btree'],
  ['value_set_members', 'ix_value_set_members_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['value_set_members', 'ix_value_set_members_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['value_set_members', 'uq_value_set_members_version_concept', ['value_set_version_id', 'concept_id'], true, 'btree'],
  ['value_set_rules', 'ix_value_set_rules_value_set_version_id', ['value_set_version_id'], false, 'btree'],
  ['value_set_rules', 'ix_value_set_rules_code_system_id', ['code_system_id'], false, 'btree'],
  ['value_set_rules', 'ix_value_set_rules_operator_concept_id', ['operator_concept_id'], false, 'btree'],
  ['value_set_rules', 'ix_value_set_rules_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['value_set_rules', 'ix_value_set_rules_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['value_set_versions', 'ix_value_set_versions_value_set_id', ['value_set_id'], false, 'btree'],
  ['value_set_versions', 'ix_value_set_versions_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['value_set_versions', 'ix_value_set_versions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['value_set_versions', 'ix_value_set_versions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['value_set_versions', 'uq_value_set_versions_value_set_id_version', ['value_set_id', 'version'], true, 'btree'],
  ['value_set_versions', 'uq_value_set_versions_set_version', ['value_set_id', 'version'], true, 'btree'],
  ['value_sets', 'uq_value_sets_internal_code', ['internal_code'], true, 'btree'],
  ['value_sets', 'uq_value_sets_canonical_url', ['canonical_url'], true, 'btree'],
  ['value_sets', 'ix_value_sets_jurisdiction_concept_id', ['jurisdiction_concept_id'], false, 'btree'],
  ['value_sets', 'ix_value_sets_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['value_sets', 'ix_value_sets_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['value_sets', 'ix_value_sets_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
];
