import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `tracking`.
 * 58 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const trackingIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['delivery_proofs', 'ix_delivery_proofs_shipment_id', ['shipment_id'], false, 'btree'],
  ['delivery_proofs', 'ix_delivery_proofs_proof_type_concept_id', ['proof_type_concept_id'], false, 'btree'],
  ['delivery_proofs', 'ix_delivery_proofs_signature_file_id', ['signature_file_id'], false, 'btree'],
  ['delivery_proofs', 'ix_delivery_proofs_photo_file_id', ['photo_file_id'], false, 'btree'],
  ['delivery_proofs', 'ix_delivery_proofs_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['delivery_proofs', 'ix_delivery_proofs_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['delivery_proofs', 'ix_delivery_proofs_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['eta_estimates', 'ix_eta_estimates_trackable_subject_id', ['trackable_subject_id'], false, 'btree'],
  ['eta_estimates', 'ix_eta_estimates_shipment_id', ['shipment_id'], false, 'btree'],
  ['eta_estimates', 'ix_eta_estimates_method_concept_id', ['method_concept_id'], false, 'btree'],
  ['eta_estimates', 'ix_eta_estimates_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['milestone_definitions', 'ix_milestone_definitions_tenant_id', ['tenant_id'], false, 'btree'],
  ['milestone_definitions', 'ix_milestone_definitions_subject_type_concept_id', ['subject_type_concept_id'], false, 'btree'],
  ['milestone_definitions', 'ix_milestone_definitions_milestone_status_concept_id', ['milestone_status_concept_id'], false, 'btree'],
  ['milestone_definitions', 'ix_milestone_definitions_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['milestone_definitions', 'ix_milestone_definitions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['milestone_definitions', 'ix_milestone_definitions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['milestone_definitions', 'ix_milestone_definitions_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['shipment_handoffs', 'ix_shipment_handoffs_shipment_id', ['shipment_id'], false, 'btree'],
  ['shipment_handoffs', 'ix_shipment_handoffs_handoff_type_concept_id', ['handoff_type_concept_id'], false, 'btree'],
  ['shipment_handoffs', 'ix_shipment_handoffs_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
  ['shipments', 'uq_shipments_shipment_number', ['shipment_number'], true, 'btree'],
  ['shipments', 'ix_shipments_trackable_subject_id', ['trackable_subject_id'], false, 'btree'],
  ['shipments', 'ix_shipments_carrier_id', ['carrier_id'], false, 'btree'],
  ['shipments', 'ix_shipments_tenant_id', ['tenant_id'], false, 'btree'],
  ['shipments', 'ix_shipments_origin_address_id', ['origin_address_id'], false, 'btree'],
  ['shipments', 'ix_shipments_destination_address_id', ['destination_address_id'], false, 'btree'],
  ['shipments', 'ix_shipments_assigned_courier_user_id', ['assigned_courier_user_id'], false, 'btree'],
  ['shipments', 'ix_shipments_tracked_subject_id', ['tracked_subject_id'], false, 'btree'],
  ['shipments', 'ix_shipments_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['shipments', 'ix_shipments_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['shipments', 'ix_shipments_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['shipments', 'ix_shipments_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['trackable_subjects', 'uq_trackable_subjects_tracking_number', ['tracking_number'], true, 'btree'],
  ['trackable_subjects', 'ix_trackable_subjects_tenant_id', ['tenant_id'], false, 'btree'],
  ['trackable_subjects', 'ix_trackable_subjects_subject_type_concept_id', ['subject_type_concept_id'], false, 'btree'],
  ['trackable_subjects', 'ix_trackable_subjects_current_status_concept_id', ['current_status_concept_id'], false, 'btree'],
  ['trackable_subjects', 'ix_trackable_subjects_current_milestone_id', ['current_milestone_id'], false, 'btree'],
  ['trackable_subjects', 'ix_trackable_subjects_priority_concept_id', ['priority_concept_id'], false, 'btree'],
  ['trackable_subjects', 'ix_trackable_subjects_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['trackable_subjects', 'ix_trackable_subjects_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['trackable_subjects', 'ix_trackable_subjects_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['trackable_subjects', 'ix_trackable_subjects_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['tracking_carriers', 'uq_tracking_carriers_code', ['code'], true, 'btree'],
  ['tracking_carriers', 'ix_tracking_carriers_tenant_id', ['tenant_id'], false, 'btree'],
  ['tracking_carriers', 'ix_tracking_carriers_carrier_type_concept_id', ['carrier_type_concept_id'], false, 'btree'],
  ['tracking_carriers', 'ix_tracking_carriers_external_provider_id', ['external_provider_id'], false, 'btree'],
  ['tracking_carriers', 'ix_tracking_carriers_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['tracking_carriers', 'ix_tracking_carriers_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['tracking_carriers', 'ix_tracking_carriers_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['tracking_carriers', 'ix_tracking_carriers_tenant_id_state_concept_id', ['tenant_id', 'state_concept_id', 'updated_at desc'], false, 'btree'],
  ['tracking_events', 'ix_tracking_events_trackable_subject_id', ['trackable_subject_id'], false, 'btree'],
  ['tracking_events', 'ix_tracking_events_milestone_definition_id', ['milestone_definition_id'], false, 'btree'],
  ['tracking_events', 'ix_tracking_events_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['tracking_events', 'ix_tracking_events_location_ping_id', ['location_ping_id'], false, 'btree'],
  ['tracking_events', 'ix_tracking_events_actor_user_id', ['actor_user_id'], false, 'btree'],
  ['tracking_events', 'ix_tracking_events_source_concept_id', ['source_concept_id'], false, 'btree'],
  ['tracking_events', 'ix_tracking_events_recorded_by_user_id', ['recorded_by_user_id'], false, 'btree'],
];
