import type { IndexTuple } from '../catalog.types';

/**
 * Índices secundarios declarados por el modelo oficial para el schema `workflow`.
 * 55 definiciones. Generado desde los `<<INDEX_SET>>` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const workflowIndexes: readonly IndexTuple[] = [
  // [tabla, nombre, columnas, único, método]
  ['state_definitions', 'ix_state_definitions_state_machine_definition_id', ['state_machine_definition_id'], false, 'btree'],
  ['state_definitions', 'ix_state_definitions_state_concept_id', ['state_concept_id'], false, 'btree'],
  ['state_definitions', 'ix_state_definitions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['state_definitions', 'ix_state_definitions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['state_definitions', 'ix_state_definitions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['state_machine_definitions', 'uq_state_machine_definitions_machine_code', ['machine_code'], true, 'btree'],
  ['state_machine_definitions', 'ix_state_machine_definitions_state_value_set_id', ['state_value_set_id'], false, 'btree'],
  ['state_machine_definitions', 'ix_state_machine_definitions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['state_machine_definitions', 'ix_state_machine_definitions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['state_machine_definitions', 'ix_state_machine_definitions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['state_machine_definitions', 'uq_state_machine_definitions_state_value_set_id_version_number', ['state_value_set_id', 'version_number'], true, 'btree'],
  ['state_transition_definitions', 'ix_state_transition_definitions_state_machine_definition_id', ['state_machine_definition_id'], false, 'btree'],
  ['state_transition_definitions', 'ix_state_transition_definitions_from_state_concept_id', ['from_state_concept_id'], false, 'btree'],
  ['state_transition_definitions', 'ix_state_transition_definitions_to_state_concept_id', ['to_state_concept_id'], false, 'btree'],
  ['state_transition_definitions', 'ix_state_transition_definitions_required_permission_id', ['required_permission_id'], false, 'btree'],
  ['state_transition_definitions', 'ix_state_transition_definitions_purpose_of_use_concept_id', ['purpose_of_use_concept_id'], false, 'btree'],
  ['state_transition_definitions', 'ix_state_transition_definitions_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['state_transition_definitions', 'ix_state_transition_definitions_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['state_transition_definitions', 'ix_state_transition_definitions_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['state_transition_events', 'ix_state_transition_events_state_machine_definition_id', ['state_machine_definition_id'], false, 'btree'],
  ['state_transition_events', 'ix_state_transition_events_transition_definition_id', ['transition_definition_id'], false, 'btree'],
  ['state_transition_events', 'ix_state_transition_events_from_state_concept_id', ['from_state_concept_id'], false, 'btree'],
  ['state_transition_events', 'ix_state_transition_events_to_state_concept_id', ['to_state_concept_id'], false, 'btree'],
  ['state_transition_events', 'ix_state_transition_events_actor_user_id', ['actor_user_id'], false, 'btree'],
  ['state_transition_events', 'ix_state_transition_events_actor_tenant_id', ['actor_tenant_id'], false, 'btree'],
  ['state_transition_events', 'ix_state_transition_events_reason_concept_id', ['reason_concept_id'], false, 'btree'],
  ['state_transition_events', 'uq_state_transition_events_idempotency', ['idempotency_key'], true, 'btree'],
  ['state_transition_events', 'brin_state_transition_events_occurred_at', ['occurred_at'], false, 'brin'],
  ['state_transition_events', 'uq_state_transition_idempotency', ['state_machine_definition_id', 'aggregate_id', 'idempotency_key'], true, 'btree', 'idempotency_key IS NOT NULL'],
  ['transition_guards', 'ix_transition_guards_state_transition_definition_id', ['state_transition_definition_id'], false, 'btree'],
  ['transition_guards', 'ix_transition_guards_guard_type_concept_id', ['guard_type_concept_id'], false, 'btree'],
  ['transition_guards', 'ix_transition_guards_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['transition_guards', 'ix_transition_guards_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['transition_guards', 'ix_transition_guards_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['transition_side_effects', 'ix_transition_side_effects_state_transition_definition_id', ['state_transition_definition_id'], false, 'btree'],
  ['transition_side_effects', 'ix_transition_side_effects_side_effect_type_concept_id', ['side_effect_type_concept_id'], false, 'btree'],
  ['transition_side_effects', 'ix_transition_side_effects_execution_mode_concept_id', ['execution_mode_concept_id'], false, 'btree'],
  ['transition_side_effects', 'ix_transition_side_effects_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['transition_side_effects', 'ix_transition_side_effects_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['transition_side_effects', 'ix_transition_side_effects_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['workflow_instances', 'ix_workflow_instances_subject_type_concept_id', ['subject_type_concept_id'], false, 'btree'],
  ['workflow_instances', 'ix_workflow_instances_tenant_id', ['tenant_id'], false, 'btree'],
  ['workflow_instances', 'ix_workflow_instances_current_state_concept_id', ['current_state_concept_id'], false, 'btree'],
  ['workflow_instances', 'ix_workflow_instances_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['workflow_instances', 'ix_workflow_instances_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['workflow_instances', 'ix_workflow_instances_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
  ['workflow_instances', 'ix_workflow_instances_tenant_id_status_concept_id', ['tenant_id', 'status_concept_id', 'updated_at desc'], false, 'btree'],
  ['workflow_tasks', 'ix_workflow_tasks_workflow_instance_id', ['workflow_instance_id'], false, 'btree'],
  ['workflow_tasks', 'ix_workflow_tasks_task_type_concept_id', ['task_type_concept_id'], false, 'btree'],
  ['workflow_tasks', 'ix_workflow_tasks_assigned_user_id', ['assigned_user_id'], false, 'btree'],
  ['workflow_tasks', 'ix_workflow_tasks_assigned_role_concept_id', ['assigned_role_concept_id'], false, 'btree'],
  ['workflow_tasks', 'ix_workflow_tasks_required_permission_id', ['required_permission_id'], false, 'btree'],
  ['workflow_tasks', 'ix_workflow_tasks_status_concept_id', ['status_concept_id'], false, 'btree'],
  ['workflow_tasks', 'ix_workflow_tasks_created_by_user_id', ['created_by_user_id'], false, 'btree'],
  ['workflow_tasks', 'ix_workflow_tasks_updated_by_user_id', ['updated_by_user_id'], false, 'btree'],
];
