export {
  CreateSegmentDto,
  SegmentResponseDto,
  SegmentMemberInputDto,
  RefreshSegmentDto,
  RefreshSegmentResponseDto,
  CreateCampaignDto,
  CampaignResponseDto,
  MaterializeMembersDto,
  MaterializeMembersResponseDto,
  PublishTemplateVersionDto,
  TemplateVersionResponseDto,
  CreateJourneyDto,
  JourneyResponseDto,
  JourneyStepDto,
  AddJourneyStepsDto,
  JourneyStepsResponseDto,
  CohortMemberDto,
  ActivateJourneyDto,
  ActivateJourneyResponseDto,
  AdvanceEnrollmentDto,
  AdvanceEnrollmentResponseDto,
  ExitEnrollmentDto,
  ExitEnrollmentResponseDto,
  CreateTrackedLinkDto,
  TrackedLinkResponseDto,
  TrackedLinkClickResponseDto,
  RecordTouchpointDto,
  TouchpointResponseDto,
  ComputeAttributionDto,
  AttributionTouchDto,
  ComputeAttributionResponseDto,
} from './marketing.dto';
export type {
  MemberType,
  MarketingChannel,
  SegmentType,
  CampaignType,
  CampaignObjective,
  JourneyTrigger,
  JourneyStepType,
  ExitReason,
  TouchType,
  ConversionRefType,
  AttributionModel,
} from './marketing.dto';
