/**
 * Catálogo de sub-códigos de negocio estables para el módulo `promotions`
 * (lealtad, referidos, promociones, cupones y redenciones). Se usan como 3er
 * argumento (`reason`) de `DomainException` y sus subclases, encima del
 * `code` genérico (CONFLICT, NOT_FOUND, etc.) que ya fija el status HTTP.
 */
export enum PromotionsErrorReason {
  // --- Programas de lealtad ---
  PROGRAM_CODE_ALREADY_EXISTS = 'PROGRAM_CODE_ALREADY_EXISTS',
  ROLLING_EXPIRY_REQUIRES_DAYS = 'ROLLING_EXPIRY_REQUIRES_DAYS',
  PROGRAM_NOT_FOUND = 'PROGRAM_NOT_FOUND',
  PROGRAM_NOT_ACTIVE = 'PROGRAM_NOT_ACTIVE',
  PROGRAM_HAS_NO_TIERS = 'PROGRAM_HAS_NO_TIERS',
  POINTS_RULE_REQUIRES_AMOUNT = 'POINTS_RULE_REQUIRES_AMOUNT',
  CREDIT_RULE_REQUIRES_AMOUNT = 'CREDIT_RULE_REQUIRES_AMOUNT',

  // --- Membresías y puntos ---
  MEMBERSHIP_NOT_FOUND = 'MEMBERSHIP_NOT_FOUND',
  MEMBERSHIP_NOT_ACTIVE = 'MEMBERSHIP_NOT_ACTIVE',
  EARNING_RULE_NOT_FOUND = 'EARNING_RULE_NOT_FOUND',
  EARNING_RULE_WRONG_PROGRAM = 'EARNING_RULE_WRONG_PROGRAM',
  EARNING_RULE_NOT_ACTIVE = 'EARNING_RULE_NOT_ACTIVE',
  EARNING_RULE_OUT_OF_VALIDITY = 'EARNING_RULE_OUT_OF_VALIDITY',
  EARNING_RULE_GRANTS_NO_POINTS = 'EARNING_RULE_GRANTS_NO_POINTS',
  EARNING_RULE_CAP_REACHED = 'EARNING_RULE_CAP_REACHED',
  REDEMPTION_POINTS_MUST_BE_POSITIVE = 'REDEMPTION_POINTS_MUST_BE_POSITIVE',
  INSUFFICIENT_POINTS_BALANCE = 'INSUFFICIENT_POINTS_BALANCE',

  // --- Referidos ---
  REFERRAL_PROGRAM_NOT_FOUND = 'REFERRAL_PROGRAM_NOT_FOUND',
  REFERRAL_PROGRAM_NOT_ACTIVE = 'REFERRAL_PROGRAM_NOT_ACTIVE',
  REFERRAL_PROGRAM_OUT_OF_VALIDITY = 'REFERRAL_PROGRAM_OUT_OF_VALIDITY',
  REFERRAL_LIMIT_REACHED = 'REFERRAL_LIMIT_REACHED',
  REFERRAL_NOT_FOUND = 'REFERRAL_NOT_FOUND',
  REFERRAL_ALREADY_QUALIFIED = 'REFERRAL_ALREADY_QUALIFIED',
  REFERRAL_SELF_NOT_ALLOWED = 'REFERRAL_SELF_NOT_ALLOWED',
  REFERRAL_EVENT_MISMATCH = 'REFERRAL_EVENT_MISMATCH',
  REWARD_MEMBERSHIP_NOT_FOUND = 'REWARD_MEMBERSHIP_NOT_FOUND',
  REFERRAL_WALLET_CREDIT_MISSING_CURRENCY = 'REFERRAL_WALLET_CREDIT_MISSING_CURRENCY',
  REFERRAL_CODE_GENERATION_EXHAUSTED = 'REFERRAL_CODE_GENERATION_EXHAUSTED',

  // --- Promociones ---
  PROMOTION_CODE_ALREADY_EXISTS = 'PROMOTION_CODE_ALREADY_EXISTS',
  PROMOTION_INVALID_DATE_RANGE = 'PROMOTION_INVALID_DATE_RANGE',
  PROMOTION_NOT_FOUND = 'PROMOTION_NOT_FOUND',
  PROMOTION_NOT_ACTIVE = 'PROMOTION_NOT_ACTIVE',
  PROMOTION_OUT_OF_VALIDITY = 'PROMOTION_OUT_OF_VALIDITY',
  PROMOTION_REDEMPTION_LIMIT_REACHED = 'PROMOTION_REDEMPTION_LIMIT_REACHED',
  PROMOTION_PER_USER_LIMIT_REACHED = 'PROMOTION_PER_USER_LIMIT_REACHED',
  PROMOTION_BUDGET_EXHAUSTED = 'PROMOTION_BUDGET_EXHAUSTED',
  NO_RULE_APPLIES_TO_ORDER = 'NO_RULE_APPLIES_TO_ORDER',
  PERCENTAGE_RULE_REQUIRES_PERCENTAGE = 'PERCENTAGE_RULE_REQUIRES_PERCENTAGE',
  PERCENTAGE_OUT_OF_RANGE = 'PERCENTAGE_OUT_OF_RANGE',
  FIXED_RULE_REQUIRES_AMOUNT = 'FIXED_RULE_REQUIRES_AMOUNT',
  BOGO_RULE_REQUIRES_QUANTITIES = 'BOGO_RULE_REQUIRES_QUANTITIES',

  // --- Cupones y redenciones ---
  PERSONAL_COUPON_REQUIRES_MEMBER = 'PERSONAL_COUPON_REQUIRES_MEMBER',
  PERSONAL_COUPON_SINGLE_QUANTITY = 'PERSONAL_COUPON_SINGLE_QUANTITY',
  COUPON_NOT_FOUND = 'COUPON_NOT_FOUND',
  COUPON_NOT_REDEEMABLE = 'COUPON_NOT_REDEEMABLE',
  COUPON_CODE_GENERATION_EXHAUSTED = 'COUPON_CODE_GENERATION_EXHAUSTED',
  DISCOUNT_TARGET_REQUIRED = 'DISCOUNT_TARGET_REQUIRED',
  REDEMPTION_NOT_FOUND = 'REDEMPTION_NOT_FOUND',
  REDEMPTION_NOT_APPLIED = 'REDEMPTION_NOT_APPLIED',

  // --- Contexto de petición ---
  TENANT_ID_REQUIRED_FOR_LISTING = 'TENANT_ID_REQUIRED_FOR_LISTING',
}
