import { Injectable } from '@nestjs/common';
import { LockMode } from '@mikro-orm/core';
import type { EntityManager } from '@mikro-orm/postgresql';
import {
  DynamicEnumDefinitions,
  DynamicEnumVersions,
  DynamicEnumOptions,
  DynamicEnumBindings,
  SystemContexts,
  SystemContextVersions,
  SystemContextInputs,
  SystemContextRefreshRuns,
  SystemContextBindings,
} from '../entities';
import { createdBy } from '../../../common';

/**
 * Describe el contrato estructural de create enum definition data.
 */
export interface CreateEnumDefinitionData {
  /**
   * Valor de code mantenido por la instancia.
   */
  code: string;
  /**
   * Valor de name mantenido por la instancia.
   */
  name: string;
  /**
   * Valor de description mantenido por la instancia.
   */
  description?: string;
  /**
   * Identificador asociado a value set.
   */
  valueSetId: string;
  /**
   * Identificador asociado a scope type concept.
   */
  scopeTypeConceptId: string;
  /**
   * Identificador asociado a tenant.
   */
  tenantId?: string;
  /**
   * Identificador asociado a country concept.
   */
  countryConceptId?: string;
  /**
   * Identificador asociado a selection mode concept.
   */
  selectionModeConceptId: string;
  /**
   * Valor de allow tenant extension mantenido por la instancia.
   */
  allowTenantExtension: boolean;
  /**
   * Valor de allow custom value mantenido por la instancia.
   */
  allowCustomValue: boolean;
  /**
   * Identificador asociado a status concept.
   */
  statusConceptId: string;
  /**
   * Identificador asociado a actor user.
   */
  actorUserId?: string;
}

/**
 * Describe el contrato estructural de create enum option data.
 */
export interface CreateEnumOptionData {
  /**
   * Identificador asociado a dynamic enum version.
   */
  dynamicEnumVersionId: string;
  /**
   * Identificador asociado a concept.
   */
  conceptId: string;
  /**
   * Valor de code mantenido por la instancia.
   */
  code: string;
  /**
   * Valor de display mantenido por la instancia.
   */
  display: string;
  /**
   * Valor de ordinal mantenido por la instancia.
   */
  ordinal: number;
  /**
   * Valor de is default mantenido por la instancia.
   */
  isDefault: boolean;
  /**
   * Valor de enabled mantenido por la instancia.
   */
  enabled: boolean;
  /**
   * Valor de metadata json mantenido por la instancia.
   */
  metadataJson?: unknown;
  /**
   * Identificador asociado a recorded by user.
   */
  recordedByUserId?: string;
}

/**
 * Describe el contrato estructural de create context version data.
 */
export interface CreateContextVersionData {
  /**
   * Identificador asociado a system context.
   */
  systemContextId: string;
  /**
   * Valor de version number mantenido por la instancia.
   */
  versionNumber: number;
  /**
   * Identificador asociado a refresh run.
   */
  refreshRunId?: string;
  /**
   * Valor de schema version mantenido por la instancia.
   */
  schemaVersion: string;
  /**
   * Valor de context json mantenido por la instancia.
   */
  contextJson: unknown;
  /**
   * Valor de content hash mantenido por la instancia.
   */
  contentHash: string;
  /**
   * Identificador asociado a generated by agent.
   */
  generatedByAgentId?: string;
  /**
   * Valor de effective from mantenido por la instancia.
   */
  effectiveFrom?: Date;
  /**
   * Valor de expires at mantenido por la instancia.
   */
  expiresAt?: Date;
  /**
   * Identificador asociado a status concept.
   */
  statusConceptId: string;
  /**
   * Identificador asociado a recorded by user.
   */
  recordedByUserId?: string;
}

/**
 * Acceso a `system_context.*`: definiciones, versiones, opciones y bindings de
 * enumeraciones dinámicas; contextos de sistema con sus versiones, entradas,
 * corridas de refresco y bindings de consumo.
 */
@Injectable()
export class SystemContextRepository {
  // --- Definiciones de enum (UC-45-01, 11) ---

  /**
   * Crea create enum definition.
   *
   * @param em - Contexto de persistencia o transacción activa.
   * @param data - Valor de data requerido por la operación.
   * @returns Resultado de create enum definition conforme al contrato `DynamicEnumDefinitions`.
   */
  createEnumDefinition(
    em: EntityManager,
    data: CreateEnumDefinitionData,
  ): DynamicEnumDefinitions {
    return em.create(
      DynamicEnumDefinitions,
      {
        code: data.code,
        name: data.name,
        description: data.description,
        valueSetId: data.valueSetId,
        scopeTypeConceptId: data.scopeTypeConceptId,
        tenantId: data.tenantId,
        countryConceptId: data.countryConceptId,
        selectionModeConceptId: data.selectionModeConceptId,
        allowTenantExtension: data.allowTenantExtension,
        allowCustomValue: data.allowCustomValue,
        statusConceptId: data.statusConceptId,
        ...createdBy(data.actorUserId),
      },
      { partial: true },
    );
  }

  /**
   * Obtiene find enum definition by id.
   *
   * @param em - Contexto de persistencia o transacción activa.
   * @param id - Identificador de id.
   * @returns Resultado de find enum definition by id conforme al contrato `Promise<DynamicEnumDefinitions | null>`.
   */
  findEnumDefinitionById(
    em: EntityManager,
    id: string,
  ): Promise<DynamicEnumDefinitions | null> {
    return em.findOne(DynamicEnumDefinitions, { id });
  }

  /**
   * Definición bloqueada. Redactar una versión la serializa: `version_number`
   * sale de un máximo, y dos redacciones simultáneas darían el mismo número.
   */
  findEnumDefinitionForUpdate(
    em: EntityManager,
    id: string,
  ): Promise<DynamicEnumDefinitions | null> {
    return em.findOne(
      DynamicEnumDefinitions,
      { id },
      { lockMode: LockMode.PESSIMISTIC_WRITE },
    );
  }

  /**
   * Obtiene find enum definition by code.
   *
   * @param em - Contexto de persistencia o transacción activa.
   * @param code - Valor de code requerido por la operación.
   * @returns Resultado de find enum definition by code conforme al contrato `Promise<DynamicEnumDefinitions | null>`.
   */
  findEnumDefinitionByCode(
    em: EntityManager,
    code: string,
  ): Promise<DynamicEnumDefinitions | null> {
    return em.findOne(DynamicEnumDefinitions, { code });
  }

  // --- Versiones de enum (UC-45-02, 03) ---

  /**
   * Crea create enum version.
   *
   * @param em - Contexto de persistencia o transacción activa.
   * @param data - Valor de data requerido por la operación.
   * @returns Resultado de create enum version conforme al contrato `DynamicEnumVersions`.
   */
  createEnumVersion(
    em: EntityManager,
    data: {
      /**
       * Identificador asociado a dynamic enum definition.
       */
      dynamicEnumDefinitionId: string;
      /**
       * Valor de version number mantenido por la instancia.
       */
      versionNumber: number;
      /**
       * Identificador asociado a value set version.
       */
      valueSetVersionId?: string;
      /**
       * Valor de schema version mantenido por la instancia.
       */
      schemaVersion?: string;
      /**
       * Identificador asociado a status concept.
       */
      statusConceptId: string;
      /**
       * Identificador asociado a recorded by user.
       */
      recordedByUserId?: string;
    },
  ): DynamicEnumVersions {
    return em.create(
      DynamicEnumVersions,
      {
        dynamicEnumDefinitionId: data.dynamicEnumDefinitionId,
        versionNumber: data.versionNumber,
        valueSetVersionId: data.valueSetVersionId,
        schemaVersion: data.schemaVersion,
        statusConceptId: data.statusConceptId,
        recordedAt: new Date(),
        recordedByUserId: data.recordedByUserId,
      },
      { partial: true },
    );
  }

  /**
   * Obtiene find enum version.
   *
   * @param em - Contexto de persistencia o transacción activa.
   * @param dynamicEnumDefinitionId - Identificador de dynamic enum definition.
   * @param versionNumber - Valor de version number requerido por la operación.
   * @returns Resultado de find enum version conforme al contrato `Promise<DynamicEnumVersions | null>`.
   */
  findEnumVersion(
    em: EntityManager,
    dynamicEnumDefinitionId: string,
    versionNumber: number,
  ): Promise<DynamicEnumVersions | null> {
    return em.findOne(DynamicEnumVersions, {
      dynamicEnumDefinitionId,
      versionNumber,
    });
  }

  /**
   * Obtiene find enum version for update.
   *
   * @param em - Contexto de persistencia o transacción activa.
   * @param dynamicEnumDefinitionId - Identificador de dynamic enum definition.
   * @param versionNumber - Valor de version number requerido por la operación.
   * @returns Resultado de find enum version for update conforme al contrato `Promise<DynamicEnumVersions | null>`.
   */
  findEnumVersionForUpdate(
    em: EntityManager,
    dynamicEnumDefinitionId: string,
    versionNumber: number,
  ): Promise<DynamicEnumVersions | null> {
    return em.findOne(
      DynamicEnumVersions,
      { dynamicEnumDefinitionId, versionNumber },
      { lockMode: LockMode.PESSIMISTIC_WRITE },
    );
  }

  /**
   * Obtiene find latest enum version.
   *
   * @param em - Contexto de persistencia o transacción activa.
   * @param dynamicEnumDefinitionId - Identificador de dynamic enum definition.
   * @returns Resultado de find latest enum version conforme al contrato `Promise<DynamicEnumVersions | null>`.
   */
  findLatestEnumVersion(
    em: EntityManager,
    dynamicEnumDefinitionId: string,
  ): Promise<DynamicEnumVersions | null> {
    return em.findOne(
      DynamicEnumVersions,
      { dynamicEnumDefinitionId },
      { orderBy: { versionNumber: 'DESC' } },
    );
  }

  /**
   * Versión publicada y vigente de la definición, bloqueada: publicar otra la
   * supersede, y sólo puede haber una sin `effective_to`.
   */
  findPublishedEnumVersionForUpdate(
    em: EntityManager,
    dynamicEnumDefinitionId: string,
    publishedStatusConceptId: string,
  ): Promise<DynamicEnumVersions | null> {
    return em.findOne(
      DynamicEnumVersions,
      {
        dynamicEnumDefinitionId,
        statusConceptId: publishedStatusConceptId,
        effectiveTo: null,
      },
      { lockMode: LockMode.PESSIMISTIC_WRITE },
    );
  }

  /**
   * Obtiene find published enum version.
   *
   * @param em - Contexto de persistencia o transacción activa.
   * @param dynamicEnumDefinitionId - Identificador de dynamic enum definition.
   * @param publishedStatusConceptId - Identificador de published status concept.
   * @returns Resultado de find published enum version conforme al contrato `Promise<DynamicEnumVersions | null>`.
   */
  findPublishedEnumVersion(
    em: EntityManager,
    dynamicEnumDefinitionId: string,
    publishedStatusConceptId: string,
  ): Promise<DynamicEnumVersions | null> {
    return em.findOne(DynamicEnumVersions, {
      dynamicEnumDefinitionId,
      statusConceptId: publishedStatusConceptId,
      effectiveTo: null,
    });
  }

  // --- Opciones de enum (UC-45-02, 05) ---

  /** Snapshot inmutable: las opciones de una versión no se reescriben. */
  createEnumOption(
    em: EntityManager,
    data: CreateEnumOptionData,
  ): DynamicEnumOptions {
    return em.create(
      DynamicEnumOptions,
      {
        dynamicEnumVersionId: data.dynamicEnumVersionId,
        conceptId: data.conceptId,
        code: data.code,
        display: data.display,
        ordinal: data.ordinal,
        isDefault: data.isDefault,
        enabled: data.enabled,
        metadataJson: data.metadataJson,
        recordedAt: new Date(),
        recordedByUserId: data.recordedByUserId,
      },
      { partial: true },
    );
  }

  /**
   * Obtiene find enum options.
   *
   * @param em - Contexto de persistencia o transacción activa.
   * @param dynamicEnumVersionId - Identificador de dynamic enum version.
   * @returns Resultado de find enum options conforme al contrato `Promise<DynamicEnumOptions[]>`.
   */
  findEnumOptions(
    em: EntityManager,
    dynamicEnumVersionId: string,
  ): Promise<DynamicEnumOptions[]> {
    return em.find(
      DynamicEnumOptions,
      { dynamicEnumVersionId },
      { orderBy: { ordinal: 'ASC' } },
    );
  }

  /**
   * Ejecuta la operación count enabled options.
   *
   * @param em - Contexto de persistencia o transacción activa.
   * @param dynamicEnumVersionId - Identificador de dynamic enum version.
   * @returns Resultado de count enabled options conforme al contrato `Promise<number>`.
   */
  countEnabledOptions(
    em: EntityManager,
    dynamicEnumVersionId: string,
  ): Promise<number> {
    return em.count(DynamicEnumOptions, {
      dynamicEnumVersionId,
      enabled: true,
    });
  }

  // --- Bindings de enum (UC-45-04, 05, 11) ---

  /**
   * Crea create enum binding.
   *
   * @param em - Contexto de persistencia o transacción activa.
   * @param data - Valor de data requerido por la operación.
   * @returns Resultado de create enum binding conforme al contrato `DynamicEnumBindings`.
   */
  createEnumBinding(
    em: EntityManager,
    data: {
      /**
       * Identificador asociado a dynamic enum definition.
       */
      dynamicEnumDefinitionId: string;
      /**
       * Valor de target schema name mantenido por la instancia.
       */
      targetSchemaName: string;
      /**
       * Valor de target entity name mantenido por la instancia.
       */
      targetEntityName: string;
      /**
       * Valor de target field name mantenido por la instancia.
       */
      targetFieldName: string;
      /**
       * Identificador asociado a system context.
       */
      systemContextId?: string;
      /**
       * Valor de required mantenido por la instancia.
       */
      required: boolean;
      /**
       * Identificador asociado a fallback concept.
       */
      fallbackConceptId?: string;
      /**
       * Identificador asociado a validation mode concept.
       */
      validationModeConceptId: string;
      /**
       * Identificador asociado a status concept.
       */
      statusConceptId: string;
      /**
       * Identificador asociado a actor user.
       */
      actorUserId?: string;
    },
  ): DynamicEnumBindings {
    return em.create(
      DynamicEnumBindings,
      {
        dynamicEnumDefinitionId: data.dynamicEnumDefinitionId,
        targetSchemaName: data.targetSchemaName,
        targetEntityName: data.targetEntityName,
        targetFieldName: data.targetFieldName,
        systemContextId: data.systemContextId,
        required: data.required,
        fallbackConceptId: data.fallbackConceptId,
        validationModeConceptId: data.validationModeConceptId,
        statusConceptId: data.statusConceptId,
        ...createdBy(data.actorUserId),
      },
      { partial: true },
    );
  }

  /** Un campo destino no puede tener dos enums gobernándolo a la vez. */
  findEnumBindingByTarget(
    em: EntityManager,
    targetSchemaName: string,
    targetEntityName: string,
    targetFieldName: string,
    activeStatusConceptId: string,
  ): Promise<DynamicEnumBindings | null> {
    return em.findOne(DynamicEnumBindings, {
      targetSchemaName,
      targetEntityName,
      targetFieldName,
      statusConceptId: activeStatusConceptId,
    });
  }

  /** Bindings activos de la definición, bloqueados: retirarla los deshabilita. */
  findEnumBindingsForUpdate(
    em: EntityManager,
    dynamicEnumDefinitionId: string,
    activeStatusConceptId: string,
  ): Promise<DynamicEnumBindings[]> {
    return em.find(
      DynamicEnumBindings,
      { dynamicEnumDefinitionId, statusConceptId: activeStatusConceptId },
      { lockMode: LockMode.PESSIMISTIC_WRITE },
    );
  }

  // --- Contextos de sistema (UC-45-06, 09, 12) ---

  /**
   * Crea create context.
   *
   * @param em - Contexto de persistencia o transacción activa.
   * @param data - Valor de data requerido por la operación.
   * @returns Resultado de create context conforme al contrato `SystemContexts`.
   */
  createContext(
    em: EntityManager,
    data: {
      /**
       * Valor de code mantenido por la instancia.
       */
      code: string;
      /**
       * Valor de name mantenido por la instancia.
       */
      name: string;
      /**
       * Valor de description mantenido por la instancia.
       */
      description?: string;
      /**
       * Identificador asociado a context type concept.
       */
      contextTypeConceptId: string;
      /**
       * Identificador asociado a scope type concept.
       */
      scopeTypeConceptId: string;
      /**
       * Identificador asociado a tenant.
       */
      tenantId?: string;
      /**
       * Identificador asociado a country concept.
       */
      countryConceptId?: string;
      /**
       * Identificador asociado a locale concept.
       */
      localeConceptId?: string;
      /**
       * Identificador asociado a refresh policy concept.
       */
      refreshPolicyConceptId?: string;
      /**
       * Identificador asociado a status concept.
       */
      statusConceptId: string;
      /**
       * Identificador asociado a actor user.
       */
      actorUserId?: string;
    },
  ): SystemContexts {
    return em.create(
      SystemContexts,
      {
        code: data.code,
        name: data.name,
        description: data.description,
        contextTypeConceptId: data.contextTypeConceptId,
        scopeTypeConceptId: data.scopeTypeConceptId,
        tenantId: data.tenantId,
        countryConceptId: data.countryConceptId,
        localeConceptId: data.localeConceptId,
        refreshPolicyConceptId: data.refreshPolicyConceptId,
        statusConceptId: data.statusConceptId,
        ...createdBy(data.actorUserId),
      },
      { partial: true },
    );
  }

  /**
   * Obtiene find context by id.
   *
   * @param em - Contexto de persistencia o transacción activa.
   * @param id - Identificador de id.
   * @returns Resultado de find context by id conforme al contrato `Promise<SystemContexts | null>`.
   */
  findContextById(
    em: EntityManager,
    id: string,
  ): Promise<SystemContexts | null> {
    return em.findOne(SystemContexts, { id });
  }

  /** Todo lo que mueve `current_version_id` bloquea el contexto. */
  findContextForUpdate(
    em: EntityManager,
    id: string,
  ): Promise<SystemContexts | null> {
    return em.findOne(
      SystemContexts,
      { id },
      { lockMode: LockMode.PESSIMISTIC_WRITE },
    );
  }

  /**
   * Obtiene find context by code.
   *
   * @param em - Contexto de persistencia o transacción activa.
   * @param code - Valor de code requerido por la operación.
   * @returns Resultado de find context by code conforme al contrato `Promise<SystemContexts | null>`.
   */
  findContextByCode(
    em: EntityManager,
    code: string,
  ): Promise<SystemContexts | null> {
    return em.findOne(SystemContexts, { code });
  }

  // --- Versiones de contexto (UC-45-06, 07, 09, 12) ---

  /**
   * Crea create context version.
   *
   * @param em - Contexto de persistencia o transacción activa.
   * @param data - Valor de data requerido por la operación.
   * @returns Resultado de create context version conforme al contrato `SystemContextVersions`.
   */
  createContextVersion(
    em: EntityManager,
    data: CreateContextVersionData,
  ): SystemContextVersions {
    return em.create(
      SystemContextVersions,
      {
        systemContextId: data.systemContextId,
        versionNumber: data.versionNumber,
        refreshRunId: data.refreshRunId,
        schemaVersion: data.schemaVersion,
        contextJson: data.contextJson,
        contentHash: data.contentHash,
        generatedByAgentId: data.generatedByAgentId,
        effectiveFrom: data.effectiveFrom,
        expiresAt: data.expiresAt,
        statusConceptId: data.statusConceptId,
        recordedAt: new Date(),
        recordedByUserId: data.recordedByUserId,
      },
      { partial: true },
    );
  }

  /**
   * Obtiene find context version by id.
   *
   * @param em - Contexto de persistencia o transacción activa.
   * @param id - Identificador de id.
   * @returns Resultado de find context version by id conforme al contrato `Promise<SystemContextVersions | null>`.
   */
  findContextVersionById(
    em: EntityManager,
    id: string,
  ): Promise<SystemContextVersions | null> {
    return em.findOne(SystemContextVersions, { id });
  }

  /**
   * Obtiene find context version for update.
   *
   * @param em - Contexto de persistencia o transacción activa.
   * @param systemContextId - Identificador de system context.
   * @param versionNumber - Valor de version number requerido por la operación.
   * @returns Resultado de find context version for update conforme al contrato `Promise<SystemContextVersions | null>`.
   */
  findContextVersionForUpdate(
    em: EntityManager,
    systemContextId: string,
    versionNumber: number,
  ): Promise<SystemContextVersions | null> {
    return em.findOne(
      SystemContextVersions,
      { systemContextId, versionNumber },
      { lockMode: LockMode.PESSIMISTIC_WRITE },
    );
  }

  /**
   * Obtiene find latest context version.
   *
   * @param em - Contexto de persistencia o transacción activa.
   * @param systemContextId - Identificador de system context.
   * @returns Resultado de find latest context version conforme al contrato `Promise<SystemContextVersions | null>`.
   */
  findLatestContextVersion(
    em: EntityManager,
    systemContextId: string,
  ): Promise<SystemContextVersions | null> {
    return em.findOne(
      SystemContextVersions,
      { systemContextId },
      { orderBy: { versionNumber: 'DESC' } },
    );
  }

  /** Versión vigente del contexto, bloqueada: activar otra la supersede. */
  findActiveContextVersionForUpdate(
    em: EntityManager,
    systemContextId: string,
    activeStatusConceptId: string,
  ): Promise<SystemContextVersions | null> {
    return em.findOne(
      SystemContextVersions,
      {
        systemContextId,
        statusConceptId: activeStatusConceptId,
        effectiveTo: null,
      },
      { lockMode: LockMode.PESSIMISTIC_WRITE },
    );
  }

  // --- Entradas de la versión (UC-45-08) ---

  /** Procedencia append-only: la entrada snapshotea la fuente tal como estaba. */
  createContextInput(
    em: EntityManager,
    data: {
      /**
       * Identificador asociado a system context version.
       */
      systemContextVersionId: string;
      /**
       * Identificador asociado a source type concept.
       */
      sourceTypeConceptId: string;
      /**
       * Valor de source schema name mantenido por la instancia.
       */
      sourceSchemaName?: string;
      /**
       * Valor de source entity name mantenido por la instancia.
       */
      sourceEntityName?: string;
      /**
       * Identificador asociado a source record.
       */
      sourceRecordId?: string;
      /**
       * Identificador asociado a source version.
       */
      sourceVersionId?: string;
      /**
       * Valor de source content hash mantenido por la instancia.
       */
      sourceContentHash?: string;
      /**
       * Valor de source freshness at mantenido por la instancia.
       */
      sourceFreshnessAt?: Date;
      /**
       * Valor de precedence mantenido por la instancia.
       */
      precedence: number;
      /**
       * Valor de required mantenido por la instancia.
       */
      required: boolean;
      /**
       * Identificador asociado a recorded by user.
       */
      recordedByUserId?: string;
    },
  ): SystemContextInputs {
    return em.create(
      SystemContextInputs,
      {
        systemContextVersionId: data.systemContextVersionId,
        sourceTypeConceptId: data.sourceTypeConceptId,
        sourceSchemaName: data.sourceSchemaName,
        sourceEntityName: data.sourceEntityName,
        sourceRecordId: data.sourceRecordId,
        sourceVersionId: data.sourceVersionId,
        sourceContentHash: data.sourceContentHash,
        sourceFreshnessAt: data.sourceFreshnessAt,
        precedence: data.precedence,
        required: data.required,
        recordedAt: new Date(),
        recordedByUserId: data.recordedByUserId,
      },
      { partial: true },
    );
  }

  /**
   * Obtiene find context inputs.
   *
   * @param em - Contexto de persistencia o transacción activa.
   * @param systemContextVersionId - Identificador de system context version.
   * @returns Resultado de find context inputs conforme al contrato `Promise<SystemContextInputs[]>`.
   */
  findContextInputs(
    em: EntityManager,
    systemContextVersionId: string,
  ): Promise<SystemContextInputs[]> {
    return em.find(
      SystemContextInputs,
      { systemContextVersionId },
      { orderBy: { precedence: 'ASC' } },
    );
  }

  // --- Corridas de refresco (UC-45-07) ---

  /**
   * Crea create refresh run.
   *
   * @param em - Contexto de persistencia o transacción activa.
   * @param data - Valor de data requerido por la operación.
   * @returns Resultado de create refresh run conforme al contrato `SystemContextRefreshRuns`.
   */
  createRefreshRun(
    em: EntityManager,
    data: {
      /**
       * Identificador asociado a system context.
       */
      systemContextId: string;
      /**
       * Valor de idempotency key mantenido por la instancia.
       */
      idempotencyKey: string;
      /**
       * Identificador asociado a trigger concept.
       */
      triggerConceptId: string;
      /**
       * Identificador asociado a status concept.
       */
      statusConceptId: string;
      /**
       * Identificador asociado a recorded by user.
       */
      recordedByUserId?: string;
    },
  ): SystemContextRefreshRuns {
    return em.create(
      SystemContextRefreshRuns,
      {
        systemContextId: data.systemContextId,
        idempotencyKey: data.idempotencyKey,
        triggerConceptId: data.triggerConceptId,
        statusConceptId: data.statusConceptId,
        startedAt: new Date(),
        recordedAt: new Date(),
        recordedByUserId: data.recordedByUserId,
      },
      { partial: true },
    );
  }

  /** Clave de idempotencia del worker: reintentar no vuelve a refrescar. */
  findRefreshRunByKey(
    em: EntityManager,
    idempotencyKey: string,
  ): Promise<SystemContextRefreshRuns | null> {
    return em.findOne(SystemContextRefreshRuns, { idempotencyKey });
  }

  // --- Bindings de consumo (UC-45-10) ---

  /**
   * Crea create context binding.
   *
   * @param em - Contexto de persistencia o transacción activa.
   * @param data - Valor de data requerido por la operación.
   * @returns Resultado de create context binding conforme al contrato `SystemContextBindings`.
   */
  createContextBinding(
    em: EntityManager,
    data: {
      /**
       * Identificador asociado a system context.
       */
      systemContextId: string;
      /**
       * Identificador asociado a consumer type concept.
       */
      consumerTypeConceptId: string;
      /**
       * Identificador asociado a consumer.
       */
      consumerId: string;
      /**
       * Identificador asociado a tenant.
       */
      tenantId?: string;
      /**
       * Identificador asociado a country concept.
       */
      countryConceptId?: string;
      /**
       * Valor de activation rule json mantenido por la instancia.
       */
      activationRuleJson?: unknown;
      /**
       * Valor de priority mantenido por la instancia.
       */
      priority: number;
      /**
       * Valor de valid from mantenido por la instancia.
       */
      validFrom?: Date;
      /**
       * Valor de valid to mantenido por la instancia.
       */
      validTo?: Date;
      /**
       * Identificador asociado a status concept.
       */
      statusConceptId: string;
      /**
       * Identificador asociado a actor user.
       */
      actorUserId?: string;
    },
  ): SystemContextBindings {
    return em.create(
      SystemContextBindings,
      {
        systemContextId: data.systemContextId,
        consumerTypeConceptId: data.consumerTypeConceptId,
        consumerId: data.consumerId,
        tenantId: data.tenantId,
        countryConceptId: data.countryConceptId,
        activationRuleJson: data.activationRuleJson,
        priority: data.priority,
        validFrom: data.validFrom,
        validTo: data.validTo,
        statusConceptId: data.statusConceptId,
        ...createdBy(data.actorUserId),
      },
      { partial: true },
    );
  }

  /** Bindings vivos del mismo consumidor: la ventana no puede solaparse. */
  findContextBindingsForConsumer(
    em: EntityManager,
    systemContextId: string,
    consumerTypeConceptId: string,
    consumerId: string,
    activeStatusConceptId: string,
  ): Promise<SystemContextBindings[]> {
    return em.find(SystemContextBindings, {
      systemContextId,
      consumerTypeConceptId,
      consumerId,
      statusConceptId: activeStatusConceptId,
    });
  }
}
