import type { ForeignKeyTuple } from '../catalog.types';

/**
 * Claves foráneas declaradas por el modelo oficial para el schema `authz`.
 * 67 restricciones. Generado desde las notas `FK/` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const authzForeignKeys: readonly ForeignKeyTuple[] = [
  // [tablaOrigen, columnaOrigen, schemaDestino, tablaDestino, columnaDestino]
  ['access_policies', 'created_by_user_id', 'iam', 'users', 'id'],
  ['access_policies', 'effect_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['access_policies', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['access_policies', 'tenant_id', 'directory', 'tenants', 'id'],
  ['access_policies', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['clinical_access_grants', 'access_level_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['clinical_access_grants', 'branch_id', 'directory', 'branches', 'id'],
  ['clinical_access_grants', 'consent_id', 'consent', 'consents', 'id'],
  ['clinical_access_grants', 'created_by_user_id', 'iam', 'users', 'id'],
  ['clinical_access_grants', 'encounter_id', 'clinical', 'encounters', 'id'],
  ['clinical_access_grants', 'granted_user_id', 'iam', 'users', 'id'],
  ['clinical_access_grants', 'patient_profile_id', 'profiles', 'patient_profiles', 'profile_id'],
  ['clinical_access_grants', 'reason_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['clinical_access_grants', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['clinical_access_grants', 'tenant_id', 'directory', 'tenants', 'id'],
  ['clinical_access_grants', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['field_permissions', 'created_by_user_id', 'iam', 'users', 'id'],
  ['field_permissions', 'mask_strategy_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['field_permissions', 'role_id', 'authz', 'roles', 'id'],
  ['field_permissions', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['permission_categories', 'created_by_user_id', 'iam', 'users', 'id'],
  ['permission_categories', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['permissions', 'action_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['permissions', 'category_id', 'authz', 'permission_categories', 'id'],
  ['permissions', 'created_by_user_id', 'iam', 'users', 'id'],
  ['permissions', 'default_scope_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['permissions', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['permissions', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['resource_scope_grants', 'created_by_user_id', 'iam', 'users', 'id'],
  ['resource_scope_grants', 'effect_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['resource_scope_grants', 'permission_id', 'authz', 'permissions', 'id'],
  ['resource_scope_grants', 'resource_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['resource_scope_grants', 'subject_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['resource_scope_grants', 'tenant_id', 'directory', 'tenants', 'id'],
  ['resource_scope_grants', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['role_permissions', 'created_by_user_id', 'iam', 'users', 'id'],
  ['role_permissions', 'effect_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['role_permissions', 'field_value_set_id', 'terminology', 'value_sets', 'id'],
  ['role_permissions', 'permission_id', 'authz', 'permissions', 'id'],
  ['role_permissions', 'role_id', 'authz', 'roles', 'id'],
  ['role_permissions', 'scope_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['role_permissions', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['role_permissions', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['roles', 'base_role_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['roles', 'created_by_user_id', 'iam', 'users', 'id'],
  ['roles', 'parent_role_id', 'authz', 'roles', 'id'],
  ['roles', 'scope_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['roles', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['roles', 'tenant_id', 'directory', 'tenants', 'id'],
  ['roles', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['user_permission_grants', 'created_by_user_id', 'iam', 'users', 'id'],
  ['user_permission_grants', 'effect_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['user_permission_grants', 'permission_id', 'authz', 'permissions', 'id'],
  ['user_permission_grants', 'scope_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['user_permission_grants', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['user_permission_grants', 'tenant_id', 'directory', 'tenants', 'id'],
  ['user_permission_grants', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['user_permission_grants', 'user_id', 'iam', 'users', 'id'],
  ['user_role_assignments', 'assigned_by_user_id', 'iam', 'users', 'id'],
  ['user_role_assignments', 'branch_id', 'directory', 'branches', 'id'],
  ['user_role_assignments', 'created_by_user_id', 'iam', 'users', 'id'],
  ['user_role_assignments', 'practice_id', 'practice', 'practices', 'id'],
  ['user_role_assignments', 'role_id', 'authz', 'roles', 'id'],
  ['user_role_assignments', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['user_role_assignments', 'tenant_id', 'directory', 'tenants', 'id'],
  ['user_role_assignments', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['user_role_assignments', 'user_id', 'iam', 'users', 'id'],
];
