import type { ForeignKeyTuple } from '../catalog.types';

/**
 * Claves foráneas declaradas por el modelo oficial para el schema `clinical_ext`.
 * 84 restricciones. Generado desde las notas `FK/` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const clinicalExtForeignKeys: readonly ForeignKeyTuple[] = [
  // [tablaOrigen, columnaOrigen, schemaDestino, tablaDestino, columnaDestino]
  ['care_gaps', 'created_by_user_id', 'iam', 'users', 'id'],
  ['care_gaps', 'gap_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['care_gaps', 'measure_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['care_gaps', 'patient_profile_id', 'profiles', 'patient_profiles', 'profile_id'],
  ['care_gaps', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['care_gaps', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['care_teams', 'category_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['care_teams', 'created_by_user_id', 'iam', 'users', 'id'],
  ['care_teams', 'episode_id', 'clinical', 'care_episodes', 'id'],
  ['care_teams', 'patient_profile_id', 'profiles', 'patient_profiles', 'profile_id'],
  ['care_teams', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['care_teams', 'tenant_id', 'directory', 'tenants', 'id'],
  ['care_teams', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['care_team_members', 'care_team_id', 'clinical_ext', 'care_teams', 'id'],
  ['care_team_members', 'created_by_user_id', 'iam', 'users', 'id'],
  ['care_team_members', 'member_role_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['care_team_members', 'practitioner_profile_id', 'profiles', 'health_practitioner_profiles', 'profile_id'],
  ['care_team_members', 'related_person_id', 'profiles', 'related_persons', 'id'],
  ['care_team_members', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['care_team_members', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['cds_rules', 'created_by_user_id', 'iam', 'users', 'id'],
  ['cds_rules', 'rule_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['cds_rules', 'severity_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['cds_rules', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['cds_rules', 'tenant_id', 'directory', 'tenants', 'id'],
  ['cds_rules', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['clinical_alerts', 'alert_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['clinical_alerts', 'created_by_user_id', 'iam', 'users', 'id'],
  ['clinical_alerts', 'encounter_id', 'clinical', 'encounters', 'id'],
  ['clinical_alerts', 'overridden_by_user_id', 'iam', 'users', 'id'],
  ['clinical_alerts', 'patient_profile_id', 'profiles', 'patient_profiles', 'profile_id'],
  ['clinical_alerts', 'rule_id', 'clinical_ext', 'cds_rules', 'id'],
  ['clinical_alerts', 'severity_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['clinical_alerts', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['clinical_alerts', 'trigger_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['clinical_alerts', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['drug_interactions', 'created_by_user_id', 'iam', 'users', 'id'],
  ['drug_interactions', 'evidence_level_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['drug_interactions', 'severity_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['drug_interactions', 'substance_a_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['drug_interactions', 'substance_b_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['drug_interactions', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['immunization_schedules', 'created_by_user_id', 'iam', 'users', 'id'],
  ['immunization_schedules', 'jurisdiction_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['immunization_schedules', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['immunization_schedules', 'tenant_id', 'directory', 'tenants', 'id'],
  ['immunization_schedules', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['immunization_schedules', 'vaccine_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['order_sets', 'condition_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['order_sets', 'created_by_user_id', 'iam', 'users', 'id'],
  ['order_sets', 'specialty_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['order_sets', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['order_sets', 'tenant_id', 'directory', 'tenants', 'id'],
  ['order_sets', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['order_set_items', 'code_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['order_set_items', 'created_by_user_id', 'iam', 'users', 'id'],
  ['order_set_items', 'default_route_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['order_set_items', 'item_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['order_set_items', 'order_set_id', 'clinical_ext', 'order_sets', 'id'],
  ['order_set_items', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['reference_ranges', 'code_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['reference_ranges', 'condition_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['reference_ranges', 'created_by_user_id', 'iam', 'users', 'id'],
  ['reference_ranges', 'sex_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['reference_ranges', 'unit_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['reference_ranges', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['referrals', 'created_by_user_id', 'iam', 'users', 'id'],
  ['referrals', 'patient_profile_id', 'profiles', 'patient_profiles', 'profile_id'],
  ['referrals', 'priority_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['referrals', 'reason_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['referrals', 'referring_profile_id', 'profiles', 'health_practitioner_profiles', 'profile_id'],
  ['referrals', 'service_request_id', 'clinical', 'service_requests', 'id'],
  ['referrals', 'source_encounter_id', 'clinical', 'encounters', 'id'],
  ['referrals', 'specialty_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['referrals', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['referrals', 'target_profile_id', 'profiles', 'health_practitioner_profiles', 'profile_id'],
  ['referrals', 'target_tenant_id', 'directory', 'tenants', 'id'],
  ['referrals', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['virtual_encounters', 'created_by_user_id', 'iam', 'users', 'id'],
  ['virtual_encounters', 'encounter_id', 'clinical', 'encounters', 'id'],
  ['virtual_encounters', 'platform_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['virtual_encounters', 'recording_file_id', 'common', 'files', 'id'],
  ['virtual_encounters', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['virtual_encounters', 'updated_by_user_id', 'iam', 'users', 'id'],
];
