import type { ForeignKeyTuple } from '../catalog.types';

/**
 * Claves foráneas declaradas por el modelo oficial para el schema `consent`.
 * 81 restricciones. Generado desde las notas `FK/` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const consentForeignKeys: readonly ForeignKeyTuple[] = [
  // [tablaOrigen, columnaOrigen, schemaDestino, tablaDestino, columnaDestino]
  ['consent_events', 'event_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['consent_events', 'new_status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['consent_events', 'previous_status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['consent_events', 'reason_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['consent_events', 'recorded_by_user_id', 'iam', 'users', 'id'],
  ['consent_events', 'subject_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['consent_evidence', 'captured_channel_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['consent_evidence', 'document_file_id', 'common', 'files', 'id'],
  ['consent_evidence', 'evidence_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['consent_evidence', 'recorded_by_user_id', 'iam', 'users', 'id'],
  ['consent_evidence', 'signature_id', 'chart', 'clinical_note_signatures', 'id'],
  ['consent_evidence', 'subject_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['consent_provisions', 'action_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['consent_provisions', 'actor_role_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['consent_provisions', 'actor_tenant_id', 'directory', 'tenants', 'id'],
  ['consent_provisions', 'actor_user_id', 'iam', 'users', 'id'],
  ['consent_provisions', 'consent_id', 'consent', 'consents', 'id'],
  ['consent_provisions', 'created_by_user_id', 'iam', 'users', 'id'],
  ['consent_provisions', 'data_class_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['consent_provisions', 'provision_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['consent_provisions', 'purpose_of_use_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['consent_provisions', 'security_label_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['consent_provisions', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['consents', 'category_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['consents', 'created_by_user_id', 'iam', 'users', 'id'],
  ['consents', 'granted_by_related_person_id', 'profiles', 'related_persons', 'id'],
  ['consents', 'granted_by_user_id', 'iam', 'users', 'id'],
  ['consents', 'patient_profile_id', 'profiles', 'patient_profiles', 'profile_id'],
  ['consents', 'processing_legal_basis_id', 'consent', 'processing_legal_bases', 'id'],
  ['consents', 'processing_purpose_id', 'consent', 'processing_purposes', 'id'],
  ['consents', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['consents', 'tenant_id', 'directory', 'tenants', 'id'],
  ['consents', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['consents', 'withdrawal_reason_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['hipaa_authorizations', 'created_by_user_id', 'iam', 'users', 'id'],
  ['hipaa_authorizations', 'expiration_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['hipaa_authorizations', 'patient_profile_id', 'profiles', 'patient_profiles', 'profile_id'],
  ['hipaa_authorizations', 'processing_purpose_id', 'consent', 'processing_purposes', 'id'],
  ['hipaa_authorizations', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['hipaa_authorizations', 'tenant_id', 'directory', 'tenants', 'id'],
  ['hipaa_authorizations', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['patient_objections', 'created_by_user_id', 'iam', 'users', 'id'],
  ['patient_objections', 'objection_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['patient_objections', 'patient_profile_id', 'profiles', 'patient_profiles', 'profile_id'],
  ['patient_objections', 'processing_purpose_id', 'consent', 'processing_purposes', 'id'],
  ['patient_objections', 'resolution_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['patient_objections', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['patient_objections', 'tenant_id', 'directory', 'tenants', 'id'],
  ['patient_objections', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['privacy_restrictions', 'created_by_user_id', 'iam', 'users', 'id'],
  ['privacy_restrictions', 'data_class_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['privacy_restrictions', 'patient_profile_id', 'profiles', 'patient_profiles', 'profile_id'],
  ['privacy_restrictions', 'restriction_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['privacy_restrictions', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['privacy_restrictions', 'target_actor_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['privacy_restrictions', 'tenant_id', 'directory', 'tenants', 'id'],
  ['privacy_restrictions', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['processing_legal_bases', 'created_by_user_id', 'iam', 'users', 'id'],
  ['processing_legal_bases', 'general_legal_basis_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['processing_legal_bases', 'jurisdiction_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['processing_legal_bases', 'processing_purpose_id', 'consent', 'processing_purposes', 'id'],
  ['processing_legal_bases', 'special_category_condition_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['processing_legal_bases', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['processing_legal_bases', 'tenant_id', 'directory', 'tenants', 'id'],
  ['processing_legal_bases', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['processing_purposes', 'created_by_user_id', 'iam', 'users', 'id'],
  ['processing_purposes', 'default_retention_class_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['processing_purposes', 'purpose_category_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['processing_purposes', 'purpose_of_use_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['processing_purposes', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['processing_purposes', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['treatment_informed_consents', 'created_by_user_id', 'iam', 'users', 'id'],
  ['treatment_informed_consents', 'decision_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['treatment_informed_consents', 'encounter_id', 'clinical', 'encounters', 'id'],
  ['treatment_informed_consents', 'interpreter_user_id', 'iam', 'users', 'id'],
  ['treatment_informed_consents', 'patient_profile_id', 'profiles', 'patient_profiles', 'profile_id'],
  ['treatment_informed_consents', 'procedure_code_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['treatment_informed_consents', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['treatment_informed_consents', 'tenant_id', 'directory', 'tenants', 'id'],
  ['treatment_informed_consents', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['treatment_informed_consents', 'witness_user_id', 'iam', 'users', 'id'],
];
