import type { ForeignKeyTuple } from '../catalog.types';

/**
 * Claves foráneas declaradas por el modelo oficial para el schema `delegated_access`.
 * 50 restricciones. Generado desde las notas `FK/` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const delegatedAccessForeignKeys: readonly ForeignKeyTuple[] = [
  // [tablaOrigen, columnaOrigen, schemaDestino, tablaDestino, columnaDestino]
  ['delegated_access_approval_requests', 'decided_by_user_id', 'iam', 'users', 'id'],
  ['delegated_access_approval_requests', 'decision_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['delegated_access_approval_requests', 'encounter_id', 'clinical', 'encounters', 'id'],
  ['delegated_access_approval_requests', 'patient_profile_id', 'profiles', 'patient_profiles', 'profile_id'],
  ['delegated_access_approval_requests', 'practitioner_delegate_assignment_id', 'delegated_access', 'practitioner_delegate_assignments', 'id'],
  ['delegated_access_approval_requests', 'requested_permission_id', 'authz', 'permissions', 'id'],
  ['delegated_access_approval_requests', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['delegated_access_grants', 'approved_by_user_id', 'iam', 'users', 'id'],
  ['delegated_access_grants', 'created_by_user_id', 'iam', 'users', 'id'],
  ['delegated_access_grants', 'encounter_id', 'clinical', 'encounters', 'id'],
  ['delegated_access_grants', 'grant_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['delegated_access_grants', 'patient_profile_id', 'profiles', 'patient_profiles', 'profile_id'],
  ['delegated_access_grants', 'practitioner_delegate_assignment_id', 'delegated_access', 'practitioner_delegate_assignments', 'id'],
  ['delegated_access_grants', 'purpose_of_use_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['delegated_access_grants', 'resource_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['delegated_access_grants', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['delegated_access_grants', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['delegated_permission_set_items', 'delegated_permission_set_id', 'delegated_access', 'delegated_permission_sets', 'id'],
  ['delegated_permission_set_items', 'permission_id', 'authz', 'permissions', 'id'],
  ['delegated_permission_sets', 'created_by_user_id', 'iam', 'users', 'id'],
  ['delegated_permission_sets', 'delegate_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['delegated_permission_sets', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['delegated_permission_sets', 'tenant_id', 'directory', 'tenants', 'id'],
  ['delegated_permission_sets', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['delegation_events', 'actor_user_id', 'iam', 'users', 'id'],
  ['delegation_events', 'event_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['delegation_events', 'practitioner_delegate_assignment_id', 'delegated_access', 'practitioner_delegate_assignments', 'id'],
  ['delegation_events', 'reason_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['delegation_events', 'target_user_id', 'iam', 'users', 'id'],
  ['organization_user_assignments', 'access_scope_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['organization_user_assignments', 'assignment_role_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['organization_user_assignments', 'care_space_id', 'practice', 'care_spaces', 'id'],
  ['organization_user_assignments', 'clinical_unit_id', 'practice', 'clinical_units', 'id'],
  ['organization_user_assignments', 'created_by_user_id', 'iam', 'users', 'id'],
  ['organization_user_assignments', 'diagnostic_unit_id', 'diagnostic_units', 'diagnostic_units', 'id'],
  ['organization_user_assignments', 'pharmacy_id', 'pharmacy', 'pharmacies', 'id'],
  ['organization_user_assignments', 'practice_id', 'practice', 'practices', 'id'],
  ['organization_user_assignments', 'practice_site_id', 'practice', 'practice_sites', 'id'],
  ['organization_user_assignments', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['organization_user_assignments', 'supervisor_user_id', 'iam', 'users', 'id'],
  ['organization_user_assignments', 'tenant_membership_id', 'directory', 'tenant_memberships', 'id'],
  ['organization_user_assignments', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['practitioner_delegate_assignments', 'appointment_scope_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['practitioner_delegate_assignments', 'created_by_user_id', 'iam', 'users', 'id'],
  ['practitioner_delegate_assignments', 'delegate_role_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['practitioner_delegate_assignments', 'delegated_permission_set_id', 'delegated_access', 'delegated_permission_sets', 'id'],
  ['practitioner_delegate_assignments', 'patient_scope_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['practitioner_delegate_assignments', 'practitioner_role_assignment_id', 'practice', 'practitioner_role_assignments', 'id'],
  ['practitioner_delegate_assignments', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['practitioner_delegate_assignments', 'updated_by_user_id', 'iam', 'users', 'id'],
];
