import type { ForeignKeyTuple } from '../catalog.types';

/**
 * Claves foráneas declaradas por el modelo oficial para el schema `diagnostics` (parte 2/2).
 * 71 restricciones. Generado desde las notas `FK/` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const diagnosticsForeignKeys2: readonly ForeignKeyTuple[] = [
  // [tablaOrigen, columnaOrigen, schemaDestino, tablaDestino, columnaDestino]
  ['radiation_dose_events', 'custodian_tenant_id', 'directory', 'tenants', 'id'],
  ['radiation_dose_events', 'device_id', 'iam', 'devices', 'id'],
  ['radiation_dose_events', 'imaging_series_id', 'diagnostics', 'imaging_series', 'id'],
  ['radiation_dose_events', 'imaging_study_id', 'diagnostics', 'imaging_studies', 'id'],
  ['radiation_dose_events', 'patient_profile_id', 'profiles', 'patient_profiles', 'profile_id'],
  ['radiation_dose_events', 'unit_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['result_verifications', 'custodian_tenant_id', 'directory', 'tenants', 'id'],
  ['result_verifications', 'previous_verification_id', 'diagnostics', 'result_verifications', 'id'],
  ['result_verifications', 'result_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['result_verifications', 'signature_id', 'chart', 'clinical_note_signatures', 'id'],
  ['result_verifications', 'verifiable_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['result_verifications', 'verification_level_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['result_verifications', 'verified_by_profile_id', 'profiles', 'health_practitioner_profiles', 'profile_id'],
  ['specimen_chain_of_custody_events', 'custody_event_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['specimen_chain_of_custody_events', 'from_party_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['specimen_chain_of_custody_events', 'location_id', 'diagnostics', 'dicom_object_locations', 'id'],
  ['specimen_chain_of_custody_events', 'signed_by_user_id', 'iam', 'users', 'id'],
  ['specimen_chain_of_custody_events', 'specimen_container_id', 'diagnostics', 'specimen_containers', 'id'],
  ['specimen_chain_of_custody_events', 'specimen_id', 'diagnostics', 'specimens', 'id'],
  ['specimen_chain_of_custody_events', 'to_party_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['specimen_collection_events', 'body_site_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['specimen_collection_events', 'collection_site_id', 'practice', 'practice_sites', 'id'],
  ['specimen_collection_events', 'collector_profile_id', 'profiles', 'health_practitioner_profiles', 'profile_id'],
  ['specimen_collection_events', 'event_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['specimen_collection_events', 'fasting_status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['specimen_collection_events', 'method_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['specimen_collection_events', 'specimen_id', 'diagnostics', 'specimens', 'id'],
  ['specimen_container_events', 'actor_profile_id', 'profiles', 'health_practitioner_profiles', 'profile_id'],
  ['specimen_container_events', 'destination_location_id', 'practice', 'care_spaces', 'id'],
  ['specimen_container_events', 'event_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['specimen_container_events', 'source_location_id', 'diagnostics', 'dicom_object_locations', 'id'],
  ['specimen_container_events', 'specimen_container_id', 'diagnostics', 'specimen_containers', 'id'],
  ['specimen_containers', 'additive_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['specimen_containers', 'capacity_unit_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['specimen_containers', 'container_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['specimen_containers', 'created_by_user_id', 'iam', 'users', 'id'],
  ['specimen_containers', 'parent_container_id', 'diagnostics', 'specimen_containers', 'id'],
  ['specimen_containers', 'specimen_id', 'diagnostics', 'specimens', 'id'],
  ['specimen_containers', 'specimen_quantity_unit_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['specimen_containers', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['specimen_containers', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['specimen_identifiers', 'created_by_user_id', 'iam', 'users', 'id'],
  ['specimen_identifiers', 'identifier_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['specimen_identifiers', 'specimen_id', 'diagnostics', 'specimens', 'id'],
  ['specimen_identifiers', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['specimen_parent_links', 'child_specimen_id', 'diagnostics', 'specimens', 'id'],
  ['specimen_parent_links', 'parent_specimen_id', 'diagnostics', 'specimens', 'id'],
  ['specimen_parent_links', 'quantity_unit_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['specimen_parent_links', 'relationship_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['specimen_processing_steps', 'additive_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['specimen_processing_steps', 'created_by_user_id', 'iam', 'users', 'id'],
  ['specimen_processing_steps', 'performer_profile_id', 'profiles', 'health_practitioner_profiles', 'profile_id'],
  ['specimen_processing_steps', 'procedure_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['specimen_processing_steps', 'specimen_id', 'diagnostics', 'specimens', 'id'],
  ['specimen_rejection_events', 'recollection_service_request_id', 'clinical', 'service_requests', 'id'],
  ['specimen_rejection_events', 'rejected_by_profile_id', 'profiles', 'health_practitioner_profiles', 'profile_id'],
  ['specimen_rejection_events', 'rejection_reason_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['specimen_rejection_events', 'specimen_id', 'diagnostics', 'specimens', 'id'],
  ['specimens', 'body_site_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['specimens', 'collection_method_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['specimens', 'collector_profile_id', 'profiles', 'health_practitioner_profiles', 'profile_id'],
  ['specimens', 'container_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['specimens', 'created_by_user_id', 'iam', 'users', 'id'],
  ['specimens', 'custodian_tenant_id', 'directory', 'tenants', 'id'],
  ['specimens', 'encounter_id', 'clinical', 'encounters', 'id'],
  ['specimens', 'patient_profile_id', 'profiles', 'patient_profiles', 'profile_id'],
  ['specimens', 'quantity_unit_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['specimens', 'service_request_id', 'clinical', 'service_requests', 'id'],
  ['specimens', 'specimen_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['specimens', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['specimens', 'updated_by_user_id', 'iam', 'users', 'id'],
];
