import type { ForeignKeyTuple } from '../catalog.types';

/**
 * Claves foráneas declaradas por el modelo oficial para el schema `diagnostic_units`.
 * 66 restricciones. Generado desde las notas `FK/` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const diagnosticUnitsForeignKeys: readonly ForeignKeyTuple[] = [
  // [tablaOrigen, columnaOrigen, schemaDestino, tablaDestino, columnaDestino]
  ['diagnostic_equipment', 'created_by_user_id', 'iam', 'users', 'id'],
  ['diagnostic_equipment', 'diagnostic_unit_site_id', 'diagnostic_units', 'diagnostic_unit_sites', 'id'],
  ['diagnostic_equipment', 'equipment_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['diagnostic_equipment', 'modality_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['diagnostic_equipment', 'operational_status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['diagnostic_equipment', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['diagnostic_price_schedules', 'broker_tenant_id', 'directory', 'tenants', 'id'],
  ['diagnostic_price_schedules', 'created_by_user_id', 'iam', 'users', 'id'],
  ['diagnostic_price_schedules', 'currency_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['diagnostic_price_schedules', 'diagnostic_unit_id', 'diagnostic_units', 'diagnostic_units', 'id'],
  ['diagnostic_price_schedules', 'diagnostic_unit_site_id', 'diagnostic_units', 'diagnostic_unit_sites', 'id'],
  ['diagnostic_price_schedules', 'insurer_tenant_id', 'directory', 'tenants', 'id'],
  ['diagnostic_price_schedules', 'price_schedule_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['diagnostic_price_schedules', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['diagnostic_price_schedules', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['diagnostic_study_components', 'component_role_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['diagnostic_study_components', 'created_by_user_id', 'iam', 'users', 'id'],
  ['diagnostic_study_offerings', 'body_site_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['diagnostic_study_offerings', 'created_by_user_id', 'iam', 'users', 'id'],
  ['diagnostic_study_offerings', 'diagnostic_unit_id', 'diagnostic_units', 'diagnostic_units', 'id'],
  ['diagnostic_study_offerings', 'diagnostic_unit_site_id', 'diagnostic_units', 'diagnostic_unit_sites', 'id'],
  ['diagnostic_study_offerings', 'modality_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['diagnostic_study_offerings', 'specimen_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['diagnostic_study_offerings', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['diagnostic_study_offerings', 'study_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['diagnostic_study_offerings', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['diagnostic_study_prices', 'diagnostic_study_offering_id', 'diagnostic_units', 'diagnostic_study_offerings', 'id'],
  ['diagnostic_study_prices', 'recorded_by_user_id', 'iam', 'users', 'id'],
  ['diagnostic_study_prices', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['diagnostic_unit_accreditations', 'accreditation_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['diagnostic_unit_accreditations', 'created_by_user_id', 'iam', 'users', 'id'],
  ['diagnostic_unit_accreditations', 'diagnostic_unit_id', 'diagnostic_units', 'diagnostic_units', 'id'],
  ['diagnostic_unit_accreditations', 'diagnostic_unit_site_id', 'diagnostic_units', 'diagnostic_unit_sites', 'id'],
  ['diagnostic_unit_accreditations', 'evidence_file_id', 'common', 'files', 'id'],
  ['diagnostic_unit_accreditations', 'issuer_tenant_id', 'directory', 'tenants', 'id'],
  ['diagnostic_unit_accreditations', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['diagnostic_unit_accreditations', 'verification_status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['diagnostic_unit_practitioner_assignments', 'assignment_role_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['diagnostic_unit_practitioner_assignments', 'created_by_user_id', 'iam', 'users', 'id'],
  ['diagnostic_unit_practitioner_assignments', 'diagnostic_unit_id', 'diagnostic_units', 'diagnostic_units', 'id'],
  ['diagnostic_unit_practitioner_assignments', 'diagnostic_unit_site_id', 'diagnostic_units', 'diagnostic_unit_sites', 'id'],
  ['diagnostic_unit_practitioner_assignments', 'practitioner_role_assignment_id', 'practice', 'practitioner_role_assignments', 'id'],
  ['diagnostic_unit_practitioner_assignments', 'specialty_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['diagnostic_unit_practitioner_assignments', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['diagnostic_unit_practitioner_assignments', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['diagnostic_unit_sites', 'created_by_user_id', 'iam', 'users', 'id'],
  ['diagnostic_unit_sites', 'diagnostic_unit_id', 'diagnostic_units', 'diagnostic_units', 'id'],
  ['diagnostic_unit_sites', 'practice_site_id', 'practice', 'practice_sites', 'id'],
  ['diagnostic_unit_sites', 'site_role_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['diagnostic_unit_sites', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['diagnostic_unit_sites', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['diagnostic_unit_specialties', 'created_by_user_id', 'iam', 'users', 'id'],
  ['diagnostic_unit_specialties', 'diagnostic_unit_id', 'diagnostic_units', 'diagnostic_units', 'id'],
  ['diagnostic_unit_specialties', 'specialty_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['diagnostic_unit_specialties', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['diagnostic_unit_specialties', 'verification_status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['diagnostic_units', 'created_by_user_id', 'iam', 'users', 'id'],
  ['diagnostic_units', 'diagnostic_unit_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['diagnostic_units', 'ownership_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['diagnostic_units', 'practice_id', 'practice', 'practices', 'id'],
  ['diagnostic_units', 'primary_practice_site_id', 'practice', 'practice_sites', 'id'],
  ['diagnostic_units', 'public_profile_id', 'community', 'public_profiles', 'id'],
  ['diagnostic_units', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['diagnostic_units', 'tenant_id', 'directory', 'tenants', 'id'],
  ['diagnostic_units', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['diagnostic_units', 'verification_status_concept_id', 'terminology', 'catalog_concepts', 'id'],
];
