import type { ForeignKeyTuple } from '../catalog.types';

/**
 * Claves foráneas declaradas por el modelo oficial para el schema `directory`.
 * 55 restricciones. Generado desde las notas `FK/` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const directoryForeignKeys: readonly ForeignKeyTuple[] = [
  // [tablaOrigen, columnaOrigen, schemaDestino, tablaDestino, columnaDestino]
  ['branches', 'branch_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['branches', 'created_by_user_id', 'iam', 'users', 'id'],
  ['branches', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['branches', 'tenant_id', 'directory', 'tenants', 'id'],
  ['branches', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['branch_memberships', 'branch_id', 'directory', 'branches', 'id'],
  ['branch_memberships', 'created_by_user_id', 'iam', 'users', 'id'],
  ['branch_memberships', 'local_role_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['branch_memberships', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['branch_memberships', 'tenant_membership_id', 'directory', 'tenant_memberships', 'id'],
  ['branch_memberships', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['tenants', 'country_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['tenants', 'created_by_user_id', 'iam', 'users', 'id'],
  ['tenants', 'currency_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['tenants', 'data_residency_region_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['tenants', 'jurisdiction_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['tenants', 'legal_entity_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['tenants', 'parent_tenant_id', 'directory', 'tenants', 'id'],
  ['tenants', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['tenants', 'tenant_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['tenants', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['tenants', 'verification_status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['tenant_affiliation_documents', 'created_by_user_id', 'iam', 'users', 'id'],
  ['tenant_affiliation_documents', 'document_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['tenant_affiliation_documents', 'file_id', 'common', 'files', 'id'],
  ['tenant_affiliation_documents', 'identifier_id', 'common', 'identifiers', 'id'],
  ['tenant_affiliation_documents', 'issuing_authority_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['tenant_affiliation_documents', 'related_person_id', 'profiles', 'persons', 'id'],
  ['tenant_affiliation_documents', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['tenant_affiliation_documents', 'tenant_id', 'directory', 'tenants', 'id'],
  ['tenant_affiliation_documents', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['tenant_affiliation_documents', 'verification_status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['tenant_affiliation_documents', 'verified_by_user_id', 'iam', 'users', 'id'],
  ['tenant_legal_representatives', 'ci_identifier_id', 'common', 'identifiers', 'id'],
  ['tenant_legal_representatives', 'created_by_user_id', 'iam', 'users', 'id'],
  ['tenant_legal_representatives', 'person_id', 'profiles', 'persons', 'id'],
  ['tenant_legal_representatives', 'power_of_attorney_document_id', 'directory', 'tenant_affiliation_documents', 'id'],
  ['tenant_legal_representatives', 'representative_role_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['tenant_legal_representatives', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['tenant_legal_representatives', 'tenant_id', 'directory', 'tenants', 'id'],
  ['tenant_legal_representatives', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['tenant_memberships', 'access_scope_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['tenant_memberships', 'created_by_user_id', 'iam', 'users', 'id'],
  ['tenant_memberships', 'invited_by_user_id', 'iam', 'users', 'id'],
  ['tenant_memberships', 'primary_branch_id', 'directory', 'branches', 'id'],
  ['tenant_memberships', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['tenant_memberships', 'tenant_id', 'directory', 'tenants', 'id'],
  ['tenant_memberships', 'tenant_role_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['tenant_memberships', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['tenant_memberships', 'user_id', 'iam', 'users', 'id'],
  ['tenant_web_configs', 'created_by_user_id', 'iam', 'users', 'id'],
  ['tenant_web_configs', 'primary_language_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['tenant_web_configs', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['tenant_web_configs', 'tenant_id', 'directory', 'tenants', 'id'],
  ['tenant_web_configs', 'updated_by_user_id', 'iam', 'users', 'id'],
];
