import type { ForeignKeyTuple } from '../catalog.types';

/**
 * Claves foráneas declaradas por el modelo oficial para el schema `education`.
 * 85 restricciones. Generado desde las notas `FK/` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const educationForeignKeys: readonly ForeignKeyTuple[] = [
  // [tablaOrigen, columnaOrigen, schemaDestino, tablaDestino, columnaDestino]
  ['assessment_attempts', 'assessment_id', 'education', 'assessments', 'id'],
  ['assessment_attempts', 'created_by_user_id', 'iam', 'users', 'id'],
  ['assessment_attempts', 'enrollment_id', 'education', 'enrollments', 'id'],
  ['assessment_attempts', 'graded_by_user_id', 'iam', 'users', 'id'],
  ['assessment_attempts', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['assessment_attempts', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['assessment_questions', 'assessment_id', 'education', 'assessments', 'id'],
  ['assessment_questions', 'created_by_user_id', 'iam', 'users', 'id'],
  ['assessment_questions', 'question_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['assessment_questions', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['assessments', 'assessment_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['assessments', 'course_id', 'education', 'courses', 'id'],
  ['assessments', 'course_module_id', 'education', 'course_modules', 'id'],
  ['assessments', 'created_by_user_id', 'iam', 'users', 'id'],
  ['assessments', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['assessments', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['certificates', 'course_id', 'education', 'courses', 'id'],
  ['certificates', 'created_by_user_id', 'iam', 'users', 'id'],
  ['certificates', 'enrollment_id', 'education', 'enrollments', 'id'],
  ['certificates', 'file_id', 'common', 'files', 'id'],
  ['certificates', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['certificates', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['cme_credit_records', 'accrediting_body_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['cme_credit_records', 'certificate_id', 'education', 'certificates', 'id'],
  ['cme_credit_records', 'created_by_user_id', 'iam', 'users', 'id'],
  ['cme_credit_records', 'jurisdiction_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['cme_credit_records', 'specialty_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['cme_credit_records', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['cme_credit_records', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['course_cohorts', 'course_id', 'education', 'courses', 'id'],
  ['course_cohorts', 'created_by_user_id', 'iam', 'users', 'id'],
  ['course_cohorts', 'delivery_mode_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['course_cohorts', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['course_cohorts', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['course_instructors', 'course_id', 'education', 'courses', 'id'],
  ['course_instructors', 'created_by_user_id', 'iam', 'users', 'id'],
  ['course_instructors', 'instructor_id', 'education', 'instructors', 'id'],
  ['course_instructors', 'role_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['course_instructors', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['course_modules', 'course_id', 'education', 'courses', 'id'],
  ['course_modules', 'created_by_user_id', 'iam', 'users', 'id'],
  ['course_modules', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['course_modules', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['course_reviews', 'course_id', 'education', 'courses', 'id'],
  ['course_reviews', 'created_by_user_id', 'iam', 'users', 'id'],
  ['course_reviews', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['course_reviews', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['course_versions', 'course_id', 'education', 'courses', 'id'],
  ['course_versions', 'created_by_user_id', 'iam', 'users', 'id'],
  ['course_versions', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['course_versions', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['courses', 'accrediting_body_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['courses', 'course_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['courses', 'cover_file_id', 'common', 'files', 'id'],
  ['courses', 'created_by_user_id', 'iam', 'users', 'id'],
  ['courses', 'currency_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['courses', 'language_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['courses', 'level_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['courses', 'specialty_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['courses', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['courses', 'tenant_id', 'directory', 'tenants', 'id'],
  ['courses', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['enrollments', 'course_id', 'education', 'courses', 'id'],
  ['enrollments', 'created_by_user_id', 'iam', 'users', 'id'],
  ['enrollments', 'enrollment_source_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['enrollments', 'learner_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['enrollments', 'payment_intent_id', 'payments', 'payment_intents', 'id'],
  ['enrollments', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['enrollments', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['instructors', 'created_by_user_id', 'iam', 'users', 'id'],
  ['instructors', 'photo_file_id', 'common', 'files', 'id'],
  ['instructors', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['instructors', 'tenant_id', 'directory', 'tenants', 'id'],
  ['instructors', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['instructors', 'user_id', 'iam', 'users', 'id'],
  ['lesson_progress', 'enrollment_id', 'education', 'enrollments', 'id'],
  ['lesson_progress', 'lesson_id', 'education', 'lessons', 'id'],
  ['lesson_progress', 'recorded_by_user_id', 'iam', 'users', 'id'],
  ['lesson_progress', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['lessons', 'content_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['lessons', 'course_module_id', 'education', 'course_modules', 'id'],
  ['lessons', 'created_by_user_id', 'iam', 'users', 'id'],
  ['lessons', 'media_file_id', 'common', 'files', 'id'],
  ['lessons', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['lessons', 'updated_by_user_id', 'iam', 'users', 'id'],
];
