import type { ForeignKeyTuple } from '../catalog.types';

/**
 * Claves foráneas declaradas por el modelo oficial para el schema `erp` (parte 3/3).
 * 69 restricciones. Generado desde las notas `FK/` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const erpForeignKeys3: readonly ForeignKeyTuple[] = [
  // [tablaOrigen, columnaOrigen, schemaDestino, tablaDestino, columnaDestino]
  ['purchase_requisition_items', 'item_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['purchase_requisition_items', 'profit_center_id', 'accounting', 'profit_centers', 'id'],
  ['purchase_requisition_items', 'project_id', 'erp', 'projects', 'id'],
  ['purchase_requisition_items', 'purchase_requisition_id', 'erp', 'purchase_requisitions', 'id'],
  ['purchase_requisition_items', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['purchase_requisition_items', 'unit_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['purchase_requisition_items', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['purchase_requisition_items', 'wbs_element_id', 'erp', 'wbs_elements', 'id'],
  ['purchase_requisitions', 'approval_status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['purchase_requisitions', 'created_by_user_id', 'iam', 'users', 'id'],
  ['purchase_requisitions', 'project_id', 'erp', 'projects', 'id'],
  ['purchase_requisitions', 'requester_employee_id', 'erp', 'employees', 'id'],
  ['purchase_requisitions', 'requesting_department_id', 'erp', 'departments', 'id'],
  ['purchase_requisitions', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['purchase_requisitions', 'tenant_id', 'directory', 'tenants', 'id'],
  ['purchase_requisitions', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['purchase_requisitions', 'wbs_element_id', 'erp', 'wbs_elements', 'id'],
  ['sales_order_items', 'contract_line_item_id', 'erp', 'contract_line_items', 'id'],
  ['sales_order_items', 'cost_center_id', 'accounting', 'cost_centers', 'id'],
  ['sales_order_items', 'created_by_user_id', 'iam', 'users', 'id'],
  ['sales_order_items', 'income_account_id', 'accounting', 'accounts', 'id'],
  ['sales_order_items', 'profit_center_id', 'accounting', 'profit_centers', 'id'],
  ['sales_order_items', 'project_id', 'erp', 'projects', 'id'],
  ['sales_order_items', 'sales_order_id', 'erp', 'sales_orders', 'id'],
  ['sales_order_items', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['sales_order_items', 'tax_code_id', 'billing', 'tax_codes', 'id'],
  ['sales_order_items', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['sales_order_items', 'wbs_element_id', 'erp', 'wbs_elements', 'id'],
  ['sales_orders', 'contract_id', 'erp', 'contracts', 'id'],
  ['sales_orders', 'created_by_user_id', 'iam', 'users', 'id'],
  ['sales_orders', 'currency_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['sales_orders', 'customer_business_partner_id', 'erp', 'business_partners', 'id'],
  ['sales_orders', 'opportunity_id', 'crm', 'opportunities', 'id'],
  ['sales_orders', 'owner_employee_id', 'erp', 'employees', 'id'],
  ['sales_orders', 'payment_terms_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['sales_orders', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['sales_orders', 'tenant_id', 'directory', 'tenants', 'id'],
  ['sales_orders', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['service_entry_items', 'cost_center_id', 'accounting', 'cost_centers', 'id'],
  ['service_entry_items', 'created_by_user_id', 'iam', 'users', 'id'],
  ['service_entry_items', 'currency_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['service_entry_items', 'profit_center_id', 'accounting', 'profit_centers', 'id'],
  ['service_entry_items', 'project_id', 'erp', 'projects', 'id'],
  ['service_entry_items', 'purchase_order_item_id', 'erp', 'purchase_order_items', 'id'],
  ['service_entry_items', 'service_entry_sheet_id', 'erp', 'service_entry_sheets', 'id'],
  ['service_entry_items', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['service_entry_items', 'wbs_element_id', 'erp', 'wbs_elements', 'id'],
  ['service_entry_sheets', 'accepted_by_employee_id', 'erp', 'employees', 'id'],
  ['service_entry_sheets', 'approval_status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['service_entry_sheets', 'created_by_user_id', 'iam', 'users', 'id'],
  ['service_entry_sheets', 'purchase_order_id', 'erp', 'purchase_orders', 'id'],
  ['service_entry_sheets', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['service_entry_sheets', 'supplier_business_partner_id', 'erp', 'business_partners', 'id'],
  ['service_entry_sheets', 'tenant_id', 'directory', 'tenants', 'id'],
  ['service_entry_sheets', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['time_off_requests', 'approver_user_id', 'iam', 'users', 'id'],
  ['time_off_requests', 'created_by_user_id', 'iam', 'users', 'id'],
  ['time_off_requests', 'employee_id', 'erp', 'employees', 'id'],
  ['time_off_requests', 'leave_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['time_off_requests', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['time_off_requests', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['wbs_elements', 'cost_center_id', 'accounting', 'cost_centers', 'id'],
  ['wbs_elements', 'created_by_user_id', 'iam', 'users', 'id'],
  ['wbs_elements', 'parent_wbs_element_id', 'erp', 'wbs_elements', 'id'],
  ['wbs_elements', 'profit_center_id', 'accounting', 'profit_centers', 'id'],
  ['wbs_elements', 'project_id', 'erp', 'projects', 'id'],
  ['wbs_elements', 'responsible_employee_id', 'erp', 'employees', 'id'],
  ['wbs_elements', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['wbs_elements', 'updated_by_user_id', 'iam', 'users', 'id'],
];
