import type { ForeignKeyTuple } from '../catalog.types';

/**
 * Claves foráneas declaradas por el modelo oficial para el schema `identity_assurance`.
 * 69 restricciones. Generado desde las notas `FK/` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const identityAssuranceForeignKeys: readonly ForeignKeyTuple[] = [
  // [tablaOrigen, columnaOrigen, schemaDestino, tablaDestino, columnaDestino]
  ['identity_assertions', 'assertion_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_assertions', 'assurance_level_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_assertions', 'identity_verification_case_id', 'identity_assurance', 'identity_verification_cases', 'id'],
  ['identity_assertions', 'issuer_identity_authority_id', 'identity_assurance', 'identity_authorities', 'id'],
  ['identity_assertions', 'revocation_reason_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_assertions', 'subject_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_authorities', 'assurance_framework_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_authorities', 'authority_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_authorities', 'created_by_user_id', 'iam', 'users', 'id'],
  ['identity_authorities', 'jurisdiction_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_authorities', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_authorities', 'tenant_id', 'directory', 'tenants', 'id'],
  ['identity_authorities', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['identity_authorities', 'verification_status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_authority_endpoints', 'assurance_level_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_authority_endpoints', 'capability_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_authority_endpoints', 'created_by_user_id', 'iam', 'users', 'id'],
  ['identity_authority_endpoints', 'identity_authority_id', 'identity_assurance', 'identity_authorities', 'id'],
  ['identity_authority_endpoints', 'integration_endpoint_id', 'integrations', 'integration_endpoints', 'id'],
  ['identity_authority_endpoints', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_authority_endpoints', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['identity_check_results', 'checked_by_actor_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_check_results', 'identity_check_id', 'identity_assurance', 'identity_checks', 'id'],
  ['identity_check_results', 'result_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_check_results', 'supersedes_result_id', 'identity_assurance', 'identity_check_results', 'id'],
  ['identity_checks', 'authority_id', 'identity_assurance', 'identity_authorities', 'id'],
  ['identity_checks', 'check_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_checks', 'created_by_user_id', 'iam', 'users', 'id'],
  ['identity_checks', 'identity_verification_case_id', 'identity_assurance', 'identity_verification_cases', 'id'],
  ['identity_checks', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_checks', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['identity_evidence_records', 'collected_under_consent_id', 'consent', 'consents', 'id'],
  ['identity_evidence_records', 'created_by_user_id', 'iam', 'users', 'id'],
  ['identity_evidence_records', 'evidence_file_id', 'common', 'files', 'id'],
  ['identity_evidence_records', 'evidence_quality_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_evidence_records', 'evidence_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_evidence_records', 'identity_verification_case_id', 'identity_assurance', 'identity_verification_cases', 'id'],
  ['identity_evidence_records', 'issuer_authority_id', 'identity_assurance', 'identity_authorities', 'id'],
  ['identity_evidence_records', 'verification_status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_fraud_signals', 'identity_verification_case_id', 'identity_assurance', 'identity_verification_cases', 'id'],
  ['identity_fraud_signals', 'resolution_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_fraud_signals', 'severity_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_fraud_signals', 'signal_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_fraud_signals', 'source_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_manual_review_cases', 'assigned_to_user_id', 'iam', 'users', 'id'],
  ['identity_manual_review_cases', 'created_by_user_id', 'iam', 'users', 'id'],
  ['identity_manual_review_cases', 'decision_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_manual_review_cases', 'identity_verification_case_id', 'identity_assurance', 'identity_verification_cases', 'id'],
  ['identity_manual_review_cases', 'review_reason_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_manual_review_cases', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_manual_review_cases', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['identity_verification_attempts', 'identity_authority_endpoint_id', 'identity_assurance', 'identity_authority_endpoints', 'id'],
  ['identity_verification_attempts', 'identity_verification_case_id', 'identity_assurance', 'identity_verification_cases', 'id'],
  ['identity_verification_attempts', 'outcome_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_verification_attempts', 'request_message_id', 'integrations', 'outbound_messages', 'id'],
  ['identity_verification_attempts', 'response_message_id', 'integrations', 'inbound_messages', 'id'],
  ['identity_verification_cases', 'created_by_user_id', 'iam', 'users', 'id'],
  ['identity_verification_cases', 'identity_verification_policy_id', 'identity_assurance', 'identity_verification_policies', 'id'],
  ['identity_verification_cases', 'requested_assurance_level_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_verification_cases', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_verification_cases', 'subject_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_verification_cases', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['identity_verification_policies', 'created_by_user_id', 'iam', 'users', 'id'],
  ['identity_verification_policies', 'required_authenticator_assurance_level_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_verification_policies', 'required_federation_assurance_level_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_verification_policies', 'required_identity_assurance_level_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_verification_policies', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_verification_policies', 'subject_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['identity_verification_policies', 'transaction_risk_concept_id', 'terminology', 'catalog_concepts', 'id'],
];
