import type { ForeignKeyTuple } from '../catalog.types';

/**
 * Claves foráneas declaradas por el modelo oficial para el schema `integrations`.
 * 49 restricciones. Generado desde las notas `FK/` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const integrationsForeignKeys: readonly ForeignKeyTuple[] = [
  // [tablaOrigen, columnaOrigen, schemaDestino, tablaDestino, columnaDestino]
  ['external_providers', 'auth_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['external_providers', 'created_by_user_id', 'iam', 'users', 'id'],
  ['external_providers', 'provider_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['external_providers', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['external_providers', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['inbound_messages', 'connection_id', 'integrations', 'provider_connections', 'id'],
  ['inbound_messages', 'created_by_user_id', 'iam', 'users', 'id'],
  ['inbound_messages', 'endpoint_id', 'integrations', 'integration_endpoints', 'id'],
  ['inbound_messages', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['inbound_messages', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['integration_endpoints', 'created_by_user_id', 'iam', 'users', 'id'],
  ['integration_endpoints', 'http_method_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['integration_endpoints', 'provider_id', 'integrations', 'external_providers', 'id'],
  ['integration_endpoints', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['integration_endpoints', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['integration_field_mappings', 'concept_map_id', 'terminology', 'concept_maps', 'id'],
  ['integration_field_mappings', 'created_by_user_id', 'iam', 'users', 'id'],
  ['integration_field_mappings', 'direction_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['integration_field_mappings', 'endpoint_id', 'integrations', 'integration_endpoints', 'id'],
  ['integration_field_mappings', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['message_responses', 'created_by_user_id', 'iam', 'users', 'id'],
  ['message_responses', 'outbound_message_id', 'integrations', 'outbound_messages', 'id'],
  ['message_responses', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['message_retries', 'created_by_user_id', 'iam', 'users', 'id'],
  ['message_retries', 'outbound_message_id', 'integrations', 'outbound_messages', 'id'],
  ['message_retries', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['message_retries', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['outbound_messages', 'connection_id', 'integrations', 'provider_connections', 'id'],
  ['outbound_messages', 'created_by_user_id', 'iam', 'users', 'id'],
  ['outbound_messages', 'endpoint_id', 'integrations', 'integration_endpoints', 'id'],
  ['outbound_messages', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['outbound_messages', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['provider_connections', 'created_by_user_id', 'iam', 'users', 'id'],
  ['provider_connections', 'credential_id', 'integrations', 'provider_credentials', 'id'],
  ['provider_connections', 'environment_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['provider_connections', 'provider_id', 'integrations', 'external_providers', 'id'],
  ['provider_connections', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['provider_connections', 'tenant_id', 'directory', 'tenants', 'id'],
  ['provider_connections', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['provider_credentials', 'connection_id', 'integrations', 'provider_connections', 'id'],
  ['provider_credentials', 'created_by_user_id', 'iam', 'users', 'id'],
  ['provider_credentials', 'secret_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['provider_credentials', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['provider_credentials', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['webhook_subscriptions', 'created_by_user_id', 'iam', 'users', 'id'],
  ['webhook_subscriptions', 'provider_id', 'integrations', 'external_providers', 'id'],
  ['webhook_subscriptions', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['webhook_subscriptions', 'tenant_id', 'directory', 'tenants', 'id'],
  ['webhook_subscriptions', 'updated_by_user_id', 'iam', 'users', 'id'],
];
