import type { ForeignKeyTuple } from '../catalog.types';

/**
 * Claves foráneas declaradas por el modelo oficial para el schema `organization_extensions`.
 * 49 restricciones. Generado desde las notas `FK/` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const organizationExtensionsForeignKeys: readonly ForeignKeyTuple[] = [
  // [tablaOrigen, columnaOrigen, schemaDestino, tablaDestino, columnaDestino]
  ['facility_licenses', 'created_by_user_id', 'iam', 'users', 'id'],
  ['facility_licenses', 'evidence_file_id', 'common', 'files', 'id'],
  ['facility_licenses', 'facility_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['facility_licenses', 'issuing_authority_tenant_id', 'directory', 'tenants', 'id'],
  ['facility_licenses', 'jurisdiction_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['facility_licenses', 'license_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['facility_licenses', 'practice_site_id', 'practice', 'practice_sites', 'id'],
  ['facility_licenses', 'tenant_id', 'directory', 'tenants', 'id'],
  ['facility_licenses', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['facility_licenses', 'verification_status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['hospitals', 'care_level_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['hospitals', 'created_by_user_id', 'iam', 'users', 'id'],
  ['hospitals', 'emergency_capability_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['hospitals', 'hospital_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['hospitals', 'ownership_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['hospitals', 'practice_id', 'practice', 'practices', 'id'],
  ['hospitals', 'primary_practice_site_id', 'practice', 'practice_sites', 'id'],
  ['hospitals', 'public_profile_id', 'community', 'public_profiles', 'id'],
  ['hospitals', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['hospitals', 'teaching_status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['hospitals', 'tenant_id', 'directory', 'tenants', 'id'],
  ['hospitals', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['hospital_service_lines', 'acuity_level_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['hospital_service_lines', 'clinical_unit_id', 'practice', 'clinical_units', 'id'],
  ['hospital_service_lines', 'created_by_user_id', 'iam', 'users', 'id'],
  ['hospital_service_lines', 'healthcare_service_id', 'practice', 'healthcare_services', 'id'],
  ['hospital_service_lines', 'hospital_id', 'organization_extensions', 'hospitals', 'id'],
  ['hospital_service_lines', 'service_line_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['hospital_service_lines', 'specialty_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['hospital_service_lines', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['hospital_service_lines', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['organization_affiliations', 'affiliation_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['organization_affiliations', 'created_by_user_id', 'iam', 'users', 'id'],
  ['organization_affiliations', 'healthcare_service_id', 'practice', 'healthcare_services', 'id'],
  ['organization_affiliations', 'host_practice_site_id', 'practice', 'practice_sites', 'id'],
  ['organization_affiliations', 'participating_tenant_id', 'directory', 'tenants', 'id'],
  ['organization_affiliations', 'primary_tenant_id', 'directory', 'tenants', 'id'],
  ['organization_affiliations', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['organization_affiliations', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['organization_data_boundaries', 'allowed_purpose_value_set_id', 'terminology', 'value_sets', 'id'],
  ['organization_data_boundaries', 'boundary_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['organization_data_boundaries', 'created_by_user_id', 'iam', 'users', 'id'],
  ['organization_data_boundaries', 'data_controller_tenant_id', 'directory', 'tenants', 'id'],
  ['organization_data_boundaries', 'data_processor_tenant_id', 'directory', 'tenants', 'id'],
  ['organization_data_boundaries', 'jurisdiction_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['organization_data_boundaries', 'residency_region_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['organization_data_boundaries', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['organization_data_boundaries', 'tenant_id', 'directory', 'tenants', 'id'],
  ['organization_data_boundaries', 'updated_by_user_id', 'iam', 'users', 'id'],
];
