import type { ForeignKeyTuple } from '../catalog.types';

/**
 * Claves foráneas declaradas por el modelo oficial para el schema `pharmacy`.
 * 63 restricciones. Generado desde las notas `FK/` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const pharmacyForeignKeys: readonly ForeignKeyTuple[] = [
  // [tablaOrigen, columnaOrigen, schemaDestino, tablaDestino, columnaDestino]
  ['pharmacies', 'created_by_user_id', 'iam', 'users', 'id'],
  ['pharmacies', 'default_currency_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['pharmacies', 'ownership_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['pharmacies', 'pharmacy_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['pharmacies', 'public_profile_id', 'community', 'public_profiles', 'id'],
  ['pharmacies', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['pharmacies', 'tenant_id', 'directory', 'tenants', 'id'],
  ['pharmacies', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['pharmacies', 'verification_status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['pharmacy_external_product_mappings', 'created_by_user_id', 'iam', 'users', 'id'],
  ['pharmacy_external_product_mappings', 'pharmacy_integration_connection_id', 'pharmacy', 'pharmacy_integration_connections', 'id'],
  ['pharmacy_external_product_mappings', 'pharmacy_product_id', 'pharmacy', 'pharmacy_products', 'id'],
  ['pharmacy_external_product_mappings', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['pharmacy_external_product_mappings', 'verification_status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['pharmacy_integration_connections', 'created_by_user_id', 'iam', 'users', 'id'],
  ['pharmacy_integration_connections', 'integration_mode_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['pharmacy_integration_connections', 'inventory_authority_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['pharmacy_integration_connections', 'pharmacy_id', 'pharmacy', 'pharmacies', 'id'],
  ['pharmacy_integration_connections', 'pharmacy_site_id', 'pharmacy', 'pharmacy_sites', 'id'],
  ['pharmacy_integration_connections', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['pharmacy_integration_connections', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['pharmacy_licenses', 'created_by_user_id', 'iam', 'users', 'id'],
  ['pharmacy_licenses', 'evidence_file_id', 'common', 'files', 'id'],
  ['pharmacy_licenses', 'issuing_authority_tenant_id', 'directory', 'tenants', 'id'],
  ['pharmacy_licenses', 'jurisdiction_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['pharmacy_licenses', 'license_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['pharmacy_licenses', 'pharmacy_id', 'pharmacy', 'pharmacies', 'id'],
  ['pharmacy_licenses', 'pharmacy_site_id', 'pharmacy', 'pharmacy_sites', 'id'],
  ['pharmacy_licenses', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['pharmacy_licenses', 'verification_status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['pharmacy_price_lists', 'created_by_user_id', 'iam', 'users', 'id'],
  ['pharmacy_price_lists', 'currency_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['pharmacy_price_lists', 'insurer_tenant_id', 'directory', 'tenants', 'id'],
  ['pharmacy_price_lists', 'pharmacy_id', 'pharmacy', 'pharmacies', 'id'],
  ['pharmacy_price_lists', 'pharmacy_site_id', 'pharmacy', 'pharmacy_sites', 'id'],
  ['pharmacy_price_lists', 'price_list_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['pharmacy_price_lists', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['pharmacy_price_lists', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['pharmacy_product_identifiers', 'assigning_authority_tenant_id', 'directory', 'tenants', 'id'],
  ['pharmacy_product_identifiers', 'created_by_user_id', 'iam', 'users', 'id'],
  ['pharmacy_product_identifiers', 'identifier_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['pharmacy_product_identifiers', 'jurisdiction_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['pharmacy_product_identifiers', 'pharmacy_product_id', 'pharmacy', 'pharmacy_products', 'id'],
  ['pharmacy_product_prices', 'pharmacy_price_list_id', 'pharmacy', 'pharmacy_price_lists', 'id'],
  ['pharmacy_product_prices', 'pharmacy_product_id', 'pharmacy', 'pharmacy_products', 'id'],
  ['pharmacy_product_prices', 'recorded_by_user_id', 'iam', 'users', 'id'],
  ['pharmacy_product_prices', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['pharmacy_products', 'created_by_user_id', 'iam', 'users', 'id'],
  ['pharmacy_products', 'dosage_form_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['pharmacy_products', 'inventory_item_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['pharmacy_products', 'manufacturer_tenant_id', 'directory', 'tenants', 'id'],
  ['pharmacy_products', 'medication_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['pharmacy_products', 'pharmacy_id', 'pharmacy', 'pharmacies', 'id'],
  ['pharmacy_products', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['pharmacy_products', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['pharmacy_sites', 'controlled_substance_capability_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['pharmacy_sites', 'created_by_user_id', 'iam', 'users', 'id'],
  ['pharmacy_sites', 'dispensing_mode_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['pharmacy_sites', 'pharmacy_id', 'pharmacy', 'pharmacies', 'id'],
  ['pharmacy_sites', 'pharmacy_site_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['pharmacy_sites', 'practice_site_id', 'practice', 'practice_sites', 'id'],
  ['pharmacy_sites', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['pharmacy_sites', 'updated_by_user_id', 'iam', 'users', 'id'],
];
