import type { ForeignKeyTuple } from '../catalog.types';

/**
 * Claves foráneas declaradas por el modelo oficial para el schema `practice`.
 * 80 restricciones. Generado desde las notas `FK/` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const practiceForeignKeys: readonly ForeignKeyTuple[] = [
  // [tablaOrigen, columnaOrigen, schemaDestino, tablaDestino, columnaDestino]
  ['care_spaces', 'clinical_unit_id', 'practice', 'clinical_units', 'id'],
  ['care_spaces', 'created_by_user_id', 'iam', 'users', 'id'],
  ['care_spaces', 'operational_status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['care_spaces', 'parent_space_id', 'practice', 'care_spaces', 'id'],
  ['care_spaces', 'practice_site_id', 'practice', 'practice_sites', 'id'],
  ['care_spaces', 'space_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['care_spaces', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['care_spaces', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['clinical_units', 'created_by_user_id', 'iam', 'users', 'id'],
  ['clinical_units', 'parent_unit_id', 'practice', 'clinical_units', 'id'],
  ['clinical_units', 'practice_site_id', 'practice', 'practice_sites', 'id'],
  ['clinical_units', 'service_mode_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['clinical_units', 'specialty_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['clinical_units', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['clinical_units', 'unit_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['clinical_units', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['healthcare_services', 'clinical_unit_id', 'practice', 'clinical_units', 'id'],
  ['healthcare_services', 'created_by_user_id', 'iam', 'users', 'id'],
  ['healthcare_services', 'practice_id', 'practice', 'practices', 'id'],
  ['healthcare_services', 'practice_site_id', 'practice', 'practice_sites', 'id'],
  ['healthcare_services', 'service_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['healthcare_services', 'specialty_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['healthcare_services', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['healthcare_services', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['inventory_items', 'created_by_user_id', 'iam', 'users', 'id'],
  ['inventory_items', 'practice_id', 'practice', 'practices', 'id'],
  ['inventory_items', 'product_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['inventory_items', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['inventory_items', 'unit_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['inventory_items', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['inventory_movements', 'inventory_item_id', 'practice', 'inventory_items', 'id'],
  ['inventory_movements', 'movement_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['inventory_movements', 'recorded_by_user_id', 'iam', 'users', 'id'],
  ['practice_accreditations', 'accreditation_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['practice_accreditations', 'created_by_user_id', 'iam', 'users', 'id'],
  ['practice_accreditations', 'evidence_file_id', 'common', 'files', 'id'],
  ['practice_accreditations', 'issuer_tenant_id', 'directory', 'tenants', 'id'],
  ['practice_accreditations', 'practice_id', 'practice', 'practices', 'id'],
  ['practice_accreditations', 'practice_site_id', 'practice', 'practice_sites', 'id'],
  ['practice_accreditations', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['practice_accreditations', 'verification_status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['practice_settings', 'category_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['practice_settings', 'created_by_user_id', 'iam', 'users', 'id'],
  ['practice_settings', 'practice_id', 'practice', 'practices', 'id'],
  ['practice_settings', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['practice_sites', 'address_id', 'common', 'addresses', 'id'],
  ['practice_sites', 'branch_id', 'directory', 'branches', 'id'],
  ['practice_sites', 'created_by_user_id', 'iam', 'users', 'id'],
  ['practice_sites', 'managing_tenant_id', 'directory', 'tenants', 'id'],
  ['practice_sites', 'operational_status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['practice_sites', 'physical_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['practice_sites', 'practice_id', 'practice', 'practices', 'id'],
  ['practice_sites', 'site_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['practice_sites', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['practice_sites', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['practices', 'admin_user_id', 'iam', 'users', 'id'],
  ['practices', 'created_by_user_id', 'iam', 'users', 'id'],
  ['practices', 'currency_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['practices', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['practices', 'tenant_id', 'directory', 'tenants', 'id'],
  ['practices', 'type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['practices', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['practitioner_role_assignments', 'clinical_unit_id', 'practice', 'clinical_units', 'id'],
  ['practitioner_role_assignments', 'created_by_user_id', 'iam', 'users', 'id'],
  ['practitioner_role_assignments', 'healthcare_service_id', 'practice', 'healthcare_services', 'id'],
  ['practitioner_role_assignments', 'practice_id', 'practice', 'practices', 'id'],
  ['practitioner_role_assignments', 'practice_site_id', 'practice', 'practice_sites', 'id'],
  ['practitioner_role_assignments', 'practitioner_profile_id', 'profiles', 'health_practitioner_profiles', 'profile_id'],
  ['practitioner_role_assignments', 'role_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['practitioner_role_assignments', 'specialty_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['practitioner_role_assignments', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['practitioner_role_assignments', 'supervisor_practitioner_profile_id', 'profiles', 'health_practitioner_profiles', 'profile_id'],
  ['practitioner_role_assignments', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['practitioner_support_assignments', 'created_by_user_id', 'iam', 'users', 'id'],
  ['practitioner_support_assignments', 'practitioner_role_assignment_id', 'practice', 'practitioner_role_assignments', 'id'],
  ['practitioner_support_assignments', 'scope_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['practitioner_support_assignments', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['practitioner_support_assignments', 'support_profile_id', 'profiles', 'secretary_profiles', 'profile_id'],
  ['practitioner_support_assignments', 'support_role_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['practitioner_support_assignments', 'updated_by_user_id', 'iam', 'users', 'id'],
];
