import type { ForeignKeyTuple } from '../catalog.types';

/**
 * Claves foráneas declaradas por el modelo oficial para el schema `promotions`.
 * 71 restricciones. Generado desde las notas `FK/` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const promotionsForeignKeys: readonly ForeignKeyTuple[] = [
  // [tablaOrigen, columnaOrigen, schemaDestino, tablaDestino, columnaDestino]
  ['coupons', 'assigned_member_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['coupons', 'coupon_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['coupons', 'created_by_user_id', 'iam', 'users', 'id'],
  ['coupons', 'promotion_id', 'promotions', 'promotions', 'id'],
  ['coupons', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['coupons', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['discount_rules', 'applies_to_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['discount_rules', 'created_by_user_id', 'iam', 'users', 'id'],
  ['discount_rules', 'currency_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['discount_rules', 'discount_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['discount_rules', 'promotion_id', 'promotions', 'promotions', 'id'],
  ['discount_rules', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['earning_rules', 'award_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['earning_rules', 'created_by_user_id', 'iam', 'users', 'id'],
  ['earning_rules', 'currency_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['earning_rules', 'event_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['earning_rules', 'loyalty_program_id', 'promotions', 'loyalty_programs', 'id'],
  ['earning_rules', 'period_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['earning_rules', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['loyalty_memberships', 'created_by_user_id', 'iam', 'users', 'id'],
  ['loyalty_memberships', 'current_tier_id', 'promotions', 'loyalty_tiers', 'id'],
  ['loyalty_memberships', 'loyalty_program_id', 'promotions', 'loyalty_programs', 'id'],
  ['loyalty_memberships', 'member_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['loyalty_memberships', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['loyalty_memberships', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['loyalty_programs', 'created_by_user_id', 'iam', 'users', 'id'],
  ['loyalty_programs', 'currency_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['loyalty_programs', 'expiry_policy_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['loyalty_programs', 'program_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['loyalty_programs', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['loyalty_programs', 'tenant_id', 'directory', 'tenants', 'id'],
  ['loyalty_programs', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['loyalty_tiers', 'created_by_user_id', 'iam', 'users', 'id'],
  ['loyalty_tiers', 'loyalty_program_id', 'promotions', 'loyalty_programs', 'id'],
  ['loyalty_tiers', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['member_referrals', 'created_by_user_id', 'iam', 'users', 'id'],
  ['member_referrals', 'referee_reward_ledger_id', 'promotions', 'loyalty_memberships', 'id'],
  ['member_referrals', 'referee_user_id', 'iam', 'users', 'id'],
  ['member_referrals', 'referral_program_id', 'promotions', 'referral_programs', 'id'],
  ['member_referrals', 'referrer_reward_ledger_id', 'promotions', 'loyalty_memberships', 'id'],
  ['member_referrals', 'referrer_user_id', 'iam', 'users', 'id'],
  ['member_referrals', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['member_referrals', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['points_ledger_entries', 'direction_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['points_ledger_entries', 'earning_rule_id', 'promotions', 'earning_rules', 'id'],
  ['points_ledger_entries', 'loyalty_membership_id', 'promotions', 'loyalty_memberships', 'id'],
  ['points_ledger_entries', 'reason_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['points_ledger_entries', 'recorded_by_user_id', 'iam', 'users', 'id'],
  ['promotions', 'created_by_user_id', 'iam', 'users', 'id'],
  ['promotions', 'currency_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['promotions', 'promotion_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['promotions', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['promotions', 'tenant_id', 'directory', 'tenants', 'id'],
  ['promotions', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['redemptions', 'coupon_id', 'promotions', 'coupons', 'id'],
  ['redemptions', 'created_by_user_id', 'iam', 'users', 'id'],
  ['redemptions', 'currency_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['redemptions', 'discount_rule_id', 'promotions', 'discount_rules', 'id'],
  ['redemptions', 'payment_intent_id', 'payments', 'payment_intents', 'id'],
  ['redemptions', 'promotion_id', 'promotions', 'promotions', 'id'],
  ['redemptions', 'redeemer_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['redemptions', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['redemptions', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['referral_programs', 'created_by_user_id', 'iam', 'users', 'id'],
  ['referral_programs', 'currency_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['referral_programs', 'qualifying_event_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['referral_programs', 'referee_award_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['referral_programs', 'referrer_award_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['referral_programs', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['referral_programs', 'tenant_id', 'directory', 'tenants', 'id'],
  ['referral_programs', 'updated_by_user_id', 'iam', 'users', 'id'],
];
