import type { ForeignKeyTuple } from '../catalog.types';

/**
 * Claves foráneas declaradas por el modelo oficial para el schema `qa_lab`.
 * 71 restricciones. Generado desde las notas `FK/` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const qaLabForeignKeys: readonly ForeignKeyTuple[] = [
  // [tablaOrigen, columnaOrigen, schemaDestino, tablaDestino, columnaDestino]
  ['assertion_results', 'recorded_by_user_id', 'iam', 'users', 'id'],
  ['assertion_results', 'test_assertion_id', 'qa_lab', 'test_assertions', 'id'],
  ['assertion_results', 'test_case_result_id', 'qa_lab', 'test_case_results', 'id'],
  ['request_payloads', 'direction_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['request_payloads', 'http_method_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['request_payloads', 'recorded_by_user_id', 'iam', 'users', 'id'],
  ['request_payloads', 'test_case_result_id', 'qa_lab', 'test_case_results', 'id'],
  ['response_payloads', 'recorded_by_user_id', 'iam', 'users', 'id'],
  ['response_payloads', 'request_payload_id', 'qa_lab', 'request_payloads', 'id'],
  ['response_payloads', 'test_case_result_id', 'qa_lab', 'test_case_results', 'id'],
  ['run_artifacts', 'artifact_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['run_artifacts', 'created_by_user_id', 'iam', 'users', 'id'],
  ['run_artifacts', 'file_id', 'common', 'files', 'id'],
  ['run_artifacts', 'test_case_result_id', 'qa_lab', 'test_case_results', 'id'],
  ['run_artifacts', 'test_run_id', 'qa_lab', 'test_runs', 'id'],
  ['run_artifacts', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['test_assertions', 'assertion_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['test_assertions', 'created_by_user_id', 'iam', 'users', 'id'],
  ['test_assertions', 'operator_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['test_assertions', 'test_case_id', 'qa_lab', 'test_cases', 'id'],
  ['test_assertions', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['test_case_results', 'created_by_user_id', 'iam', 'users', 'id'],
  ['test_case_results', 'error_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['test_case_results', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['test_case_results', 'test_case_id', 'qa_lab', 'test_cases', 'id'],
  ['test_case_results', 'test_run_id', 'qa_lab', 'test_runs', 'id'],
  ['test_case_results', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['test_cases', 'case_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['test_cases', 'created_by_user_id', 'iam', 'users', 'id'],
  ['test_cases', 'http_method_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['test_cases', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['test_cases', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['test_defects', 'assigned_to_user_id', 'iam', 'users', 'id'],
  ['test_defects', 'created_by_user_id', 'iam', 'users', 'id'],
  ['test_defects', 'defect_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['test_defects', 'severity_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['test_defects', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['test_defects', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['test_defects', 'tenant_id', 'directory', 'tenants', 'id'],
  ['test_defects', 'test_case_id', 'qa_lab', 'test_cases', 'id'],
  ['test_defects', 'test_case_result_id', 'qa_lab', 'test_case_results', 'id'],
  ['test_defects', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['test_environments', 'created_by_user_id', 'iam', 'users', 'id'],
  ['test_environments', 'environment_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['test_environments', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['test_environments', 'tenant_id', 'directory', 'tenants', 'id'],
  ['test_environments', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['test_fixtures', 'created_by_user_id', 'iam', 'users', 'id'],
  ['test_fixtures', 'file_id', 'common', 'files', 'id'],
  ['test_fixtures', 'fixture_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['test_fixtures', 'test_case_id', 'qa_lab', 'test_cases', 'id'],
  ['test_fixtures', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['test_runs', 'created_by_user_id', 'iam', 'users', 'id'],
  ['test_runs', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['test_runs', 'tenant_id', 'directory', 'tenants', 'id'],
  ['test_runs', 'trigger_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['test_runs', 'triggered_by_user_id', 'iam', 'users', 'id'],
  ['test_runs', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['test_schedules', 'concurrency_policy_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['test_schedules', 'created_by_user_id', 'iam', 'users', 'id'],
  ['test_schedules', 'notify_channel_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['test_schedules', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['test_schedules', 'tenant_id', 'directory', 'tenants', 'id'],
  ['test_schedules', 'trigger_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['test_schedules', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['test_suites', 'created_by_user_id', 'iam', 'users', 'id'],
  ['test_suites', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['test_suites', 'suite_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['test_suites', 'target_system_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['test_suites', 'tenant_id', 'directory', 'tenants', 'id'],
  ['test_suites', 'updated_by_user_id', 'iam', 'users', 'id'],
];
