import type { ForeignKeyTuple } from '../catalog.types';

/**
 * Claves foráneas declaradas por el modelo oficial para el schema `read_models`.
 * 74 restricciones. Generado desde las notas `FK/` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const readModelsForeignKeys: readonly ForeignKeyTuple[] = [
  // [tablaOrigen, columnaOrigen, schemaDestino, tablaDestino, columnaDestino]
  ['frontend_page_views', 'created_by_user_id', 'iam', 'users', 'id'],
  ['frontend_page_views', 'frontend_route_id', 'read_models', 'frontend_routes', 'id'],
  ['frontend_page_views', 'read_model_definition_id', 'read_models', 'read_model_definitions', 'id'],
  ['frontend_page_views', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['frontend_page_views', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['frontend_page_views', 'view_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['frontend_routes', 'cache_policy_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['frontend_routes', 'created_by_user_id', 'iam', 'users', 'id'],
  ['frontend_routes', 'portal_surface_id', 'read_models', 'portal_surfaces', 'id'],
  ['frontend_routes', 'purpose_of_use_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['frontend_routes', 'required_permission_id', 'authz', 'permissions', 'id'],
  ['frontend_routes', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['frontend_routes', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['frontend_view_actions', 'action_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['frontend_view_actions', 'allowed_state_value_set_id', 'terminology', 'value_sets', 'id'],
  ['frontend_view_actions', 'confirmation_policy_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['frontend_view_actions', 'created_by_user_id', 'iam', 'users', 'id'],
  ['frontend_view_actions', 'frontend_page_view_id', 'read_models', 'frontend_page_views', 'id'],
  ['frontend_view_actions', 'prominence_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['frontend_view_actions', 'required_permission_id', 'authz', 'permissions', 'id'],
  ['frontend_view_actions', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['frontend_view_actions', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['frontend_view_fields', 'created_by_user_id', 'iam', 'users', 'id'],
  ['frontend_view_fields', 'display_component_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['frontend_view_fields', 'frontend_page_view_id', 'read_models', 'frontend_page_views', 'id'],
  ['frontend_view_fields', 'permission_id', 'authz', 'permissions', 'id'],
  ['frontend_view_fields', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['frontend_view_fields', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['frontend_view_filters', 'created_by_user_id', 'iam', 'users', 'id'],
  ['frontend_view_filters', 'dynamic_enum_definition_id', 'system_context', 'dynamic_enum_definitions', 'id'],
  ['frontend_view_filters', 'frontend_page_view_id', 'read_models', 'frontend_page_views', 'id'],
  ['frontend_view_filters', 'input_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['frontend_view_filters', 'operator_value_set_id', 'terminology', 'value_sets', 'id'],
  ['frontend_view_filters', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['frontend_view_filters', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['frontend_view_filters', 'value_set_id', 'terminology', 'value_sets', 'id'],
  ['frontend_view_kpis', 'created_by_user_id', 'iam', 'users', 'id'],
  ['frontend_view_kpis', 'frontend_page_view_id', 'read_models', 'frontend_page_views', 'id'],
  ['frontend_view_kpis', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['frontend_view_kpis', 'unit_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['frontend_view_kpis', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['frontend_view_sort_options', 'created_by_user_id', 'iam', 'users', 'id'],
  ['frontend_view_sort_options', 'direction_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['frontend_view_sort_options', 'frontend_page_view_id', 'read_models', 'frontend_page_views', 'id'],
  ['frontend_view_sort_options', 'nulls_position_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['frontend_view_sort_options', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['frontend_view_sort_options', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['frontend_view_states', 'created_by_user_id', 'iam', 'users', 'id'],
  ['frontend_view_states', 'frontend_page_view_id', 'read_models', 'frontend_page_views', 'id'],
  ['frontend_view_states', 'state_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['frontend_view_states', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['frontend_view_states', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['portal_surfaces', 'audience_role_value_set_id', 'terminology', 'value_sets', 'id'],
  ['portal_surfaces', 'created_by_user_id', 'iam', 'users', 'id'],
  ['portal_surfaces', 'portal_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['portal_surfaces', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['portal_surfaces', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['read_model_definitions', 'created_by_user_id', 'iam', 'users', 'id'],
  ['read_model_definitions', 'object_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['read_model_definitions', 'refresh_mode_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['read_model_definitions', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['read_model_definitions', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['read_model_dependencies', 'dependency_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['read_model_dependencies', 'read_model_definition_id', 'read_models', 'read_model_definitions', 'id'],
  ['read_model_refresh_runs', 'read_model_definition_id', 'read_models', 'read_model_definitions', 'id'],
  ['read_model_refresh_runs', 'refresh_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['read_model_refresh_runs', 'result_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['user_view_preferences', 'created_by_user_id', 'iam', 'users', 'id'],
  ['user_view_preferences', 'density_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['user_view_preferences', 'frontend_page_view_id', 'read_models', 'frontend_page_views', 'id'],
  ['user_view_preferences', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['user_view_preferences', 'tenant_id', 'directory', 'tenants', 'id'],
  ['user_view_preferences', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['user_view_preferences', 'user_id', 'iam', 'users', 'id'],
];
