import type { ForeignKeyTuple } from '../catalog.types';

/**
 * Claves foráneas declaradas por el modelo oficial para el schema `reporting`.
 * 70 restricciones. Generado desde las notas `FK/` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const reportingForeignKeys: readonly ForeignKeyTuple[] = [
  // [tablaOrigen, columnaOrigen, schemaDestino, tablaDestino, columnaDestino]
  ['dashboard_widgets', 'created_by_user_id', 'iam', 'users', 'id'],
  ['dashboard_widgets', 'dashboard_id', 'reporting', 'dashboards', 'id'],
  ['dashboard_widgets', 'report_definition_id', 'reporting', 'report_definitions', 'id'],
  ['dashboard_widgets', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['dashboard_widgets', 'visualization_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['dashboard_widgets', 'widget_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['dashboards', 'created_by_user_id', 'iam', 'users', 'id'],
  ['dashboards', 'required_permission_id', 'authz', 'permissions', 'id'],
  ['dashboards', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['dashboards', 'tenant_id', 'directory', 'tenants', 'id'],
  ['dashboards', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['report_columns', 'aggregation_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['report_columns', 'created_by_user_id', 'iam', 'users', 'id'],
  ['report_columns', 'report_definition_id', 'reporting', 'report_definitions', 'id'],
  ['report_columns', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['report_data_sources', 'created_by_user_id', 'iam', 'users', 'id'],
  ['report_data_sources', 'read_model_definition_id', 'read_models', 'read_model_definitions', 'id'],
  ['report_data_sources', 'source_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['report_data_sources', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['report_data_sources', 'tenant_id', 'directory', 'tenants', 'id'],
  ['report_data_sources', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['report_definitions', 'category_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['report_definitions', 'created_by_user_id', 'iam', 'users', 'id'],
  ['report_definitions', 'data_source_id', 'reporting', 'report_data_sources', 'id'],
  ['report_definitions', 'default_output_format_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['report_definitions', 'required_permission_id', 'authz', 'permissions', 'id'],
  ['report_definitions', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['report_definitions', 'tenant_id', 'directory', 'tenants', 'id'],
  ['report_definitions', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['report_distributions', 'channel_id', 'messaging', 'message_channels', 'id'],
  ['report_distributions', 'created_by_user_id', 'iam', 'users', 'id'],
  ['report_distributions', 'recipient_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['report_distributions', 'recipient_user_id', 'iam', 'users', 'id'],
  ['report_distributions', 'report_execution_id', 'reporting', 'report_executions', 'id'],
  ['report_distributions', 'schedule_id', 'reporting', 'report_schedules', 'id'],
  ['report_distributions', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['report_distributions', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['report_executions', 'created_by_user_id', 'iam', 'users', 'id'],
  ['report_executions', 'output_file_id', 'common', 'files', 'id'],
  ['report_executions', 'output_format_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['report_executions', 'report_definition_id', 'reporting', 'report_definitions', 'id'],
  ['report_executions', 'report_version_id', 'reporting', 'report_versions', 'id'],
  ['report_executions', 'requested_by_user_id', 'iam', 'users', 'id'],
  ['report_executions', 'schedule_id', 'reporting', 'report_schedules', 'id'],
  ['report_executions', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['report_executions', 'tenant_id', 'directory', 'tenants', 'id'],
  ['report_executions', 'trigger_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['report_executions', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['report_parameters', 'created_by_user_id', 'iam', 'users', 'id'],
  ['report_parameters', 'report_definition_id', 'reporting', 'report_definitions', 'id'],
  ['report_parameters', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['report_parameters', 'value_set_id', 'terminology', 'value_sets', 'id'],
  ['report_schedules', 'created_by_user_id', 'iam', 'users', 'id'],
  ['report_schedules', 'output_format_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['report_schedules', 'report_definition_id', 'reporting', 'report_definitions', 'id'],
  ['report_schedules', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['report_schedules', 'tenant_id', 'directory', 'tenants', 'id'],
  ['report_schedules', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['report_snapshots', 'created_by_user_id', 'iam', 'users', 'id'],
  ['report_snapshots', 'report_execution_id', 'reporting', 'report_executions', 'id'],
  ['report_snapshots', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['report_subscriptions', 'channel_id', 'messaging', 'message_channels', 'id'],
  ['report_subscriptions', 'created_by_user_id', 'iam', 'users', 'id'],
  ['report_subscriptions', 'report_schedule_id', 'reporting', 'report_schedules', 'id'],
  ['report_subscriptions', 'subscriber_user_id', 'iam', 'users', 'id'],
  ['report_subscriptions', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['report_versions', 'created_by_user_id', 'iam', 'users', 'id'],
  ['report_versions', 'report_definition_id', 'reporting', 'report_definitions', 'id'],
  ['report_versions', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['report_versions', 'updated_by_user_id', 'iam', 'users', 'id'],
];
