import type { ForeignKeyTuple } from '../catalog.types';

/**
 * Claves foráneas declaradas por el modelo oficial para el schema `scheduling`.
 * 77 restricciones. Generado desde las notas `FK/` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const schedulingForeignKeys: readonly ForeignKeyTuple[] = [
  // [tablaOrigen, columnaOrigen, schemaDestino, tablaDestino, columnaDestino]
  ['appointment_bookings', 'appointment_id', 'clinical', 'appointments', 'id'],
  ['appointment_bookings', 'bookable_slot_id', 'scheduling', 'bookable_slots', 'id'],
  ['appointment_bookings', 'booked_by_user_id', 'iam', 'users', 'id'],
  ['appointment_bookings', 'booking_channel_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['appointment_bookings', 'booking_policy_id', 'scheduling', 'booking_policies', 'id'],
  ['appointment_bookings', 'created_by_user_id', 'iam', 'users', 'id'],
  ['appointment_bookings', 'patient_profile_id', 'profiles', 'patient_profiles', 'profile_id'],
  ['appointment_bookings', 'service_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['appointment_bookings', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['appointment_bookings', 'tenant_id', 'directory', 'tenants', 'id'],
  ['appointment_bookings', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['appointment_reminders', 'channel_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['appointment_reminders', 'created_by_user_id', 'iam', 'users', 'id'],
  ['appointment_reminders', 'notification_request_id', 'messaging', 'notification_requests', 'id'],
  ['appointment_reminders', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['appointment_reminders', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['availability_exceptions', 'created_by_user_id', 'iam', 'users', 'id'],
  ['availability_exceptions', 'exception_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['availability_exceptions', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['availability_slots', 'appointment_id', 'clinical', 'appointments', 'id'],
  ['availability_slots', 'care_space_id', 'practice', 'care_spaces', 'id'],
  ['availability_slots', 'created_by_user_id', 'iam', 'users', 'id'],
  ['availability_slots', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['availability_slots', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['bookable_slots', 'created_by_user_id', 'iam', 'users', 'id'],
  ['bookable_slots', 'schedule_template_id', 'scheduling', 'schedule_templates', 'id'],
  ['bookable_slots', 'service_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['bookable_slots', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['bookable_slots', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['booking_cancellations', 'cancelled_by_user_id', 'iam', 'users', 'id'],
  ['booking_cancellations', 'created_by_user_id', 'iam', 'users', 'id'],
  ['booking_cancellations', 'currency_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['booking_cancellations', 'fee_payment_intent_id', 'payments', 'payment_intents', 'id'],
  ['booking_cancellations', 'reason_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['booking_cancellations', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['booking_cancellations', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['booking_policies', 'created_by_user_id', 'iam', 'users', 'id'],
  ['booking_policies', 'currency_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['booking_policies', 'practice_id', 'practice', 'practices', 'id'],
  ['booking_policies', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['booking_policies', 'tenant_id', 'directory', 'tenants', 'id'],
  ['booking_policies', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['booking_reschedules', 'reason_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['booking_reschedules', 'recorded_by_user_id', 'iam', 'users', 'id'],
  ['booking_reschedules', 'rescheduled_by_user_id', 'iam', 'users', 'id'],
  ['practitioner_schedules', 'care_space_id', 'practice', 'care_spaces', 'id'],
  ['practitioner_schedules', 'created_by_user_id', 'iam', 'users', 'id'],
  ['practitioner_schedules', 'practice_id', 'practice', 'practices', 'id'],
  ['practitioner_schedules', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['practitioner_schedules', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['schedulable_resources', 'created_by_user_id', 'iam', 'users', 'id'],
  ['schedulable_resources', 'practice_id', 'practice', 'practices', 'id'],
  ['schedulable_resources', 'resource_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['schedulable_resources', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['schedulable_resources', 'tenant_id', 'directory', 'tenants', 'id'],
  ['schedulable_resources', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['schedule_rules', 'created_by_user_id', 'iam', 'users', 'id'],
  ['schedule_rules', 'schedule_template_id', 'scheduling', 'schedule_templates', 'id'],
  ['schedule_rules', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['schedule_templates', 'booking_policy_id', 'scheduling', 'booking_policies', 'id'],
  ['schedule_templates', 'created_by_user_id', 'iam', 'users', 'id'],
  ['schedule_templates', 'practitioner_schedule_id', 'scheduling', 'practitioner_schedules', 'id'],
  ['schedule_templates', 'service_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['schedule_templates', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['schedule_templates', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['slot_holds', 'bookable_slot_id', 'scheduling', 'bookable_slots', 'id'],
  ['slot_holds', 'created_by_user_id', 'iam', 'users', 'id'],
  ['slot_holds', 'held_by_user_id', 'iam', 'users', 'id'],
  ['slot_holds', 'patient_profile_id', 'profiles', 'patient_profiles', 'profile_id'],
  ['slot_holds', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['slot_holds', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['waitlist_entries', 'created_by_user_id', 'iam', 'users', 'id'],
  ['waitlist_entries', 'patient_profile_id', 'profiles', 'patient_profiles', 'profile_id'],
  ['waitlist_entries', 'service_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['waitlist_entries', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['waitlist_entries', 'tenant_id', 'directory', 'tenants', 'id'],
  ['waitlist_entries', 'updated_by_user_id', 'iam', 'users', 'id'],
];
