import type { ForeignKeyTuple } from '../catalog.types';

/**
 * Claves foráneas declaradas por el modelo oficial para el schema `system_context`.
 * 51 restricciones. Generado desde las notas `FK/` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const systemContextForeignKeys: readonly ForeignKeyTuple[] = [
  // [tablaOrigen, columnaOrigen, schemaDestino, tablaDestino, columnaDestino]
  ['dynamic_enum_bindings', 'created_by_user_id', 'iam', 'users', 'id'],
  ['dynamic_enum_bindings', 'dynamic_enum_definition_id', 'system_context', 'dynamic_enum_definitions', 'id'],
  ['dynamic_enum_bindings', 'fallback_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['dynamic_enum_bindings', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['dynamic_enum_bindings', 'system_context_id', 'system_context', 'system_contexts', 'id'],
  ['dynamic_enum_bindings', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['dynamic_enum_bindings', 'validation_mode_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['dynamic_enum_definitions', 'country_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['dynamic_enum_definitions', 'created_by_user_id', 'iam', 'users', 'id'],
  ['dynamic_enum_definitions', 'scope_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['dynamic_enum_definitions', 'selection_mode_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['dynamic_enum_definitions', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['dynamic_enum_definitions', 'tenant_id', 'directory', 'tenants', 'id'],
  ['dynamic_enum_definitions', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['dynamic_enum_definitions', 'value_set_id', 'terminology', 'value_sets', 'id'],
  ['dynamic_enum_options', 'concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['dynamic_enum_options', 'dynamic_enum_version_id', 'system_context', 'dynamic_enum_versions', 'id'],
  ['dynamic_enum_options', 'recorded_by_user_id', 'iam', 'users', 'id'],
  ['dynamic_enum_versions', 'dynamic_enum_definition_id', 'system_context', 'dynamic_enum_definitions', 'id'],
  ['dynamic_enum_versions', 'recorded_by_user_id', 'iam', 'users', 'id'],
  ['dynamic_enum_versions', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['dynamic_enum_versions', 'value_set_version_id', 'terminology', 'value_set_versions', 'id'],
  ['system_context_bindings', 'consumer_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['system_context_bindings', 'country_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['system_context_bindings', 'created_by_user_id', 'iam', 'users', 'id'],
  ['system_context_bindings', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['system_context_bindings', 'system_context_id', 'system_context', 'system_contexts', 'id'],
  ['system_context_bindings', 'tenant_id', 'directory', 'tenants', 'id'],
  ['system_context_bindings', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['system_context_inputs', 'recorded_by_user_id', 'iam', 'users', 'id'],
  ['system_context_inputs', 'source_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['system_context_inputs', 'system_context_version_id', 'system_context', 'system_context_versions', 'id'],
  ['system_context_refresh_runs', 'recorded_by_user_id', 'iam', 'users', 'id'],
  ['system_context_refresh_runs', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['system_context_refresh_runs', 'system_context_id', 'system_context', 'system_contexts', 'id'],
  ['system_context_refresh_runs', 'trigger_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['system_context_versions', 'generated_by_agent_id', 'automation', 'agents', 'id'],
  ['system_context_versions', 'recorded_by_user_id', 'iam', 'users', 'id'],
  ['system_context_versions', 'refresh_run_id', 'system_context', 'system_context_refresh_runs', 'id'],
  ['system_context_versions', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['system_context_versions', 'system_context_id', 'system_context', 'system_contexts', 'id'],
  ['system_contexts', 'context_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['system_contexts', 'country_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['system_contexts', 'created_by_user_id', 'iam', 'users', 'id'],
  ['system_contexts', 'current_version_id', 'system_context', 'system_context_versions', 'id'],
  ['system_contexts', 'locale_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['system_contexts', 'refresh_policy_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['system_contexts', 'scope_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['system_contexts', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['system_contexts', 'tenant_id', 'directory', 'tenants', 'id'],
  ['system_contexts', 'updated_by_user_id', 'iam', 'users', 'id'],
];
