import type { ForeignKeyTuple } from '../catalog.types';

/**
 * Claves foráneas declaradas por el modelo oficial para el schema `terminology`.
 * 69 restricciones. Generado desde las notas `FK/` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const terminologyForeignKeys: readonly ForeignKeyTuple[] = [
  // [tablaOrigen, columnaOrigen, schemaDestino, tablaDestino, columnaDestino]
  ['catalog_concepts', 'code_system_version_id', 'terminology', 'code_system_versions', 'id'],
  ['catalog_concepts', 'created_by_user_id', 'iam', 'users', 'id'],
  ['catalog_concepts', 'replaced_by_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['catalog_concepts', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['catalog_concepts', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['catalog_import_batches', 'code_system_version_id', 'terminology', 'code_system_versions', 'id'],
  ['catalog_import_batches', 'file_id', 'common', 'files', 'id'],
  ['catalog_import_batches', 'recorded_by_user_id', 'iam', 'users', 'id'],
  ['catalog_import_batches', 'source_id', 'terminology', 'terminology_sources', 'id'],
  ['catalog_import_batches', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['code_systems', 'content_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['code_systems', 'created_by_user_id', 'iam', 'users', 'id'],
  ['code_systems', 'source_id', 'terminology', 'terminology_sources', 'id'],
  ['code_systems', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['code_systems', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['code_system_versions', 'code_system_id', 'terminology', 'code_systems', 'id'],
  ['code_system_versions', 'created_by_user_id', 'iam', 'users', 'id'],
  ['code_system_versions', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['code_system_versions', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['concept_designations', 'concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['concept_designations', 'created_by_user_id', 'iam', 'users', 'id'],
  ['concept_designations', 'designation_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['concept_designations', 'language_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['concept_designations', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['concept_maps', 'created_by_user_id', 'iam', 'users', 'id'],
  ['concept_maps', 'equivalence_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['concept_maps', 'source_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['concept_maps', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['concept_maps', 'target_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['concept_maps', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['concept_properties', 'concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['concept_properties', 'created_by_user_id', 'iam', 'users', 'id'],
  ['concept_properties', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['concept_relationships', 'created_by_user_id', 'iam', 'users', 'id'],
  ['concept_relationships', 'relationship_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['concept_relationships', 'source_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['concept_relationships', 'target_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['concept_relationships', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['tenant_catalog_policies', 'created_by_user_id', 'iam', 'users', 'id'],
  ['tenant_catalog_policies', 'mode_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['tenant_catalog_policies', 'tenant_id', 'directory', 'tenants', 'id'],
  ['tenant_catalog_policies', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['tenant_catalog_policies', 'value_set_id', 'terminology', 'value_sets', 'id'],
  ['tenant_concept_config', 'concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['tenant_concept_config', 'created_by_user_id', 'iam', 'users', 'id'],
  ['tenant_concept_config', 'tenant_id', 'directory', 'tenants', 'id'],
  ['tenant_concept_config', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['terminology_sources', 'created_by_user_id', 'iam', 'users', 'id'],
  ['terminology_sources', 'jurisdiction_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['terminology_sources', 'source_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['terminology_sources', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['terminology_sources', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['value_sets', 'created_by_user_id', 'iam', 'users', 'id'],
  ['value_sets', 'jurisdiction_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['value_sets', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['value_sets', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['value_set_members', 'concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['value_set_members', 'created_by_user_id', 'iam', 'users', 'id'],
  ['value_set_members', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['value_set_members', 'value_set_version_id', 'terminology', 'value_set_versions', 'id'],
  ['value_set_rules', 'code_system_id', 'terminology', 'code_systems', 'id'],
  ['value_set_rules', 'created_by_user_id', 'iam', 'users', 'id'],
  ['value_set_rules', 'operator_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['value_set_rules', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['value_set_rules', 'value_set_version_id', 'terminology', 'value_set_versions', 'id'],
  ['value_set_versions', 'created_by_user_id', 'iam', 'users', 'id'],
  ['value_set_versions', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['value_set_versions', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['value_set_versions', 'value_set_id', 'terminology', 'value_sets', 'id'],
];
