import type { ForeignKeyTuple } from '../catalog.types';

/**
 * Claves foráneas declaradas por el modelo oficial para el schema `tracking`.
 * 51 restricciones. Generado desde las notas `FK/` de la bóveda SALUD;
 * no editar a mano: regenerar con `yarn orm:catalog`.
 */
export const trackingForeignKeys: readonly ForeignKeyTuple[] = [
  // [tablaOrigen, columnaOrigen, schemaDestino, tablaDestino, columnaDestino]
  ['delivery_proofs', 'created_by_user_id', 'iam', 'users', 'id'],
  ['delivery_proofs', 'photo_file_id', 'common', 'files', 'id'],
  ['delivery_proofs', 'proof_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['delivery_proofs', 'shipment_id', 'tracking', 'shipments', 'id'],
  ['delivery_proofs', 'signature_file_id', 'common', 'files', 'id'],
  ['delivery_proofs', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['delivery_proofs', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['eta_estimates', 'method_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['eta_estimates', 'recorded_by_user_id', 'iam', 'users', 'id'],
  ['eta_estimates', 'shipment_id', 'tracking', 'shipments', 'id'],
  ['eta_estimates', 'trackable_subject_id', 'tracking', 'trackable_subjects', 'id'],
  ['milestone_definitions', 'created_by_user_id', 'iam', 'users', 'id'],
  ['milestone_definitions', 'milestone_status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['milestone_definitions', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['milestone_definitions', 'subject_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['milestone_definitions', 'tenant_id', 'directory', 'tenants', 'id'],
  ['milestone_definitions', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['shipment_handoffs', 'handoff_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['shipment_handoffs', 'recorded_by_user_id', 'iam', 'users', 'id'],
  ['shipment_handoffs', 'shipment_id', 'tracking', 'shipments', 'id'],
  ['shipments', 'assigned_courier_user_id', 'iam', 'users', 'id'],
  ['shipments', 'carrier_id', 'tracking', 'tracking_carriers', 'id'],
  ['shipments', 'created_by_user_id', 'iam', 'users', 'id'],
  ['shipments', 'destination_address_id', 'common', 'addresses', 'id'],
  ['shipments', 'origin_address_id', 'common', 'addresses', 'id'],
  ['shipments', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['shipments', 'tenant_id', 'directory', 'tenants', 'id'],
  ['shipments', 'trackable_subject_id', 'tracking', 'trackable_subjects', 'id'],
  ['shipments', 'tracked_subject_id', 'geo', 'tracked_subjects', 'id'],
  ['shipments', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['trackable_subjects', 'created_by_user_id', 'iam', 'users', 'id'],
  ['trackable_subjects', 'current_milestone_id', 'tracking', 'milestone_definitions', 'id'],
  ['trackable_subjects', 'current_status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['trackable_subjects', 'priority_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['trackable_subjects', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['trackable_subjects', 'subject_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['trackable_subjects', 'tenant_id', 'directory', 'tenants', 'id'],
  ['trackable_subjects', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['tracking_carriers', 'carrier_type_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['tracking_carriers', 'created_by_user_id', 'iam', 'users', 'id'],
  ['tracking_carriers', 'external_provider_id', 'integrations', 'external_providers', 'id'],
  ['tracking_carriers', 'state_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['tracking_carriers', 'tenant_id', 'directory', 'tenants', 'id'],
  ['tracking_carriers', 'updated_by_user_id', 'iam', 'users', 'id'],
  ['tracking_events', 'actor_user_id', 'iam', 'users', 'id'],
  ['tracking_events', 'location_ping_id', 'geo', 'location_pings', 'id'],
  ['tracking_events', 'milestone_definition_id', 'tracking', 'milestone_definitions', 'id'],
  ['tracking_events', 'recorded_by_user_id', 'iam', 'users', 'id'],
  ['tracking_events', 'source_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['tracking_events', 'status_concept_id', 'terminology', 'catalog_concepts', 'id'],
  ['tracking_events', 'trackable_subject_id', 'tracking', 'trackable_subjects', 'id'],
];
