/**
 * Catálogo de sub-códigos de negocio estables para `platform_ops`.
 *
 * `code` (en `DomainException`) dice el tipo HTTP del error; `reason` dice
 * cuál error concreto de ese tipo fue, dentro de este módulo. Un cliente
 * puede ramificar sobre `reason` sin parsear `message`.
 */
export enum PlatformOpsErrorReason {
  // --- Fiabilidad: SLO, error budget, capacidad (ops-reliability.service.ts) ---
  SLO_MEASUREMENT_WINDOW_INVERTED = 'SLO_MEASUREMENT_WINDOW_INVERTED',
  SLO_MEASUREMENT_WINDOW_EMPTY = 'SLO_MEASUREMENT_WINDOW_EMPTY',
  SLO_GOOD_EVENTS_EXCEED_TOTAL = 'SLO_GOOD_EVENTS_EXCEED_TOTAL',
  SLO_NOT_FOUND = 'SLO_NOT_FOUND',
  SLO_NOT_ACTIVE = 'SLO_NOT_ACTIVE',
  SLO_MEASUREMENT_BEFORE_EFFECTIVE = 'SLO_MEASUREMENT_BEFORE_EFFECTIVE',
  SLO_MEASUREMENT_AFTER_EFFECTIVE = 'SLO_MEASUREMENT_AFTER_EFFECTIVE',
  ERROR_BUDGET_POLICY_NOT_FOUND = 'ERROR_BUDGET_POLICY_NOT_FOUND',
  ERROR_BUDGET_POLICY_NOT_ACTIVE = 'ERROR_BUDGET_POLICY_NOT_ACTIVE',
  ERROR_BUDGET_NO_MEASUREMENT = 'ERROR_BUDGET_NO_MEASUREMENT',
  ERROR_BUDGET_BURN_RATE_BELOW_WARNING = 'ERROR_BUDGET_BURN_RATE_BELOW_WARNING',
  CAPACITY_VALUE_NOT_POSITIVE = 'CAPACITY_VALUE_NOT_POSITIVE',
  CAPACITY_PLAN_NOT_FOUND = 'CAPACITY_PLAN_NOT_FOUND',
  CAPACITY_PLAN_NOT_ACTIVE = 'CAPACITY_PLAN_NOT_ACTIVE',
  CAPACITY_MEASUREMENT_OUTSIDE_HORIZON = 'CAPACITY_MEASUREMENT_OUTSIDE_HORIZON',

  // --- Releases: cambios, aprobaciones, artefactos, despliegues (ops-releases.service.ts) ---
  CHANGE_WINDOW_INVERTED = 'CHANGE_WINDOW_INVERTED',
  SERVICE_COMPONENT_NOT_FOUND = 'SERVICE_COMPONENT_NOT_FOUND',
  SERVICE_COMPONENT_NOT_ACTIVE = 'SERVICE_COMPONENT_NOT_ACTIVE',
  MAINTENANCE_WINDOW_NOT_FOUND = 'MAINTENANCE_WINDOW_NOT_FOUND',
  MAINTENANCE_WINDOW_CLOSED = 'MAINTENANCE_WINDOW_CLOSED',
  CHANGE_STARTS_BEFORE_WINDOW = 'CHANGE_STARTS_BEFORE_WINDOW',
  CHANGE_ENDS_AFTER_WINDOW = 'CHANGE_ENDS_AFTER_WINDOW',
  CHANGE_REQUEST_NOT_FOUND = 'CHANGE_REQUEST_NOT_FOUND',
  CHANGE_NOT_DECIDABLE = 'CHANGE_NOT_DECIDABLE',
  APPROVER_IS_REQUESTER = 'APPROVER_IS_REQUESTER',
  APPROVAL_STEP_ALREADY_VOTED = 'APPROVAL_STEP_ALREADY_VOTED',
  APPROVAL_STEP_OUT_OF_ORDER = 'APPROVAL_STEP_OUT_OF_ORDER',
  BUILD_TOOL_NOT_FOUND = 'BUILD_TOOL_NOT_FOUND',
  BUILD_TOOL_NOT_APPROVED = 'BUILD_TOOL_NOT_APPROVED',
  ARTIFACT_REF_DUPLICATE = 'ARTIFACT_REF_DUPLICATE',
  ARTIFACT_VERSION_DUPLICATE = 'ARTIFACT_VERSION_DUPLICATE',
  CHANGE_NOT_APPROVED = 'CHANGE_NOT_APPROVED',
  ARTIFACT_NOT_FOUND = 'ARTIFACT_NOT_FOUND',
  ARTIFACT_NOT_ACTIVE = 'ARTIFACT_NOT_ACTIVE',
  ARTIFACT_COMPONENT_MISMATCH = 'ARTIFACT_COMPONENT_MISMATCH',
  PRODUCTION_READINESS_REVIEW_MISSING = 'PRODUCTION_READINESS_REVIEW_MISSING',
  DEPLOYMENTS_FROZEN = 'DEPLOYMENTS_FROZEN',
  DEPLOYMENT_NOT_FOUND = 'DEPLOYMENT_NOT_FOUND',
  DEPLOYMENT_NOT_REVERSIBLE = 'DEPLOYMENT_NOT_REVERSIBLE',
  DEPLOYMENT_NOT_CURRENT = 'DEPLOYMENT_NOT_CURRENT',
  ROLLBACK_TARGET_NOT_FOUND = 'ROLLBACK_TARGET_NOT_FOUND',
  ROLLBACK_TARGET_MISMATCH = 'ROLLBACK_TARGET_MISMATCH',
  CHANGE_NUMBER_EXHAUSTED = 'CHANGE_NUMBER_EXHAUSTED',
  DEPLOYMENT_NUMBER_EXHAUSTED = 'DEPLOYMENT_NUMBER_EXHAUSTED',

  // --- Prácticas: revisión de preparación, runbooks, resiliencia (ops-practices.service.ts) ---
  READINESS_REVIEW_NOT_FOUND = 'READINESS_REVIEW_NOT_FOUND',
  READINESS_REVIEW_NOT_IN_PROGRESS = 'READINESS_REVIEW_NOT_IN_PROGRESS',
  READINESS_FINDING_NOT_IN_REVIEW = 'READINESS_FINDING_NOT_IN_REVIEW',
  READINESS_FINDING_NOT_OPEN = 'READINESS_FINDING_NOT_OPEN',
  READINESS_BLOCKING_FINDINGS_OPEN = 'READINESS_BLOCKING_FINDINGS_OPEN',
  RUNBOOK_NOT_FOUND = 'RUNBOOK_NOT_FOUND',
  RUNBOOK_NOT_ACTIVE = 'RUNBOOK_NOT_ACTIVE',
  RUNBOOK_VERSION_DUPLICATE = 'RUNBOOK_VERSION_DUPLICATE',
  RUNBOOK_EXECUTION_WINDOW_INVERTED = 'RUNBOOK_EXECUTION_WINDOW_INVERTED',
  RUNBOOK_VERSION_NOT_FOUND = 'RUNBOOK_VERSION_NOT_FOUND',
  RESILIENCE_EXERCISE_WINDOW_INVERTED = 'RESILIENCE_EXERCISE_WINDOW_INVERTED',
  RESILIENCE_EXERCISE_NOT_FOUND = 'RESILIENCE_EXERCISE_NOT_FOUND',
  RESILIENCE_EXERCISE_ALREADY_CLOSED = 'RESILIENCE_EXERCISE_ALREADY_CLOSED',
  RECOVERY_OBJECTIVE_NOT_FOUND = 'RECOVERY_OBJECTIVE_NOT_FOUND',

  // --- Observabilidad: health checks, incidentes, postmortem (ops-incidents.service.ts) ---
  HEALTH_CHECK_NOT_FOUND = 'HEALTH_CHECK_NOT_FOUND',
  HEALTH_CHECK_NOT_ACTIVE = 'HEALTH_CHECK_NOT_ACTIVE',
  HEALTH_CHECK_DISABLED = 'HEALTH_CHECK_DISABLED',
  INCIDENT_NOT_FOUND = 'INCIDENT_NOT_FOUND',
  INCIDENT_ALREADY_RESOLVED = 'INCIDENT_ALREADY_RESOLVED',
  INCIDENT_NOT_RESOLVED = 'INCIDENT_NOT_RESOLVED',
  INCIDENT_POSTMORTEM_ALREADY_EXISTS = 'INCIDENT_POSTMORTEM_ALREADY_EXISTS',
  INCIDENT_TRANSITION_INVALID = 'INCIDENT_TRANSITION_INVALID',
  INCIDENT_RESOLVE_MISSING_ROOT_CAUSE = 'INCIDENT_RESOLVE_MISSING_ROOT_CAUSE',
  POSTMORTEM_ACTION_CODE_DUPLICATE = 'POSTMORTEM_ACTION_CODE_DUPLICATE',
}
