/**
 * Catálogo de sub-códigos de negocio estables del módulo `ads`.
 *
 * `DomainException` (y sus subclases) ya llevan un `code` genérico (CONFLICT,
 * NOT_FOUND, etc.), común a todo el API. `AdsErrorReason` añade el **cuál**
 * dentro de ese tipo, propio de este módulo, para que un cliente pueda
 * ramificar sobre un valor estable sin parsear el `message` (que sigue siendo
 * sólo para humanos y puede cambiar de redacción).
 */
export enum AdsErrorReason {
  // --- Cuentas, business managers, socios y conexión de plataforma ---
  AD_ACCOUNT_REF_DUPLICATE = 'AD_ACCOUNT_REF_DUPLICATE',
  BUSINESS_MANAGER_NOT_FOUND = 'BUSINESS_MANAGER_NOT_FOUND',
  BUSINESS_MANAGER_CREATION_DATA_MISSING = 'BUSINESS_MANAGER_CREATION_DATA_MISSING',
  BUSINESS_MANAGER_REF_DUPLICATE = 'BUSINESS_MANAGER_REF_DUPLICATE',
  PARTNER_NOT_ACTIVE = 'PARTNER_NOT_ACTIVE',
  AD_ACCOUNT_NOT_FOUND = 'AD_ACCOUNT_NOT_FOUND',
  AD_ACCOUNT_NOT_IN_BUSINESS_MANAGER = 'AD_ACCOUNT_NOT_IN_BUSINESS_MANAGER',
  PLATFORM_ACCOUNT_ALREADY_CONNECTED = 'PLATFORM_ACCOUNT_ALREADY_CONNECTED',

  // --- Campañas, segmentación, identidades y presupuesto ---
  CAMPAIGN_SCHEDULE_INVERTED = 'CAMPAIGN_SCHEDULE_INVERTED',
  CAMPAIGN_BUDGET_MISSING = 'CAMPAIGN_BUDGET_MISSING',
  AD_ACCOUNT_NOT_ACTIVE = 'AD_ACCOUNT_NOT_ACTIVE',
  AD_ACCOUNT_SPEND_CAP_EXHAUSTED = 'AD_ACCOUNT_SPEND_CAP_EXHAUSTED',
  TARGETING_SPEC_NOT_FOUND = 'TARGETING_SPEC_NOT_FOUND',
  TARGETING_AGE_RANGE_INVERTED = 'TARGETING_AGE_RANGE_INVERTED',
  LOOKALIKE_COUNTRY_MISSING = 'LOOKALIKE_COUNTRY_MISSING',
  AD_SET_NOT_FOUND = 'AD_SET_NOT_FOUND',
  IDENTITY_NOT_FOUND = 'IDENTITY_NOT_FOUND',
  IDENTITY_NOT_ACTIVE = 'IDENTITY_NOT_ACTIVE',
  BUDGET_SCHEDULE_RANGE_INVERTED = 'BUDGET_SCHEDULE_RANGE_INVERTED',
  CAMPAIGN_NOT_FOUND = 'CAMPAIGN_NOT_FOUND',
  BUDGET_SCHEDULE_EXCEEDS_SPEND_CAP = 'BUDGET_SCHEDULE_EXCEEDS_SPEND_CAP',
  BUDGET_SCHEDULE_OVERLAP = 'BUDGET_SCHEDULE_OVERLAP',

  // --- Política de datos, ingesta, conversiones y catálogo ---
  EVENT_POLICY_CODE_DUPLICATE = 'EVENT_POLICY_CODE_DUPLICATE',
  FIELD_RULE_TRANSFORMATION_MISSING = 'FIELD_RULE_TRANSFORMATION_MISSING',
  PLATFORM_CONNECTION_NOT_FOUND = 'PLATFORM_CONNECTION_NOT_FOUND',
  PLATFORM_CONNECTION_NOT_ACTIVE = 'PLATFORM_CONNECTION_NOT_ACTIVE',
  CONVERSION_DATASET_NOT_FOUND = 'CONVERSION_DATASET_NOT_FOUND',
  CONVERSION_DATASET_NOT_ACTIVE = 'CONVERSION_DATASET_NOT_ACTIVE',
  CONVERSION_CONSENT_REQUIRED = 'CONVERSION_CONSENT_REQUIRED',
  CATALOG_NOT_FOUND = 'CATALOG_NOT_FOUND',
  CATALOG_FEED_NOT_FOUND = 'CATALOG_FEED_NOT_FOUND',
  CATALOG_FEED_CATALOG_MISMATCH = 'CATALOG_FEED_CATALOG_MISMATCH',
  CATALOG_FEED_NOT_ACTIVE = 'CATALOG_FEED_NOT_ACTIVE',

  // --- Experimentos, reglas automatizadas, moderación, facturación y leads ---
  EXPERIMENT_TRAFFIC_SPLIT_INVALID = 'EXPERIMENT_TRAFFIC_SPLIT_INVALID',
  EXPERIMENT_CONTROL_COUNT_INVALID = 'EXPERIMENT_CONTROL_COUNT_INVALID',
  EXPERIMENT_VARIANT_CAMPAIGN_NOT_FOUND = 'EXPERIMENT_VARIANT_CAMPAIGN_NOT_FOUND',
  EXPERIMENT_VARIANT_AD_SET_NOT_FOUND = 'EXPERIMENT_VARIANT_AD_SET_NOT_FOUND',
  AUTOMATED_RULE_NOT_FOUND = 'AUTOMATED_RULE_NOT_FOUND',
  AUTOMATED_RULE_NOT_ENABLED = 'AUTOMATED_RULE_NOT_ENABLED',
  AD_NOT_FOUND = 'AD_NOT_FOUND',
  REVIEW_DISAPPROVAL_POLICY_DATA_MISSING = 'REVIEW_DISAPPROVAL_POLICY_DATA_MISSING',
  POLICY_VIOLATION_NOT_FOUND = 'POLICY_VIOLATION_NOT_FOUND',
  POLICY_VIOLATION_NOT_OPEN = 'POLICY_VIOLATION_NOT_OPEN',
  POLICY_APPEAL_ALREADY_EXISTS = 'POLICY_APPEAL_ALREADY_EXISTS',
  INVOICE_PERIOD_INVERTED = 'INVOICE_PERIOD_INVERTED',
  INVOICE_NUMBER_DUPLICATE = 'INVOICE_NUMBER_DUPLICATE',
  INVOICE_PERIOD_ALREADY_ISSUED = 'INVOICE_PERIOD_ALREADY_ISSUED',
  INVOICE_PERIOD_NO_USAGE = 'INVOICE_PERIOD_NO_USAGE',
  LEAD_FORM_NOT_FOUND = 'LEAD_FORM_NOT_FOUND',
  LEAD_FORM_NOT_ACTIVE = 'LEAD_FORM_NOT_ACTIVE',
  LEAD_REQUIRED_ANSWERS_MISSING = 'LEAD_REQUIRED_ANSWERS_MISSING',
}
