-- SALUD v4.0.10 · módulo 35 · schema messaging
-- Generado de diagram_35_messaging.puml — NO editar a mano.


CREATE TABLE IF NOT EXISTS "messaging"."domain_events" (
    "id" uuid NOT NULL,
    "tenant_id" uuid,
    "event_type" varchar NOT NULL,
    "event_version" integer NOT NULL,
    "aggregate_type" varchar NOT NULL,
    "aggregate_id" uuid NOT NULL,
    "payload_json" jsonb NOT NULL,
    "metadata_json" jsonb,
    "correlation_id" varchar NOT NULL,
    "causation_id" uuid,
    "occurred_at" timestamptz,
    "recorded_at" timestamptz NOT NULL,
    "recorded_by_user_id" uuid,
    CONSTRAINT "pk_domain_events" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "messaging"."outbox_messages" (
    "id" uuid NOT NULL,
    "tenant_id" uuid,
    "domain_event_id" uuid NOT NULL,
    "aggregate_type" varchar NOT NULL,
    "aggregate_id" uuid NOT NULL,
    "idempotency_key" varchar NOT NULL,
    "payload_json" jsonb NOT NULL,
    "status_concept_id" uuid NOT NULL,
    "available_at" timestamptz,
    "published_at" timestamptz,
    "attempts" integer NOT NULL,
    "max_attempts" integer NOT NULL,
    "locked_by" varchar,
    "lock_expires_at" timestamptz,
    "last_error_text" text,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_outbox_messages" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "messaging"."event_subscriptions" (
    "id" uuid NOT NULL,
    "tenant_id" uuid,
    "subscriber_code" varchar NOT NULL,
    "event_type" varchar NOT NULL,
    "event_version" integer,
    "delivery_mode_concept_id" uuid NOT NULL,
    "target_queue" varchar,
    "filter_json" jsonb,
    "is_active" boolean NOT NULL,
    "state_concept_id" uuid NOT NULL,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_event_subscriptions" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "messaging"."event_deliveries" (
    "id" uuid NOT NULL,
    "domain_event_id" uuid NOT NULL,
    "subscription_id" uuid NOT NULL,
    "status_concept_id" uuid NOT NULL,
    "attempt_number" integer NOT NULL,
    "error_text" text,
    "handled_at" timestamptz,
    "recorded_at" timestamptz NOT NULL,
    "recorded_by_user_id" uuid,
    CONSTRAINT "pk_event_deliveries" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "messaging"."message_queues" (
    "id" uuid NOT NULL,
    "code" varchar NOT NULL,
    "name" varchar NOT NULL,
    "default_priority" integer,
    "default_max_attempts" integer,
    "visibility_timeout_s" integer,
    "dead_letter_queue_id" uuid,
    "state_concept_id" uuid NOT NULL,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_message_queues" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "messaging"."queued_jobs" (
    "id" uuid NOT NULL,
    "queue_id" uuid NOT NULL,
    "tenant_id" uuid,
    "job_type" varchar NOT NULL,
    "dedupe_key" varchar,
    "priority" integer NOT NULL,
    "payload_json" jsonb NOT NULL,
    "status_concept_id" uuid NOT NULL,
    "available_at" timestamptz,
    "started_at" timestamptz,
    "completed_at" timestamptz,
    "attempts" integer NOT NULL,
    "max_attempts" integer NOT NULL,
    "locked_by" varchar,
    "lock_expires_at" timestamptz,
    "last_error_text" text,
    "result_json" jsonb,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_queued_jobs" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "messaging"."dead_letter_jobs" (
    "id" uuid NOT NULL,
    "queue_id" uuid NOT NULL,
    "original_job_id" uuid NOT NULL,
    "failure_reason_text" text NOT NULL,
    "payload_json" jsonb NOT NULL,
    "attempts" integer NOT NULL,
    "failed_at" timestamptz,
    "recorded_at" timestamptz NOT NULL,
    "recorded_by_user_id" uuid,
    CONSTRAINT "pk_dead_letter_jobs" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "messaging"."in_app_notifications" (
    "id" uuid NOT NULL,
    "recipient_user_id" uuid NOT NULL,
    "tenant_id" uuid,
    "channel_concept_id" uuid NOT NULL,
    "category_concept_id" uuid,
    "template_code" varchar,
    "subject" varchar,
    "body_text" text,
    "payload_json" jsonb,
    "related_resource_type" varchar,
    "related_resource_id" uuid,
    "status_concept_id" uuid NOT NULL,
    "scheduled_at" timestamptz,
    "sent_at" timestamptz,
    "read_at" timestamptz,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    "notification_request_id" uuid NOT NULL,
    "notification_delivery_id" uuid NOT NULL,
    "dispatch_recipient_id" uuid,
    "available_at" timestamptz NOT NULL,
    "first_seen_at" timestamptz,
    "last_seen_at" timestamptz,
    "opened_at" timestamptz,
    "dismissed_at" timestamptz,
    "archived_at" timestamptz,
    "expires_at" timestamptz,
    "action_state_json" jsonb,
    CONSTRAINT "pk_in_app_notifications" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "messaging"."message_channels" (
    "id" uuid NOT NULL,
    "code" varchar NOT NULL,
    "name" varchar NOT NULL,
    "channel_type_concept_id" uuid NOT NULL,
    "supports_templates" boolean,
    "state_concept_id" uuid NOT NULL,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_message_channels" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "messaging"."messaging_providers" (
    "id" uuid NOT NULL,
    "code" varchar NOT NULL,
    "name" varchar NOT NULL,
    "provider_type_concept_id" uuid NOT NULL,
    "capabilities_json" jsonb,
    "external_provider_id" uuid,
    "state_concept_id" uuid NOT NULL,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    "adapter_code" varchar NOT NULL,
    "adapter_version" varchar NOT NULL,
    "is_builtin" boolean NOT NULL,
    "supports_webhooks" boolean NOT NULL,
    "supports_polling" boolean NOT NULL,
    "supports_delivery_receipts" boolean NOT NULL,
    "supports_read_receipts" boolean NOT NULL,
    "supports_click_receipts" boolean NOT NULL,
    "supports_reply_receipts" boolean NOT NULL,
    "provider_time_semantics_concept_id" uuid,
    CONSTRAINT "pk_messaging_providers" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "messaging"."provider_channel_configs" (
    "id" uuid NOT NULL,
    "provider_id" uuid NOT NULL,
    "channel_id" uuid NOT NULL,
    "tenant_id" uuid,
    "sender_identity" varchar,
    "credential_id" uuid,
    "config_json" jsonb,
    "priority" integer,
    "rate_limit_per_min" integer,
    "state_concept_id" uuid NOT NULL,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    "adapter_config_version" integer NOT NULL,
    "webhook_endpoint_key" varchar,
    "webhook_secret_credential_id" uuid,
    "webhook_signature_scheme_concept_id" uuid,
    "tracking_mode_concept_id" uuid NOT NULL,
    "polling_interval_seconds" integer,
    "status_mapping_version" integer NOT NULL,
    "enabled_at" timestamptz,
    "disabled_at" timestamptz,
    "enabled_by_user_id" uuid,
    "disabled_by_user_id" uuid,
    CONSTRAINT "pk_provider_channel_configs" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "messaging"."message_templates" (
    "id" uuid NOT NULL,
    "tenant_id" uuid,
    "code" varchar NOT NULL,
    "channel_id" uuid NOT NULL,
    "language_concept_id" uuid,
    "subject_template" varchar NOT NULL,
    "body_template" text NOT NULL,
    "variables_json" jsonb,
    "provider_template_ref" varchar,
    "version" integer NOT NULL,
    "status_concept_id" uuid NOT NULL,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_message_templates" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "messaging"."notification_requests" (
    "id" uuid NOT NULL,
    "tenant_id" uuid,
    "recipient_user_id" uuid NOT NULL,
    "recipient_address" varchar,
    "channel_id" uuid NOT NULL,
    "template_id" uuid,
    "domain_event_id" uuid,
    "payload_json" jsonb,
    "debounce_key" varchar,
    "priority" integer NOT NULL,
    "category_concept_id" uuid,
    "related_resource_type" varchar,
    "related_resource_id" uuid,
    "status_concept_id" uuid NOT NULL,
    "scheduled_at" timestamptz,
    "consent_id" uuid,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    "dispatch_id" uuid,
    "dispatch_recipient_id" uuid,
    "recipient_type_concept_id" uuid NOT NULL,
    "recipient_ref_id" uuid NOT NULL,
    "recipient_endpoint_id" uuid,
    "source_concept_id" uuid NOT NULL,
    "authorized_by_user_id" uuid NOT NULL,
    "authorization_snapshot_json" jsonb NOT NULL,
    "content_snapshot_json" jsonb NOT NULL,
    "content_hash" varchar NOT NULL,
    "idempotency_key" varchar NOT NULL,
    "expires_at" timestamptz,
    "cancellation_requested_at" timestamptz,
    "cancelled_at" timestamptz,
    CONSTRAINT "pk_notification_requests" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "messaging"."notification_deliveries" (
    "id" uuid NOT NULL,
    "notification_request_id" uuid NOT NULL,
    "provider_id" uuid NOT NULL,
    "channel_id" uuid NOT NULL,
    "attempt_number" integer NOT NULL,
    "provider_message_ref" varchar,
    "status_concept_id" uuid NOT NULL,
    "error_code" varchar,
    "error_text" text,
    "cost_amount" numeric,
    "currency_concept_id" uuid,
    "sent_at" timestamptz,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    "provider_channel_config_id" uuid NOT NULL,
    "adapter_code" varchar NOT NULL,
    "adapter_version" varchar NOT NULL,
    "started_at" timestamptz,
    "accepted_at" timestamptz,
    "delivered_at" timestamptz,
    "seen_at" timestamptz,
    "read_at" timestamptz,
    "clicked_at" timestamptz,
    "replied_at" timestamptz,
    "bounced_at" timestamptz,
    "failed_at" timestamptz,
    "cancelled_at" timestamptz,
    "expired_at" timestamptz,
    "terminal_at" timestamptz,
    "last_event_at" timestamptz,
    "last_event_id" uuid,
    "provider_status_raw" varchar,
    "provider_response_hash" varchar,
    CONSTRAINT "pk_notification_deliveries" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "messaging"."delivery_receipts" (
    "id" uuid NOT NULL,
    "delivery_id" uuid NOT NULL,
    "receipt_type_concept_id" uuid NOT NULL,
    "provider_status" varchar,
    "raw_payload_json" jsonb,
    "occurred_at" timestamptz,
    "recorded_at" timestamptz NOT NULL,
    "recorded_by_user_id" uuid,
    CONSTRAINT "pk_delivery_receipts" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "messaging"."recipient_preferences" (
    "id" uuid NOT NULL,
    "user_id" uuid NOT NULL,
    "tenant_id" uuid,
    "channel_id" uuid NOT NULL,
    "category_concept_id" uuid,
    "opted_in" boolean NOT NULL,
    "quiet_hours_json" jsonb,
    "language_concept_id" uuid,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_recipient_preferences" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "messaging"."adapter_event_mappings" (
    "id" uuid NOT NULL,
    "provider_id" uuid NOT NULL,
    "channel_id" uuid NOT NULL,
    "mapping_version" integer NOT NULL,
    "external_event_code" varchar NOT NULL,
    "canonical_event_type_concept_id" uuid NOT NULL,
    "canonical_delivery_status_concept_id" uuid NOT NULL,
    "terminal" boolean NOT NULL,
    "success" boolean,
    "precedence" integer NOT NULL,
    "condition_json" jsonb,
    "effective_from" timestamptz NOT NULL,
    "effective_to" timestamptz,
    "state_concept_id" uuid NOT NULL,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid NOT NULL,
    "updated_by_user_id" uuid NOT NULL,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_adapter_event_mappings" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "messaging"."adapter_inbound_events" (
    "id" uuid NOT NULL,
    "provider_id" uuid NOT NULL,
    "provider_channel_config_id" uuid NOT NULL,
    "channel_id" uuid NOT NULL,
    "ingestion_type_concept_id" uuid NOT NULL,
    "external_event_id" varchar,
    "external_event_code" varchar NOT NULL,
    "provider_message_ref" varchar,
    "payload_json_encrypted" jsonb,
    "payload_storage_ref" varchar,
    "payload_sha256" varchar NOT NULL,
    "headers_redacted_json" jsonb,
    "signature_status_concept_id" uuid NOT NULL,
    "replay_status_concept_id" uuid NOT NULL,
    "received_at" timestamptz NOT NULL,
    "provider_occurred_at" timestamptz,
    "processing_status_concept_id" uuid NOT NULL,
    "processing_attempts" integer NOT NULL,
    "mapping_version" integer,
    "delivery_id" uuid,
    "normalization_error_code" varchar,
    "normalization_error_detail" text,
    "recorded_at" timestamptz NOT NULL,
    CONSTRAINT "pk_adapter_inbound_events" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "messaging"."adapter_tracking_capabilities" (
    "id" uuid NOT NULL,
    "provider_id" uuid NOT NULL,
    "channel_id" uuid NOT NULL,
    "canonical_event_type_concept_id" uuid NOT NULL,
    "support_level_concept_id" uuid NOT NULL,
    "evidence_source_concept_id" uuid NOT NULL,
    "notes" text,
    "state_concept_id" uuid NOT NULL,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid NOT NULL,
    "updated_by_user_id" uuid NOT NULL,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_adapter_tracking_capabilities" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "messaging"."delivery_reconciliation_runs" (
    "id" uuid NOT NULL,
    "provider_channel_config_id" uuid NOT NULL,
    "started_at" timestamptz NOT NULL,
    "finished_at" timestamptz,
    "status_concept_id" uuid NOT NULL,
    "query_window_from" timestamptz NOT NULL,
    "query_window_to" timestamptz NOT NULL,
    "deliveries_checked" bigint NOT NULL,
    "events_imported" bigint NOT NULL,
    "inconsistencies_found" bigint NOT NULL,
    "error_detail" text,
    "created_by_user_id" uuid NOT NULL,
    "created_at" timestamptz NOT NULL,
    CONSTRAINT "pk_delivery_reconciliation_runs" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "messaging"."delivery_status_transitions" (
    "id" uuid NOT NULL,
    "from_status_concept_id" uuid,
    "event_type_concept_id" uuid NOT NULL,
    "to_status_concept_id" uuid NOT NULL,
    "channel_type_concept_id" uuid,
    "allow_late_event" boolean NOT NULL,
    "allow_after_terminal" boolean NOT NULL,
    "precedence" integer NOT NULL,
    "state_concept_id" uuid NOT NULL,
    CONSTRAINT "pk_delivery_status_transitions" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "messaging"."delivery_tracking_events" (
    "id" uuid NOT NULL,
    "delivery_id" uuid NOT NULL,
    "notification_request_id" uuid NOT NULL,
    "dispatch_id" uuid,
    "dispatch_recipient_id" uuid,
    "inbound_event_id" uuid,
    "canonical_event_type_concept_id" uuid NOT NULL,
    "resulting_status_concept_id" uuid NOT NULL,
    "source_concept_id" uuid NOT NULL,
    "provider_event_code" varchar,
    "provider_event_id" varchar,
    "provider_message_ref" varchar,
    "sequence_number" bigint,
    "occurred_at" timestamptz NOT NULL,
    "received_at" timestamptz NOT NULL,
    "effective_at" timestamptz NOT NULL,
    "precedence" integer NOT NULL,
    "is_terminal" boolean NOT NULL,
    "is_success" boolean,
    "is_late" boolean NOT NULL,
    "is_duplicate" boolean NOT NULL,
    "metadata_json" jsonb,
    "recorded_at" timestamptz NOT NULL,
    "recorded_by_user_id" uuid,
    CONSTRAINT "pk_delivery_tracking_events" PRIMARY KEY ("id")
);
