/**
 * Catálogo de sub-códigos de negocio del módulo `automation`.
 *
 * Cada miembro nombra una situación de negocio distinta dentro del `code`
 * genérico (CONFLICT, NOT_FOUND, PRECONDITION_FAILED, …) que ya fija el
 * `DomainException`. Un cliente puede ramificar sobre `reason` sin tener que
 * parsear `message`, que sigue siendo sólo para humanos.
 */
export enum AutomationErrorReason {
  // --- Workflows y pasos --------------------------------------------------
  WORKFLOW_CODE_ALREADY_EXISTS = 'WORKFLOW_CODE_ALREADY_EXISTS',
  DUPLICATE_STEP_CODE_IN_BATCH = 'DUPLICATE_STEP_CODE_IN_BATCH',
  STEP_TARGET_NOT_DECLARED = 'STEP_TARGET_NOT_DECLARED',
  AGENT_CALL_STEP_MISSING_AGENT = 'AGENT_CALL_STEP_MISSING_AGENT',
  TOOL_CALL_STEP_MISSING_TOOL = 'TOOL_CALL_STEP_MISSING_TOOL',
  STEP_AGENT_NOT_FOUND = 'STEP_AGENT_NOT_FOUND',
  STEP_TOOL_NOT_FOUND = 'STEP_TOOL_NOT_FOUND',
  WORKFLOW_NOT_FOUND = 'WORKFLOW_NOT_FOUND',
  WORKFLOW_ARCHIVED = 'WORKFLOW_ARCHIVED',

  // --- Disparadores --------------------------------------------------------
  TRIGGER_CODE_ALREADY_EXISTS = 'TRIGGER_CODE_ALREADY_EXISTS',
  EVENT_TRIGGER_MISSING_EVENT_TYPE = 'EVENT_TRIGGER_MISSING_EVENT_TYPE',
  SCHEDULE_TRIGGER_MISSING_CRON = 'SCHEDULE_TRIGGER_MISSING_CRON',
  CRON_INVALID_FIELD_COUNT = 'CRON_INVALID_FIELD_COUNT',
  TRIGGER_NOT_FOUND = 'TRIGGER_NOT_FOUND',
  TRIGGER_DISABLED = 'TRIGGER_DISABLED',
  TRIGGER_WORKFLOW_MISMATCH = 'TRIGGER_WORKFLOW_MISMATCH',

  // --- Agentes y versiones ---------------------------------------------------
  AGENT_CODE_ALREADY_EXISTS = 'AGENT_CODE_ALREADY_EXISTS',
  ACTING_AGENT_MISSING_SERVICE_IDENTITY = 'ACTING_AGENT_MISSING_SERVICE_IDENTITY',
  AGENT_NOT_FOUND = 'AGENT_NOT_FOUND',
  AGENT_NOT_ACTIVE = 'AGENT_NOT_ACTIVE',
  AGENT_VERSION_NOT_FOUND_FOR_AGENT = 'AGENT_VERSION_NOT_FOUND_FOR_AGENT',
  AGENT_VERSION_NOT_DRAFT = 'AGENT_VERSION_NOT_DRAFT',
  AGENT_VERSION_NOT_PUBLISHED = 'AGENT_VERSION_NOT_PUBLISHED',
  NEW_VERSION_MISSING_PROMPT_TEMPLATE = 'NEW_VERSION_MISSING_PROMPT_TEMPLATE',

  // --- Herramientas y enlaces ------------------------------------------------
  TOOL_CODE_ALREADY_EXISTS = 'TOOL_CODE_ALREADY_EXISTS',
  HTTP_TOOL_MISSING_INTEGRATION_ENDPOINT = 'HTTP_TOOL_MISSING_INTEGRATION_ENDPOINT',
  DUPLICATE_TOOL_IN_BINDING_BATCH = 'DUPLICATE_TOOL_IN_BINDING_BATCH',
  TOOL_NOT_FOUND = 'TOOL_NOT_FOUND',
  TOOL_NOT_ACTIVE = 'TOOL_NOT_ACTIVE',
  TOOL_ALREADY_BOUND_TO_VERSION = 'TOOL_ALREADY_BOUND_TO_VERSION',
  TOOL_NOT_BOUND_TO_VERSION = 'TOOL_NOT_BOUND_TO_VERSION',
  TOOL_BINDING_DENIED = 'TOOL_BINDING_DENIED',
  TOOL_CALL_LIMIT_EXCEEDED = 'TOOL_CALL_LIMIT_EXCEEDED',

  // --- Guardrails --------------------------------------------------------
  GUARDRAIL_CODE_ALREADY_EXISTS = 'GUARDRAIL_CODE_ALREADY_EXISTS',
  COST_GUARDRAIL_MISSING_CAP = 'COST_GUARDRAIL_MISSING_CAP',
  PHI_GUARDRAIL_MISSING_HANDLING = 'PHI_GUARDRAIL_MISSING_HANDLING',
  GUARDRAIL_POLICY_NOT_FOUND = 'GUARDRAIL_POLICY_NOT_FOUND',
  GUARDRAIL_POLICY_NOT_ACTIVE = 'GUARDRAIL_POLICY_NOT_ACTIVE',
  GUARDRAIL_ALREADY_ATTACHED = 'GUARDRAIL_ALREADY_ATTACHED',

  // --- Memoria del agente --------------------------------------------------
  MEMORY_SCOPE_MISSING_REFERENCE = 'MEMORY_SCOPE_MISSING_REFERENCE',

  // --- Runs de workflow y de agente -----------------------------------------
  WORKFLOW_RUN_NOT_FOUND = 'WORKFLOW_RUN_NOT_FOUND',
  WORKFLOW_RUN_NOT_RUNNING = 'WORKFLOW_RUN_NOT_RUNNING',
  WORKFLOW_RUN_HAS_PENDING_APPROVALS = 'WORKFLOW_RUN_HAS_PENDING_APPROVALS',
  AGENT_RUN_NOT_FOUND = 'AGENT_RUN_NOT_FOUND',
  AGENT_RUN_NOT_RUNNING_FOR_STEP = 'AGENT_RUN_NOT_RUNNING_FOR_STEP',
  AGENT_RUN_NOT_RUNNING_FOR_RECORD_WRITE = 'AGENT_RUN_NOT_RUNNING_FOR_RECORD_WRITE',
  AGENT_RUN_ALREADY_FINISHED = 'AGENT_RUN_ALREADY_FINISHED',
  AGENT_RUN_NOT_PAUSED = 'AGENT_RUN_NOT_PAUSED',

  // --- Aprobaciones --------------------------------------------------------
  APPROVAL_NOT_FOUND = 'APPROVAL_NOT_FOUND',
  APPROVAL_ALREADY_DECIDED = 'APPROVAL_ALREADY_DECIDED',

  // --- Automatización de registro (UC-48-13) --------------------------------
  RECORD_AUTOMATION_NOT_FOUND = 'RECORD_AUTOMATION_NOT_FOUND',
  RECORD_AUTOMATION_NOT_ACTIVE = 'RECORD_AUTOMATION_NOT_ACTIVE',
  RECORD_AUTOMATION_WRONG_AGENT = 'RECORD_AUTOMATION_WRONG_AGENT',
  AGENT_MISSING_SERVICE_IDENTITY_FOR_RECORD_WRITE = 'AGENT_MISSING_SERVICE_IDENTITY_FOR_RECORD_WRITE',
  UPSERT_MISSING_DEDUPE_KEY = 'UPSERT_MISSING_DEDUPE_KEY',
  FIELD_MAPPING_NOT_DECLARED = 'FIELD_MAPPING_NOT_DECLARED',
  FIELD_MAPPING_RULE_INVALID = 'FIELD_MAPPING_RULE_INVALID',
  FIELD_MAPPING_SOURCE_NOT_STRING = 'FIELD_MAPPING_SOURCE_NOT_STRING',
  FIELD_MAPPING_RULE_MISSING_SOURCE = 'FIELD_MAPPING_RULE_MISSING_SOURCE',
  FIELD_MAPPING_REQUIRED_VALUE_MISSING = 'FIELD_MAPPING_REQUIRED_VALUE_MISSING',
  VALIDATION_REQUIRED_FIELD_MISSING = 'VALIDATION_REQUIRED_FIELD_MISSING',
}
