export * from './consents.repository';
export * from './consent-provisions.repository';
export * from './consent-events.repository';
export * from './consent-evidence.repository';
export * from './hipaa-authorizations.repository';
export * from './patient-objections.repository';
export * from './privacy-restrictions.repository';
export * from './processing-legal-bases.repository';
export * from './treatment-informed-consents.repository';
