/**
 * Catálogo de sub-códigos de negocio del módulo `community`.
 *
 * Cada miembro nombra una situación de negocio distinta que puede producir un
 * `DomainException` (o subclase) dentro de este módulo. El `code` genérico de
 * la excepción (`CONFLICT`, `NOT_FOUND`, etc.) sigue diciendo el tipo HTTP;
 * `reason` dice **cuál** de los errores de ese tipo fue, dentro de este
 * catálogo, para que un cliente pueda ramificar sin parsear `message`.
 */
export enum CommunityErrorReason {
  // --- Grupos ---
  GROUP_NOT_FOUND = 'GROUP_NOT_FOUND',
  GROUP_SECRET_NOT_VISIBLE = 'GROUP_SECRET_NOT_VISIBLE',
  GROUP_DISSOLVED = 'GROUP_DISSOLVED',
  GROUP_SLUG_ALREADY_IN_USE = 'GROUP_SLUG_ALREADY_IN_USE',
  GROUP_TOPIC_NOT_FOUND = 'GROUP_TOPIC_NOT_FOUND',
  OWNER_PUBLIC_PROFILE_REQUIRED = 'OWNER_PUBLIC_PROFILE_REQUIRED',
  ALREADY_GROUP_MEMBER = 'ALREADY_GROUP_MEMBER',
  MEMBER_NOT_IN_GROUP = 'MEMBER_NOT_IN_GROUP',
  GROUP_OWNER_CANNOT_BE_REMOVED = 'GROUP_OWNER_CANNOT_BE_REMOVED',
  MEMBER_UPDATE_NO_CHANGE_REQUESTED = 'MEMBER_UPDATE_NO_CHANGE_REQUESTED',
  GROUP_MEMBERSHIP_NOT_FOUND = 'GROUP_MEMBERSHIP_NOT_FOUND',
  JOIN_REQUEST_ALREADY_RESOLVED = 'JOIN_REQUEST_ALREADY_RESOLVED',
  PUBLIC_GROUP_OWNER_PROFILE_MISSING = 'PUBLIC_GROUP_OWNER_PROFILE_MISSING',
  PUBLIC_GROUP_OWNER_PROFILE_INCOMPLETE = 'PUBLIC_GROUP_OWNER_PROFILE_INCOMPLETE',
  GROUP_WALL_PARENT_NOT_IN_GROUP = 'GROUP_WALL_PARENT_NOT_IN_GROUP',

  // --- Perfiles públicos ---
  ORGANIZATION_VITRINA_NOT_PROJECTED = 'ORGANIZATION_VITRINA_NOT_PROJECTED',
  PROFILE_NOT_FOUND_BY_SLUG = 'PROFILE_NOT_FOUND_BY_SLUG',
  PUBLIC_PROFILE_NOT_FOUND = 'PUBLIC_PROFILE_NOT_FOUND',
  PUBLIC_PROFILE_BLOCKED = 'PUBLIC_PROFILE_BLOCKED',
  PROFILE_SLUG_ALREADY_IN_USE = 'PROFILE_SLUG_ALREADY_IN_USE',
  OWN_PROFILE_SAVE_FAILED = 'OWN_PROFILE_SAVE_FAILED',
  POST_AUTHOR_PROFILE_NOT_FOUND = 'POST_AUTHOR_PROFILE_NOT_FOUND',
  COMMENT_AUTHOR_PROFILE_NOT_FOUND = 'COMMENT_AUTHOR_PROFILE_NOT_FOUND',

  // --- Posts, comentarios, reacciones y grafo social ---
  POST_NOT_FOUND = 'POST_NOT_FOUND',
  POST_NOT_VISIBLE = 'POST_NOT_VISIBLE',
  PARENT_COMMENT_NOT_FOUND = 'PARENT_COMMENT_NOT_FOUND',
  COMMENT_MEDIA_NOT_FOUND = 'COMMENT_MEDIA_NOT_FOUND',
  COMMENT_MEDIA_INVALID_PARENT = 'COMMENT_MEDIA_INVALID_PARENT',
  BOOKMARK_ALREADY_EXISTS = 'BOOKMARK_ALREADY_EXISTS',
  CANNOT_FOLLOW_SELF = 'CANNOT_FOLLOW_SELF',
  ALREADY_FOLLOWING = 'ALREADY_FOLLOWING',
  CANNOT_BLOCK_SELF = 'CANNOT_BLOCK_SELF',
  USER_ALREADY_BLOCKED = 'USER_ALREADY_BLOCKED',

  // --- Encuestas ---
  POLL_NOT_FOUND = 'POLL_NOT_FOUND',
  POLL_POST_NOT_VISIBLE = 'POLL_POST_NOT_VISIBLE',
  POLL_POST_NOT_FOUND = 'POLL_POST_NOT_FOUND',
  POLL_CLOSED = 'POLL_CLOSED',
  POLL_OPTION_NOT_IN_POLL = 'POLL_OPTION_NOT_IN_POLL',
  DUPLICATE_VOTE_OPTION = 'DUPLICATE_VOTE_OPTION',
  POLL_SINGLE_VOTE_ONLY = 'POLL_SINGLE_VOTE_ONLY',

  // --- Mensajería ---
  CONVERSATION_NOT_FOUND = 'CONVERSATION_NOT_FOUND',
  CONVERSATION_BLOCKED_PEER = 'CONVERSATION_BLOCKED_PEER',
  SENDER_NOT_ACTIVE_PARTICIPANT = 'SENDER_NOT_ACTIVE_PARTICIPANT',
  RECIPIENT_NOT_ACTIVE_PARTICIPANT = 'RECIPIENT_NOT_ACTIVE_PARTICIPANT',
  BLOCKED_BETWEEN_PARTICIPANTS = 'BLOCKED_BETWEEN_PARTICIPANTS',

  // --- Reseñas ---
  ENCOUNTER_NOT_FOUND_FOR_REVIEW = 'ENCOUNTER_NOT_FOUND_FOR_REVIEW',
  ENCOUNTER_NOT_OWNED_BY_PATIENT = 'ENCOUNTER_NOT_OWNED_BY_PATIENT',
  ENCOUNTER_NOT_FINISHED = 'ENCOUNTER_NOT_FINISHED',
  ENCOUNTER_PRACTITIONER_MISMATCH = 'ENCOUNTER_PRACTITIONER_MISMATCH',
  REVIEW_TARGET_PROFILE_NOT_FOUND = 'REVIEW_TARGET_PROFILE_NOT_FOUND',
  REVIEW_TARGET_NOT_ACCEPTING_REVIEWS = 'REVIEW_TARGET_NOT_ACCEPTING_REVIEWS',
  DUPLICATE_VERIFIED_REVIEW = 'DUPLICATE_VERIFIED_REVIEW',
  REVIEW_NOT_FOUND = 'REVIEW_NOT_FOUND',
  REVIEW_ALREADY_RESPONDED = 'REVIEW_ALREADY_RESPONDED',

  // --- Moderación ---
  MODERATION_QUEUE_ENTRY_NOT_FOUND = 'MODERATION_QUEUE_ENTRY_NOT_FOUND',
  MODERATION_QUEUE_ALREADY_RESOLVED = 'MODERATION_QUEUE_ALREADY_RESOLVED',
  MODERATION_DECISION_NOT_FOUND = 'MODERATION_DECISION_NOT_FOUND',
  APPEAL_ALREADY_OPEN = 'APPEAL_ALREADY_OPEN',
  APPEAL_NOT_FOUND = 'APPEAL_NOT_FOUND',
  APPEAL_ALREADY_RESOLVED = 'APPEAL_ALREADY_RESOLVED',

  // --- Superficie pública (directorio) ---
  PUBLIC_COMMENT_NOT_FOUND = 'PUBLIC_COMMENT_NOT_FOUND',
  PUBLIC_POST_NOT_FOUND = 'PUBLIC_POST_NOT_FOUND',
  PUBLIC_FILE_NOT_FOUND = 'PUBLIC_FILE_NOT_FOUND',
  PUBLIC_DIRECTORY_PROFILE_NOT_FOUND = 'PUBLIC_DIRECTORY_PROFILE_NOT_FOUND',
  PUBLIC_DIRECTORY_PROFILE_PREFIX_INVALID = 'PUBLIC_DIRECTORY_PROFILE_PREFIX_INVALID',
}
