-- SALUD v4.0.10 · módulo 08 · schema clinical
-- Generado de diagram_08_clinical.puml — NO editar a mano.


CREATE TABLE IF NOT EXISTS "clinical"."family_member_history" (
    "id" uuid NOT NULL,
    "custodian_tenant_id" uuid NOT NULL,
    "patient_profile_id" uuid NOT NULL,
    "relationship_concept_id" uuid NOT NULL,
    "condition_concept_id" uuid,
    "onset_age_years" integer,
    "deceased" boolean,
    "deceased_age_years" integer,
    "note_text" text,
    "recorded_by_user_id" uuid,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_family_member_history" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "clinical"."social_history" (
    "id" uuid NOT NULL,
    "custodian_tenant_id" uuid NOT NULL,
    "patient_profile_id" uuid NOT NULL,
    "category_concept_id" uuid NOT NULL,
    "status_concept_id" uuid,
    "value_concept_id" uuid,
    "value_text" text,
    "quantity_decimal" numeric,
    "unit_concept_id" uuid,
    "effective_at" timestamptz,
    "recorded_by_user_id" uuid,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_social_history" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "clinical"."care_episodes" (
    "id" uuid NOT NULL,
    "patient_profile_id" uuid NOT NULL,
    "tenant_id" uuid NOT NULL,
    "responsible_practitioner_id" uuid,
    "type_concept_id" uuid,
    "status_concept_id" uuid NOT NULL,
    "start_at" timestamptz,
    "end_at" timestamptz,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_care_episodes" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "clinical"."encounters" (
    "id" uuid NOT NULL,
    "patient_profile_id" uuid NOT NULL,
    "episode_id" uuid,
    "tenant_id" uuid NOT NULL,
    "branch_id" uuid,
    "primary_practitioner_id" uuid,
    "class_concept_id" uuid,
    "type_concept_id" uuid,
    "status_concept_id" uuid NOT NULL,
    "reason_text" text,
    "start_at" timestamptz,
    "end_at" timestamptz,
    "appointment_id" uuid,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_encounters" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "clinical"."observations" (
    "id" uuid NOT NULL,
    "custodian_tenant_id" uuid NOT NULL,
    "patient_profile_id" uuid NOT NULL,
    "encounter_id" uuid,
    "based_on_service_request_id" uuid,
    "category_concept_id" uuid,
    "code_concept_id" uuid NOT NULL,
    "status_concept_id" uuid NOT NULL,
    "value_type_concept_id" uuid NOT NULL,
    "value_decimal" numeric,
    "value_integer" bigint,
    "value_boolean" boolean,
    "value_text" text,
    "value_concept_id" uuid,
    "value_datetime" timestamptz,
    "value_date" date,
    "quantity_value" numeric,
    "quantity_unit_concept_id" uuid,
    "range_low_value" numeric,
    "range_high_value" numeric,
    "range_unit_concept_id" uuid,
    "ratio_numerator_value" numeric,
    "ratio_numerator_unit_concept_id" uuid,
    "ratio_denominator_value" numeric,
    "ratio_denominator_unit_concept_id" uuid,
    "sampled_data_json" jsonb,
    "value_file_id" uuid,
    "value_reference_type_concept_id" uuid,
    "value_reference_id" uuid,
    "data_absent_reason_concept_id" uuid,
    "interpretation_concept_id" uuid,
    "method_concept_id" uuid,
    "body_site_concept_id" uuid,
    "specimen_id" uuid,
    "source_device_id" uuid,
    "effective_start_at" timestamptz,
    "effective_end_at" timestamptz,
    "issued_at" timestamptz,
    "recorded_by_user_id" uuid,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_observations" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "clinical"."observation_components" (
    "id" uuid NOT NULL,
    "observation_id" uuid NOT NULL,
    "code_concept_id" uuid NOT NULL,
    "value_type_concept_id" uuid NOT NULL,
    "value_decimal" numeric,
    "value_integer" bigint,
    "value_boolean" boolean,
    "value_text" text,
    "value_concept_id" uuid,
    "value_datetime" timestamptz,
    "quantity_value" numeric,
    "quantity_unit_concept_id" uuid,
    "range_low_value" numeric,
    "range_high_value" numeric,
    "range_unit_concept_id" uuid,
    "data_absent_reason_concept_id" uuid,
    "interpretation_concept_id" uuid,
    "ordinal" integer NOT NULL,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_observation_components" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "clinical"."conditions" (
    "id" uuid NOT NULL,
    "custodian_tenant_id" uuid NOT NULL,
    "patient_profile_id" uuid NOT NULL,
    "encounter_id" uuid,
    "code_concept_id" uuid NOT NULL,
    "category_concept_id" uuid,
    "clinical_status_concept_id" uuid,
    "verification_status_concept_id" uuid,
    "severity_concept_id" uuid,
    "laterality_concept_id" uuid,
    "clinical_course_concept_id" uuid,
    "onset_at" timestamptz,
    "expected_resolution_at" timestamptz,
    "resolved_at" timestamptz,
    "recorded_by_user_id" uuid,
    "note_text" text,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_conditions" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "clinical"."allergy_intolerances" (
    "id" uuid NOT NULL,
    "custodian_tenant_id" uuid NOT NULL,
    "patient_profile_id" uuid NOT NULL,
    "substance_concept_id" uuid NOT NULL,
    "type_concept_id" uuid,
    "category_concept_id" uuid,
    "criticality_concept_id" uuid,
    "clinical_status_concept_id" uuid,
    "verification_status_concept_id" uuid,
    "recorded_by_user_id" uuid,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_allergy_intolerances" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "clinical"."allergy_reactions" (
    "id" uuid NOT NULL,
    "allergy_id" uuid NOT NULL,
    "manifestation_concept_id" uuid NOT NULL,
    "severity_concept_id" uuid,
    "description" text,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_allergy_reactions" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "clinical"."service_requests" (
    "id" uuid NOT NULL,
    "custodian_tenant_id" uuid NOT NULL,
    "patient_profile_id" uuid NOT NULL,
    "encounter_id" uuid,
    "code_concept_id" uuid NOT NULL,
    "category_concept_id" uuid,
    "intent_concept_id" uuid,
    "priority_concept_id" uuid,
    "status_concept_id" uuid NOT NULL,
    "requester_profile_id" uuid,
    "performer_tenant_id" uuid,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_service_requests" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "clinical"."diagnostic_reports" (
    "id" uuid NOT NULL,
    "custodian_tenant_id" uuid NOT NULL,
    "patient_profile_id" uuid NOT NULL,
    "service_request_id" uuid,
    "encounter_id" uuid,
    "code_concept_id" uuid NOT NULL,
    "category_concept_id" uuid,
    "lifecycle_status_concept_id" uuid NOT NULL,
    "current_version_id" uuid,
    "current_released_version_id" uuid,
    "result_release_status_concept_id" uuid,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_diagnostic_reports" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "clinical"."medication_requests" (
    "id" uuid NOT NULL,
    "custodian_tenant_id" uuid NOT NULL,
    "patient_profile_id" uuid NOT NULL,
    "encounter_id" uuid,
    "medication_concept_id" uuid NOT NULL,
    "substance_atc_concept_id" uuid,
    "intent_concept_id" uuid,
    "status_concept_id" uuid NOT NULL,
    "prescriber_profile_id" uuid,
    "dose_text" varchar,
    "route_concept_id" uuid,
    "frequency_text" varchar,
    "quantity_decimal" numeric,
    "unit_concept_id" uuid,
    "valid_from" timestamptz,
    "valid_to" timestamptz,
    "patient_instructions_text" text,
    "indication_condition_id" uuid,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    "signed_at" timestamptz,
    "signed_by_user_id" uuid,
    "issued_at" timestamptz,
    "status_reason_text" text,
    "replaces_request_id" uuid,
    "replaced_by_request_id" uuid,
    "renewed_from_request_id" uuid,
    "issue_idempotency_key" varchar,
    CONSTRAINT "pk_medication_requests" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "clinical"."prescription_signature_policies" (
    "id" uuid NOT NULL,
    "tenant_id" uuid NOT NULL,
    "jurisdiction_code" varchar(16),
    "medication_type_concept_id" uuid,
    "channel_concept_id" uuid,
    "signature_required" boolean NOT NULL,
    "effective_from" timestamptz NOT NULL,
    "effective_to" timestamptz,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_prescription_signature_policies" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "clinical"."medication_records" (
    "id" uuid NOT NULL,
    "custodian_tenant_id" uuid NOT NULL,
    "patient_profile_id" uuid NOT NULL,
    "request_id" uuid,
    "medication_concept_id" uuid NOT NULL,
    "status_concept_id" uuid NOT NULL,
    "record_type_concept_id" uuid,
    "dose_decimal" numeric,
    "unit_concept_id" uuid,
    "administered_at" timestamptz,
    "recorded_by_user_id" uuid,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_medication_records" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "clinical"."procedures" (
    "id" uuid NOT NULL,
    "custodian_tenant_id" uuid NOT NULL,
    "patient_profile_id" uuid NOT NULL,
    "encounter_id" uuid,
    "code_concept_id" uuid NOT NULL,
    "status_concept_id" uuid NOT NULL,
    "performer_profile_id" uuid,
    "performed_at" timestamptz,
    "note_text" text,
    "service_request_id" uuid,
    "parent_procedure_id" uuid,
    "category_concept_id" uuid,
    "status_reason_concept_id" uuid,
    "practice_site_id" uuid,
    "care_space_id" uuid,
    "recorder_profile_id" uuid,
    "outcome_concept_id" uuid,
    "reported_source_concept_id" uuid,
    "occurrence_start_at" timestamptz,
    "occurrence_end_at" timestamptz,
    "recorded_at" timestamptz,
    "follow_up_text" text,
    "operative_report_file_id" uuid,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_procedures" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "clinical"."immunizations" (
    "id" uuid NOT NULL,
    "custodian_tenant_id" uuid NOT NULL,
    "patient_profile_id" uuid NOT NULL,
    "vaccine_concept_id" uuid NOT NULL,
    "status_concept_id" uuid NOT NULL,
    "dose_number" integer,
    "lot_number" varchar,
    "route_concept_id" uuid,
    "administered_at" timestamptz,
    "administered_by_profile_id" uuid,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_immunizations" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "clinical"."appointments" (
    "id" uuid NOT NULL,
    "patient_profile_id" uuid NOT NULL,
    "practitioner_profile_id" uuid,
    "tenant_id" uuid NOT NULL,
    "branch_id" uuid,
    "type_concept_id" uuid,
    "status_concept_id" uuid NOT NULL,
    "channel_concept_id" uuid,
    "start_at" timestamptz NOT NULL,
    "end_at" timestamptz,
    "reason_text" text,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_appointments" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "clinical"."encounter_participants" (
    "id" uuid NOT NULL,
    "encounter_id" uuid NOT NULL,
    "practitioner_profile_id" uuid NOT NULL,
    "participant_role_concept_id" uuid NOT NULL,
    "practitioner_role_assignment_id" uuid,
    "period_start" timestamptz,
    "period_end" timestamptz,
    "is_responsible" boolean,
    "status_concept_id" uuid NOT NULL,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_encounter_participants" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "clinical"."encounter_locations" (
    "id" uuid NOT NULL,
    "encounter_id" uuid NOT NULL,
    "practice_site_id" uuid NOT NULL,
    "clinical_unit_id" uuid,
    "care_space_id" uuid,
    "location_status_concept_id" uuid NOT NULL,
    "period_start" timestamptz,
    "period_end" timestamptz,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_encounter_locations" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "clinical"."observation_performers" (
    "id" uuid NOT NULL,
    "observation_id" uuid NOT NULL,
    "performer_type_concept_id" uuid NOT NULL,
    "performer_id" uuid NOT NULL,
    "performer_role_concept_id" uuid,
    "ordinal" integer NOT NULL,
    "created_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    CONSTRAINT "pk_observation_performers" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "clinical"."observation_reference_ranges" (
    "id" uuid NOT NULL,
    "observation_id" uuid NOT NULL,
    "observation_component_id" uuid,
    "low_value" numeric,
    "high_value" numeric,
    "unit_concept_id" uuid,
    "type_concept_id" uuid,
    "applies_to_concept_id" uuid,
    "age_low_years" numeric,
    "age_high_years" numeric,
    "text" varchar,
    "created_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    CONSTRAINT "pk_observation_reference_ranges" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "clinical"."observation_notes" (
    "id" uuid NOT NULL,
    "observation_id" uuid NOT NULL,
    "author_user_id" uuid NOT NULL,
    "note_text" text NOT NULL,
    "recorded_at" timestamptz NOT NULL,
    CONSTRAINT "pk_observation_notes" PRIMARY KEY ("id")
);
