-- SALUD v4.0.10 · módulo 50 · schema marketing
-- Generado de diagram_50_marketing.puml — NO editar a mano.


CREATE TABLE IF NOT EXISTS "marketing"."segments" (
    "id" uuid NOT NULL,
    "tenant_id" uuid NOT NULL,
    "code" varchar NOT NULL,
    "name" varchar NOT NULL,
    "segment_type_concept_id" uuid NOT NULL,
    "definition_json" jsonb,
    "source_read_model_id" uuid,
    "estimated_size" bigint,
    "last_refreshed_at" timestamptz,
    "state_concept_id" uuid NOT NULL,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_segments" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "marketing"."segment_members" (
    "id" uuid NOT NULL,
    "segment_id" uuid NOT NULL,
    "member_type_concept_id" uuid NOT NULL,
    "member_ref_id" uuid NOT NULL,
    "score" numeric,
    "added_at" timestamptz,
    "status_concept_id" uuid NOT NULL,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_segment_members" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "marketing"."marketing_campaigns" (
    "id" uuid NOT NULL,
    "tenant_id" uuid NOT NULL,
    "code" varchar NOT NULL,
    "name" varchar NOT NULL,
    "campaign_type_concept_id" uuid NOT NULL,
    "objective_concept_id" uuid NOT NULL,
    "channel_concept_id" uuid,
    "segment_id" uuid,
    "budget_amount" numeric,
    "currency_concept_id" uuid,
    "ad_campaign_ref_id" uuid,
    "promotion_id" uuid,
    "start_at" timestamptz,
    "end_at" timestamptz,
    "owner_user_id" uuid,
    "status_concept_id" uuid NOT NULL,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    "governance_scope_concept_id" uuid,
    "requires_explicit_publish" boolean,
    "published_version" integer,
    "published_at" timestamptz,
    "published_by_user_id" uuid,
    "approved_content_hash" varchar,
    "approved_audience_hash" varchar,
    "cancellation_reason" varchar,
    "cancelled_at" timestamptz,
    "cancelled_by_user_id" uuid,
    CONSTRAINT "pk_marketing_campaigns" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "marketing"."campaign_members" (
    "id" uuid NOT NULL,
    "campaign_id" uuid NOT NULL,
    "member_type_concept_id" uuid NOT NULL,
    "member_ref_id" uuid NOT NULL,
    "member_status_concept_id" uuid NOT NULL,
    "added_at" timestamptz,
    "responded_at" timestamptz,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    "source_segment_member_id" uuid,
    "first_dispatch_id" uuid,
    "last_dispatch_id" uuid,
    "total_dispatches" integer,
    CONSTRAINT "pk_campaign_members" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "marketing"."content_templates" (
    "id" uuid NOT NULL,
    "tenant_id" uuid NOT NULL,
    "code" varchar NOT NULL,
    "name" varchar NOT NULL,
    "channel_concept_id" uuid NOT NULL,
    "language_concept_id" uuid,
    "subject" varchar,
    "body_template" text,
    "variables_json" jsonb,
    "messaging_template_id" uuid,
    "version" integer NOT NULL,
    "status_concept_id" uuid NOT NULL,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_content_templates" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "marketing"."journeys" (
    "id" uuid NOT NULL,
    "tenant_id" uuid NOT NULL,
    "code" varchar NOT NULL,
    "name" varchar NOT NULL,
    "entry_trigger_concept_id" uuid NOT NULL,
    "entry_segment_id" uuid,
    "goal_metric_concept_id" uuid,
    "definition_json" jsonb,
    "state_concept_id" uuid NOT NULL,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_journeys" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "marketing"."journey_steps" (
    "id" uuid NOT NULL,
    "journey_id" uuid NOT NULL,
    "step_code" varchar NOT NULL,
    "step_type_concept_id" uuid NOT NULL,
    "channel_concept_id" uuid,
    "content_template_id" uuid,
    "wait_duration_minutes" integer,
    "condition_json" jsonb,
    "next_step_id" uuid,
    "branch_step_id" uuid,
    "ordinal" integer,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_journey_steps" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "marketing"."journey_enrollments" (
    "id" uuid NOT NULL,
    "journey_id" uuid NOT NULL,
    "member_type_concept_id" uuid NOT NULL,
    "member_ref_id" uuid NOT NULL,
    "current_step_id" uuid,
    "status_concept_id" uuid NOT NULL,
    "entered_at" timestamptz,
    "exited_at" timestamptz,
    "exit_reason_concept_id" uuid,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_journey_enrollments" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "marketing"."tracked_links" (
    "id" uuid NOT NULL,
    "campaign_id" uuid,
    "code" varchar NOT NULL,
    "target_url" text NOT NULL,
    "utm_source" varchar,
    "utm_medium" varchar,
    "utm_campaign" varchar,
    "utm_content" varchar,
    "click_count" bigint,
    "state_concept_id" uuid NOT NULL,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_tracked_links" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "marketing"."marketing_touchpoints" (
    "id" uuid NOT NULL,
    "campaign_id" uuid,
    "journey_id" uuid,
    "tracked_link_id" uuid,
    "member_type_concept_id" uuid NOT NULL,
    "member_ref_id" uuid NOT NULL,
    "touch_type_concept_id" uuid NOT NULL,
    "channel_concept_id" uuid NOT NULL,
    "content_template_id" uuid,
    "metadata_json" jsonb,
    "occurred_at" timestamptz,
    "recorded_at" timestamptz NOT NULL,
    "recorded_by_user_id" uuid,
    "dispatch_id" uuid,
    "dispatch_recipient_id" uuid,
    "notification_request_id" uuid,
    "notification_delivery_id" uuid,
    "tracking_event_id" uuid,
    CONSTRAINT "pk_marketing_touchpoints" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "marketing"."attribution_touches" (
    "id" uuid NOT NULL,
    "conversion_ref_type" varchar NOT NULL,
    "conversion_ref_id" uuid NOT NULL,
    "marketing_touchpoint_id" uuid NOT NULL,
    "attribution_model_concept_id" uuid NOT NULL,
    "weight" numeric NOT NULL,
    "attributed_value" numeric,
    "currency_concept_id" uuid,
    "position_concept_id" uuid,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid,
    "updated_by_user_id" uuid,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_attribution_touches" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "marketing"."campaign_dispatches" (
    "id" uuid NOT NULL,
    "tenant_id" uuid,
    "campaign_id" uuid NOT NULL,
    "schedule_id" uuid,
    "journey_id" uuid,
    "journey_step_id" uuid,
    "occurrence_key" varchar NOT NULL,
    "planned_at" timestamptz NOT NULL,
    "audience_snapshot_at" timestamptz,
    "started_at" timestamptz,
    "finished_at" timestamptz,
    "status_concept_id" uuid NOT NULL,
    "source_concept_id" uuid NOT NULL,
    "content_template_id" uuid NOT NULL,
    "content_template_version" integer NOT NULL,
    "content_hash" varchar NOT NULL,
    "audience_definition_hash" varchar NOT NULL,
    "total_candidates" bigint NOT NULL,
    "total_eligible" bigint NOT NULL,
    "total_suppressed" bigint NOT NULL,
    "total_requests" bigint NOT NULL,
    "total_accepted" bigint NOT NULL,
    "total_delivered" bigint NOT NULL,
    "total_seen" bigint NOT NULL,
    "total_read" bigint NOT NULL,
    "total_failed" bigint NOT NULL,
    "total_cancelled" bigint NOT NULL,
    "idempotency_key" varchar NOT NULL,
    "authorized_by_user_id" uuid NOT NULL,
    "authorization_snapshot_json" jsonb NOT NULL,
    "failure_code" varchar,
    "failure_detail" text,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid NOT NULL,
    "updated_by_user_id" uuid NOT NULL,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_campaign_dispatches" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "marketing"."campaign_dispatch_recipients" (
    "id" uuid NOT NULL,
    "dispatch_id" uuid NOT NULL,
    "member_type_concept_id" uuid NOT NULL,
    "member_ref_id" uuid NOT NULL,
    "recipient_endpoint_id" uuid,
    "recipient_user_id" uuid,
    "channel_id" uuid NOT NULL,
    "language_concept_id" uuid,
    "timezone_name" varchar,
    "consent_id" uuid,
    "consent_status_concept_id" uuid NOT NULL,
    "preference_snapshot_json" jsonb,
    "eligibility_status_concept_id" uuid NOT NULL,
    "suppression_reason_concept_id" uuid,
    "suppression_detail" varchar,
    "scheduled_at" timestamptz NOT NULL,
    "notification_request_id" uuid,
    "current_delivery_id" uuid,
    "current_status_concept_id" uuid NOT NULL,
    "idempotency_key" varchar NOT NULL,
    "snapshot_json" jsonb NOT NULL,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid NOT NULL,
    "updated_by_user_id" uuid NOT NULL,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_campaign_dispatch_recipients" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "marketing"."campaign_schedules" (
    "id" uuid NOT NULL,
    "tenant_id" uuid,
    "campaign_id" uuid,
    "journey_id" uuid,
    "schedule_type_concept_id" uuid NOT NULL,
    "timezone_name" varchar NOT NULL,
    "scheduled_once_at" timestamptz,
    "cron_expression" varchar,
    "recurrence_rule_json" jsonb,
    "valid_from" timestamptz NOT NULL,
    "valid_until" timestamptz,
    "allowed_weekdays_json" jsonb,
    "allowed_time_window_json" jsonb,
    "missed_run_policy_concept_id" uuid NOT NULL,
    "overlap_policy_concept_id" uuid NOT NULL,
    "next_run_at" timestamptz,
    "last_run_at" timestamptz,
    "max_occurrences" integer,
    "completed_occurrences" integer NOT NULL,
    "status_concept_id" uuid NOT NULL,
    "schedule_version" integer NOT NULL,
    "published_content_hash" varchar NOT NULL,
    "published_audience_hash" varchar NOT NULL,
    "authorized_by_user_id" uuid NOT NULL,
    "authorized_at" timestamptz NOT NULL,
    "authorization_snapshot_json" jsonb NOT NULL,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "created_by_user_id" uuid NOT NULL,
    "updated_by_user_id" uuid NOT NULL,
    "row_version" integer NOT NULL DEFAULT 1,
    CONSTRAINT "pk_campaign_schedules" PRIMARY KEY ("id")
);
