/**
 * Catálogo de sub-códigos de negocio del carril `pharma_lab` (spec 5267-5738).
 *
 * Cada miembro es una situación de negocio distinta que puede producir el mismo
 * `ErrorCode` genérico (CONFLICT, NOT_FOUND, PRECONDITION_FAILED, ...) por
 * caminos diferentes. El cliente puede ramificar sobre `reason` sin parsear el
 * `message`, que sigue siendo sólo para humanos.
 */
export enum PharmaLabErrorReason {
  // Laboratorio y organización
  LAB_NOT_FOUND = 'LAB_NOT_FOUND',
  LAB_NOT_ACTIVE = 'LAB_NOT_ACTIVE',
  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  TENANT_ALREADY_LAB = 'TENANT_ALREADY_LAB',
  STAFF_ALREADY_LINKED = 'STAFF_ALREADY_LINKED',
  STAFF_NOT_FOUND = 'STAFF_NOT_FOUND',
  USER_ACCOUNT_NOT_FOUND = 'USER_ACCOUNT_NOT_FOUND',

  // Visitadores médicos
  VISITOR_ALREADY_REGISTERED = 'VISITOR_ALREADY_REGISTERED',
  VISITOR_INTERNAL_CODE_TAKEN = 'VISITOR_INTERNAL_CODE_TAKEN',
  VISITOR_ALREADY_UNLINKED = 'VISITOR_ALREADY_UNLINKED',
  VISITOR_ALREADY_LINKED = 'VISITOR_ALREADY_LINKED',
  VISITOR_PROFILE_NOT_FOUND = 'VISITOR_PROFILE_NOT_FOUND',
  VISITOR_PRODUCT_NOT_IN_LAB_CATALOG = 'VISITOR_PRODUCT_NOT_IN_LAB_CATALOG',
  VISITOR_LINK_NOT_ACTIVE = 'VISITOR_LINK_NOT_ACTIVE',
  VISITOR_NOT_FOUND_IN_LAB = 'VISITOR_NOT_FOUND_IN_LAB',

  // Catálogo de productos y material informativo
  PRODUCT_STATUS_TRANSITION_NOT_ALLOWED = 'PRODUCT_STATUS_TRANSITION_NOT_ALLOWED',
  PRODUCT_INDICATION_REQUIRES_APPROVAL = 'PRODUCT_INDICATION_REQUIRES_APPROVAL',
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  MATERIAL_APPROVED_IMMUTABLE = 'MATERIAL_APPROVED_IMMUTABLE',
  MATERIAL_NOT_IN_DRAFT = 'MATERIAL_NOT_IN_DRAFT',
  MATERIAL_NO_ASSETS_TO_REVIEW = 'MATERIAL_NO_ASSETS_TO_REVIEW',
  MATERIAL_NOT_IN_REVIEW = 'MATERIAL_NOT_IN_REVIEW',
  MATERIAL_DECISION_INVALID = 'MATERIAL_DECISION_INVALID',
  MATERIAL_NOT_FOUND = 'MATERIAL_NOT_FOUND',
  MATERIAL_NOT_APPROVED_FOR_SOCIAL_POST = 'MATERIAL_NOT_APPROVED_FOR_SOCIAL_POST',
  MATERIAL_NOT_APPROVED_FOR_SHARING = 'MATERIAL_NOT_APPROVED_FOR_SHARING',
  MATERIAL_NOT_VALID_ON_VISIT_DATE = 'MATERIAL_NOT_VALID_ON_VISIT_DATE',

  // Documentos regulatorios
  DOCUMENT_INVALIDATED_NO_NEW_VERSIONS = 'DOCUMENT_INVALIDATED_NO_NEW_VERSIONS',
  DOCUMENT_ALREADY_INVALIDATED = 'DOCUMENT_ALREADY_INVALIDATED',
  DOCUMENT_VERSION_NOT_FOUND = 'DOCUMENT_VERSION_NOT_FOUND',
  DOCUMENT_NOT_FOUND = 'DOCUMENT_NOT_FOUND',

  // Farmacovigilancia
  ADVERSE_EVENT_REPORT_STATUS_TRANSITION_NOT_ALLOWED = 'ADVERSE_EVENT_REPORT_STATUS_TRANSITION_NOT_ALLOWED',
  ADVERSE_EVENT_CASE_CODE_EXHAUSTED = 'ADVERSE_EVENT_CASE_CODE_EXHAUSTED',
  ADVERSE_EVENT_REPORT_NOT_FOUND = 'ADVERSE_EVENT_REPORT_NOT_FOUND',

  // Publicaciones sociales / científicas
  POST_SUBMISSION_NOT_FOUND = 'POST_SUBMISSION_NOT_FOUND',
  POST_SUBMISSION_ALREADY_RESOLVED = 'POST_SUBMISSION_ALREADY_RESOLVED',
  POST_SUBMISSION_DECISION_INVALID = 'POST_SUBMISSION_DECISION_INVALID',

  // Contabilidad / analítica
  JOURNAL_TRANSACTION_NOT_FOUND = 'JOURNAL_TRANSACTION_NOT_FOUND',

  // Avisos
  NOTICE_NOT_FOUND = 'NOTICE_NOT_FOUND',

  // Encuestas post-visita
  SURVEY_ALREADY_CLOSED = 'SURVEY_ALREADY_CLOSED',
  SURVEY_RESPONSE_NOT_FOUND = 'SURVEY_RESPONSE_NOT_FOUND',
  SURVEY_NOT_FOUND = 'SURVEY_NOT_FOUND',
  SURVEY_RESPONSE_ALREADY_SUBMITTED = 'SURVEY_RESPONSE_ALREADY_SUBMITTED',
  SURVEY_REQUIRED_ANSWERS_MISSING = 'SURVEY_REQUIRED_ANSWERS_MISSING',
  SURVEY_ANSWER_QUESTION_MISMATCH = 'SURVEY_ANSWER_QUESTION_MISMATCH',
  SURVEY_NOT_FOUND_IN_LAB = 'SURVEY_NOT_FOUND_IN_LAB',

  // Agenda de visitas del doctor
  DOCTOR_AGENDA_NOT_CONFIGURED = 'DOCTOR_AGENDA_NOT_CONFIGURED',
  VISIT_BLOCK_TARGET_MISSING = 'VISIT_BLOCK_TARGET_MISSING',
  VISIT_BLOCK_NOT_FOUND = 'VISIT_BLOCK_NOT_FOUND',
  VISIT_BLOCK_ALREADY_LIFTED = 'VISIT_BLOCK_ALREADY_LIFTED',
  VISIT_MIN_NOTICE_NOT_MET = 'VISIT_MIN_NOTICE_NOT_MET',
  VISIT_DURATION_EXCEEDS_MAX = 'VISIT_DURATION_EXCEEDS_MAX',
  VISIT_OUTSIDE_WINDOWS = 'VISIT_OUTSIDE_WINDOWS',
  VISIT_MODALITY_MISMATCH = 'VISIT_MODALITY_MISMATCH',
  VISIT_DAILY_QUOTA_REACHED = 'VISIT_DAILY_QUOTA_REACHED',
  VISIT_SLOT_OVERLAPS_REQUEST = 'VISIT_SLOT_OVERLAPS_REQUEST',
  VISIT_WINDOW_FULL = 'VISIT_WINDOW_FULL',
  VISIT_SLOT_OVERLAPS_CLINICAL_AGENDA = 'VISIT_SLOT_OVERLAPS_CLINICAL_AGENDA',
  VISIT_BLOCKED_BY_DOCTOR = 'VISIT_BLOCKED_BY_DOCTOR',
  VISIT_VISITOR_SPECIALTY_NOT_ACCEPTED = 'VISIT_VISITOR_SPECIALTY_NOT_ACCEPTED',
  VISIT_WINDOW_TIME_RANGE_INVALID = 'VISIT_WINDOW_TIME_RANGE_INVALID',
  VISIT_WINDOWS_OVERLAP = 'VISIT_WINDOWS_OVERLAP',

  // Solicitudes de visita (ciclo de vida)
  VISIT_REQUEST_NOT_FOUND = 'VISIT_REQUEST_NOT_FOUND',
  VISIT_REQUEST_FINAL_STATE = 'VISIT_REQUEST_FINAL_STATE',
  VISIT_REQUEST_TRANSITION_NOT_ALLOWED = 'VISIT_REQUEST_TRANSITION_NOT_ALLOWED',
  VISIT_RESCHEDULE_CUTOFF_PASSED = 'VISIT_RESCHEDULE_CUTOFF_PASSED',
  VISIT_TOPIC_PRODUCT_NOT_AUTHORIZED = 'VISIT_TOPIC_PRODUCT_NOT_AUTHORIZED',
  VISIT_TOPIC_PRODUCT_BLOCKED = 'VISIT_TOPIC_PRODUCT_BLOCKED',

  // Registro, confirmación y calificación de visitas
  VISIT_RECORD_NOT_FOUND = 'VISIT_RECORD_NOT_FOUND',
  VISIT_RECORD_NOT_YET_RECORDABLE = 'VISIT_RECORD_NOT_YET_RECORDABLE',
  VISIT_RECORD_ALREADY_EXISTS = 'VISIT_RECORD_ALREADY_EXISTS',
  VISIT_RECORD_ALREADY_RESOLVED = 'VISIT_RECORD_ALREADY_RESOLVED',
  VISIT_NOT_COMPLETED_FOR_RATING = 'VISIT_NOT_COMPLETED_FOR_RATING',
  VISIT_RATING_ALREADY_EXISTS = 'VISIT_RATING_ALREADY_EXISTS',
}
